### ISSUE TITLE
Request [GLSL,MSL,HLSL]: Support for new SPV_EXT_fragment_shader_interlock 

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#1002]
Hi,
after my last year request (https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/27) to expose ROV functionality, finally new Vulkan 1.1.110 got released with VK_EXT_fragment_shader_interlock support and associated SPIR-V ext.: SPV_EXT_fragment_shader_interlock..
right now SPIR-V ext is here:
https://github.com/KhronosGroup/SPIRV-Registry/pull/31/commits/065daf4d19a4be2da7dc78d525768668d4188a68

As all other modern APIs (Metal2 and D3D12 and even GL4) support this functionality to various degrees (I mean for ex. the interactions with Variable rate shading are missing in Metal not sure how interacts with new D3D12 VRS support) would be nice if SPIRV-Cross can support it in all shading languages: GLSL output (it's the same existing https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_fragment_shader_interlock.txt), Metal and HLSL..

EDIT: forgot to note we have drv support from NV (0-day) and even Mesa Anvil patches for Intel: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/989

thanks..

**Comment by oscarbg** [comment]
Forgot to say MSL support will be the most useful/interesting IMHO by far, for MoltenVK..

**Comment by HansKristian-Work** [comment]
This one might be complicated ... Trying to figure out how this can be implemented.

GLSL:
- The SPIR-V spec states that begin/end interlocked must be dynamically executed once, but the GLSL extension is far more strict, stating that begin/end must happen in main, outside control flow, and cannot be used after a return.

**Comment by Degerz** [comment]
For HLSL, I believe it's per-sample interlocks from other people's testing. 

Am wondering if it's also possible to map SPIR-V interlocks to MSL's `[[color(m)]]` attribute qualifier because in MSL you can directly access the colour attachments inside a fragment shader on iOS devices. I assume this will be either tricky without some special considerations as to how image atomics are used in SPIR-V or impossible sincetheir programming models are incompatible.

**Comment by oscarbg** [comment]
@HansKristian-Work thanks for giving an in depth look..
Regarding GLSL: yes SPIR-V seems more general.. obviously if SPIR-V is generated from GLSL shouldn't be a problem.. in other cases printing an "unsupported" message should be ok..
In other cases really no idea.. 
sad hearing MSL might be difficult to support and for HLSL I was simply thinking about per-pixel support..
