### ISSUE TITLE
[GLSL, MSL, CPP] variables are sometimes not declared in generated code

### ISSUE THREAD

**Issue by MichaelE1000** [KhronosGroup/SPIRV-Cross#1003]
I tried to cross compile a kernel from OpenCL C to SPIR-V (with clspv) and then to MSL but I came across an issue where variables where not declared anymore if a block had already been used earlier in the code generation.

OpenCL C source code: [https://paste.ubuntu.com/p/rjWZfDStnp/](https://paste.ubuntu.com/p/rjWZfDStnp/)
SPIR-V code generated with clspv (after conversion with spirv-dis: [https://paste.ubuntu.com/p/SCsbg2tBXJ/](https://paste.ubuntu.com/p/SCsbg2tBXJ/)
Generated GLSL code: [https://paste.ubuntu.com/p/dx6MvXt3XR/](https://paste.ubuntu.com/p/dx6MvXt3XR/)

If you look at line 81, the variable "_39" is used although it is not declared in this scope.
The same symptom also occurs when using the MSL and CPP generation. (Which is not surprising since all these implementations are just specialising the CompilerGLSL class.)

I had a look at the code and I think that the variables are not managed per scope level, meaning once they are declared the generator thinks that they are always available.
I tried to fix this and got working results with these changes here: [Patch Proposal](https://github.com/MichaelE1000/SPIRV-Cross/commit/c4f8cde5e4f22fdc045aae0d9ba83e37df639769)

I would appreciate if you could give me some feedback if my analysis is correct and how this problem should be solved in the code base. I didn't create a pull request since I'm not familiar enough with the code base and would appreciate some feedback first. Thanks!

**Comment by HansKristian-Work** [comment]
There is something very fishy about this CFG, I'm not sure it's valid structured SPIR-V to begin with. It passes spirv-val, but I can't see how. Block %36 is branched to from different scopes without any merge operation, and that doesn't seem right.

Generally, we use the CFG to figure out in which scope to place variables. Declaring them twice like this might work around this particular case, but it feels like a hack with unknown consequences, and I'll try to understand what can be done about this control flow.

**Comment by HansKristian-Work** [comment]
Added a PR which fixes the issue for this shader.

**Comment by alan-baker** [comment]
This looks like a bug in clspv to be honest. It's misidentifying where to put selection merges due to some faulty logic.

**Comment by alan-baker** [comment]
Also worth noting the validator doesn't flag this because it's not fully nailed down where selection merges are required. See SPIR internal issue 115.

**Comment by MichaelE1000** [comment]
@HansKristian-Work  I tried your pull request, it solves the issue/symptom.

@alan-baker I agree this could of course be source of the problem. Any ideas what should be done to completely resolve it?

**Comment by alan-baker** [comment]
Can you open a bug on clspv with the OpenCL C? I'll try to get a fix for it soon.

**Comment by HansKristian-Work** [comment]
Merged the "fix" as it was not particularly invasive. Will be necessary to clarify if this is actually legal SPIR-V though.

**Comment by alan-baker** [comment]
https://github.com/google/clspv/pull/378 addresses this in clspv.

**Comment by HansKristian-Work** [comment]
Thanks. Guess there is nothing more for me to do here.
