### ISSUE TITLE
[MSL] Support for new Metal Shading Language 2.2 features..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#1004]
Hi,
we have Metal news from WWDC19.. 

there is new Metal 3.0 API: (link: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) 
and new Metal 2.2 Shading language: (link: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) 

from quick inspection from Metal 2.2 SL seems we have now support for:
*int64 (still not FP64 support!!)
*barycentrics
*primitive_id
*Fragment shader inputs:thread_index_in_{quadgroup,simdgroup} & threads_per_simdgroup
(this will be nice to fix issues like https://github.com/KhronosGroup/MoltenVK/issues/629)
*MacOS only: min_lod_clamp() as you can specify LOD range for a sampler..

all this should be supported on Vulkan (so SPIR-V also) either as optional features or extensions..
so would be nice for SPIRV-Cross to support it..
also Metal 3.0 API PDF notes "Texture swizzle", may be nice if much of the current hackery SPIRV-
Cross does for MSL support can be avoided..

to end no pressure&hurry to support these.. this will be in beta as you know until late September..
just wanted to post now that I have taken some look at it before it goes out of my mind.. :-))

thanks..

**Comment by oscarbg** [comment]
I posted a MoltenVK issue with some more info on Metal 3.0 features: maybe I missed someone useful for SPIRV-Cross too:
https://github.com/KhronosGroup/MoltenVK/issues/631

**Comment by cdavis5e** [comment]
Another new feature: `calculate_clamped_lod()` and `calculate_unclamped_lod()`. We can finally implement `OpImageQueryLod`.

The iOS headers also have yet another new feature: sparse textures. Now we can implement `OpImageSparseXxx`, at least on iOS. (When's this coming to Mac? I want my `D3D_FEATURE_LEVEL_12_0` now, dammit!)

iOS also gained support for SIMD-groups, so now we can actually have subgroup support on iOS.

Packed vectors are now a first class type. This was a long-standing request of Vulkan Portability.

There also seems to be new support for variable-rate shading, so now `SPV_EXT_fragment_invocation_density` should be possible.

**Comment by HansKristian-Work** [comment]
Oh, QueryLod, nice. MSL is catching up. I would prefer if separate issues are filed for specific MSL features we'd like to have implemented. Meta-issues like these are not all that actionable.

**Comment by cdavis5e** [comment]
I have filed the following issues:

#1009 
#1010 
#1011 
#1012 
#1013 
#1014 
#1015

**Comment by oscarbg** [comment]
nice findings @cdavis5e..
any reason to not open separate issues for:
*barycentrics: should be mappable to SPV_NV_fragment_shader_barycentric and/or  SPV_AMD_shader_explict_vertex_parameter?
*primitive_id: -> SPIR-V PrimitiveId?

**Comment by HansKristian-Work** [comment]
@cdavis5e Thanks for making the issues. If you're picking an issue up, please add a comment to it so we don't duplicate work. I'll start working on the features next week if I don't see anything.

**Comment by HansKristian-Work** [comment]
I think we've covered all of these now, closing.

**Comment by oscarbg** [comment]
yep.. thanks!
