### ISSUE TITLE
[MSL] Support SPV_NV_fragment_shader_barycentric in MSL 2.2

### ISSUE THREAD

**Issue by cdavis5e** [KhronosGroup/SPIRV-Cross#1010]
MSL 2.2 adds new builtins for use from fragment shaders, giving barycentric coordinates for a fragment relative to the primitive it was rasterized from, as well as the primitive's ID. We can use these new builtins to support the SPIR-V `PrimitiveId` builtin in a fragment shader, as well as the `SPV_NV_fragment_shader_barycentric` extension. It is likely that Khronos will standardize a vendor-neutral barycentric coordinate extension in the future; when they do, we'll be well-positioned to support that as well. Unfortunately, barycentrics in Metal only support `center` interpolation; no `centroid` or `sample` interpolation here. We won't be able to support the extended barycentrics in the `SPV_AMD_shader_explicit_vertex_parameter`.

**Comment by HansKristian-Work** [comment]
This SPIR-V extension also adds support for per-vertex attributes, but I don't think that's reasonable to support as well. MSL seems to assume you'll pull in primitives from a buffer with primitive_id here. I think it's fine to just support the barycentric part.
