### ISSUE TITLE
[MSL] Implement OpImageQueryLod using new MSL 2.2 functionality

### ISSUE THREAD

**Issue by cdavis5e** [KhronosGroup/SPIRV-Cross#1013]
MSL 2.2 adds support for two new methods on textures, `calculate_clamped_lod()` and `calculate_unclamped_lod()`, which return the implicit LOD that would be used for a sample operation at the given coordinates. It should be possible to use these two new methods to finally implement `OpImageQueryLod`.

**Comment by HansKristian-Work** [comment]
I can't find this in the latest MSL 2.2 specification.

**Comment by billhollings** [comment]
> I can't find this in the latest MSL 2.2 specification.

https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

**Comment by HansKristian-Work** [comment]
Right, I have the 2.2 spec, but I can't find any mention of these functions *in* the spec. Are they in the headers, but not spec yet for some reason?

**Comment by billhollings** [comment]
D'oh! Sorry...I hastily misread your request as just looking **_for_** the spec...not **_at_** it!  🤦🏻‍♂️

**Comment by cdavis5e** [comment]
They are in the headers. From `<metal_texture>`, there are two new methods:

```c++
// On 2D texture types
float calculate_clamped_lod(sampler s, float2 coord);
float calculate_unclamped_lod(sampler s, float2 coord);
// On 3D/cube texture types
float calculate_clamped_lod(sampler s, float3 coord);
float calculate_unclamped_lod(sampler s, float3 coord);
```
