### ISSUE TITLE
Converting SPIR-V to MSL leads to use of undeclared variable

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1033]
I was trying to convert SPIR-V to MSL using SPIRV-Cross and found that when a GLSL shader has variable declarations inside a switch statement like the following:
```glsl

// GLSL:
switch(0)
 {
   case 0:
     int a = 1;   
   case 1:
     int b = 1;
   case 2:
     int c = 1;  
 }
```

SPIRV-Cross seems to move all declarations in each case into the first case of the switch statement leading to an invalid shader:
```glsl
 // MSL:
 switch (0)
   {
       case 0:
       {
           int a = 1;
           int b = 1;
           int c = 1;
           break;
       }
       case 1:
       {
           b = 1; // error: use of undeclared identifier 'b'
           c = 1;
           break;
       }
       case 2:
       {
           c = 1;
           break;
       }
   }
```
<br />

Versions: 
- SPIRV-Cross: built from source (commit `05ea055096df8b7b8b3e3f7e121279acf83f74c0`)
- glslangValidator: Glslang Version: 7.12.3226

<br />

Steps to reproduce:
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Convert the SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`

Note that before running SPIRV-Cross, I also used `spirv-val` to check that the SPIR-V produced by glslangValidator is valid.

<br />

[This archive](https://github.com/KhronosGroup/SPIRV-Cross/files/3306526/Archive.zip) contains the original fragment shader, the associated SPIR-V, and MSL shader.

<br />

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
Pretty sure this is due to lack of fall-through case handling, but I'll need to reproduce first.

**Comment by HansKristian-Work** [comment]
This was kind of fixed two weeks ago, but the code-gen is still duplicated, so that needs to be fixed.
