### ISSUE TITLE
Overriding argument buffer bindings

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/SPIRV-Cross#1037]
Currently, descriptor set number X is always mapped to "[[buffer(X)]]" in Metal. We need an ability to change that.

The simplest approach could be defining a constant like `kArgumentBufferBinding`, such that an override for "set(X) binding(kArgumentBufferBinding)" points to the binding of the argument buffer itself instead of changing the index of its contents (which is what overrides for  set(X) do today if X is ends up being an argument buffer).

**Comment by HansKristian-Work** [comment]
To be clear, you want to be able to bind descriptor set N's argument to potentially a buffer(M), and not always a 1:1 mapping between set and buffer(N)? I guess this is to better handle cases where there are gaps in the descriptor sets?

**Comment by kvark** [comment]
@HansKristian-Work correct. This is needed for multiple things, e.g. the gaps may appear due to the stage flags of descriptor sets. In general, there is no reason to have a model where all the bindings can be remapped (and even *have to* be remapped, like the elements of an argument buffer) *except*  the argument buffers themselves.

**Comment by HansKristian-Work** [comment]
Alright. Shouldn't be hard to add.
