### ISSUE TITLE
MSL: using unpackUnorm4x8 as an argument to outerProduct built-ins fails on macOS 10.14

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1049]
On MacOS 10.14, I tried to convert SPIR-V to MSL and found an issue that when using the unpackUnorm4x8 as the argument of the outerProduct function, the MSL compiler gives the following error: 

```
result.msl:14:16: error: use of undeclared identifier 'outerProduct'
    float4 a = outerProduct(unpack_unorm4x8_to_float(80045u), float2(1.0))[1];
               ^
```

The GLSL fragment shader:
```GLSL
void main()
{
 vec4 a = outerProduct(unpackUnorm4x8(80045u), vec2(1.0))[1]; 
 _GLF_color = vec4(1.0);
}
```

MSL obtained by SPIRV-Cross:

```GLSL
fragment main0_out main0()
{
    main0_out out = {};
    float4 a = outerProduct(unpack_unorm4x8_to_float(80045u), float2(1.0))[1];
    out._GLF_color = float4(1.0);
    return out;
}
```

**Versions:**
- SPIRV-Cross: git-8ee8e60f70f937c72379ab1fc404a1c36d660a31 (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command glslangValidator -V sample.frag -o sample.spv
- Convert the SPIR-V to MSL using SPIRV-Cross with the command spirv-cross --msl sample.spv --output result.msl
- Build a Metal library with the command xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl

Note that before running SPIRV-Cross, I also used spirv-val to check that the SPIR-V produced by glslangValidator is valid.

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3339233/Archive.zip) contains the original fragment shader, the associated SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by cdavis5e** [comment]
The problem is that `OpOuterProduct` itself is not supported by the MSL backend. It winds up delegating back to the GLSL backend, which emits a call to `outerProduct()`, which doesn't exist in MSL. I don't think there's anything in the Metal standard library that corresponds directly to this, which is part of why it's unimplemented. The other part is, I suspect that this operation is fairly rare, so it hasn't come up before.

**Comment by HansKristian-Work** [comment]
Right, I don't think it's implemented at all in MSL yet, I thought it was, but I guess we didn't have any test coverage for it. Should be easy to add though. I'll get to it on Monday.
