### ISSUE TITLE
bug : reference variable outside of its scope

### ISSUE THREAD

**Issue by zhaijialong** [KhronosGroup/SPIRV-Cross#1054]
Hi, @Themaister .

Here is a link which shows the bug :
http://shader-playground.timjones.io/f0b1e88a4c165535cf816bb62d3e5ec7

In the generated glsl code ,
```
{
      //....
      vec3 _632 = mix(_435.xyz, textureLod(SPIRV_Cross_Combinedtex_ColorMapsam_PointClamp, _604.xy, 0.0).xyz, vec3((_604.z > 0.0) ? _620 : (_620 * clamp(4.0 * (1.0 - _604.w), 0.0, 1.0))));
}
_676 = vec4(_632.x, _632.y, _632.z, _435.w);
```

`_676` references the `_632` outside it scope, that results in a compilation error for the glsl.

The spir-v code and it source HLSL both work well for Vulkan and D3D, so maybe it's a bug in spirv-cross ?

Thanks.

**Comment by HansKristian-Work** [comment]
I've identified the bug, but this is a really difficult edge case where the shader is abusing how scopes work. The inner part of the else {} block dominates the outside of the if () / else() construct, since the if () part breaks out.

**Comment by zhaijialong** [comment]
Yes, the generated glsl has lots of `if(...) { break; }` which doesn't exist in the original hlsl code, maybe it's due to DXC -O3 optimize.

Will we have a fix for this bug soon ? Thanks so much for your great work, @HansKristian-Work .
