### ISSUE TITLE
MSL: using the variable identifier as an argument to refract built-ins fails on macOS 10.14

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1056]
On MacOS 10.14, I tried to convert SPIR-V to MSL and found an issue that when using a float variable identifier as the argument of a refract function, the MSL compiler gives the following error:

```
result.msl:15:15: error: no matching function for call to 'refract'
    float b = refract(1.0, 1.0, a);
              ^~~~~~~
```

The GLSL fragment shader:
```GLSL
void main()
{
    float a = 1.0;
    float b = refract(1.0, 1.0, a);
    _GLF_color = vec4(10.0);
}
```

The MSL shader obtained by SPIRV-Cross:

```GLSL
fragment main0_out main0()
{
    main0_out out = {};
    float a = 1.0;
    float b = refract(1.0, 1.0, a);
    out._GLF_color = float4(10.0);
    return out;
}
```

**Versions**:

- SPIRV-Cross: git-41399fc899b9b941bc17810a72d9aa8750bb18e9 (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Convert the SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`
- Build a Metal library with the command `xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl`

Note that before running SPIRV-Cross, I also used spirv-val to check that the SPIR-V produced by glslangValidator is valid.

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3351168/Archive.zip) contains the original fragment shader, the associated SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by cdavis5e** [comment]
That is because MSL lacks overloads of `refract()` for scalars. Most of the functions in `<metal_geometric>`, like the `length()` function (as you discovered in #1047), lack scalar overloads.

**Comment by HansKristian-Work** [comment]
Odd that this is even allowed in SPIR-V, another easy fix I guess ...
