### ISSUE TITLE
Shaders with SPV debug info

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#1057]
How to deal with SPV debug info? Maybe let the parser keep the debug info, as well as 'OpLine' and 'OpNoLine', so that this parser could be used for other purposes.

[SPV debug info](https://www.khronos.org/registry/spir-v/specs/unified1/DebugInfo.html#_introduction)

**Comment by HansKristian-Work** [comment]
SPIRV-Cross has an option to support emitting source-relevant OpLine statements already. See --emit-line-directives in the CLI.

I'm not sure how valuable it is to capture **all** debug information, that sounds more like SPIRV-Tools to me.

**Comment by lifpan** [comment]
I hope it can parse such shaders as if there is no SPV debug info extension instructions, no matter it will capture the debug information or not.

**Comment by HansKristian-Work** [comment]
Yes, SPIRV-Cross should at least parse all valid SPIR-V shaders, even if the opcodes are ignored in the end. I think we have covered all debug op-codes, but if there are gaps, please file issues.

**Comment by HansKristian-Work** [comment]
PR was merged.
