### ISSUE TITLE
spirv -> MSL constant buffer bindings ignored

### ISSUE THREAD

**Issue by LiamTyler** [KhronosGroup/SPIRV-Cross#1072]
I pulled the latest spirv-cross this morning, and saw that I had shaders compiling, but the bindings were ignored. Specifically, I have 3 constant buffers, and the binding numbers ([[buffer(0)]]) didn't match the HLSL. I took a peak at the disassembled spirv file, which looked like it had the expected bindings. Only the generated MSL was off. I reverted back to a random old commit of spirv-cross: 05ea055096df8b7b8b3e3f7e121279acf83f74c0, and the problem went away. Was there a change I was unaware of or a new flag that is needed?

I emailed the spirv, for the same reason as last time. Let me know if anything else is needed!

**Comment by HansKristian-Work** [comment]
Hi, this is expected. There was a recent rework of automatic resource binding which removed the fallback for bindings where DecorationBinding would map directly to MSL bindings. This is not correct in all cases, but I guess it was inevitable that someone relied on this behavior. You should use the add_msl_resource_binding API to map set/binding to MSL bindings more explicitly. Otherwise, I can bring the old behavior back under a new option, with the caveat that it will only work if the input SPIR-V is friendly to this method.

**Comment by LiamTyler** [comment]
Oh, got it. I got it working with one shader using the add_msl_resource_binding. Still have a lot of shaders to test, but seems good so far. Part of my reflection / remapping step depends on whether the resource was a srv, uav, or cbv back in the HLSL. I was looking around in the code, but I didn't see a clear way to detect that. Is there a good way to query that for a given resource?

**Comment by HansKristian-Work** [comment]
Cool. I think this is what you need: https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide#mapping-reflection-output-to-vulkan-cheat-sheet

**Comment by LiamTyler** [comment]
Thanks. Back to the add_msl_resource_binding(): It worked on that first shader, but it isn't working on most other shaders. Here is what im doing:
```
auto executionModel = compiler.get_execution_model();
spirv_cross::MSLResourceBinding newBinding;
newBinding.stage = executionModel;
auto resources = compiler.get_shader_resources();
printf("Shader Resources: Uniform buffers\n");
for ( const auto& resource : resources.uniform_buffers ) {
	unsigned set = compiler.get_decoration( resource.id, spv::DecorationDescriptorSet );
	unsigned binding = compiler.get_decoration( resource.id, spv::DecorationBinding );
	printf( "Uniform Buffer %s at set = %u, binding = %u\n", resource.name.c_str(), set, binding );
	newBinding.desc_set = set;
	newBinding.binding = binding;
	newBinding.msl_buffer = binding;
	compiler.add_msl_resource_binding( newBinding );
}
// repeated for storage_buffers, storage_images, etc
```

Am I missing something again? The 'binding' is always exactly what I want the MSL to be, but not what ends up being used in the generated MSL. Sorry for the confusion on my part!

**Comment by HansKristian-Work** [comment]
That code should work fine. You'll need to set msl_texture or msl_sampler however when rebinding image types though. Easiest to just set all members directly to binding if you're doing 1:1 mapping scheme, the right member will be picked when bindings are assigned. If that won't work, please send a SPIR-V where this doesn't work and the MSL you get out, and I'll try to make it work.

**Comment by LiamTyler** [comment]
Oh. Apparently for the separate_images I was setting binding and msl_texture, but if you don't set msl_buffer it screws up the [[buffer]] numbers in the output. Setting all of them like you said seems to have solved it. Thank you!
