### ISSUE TITLE
MSL: using findLSB() as an argument to clamp built-ins fails on macOS 10.14

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1073]
On MacOS 10.14, I tried to convert SPIR-V to MSL and found that when using the findLSB() as the argument of the clamp function, the MSL compiler gives the following error:
```
result.msl:17:9: error: no matching function for call to 'clamp'
    if (clamp(47910, findLSB(40365u), 1) > 0)
        ^~~~~
```

The GLSL fragment shader:
```GLSL
void main()
{
 if(clamp(47910, findLSB(40365u), 1) > 0)
  {
   discard;
  }
}
```

MSL obtained by SPIRV-Cross:
```GLSL
fragment void main0()
{
    if (clamp(47910, findLSB(40365u), 1) > 0)
    {
        discard_fragment();
    }
}

```

**Versions**:

- SPIRV-Cross: git-44f688bf0b77d4f1a2c87de85980be0696974881 (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`

- Validate the generated SPIR-V with the command `spirv-val sample.spv`
- Convert the SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`
- Build a Metal library with the command `xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl`

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3380225/Archive.zip)  contains the original fragment shader, the associated SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
Seems like sign mismatch where findMSB expects to return an int, but it's not, and overload resolution fails.
