### ISSUE TITLE
MSL: no matching function for call to faceforward on macOS 10.14

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1085]
On MacOS 10.14, when using the variable identifier as the parameter of the built-in function `faceforward`, the MSL compiler gives the following error:
```
result.msl:9:15: error: no matching function for call to 'faceforward'
    float b = faceforward(1.0, a, 1.0);
              ^~~~~~~~~~~
```

The GLSL fragment shader:
```GLSL
void main()
{
    float a = 1.0;
    float b = faceforward(1.0, a, 1.0);
}
```

MSL obtained by SPIRV-Cross:
```GLSL

fragment void main0()
{
    float a = 1.0;
    float b = faceforward(1.0, a, 1.0);
}
```

**Versions:**

- SPIRV-Cross: git-33d2bbcf69c15680919c1f6ffeafb2b744460c66 (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**

- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Validate the generated SPIR-V with the command `spirv-val sample.spv`
- Convert the SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`
- Build a Metal library with the command `xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl`

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3393462/Archive.zip) contains the original fragment shader, the associated SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by cdavis5e** [comment]
This is yet another function from `<metal_graphics>` that doesn't have a scalar overload. At this point, I think we should just add scalar versions of all those functions.

**Comment by HansKristian-Work** [comment]
Ye ... I was doing a pass over the builtin functions a few days ago, but somehow forgot to check if also had this weird scalar-only restriction. Guess it's time to go over all functions one by one.
