### ISSUE TITLE
MSL: why is a std140 mat3 compiled to packed_float3x3?

### ISSUE THREAD

**Issue by bejado** [KhronosGroup/SPIRV-Cross#1088]
Given the following GLSL:

```
#version 410

layout(std140) uniform ObjectUniforms
{
    mat3 worldFromModelNormalMatrix;
} objectUniforms;

layout(location = 6) out vec3 vertex_worldTangent;

void main()
{
    vertex_worldTangent = objectUniforms.worldFromModelNormalMatrix * vec3(1.0, 0.0, 0.0);
}
```

`SPIRV-cross` on the latest [master](fb71a337a2899eed2d1dbc2f5cd21cb35aba67b0) now emits a `packed_float3x3` for `worldFromModelNormalMatrix` along with a `typedef`:

```
typedef packed_float3 packed_float3x3[3];
struct ObjectUniforms
{
    packed_float3x3 worldFromModelNormalMatrix;
};
```

**Isn't the correct type here a MSL`float3x3`?** Previously `SPIRV-cross` output `float3x3`, which has the same packing as GLSL's `mat3` under `std140`. [This commit](https://github.com/KhronosGroup/SPIRV-Cross/commit/28454facbb3d1b3ecdb29749d8d87ba7b31c3e2c) seems suspect.

Command-line:
```
$ glslangValidator -G -o test.spv test.frag
$ spirv-cross --msl test.spv
```

**Comment by cdavis5e** [comment]
Sorry about that. I was working on support for scalar block layout, and I think I broke this for you. It seems to be marking that member as packed, when it shouldn't be, since `float3` has the correct 16-byte alignment and size for `std140` layout. I'll look into this--we're aware that code is in need of serious refactoring (see #1074).

**Comment by bejado** [comment]
No problem! Thanks for the quick response

**Comment by HansKristian-Work** [comment]
Yup, fallout from the scalar matrix support, surprised this wasn't caught in testing, sorry about that. Stepped through and the check goes here: https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.cpp#L2571.

I think I'll start thinking about the packing refactor seriously in the meantime ...
