### ISSUE TITLE
Issue with translated texelFetch from Load and Vulkan semantics

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#1090]
I have an issue where a shader doing a Load in hlsl is being translated and I'm hitting a problem but I don't know the solution to it. Essentially doing a Load() in hlsl is translated as texelFetch() in glsl. Because texelFetch needs a sampler to comply with glsl, SPIRV-Cross creates a dummy sampler and uses it with texelFetch.

However, creating glsl with Vulkan semantics on fails with this error message:

> "Vulkan GLSL should not have a dummy sampler for combining"

Now, the platform I'm working on needs the separate textures and samplers feature from Vulkan, which is why I'm passing the Vulkan semantics glsl to it.

If I disable the call to glsl.build_dummy_sampler_for_combined_images() then the platform complains that

> extension EXT_samplerless_texture_functions not supported

Is there a middle ground here? Is it really illegal for Vulkan glsl to call texelFetch with a sampler?

**Comment by HansKristian-Work** [comment]
It's not technically illegal, but the Vulkan GLSL path uses EXT_samplerless_texture_functions to support this case, as glslang supports it. If you're on a platform which consumes Vulkan GLSL and somehow doesn't support this extension, I guess we'll need to support both paths ...

**Comment by redorav** [comment]
Sorry to give you a headache
