### ISSUE TITLE
Is it possible to extract uniform buffer default value? 

### ISSUE THREAD

**Issue by GregSlazinski** [KhronosGroup/SPIRV-Cross#1094]
I use Microsoft directx shader compiler to generate spirv code from hlsl and process it using spirv-cross library.
Inside hlsl code I define a constant buffer:
```
cbuffer XX 
{
   float x;
   float2 param[2]={float2(0,1), float2(2,3)};
}
```
Is it possible to obtain the default values for 'param'?
This can be done in d3d reflection api (when compiling to dxil byte code instead of spirv), but I haven't seen an option to do it in spirv cross. 
I'm using the spirv c shared api.

**Comment by HansKristian-Work** [comment]
I don't think this can be expressed in SPIR-V to begin with, so no.

**Comment by GregSlazinski** [comment]
Thank you for your reply.
That's unfortunate, it means I would have to compile the shaders 2 times, first for hlsl to extract values with d3d reflection, and then to spirv to be able to convert to glsl. 
If possible I'd like to make this a feature request, to spirv and spirv-cross. 
Do you know a good place where I could report this feature request for spirv?
Thank you very much

**Comment by HansKristian-Work** [comment]
I think https://github.com/KhronosGroup/SPIRV-Headers is the place for SPIR-V spec related issues.

**Comment by GregSlazinski** [comment]
Many thanks!
Just posted a feature request on the link that you've mentioned.

**Comment by HansKristian-Work** [comment]
Nothing to do here for now.
