### ISSUE TITLE
MSL: Using modf built in throws an error :non-const reference cannot bind to vector element

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1096]
On MacOS 10.14, I tried to convert SPIR-V to MSL and found an issue that when using a component of a vector as the argument of a `modf` built-in, the MSL compiler gives the following error:
```
program_source:9:51: error: non-const reference cannot bind to vector element
    float _15 = modf(0.1500000059604644775390625, col.x);
                                                  ^~~~~
```

The GLSL fragment shader:
```GLSL
void main()
{
 vec3 col;
 float a = modf(0.15, col.s);
}
```

MSL obtained by SPIRV-Cross:
```GLSL
fragment void main0()
{
    float3 col;
    float _16 = modf(0.1500000059604644775390625, col.x);
}

```

**Versions:**
- SPIRV-Cross: git-98d8bcd64b58ddc754927985861ef6f53625917c (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Run the SPIR-V optimizer with the command `spirv-opt sample.spv -o sample.opt.spv -O`
- Validate the optimized SPIR-V with the command `spirv-val sample.opt.spv`
- Convert the optimized SPIR-V to MSL using SPIRV-Cross with the `command spirv-cross --msl sample.opt.spv --output result.opt.msl`

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3418253/Archive.zip) contains the original fragment shader, the associated optimized SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
That is ... surprising, most likely can't pass an OpAccessChain which is a scalar into those functions.

**Comment by cdavis5e** [comment]
I suspect this is because you are not allowed to take the address of a vector component or swizzle. From MSL 2.2 §2.2.1:

> The following methods of vector component access are not permitted and result in a compile-time error:
>[...]
> * A pointer or reference to a vector with swizzles is an error:
>    ```c++
>    float4 pos = float4(1.0f, 2.0f, 3.0f, 4.0f);
>    my_func(&pos.xy); // This is an illegal pointer to a swizzle.
>    ```

**Comment by HansKristian-Work** [comment]
Ye, I knew this was the case for vector swizzles, but surprised about a single component. Easy to fix though, another thing to look for, if an expression going into these function are access chains and create dummy temporaries as necessary. There's some GLSL ops which take an out parameter.
