### ISSUE TITLE
ES2 varying mismatch

### ISSUE THREAD

**Issue by Tatsi** [KhronosGroup/SPIRV-Cross#1104]
When generating glsl code for OpenGL ES 2.0 from SPIR-V the `in` and `out` definitions are converted to `varying`'s, but the names of the corresponding output and input aren't made to match. 

With newer glsl languages they are matched with the `location` definition. When the generated glsl is fed to the driver and the names don't match these attributes are optimized out and thus not included in the produced shader program. This leads to the fact that when generating SPIR-V code that might be used with OpenGL ES 2.0 it has to be assured that the names match.

Here are examples of vertex and fragment shader code for GLSL4.5 and GLSL1.0 that have been generated from the same SPIR-V with SPIRV-Cross:

GLSL 4.5 vertex shader:

```
#version 450
...
layout(location = 0) out vec2 uvOut;
layout(location = 1) in vec2 texCoord;
...

void main()
{
    vec4 mvpPos = _13.g_model_view_projection_matrix * vec4(vertex, 1.0);
    gl_Position = mvpPos;
    uvOut = texCoord;
}
```

Corresponding GLSL 1.00 vertex shader:

```
#version 100
...
varying mediump vec2 uvOut;
attribute vec2 texCoord;
...

void main()
{
    vec4 mvpPos = _13.g_model_view_projection_matrix * vec4(vertex, 1.0);
    gl_Position = mvpPos;
    uvOut = texCoord;
}
```

GLSL 4.5 fragment shader:

```
#version 450
...
layout(location = 0) in vec2 uvIn;
...
void main()
{
    gl_FragData[0] = texture(albedo, uvIn);
}
```

Corresponding GLSL 1.00 fragment shader:

```
#version 100
...
varying mediump vec2 uvIn;
...
void main()
{
    gl_FragData[0] = texture2D(albedo, uvIn);
}
```

The options used when generating GLSL4.5:

````
options.es = false;
options.version = 450;
options.fragment.default_float_precision = CompilerGLSL::Options::Highp;
````

The options used when generating GLSL1.0:

````
options.es = true;
options.version = 100;
options.fragment.default_float_precision = CompilerGLSL::Options::Highp;
````

**Comment by HansKristian-Work** [comment]
This is expected. You can reflect stage inputs and outputs and rename them to fit your desired naming scheme before cross-compiling if the names do not match. See Compiler::set_name(). E.g. something like this for vertex outputs (and similar for fragment inputs).
```
for (auto &resource : resources.stage_outputs)
{
    uint32_t location = compiler.get_decoration(resource.id, DecorationLocation);
    compiler.set_name(resource.id, string("VARYING_") + std::to_string(location));
}
```

**Comment by HansKristian-Work** [comment]
No reply in over a month, so assuming this clarified the issue.
