### ISSUE TITLE
Renaming uniform block with an existing name

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/SPIRV-Cross#1107]
Hi, I'm trying to use the reflection API to change the names of resources in order to make them more predictable for binding in OpenGL. Using `Compiler::set_name()` seems to work fine for most things, but I see some confusing behavior when trying to override the name of a uniform block which already has a name decoration. In that case, it seem like `set_name` only modifies the "instance" name, and the original block name persists. E.g. when I try to rename a uniform resource with the name "example_0_0", I expect something like this:

```C
layout(std140) uniform example_0_0
{
    mat4 _m0;
} example_0_0_1;
```

However, if the resource already had a name, then I get this:

```C
layout(std140) uniform OriginalName
{
    mat4 OriginalMatrixName;
} example_0_0;
```

I suspect that there's a different ID that I'm supposed to be passing to the set_name function in this case, or an additional one.

**Comment by HansKristian-Work** [comment]
You can call set_name on the base_type_id instead. That corresponds to the Block name in GLSL.

**Comment by mellinoe** [comment]
@HansKristian-Work Thank you, works like a charm!
