### ISSUE TITLE
Performance regression with spirv-cross compilation to GLSL

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Cross#1108]
We are experiencing compile-time slowdowns of about 75x for the attached SPIRV input file
[shader_test.spirv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3447657/shader_test.spirv.zip)

I've bisected the changes and I think the slowdown was caused by commit https://github.com/KhronosGroup/SPIRV-Cross/commit/18bcc9b79077fe179318f607d348ff35afd24f6a

To reproduce, compile and run this code:

```c++
#include <sys/time.h>

#include <cinttypes>
#include <cstdlib>
#include <memory>
#include <spirv_glsl.hpp>
#include <sstream>

int main(int argc, char **argv) {
  std::string input;

  const int argc_check = argc - 1;
  for (int i = 1; i < argc; ++i) {
    if (!strcmp("-i", argv[i]) && i < argc_check) {
      input = argv[++i];
    }
  }
  if (input.empty()) {
    printf("\nNo input shader has been specified.\n");
    return -1;
  }

  FILE *raw_file_ptr = fopen(input.c_str(), "rb");
  if (raw_file_ptr == nullptr) {
    printf("\nFailed to read shader blob.\n");
    return -1;
  }
  fseek(raw_file_ptr, SEEK_SET, SEEK_END);

  const size_t file_size = static_cast<size_t>(ftell(raw_file_ptr));
  rewind(raw_file_ptr);

  std::vector<uint32_t> spirv_blob;
  spirv_blob.resize(file_size / 4);
  fread(spirv_blob.data(), 1, file_size, raw_file_ptr);

  timeval tv_start;
  gettimeofday(&tv_start, NULL);

  spirv_cross::CompilerGLSL glslCompiler(spirv_blob);
  glslCompiler.compile();

  timeval tv_end;
  gettimeofday(&tv_end, NULL);

  int64_t milliseconds = (tv_end.tv_sec - tv_start.tv_sec) * 1000;
  milliseconds += (tv_end.tv_usec - tv_start.tv_usec) / 1000;
  printf("Shader compiled in %d ms\n", (int)milliseconds);

  return 0;
}
```

Before that commit, the output is:

```
$ ./compile -i shader_test.spirv
Shader compiled in 38 ms
```

After the commit, the output is:

```
$ ./compile -i shader_test.spirv
Shader compiled in 2923 ms
```

I analyzed the execution with Linux Perf.  It shows a vastly increased amount of time spent in `spirv_cross::CompilerGLSL::disallow_forwarding_in_expression_chain`.  The hash sets used seem to be taking an inordinate amount of time.

@HansKristian-Work this seems to be a change of yours.  Would you be able to take a look?

Thanks.  Diego.

**Comment by HansKristian-Work** [comment]
Is this a blocking issue? That commit is quite recent, so should be possible to roll back before that one for time being.

**Comment by dnovillo** [comment]
> Is this a blocking issue? That commit is quite recent, so should be possible to roll back before that one for time being. On holiday at the moment.

If you think you'll need more time to figure out the performance issue, I think we would prefer rolling the change back, as it is blocking internal developers whose tests are timing out.  Thanks.

**Comment by HansKristian-Work** [comment]
Probably best to roll back for time being, I'll look at this when I'm back.

**Comment by dnovillo** [comment]
> Probably best to roll back for time being, I'll look at this when I'm back.

Thanks!  Will you be doing this, or should I ask someone else?  I don't have write access to this repo.

**Comment by HansKristian-Work** [comment]
Feel free to PR, I'll review it at least. It's likely a pathological case where that function starts to recurse really deep all the time for some reason.

**Comment by dnovillo** [comment]
> Feel free to PR, I'll review/merge. It's likely a pathological case where that function starts to recurse really deep all the time for some reason.

Done in #1109.  Thanks.
