### ISSUE TITLE
test_shaders.py on OS X: FileNotFoundError: [Errno 2] No such file or directory: 'glslangValidator'

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#111]
@Kangz @HansKristian-ARM 

Where you able to get the test script running on OS X?

I am attempting to run the following on OS X 10.11.6 (El Capitan):

    ./test_shaders.py --metal shaders-msl

but I get the following error:

    FileNotFoundError: [Errno 2] No such file or directory: 'glslangValidator'

`glslang/build/StandAlone` is in my $PATH, it is built, and I can successfully invoke an unqualified `glslangValidator` directly from the command line from any directory, including the directory containing `test_shaders.py`.

Any idea why this isn't working for me? Was there additional setup you performed for any of `SPIRV-Cross`, `glslangValidator`, or `Python` in order to allow Python's `subprocess.check_call()` function to find `glslangValidator` under OS X?

Thanks.

**Comment by Kangz** [comment]
You need to have glslangValidator, spirv-as and spirv-val in your PATH, maybe it is another one that's missing? Adding them all to the PATH worked for me. Also you need to make sure glslang is the at the commit listed in the .travis.yaml if you want things to pass CI.

**Comment by billhollings** [comment]
@Kangz  Thanks for your suggestion.

I added the `SPIRV-Tools/build/tools` directory to my $PATH, and I can now launch both `spirv-as` and `spirv-val` from command line in the `SPIRV-Cross` directory.

Sadly it doesn't help. Python is still not finding `glslangValidator`...even though it too is accessible from the command line in the `SPIRV-Cross` directory.

I'm using `Python 3.5.2`...if that could conceivably matter.

**Comment by HansKristian-ARM** [comment]
This is really weird, yes. I tried this on a 10.10 box after building glslang/spirv-tools fresh.
```
PATH=$PATH:../glslang/build/Standalone/:../spirv-tools/build/tools ./test_shaders.py shaders-msl --metal
```
If I copy all the binaries to /usr/local/bin then it worked fine without PATH.
Is your python3 binary linking to someplace weird? I have mine in /usr/local/bin at least.

**Comment by billhollings** [comment]
Arrrgghh!!!

Okay...I've figured this out finally.

In my terminal shell `PATH` env var, I was using `~/...` instead of the absolute path through `/Users/bill/...`.

This works fine when running `glslValidator` from the command line...but not from within `test_shaders.py `.

I was delayed in figuring this out because...arbitrarily...and frustratingly...using  `~/...` in the `PATH`-setting pre-command you use above...DOES work! It gets resolved to `/Users/bill/...` before it is appended to the `PATH` and passed to `python3`...whereas the original shell `PATH` appears in `python3` with the `~/...` values still intact.
