### ISSUE TITLE
MSL: converting ivec4 in GLSL leads to an error no matching constructor for int4  

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1112]
On MacOS 10.14, I have found that when converting the following GLSL shader, the MSL compiler gives an error:
```
result.msl:14:38: error: no matching constructor for initialization of 'int4' (vector of 4 'int' values)
    out._GLF_color = as_type<float4>(int4(1, popcount(uint2(12014u, 29527u)), 1));
                                     ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The GLSL fragment shader:

```GLSL
void main()
{
 _GLF_color = intBitsToFloat(ivec4(1, bitCount(uvec2(12014u, 29527u)), 1));
}
```

MSL obtained by SPIRV-Cross:
```GLSL
fragment main0_out main0()
{
    main0_out out = {};
    out._GLF_color = as_type<float4>(int4(1, popcount(uint2(12014u, 29527u)), 1));
    return out;
}

```

**Versions:**
- SPIRV-Cross: git-4ce04480ec5469fe7ebbdd66c3016090a704d81b (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Validate the obtained SPIR-V with the command `spirv-val sample.spv`
- Convert the SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`
- Build a Metal library with the command `xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl`

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3457355/Archive.zip) contains the original fragment shader, the associated SPIR-V, and MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
Yet another sign conversion issue, except this time it's not in GLSL.std450.
