### ISSUE TITLE
MSL: no matching function for 'ldexp' when using with uvec4

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1115]
On MacOS 10.14, when using uvec4 type as the argument of the ldexp function, the MSL compiler gives the following error:
```
result.msl:14:22: error: no matching function for call to 'ldexp'
    out._GLF_color = ldexp(float4(1.0), popcount(uint4(1u)));
                     ^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/902.1/include/metal/metal_math:2185:26: note: candidate function not
      viable: no known conversion from 'unsigned int __attribute__((ext_vector_type(4)))' (vector of 4 'unsigned int' values) to 'vec<int, 4>' (vector of 4 'int' values) for 2nd
      argument
  METAL_ASM vec<float,4> ldexp(vec<float,4> x, vec<int,4> k) __asm("air." _AIR_PREFIX_float "ldexp.v4f32");
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/902.1/include/metal/metal_math:1340:18: note: candidate function not
      viable: no known conversion from 'float4' (vector of 4 'float' values) to 'half' for 1st argument
  METAL_ASM half ldexp(half x, int k) __asm("air." _AIR_PREFIX_half "ldexp.f16");
```

The GLSL fragment shader:
```c
layout(location = 0) out vec4 _GLF_color;

void main()
{
 _GLF_color = ldexp(vec4(1.0), bitCount(uvec4(1u)));
}

```

MSL obtained by SPIRV-Cross:
```c
fragment main0_out main0()
{
    main0_out out = {};
    out._GLF_color = ldexp(float4(1.0), popcount(uint4(1u)));
    return out;
}
```

**Versions:**

- SPIRV-Cross: git-4ce04480ec5469fe7ebbdd66c3016090a704d81b (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Validate the obtained SPIR-V with the command `spirv-val sample.spv`
- Convert the generated SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.spv --output result.msl`
- Build a Metal library with the command `xcrun --sdk macosx10.14 metal -x metal -std=macos-metal1.2 result.msl`

This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3501285/Archive.zip) contains the original fragment shader, the associated SPIR-V, and the MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
This bug kinda "fixed itself" with the popcount fix, but ldexp only takes int, so need to fix that explicitly ...
