### ISSUE TITLE
Failed assertion on invalid spirv

### ISSUE THREAD

**Issue by LiamTyler** [KhronosGroup/SPIRV-Cross#1116]
Hi,

There are some cases that DXC can spit out invalid spirv, which in my pipeline automatically gets fed into SPIRV-Cross to translate it to MSL. DXC being wrong is a different issue, which I am posting bug reports on that github for, but it would be nice if SPIRV-Cross just gave an error message, instead of hitting an assert and stopping everything. I realize this is pretty low priority, but I think it would be good for SPIRV-Cross to handle bad input gracefully.

If this is worth investigating, I can post an example spirv file if that would help.

**Comment by HansKristian-Work** [comment]
SPIRV-Cross is not a validator. If the SPIR-V fails spirv-val, SPIRV-Cross may behave unexpectedly. It is not very useful for SPIRV-Cross to have its own validation suite just to avoid this kind of problem.
