### ISSUE TITLE
MSL: Failed assert in CompilerGLSL::build_composite_combiner

### ISSUE THREAD

**Issue by LiamTyler** [KhronosGroup/SPIRV-Cross#1117]
Hello,

I ran into a case where I hit the assert:
```c++
assert(!e->expression.empty() && e->expression.front() == '.');
```
in `CompilerGLSL::build_composite_combiner` with a valid spirv file. `e->expression` was "[1]".

I took a glace at the code and it seemed to be from this HLSL line:
```hlsl
float4 eyePos = float4 ( inverseWorldViewMatrix [ 3 ] . xyz , 1 ) ;
```

Which generated the following spirv snippet:
```
%442 = OpAccessChain %_ptr_Uniform_v4float %myCbufferStruct %int_4 %uint_3
%443 = OpLoad %v4float %442
%444 = OpCompositeExtract %float %443 0
%445 = OpCompositeExtract %float %443 1
%446 = OpCompositeExtract %float %443 2
%447 = OpCompositeConstruct %v4float %444 %445 %446 %float_1
```

It turned out that during the `emit_instruction` for these `OpCompositeExtract` instructions, the `access_chain_internal` was returning the expressions "[0]", "[1]" and "[2]" for these, instead of ".x", ".y", and ".z" like I think its supposed to? During `access_chain_internal`, the function `is_non_native_row_major_matrix` would return true for the %443 id above because in:

```c++
bool CompilerMSL::is_non_native_row_major_matrix(uint32_t id)
{
	auto *e = maybe_get<SPIRExpression>(id);
	if (e)
		return e->need_transpose;
	else
		return has_decoration(id, DecorationRowMajor);
}
```

`e->need_transpose` was true. I know the matrix needs to be transposed, but should this function only return true if `id` is actually a matrix? I changed it to this:

```c++
bool CompilerMSL::is_non_native_row_major_matrix(uint32_t id)
{
	auto *e = maybe_get<SPIRExpression>(id);
	bool isMatrix = is_matrix(expression_type(id));
	if (!isMatrix)
		return false;
	if (e)
		return e->need_transpose;
	else
		return has_decoration(id, DecorationRowMajor);
}
```

And it seems to work, but I've only tried it on a few shaders so far.

I realize I might be totally off on what the problem is, but I wanted to at least take a stab at figuring it out 😄 I am wondering if this was the right thing to change though, and can email the spirv file if need be too.

**Comment by HansKristian-Work** [comment]
A reproducing SPIR-V would be helpful.

**Comment by LiamTyler** [comment]
I emailed the spirv file. Thanks for the quick response

**Comment by HansKristian-Work** [comment]
Is this urgent? On holiday next week as well, but can have a quick look tomorrow if this is a blocking issue.

**Comment by LiamTyler** [comment]
Not particularly-- I can just use my hack for now too. Thank you for the offer though. Enjoy your holiday!
