### ISSUE TITLE
Several MSL tests fail in Travis but not locally due to non-optimized for(;;) loops

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#112]
The following GLSL tests:

    flatten/dynamic.flatten.vert
    flatten/copy.flatten.vert
    frag/for-loop-init.frag

all convert correctly GLSL->SPIRV->MSL, compile as valid MSL, and pass as tests when run locally, but cause the Travis build to fail the MD5 comparison when submitted to GitHub.

All of these tests seem to be failing because they create a non-optimized `for(;;)` loops when run under Travis, whereas the same tests create correctly-structured for-loops when run locally.

**Comment by HansKristian-ARM** [comment]
This is certainly one of the more bizarre cases, considering this works in GLSL backend and same code path is run for MSL, yet it does different things there and only on Travis.

**Comment by HansKristian-ARM** [comment]
Managed to reproduce locally, so shouldn't be too hard to fix.
