### ISSUE TITLE
HLSL: redundant "continue" statements

### ISSUE THREAD

**Issue by bjin** [KhronosGroup/SPIRV-Cross#1120]
[mpv](https://github.com/mpv-player/mpv/) is using SPIRV-Cross to generate HLSL code for its Direct3D backend. It however doesn't work well with the newly introduced error diffusion dithering. It turns out that the redundant "continue" statements generated by SPIRV-Cross confused the control flow analysis of D3D Compiler and failed the HLSL compilation. See mpv-player/mpv#6814

Here is the main loop of the generated HLSL code, with omitted code marked as `[...]`.
```hlsl
void comp_main()
{
    [...]
    for (int _311 = 0; _311 < 4779; _311++)
    {
        AllMemoryBarrier();
        GroupMemoryBarrierWithGroupSync();
        [...]
        if ((0 <= _71) && (_71 < 1779))
        {
            [...]
            continue;
        }
        else
        {
            continue;
        }
        continue;
    }
}
```
Note that `_71` depends on both `_311` and local thread index. It's clear that all barrier calls should sync with each other, since the conditional check is somehow independent. However, with those redundant "continue" statements, the D3D compiler failed with the following error message:
```
error X3663: thread sync operation found in varying flow control, consider reformulating your algorithm so all threads will hit the sync simultaneously
```
After removing all three redundant "continue" statements, the generated HLSL code will compile just fine.

Is it possible for SPIRV-Cross to get rid of all those redundant "continue" statements?

**Comment by HansKristian-Work** [comment]
Please post original SPIR-V.

**Comment by bjin** [comment]
@rossy could you please exact the intermediate SPIRV as well as SPIRV-Cross version used. I wasn't exactly convinience to do so.

**Comment by HansKristian-Work** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/pull/1131 might fix the issue, working on a related issue which also ended up being continue block related.

**Comment by rossy** [comment]
Here's the [original SPIR-V][1]. #1131 seems to fix the issue for me though. Nice work.

[1]: https://gist.github.com/rossy/78a6edec8ead195d9a473d40bca9055d#file-dither-opt-comp-spv

**Comment by HansKristian-Work** [comment]
Thanks. Verifyed the continues are gone now, so guess this was fixed by accident, nice.
