### ISSUE TITLE
Shader sends spirv-cross into seemingly infinite loop

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Cross#1121]
[Files to repro the problem](https://github.com/KhronosGroup/SPIRV-Cross/files/3529788/tofile.zip)

I find doing:

```
spirv-cross generated_1.opt.spv
```

nothing happens for a long time.

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz) on spirv-cross git commit 4ce04480.

**Comment by HansKristian-Work** [comment]
Does not reproduce on master, but it does reproduce on the commit. There seems to have been an infinite loop in a function which was refactored today.
