### ISSUE TITLE
spirv-cross yields invalid GLSL (unexpected IDENTIFIER)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Cross#1122]
[Files to repro the problem](https://github.com/KhronosGroup/SPIRV-Cross/files/3529798/tofile.zip)

Doing:

```
spirv-cross generated_1.opt.spv --output temp.frag && glslangValidator temp.frag
```

gives:

```
ERROR: 0:158: '' :  syntax error, unexpected IDENTIFIER, expecting LEFT_PAREN
ERROR: 1 compilation errors.  No code generated.
```

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz) on spirv-cross git commit 4ce04480.

**Comment by HansKristian-Work** [comment]
Similar bug as seen a few days ago, but it's fixed. Reproduces on given commit, but not master.
