### ISSUE TITLE
spirv-cross yields invalid GLSL (syntax error, unexpected MEDIUM_PRECISION)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Cross#1125]
[Files to repro the problem](https://github.com/KhronosGroup/SPIRV-Cross/files/3530793/tofile.zip)

Doing:

```
spirv-cross generated_0.opt.spv --output temp.frag && glslangValidator temp.frag
```

gives:

```
temp.frag
ERROR: 0:810: '' :  syntax error, unexpected MEDIUM_PRECISION
ERROR: 1 compilation errors.  No code generated.
```

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz) on spirv-cross git commit 4ce04480.

**Comment by HansKristian-Work** [comment]
Similar bug, also fixed on master, but reproduced on reported commit.
