### ISSUE TITLE
spirv-cross yields invalid GLSL (cannot convert from ' global highp 2-component vector of int' to ' temp highp 4-component vector of int')

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Cross#1127]
[Files to repro the problem](https://github.com/KhronosGroup/SPIRV-Cross/files/3530810/tofile.zip)

Doing:

```
spirv-cross generated_0.opt.spv --output temp.frag && glslangValidator temp.frag
```

gives:

```
temp.frag
ERROR: 0:484: 'assign' :  cannot convert from ' global highp 2-component vector of int' to ' temp highp 4-component vector of int'
ERROR: 0:484: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz) on spirv-cross git commit 4ce04480.

**Comment by afd** [comment]
For this, #1122, #1123, #1124, #1125 and #1126:

- I did not use spirv-reduce to search for smaller SPIR-V repros; if the repros are too large to make debugging possible then using spirv-reduce would help make them smaller (happy to give it a try in that case)

- In all cases spirv-val says the input SPIR-V is valid

**Comment by HansKristian-Work** [comment]
spirv-val errors:
```
error: line 1264: OpStore Pointer <id> '1010[%GLF_merged4_0_1_1_1_1_5_2_1_5_3_1_5imsb14msb15msb24]'s type does not match Object <id> '1043[%1043]'s type.
  OpStore %GLF_merged4_0_1_1_1_1_5_2_1_5_3_1_5imsb14msb15msb24 %1043
```
SPIR-V module is trying to assigning a vec2 to vec4.
