### ISSUE TITLE
MSL: unexpected type name 'int2': expected expression

### ISSUE THREAD

**Issue by jiradeto** [KhronosGroup/SPIRV-Cross#1128]
When converting the GLSL fragment shader attached in the Archive below to MSL shader, the metal compiler gives an error:
```
result.opt.msl:50:15: error: unexpected type name 'int2': expected expression
        _91 = int2 _93;
              ^
```

MSL obtained by SPIRV-Cross:

```
fragment main0_out main0(float4 gl_FragCoord [[position]])
{
    main0_out out = {};
    int2 _86;
    _86 = _87;
    float _78[10];
    int2 _91;
    for (int _85 = 1; _85 < 2; _86 = _91, _85++)
    {
        switch (0)
        {
            default:
            {
                int2 _93;
                if (1.0 < _78[1])
                {
                    int2 _83 = _95;
                    _83.y = 1;
                    if (gl_FragCoord.y < 0.0)
                    {
                        _91 = _83;
                        continue;
                    }
                    _93 = _83;
                }
                else
                {
                    _93 = _86;
                }
                if (1.0 > gl_FragCoord.x)
                {
                    break;
                }
                break;
            }
        }
        _91 = int2 _93;
        continue;
    }
    _78[_86.y] = 1.0;
    float3 _70 = float3(1.0, _78[1], 1.0);
    out._GLF_color = float4(_70.x, _70.y, _70.z, out._GLF_color.w);
    return out;
}
```

**Versions:**

- SPIRV-Cross: git-4ce04480ec5469fe7ebbdd66c3016090a704d81b (Most recent version of this writing)
- glslangValidator: Glslang Version: 7.12.3226

**Steps to reproduce:**
- Convert the GLSL shader to SPIR-V using glslangValidator with the command `glslangValidator -V sample.frag -o sample.spv`
- Validate the obtained SPIR-V with the command `spirv-val sample.spv`
- Run the SPIR-V optimizer with the command `spirv-opt sample.spv -o sample.opt.spv -O`
- Validate the optimized SPIR-V with the command `spirv-val sample.opt.spv`
- Convert the optimized SPIR-V to MSL using SPIRV-Cross with the command `spirv-cross --msl sample.opt.spv --output result.opt.msl`
 
This [Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/3532942/Archive.zip) contains the original fragment shader, the associated SPIR-V, and the MSL shader.

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by HansKristian-Work** [comment]
Similar issue as the others. Fixed on master, reproduced on reported commit.
