### ISSUE TITLE
Texture2D<min16float4> gets converted to uniform highp sampler2D

### ISSUE THREAD

**Issue by GregSlazinski** [KhronosGroup/SPIRV-Cross#1132]
I'm using Microsoft DirectX Shader Compiler,
and in all cases, declaring textures as `min16float` (example: `Texture2D<min16float4>`) gets converted to `highp sampler2D` in pixel shaders, but `min16float` should be `mediump`.
Please see original issue here:
https://github.com/microsoft/DirectXShaderCompiler/issues/2399

**Comment by HansKristian-Work** [comment]
Alright, seems like when we combine image samplers, the mediump is lost in translation somewhere.

**Comment by g-exp** [comment]
If I declare Texture2D<min16float4>, translated glsl only outputs data type like uniform mediump texture2D xxxxxx, but still
uniform sampler xxxx, any idea how to make mediump sampler outputs through hlsl? Thx a lot

**Comment by g-exp** [comment]
For combined sampler like sampler2D in glsl, find [[vk::combinedImageSampler]] from https://github.com/microsoft/DirectXShaderCompiler/wiki/Vulkan-combined-image-sampler-type, not sure if any similar way in hlsl for GLES?
