### ISSUE TITLE
MSL: gl_VertexIndex and gl_InstanceIndex are incorrectly emitted as uint instead of int

### ISSUE THREAD

**Issue by DagAgren** [KhronosGroup/SPIRV-Cross#1139]
The gl_VertexIndex and gl_InstanceIndex builtins are emitted as `uint` in generated MSL code. In GLSL, they are `int`. This works in most cases, but it breaks when you do arithmetic on them that can go negative. For instance, I do something like `float offset = float(gl_InstanceIndex - 1);` in my shader, to render two extra copies that are offset in opposite directions.

Since the GLSL code treats it as an `int`, even casting to `int` will not work, as the cast is optimised out as redundant.

**Comment by HansKristian-Work** [comment]
Hm, weird. There is supposed to be the bitload_from_builtin_load to cover these cases where MSL doesn't match with SPIR-V declared type, but doesn't work in this case.

**Comment by HansKristian-Work** [comment]
Just forgot to add those builtins to the list :man_facepalming: Easy fix.
