### ISSUE TITLE
reflect hlsl resource seems did not work well

### ISSUE THREAD

**Issue by 13431904801** [KhronosGroup/SPIRV-Cross#1149]
hi~ guys, I met a trouble when I try to use spriv-cross to reflect spv resource.  That's what I do below:
1. use glslang to get a new spv file:
glslangvalidator -V -D hlsl.gather.basic.dx10.frag -e main -q --hlsl-iomap --auto-map-bindings -o hlsl.gather.basic.dx10.frag.spv
2. read spv from file and use spriv-cross API like this:
	CompilerHLSL comp(std::move(spirv_bin_ref));
	auto active = comp.get_active_interface_variables();

	ShaderResources res = comp.get_shader_resources(active);
	comp.set_enabled_interface_variables(move(active));

then I get only 1 samplerd_image, but actually it has 3 samplerd_image. So Could anyone help me to found the error? thx a lot.

**Comment by KarimLUCCIN** [comment]
Could it be because the other samplers are just not used from the code, and thus, optimized away?

**Comment by 13431904801** [comment]
SamplerState       g_sSamp : register(s0);

Texture1D          g_tTex1df4a : register(t1);

uniform Texture1D <float4> g_tTex1df4 : register(t0);
Texture1D <int4>   g_tTex1di4;
Texture1D <uint4>  g_tTex1du4;

uniform Texture2D <float4> g_tTex2df4 : register(t2);
uniform Texture2D <int4>   g_tTex2di4 : register(t3);;
uniform Texture2D <uint4>  g_tTex2du4 : register(t4);;;

Texture3D <float4> g_tTex3df4;
Texture3D <int4>   g_tTex3di4;
Texture3D <uint4>  g_tTex3du4;

TextureCube <float4> g_tTexcdf4;
TextureCube <int4>   g_tTexcdi4;
TextureCube <uint4>  g_tTexcdu4;

struct PS_OUTPUT
{
    float4 Color : SV_Target0;
    float  Depth : SV_Depth;
};

PS_OUTPUT main()
{
   PS_OUTPUT psout;

   // no 1D Gathers

   float4 txval20 = g_tTex2df4 . Gather(g_sSamp, float2(0.1, 0.2), int2(1,0));
   int4   txval21 = g_tTex2di4 . Gather(g_sSamp, float2(0.3, 0.4), int2(1,1));
   uint4  txval22 = g_tTex2du4 . Gather(g_sSamp, float2(0.5, 0.6), int2(1,-1));

   // no 3D gathers
   // No Cube offset gathers

   psout.Color = 1.0;
   psout.Depth = 1.0;

   return psout;
}


that is hlsl file.

**Comment by HansKristian-Work** [comment]
I cannot reproduce it. I tried compiling the shader with glslang, without optimizations, and I get this with `--dump-resources --remove-unused-variables --hlsl --shader-model 50`.

```
separate images
=============

 ID 016 : g_tTex2df4 (Set : 0) (Binding : 2) writeonly readonly
 ID 037 : g_tTex2di4 (Set : 0) (Binding : 3) writeonly readonly
 ID 051 : g_tTex2du4 (Set : 0) (Binding : 4) writeonly readonly
=============

separate samplers
=============

 ID 020 : g_sSamp (Set : 0) (Binding : 0)
=============
```

```
struct PS_OUTPUT
{
    float4 Color;
    float Depth;
};

Texture2D<float4> g_tTex2df4 : register(t2);
SamplerState g_sSamp : register(s0);
Texture2D<float4> g_tTex2di4 : register(t3);
Texture2D<float4> g_tTex2du4 : register(t4);
Texture1D<float4> g_tTex1df4a : register(t1);
Texture1D<float4> g_tTex1df4 : register(t0);
Texture1D<float4> g_tTex1di4 : register(t0);
Texture1D<float4> g_tTex1du4 : register(t0);
Texture3D<float4> g_tTex3df4 : register(t0);
Texture3D<float4> g_tTex3di4 : register(t0);
Texture3D<float4> g_tTex3du4 : register(t0);
TextureCube<float4> g_tTexcdf4 : register(t0);
TextureCube<float4> g_tTexcdi4 : register(t0);
TextureCube<float4> g_tTexcdu4 : register(t0);

static float gl_FragDepth;
static float4 _entryPointOutput_Color;

struct SPIRV_Cross_Output
{
    float4 _entryPointOutput_Color : SV_Target0;
    float gl_FragDepth : SV_Depth;
};

PS_OUTPUT _main()
{
    float4 txval20 = g_tTex2df4.GatherRed(g_sSamp, float2(0.100000001490116119384765625f, 0.20000000298023223876953125f), int2(1, 0));
    int4 txval21 = int4(g_tTex2di4.GatherRed(g_sSamp, float2(0.300000011920928955078125f, 0.4000000059604644775390625f), int2(1, 1)));
    uint4 txval22 = uint4(g_tTex2du4.GatherRed(g_sSamp, float2(0.5f, 0.60000002384185791015625f), int2(1, -1)));
    PS_OUTPUT psout;
    psout.Color = 1.0f.xxxx;
    psout.Depth = 1.0f;
    return psout;
}

void frag_main()
{
    PS_OUTPUT flattenTemp = _main();
    _entryPointOutput_Color = flattenTemp.Color;
    gl_FragDepth = flattenTemp.Depth;
}

SPIRV_Cross_Output main()
{
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_FragDepth = gl_FragDepth;
    stage_output._entryPointOutput_Color = _entryPointOutput_Color;
    return stage_output;
}
```

If I run this through the optimizer, everything is optimized away.
```
static float gl_FragDepth;
static float4 _entryPointOutput_Color;

struct SPIRV_Cross_Output
{
    float4 _entryPointOutput_Color : SV_Target0;
    float gl_FragDepth : SV_Depth;
};

void frag_main()
{
    _entryPointOutput_Color = 1.0f.xxxx;
    gl_FragDepth = 1.0f;
}

SPIRV_Cross_Output main()
{
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_FragDepth = gl_FragDepth;
    stage_output._entryPointOutput_Color = _entryPointOutput_Color;
    return stage_output;
}
```

**Comment by HansKristian-Work** [comment]
Do you have the exact SPIR-V you're using to reflect on?

**Comment by 13431904801** [comment]
Yes I have.  So that I could load it .
