### ISSUE TITLE
Make installation optinal

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Cross#1153]
At the moment, CMake script runs [install command](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/CMakeLists.txt#L145) unconditionally for all libraries. This is undesired for projects that use SPIRV-Cross internally and do not need to install SPIRV-Cross libraries.
Making the installation optional by adding for instance `SPIRV_CROSS_SKIP_INSTALL` option would be very helpful in such cases.

**Comment by HansKristian-Work** [comment]
Should be trivial to add.
