### ISSUE TITLE
Enable position-independent code 

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Cross#1157]
SPIRV-Cross is now built with position-independent code disabled, which causes [gcc link errors](https://travis-ci.org/DiligentGraphics/DiligentCore/jobs/586106228#L1105) when the library is linked into a shared library. 
This can be fixed by adding `-fPIC` to [compile options](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/CMakeLists.txt#L85)

**Comment by HansKristian-Work** [comment]
The easiest approach here is to use set_target_properties and enable position independent code. -fPIC is used when SPIRV-Cross is actually built as a shared library.

**Comment by DiligentGraphics** [comment]
That would be great. I don't think adding this option will hurt in any way. SPIRV-Tools and glslang, for instance, always enable position-indrpendent code
