### ISSUE TITLE
new Microsoft DXIL format output support?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#116]
Hi,
don't know if makes sense to ask as part of this project.. but seeing existing HLSL support, would like to ask SPIRV-Cross devs for supporting as output Microsoft new DXIL format which is part of open sourced Microsoft new shader compiler for Shader Model 6.0, i.e. effectively supporting SPIRV -> DXIL translation..
also don't know where to ask about DXIL->SPIRV translation as don't hope Microsoft does this work..
thanks..

**Comment by HansKristian-ARM** [comment]
Translating between bytecode formats is outside the project scope of SPIRV-Cross, and I don't see much value in supporting DXIL and HLSL at the same time. I would rather time is spent improving HLSL backend than splitting up effort into this.

A more natural route for this kind of translation is via SPIR-V -> LLVM -> whatever.

**Comment by oscarbg** [comment]
that's reasonable.. thanks..
