### ISSUE TITLE
GLSL compiler issue about 'imageAtomicAdd'

### ISSUE THREAD

**Issue by xlincuts** [KhronosGroup/SPIRV-Cross#1163]
I got a compilation error when convert from HLSL -> SPIRV (SPIRV-Cross) -> GLSL.
**error C1115: unable to find compatible overloaded function "imageAtomicAdd(struct uimageBuffer1x32_bindless, uint, uint)"**

The second param only accepts int/ivec2/ivec3, not uint.
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/imageAtomicAdd.xhtml

The spirv version was 1.3 and the issue still existed when I tried 1.5

**Comment by HansKristian-Work** [comment]
The current PR in flight has a fix for this.

**Comment by HansKristian-Work** [comment]
This should be fixed now on master.
