### ISSUE TITLE
MSL: argument buffers wrong address space when > 8192 bindings

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/SPIRV-Cross#1170]
When binding more than 8192 bindings in a descriptor-set with argument_buffers enabled, the constant address space for the argument buffer is illegal.

```
program_source:14:19: error: size of constant buffer cannot exceed 65536
kernel void main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
``` 

A proposed solution would be to change the address space to 'device' when spirv-cross detects that the constant buffer size would exceed 65536 bytes in case of argument buffers?

GLSL
```
#version 460

uniform layout(rgba32f, binding = 0, set = 10) writeonly image2D myImages[8000];
uniform layout(rgba32f, binding = 1, set = 10) writeonly image2D myImages2[193];

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;
void main()
{
    vec4 foo = vec4(8,6,4,2);
    imageStore(myImages[1], ivec2(0, 0), foo);
    imageStore(myImages2[1], ivec2(0, 0), foo);
}
```

MSL:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(32u, 1u, 1u);

struct spvDescriptorSetBuffer0
{
    array<texture2d<float, access::write>, 8000> myImages [[id(0)]];
    array<texture2d<float, access::write>, 193> myImages2 [[id(8000)]];
};

kernel void main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    float4 foo = float4(8.0, 6.0, 4.0, 2.0);
    spvDescriptorSet0.myImages[1].write(foo, uint2(int2(0)));
    spvDescriptorSet0.myImages2[1].write(foo, uint2(int2(0)));
}
```

Cheers,

**Comment by HansKristian-Work** [comment]
It would be quite iffy for SPIRV-Cross to perform this change automatically. Perhaps adding an option which forces an IAB to become `device` rather than `constant` would be appropriate.

**Comment by starbucksDave** [comment]
Thanks for the quick reply!
An option that forces device on an IAB would work, the only downside I see to this is that this option would be global for the IABs within a kernel, which might not be ideal when having multiple IABs that contain different data eg texture arrays vs an IAB that contains only a small amount of buffers.
The ```device``` address space is important for the bindless usecase where the amount of descriptors exceeds 8K.

**Comment by HansKristian-Work** [comment]
There would be an option to opt-in to say "set 0 is large, use device, set 1 is small, use constant", etc. But this needs to be driven by the API user. SPIRV-Cross should not hallucinate this since it will mess with pipeline layouts, etc, for things like MoltenVK, and I really don't want to add weird heuristics here.

**Comment by starbucksDave** [comment]
I understand, that solution should work!
Thanks!
