### ISSUE TITLE
MSL: is it possible to support function constants?

### ISSUE THREAD

**Issue by kakashidinho** [KhronosGroup/SPIRV-Cross#1180]
I'm not sure if there is any option to convert an uniform constant to function constant in MSL.
Function constant is compile time constant and might be useful for certain optimizations.

Since GLSL doesn't have function constants concept. It would be useful to have an option to convert a uniform to function constant.

**Comment by HansKristian-Work** [comment]
Function constants are supported. This maps to Vulkan's specialization constants.

**Comment by kakashidinho** [comment]
Thanks for the info.

**Comment by HansKristian-Work** [comment]
Ok, don't think there is anything to do here.
