### ISSUE TITLE
Integrate BUILD.gn file into SPIRV-Cross repository

### ISSUE THREAD

**Issue by null77** [KhronosGroup/SPIRV-Cross#1189]
Chromium needs to use GN for its build system. We don't have a centralized GN file we can share across repos. Dawn has one here:

https://dawn.googlesource.com/dawn/+/84bcf44fae4b2880b9dffd1d72a999565e5a5759/third_party/BUILD.gn#25

and ANGLE is adding one here:

https://chromium-review.googlesource.com/c/angle/angle/+/1887251/2/third_party/spirv-cross/BUILD.gn

If any other clients were to use spirv-cross with Chromium they'd likely need their own too. What we've done in prior examples (e.g. glslang and SPIRV-Tools) is integrate our GN files upstream.

 * https://github.com/KhronosGroup/glslang/blob/master/BUILD.gn
 * https://github.com/KhronosGroup/SPIRV-Tools/blob/master/BUILD.gn

It would be a great help if we could upstream a version of the GN build files into spirv-cross. No testing is necessary right now. We'd detect build misconfiguration when rolling new version of SPIRV-Cross into Chromium or other client projects and we could update as needed. Would this be possible?

@Kangz @dj2 fyi

**Comment by HansKristian-Work** [comment]
I'm fine having the file in the repo as long as I don't have to janitor it myself and adding a .gn build doesn't require having a lot of other changes to accomodate it. Seems like the build file is fairly trivial, so don't think there are issues there.

**Comment by kakashidinho** [comment]
I have created a pull request for this here https://github.com/KhronosGroup/SPIRV-Cross/pull/1192
