### ISSUE TITLE
No way to access struct member names and decorations via the C API?

### ISSUE THREAD

**Issue by alpqr** [KhronosGroup/SPIRV-Cross#1190]
When getting the name (or decorations) for members of a struct inside a (uniform or other) block, one would write something like the following with the C++ API:

```
idx = 0;
// type.basetype is SPIRType::Struct
for (uint32_t member : type.member_types) {
    const std::string &name = compiler->get_member_name(type.self, idx);
    ...
    ++idx;
```

As far as I can see this cannot be expressed with the C API as there is no equivalent for 'self' there.

```
// spvc_type_get_basetype(type) == SPVC_BASETYPE_STRUCT
for (unsigned idx = 0; idx < spvc_type_get_num_member_types(type); ++idx) {
    // what should ??? be here:
    const char *name = spvc_compiler_get_member_name(compiler, ???, idx); 
    ...
```

For members of the block itself this is not a problem because spvc_reflected_resource has base_type_id, but what about members of a struct inside the block?

**Comment by QuantumDeveloper** [comment]
I think there should be something like `uniformBuffers[i].Base_type_id`

**Comment by HansKristian-Work** [comment]
Right, so this would be a problem if the member of a struct is a modified type with array for example.

**Comment by alpqr** [comment]
Thanks for the quick patch! Cheers.
