### ISSUE TITLE
spvc_resource_type missing UNIFORM_TEXEL_BUFFER and STORAGE_TEXEL_BUFFER?

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/SPIRV-Cross#1198]
In docs I see that every shader type has an equivalent in spvc_resource_type enum, except Buffer and RWBuffer.
Does they should be reflected with type SPVC_RESOURCE_TYPE_ACCELERATION_STRUCTURE?

BTW, It would be cool to have a function, that will return all resources, which are using for current shader stage. Just to have one call and not to mess up with looping through all available resource types (IMHO).

**Comment by HansKristian-Work** [comment]
Buffer/RWBuffer types are effectively images with Buffer dimension in Vulkan/SPIR-V. See Wiki page for mapping. HLSL does not match well with what you'd think.

https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide#mapping-reflection-output-to-vulkan-cheat-sheet

**Comment by QuantumDeveloper** [comment]
Ah, ok.
So, there is no SPVC_RESOURCE_TYPE_ACCELERATION_STRUCTURE resource in HLSL or GLSL according to that table?

**Comment by HansKristian-Work** [comment]
That'd be ray-tracing stuff `accelerationStructure`. That was added after the Wiki page was written, just ignore it.

**Comment by QuantumDeveloper** [comment]
I see. Thanks.

What do you think about enhancement that I suggested in my first message ?

**Comment by HansKristian-Work** [comment]
No, it would just make reflection more cumbersome since you'd have to do deep reflection on the types to figure out which resource type it's referring to. That's the reason it's split out. You should know which resource types are relevant for your use case.

**Comment by QuantumDeveloper** [comment]
Heh, ok. 
Well, thanks for your answers :)
