### ISSUE TITLE
Support tesselation shaders in Metal backend..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#120]
Hi,
just pointing it out.. Not much usage right now since MoltenVK still doesn't support tesselation stage which is new in OSX 10.12 and IOS 10..
Can't ask about geometry shaders as this stage isn't supported on Metal..
Would be nice if a detailed issue is created detailing all Metal shading features and if currently supported by SPIR-V cross similar to this (HLSL support in glslang):
https://github.com/KhronosGroup/glslang/issues/362

**Comment by billhollings** [comment]
@oscarbg 

Tessellation support for MoltenVK is coming soon...on the order of weeks.

As part of that, of course, I will add tessellation support here too.

...Bill

**Comment by oscarbg** [comment]
good news, will wait for it..
thanks Bill..

**Comment by oscarbg** [comment]
@billhollings 
no pressure but some update?
say compute&tesselation will be done by Siggraph 2017 end of July?

**Comment by billhollings** [comment]
@oscarbg 

We are starting compute this week.But unlikely that both compute and tessellation will be ready by SIGGRAPH.

**Comment by oscarbg** [comment]
Wish best luck anyway with these two important features.. also let's see Metal WWDC news!!

**Comment by oscarbg** [comment]
@billhollings
I see you posted 0.19 last month with compute support.. 👍 
no pressure but can share what are you working next (say for 0.20?)
tesselation like asked here, Metal 2 improvements?

**Comment by cdavis5e** [comment]
I'm working on tessellation right now. Barring urgent bugs in MoltenVK with my employer's projects, I want to have this ready in the next couple of weeks.
