### ISSUE TITLE
Add separate function for getting warnings separately from errors

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/SPIRV-Cross#1202]
Currently we have possibility to get number of errors and number of warnings, but its impossible to get warnings separately from error string without parsing.
Would be nice just to separate them.

**Comment by HansKristian-Work** [comment]
SPIRV-Cross only reports errors, not warnings, not sure what you mean here.

**Comment by QuantumDeveloper** [comment]
Sorry, wrong repo :) I wish everyone answer as quick as you))
