### ISSUE TITLE
[Question] Best way to generate Vertex/Hull kernel for Metal

### ISSUE THREAD

**Issue by LautrecOfCarim** [KhronosGroup/SPIRV-Cross#1205]
I'm referring to this page:
https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Tessellation/Tessellation.html
where the suggested method is to use a compute shader kernel which calls the vertex shader entry and the hull shader entry (or their excerpt methods, which are functionally the same).

When I compile the HS to spirv
dxc.exe -T hs_6_2 -E HS Tess.hlsl -spirv -Fo HS.spir
and generate the MSL shader from there
spirv-cross.exe --msl .\HS.spir --output HS.msl

I get a kernel, but it only has half the code I need - the hull shader method. Which is normal, because we only feed it that bytecode, but is there a way to reference both the VS and HS bytecode and generate kernel code similar to the one on Apple's page? What's the default way to generate hull compute kernels from a hull shader?

[Tess-hlsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/3824197/Tess-hlsl.txt)

**Comment by HansKristian-Work** [comment]
You'll need to split it up into two kernels to use vertex/tesc shaders as-is. Use attributes to link up data between stages. The "Metal way" only works if you're writing MSL from scratch to specifically target Metal's way of doing tessellation.

**Comment by HansKristian-Work** [comment]
Another option would be if you know two things up front:

- patch control points == number of output control points in Hull.
- The vertex shader only forwards attribute inputs to output attributes.
That way the vertex shader can be ignored completely and you should be able to just convert the hull shader to Metal and use that as a single kernel, but haven't tested that myself.

**Comment by HansKristian-Work** [comment]
Doesn't seems like there's any further action to take here, so closing.
