### ISSUE TITLE
Push constants do not get bound to the right resource and overlaps with others when converting to HLSL

### ISSUE THREAD

**Issue by MatiasPi** [KhronosGroup/SPIRV-Cross#1206]
When using push constants, they do not get bound to the right resource, and they overlap with other resources that are already bound by other Uniform Buffers. If you try to compile the generated HLSL, you get this error:

```error: resource DrawData at register 0 overlaps with resource CanvasData at register 0, space 0```

GLSL (Vulkan):

```glsl

layout(push_constant, binding = 0, std430) uniform DrawData {
	vec2 world_x;
	vec2 world_y;
	[...]
} draw_data;


layout(set = 2, binding = 0, std140) uniform CanvasData {
	mat4 canvas_transform;
	mat4 screen_transform;
	[...]
} canvas_data;
```

HLSL:

```hlsl
cbuffer DrawData : register(b0)
{
    float2 draw_data_world_x : packoffset(c0);
    float2 draw_data_world_y : packoffset(c0.z);
    [...]
};

cbuffer CanvasData : register(b0)
{
    row_major float4x4 canvas_data_canvas_transform : packoffset(c0);
    row_major float4x4 canvas_data_screen_transform : packoffset(c4);
    [...]
};
```

**Comment by HansKristian-Work** [comment]
You'll need to use the reflection API to assign a DecorationBinding for the push constant block, otherwise it ends up at "b0".

**Comment by reduz** [comment]
Even if it ends at b0, i don't see why other cbuffers will collide with it. Is there any reason why it can't be treated as any other cbuffer?

**Comment by HansKristian-Work** [comment]
Push constants are translated into cbuffers in HLSL, and thus the binding space for UBOs and push constants will collide in some way. DecorationBinding is used to figure out which "b#" binding to use, and you can override those, even for the push constant block before calling compile() to get a consistent mapping. If you're targeting SM 5.1+/DX12, descriptor set decoration will be translated into `register(b#, space#)` as well.

**Comment by HansKristian-Work** [comment]
> they do not get bound to the right resource

What is the "right" resource here?

**Comment by reduz** [comment]
@HansKristian-Work I don't know, I don't personally care unless it does not collide. Reflection can be used afterwards to check what as assigned, so the problem here is that, per OP, both structures are assigned b0. It would be easily fixed if they were assigned different ones.

**Comment by HansKristian-Work** [comment]
For the "I don't care" approach, an option to simply not emit any register bindings in HLSL would work in that case. Then you can reflect the HLSL output later. That can be added.

**Comment by HansKristian-Work** [comment]
Another weird quirk here is that you should never use "binding = N" on push constant blocks, as it's meaningless in Vulkan. That's why the push constant block is declared with a `register` declaration to begin with.

**Comment by HansKristian-Work** [comment]
Added support to omit any `register()` declarations per-resource type, so you can rely on d3d compiler for resource assignment.
