### ISSUE TITLE
Int array reports incorrect size?

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/SPIRV-Cross#1207]
I am playing with uniform buffers and found strange thing. Array of integers reported as 16 bytes per value instead of 4 bytes.
I have an array of size 10 and spirv-cross reports that common size of variable is 160 bytes instead of 40, but in the same time array size reported correctly and return 10 and variable type is int which is rather confusing.

**Update**
forgot to mention that I am disassembling HLSL shader

**Comment by HansKristian-Work** [comment]
Arrays in HLSL cbuffers are padded to 16 byte per element.

**Comment by QuantumDeveloper** [comment]
But I see that in GLSL is the same behavior.  Does this means that each element take 16 bytes in memory? Am I right?

**Comment by HansKristian-Work** [comment]
Yes, GLSL std140 layout also pads arrays to 16 bytes in UBOs.

**Comment by QuantumDeveloper** [comment]
Ok, just found in docs that arrays are packed as 4 component vectors takin 4 bytes6 so altogether is 16 bytes per item in array...
