### ISSUE TITLE
MSL : Translate C style array to array<T> causes regression on Dawn end2end tests

### ISSUE THREAD

**Issue by shaoboyan** [KhronosGroup/SPIRV-Cross#1210]
After applying [this patch](https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Cross/+/d50659af92fc379ba33e26cf5c39d4233396cb38), [VertexFormatTests](https://cs.chromium.org/chromium/src/third_party/dawn/src/tests/end2end/VertexFormatTests.cpp)) from end2end tests of Dawn is broken on Mac of Intel Iris Pro platform. 
The root cause seems to be Intel platform doesn't support variable as indexing of array<array<T>> type on Iris Pro. Here are detail infos.
This is the original glsl shader :
```
#version 450
        layout(location = 0) in ivec2 test;
        layout(location = 0) out vec4 color;
        
        void main() {
            int expected[3][2];
            expected[0][0] = int(127);
            expected[0][1] = int(0);
            expected[1][0] = int(-128);
            expected[1][1] = int(-2);
            expected[2][0] = int(120);
            expected[2][1] = int(-121);
            
            bool success = true;
            int testVal0;
            int expectedVal0;
            int testVal1;
            int expectedVal1;
            testVal0 = test[0];
            testVal1 = test[1];
            expectedVal0 = expected[gl_VertexIndex][0];
            expectedVal1 = expected[gl_VertexIndex][1];
            /* Workaround     
                if (gl_VertexIndex == 0) {
                    expectedVal0 = expected[0][0];
                    expectedVal1 = expected[0][1];
                } else if (gl_VertexIndex == 1) {
                    expectedVal0 = expected[1][0];
                    expectedVal1 = expected[1][1];
                } else {
                    expectedVal0 = expected[2][0];
                    expectedVal1 = expected[2][1];
                }
            }*/
            success = success && (testVal0 == expectedVal0);
            success = success && (testVal1 == expectedVal1);
            if (success) {
                color = vec4(0.0f, 1.0f, 0.0f, 1.0f);
            } else {
                color = vec4(1.0f, 0.0f, 0.0f, 1.0f);
            }
           
            const vec2 pos[3] = vec2[3](vec2(0.0f, 0.5f), vec2(-0.5f, -0.5f), vec2(0.5f, -0.5f));
            gl_Position = vec4(pos[gl_VertexIndex], 0.0, 1.0);
```
And the translated metal shader before applying array<T> patch is :
```
#include <simd/simd.h>

using namespace metal;

constant float2 _88[3] = { float2(0.0, 0.5), float2(-0.5), float2(0.5, -0.5) };

struct main0_out
{
    float4 color [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    int2 test [[attribute(0)]];
};

vertex main0_out main0(main0_in in [[stage_in]], uint gl_VertexIndex [[vertex_id]])
{
    main0_out out = {};
    int expected[3][2];
    expected[0][0] = 127;
    expected[0][1] = 0;
    expected[1][0] = -128;
    expected[1][1] = -2;
    expected[2][0] = 120;
    expected[2][1] = -121;
    bool success = true;
    bool useVariable = true;
    int testVal0 = in.test.x;
    int testVal1 = in.test.y;
    int expectedVal0 = expected[int(gl_VertexIndex)][0];
    int expectedVal1 = expected[int(gl_VertexIndex)][1];
    success = success && (testVal0 == expectedVal0);
    success = success && (testVal1 == expectedVal1);
    if (success)
    {
        out.color = float4(0.0, 1.0, 0.0, 1.0);
    }
    else
    {
        out.color = float4(1.0, 0.0, 0.0, 1.0);
    }
    out.gl_Position = float4(_88[int(gl_VertexIndex)], 0.0, 1.0);
    return out;
}
```
The translated metal shader after applying array<T> patch is :
```
#pragma clang diagnostic ignored "-Wmissing-braces"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
	
template <typename T, size_t Num>
struct unsafe_array
{
	T __Elements[Num ? Num : 1];
	
	constexpr size_t size() const thread { return Num; }
	constexpr size_t max_size() const thread { return Num; }
	constexpr bool empty() const thread { return Num == 0; }
	
	constexpr size_t size() const device { return Num; }
	constexpr size_t max_size() const device { return Num; }
	constexpr bool empty() const device { return Num == 0; }
	
	constexpr size_t size() const constant { return Num; }
	constexpr size_t max_size() const constant { return Num; }
	constexpr bool empty() const constant { return Num == 0; }
	
	constexpr size_t size() const threadgroup { return Num; }
	constexpr size_t max_size() const threadgroup { return Num; }
	constexpr bool empty() const threadgroup { return Num == 0; }
	
	thread T &operator[](size_t pos) thread
	{
		return __Elements[pos];
	}
	constexpr const thread T &operator[](size_t pos) const thread
	{
		return __Elements[pos];
	}
	
	device T &operator[](size_t pos) device
	{
		return __Elements[pos];
	}
	constexpr const device T &operator[](size_t pos) const device
	{
		return __Elements[pos];
	}
	
	constexpr const constant T &operator[](size_t pos) const constant
	{
		return __Elements[pos];
	}
	
	threadgroup T &operator[](size_t pos) threadgroup
	{
		return __Elements[pos];
	}
	constexpr const threadgroup T &operator[](size_t pos) const threadgroup
	{
		return __Elements[pos];
	}
};

using namespace metal;

constant unsafe_array<float2,3> _88 = unsafe_array<float2,3>({ float2(0.0, 0.5), float2(-0.5), float2(0.5, -0.5) });

struct main0_out
{
    float4 color [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    int2 test [[attribute(0)]];
};

vertex main0_out main0(main0_in in [[stage_in]], uint gl_VertexIndex [[vertex_id]])
{
    main0_out out = {};
    unsafe_array<unsafe_array<int,3>,2> expected;
    expected[0][0] = 127;
    expected[0][1] = 0;
    expected[1][0] = -128;
    expected[1][1] = -2;
    expected[2][0] = 120;
    expected[2][1] = -121;
    bool success = true;
    bool useVariable = true;
    int testVal0 = in.test.x;
    int testVal1 = in.test.y;
    int expectedVal0 = expected[int(gl_VertexIndex)][0];
    int expectedVal1 = expected[int(gl_VertexIndex)][1];
    success = success && (testVal0 == expectedVal0);
    success = success && (testVal1 == expectedVal1);
    if (success)
    {
        out.color = float4(0.0, 1.0, 0.0, 1.0);
    }
    else
    {
        out.color = float4(1.0, 0.0, 0.0, 1.0);
    }
    out.gl_Position = float4(_88[int(gl_VertexIndex)], 0.0, 1.0);
    return out;
}
```
The only difference between these two shaders are using of unsafe_array<T> to replace C style array.

I'm doing some initial experiment and find a simple workaround in glsl is to replace 
```
            expectedVal0 = expected[gl_VertexIndex][0];
            expectedVal1 = expected[gl_VertexIndex][1];
``` 
with a non variable indexing form like this:

```
 if (gl_VertexIndex == 0) {
                    expectedVal0 = expected[0][0];
                    expectedVal1 = expected[0][1];
                } else if (gl_VertexIndex == 1) {
                    expectedVal0 = expected[1][0];
                    expectedVal1 = expected[1][1];
                } else {
                    expectedVal0 = expected[2][0];
                    expectedVal1 = expected[2][1];
                }
```
can make the tests work again. This proves that Intel platform doesn't support variable as indexing of array<array<T>> type on Iris Pro.

I also did some experiment on MacOS of UHD630 Intel graphics platform, it turns out that all the cases using variable as indexing of a 1D array failed.

I think this maybe a driver issue for Intel GPU on metal(Need to double check). And for spirv-cross, can we workaround Intel Platform by not translating C style array to array<T> form?

**Comment by shaoboyan** [comment]
@Kangz @austinEng  This is related to [Dawn issue 259](https://bugs.chromium.org/p/dawn/issues/detail?id=259&q=&colspec=ID%20Type%20Status%20Pri%20Milestone%20Owner%20Summary).

**Comment by HansKristian-Work** [comment]
Are you sure you are on master? `    unsafe_array<unsafe_array<int,3>,2> expected;` is wrong order of arguments, and this was fixed on master.

**Comment by HansKristian-Work** [comment]
The output on master is:
```
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

constant spvUnsafeArray<float2, 3> _87 = spvUnsafeArray<float2, 3>({ float2(0.0, 0.5), float2(-0.5), float2(0.5, -0.5) });

struct main0_out
{
    float4 color [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    int2 test [[attribute(0)]];
};

vertex main0_out main0(main0_in in [[stage_in]], uint gl_VertexIndex [[vertex_id]])
{
    main0_out out = {};
    spvUnsafeArray<spvUnsafeArray<int, 2>, 3> expected;
    expected[0][0] = 127;
    expected[0][1] = 0;
    expected[1][0] = -128;
    expected[1][1] = -2;
    expected[2][0] = 120;
    expected[2][1] = -121;
    bool success = true;
    int testVal0 = in.test.x;
    int testVal1 = in.test.y;
    int expectedVal0 = expected[int(gl_VertexIndex)][0];
    int expectedVal1 = expected[int(gl_VertexIndex)][1];
    success = success && (testVal0 == expectedVal0);
    success = success && (testVal1 == expectedVal1);
    if (success)
    {
        out.color = float4(0.0, 1.0, 0.0, 1.0);
    }
    else
    {
        out.color = float4(1.0, 0.0, 0.0, 1.0);
    }
    out.gl_Position = float4(_87[int(gl_VertexIndex)], 0.0, 1.0);
    return out;
}
```

**Comment by HansKristian-Work** [comment]
This smells like a driver bug to me. Does it repro only on Iris, or all Intel chips?

**Comment by shaoboyan** [comment]
@HansKristian-Work  It can reproduced on UHD630  too and it seems on UHD630 it will failed all the 1D array that use variable as index.  And it is not realted with MacOS version(can reproduce on 10.14.6 and 10.15.1)

**Comment by shaoboyan** [comment]
Just see your comments about master fixing. Will try it and report.

**Comment by shaoboyan** [comment]
@HansKristian-Work  I updated my Dawn project and the spirv-cross is in commit fd5aa3ad51e. The shader dump is exactly as you paste in the comments. But the failure still happens and my workaround to not use variable as indexing still works. 
So I think we can continue the discussion.

**Comment by shaoboyan** [comment]
@Jiawei-Shao

**Comment by HansKristian-Work** [comment]
@LukasBanana did you observe something like this on UE4 with Intel/macOS?

**Comment by HansKristian-Work** [comment]
Has this been reported to Apple?

**Comment by LukasBanana** [comment]
We haven't experienced anything like that, at least not that I'm aware of.
The reported `unsafe_array` is definitely from an older commit as @HansKristian-Work pointed out.

The issue sounds weird since the metal library itself contains several instances of variable array indexing, like this one from the `struct matrix` template:
```cpp
  METAL_FUNC thread vec<T, Rows> &operator[](int r) thread
  {
    return columns[r];
  }
```

**Comment by shaoboyan** [comment]
@LukasBanana On Iris pro, 1D variable indexing works fine but 2D is not(You can see my dumped shader, that gl_Position get correct value, but expected[variable][] not). On UHD630, 1D seems not work. And the latest dumped shader is as same as https://github.com/KhronosGroup/SPIRV-Cross/issues/1210#issuecomment-553323254 So can you double check it?
@HansKristian-Work not yet report it, double check on other Iris pro machine and can reproduce it, will  report it today.

**Comment by shaoboyan** [comment]
@LukasBanana and @HansKristian-Work . I wirte a native metal case based on metal triangle example to reproduce this issue here:  [https://github.com/shaoboyan/ReproduceMetalIssue](https://github.com/shaoboyan/ReproduceMetalIssue). The main logic is under folder [Render](https://github.com/shaoboyan/ReproduceMetalIssue/tree/master/Renderer) and the device chosen logic is [here](https://github.com/shaoboyan/ReproduceMetalIssue/blob/master/Application/AAPLViewController.m#L27);
- The [master branch](https://github.com/shaoboyan/ReproduceMetalIssue) is the case that can reproduce this issue. 
- The [NoIntelGPU branch](https://github.com/shaoboyan/ReproduceMetalIssue/tree/NoIntelGPU) is the branch that [choose no Intel GPU if possible](https://github.com/shaoboyan/ReproduceMetalIssue/blob/NoIntelGPU/Application/AAPLViewController.m#L31) and the case works fine. 
- The [Workaround branch](https://github.com/shaoboyan/ReproduceMetalIssue/tree/Workaround) is the branch that [using non variable indexing](https://github.com/shaoboyan/ReproduceMetalIssue/blob/Workaround/Renderer/AAPLShaders.metal#L77) and the case works fine on [Intel GPU](https://github.com/shaoboyan/ReproduceMetalIssue/blob/Workaround/Application/AAPLViewController.m#L27)
- The [obviousSample branch](https://github.com/shaoboyan/ReproduceMetalIssue/tree/obviousSample) is the branch that [directly compared the value from 2D array and access by variable indexing and the literal value that stored in it](https://github.com/shaoboyan/ReproduceMetalIssue/blob/obviousSample/Renderer/AAPLShaders.metal#L75). And on Intel GPU, this case still failed.



@Kangz  and @austinEng I drafted a radar to report this issue [here](https://docs.google.com/document/d/1eOlfeJn4v6GioZkdEpZnDJRTLIz3utTsYsNV5OtqkeA/edit?usp=sharing). Since Ken is on vocation, can you help to review it and help to file the radar?

**Comment by shaoboyan** [comment]
@LukasBanana  and @HansKristian-Work  sry for bothering. But have some new updates.
I've created two simple case that just draw triangle. These two cases show some difference about failure on Iris Pro and failure on UHD630.

- This [drawTriangleIrisPro](https://github.com/shaoboyan/ReproduceMetalIssue/tree/drawTriangleIrisPro) shows that [for 2D array, on Iris pro, the variable indexing cannot get correct value](https://github.com/shaoboyan/ReproduceMetalIssue/blob/drawTriangleIrisPro/Renderer/AAPLShaders.metal#L82). So on Iris Pro, this sample presents all black. But on UHD630, this case works fine and can draw a red triangle the same as Readon.

- This [drawTriangleUHD630](https://github.com/shaoboyan/ReproduceMetalIssue/tree/drawTriangleUHD630) shows that [for shader global const array, on UHD630, the array cannot return the value, even with constant indexing](https://github.com/shaoboyan/ReproduceMetalIssue/blob/drawTriangleUHD630/Renderer/AAPLShaders.metal#L63). So on UHD630, this sample presents all black (and constant indexing workaround not works either). But this case works fine on Irsi pro and can draw a red triangle the same as Readon.

Hope this will help.

**Comment by HansKristian-Work** [comment]
I tried some custom tests on 10.14.5 with Iris 6100, and both array-of-array dynamic indexing as well as 1D array case worked fine for me.

**Comment by HansKristian-Work** [comment]
2D array test:
```
#version 450
layout(local_size_x = 16) in;

layout(std430, binding = 0, set = 0) buffer SSBO
{
    vec4 outputs[];
};

const vec4 LUT[16] = vec4[](
    vec4(0.0),
    vec4(1.0),
    vec4(2.0),
    vec4(3.0),
    vec4(4.0),
    vec4(5.0),
    vec4(6.0),
    vec4(7.0),
    vec4(8.0),
    vec4(9.0),
    vec4(10.0),
    vec4(12.0),
    vec4(13.0),
    vec4(14.0),
    vec4(15.0),
    vec4(16.0));

void main()
{
    vec4 arr[4][4];
    for (uint y = 0; y < 4; y++)
        for (uint x = 0; x < 4; x++)
            arr[y][x] = LUT[y * 4 + x];
    outputs[gl_GlobalInvocationID.x] = arr[gl_GlobalInvocationID.x >> 2][gl_GlobalInvocationID.x & 3];
}
```

**Comment by HansKristian-Work** [comment]
I also tried this shader:
```
#version 450
layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

const vec4 _56[16] = vec4[](vec4(0.0), vec4(1.0), vec4(2.0), vec4(3.0), vec4(4.0), vec4(5.0), vec4(6.0), vec4(7.0), vec4(8.0), vec4(9.0), vec4(10.0), vec4(12.0), vec4(13.0), vec4(14.0), vec4(15.0), vec4(16.0));

layout(set = 0, binding = 0, std430) buffer _9_11
{
    vec4 _m0[];
} _11;

void main()
{
    _11._m0[gl_GlobalInvocationID.x] = _56[gl_GlobalInvocationID.x ^ 3u];
}
```
That works as well.

**Comment by HansKristian-Work** [comment]
The current picture I'm seeing:

- A rather nasty Intel specific driver bug, which may be restricted to certain macOS versions.
- The maintenance cost of maintaining a compiler workaround is rather high. The complexity of adding the value-semantic arrays was moderately high, but we managed to remove a lot of hacks in the process and improve performance and correctness a great deal.
- Adding a "slow" path for Intel would mean supporting both the value-semantic types *and* maintaining all the other old hacks required to fake value-semantics for array types. All users of SPIRV-Cross would need to be aware of this specific issue as well.
- I'm not convinced right now that we need to go this far in SPIRV-Cross.

**Comment by shaoboyan** [comment]
@HansKristian-Work Totally understand  the complexity for adding this workaround. And thanks for pointing out the maintaining overhead about workaround this. It seems that if we keep C style array, we need to add back validation rules.

The second shader you tried is not the case that will failure Iris Pro but UHD630. I'll try the first shader and see whether it will help to further narrow down the issue.

Could you help me one more thing to narrow down the issue?  Could you pls help to run [this case](https://github.com/shaoboyan/ReproduceMetalIssue/tree/drawTriangleIrisPro) on your 10.14.5 with Iris 6100 ( it should render a red triangle, otherwise it will be all black)? The mac on my hand are all 10.14.6 and after, so I'm not sure whether this is a 10.14.5 to 10.14.6 regression.

Thanks for your kindly helps on this issue!

**Comment by HansKristian-Work** [comment]
<img width="912" alt="Screenshot 2019-11-16 at 15 43 05" src="https://user-images.githubusercontent.com/17786731/68994886-18086800-0888-11ea-9d44-e56ea3483ab8.png">
I get this on 10.14.5 with Iris 6100.

**Comment by shaoboyan** [comment]
@HansKristian-Work Big thanks for your help! So l plan to report this driver bug first and see their comments. WDYT?

**Comment by HansKristian-Work** [comment]
It's pretty clear this is something Apple needs to fix. I have no plans to take further action on this, so closing.

**Comment by Kangz** [comment]
+CC @zoddicus that's another SPIRV-Cross issue we ran into and need to figure out where the workaround would live.

**Comment by shaoboyan** [comment]
@Kangz thanks for backing to this.

**Comment by zeux** [comment]
Just a note that we have hit the same issue after a SPIRV-Cross upgrade. My understanding is that it happens on latest macOS hardware/software; this makes MSL translation unworkable. We'll need to use the older version of SPIRV-Cross for the time being.

**Comment by zeux** [comment]
To be more specific (sorry, the last reply was a bit brief because we had to rebuild the compilation toolchain without the offending change), the shader we use is reading from this constant array:

```
constant float3 _258[16] = { float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0) };
constant float3 _270[16] = { float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.699999988079071044921875, 0.699999988079071044921875, 0.0), float3(0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, -1.0), float3(0.0, 0.0, 1.0) };
```

Using a dynamic index inside the vertex shader. After the SPIRV-Cross update the shader translation is now emitting:

```
constant spvUnsafeArray<float3, 16> _258 = spvUnsafeArray<float3, 16>({ float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0) });
constant spvUnsafeArray<float3, 16> _270 = spvUnsafeArray<float3, 16>({ float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.699999988079071044921875, 0.699999988079071044921875, 0.0), float3(0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, -1.0), float3(0.0, 0.0, 1.0) });
```

And on the same systems identified in this thread - macOS 10.14, Intel Iris graphics - the shader is miscompiled by the driver. It's obviously a problem in the driver, but we can't ship shaders like this. 

Obviously appreciate the maintenance concerns, however there are already some special cases for spvUnsafeArray usage, e.g. for packed floats - would it be possible to stop emitting it for constant data at least, where copying presumably isn't a big issue?

We're going to use version 2019-09-06 for the time being. If spvUnsafeArray continues to be used we'll need to wait for Apple to fix this, which could take an unbounded amount of time :(

**Comment by LukasBanana** [comment]
Since this is causing various issues with driver bugs, maybe it's worth adding an option to opt-out this feature. IIRC `use_builtin_array` is a good starting point to figure out how to disable `spvUnsafeArray`. The primary benefit we tried to accomplish with this template class are performance optimizations as it can prevent expensive copy operations.

**Comment by zeux** [comment]
FWIW the reports we got were from macOS 10.14.2 and 10.14.6 (there's probably other systems affected, surely anything between these). It looks like 10.14.6 is the most recent macOS version so I am assuming this still happens live on most recent software, at least with our shaders.

It would be great to have a flag to disable this or to work around this in some other way by only emitting spvUnsafeArray when necessary.

**Comment by shaoboyan** [comment]
@zeux and @Kangz, Thanks for continuing work on this.  Yes, 10.14.2 and 10.14.6 can reproduce it. And I also can reproduce it on 10.15.1.
Have a flag to disable this sounds good and for possible workaround,,
 I raise a chromium issue to summarize the findings and possible workaround methods. https://bugs.chromium.org/p/chromium/issues/detail?id=1047556&q=Array&can=2
Hope it will help.

**Comment by HansKristian-Work** [comment]
Forcing use_builtin_array to true is a start, but we removed a lot of hacks in the process, where we could now treat arrays as a value type. All the hacks required to workaround no value type semantics must now be reintroduced and made conditional.

It seems like I have no choice if real content is hitting this problem (thanks Apple), but I won't support a half-way solution. If workaround is in effect, no fancy arrays at all.

**Comment by LukasBanana** [comment]
@zeux can you figure out if the same error occurs with the built-in `array<T, N>` template from `<metal_stdlib>`? Maybe Intel's driver can handle the "internal" structures better. If that's the case, we could consider replacing our custom solution and still have arrays as value types. The only down side would be that the internal (but also publicly visible) member `__elems` is undocumented, so no guarantee for consistency across API versions.

**Comment by HansKristian-Work** [comment]
@LukasBanana I hope that works. Is there a real need to use the internal __elems thingy though? iirc, that is only accessed for the fallback array copy functions.

**Comment by LukasBanana** [comment]
> We can template those based on array instead perhaps.

Sounds good to me. And yes, it was only used at this spot:
```C++
// Pass internal array of spvUnsafeArray<> into wrapper functions
if (lhs_thread)
	statement("spvArrayCopy", tag, type.array.size(), "(", lhs, ".elements, ", to_expression(rhs_id), ");");
else if (rhs_thread)
	statement("spvArrayCopy", tag, type.array.size(), "(", lhs, ", ", to_expression(rhs_id), ".elements);");
else
	statement("spvArrayCopy", tag, type.array.size(), "(", lhs, ", ", to_expression(rhs_id), ");");
```

**Comment by HansKristian-Work** [comment]
But ye, if someone can try to just take a repro case for this and replace the custom template and array and see if that works, I can fix it "properly". @shaoboyan can you try this in your repro?

**Comment by shaoboyan** [comment]
@HansKristian-Work  sry for late replying. I'd like to repro it when I got my mac (in Wednesday I think).

**Comment by shaoboyan** [comment]
@HansKristian-Work Finally got my mac, I'll try this ASAP.

**Comment by shaoboyan** [comment]
@HansKristian-Work @LukasBanana  Sry for bothering. But I'm not sure how to use array<T, N> in MSL.
When I tried to replace custom template unsafe_array<unsafe_array<float, 2>, 3> to array<array<float, 2>, 3>, I got a compile error (the metal_stdlib.h has been included).
I searched a bit and cannot find any guidance to use array<T, N>(e.g. in https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf). Can you help on this?

**Comment by HansKristian-Work** [comment]
@shaoboyan Thanks for testing. `array<T, N>` is currently used for texture and sampler arrays, so I'd be surprised if this does not work, I'll try to play around with the Metal compiler to see what happens.

**Comment by HansKristian-Work** [comment]
@shaoboyan It compiles for me if MSL 2.0 is enabled in xcrun. I tried something like:
```
array<array<uint, 4>, 4> arr;
arr[1][2] = 1;
// etc
```

**Comment by shaoboyan** [comment]
@HansKristian-Work  I'll check whether my MSL 2.0 is enabled in xcrun.  Thank you for trying.

**Comment by shaoboyan** [comment]
@HansKristian-Work  It works when I change my deploy target to 10.15, and array<array<float, 2>, 3> still doesn't work (I got all black screen).  :(
(And the previous workaround that replace float to float2 works)

**Comment by HansKristian-Work** [comment]
Sigh, guess we have no choice then. I've created a new issue, I'll get around to it eventually.

**Comment by shaoboyan** [comment]
Thanks for helping on this...

**Comment by HansKristian-Work** [comment]
@shaoboyan @zeux This should be fixed now on master. If there are cases I missed, I'll fix those as well. Test coverage on the workaround might not be 100%.

**Comment by shaoboyan** [comment]
@HansKristian-Work  Thanks for your work on this. I'll double check it
