### ISSUE TITLE
How do I determine the array dimension for "Texture2D foo[100];"?

### ISSUE THREAD

**Issue by bernief1** [KhronosGroup/SPIRV-Cross#1212]
I'm trying to implement a (large) array of Texture2D's. Example HLSL syntax is just this:

```
SamplerState samp;
Texture2D foo[100];

void bar()
{
    float4 v = foo[0].Sample(samp, float2(0,0));
}
```

This compiles fine in DXC. However, when I run through spirv_cross, the SPIRType for 'foo' has empty array = {}. I would expect array would contain {100}.

Am I doing something wrong?

**Comment by HansKristian-Work** [comment]
If this is related to reflection you need to look at `compiler.get_type(resource.type_id)`. This it the actual type the resource is declared with and will have array information in `SPIRType::array[0]`.

**Comment by bernief1** [comment]
SPIRType::array is empty, even when i declare the texture as Texture2D foo[100].
i would expect array would be {100}, but it is empty, i.e. {}

**Comment by HansKristian-Work** [comment]
How are you querying this in code, and what does the SPIR-V look like?

**Comment by bernief1** [comment]
Ah, I figured it out. I was using resource.base_type_id, when I need to be using resource.type_id.

All good now for this issue!
