### ISSUE TITLE
How do I query which builtins are in use (e.g. SV_Position, SV_VertexID, etc.)?

### ISSUE THREAD

**Issue by bernief1** [KhronosGroup/SPIRV-Cross#1213]
I would expect these to come in spirv_cross::ShaderResources::stage_inputs, but I'm not seeing them. Are they accessed a different way?

**Comment by bernief1** [comment]
Actually I don't think we need them.

**Comment by HansKristian-Work** [comment]
It's not currently possible to query builtin inputs/outputs which are used, but the issue was closed so I'll leave it at that.
