### ISSUE TITLE
MSL: Fragment shader has two textures bound at the same index

### ISSUE THREAD

**Issue by SausCode** [KhronosGroup/SPIRV-Cross#1219]
Hi,

Have run into this on a few shaders that I'm translating. Two textures end up being bound at the same texture binding slot. In this case v_22 and v_31.

Here's the gist with the disassembly and generated MSL.
[https://gist.github.com/SausCode/31510eaeaf57e5340b0f2173a5f70a69](url)

Let me know if you need more info.

Cheers

**Comment by HansKristian-Work** [comment]
Your link is broken I think.

**Comment by SausCode** [comment]
Thanks! :)
