### ISSUE TITLE
MSL: Fragment shader missing gl_ClipDistance (metal's clip_distance) as input 

### ISSUE THREAD

**Issue by SausCode** [KhronosGroup/SPIRV-Cross#1223]
Hi,

Running into a case where the shader uses the clip distance in SPIR-V, gl_ClipDistance, but when translating to MSL the clip_distance is not being emitted.

Here's the gist with the disassembly and generated MSL, and the link should work this time. :)
https://gist.github.com/SausCode/a3572e7b700bcd29b53fb7c3070cbe0e

Let me know if you need more info.

Cheers

**Comment by HansKristian-Work** [comment]
Ok, so the problem here is that Metal does not support ClipDistance in fragment shaders, so to support it, we'll need to workaround it by plumbing through custom varyings which the fragment stage can actually read.

I suggest passing down your own varying as a workaround for time being.

**Comment by SausCode** [comment]
Awesome, thanks!
