### ISSUE TITLE
Lot of warnings due to SPIRV_CROSS_THROW

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#1225]
Hi,

There are lot of warnings when using SPIRV_CROSS_THROW in methods returning a value, this warning appears in VisualStudio 2019, I could suspend the warning by defining the "/wd4715" but I think would be better to avoid warning supression.

I can submit PR in case.

**Comment by HansKristian-Work** [comment]
Is this when compiling without exceptions? In that case it calls report_and_abort() which is marked [[noreturn]] on non-MSVC compilers. A PR would be fine, but I won't accept a large PR with lots of tiny workarounds everywhere SPIRV_CROSS_THROW is called.

**Comment by amerkoleci** [comment]
Yeah, I have exceptions turned off in my codebase, not sure how to workaround otherwise.
