### ISSUE TITLE
HLSL vertex shaders output to POSITION instead of SV_Position

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/SPIRV-Cross#123]
I've started to play around with outputting HLSL, and it has some issues. Here's a full, though simple, example:

    cat fxaa.vert

```
#version 450
in vec4 a_position;
in vec2 a_texcoord0;
out vec2 v_texcoord0;
void main() {
  v_texcoord0 = a_texcoord0;
  gl_Position = a_position;
}
```
GLSL output is completely normal:

    glslangValidator -H fxaa.vert -o fxaa.spv
    spirv-cross fxaa.spv

```
#version 450

out vec2 v_texcoord0;
in vec2 a_texcoord0;
in vec4 a_position;

void main()
{
    v_texcoord0 = a_texcoord0;
    gl_Position = a_position;
}
```
while HLSL output is a little odd:

    spirv-cross --hlsl fxaa.spv

```
uniform float4 gl_HalfPixel;

static float2 v_texcoord0;
static float2 a_texcoord0;
static float4 gl_Position;
static float4 a_position;

struct InputVert
{
    float4 a_position : TEXCOORD0;
    float2 a_texcoord0 : TEXCOORD1;
};

struct OutputVert
{
    float2 v_texcoord0 : TEXCOORD0;
    float4 gl_Position : POSITION;
};

void vert_main()
{
    v_texcoord0 = a_texcoord0;
    gl_Position = a_position;
}

OutputVert main(InputVert input)
{
    a_texcoord0 = input.a_texcoord0;
    a_position = input.a_position;
    vert_main();
    OutputVert output;
    output.v_texcoord0 = v_texcoord0;
    output.gl_Position = gl_Position;
    output.gl_Position.x = output.gl_Position.x - gl_HalfPixel.x * output.gl_Position.w;
    output.gl_Position.y = output.gl_Position.y + gl_HalfPixel.y * output.gl_Position.w;
    return output;
}
```

Using the static variables and wrapping the main function for implementation ease makes some sense. But it also outputs to POSITION instead of SV_Position, which will simply not work in D3D11. In addition, there's a gl_HalfPixel "uniform" which I don't believe is valid or at least not common HLSL. It needs to be either be in cbuffer (D3D11), or it needs to have a c* register assigned.

Is spirv-cross set to some kind of D3D9 compatibility mode by default?

(another minor issue: typing ```spirv-cross -hlsl fxaa.vert``` instead of ```spirv-cross --hlsl fxaa.vert) causes a SIGSEGV)

**Comment by HansKristian-ARM** [comment]
Pinging @RobDangerous.
D3D9 is the default from what I can tell, don't think CLI option to set shader model has been hooked up yet.

**Comment by RobDangerous** [comment]
Aye, it's shader model 3.0 by default, see https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.hpp#L31
gl_HalfPixel is valid as it is but is also kicked out if you use shader model 4.0 or higher.

**Comment by HansKristian-ARM** [comment]
Fixed the crash bug, silly oversight when optional exceptions were added.

**Comment by HansKristian-ARM** [comment]
PR to set HLSL shader model.
https://github.com/KhronosGroup/SPIRV-Cross/pull/124

Is this format to express HLSL shader models intuitive?

**Comment by RobDangerous** [comment]
I like it. There are some complications with D3D9on11 or whatever that's called (basically shader model 3 on Windows phones) however but haven't completely figured that out myself yet.

**Comment by hrydgard** [comment]
I recall there used to be "non-number" shader models like ps_2_x so an integer instead of a string is a little odd. Though all of those are so old it probably doesn't matter.

**Comment by RobDangerous** [comment]
For what's currently supported an int is sufficient but that will probably change. We could use a string containing the shader profile ala https://msdn.microsoft.com/de-de/library/windows/desktop/bb509626%28v=vs.85%29.aspx

**Comment by hrydgard** [comment]
Alright, yeah, that might be best.

For D3D9, it would be good to be able to have an option to be able to specify a constant register for the half_pixel variable. Also the "uniform" keyword is unnecessary, global variables are uniforms. The line should look like this with a constant register 16 configured, for example:

    float4 gl_HalfPixel : register(c16);

This would eliminate the need to use reflection to find out the register number. 

Or I guess some more generic mechanism to set the D3D9 constant numbers would be the best thing anyway... There might already be one?

**Comment by HansKristian-ARM** [comment]
I expect that DecorationLocation should be used here.
When declaring a uniform which is layout(location = N), it might make sense to declare that in HLSL as : register(cN), similar with textures and samplers.

The problem is that gl_HalfPixel is a uniform which is invented by SPIRV-Cross, so ideally we would want an interface to set forced locations for magic builtins from API.

**Comment by HansKristian-ARM** [comment]
One annoying point about using the string shader profiles is that things like vs_*, ps_* prefixes are redundant as they are implied by the entry point you choose.

**Comment by hrydgard** [comment]
I guess things could go in the other direction - the prefix of the shader profile might override the stage setting. Though maybe that would feel inconsistent with the glsl support.

**Comment by HansKristian-ARM** [comment]
The stage setting is part of the SPIR-V module itself (OpEntryPoint <name> <stage>), so there is no valid way the stage can be overridden like that.

**Comment by hrydgard** [comment]
Ah yeah, of course.

**Comment by HansKristian-ARM** [comment]
As for the odd-ball D3D9on11 case, isn't that just a case where the syntax is SM 4.0, but the feature set you can use is restricted to DX9 levels? SPIRV-Cross can't magically make shaders compatible with older D3D versions anyways (GLSL often can due to extensions, but iirc that's not an option in DX).

**Comment by hrydgard** [comment]
I don't currently really care much about the case, but I think you're right.

**Comment by HansKristian-ARM** [comment]
We can always fix it if it comes up later, for now, --shader-model NN seems like a good enough solution to me.
