### ISSUE TITLE
Handle "linear" name when translating to HLSL

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/SPIRV-Cross#1232]
This is a [keyword in HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-struct) and shader translation should handle that.

**Comment by HansKristian-Work** [comment]
I cannot reproduce the issue with a trivial test, this is already handled by `CompilerHLSL::replace_illegal_names()`. Do you have a concrete SPIR-V reproducer?

**Comment by kvark** [comment]
I'll get the test case. FWIW, it was a field in a structure in a storage buffer.

**Comment by HansKristian-Work** [comment]
Ok, reproduced it from GLSL:
```
#version 450
struct Foo
{
	float linear;
};

layout(set = 0, binding = 0, std430) buffer SSBO
{
	Foo foo;
	Foo foo2;
};

void main()
{
	Foo f = foo;
	int linear = 10;
	foo2 = f;
}
```
The plain variable seems fine, but the member name is not fixed for some reason.
