### ISSUE TITLE
Is there any way to unify gl_FragCoord?

### ISSUE THREAD

**Issue by daemyung** [KhronosGroup/SPIRV-Cross#1246]
On OpenGL, gl_FragCoord.y is increased from down to up. But other graphics APIs are increased from up to down. Is it possible to unify the screen space?

**Comment by daemyung** [comment]
It is impossible to unify even I try to use vulkan maintenance extension. Each graphics API has dedicated coordinate system for instance ndc, window coordinates and texture coordinates.

**Comment by HansKristian-Work** [comment]
gl_FragCoord is painful to deal with. I think you just need to make this more portable in your shader code, SPIRV-Cross cannot easily just "make it work".

**Comment by daemyung** [comment]
The only way to solve this issue is that ESSL supports layout for gl_FragCoord.

**Comment by HansKristian-Work** [comment]
Right, there should be a layout() in; for Y-flipped FragCoord. I can add support for that since it's easy to support, but if it's not supported in ESSL, it might not be all that useful.
