### ISSUE TITLE
SPIRV Component decorations

### ISSUE THREAD

**Issue by o1lo01ol1o** [KhronosGroup/SPIRV-Cross#1249]
As originally raised here:  https://github.com/KhronosGroup/MoltenVK/issues/807#issuecomment-570964215 

It seems MSL doesn't (fully?) support Component decorations.

**Comment by HansKristian-Work** [comment]
Component decoration is not supported at all. MSL does not support it directly.

This feature is really painful to emulate. I'm trying to narrow down what we need to consider. First we have this lifeline ...

```
A user-defined output variable is considered to match an input variable in the subsequent stage if
the two variables are declared with the same **Location and Component decoration and match in type
and decoration,** except that interpolation decorations are not required to match. For the purposes
of interface matching, variables declared without a Component decoration are considered to have a
Component decoration of zero.
```
So here it's clear we don't have to consider that "we can reinterpret components at will" ala:
```
// Vert
layout(location = 0) out vec4 Foo;

// Frag
layout(location = 0, component = 1) in float Foo1;
layout(location = 0, component = 3) in float Foo3;
```

**Comment by HansKristian-Work** [comment]
This means we should be able to just do something like "locn0_c1" to express layout(location = 0, component = 1). Interfaces have to match after all. MSL doesn't really have a concept of "locations" for varyings, it's all user-provided names.

**Comment by HansKristian-Work** [comment]
That leaves vertex shader inputs, which we need to handle.

```
Location aliasing is allowed only if it does not cause component aliasing. Further, when
location aliasing, the aliases sharing the location must all have the same SPIR-V floating-point
component type or all have the same width integer-type components.
```
All inputs in a location must have the same type, so we should be able to pad out an attribute to float4/int4/uint4 and extract only what we need.

**Comment by HansKristian-Work** [comment]
Fragment shader outputs also come into play here ...

**Comment by HansKristian-Work** [comment]
I have a PR in flight which should fix the issue for vertex input and fragment output, but tessellation is going to be near-impossible, and I really don't want to do it. Do you absolutely need this for tessellation as well?

**Comment by sheaf** [comment]
Hey HansKristian, thanks for your help with this.    

My situation is that I have written an embedded language that compiles to `SPIR-V` (project repository [here](https://gitlab.com/sheaf/fir)), which means I'm relying on `spirv-cross` to run the shaders on macOS.    

I don't **need** any support for component decorations, as I believe any code that uses them can be straightforwardly rewritten to not use them (manually take apart / reassemble the components as needed). The project repository contains very simple examples which use component decorations (see [here](https://gitlab.com/sheaf/fir/blob/master/fir-examples/examples/shaders/FIR/Examples/Hopf/Shaders.hs)); their purpose is solely to demonstrate that functionality to users. See for instance this [documentation page](https://sheaf.gitlab.io/fir/FIR-Validation-Layout.html) which illustrates all the complexities of the `Vulkan` location/component system.    

Unfortunately it is the case that the previously linked example does use component decorations for tessellation stages, but I hope it is clear from this message that there is absolutely no need to accommodate me. As a point of principle I think it would be nice to have full support for this stuff on macOS, but you absolutely know what's best for `spirv-cross`, and I think it is completely reasonable to tell users to avoid component decorations if they desire portable shaders.

**Comment by HansKristian-Work** [comment]
Alright, thanks for clarifying. I'll just leave it at vertex/fragment support for Component and throw error when observed in tessellation.
