### ISSUE TITLE
HLSL pixel shader: Even with SM5.0, old style texture sampling is used

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/SPIRV-Cross#125]
When choosing shader model 50, it still generates DX9-style texture sampling.

Input: 

```
#version 450
layout(binding = 0) uniform sampler2D sampler0;
layout(location = 0) in vec2 v_texcoord0;
layout(location = 0) out vec4 fragColor;
void main() {
  vec3 rgb = texture(sampler0, v_texcoord0.xy).xyz;
  float luma = dot(rgb, vec3(0.299, 0.587, 0.114));
  fragColor.rgb = vec3(luma, luma, luma);
  fragColor.a = 1.0;
}
```

    glslangValidator -H grayscale.frag -o grayscale.spv
    spirv-cross --hlsl --shader-model 50 grayscale.spv

```
uniform sampler2D sampler0;

static float2 v_texcoord0;
static float4 fragColor;

struct InputFrag
{
    float2 v_texcoord0 : TEXCOORD0;
};

struct OutputFrag
{
    float4 fragColor : COLOR;
};

void frag_main()
{
    float3 rgb = tex2D(sampler0, v_texcoord0).xyz;
    float luma = dot(rgb, float3(0.2989999949932098388671875f, 0.58700001239776611328125f, 0.114000000059604644775390625f));
    float3 _35 = float3(luma, luma, luma);
    fragColor = float4(_35.x, _35.y, _35.z, fragColor.w);
    fragColor.w = 1.0f;
}

OutputFrag main(InputFrag input)
{
    v_texcoord0 = input.v_texcoord0;
    frag_main();
    OutputFrag output;
    output.fragColor = fragColor;
    return output;
}
```

D3DCompile() does not accept tex2d when compiling for shader model 5.0. I would expect something like:

```
Texture2D<float4> sampler0_tex : register(t0);
SamplerState sampler0_samp : register(s0);
...
float3 rgb = sampler0_tex.Sample(sampler0_samp, v_texcoord0).xyz;
...
```

I suppose by default if the original sampler was in location 0, then the texture/sampler would be assigned to t0/s0, and so on, then you could override that by switching around the decorations if you like, having them share samplerstate or something.

Also I think all "uniform" prefixes should be dropped when generating HLSL, they are not normally used.

**Comment by HansKristian-ARM** [comment]
Ping @RobDangerous. I noted this during the initial review, but I'm not sure how Robert got it working.

**Comment by RobDangerous** [comment]
I use D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY. Forgot about that, will make it work without it.

**Comment by hrydgard** [comment]
Ah, that'd be great. Would prefer to not have to use the backwards compatibility flag.

**Comment by RobDangerous** [comment]
I think this one can be closed as well.

**Comment by HansKristian-ARM** [comment]
I'm not sure about this one. The separate image/sampler style is not working that well currently, you cannot pass a combined sampler through function calls for example, I'd keep this open until it becomes more robust.

**Comment by RobDangerous** [comment]
Ah, ok, I didn't even think of that.

**Comment by HansKristian-ARM** [comment]
Fixed parameter passing in all cases I could think of. Support for modern HLSL texture sampling should be pretty good now.
