### ISSUE TITLE
GLSL 100 vertex output contains unflattened struct

### ISSUE THREAD

**Issue by youaresoomean** [KhronosGroup/SPIRV-Cross#126]
Hi,

we use glslang to compile HLSL to SPIR-V and then SPIRV-Cross to generate GLSL 100 shaders. 
The simple HLSL vertex-shader below results in a GLSL code with a varying struct which is not support in GLSL/ES v1.0. Do i miss anything on the spir-v generation side? Or are there any functions to flatten the structs manually?

Thanks alot for any help!

```
// Input HLSL 

cbuffer FrameConstants : register(b0)
{
	float4x4 viewMatrix;
	float4x4 projectionMatrix;
	float4x4 viewProjectionMatrix;
	float4 viewportParams;
};


struct VSInput
{
	float3 position : POSITION;
	float4 params : TEXCOORD0;
	float4 color : COLOR0;
};

struct VSOutput
{
	float4 position : SV_POSITION;
	float3 ws_position : TEXCOORD0;
	float4 color    : COLOR0;
};

VSOutput main(VSInput vtxIn)
{
	VSOutput vtxOut;

	float4 pos = float4(vtxIn.position.xyz, 1.0);
	pos = mul(viewProjectionMatrix, pos);
	vtxOut.position = pos;
    vtxOut.color = vtxIn.color;
	vtxOut.ws_position = vtxIn.position.xyz;
	return vtxOut;
}
```
This results in the spirv file in the attachment. 
We pass this to spirv-cross with the following compiler options

```
	spirv_cross::CompilerGLSL::Options opts;
	opts.es = true;
	opts.version = 100;
	opts.force_temporary = true;

	spirv_cross::CompilerGLSL compiler(spirv_opcodes);
	compiler.set_options(opts);
	spirv_cross::ShaderResources res = compiler.get_shader_resources();
	for (auto & v : res.push_constant_buffers)
	{
		compiler.flatten_buffer_block(v.id);
	}
	for (auto & v : res.uniform_buffers)
	{
		compiler.flatten_buffer_block(v.id);
	}
...
```
Output of SPIR-V Cross

```
// Output Spir-V to GLSL
#version 100

struct VSInput
{
    vec3 position;
    vec4 params;
    vec4 color;
};

struct VSOutput
{
    vec4 position;
    vec3 ws_position;
    vec4 color;
};

struct VSOutput_1
{
    vec3 ws_position;
    vec4 color;
};

uniform vec4 FrameConstants[13];
attribute vec3 position;
attribute vec4 params;
attribute vec4 color;
varying VSOutput_1 _entryPointOutput;

VSOutput _main(VSInput vtxIn)
{
    vec3 _22 = vtxIn.position;
    float _24 = _22.x;
    float _25 = _22.y;
    float _26 = _22.z;
    vec4 _27 = vec4(_24, _25, _26, 1.0);
    vec4 pos = _27;
    vec4 _28 = pos;
    mat4 _36 = mat4(FrameConstants[8], FrameConstants[9], FrameConstants[10], FrameConstants[11]);
    vec4 _37 = _36 * _28;
    pos = _37;
    vec4 _40 = pos;
    VSOutput vtxOut;
    vtxOut.position = _40;
    vec4 _43 = vtxIn.color;
    vtxOut.color = _43;
    vec3 _47 = vtxIn.position;
    vtxOut.ws_position = _47;
    VSOutput _49 = vtxOut;
    return _49;
}

void main()
{
    vec3 _55 = position;
    VSInput vtxIn;
    vtxIn.position = _55;
    vec4 _59 = params;
    vtxIn.params = _59;
    vec4 _62 = color;
    vtxIn.color = _62;
    VSInput _66 = vtxIn;
    VSInput param = _66;
    VSOutput _67 = _main(param);
    VSOutput flattenTemp = _67;
    vec4 _71 = flattenTemp.position;
    gl_Position = _71;
    vec3 _76 = flattenTemp.ws_position;
    _entryPointOutput.ws_position = _76;
    vec4 _80 = flattenTemp.color;
    _entryPointOutput.color = _80;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}
```
Binary dump ..just remove txt extension
[spirv-output.bin.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/787050/spirv-output.bin.txt)

**Comment by HansKristian-ARM** [comment]
Okay, it seems like HLSL will emit I/O blocks for vertex which makes sense, however, there is currently no way to flatten those. I'll look at it when I have some time (likely after GDC, but you never know). It would be like UBO/Push constant flattening, but this should be much easier to implement.

**Comment by HansKristian-ARM** [comment]
Got the flattening working for vertex outputs from HLSL inputs, but it's not super pretty atm.
https://github.com/KhronosGroup/SPIRV-Cross/pull/127

Made a WIP PR, because I'd like to know if this kind of approach would be suitable.

```
struct Foobar
{
   float4 coord;
};
```

Will translate to
```
varying vec4 Foobar_coord;
```

Now the fuzzy part is how vertex/fragment linking will work. Often HLSL shaders have different types for their vertex outputs and fragment inputs, and I'm not sure how HLSL semantics will work because they don't seem to map to any obvious location, it's just a flat struct with no linking information whatsoever in the SPIR-V module ...

**Comment by youaresoomean** [comment]
Hi, 
this would be perfectly fine for our (quite simple) shaders. The restriction that structs have to match in name, member name/order/type is ok i guess - didn't know semantics are not preserved in SPIR-V.

**Comment by HansKristian-ARM** [comment]
For the struct name in vertex/fragment, it can always be solved by reflection where you force the structs to a certain name before cross-compiling to ESSL, so it shouldn't be a problem in practice.

**Comment by youaresoomean** [comment]
Just tried PR #127. Struct flattening looks fine. Is the code already supposed to be complete (i.e. should generate valid output)? If yes, then it still uses the unflattened struct variable instance in my case. If not just ignore this post :).

**Comment by HansKristian-ARM** [comment]
It's only implemented for vertex atm, and only if the target version needs it (ESSL 300 or earlier, GLSL 140 or earlier.)

**Comment by youaresoomean** [comment]
Output currently is..see !! comments
```glsl
#version 100

struct VSInput
{
    vec3 position;
    vec4 params;
    vec4 color;
};

struct VSOutput
{
    vec4 position;
    vec3 ws_position;
    vec4 color;
};

struct VSOutput_1
{
    vec3 ws_position;
    vec4 color;
};

uniform vec4 FrameConstants[13];
attribute vec3 position;
attribute vec4 params;
attribute vec4 color;
varying vec3 VSOutput_1_ws_position;
varying vec4 VSOutput_1_color;

VSOutput _main(VSInput vtxIn)
{
    vec3 _22 = vtxIn.position;
    float _24 = _22.x;
    float _25 = _22.y;
    float _26 = _22.z;
    vec4 _27 = vec4(_24, _25, _26, 1.0);
    vec4 pos = _27;
    vec4 _28 = pos;
    mat4 _36 = mat4(FrameConstants[8], FrameConstants[9], FrameConstants[10], FrameConstants[11]);
    vec4 _37 = _36 * _28;
    pos = _37;
    vec4 _40 = pos;
    VSOutput vtxOut;
    vtxOut.position = _40;
    vec4 _43 = vtxIn.color;
    vtxOut.color = _43;
    vec3 _47 = vtxIn.position;
    vtxOut.ws_position = _47;
    VSOutput _49 = vtxOut;
    return _49;
}

void main()
{
    vec3 _55 = position;
    VSInput vtxIn;
    vtxIn.position = _55;
    vec4 _59 = params;
    vtxIn.params = _59;
    vec4 _62 = color;
    vtxIn.color = _62;
    VSInput _66 = vtxIn;
    VSInput param = _66;
    VSOutput _67 = _main(param);
    VSOutput flattenTemp = _67;
    vec4 _71 = flattenTemp.position;
    gl_Position = _71;
    vec3 _76 = flattenTemp.ws_position;
     // !! uses  _entryPointOutput instead of VSOutput_1_ws_position
    _entryPointOutput.ws_position = _76;
    vec4 _80 = flattenTemp.color;
    // !! same here
    _entryPointOutput.color = _80;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}

```

**Comment by HansKristian-ARM** [comment]
Ah, right. That case won't work atm, still a fair bit of cases to work out then.

**Comment by HansKristian-ARM** [comment]
Should have implemented it correctly now for both vertex and fragment, please try again :)

**Comment by youaresoomean** [comment]
Thanks alot! Vertex stage compiles/validates now.
In fragment stage the positon of the precision qualifier is wrong.
Output currently is:
```
...
highp varying vec3 PSInput_1_ws_position_1;
highp varying vec4 PSInput_1_color_1;
...
```
should be:
varying **highp** vec3 ...

**Comment by HansKristian-ARM** [comment]
Hm ... right, legacy GLSL seems to be stricter about the ordering here of qualifiers than modern GLSL, odd that this never came up until now.

Need to ensure the qualifier ordering when emitting variables it seems.

**Comment by HansKristian-ARM** [comment]
Reworked how qualifiers work, should work now.

**Comment by youaresoomean** [comment]
Excellent - thanks alot!
