### ISSUE TITLE
bool uniforms and legacy ES shaders

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/SPIRV-Cross#1265]
Hello,
I have this shader (test.vert):
```
#version 450

layout(set = 0, binding = 0) uniform UBO
{
	bool b;
}

void main()
{
	gl_Position = b ? vec4(0.0) : vec4(1.0)
}
```
When I try to convert it for ES 2.0 targets spirv-cross throws next exception:
`Unsigned integers not supported for ES targets.`

For conversion I use following tools:
```
glslangValidator.exe -V -o test.vert.spv test.vert
spirv-cross test.vert.spv --version 100 --es --output test.vert.es
```
How to workaround this?
Thanks.

**Comment by HansKristian-Work** [comment]
Use int instead of bool. Bool in buffers are promoted implicitly to uint, which is unsupported in legacy ESSL.

**Comment by HansKristian-Work** [comment]
Doesn't seem to be more to do here, closing.
