### ISSUE TITLE
OpUndef in SPIRV yields "free" constant in HLSL

### ISSUE THREAD

**Issue by hugoam** [KhronosGroup/SPIRV-Cross#1276]
I'm wondering if we can consider this a SPIRV-Cross issue (don't hesitate to correct me and close this if it isn't).

I have a shader with a `float4` variable staying uninitialized in one of the code paths.
Now the problem is, after the SPIRV-Cross `SPIRV -> HLSL` compilation step, the `OpUndef` somehow is translated to a "free" `float4` constant/uniform.

This is an issue because my only uniforms are in a uniform block, which has an explicit binding (that can picked up with reflection etc). When loading this HLSL shader in D3D12, I don't expect to have to bind a buffer with a different binding as the ones I had at the SPIRV step, i.e my uniform block (at `set = 0` and `binding = 1`).
But the existence of this additional "parasite" uniform will make D3D12 *require* me to have a buffer bound at `set = 0` and `binding = 0` even though I have no way to detect that this uniform will even exist in any of the previous compilation steps. I think this is unfortunate and breaks all the determinism of the validation steps of a rendering pipeline, and I think this might be considered a SPIRV-Cross issue, but I'm not entirely sure because I'm not the most experienced with those topics yet either.

Here is the minimal reproduction of this `SPIRV-Cross` behavior I could come up with:
http://shader-playground.timjones.io/c22bb864cbfba58af2d37614a7bb616a

The points of interest in this reproduction are `%111 = OpUndef %v4float` on the SPIRV side which gets translated to the constant/uniform `float4 _111;` on the HLSL side.

Any enlightenment on this issue would be appreciated :)

**Comment by HansKristian-Work** [comment]
Oh ... that is not intentional, should be static. Classic HLSL issue.

**Comment by HansKristian-Work** [comment]
PR in flight.

**Comment by hugoam** [comment]
Great ! Thank you very much for the very quick fix :)
