### ISSUE TITLE
glslangvalidator generated SPIRV causes infinite loop

### ISSUE THREAD

**Issue by jaybaird** [KhronosGroup/SPIRV-Cross#1278]
Hello,

When running `spirv_cross::CompilerGLSL` against a SPIRV binary generated from the reference compiler I get an infinite loop in `SmallVector::reserve`. It appears the [Bound value on word 3](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_physicallayout_a_physical_layout_of_a_spir_v_module_and_instruction) is close to `SIZE_MAX` which will overflow `target_capacity` and lead to an infinite loop.

I've tried modifying the code to recognize this situation and provide a saner `target_capacity` value but this leads to different crashing side-effects which are also less than ideal. Is there something happening in my pipeline that's causing the reference compiler to output such a large Bound?

Thanks!

**Comment by HansKristian-Work** [comment]
In 2.17 of SPIR-V spec, the ID bound limit is ~4 million. Your SPIR-V is invalid if the ID bound is too large. I think I'll just add some sanity checking to avoid this scenario in the future.

**Comment by jaybaird** [comment]
Thanks!
