### ISSUE TITLE
Is there any way convert legacy glsl to hlsl qucikly?

### ISSUE THREAD

**Issue by klob** [KhronosGroup/SPIRV-Cross#1279]
When I use SPIRV-Cross convert old version glsl ,such as 1.2.0, the following error occured
ERROR: #version: ES shaders for SPIR-V require version 310 or higher
Is there any way convert legacy glsl to hlsl qucikly? 
My project has a lot shaders use glsl 1.2.0, do I have to updating shader from 120 to 330 manually first？

**Comment by HansKristian-Work** [comment]
SPIRV-Cross is not a GLSL compiler, you'll need to update the version to whatever glslang requires so it can make SPIR-V out of it.
