### ISSUE TITLE
GLSL extension ops in SPIR-V do not use HLSL builtins correctly

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/SPIRV-Cross#128]
GLSL has a few obscure builtin functions that take two vectors and produce an equally-sized vector of bools. These are: lessThan, greaterThan, greaterThanEqual, equal, notEqual. For example, 

    lessThanEqual(vec2(1.0, 2.0), vec2(1.5, 1.5))  = bvec2(true, false).

These seem to be translated to SPIRV by glslang, but SPIRV-Cross simply translates them back to the same function calls in HLSL, but in HLSL these functions do not exist.

I can easily work around this of course by reimplementing them, but would be nice if they were supported, probably simply generated into the HLSL code when used.

**Comment by HansKristian-ARM** [comment]
Yup, HLSL backend would need to add an extra override for the GLSL builtins, pretty sure it falls back to GLSL implementation at the moment.

**Comment by hrydgard** [comment]
Additionally, mix() needs to be replaced with lerp().

**Comment by HansKristian-ARM** [comment]
Pretty sure we just have to override the entire OpExtInstr and implement it for HLSL wholesale.

**Comment by HansKristian-ARM** [comment]
Ping @RobDangerous.

**Comment by RobDangerous** [comment]
Okidoki

**Comment by rextimmy** [comment]
Same story with the glsl function floatBitsToInt (and the other bit casting functions). That is getting missed for both hlsl (asInt) and metal(as_type<>).

**Comment by RobDangerous** [comment]
@hrydgard, mix was already replaced with lerp. Did you maybe mix something up? Everything else is in the pull-request.

**Comment by hrydgard** [comment]
Pretty sure it wasn't, for me. I'll verify later - maybe depends on the types used? There are a few weird GLSL mix uses that don't quite map to lerp, IIRC.

But good news that fixes are underway!

**Comment by HansKristian-ARM** [comment]
There is boolean mix, but I think that maps to OpSelect and friends. That might need some special implementation in HLSL.

**Comment by HansKristian-ARM** [comment]
Can this issue be closed now?

**Comment by rextimmy** [comment]
Should i open a separate issue for that floatBitsToInt(and friends)? That is working now for hlsl but it's still not for msl

**Comment by hrydgard** [comment]
I'm fine with closing.

**Comment by HansKristian-ARM** [comment]
@rextimmy yes please open an MSL ticket, this ticket was for HLSL. Closing.
