### ISSUE TITLE
MSL: Reinstate old hacks for array-as-value-types

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Cross#1282]
Reference: https://github.com/KhronosGroup/SPIRV-Cross/issues/1210

Apparently, real-world content is running into this bug on certain Intel-based macbooks. If we use an array type wrapper, dynamically indexing into the array may break on certain driver revisions.

It seems inevitable that we will need to maintain two paths for how arrays work to either favor workarounds or performance.

**Comment by LukasBanana** [comment]
Thank you for considering both paths for either performance or workarounds.

As for the template wrapper, I think switching to Metal's own `array<T, N>` template can at least simplify the resulting shader a bit and is potentially more stable in regards to driver updates. That should also make it easier to file bug reports at Apple.

**Comment by HansKristian-Work** [comment]
array<> is only supported on MSL 2.0, but if we can fallback to the hacky path for older MSL, that'd work.

**Comment by LukasBanana** [comment]
I synced with my colleagues. Turns out Metal's standard `array<>` template is only intended for texture and sampler entry point arguments. They are not supported as general purpose arrays like C++11's `std::array`. In this case, it would be great if you can keep our custom solution (if it's enabled).

**Comment by HansKristian-Work** [comment]
Alright, thanks for confirming.

**Comment by HansKristian-Work** [comment]
I'll try to get this done next week.
