### ISSUE TITLE
DecorationNonWritable and DecorationNonReadable are always set on Storage Images

### ISSUE THREAD

**Issue by Jiawei-Shao** [KhronosGroup/SPIRV-Cross#1286]
Hi SPIRV-Cross developers:

I am a Chromium/Dawn developer and now I am meeting several issues in SPIR-V Cross when I am implementing storage textures in Dawn.

Now ```readonly-storage-texture``` and ```writeonly-storage-texture``` have been supported as [WebGPU binding types](https://gpuweb.github.io/gpuweb/#enumdef-gpubindingtype), on D3D12. ```readonly-storage-texture``` is intended to match SRVs, and ```writeonly-storage-texture``` is intended to match UAVs.

But in SPIRV-Cross, I find whether I declare ```DecorationNonReadable``` or ```DecorationNonWritable``` on an image variable:
- I can always detect both the decoration ```DecorationNonWritable``` and ```DecorationNonReadable``` be set. It seems [here](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_parser.cpp#L714) is the code in SPIRV-Cross where both these two decorations are set on all image variables.
- The image variable is always translated into ```RWTexture2D``` when it is translated into HLSL.

Here is an example. Considering the following GLSL shader:
```
// 1.comp
#version 450
layout(set = 0, binding = 0, rgba8) uniform highp readonly image2D image0;
layout(set = 0, binding = 1, rgba8) uniform highp writeonly image2D image1;
void main() {
    vec4 pixel = imageLoad(image0, ivec2(gl_LocalInvocationID));
    imageStore(image1, ivec2(gl_LocalInvocationID), pixel);
}
```

Here is the translation result of 1.comp with glslang. You can see ```NonWritable``` and ```NonReadable``` has been correctly translated in the result.
```
// 1.spv
// glslang_validator.exe -H -V -o 1.spv 1.comp
// Module Version 10000
// Generated by (magic number): 80008
// Id's are bound by 35

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 17
                              ExecutionMode 4 LocalSize 1 1 1
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "pixel"
                              Name 12  "image0"
                              Name 17  "gl_LocalInvocationID"
                              Name 27  "image1"
                              Decorate 12(image0) DescriptorSet 0
                              Decorate 12(image0) Binding 0
                              Decorate 12(image0) NonWritable
                              Decorate 17(gl_LocalInvocationID) BuiltIn LocalInvocationId
                              Decorate 27(image1) DescriptorSet 0
                              Decorate 27(image1) Binding 1
                              Decorate 27(image1) NonReadable
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
              10:             TypeImage 6(float) 2D nonsampled format:Rgba8
              11:             TypePointer UniformConstant 10
      12(image0):     11(ptr) Variable UniformConstant
              14:             TypeInt 32 0
              15:             TypeVector 14(int) 3
              16:             TypePointer Input 15(ivec3)
17(gl_LocalInvocationID):     16(ptr) Variable Input
              19:             TypeInt 32 1
              20:             TypeVector 19(int) 3
              22:             TypeVector 19(int) 2
      27(image1):     11(ptr) Variable UniformConstant
         4(main):           2 Function None 3
               5:             Label
        9(pixel):      8(ptr) Variable Function
              13:          10 Load 12(image0)
              18:   15(ivec3) Load 17(gl_LocalInvocationID)
              21:   20(ivec3) Bitcast 18
              23:     19(int) CompositeExtract 21 0
              24:     19(int) CompositeExtract 21 1
              25:   22(ivec2) CompositeConstruct 23 24
              26:    7(fvec4) ImageRead 13 25
                              Store 9(pixel) 26
              28:          10 Load 27(image1)
              29:   15(ivec3) Load 17(gl_LocalInvocationID)
              30:   20(ivec3) Bitcast 29
              31:     19(int) CompositeExtract 30 0
              32:     19(int) CompositeExtract 30 1
              33:   22(ivec2) CompositeConstruct 31 32
              34:    7(fvec4) Load 9(pixel)
                              ImageWrite 28 33 34
                              Return
                              FunctionEnd
```

Here is the translation result of translating 1.spv into HLSL shaders. With "--dump-resources" we can see both ```readonly``` and ```writeonly``` are set on both image0 and image1, and they are all translated into ```RWTexture2D```.
```
// spirv-cross.exe 1.spv --dump-resources --hlsl --shader-model 50
...
images
=============
 ID 012 : image0 (Set : 0) (Binding : 0) writeonly readonly
 ID 027 : image1 (Set : 0) (Binding : 1) writeonly readonly
=============
...
=============
RWTexture2D<unorm float4> image0 : register(u0);
RWTexture2D<unorm float4> image1 : register(u1);

static uint3 gl_LocalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_LocalInvocationID : SV_GroupThreadID;
};

void comp_main()
{
    float4 pixel = image0[int2(int3(gl_LocalInvocationID).xy)];
    image1[int2(int3(gl_LocalInvocationID).xy)] = pixel;
}

[numthreads(1, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_LocalInvocationID = stage_input.gl_LocalInvocationID;
    comp_main();
}
```

**Comment by cdavis5e** [comment]
That's because both image types are non-sampled (`Sampled`=2). Storage images, whether `readonly`, `writeonly`, or `readwrite`, are always translated to D3D UAVs. If you want an SRV, use a sampled image (`Sampled`=1 in SPIR-V; `texture2D` or `sampler2D` in GLSL).

The decorations are always forced because HLSL doesn't support them at all. (See comment just above the source line you linked.) They are removed by the GLSL and MSL backends when read or write operations are detected.

**Comment by HansKristian-Work** [comment]
Yes, image2D will always be equivalent to a UAV in HLSL. This is expected behavior.

**Comment by Jiawei-Shao** [comment]
Thanks for your comments. I still have some questions with the translation of storage images to HLSL, which may affect the design of WebGPU API. PTAL, thanks!

@cdavis5e said "the decorations are always forced because HLSL doesn't support them at all", could you explain a bit more about it? As far as I know, in HLSL:
- Read-only resources are always matching SRVs, which is Non-Writable.
- For UAVs, "typed UAV loads" are [not allowed on all texture formats](https://docs.microsoft.com/en-us/windows/win32/direct3d12/typed-unordered-access-view-loads) (in fact only ```R32_FLOAT```, ```R32_UINT``` and ```R32_SINT``` are always supported on all feature level 11_0 hardwares).  If you always translate read-only storage images into UAVs instead of SRVs, then we will prevent the use of quite a lot of texture formats with this shader because these formats may not support typed UAV reading on everywhere.

So although @HansKristian-Work said "```image2D``` (```STORAGE_IMAGE```) will always be equivalent to a UAV in HLSL. This is expected behavior", it seems that if the ```image2D``` is read-only, it is better to translate it into SRVs instead of UAVs to avoid the use of the texture format being limited by "typed UAV loading" rules in HLSL.

The "typed UAV loads" rules in HLSL is also one of the main reason to separate "writeonly-storage-texture" from (read-write) "storage-texture" in WebGPU. Another reason is there are [similar limitations on the texture formats that support read-write access in Metal](https://developer.apple.com/documentation/metal/mtldevice/2887289-readwritetexturesupport?language=objc). In WebGPU, we have to define different limitations on the use of texture formats as "```readonly-storage-texture```", "```writeonly-storage-texture```" and "```readwrite-storage-texture```".

Invited more WebGPU developers into our discussion. @Kangz @austineng @kainino0x

**Comment by cdavis5e** [comment]
> @cdavis5e said "the decorations are always forced because HLSL doesn't support them at all", could you explain a bit more about it?

What I mean is, there's no equivalent to the `readonly`, `writeonly`, and `readwrite` qualifiers in HLSL. You have SRVs, which support sampling operations and reading texels; and UAVs, which support reading and writing individual texels, but not sampling. So when you use e.g. DXC or glslang to compile HLSL to SPIR-V, and you have a UAV in the shader, they produce SPIR-V without those decorations at all. But these are important for GLSL or Metal, because the access level must be declared in the shader. So we assume both decorations at first, and do analysis of the SPIR-V code. If an image is read, we drop `NonReadable`, and if it is written, we drop `NonWritable`. We don't do this for HLSL, though, because again, it doesn't support this.

So when you use SPIRV-Cross to produce HLSL, storage images will always appear to be `NonReadable` and `NonWritable`, because we set them both in case this SPIR-V module was compiled *from* HLSL, and it doesn't matter for compiling *to* HLSL because it doesn't support them.

**Comment by cdavis5e** [comment]
Another thing about storage images in SPIR-V is that, by default, you have to declare the image format in the shader, and only a small subset of image formats is supported for storage images. If you want more, you have to declare a capability, `StorageImageExtendedFormats`, which allows all image formats. And if you want to avoid declaring a format at all, you need `StorageImageReadWithoutFormat` and/or `StorageImageWriteWithoutFormat`, depending on whether the image is read or written. There is no guarantee that any of these will be supported by the SPIR-V consumer.

The default set of storage image formats includes `R32_FLOAT`, `R32_INT`, and `R32_UINT`. But it also includes `R32G32B32A32_FLOAT`, `R16G16B16A16_FLOAT`, `R8G8B8A8_UNORM`, `R8G8B8A8_SNORM`, `R32G32B32A32_INT`, `R16G16B16A16_INT`, `R8G8B8A8_INT`, `R32G32B32A32_UINT`, `R16G16B16A16_UINT`, and `R8G8B8A8_UINT`, which is above and beyond what D3D requires.

Typically, the API provides a mechanism for querying what capabilities a given format supports. D3D, OpenGL, and Vulkan all provide this. Metal doesn't, but Apple publishes the capabilities supported by each Metal feature set. (These must then be hardcoded in implementations like MoltenVK.) In any case, you'll probably have to provide your own mechanism for this in WebGPU.

**Comment by Jiawei-Shao** [comment]
@cdavis5e thanks for your quick response.

On D3D, in fact I still don't agree that "there's no equivalent to the ```readonly```, ```writeonly```, and ```readwrite``` qualifiers in HLSL". I think ```readonly``` storage textures should be translate to SRVs, while both ```writeonly``` and ```readwrite``` storage textures should refer to UAVs, and this is actually how ```readonly```, ```writeonly``` and ```readwrite``` qualifiers work in HLSL. Now we always translate "readonly storage textures" into UAVs on HLSL, **it is preventing the use of quite a lot of texture formats with this shader**, which should have been able to be used if "readonly storage textures" are translated into SRVs.

In the current discussion of WebGPU features we only focus on the core features in D3D, Vulkan and Metal. I have reported all the support of texture formats as "writable storage textures" and "read-write storage textures" to WebGPU CG ([here](https://github.com/gpuweb/gpuweb/issues/513)). When writing that proposal I realized the limitations on the texture formats used as "writable storage textures" and "read-write storage textures" are **different** so we agree to separate ```writeonly-storage-texture``` from ```read-write-storage-texture``` (not included in the current SPEC because it cannot be supported on all Metal devices and has to be an extension).

**Comment by HansKristian-Work** [comment]
Translating read-only image2D to SRV is wrong, because read-only image2D can still be coherent with write-only image2Ds, but sampled images cannot. They use a different way of fetching data, it's not just a question of "read-only" vs "read-write".

**Comment by Jiawei-Shao** [comment]
Thanks @HansKristian-Work. I think here you are talking about memory qualifiers on image variables including ```coherent```, ```restrict```, etc. Sorry I am quite new to the memory qualifiers so there could be some misunderstanding in my following responses.

> Translating read-only image2D to SRV is wrong, because read-only image2D can still be coherent with write-only image2Ds, but sampled images cannot. They use a different way of fetching data, it's not just a question of "read-only" vs "read-write".

As the image object is declared as "```readonly```", in the current dispatch or draw, none of the invocations can modify its content. So I think here you mean that at the same time, maybe there is another dispatch/draw call that is executing on the same GPU at the same time, where the same image resource is writable and declared as "```coherent```", and that call will affect the result of ```imageLoad()``` in this call where it is declared as "```readonly```"? I am not sure if we should think about such usage in WebGPU. @Kangz do you have any idea about that?

Also I find "```coherent```" is not supported in Vulkan Memory Model, and I see there is such statement in the [Vulkan SPEC](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#memory-model) "while GLSL (and legacy SPIR-V) applies the 'coherent' decoration to variables (for historical reasons), this model treats each memory access instruction as having optional implicit availability/visibility operations. ", maybe in the future we may not need to think about it in Vulkan?

> If you want read-only with wide feature support, why not just use SAMPLED_IMAGE / sampled2D? 

Read-only storage images are special snowflakes in the zoo of buffer types.
Because in Vulkan(SPIR-V) there are concepts of "NonReadable" and "NonWritable" and in Metal "```sample```", "```read```", "```write```", and "```readwrite```" are different attributes. It will be unfortunate if we can only translate all "storage textures" into UAVs on D3D and limit the usage of storage textures into only a small set of texture formats.

**Comment by HansKristian-Work** [comment]
Well, I think WebGPU in that case needs to spec out exactly what a SPIR-V resource type should translate to in all target languages, because I'm getting kinda confused as to what you're trying to achieve with a "read-only storage image" type to begin with, if you're not going to emit UAVs. If you're emitting an SRV, that's a classic sampled image, not storage image.

Note that storage images can also be buffer types, i.e. typed buffers, which can be further subdivided into "samplerBuffer" or "imageBuffer" in GLSL or `Buffer<T>` vs `RWBuffer<T>` in HLSL.

I would recommend not to look at NonReadable/Writable too deeply. To me, they're mostly hints which guide optimization, not fundamental attributes of the type. Unfortunately, MSL is annoying here with its image attributes which we try to translate depending on various inputs.

FWIW, I'm open to adding some mechanism to emit very specific resource types for given resource types in SPIR-V if this is truly needed.

**Comment by Kangz** [comment]
To provide more context, in WebGPU we need to separate between the `readonly-storage-texture` and `writeonly-storage-texture` because of Metal devices that we target. (`readwrite-storage-texture` will come later, for example as an extension for devies that support it). In general WebGPU tries to prevent data races and in particular it is invalid to use the same subresources as both `readonly-storage-texture` and `writeonly-storage-texture`.

However it should be valid to use a texture at the same time as `sampled-texture` and `readonly-storage-texture`. However in D3D12 it is invalid to transition a resource to `D3D12_RESOURCE_STATE_UNORDERED_ACCESS | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE`. So we are looking at supporting `readonly-storage-texture` via the SRV path. AFAIU all the readonly `RWTexture2D` operations are available on `Texture2D` so what's preventing supporting `NonWritable` `Sampled=2` textures via that path?

Also WebGPU will likely never support "samplerBuffer" or "imageBuffer".

**Comment by HansKristian-Work** [comment]
Hm, but if you're supposed to be able to use a texture at the same time with sampled-texture and readonly-storage-texture, why even support readonly-storage-texture?

There are some other problems though. I assume in this model, each resource in the bind group itself would be flagged as readonly-storage-texture vs writeonly-storage-texture?

I can see some problems with function calls, e.g. say we have a GLSL shader doing this:

```
layout(set = 0, binding = 0) readonly uniform image2D uImage0;
layout(set = 0, binding = 1) uniform image2D uImage1;
layout(location = 0) out vec4 FragColor;

vec4 load_image(image2D img, ivec2 coord)
{
    return imageLoad(img, coord);
}

void main()
{
    FragColor = load_image(uImage0, ivec2(10));
    FragColor += load_image(uImage1, ivec2(20));
}
```
Now, if we say that `uImage1` is readonly-storage-image and `uImage2` is readwrite-storage-texture in the bind group declaration. In this model, uImage1 will be declared as a texture2D instead, and we can no longer pass the image argument to `load_image`, as there is now a conflict.

**Comment by HansKristian-Work** [comment]
I suppose it might be possible to do this correctly if WebGPU enforces that:

- Storage images and any function parameters must be declared with either NonReadable or NonWritable, or neither. Declaring both would not be allowed. This way we can statically determine readonly/writeonly/readwrite. Vulkan or SPIR-V specs don't mandate that these decorations are actually used by shaders unless in certain scenarios like when Read/WriteWithoutFormat or fragmentStorageAndAtomics are not supported for example, just to aid validation. Essentially, WebGPU would have to treat these decorations as part of the type system, with strict validation. HLSL compilers will not emit these decorations however, so relying on these decorations seems rather scary.
- Decorations must match exactly between caller and callee. I don't think SPIR-V specifies this particularly well ...

If there are some rules like that, then it's not terribly hard to add options like "treat readonly texture resources as SRV always" and similar for buffer objects.

**Comment by HansKristian-Work** [comment]
@Jiawei-Shao regarding the weird decoration setting in https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_parser.cpp#L714, that's actually a bug. Not sure how that old hack has been lingering for so long without detection. There a PR in flight which fixes that:
https://github.com/KhronosGroup/SPIRV-Cross/pull/1287. It also tweaks a few things, e.g. being able to force UAV for a readonly SSBO. Forcing Texture instead of RWTexture on readonly would be a very similar and trivial change if required, just please consider the implications it has as stated above.

**Comment by Kangz** [comment]
> Storage images and any function parameters must be declared with either NonReadable or NonWritable, or neither.

That seems fine but if like you said it is a problem for HLSL maybe we'll need a legalization pass before SPIRV-Cross to add the correct decorations. +CC @zoddicus @dj2, does it sound ok to require the access flags of textures to match exactly at function calls?

**Comment by Jiawei-Shao** [comment]
I have verified now both NonReadable and NonWritable are set correctly on storage images on D3D12. Thanks for your fix!

**Comment by HansKristian-Work** [comment]
This specific issue can be closed I think since it refers to the parser bug. If you need SRV readonly storage images, please open another issue.

**Comment by Jiawei-Shao** [comment]
> This specific issue can be closed I think since it refers to the parser bug. If you need SRV readonly storage images, please open another issue.

I've filed the issue here: https://github.com/KhronosGroup/SPIRV-Cross/issues/1306
PTAL, thanks!
