### ISSUE TITLE
GLSL to readable HLSL

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/SPIRV-Cross#1291]
To ease porting of old GLSL shaders to HLSL, I wonder is there a way to compile GLSL to SPIR-V with all the debug symbols and all other info turned on and convert that SPIR-V to readable HLSL that preserves the original GLSL variable names, code structure and everything?

Thanks!

**Comment by HansKristian-Work** [comment]
glslang? GLSL -> SPIR-V without optimizations results in very close codegen to the original.

**Comment by procedural** [comment]
> glslang?

Yep.

> GLSL -> SPIR-V without optimizations results in very close codegen to the original.

Cool, I haven't tried converting GLSL to HLSL this way yet, but I wonder how close will it be...

**Comment by HansKristian-Work** [comment]
Doesn't seem to any further actionable items here, so closing.

**Comment by procedural** [comment]
I doubt it will be readable and close to original, tho :P

**Comment by procedural** [comment]
What I should probably ask is this: what is the way, and is there a way, to convert GLSL to HLSL 1:1 with SPIRV-Cross in-between, and what should glslang and SPIRV-Cross do to make it happen?... I doubt it will be as easy as `glslangValidator input.glsl -o output.spv && spirv-cross output.spv -o output.hlsl`...

**Comment by HansKristian-Work** [comment]
That's basically it, yes. Well, HLSL does need some wrapper stuff, but it's not that bad.
```
#version 450

layout(location = 0) out vec4 FragColor;
layout(location = 0) in vec2 vUV;
layout(set = 0, binding = 0) uniform texture2D uTex;
layout(set = 0, binding = 1) uniform sampler uSamp;

layout(set = 0, binding = 2) uniform UBO
{
	int count;
} ubo;

void main()
{
	FragColor = vec4(0.0);
	for (int i = 0; i < ubo.count; i++)
	{
		FragColor += texture(sampler2D(uTex, uSamp), vUV + 0.1 * float(i));
	}
}
```
`glslangValidator -H -V -o test.spv test.frag && spirv-cross test.spv --vulkan-semantics`
```
#version 450

layout(set = 0, binding = 2, std140) uniform UBO
{
    int count;
} ubo;

layout(set = 0, binding = 0) uniform texture2D uTex;
layout(set = 0, binding = 1) uniform sampler uSamp;

layout(location = 0) out vec4 FragColor;
layout(location = 0) in vec2 vUV;

void main()
{
    FragColor = vec4(0.0);
    for (int i = 0; i < ubo.count; i++)
    {
        FragColor += texture(sampler2D(uTex, uSamp), vUV + vec2(0.100000001490116119384765625 * float(i)));
    }
}
```
`glslangValidator -H -V -o test.spv test.frag && spirv-cross test.spv --hlsl --shader-model 50`
```
cbuffer UBO : register(b2)
{
    int ubo_count : packoffset(c0);
};

Texture2D<float4> uTex : register(t0);
SamplerState uSamp : register(s1);

static float4 FragColor;
static float2 vUV;

struct SPIRV_Cross_Input
{
    float2 vUV : TEXCOORD0;
};

struct SPIRV_Cross_Output
{
    float4 FragColor : SV_Target0;
};

void frag_main()
{
    FragColor = 0.0f.xxxx;
    for (int i = 0; i < ubo_count; i++)
    {
        FragColor += uTex.Sample(uSamp, vUV + (0.100000001490116119384765625f * float(i)).xx);
    }
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    vUV = stage_input.vUV;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.FragColor = FragColor;
    return stage_output;
}
```
