### ISSUE TITLE
include/spirv_cross/sampler.hpp has wrong type for wrap_t

### ISSUE THREAD

**Issue by kig** [KhronosGroup/SPIRV-Cross#1293]
Hi, the file include/spirv_cross/sampler.hpp has a sampler `wrap_t` defined with the `format` type, which errors on recent versions of Clang.

https://github.com/KhronosGroup/SPIRV-Cross/blob/7d42fd7f7b8bd92a57a6a7745f9841a1128f58f7/include/spirv_cross/sampler.hpp#L88
When I change it to the following, the compile error goes away
```c
spirv_cross_wrap wrap_t;
```

**Comment by HansKristian-Work** [comment]
Fixed on master.
