### ISSUE TITLE
Initializing variables for webGPU

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Cross#1298]
See https://github.com/KhronosGroup/SPIRV-Tools/issues/3244 for some background.

For WebGPU, we need all variables to be initialized.  In some cases, spirv-cross will create new variable to handle OpPhi instructions, and they will not have an initializer.  Would it be possible, under an option, to generate an initializer for those variables?

**Comment by HansKristian-Work** [comment]
It should be possible to add an option which forces all variables to be initialized to 0.
