### ISSUE TITLE
MSL - 'user' attribute cannot be applied to types

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#130]
I am trying to get the red triangle running on Metal, using the following shader:

GLSL source:
```
// vert
#version 450
in vec3 pos;
void main() {
	gl_Position = vec4(pos, 1.0);
}

// frag
#version 450
out vec4 fragColor;
void main() {
	fragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
```

MSL output:
```
// vert
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct simple_vert_main_in
{
    float3 pos [[attribute(0)]];
};

struct simple_vert_main_out
{
    // !Parse issue: 'user' attribute cannot be applied to types
    float4 gl_PerVertex_gl_TexCoord[1] [[user(locn0)]];
    float4 gl_PerVertex_gl_FrontSecondaryColor [[user(locn0)]];
    float4 gl_PerVertex_gl_FrontColor [[user(locn0)]];
    float gl_PerVertex_gl_FogFragCoord [[user(locn0)]];
    float4 gl_PerVertex_gl_ClipVertex [[user(locn0)]];
    float4 gl_PerVertex_gl_BackSecondaryColor [[user(locn0)]];
    float4 gl_PerVertex_gl_BackColor [[user(locn0)]];
    float4 gl_Position [[position]];
    float gl_PointSize;
    float gl_ClipDistance[1] /* [[clip_distance]] built-in not yet supported under Metal. */;
    float gl_BuiltIn_4[1];
};

vertex simple_vert_main_out simple_vert_main(simple_vert_main_in in [[stage_in]], uint gl_VertexID [[vertex_id]], uint gl_InstanceID [[instance_id]])
{
    simple_vert_main_out out = {};
    out.gl_Position = float4(in.pos, 1.0);
    out.gl_Position.z = (out.gl_Position.z + out.gl_Position.w) * 0.5;       // Adjust clip-space for Metal
    return out;
}

// frag
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct simple_frag_main_out
{
    float4 fragColor [[color(0)]];
};

fragment simple_frag_main_out simple_frag_main()
{
    simple_frag_main_out out = {};
    out.fragColor = float4(1.0, 0.0, 0.0, 1.0);
    return out;
}

```

At compile time, the line
`float4 gl_PerVertex_gl_TexCoord[1] [[user(locn0)]];`
throws *'user' attribute cannot be applied to types*.

Blindly changing the line to
`float4 gl_PerVertex_gl_TexCoord [[user(locn0)]];`
seems to get past the error and the beloved red triangle shows up.

Given my limited MSL knowledge so far, am I missing something?

I am using SPIRV-Cross through [krafix](https://github.com/Kode/krafix), macos 10.11.6, XCode 8.2.1.

**Comment by HansKristian-ARM** [comment]
The problem here seems to be that a lot of legacy-related vertex varyings are used in the SPIR-V output, but I don't see how this happens since my glslang does not emit these legacy variables (gl_TexCoord, gl_FrontColor, etc).

Which compiler/version did you use to generate this SPIR-V?

**Comment by luboslenco** [comment]
I will have to dig through the krafix pipeline to figure out why the legacy stuff happens.

Will begin by compiling krafix using the latest glslang and check if there are any odd flags/versions being passed around. Not an issue of SPIRV-Cross though.

Thanks!

**Comment by RobDangerous** [comment]
For reference, this happens when glslang is used without EShMsgSpvRules which otherwise works fine (though probably mostly by accident) to enable older style glsl to also work (varying, gl_FragColor,...).
