### ISSUE TITLE
Function containing "discard" is stripped when the return value is not used by caller

### ISSUE THREAD

**Issue by limingchina** [KhronosGroup/SPIRV-Cross#1304]
When a function's return value is not used by the caller, it gets stripped during the shader conversion. However, the function could contain "discard" which would affect the control flow.

I have the following fragment shader FunctionNotCalled.frag. 

+++++++++++++++++
#version 450
#pragma debug(on)
layout(location = 1) in vec4 voColor;
layout(location = 0) out vec4 poColor;

float DiscardFragments(float value)
{
    if (value > 0.5)
        discard;
    return value;
}

void main()
{
    DiscardFragments(voColor.a);
    poColor = voColor;
 }
+++++++++++++++++

After converting to spirv and then to msl, the DiscardFragments call gets removed.
`glslangValidator FunctionNotCalled.frag -V -o FunctionNotCalled.spir`
`spirv-cross --msl FunctionNotCalled.spirv -o FunctionNotCalled.metal`

Here is the metal shader output:
+++++++++++++++++
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 poColor [[color(0)]];
};

struct main0_in
{
    float4 voColor [[user(locn1)]];
};

inline float DiscardFragments(thread const float& value)
{
    if (value > 0.5)
    {
        discard_fragment();
    }
    return value;
}

fragment main0_out main0(main0_in in [[stage_in]])
{
    main0_out out = {};
    float param = in.voColor.w;
    out.poColor = in.voColor;
    return out;
}
+++++++++++++++++

When I remove the return value from the function **DiscardFragments**, the result is expected. This also happens for hlsl shader output for spriv-cross

**Comment by HansKristian-Work** [comment]
This works as expected on master. This was fixed many months ago in bfa76ee2ab5319734d84126f8bd20e7ddf44a78a.

**Comment by limingchina** [comment]
Thanks. I've checked. With the latest master, the function is not stripped. Sorry for the noise.
