### ISSUE TITLE
HLSL: SV_Position becomes undefined gl_FragCoord

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/SPIRV-Cross#131]
Hi,

I'm not sure if this is a supported path or I'm just doing something completely silly. I have the following HLSL shader that comes back out of SPIRV-Cross via the HLSL generator with gl_FragCoord being used but not defined:
```C
struct VSOutput {
  float4 Position  : SV_POSITION;
  float3 Color     : COLOR;
  float2 TexCoord0 : TEXCOORD0;
};

float4 PSMain(VSOutput In) : SV_TARGET
{
  return float4(In.Color, 1);
}
```

Here is the resulting shader:
```C
struct VSOutput
{
    float4 Position;
    float3 Color;
    float2 TexCoord0;
};

struct VSOutput_1
{
    float3 Color;
    float2 TexCoord0;
};

static float4 In_Position;
static struct VSOutput_1 In;
static float4 _entryPointOutput;

struct InputFrag
{
    struct VSOutput_1 In : TEXCOORD0;
    float4 In_Position : TEXCOORD2;
};

struct OutputFrag
{
    float4 _entryPointOutput : COLOR;
};

float4 _PSMain(struct VSOutput In_1)
{
    return float4(In_1.Color, 1.0f);
}

void frag_main()
{
    struct VSOutput In_1;
    In_1.Position = gl_FragCoord; // HERE
    In_1.Color = In.Color;
    In_1.TexCoord0 = In.TexCoord0;
    struct VSOutput param = In_1;
    _entryPointOutput = _PSMain(param);
}

OutputFrag main(InputFrag input)
{
    In_Position = input.In_Position;
    In = input.In;
    frag_main();
    OutputFrag output;
    output._entryPointOutput = _entryPointOutput;
    return output;
}
```

From the debugger, I can see that it does map to In_Position, but it's looking like because of the FragCoord decorator generated by glslang, it's getting remapped to gl_FragCoord?

I'm using 50 for the shader_model compiler option. Is there something I'm missing?

**Comment by HansKristian-ARM** [comment]
Looking over the HLSL backend, the builtin support seems to only handle gl_Position for the most part at the moment. A quick hack seems to be able to fix it, but will need some thinking to do it in a clean way.

**Comment by HansKristian-ARM** [comment]
@RobDangerous I have an idea how to fix this, so I can do it.

**Comment by HansKristian-ARM** [comment]
Should work in this PR: https://github.com/KhronosGroup/SPIRV-Cross/pull/136

**Comment by chaoticbob** [comment]
Thanks for the quick fix - I'll give it ago.

**Comment by HansKristian-ARM** [comment]
Fixed on master.
