### ISSUE TITLE
[Question] How to tell which UBO members are actually used with the reflection API?

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1312]
Hi, is it currently possible to tell which UBO members are actually used ( as you would do with e.g. `if(D3D12_SHADER_VARIABLE_DESC.tFlags & D3D_SVF_USED)` for DX11/DX12 reflection)? Note that we're not actually interested in transpiring to a different language here, we're using the C reflection API on SPIR-V emitted from DXC to target Vulkan.

I tried to do something of the sort:
```
    spvc_set activeInterfaceVariables;
    result = spvc_compiler_get_active_interface_variables(spvCompiler, &activeInterfaceVariables);
    DebugAssert(result == SPVC_SUCCESS);

    result = spvc_compiler_create_shader_resources_for_active_variables(spvCompiler, &spvResources, activeInterfaceVariables);
    DebugAssert(result == SPVC_SUCCESS);

    result = spvc_compiler_set_enabled_interface_variables(spvCompiler, activeInterfaceVariables);
    DebugAssert(result == SPVC_SUCCESS);
```
but the member count in the resulting UBO resources does not get reduced (assuming I'm calling them correctly), I'm guessing the code example in https://github.com/KhronosGroup/SPIRV-Cross/pull/45 is only for unused resource elimination, not for individual constants?
Sorry if this has been answered elsewhere, the PR link above was the closest thing I could find.

**Comment by HansKristian-Work** [comment]
There is an API to query which members of a UBO is statically accessed, but it does not affect codegen as that would require awkward padding. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L231. It might not be exposed to the C API yet though.

**Comment by Dredhog** [comment]
Hmm, I see that this function **is** already exposed to the C API https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross_c.h#L856. Thank you, this looks like what I needed!

**Comment by chromedays** [comment]
How did you use get_member_decoration to tell if the member is actually used or not?

**Comment by Dredhog** [comment]
@chromedays I didn't use `get_member_decoration`, it only looks that way since the line reference in my link has rotted... (as the link is always pointing to the most recent master while the line number is hardcoded).

If you check the history of the file at the time I posted the message (07 Apr 2020) it's actually pointing to `spvc_compiler_get_active_buffer_ranges` https://github.com/KhronosGroup/SPIRV-Cross/blob/941cceedb4f0e6280fc7fa4a71c1ebff8955198a/spirv_cross_c.h#L856. Good luck!

**Comment by chromedays** [comment]
@Dredhog Ahh I see. Thanks! The links to both c and cpp apis were coincidentally pointing get_member_decoration lol.
