### ISSUE TITLE
Compatibility with clang-cl

### ISSUE THREAD

**Issue by Malacath-92** [KhronosGroup/SPIRV-Cross#1315]
When building SPRIV-Cross with clang-cl
```sh
cmake .. -G"Visual Studio 16 2019" -T ClangCL
cmake --build .
```
I get tons of warnings that are neither present on a regular clang build nor an MSVC build.
I'm not sure why many of these warnings are enabled by `-Wall` in clang-cl but not in regular clang.
I am wondering if the strategy here should be to just disable those warnings from cmake if clang-cl is detected or if some should be fixed.

Detecting clang-cl is easy using the CMAKE_CXX_SIMULATE_ID and I'd be happy to fix up a PR to make SPIRV-Cross clang-cl compatible.

For completeness, the list of warning categories is the following:
```
-Wunused-macros
-Wsign-conversion
-Wswitch-enum
-Wdouble-promotion
-Wold-style-cast
-Wdeprecated
-Wmicrosoft-enum-value
-Wcovered-switch-default
-Wimplicit-fallthrough
-Wexit-time-destructors
-Wduplicate-enum
-Wsign-compare
-Wrange-loop-analysis
-Wfloat-equal
-Wunreachable-code-break
-Wunreachable-code-return
-Wc++98-compat
-Wc++98-compat-pedantic
```

Edit: Correction after reading the docs closer I can see that clang-cl maps MSVC warning levels as follows
```
  /W0                     Disable all warnings
  /W1                     Enable -Wall
  /W2                     Enable -Wall
  /W3                     Enable -Wall
  /W4                     Enable -Wall and -Wextra
  /Wall                   Enable -Weverything
```
So -Wall is probably mapped to -Weverything. The warning levels thus need to be only properly adjusted for clang-cl

**Comment by HansKristian-Work** [comment]
I don't particularly care about clang-cl w.r.t. warnings, but if you PR it and it's not too annoying, it can be merged.

**Comment by Malacath-92** [comment]
I see that this stuff is mainly maintained for gcc and clang, I'm only suggesting it for the sake of giving clang-cl user a warning-free compile as well.
