### ISSUE TITLE
MSL : spirv-cross delete unused uniform variables when converting spv into msl

### ISSUE THREAD

**Issue by lch32111** [KhronosGroup/SPIRV-Cross#1317]
Hi. I'm using glslang and spirv-cross to implement cross-compile system. I'm saving the uniform variables into a file for compiling shaders for multiple platforms. The problem is..

When I declare texture resource and uniform buffer block, which are unused in the shader now, spirv-cross delete the unused resources when converting spv into msl, even if spv code has the information about the unused resources.

Here is the codes
[spv code.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/4459704/spv.code.txt)
[msl code.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/4459706/msl.code.txt)

The declarations of unused resource are
```
uniform mediump sampler2D texA;
uniform mediump sampler2DArray texB;

layout(set = 3, std140, binding = 7) uniform specialUBO
{
    vec3 test;
} special_ubo;

layout(set = 2, binding = 4) uniform mediump samplerCube texC;
```

I wonder this is the expected result or not. And Can I keep these unused variables on the spriv-cross result?

Thanks

**Comment by HansKristian-Work** [comment]
This is expected. There is currently no way of forcing unused resources to be declared, unless you're using indirect argument buffers, in which case there is an option for it, since it can affect ABI.

**Comment by lch32111** [comment]
Okay. Thanks!
