### ISSUE TITLE
MSL: Is it possible to disable vertex shader's custom output attribute [[user(clipN)]]?

### ISSUE THREAD

**Issue by kakashidinho** [KhronosGroup/SPIRV-Cross#1320]
As far as I understand, this commit [a3fe9756](https://github.com/KhronosGroup/SPIRV-Cross/commit/a3fe9756d280898bc20207a5046d665ebfc1dc3d) introduced custom output variable with attribute `[[user(clipN)]]` along side the normal `[[clip_distance]]` variable to vertex shader if `gl_ClipDistance` is encountered.

Isn't it a bit waste of output vector slot if fragment shader never need it? If vertex shader write to 8 `[[clip_distance]]` elements, 8 more `[[user(clipN)]]` variables will be inserted to its output struct.
I'm not sure whether Metal internal pipeline compiler will automatically strip unused vertex shader's output variables or not.

Is there any option to disable this custom output variable?

Thanks.

**Comment by HansKristian-Work** [comment]
I don't think there is an option to remove them, but it is not hard to add an opt-in path where you know clip distances won't ever be read in fragment.

**Comment by kakashidinho** [comment]
Thanks for the update
