### ISSUE TITLE
[MSL] SPIRV-Cross assumes std140 layout and fails with SPIR-V generated with DXC's -fvk-use-dx-layout option

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1321]
This issue seems highly related to the assumption about float array implementation mentioned in https://github.com/KhronosGroup/SPIRV-Cross/pull/134#issuecomment-287390362.

It seems that currently a float array is expanded to a float4 array of the same length with the assumption that every element takes up 16 bytes, which is not the case when generating SPIR-V with DXC with the `-fvk-use-dx-layout` option, which packs UBOs and SSBOs in DirectX's format. In the following snippet the last element of the UBO member `Float_16` should not be padded
```
cbuffer NamedCBuffer
{
    float Float_16[15];
    float Float_0;
};

RWBuffer<float> Result; 

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[id.x] = Float_0;
}
```

Passing this snippet through DXC with the CLI command:
`dxc.exe repro_shader.txt -spirv -fvk-use-dx-layout -E CSMain -T cs_6_0`

generates the following SPIR-V:
```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 26
; Schema: 0
               OpCapability Shader
               OpCapability SampledBuffer
               OpCapability ImageBuffer
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %CSMain "CSMain" %gl_GlobalInvocationID
               OpExecutionMode %CSMain LocalSize 8 8 1
               OpSource HLSL 630
               OpName %type_NamedCBuffer "type.NamedCBuffer"
               OpMemberName %type_NamedCBuffer 0 "Float_16"
               OpMemberName %type_NamedCBuffer 1 "Float_0"
               OpName %NamedCBuffer "NamedCBuffer"
               OpName %type_buffer_image "type.buffer.image"
               OpName %Result "Result"
               OpName %CSMain "CSMain"
               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %NamedCBuffer DescriptorSet 0
               OpDecorate %NamedCBuffer Binding 0
               OpDecorate %Result DescriptorSet 0
               OpDecorate %Result Binding 1
               OpDecorate %_arr_float_uint_15 ArrayStride 16
               OpMemberDecorate %type_NamedCBuffer 0 Offset 0
               OpMemberDecorate %type_NamedCBuffer 1 Offset 228
               OpDecorate %type_NamedCBuffer Block
        %int = OpTypeInt 32 1
      %int_1 = OpConstant %int 1
       %uint = OpTypeInt 32 0
    %uint_15 = OpConstant %uint 15
      %float = OpTypeFloat 32
%_arr_float_uint_15 = OpTypeArray %float %uint_15
%type_NamedCBuffer = OpTypeStruct %_arr_float_uint_15 %float
%_ptr_Uniform_type_NamedCBuffer = OpTypePointer Uniform %type_NamedCBuffer
%type_buffer_image = OpTypeImage %float Buffer 2 0 0 2 R32f
%_ptr_UniformConstant_type_buffer_image = OpTypePointer UniformConstant %type_buffer_image
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
       %void = OpTypeVoid
         %18 = OpTypeFunction %void
%_ptr_Uniform_float = OpTypePointer Uniform %float
%NamedCBuffer = OpVariable %_ptr_Uniform_type_NamedCBuffer Uniform
     %Result = OpVariable %_ptr_UniformConstant_type_buffer_image UniformConstant
%gl_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input
     %CSMain = OpFunction %void None %18
         %20 = OpLabel
         %21 = OpLoad %v3uint %gl_GlobalInvocationID
         %22 = OpAccessChain %_ptr_Uniform_float %NamedCBuffer %int_1
         %23 = OpLoad %float %22
         %24 = OpCompositeExtract %uint %21 0
         %25 = OpLoad %type_buffer_image %Result
               OpImageWrite %25 %24 %23 None
               OpReturn
               OpFunctionEnd

```
If the `-fvk-use-dx-layout` were omitted the line `OpMemberDecorate %type_NamedCBuffer 1 Offset 228`
would become ` OpMemberDecorate %type_NamedCBuffer 1 Offset 240` which is what SPIRV-Cross expects.

That is `Float_0` should end up at offset 228 with DX layout and not 240.

SPIRV-Cross ends up returning SPVC_ERROR_UNSUPPORTED_SPIRV after the following part of the code returns `false` in `spirv_msl.cpp`:

```
	if (!mbr_type.array.empty())
	{
		// If we have an array type, array stride must match exactly with SPIR-V.
		uint32_t spirv_array_stride = type_struct_member_array_stride(type, index);
		uint32_t msl_array_stride = get_declared_struct_member_array_stride_msl(type, index);
		if (spirv_array_stride != msl_array_stride)
			return false;
	}
```

We at Unity would like to use SPIRV-Cross for MSL generation and would prefer the constant buffers in MSL to have binary compatibility with other platforms such as DX, which is the standard for us.

Since the use of the dx-layout is not indicated anywhere in the SPIR-V, it seems that this issue could be addressed with an additional option to SPIRV-Cross telling it to expect and emit DirectX layout conformant MSL. A possible solution that comes to mind would be instead of generating a float4 array, generate an array of floats with a size that fills the inner padding and only pads the last element when to match DirectX's layout. e.g. doing something like `float Float16[15*4-3];` in this particular case (the name Float16 here is just to match the snippet, it is not intended to help in explaining)

**Comment by HansKristian-Work** [comment]
Buffer layout can only be deduced directly from Offset/ArrayStride/MatrixStride, there will not be an option to handle this. This detail of DX layout is surprising to me.

Reading the Vulkan spec, this kind of buffer layout requires scalar block layout:

```
Unless the scalarBlockLayout feature is enabled on the device:
• Vectors must not improperly straddle, as defined above.
• The Offset decoration of a member **must not place it between the end of a structure or an array
and the next multiple of the alignment of that structure or array**.
```

Is it intentional for DXC to emit ArrayStride of 16 here at all? DXC might as well just emit flat ArrayStride of 4 here. It might be possible to emit that workaround in SPIRV-Cross, and it seems it might be required for scalar block layout, which is a shame ...

**Comment by HansKristian-Work** [comment]
I'll give it a spin, worst case, DXC could support a std140 friendly mode for CBV which does not rely on scalar block layout where the UBO is represented as a plain vec4 array like DXBC/DXIL.

**Comment by Dredhog** [comment]
> It might be possible to emit that workaround in SPIRV-Cross, and it seems it might be required for scalar block layout, which is a shame ...

Given that SPIRV-Cross intends to support scalar layout (from what I've seen in the code) it would be desirable that DX layout could be handled as well, since it does not introduce any permissions which are not present in scalar block layout. To this point the DXC Vulkan doc says: 

> To use scalar layout, the application side need to request VK_EXT_scalar_block_layout. This is also true for using DirectX memory layout since there is no dedicated DirectX layout extension for Vulkan (at least for now). So we must request something more permissive.

in the section about memory layout rules
https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#memory-layout-rules

>I'll give it a spin, worst case, DXC could support a std140 friendly mode for CBV which does not rely on scalar block layout where the UBO is represented as a plain vec4 array like DXBC/DXIL.

It would be great if SPIRV-Cross could address this! DXC does support a combined std140/std430 mode with `-fvk-use-gl-layout` which is essentially the default, but it's not compatible with the DirectX layout, which is the key here. Sadly, as the previous quote from DXC says you cannot have dx layout without conforming to scalar layout currently.

**Comment by Dredhog** [comment]
Awesome, thank you!
