### ISSUE TITLE
SPIRV: No new ray query opcodes

### ISSUE THREAD

**Issue by erymin** [KhronosGroup/SPIRV-Cross#1333]
I use SPIRV-Cross for shader reflection and it seems that new ray query related opcodes have not been added yet to spirv-cross.
Will it be added in the future?

**Comment by HansKristian-Work** [comment]
Do the new ray-tracing opcodes somehow affect shader reflection, do you have a failing SPIR-V?

**Comment by erymin** [comment]
Hi, @HansKristian-Work !
Yes, when I just do
`spirv_cross::CompilerGLSL glsl(spirv);`
it fails here: https://github.com/KhronosGroup/SPIRV-Cross/blob/58548e25a25b97d827c074bad3e9039e918f8cf2/spirv_parser.cpp#L1076

Opcode was not processed and I fall into the default branch but there's no current block for some reason.

Shader is really simple, just this:
`rayQueryEXT query;
 rayQueryInitializeEXT(query, g_scene_acceleration_structure, gl_RayFlagsTerminateOnFirstHitEXT, 1, vec3(0),0, vec3(1), 1e+6);`

**Comment by erymin** [comment]
@HansKristian-Work Thank you for the fast reaction, it works now!
