### ISSUE TITLE
Potentially illegal GLSL ES Output for WebGL

### ISSUE THREAD

**Issue by tjachmann** [KhronosGroup/SPIRV-Cross#1341]
I have some SPIRV-V files that when converted to webgl (with --version 100 --es) generate code
thats not conform. More precisily they contain a switch statement. But switch is not supported by that glsl es version., resulting in a compiler error when used in webgl. So from my view this arguably a bug in the conversion from spirv-cross. 

In my current cases the switch statement is essentially deadcode, which I can get rid of by running through spirv-opt before converting to  GLSL ES. But I guess there will be other potential cases, where a switch statement is generated, that cannot be optimized away ahead, resulting in malformed output.

**Comment by HansKristian-Work** [comment]
It is implied that not all SPIR-V code can generate valid ESSL 1.0. The SPIR-V cannot use features which are not supported. Targeting ESSL 1.0 requires some cooperation from the user to make it work in any reasonable way.

I consider this not-a-bug. The work required to workaround this limitation is not worth it.
