### ISSUE TITLE
GLSL: Support `GL_KHR_shader_subgroup_ballot`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/SPIRV-Cross#1352]
`GL_KHR_shader_subgroup_ballot` is 1:1 match with OpenGL's `GL_ARB_shader_ballot` except that the masks and bitfileds are implemented as `uint64_t` not `uvec4`.

This makes it require `GL_ARB_gpu_shader_int64`, and not any of  `GL_AMD_gpu_shader_int64` or `GL_NV_gpu_shader5` because the `GL_ARB_shader_ballot` extension spec explicitly states the requirement for `GL_ARB_gpu_shader_int64`.

Some of functionality can also be implemented via `GL_NV_shader_thread_group` which if available should be preferred because it uses the `uint` type and all bitmask operations are 2x less complex.

The masks are easily defined as well as the ballot operations
```
#extension ARB_gpu_shader5 : require
#extension GL_NV_shader_thread_group : enable
#extension GL_NV_shader_thread_shuffle : enable
#ifdef GL_NV_shader_thread_group 
    gl_SubgroupEqMask = uvec4(gl_ThreadEqMaskNV,0u,0u,0u);
    gl_SubgroupGeMask = uvec4(gl_ThreadGeMaskNV,0u,0u,0u);
    gl_SubgroupGtMask = uvec4(gl_ThreadGtMaskNV,0u,0u,0u);
    gl_SubgroupLeMask = uvec4(gl_ThreadLeMaskNV,0u,0u,0u);
    gl_SubgroupLtMask = uvec4(gl_ThreadLtMaskNV,0u,0u,0u);

    subgroupBallot = uvec4(ballotThreadNV,0u,0u,0u)
#else
    #extension GL_ARB_shader_ballot : require
    #extension GL_ARB_gpu_shader_int64 : require

    gl_SubgroupEqMask = uvec4(unpackUint2x32(gl_SubGroupEqMaskARB),0u,0u);
    gl_SubgroupGeMask = uvec4(unpackUint2x32(gl_SubGroupGeMaskARB),0u,0u);
    gl_SubgroupGtMask = uvec4(unpackUint2x32(gl_SubGroupGtMaskARB),0u,0u);
    gl_SubgroupLeMask = uvec4(unpackUint2x32(gl_SubGroupLeMaskARB),0u,0u);
    gl_SubgroupLtMask = uvec4(unpackUint2x32(gl_SubGroupLtMaskARB),0u,0u);

    subgroupBallot = uvec4(unpackUint2x32(ballotARB),0u,0u)
#endif 

#define CAN_USE_NV_SHUFFLES (defined(GL_NV_shader_thread_group) && defined(GL_NV_shader_thread_shuffle))
T subgroupBroadcastFirst(T value)
{
#ifdef GL_NV_shader_thread_shuffle
    return shuffleNV(value,0,gl_WarpSizeNV); 
#else
    return readFirstInvocationARB(value);
#endif 
}

T subgroupBroadcast(T value,  uint id)
{
#ifdef GL_NV_shader_thread_shuffle 
    return shuffleNV(value,index,gl_WarpSizeNV);
#else
    return readInvocationARB(value,id);
#endif 
}
#undef CAN_USE_NV_SHUFFLES 

uint subgroupBallotFindLSB(uvec4 value)
{
#ifdef GL_NV_shader_thread_group 
    return findLSB(value.x);
#else 
    int firstLive = findLSB(value.x);
    return uint(firstLive!=-1 ? firstLive:(findLSB(value.y)+32));
#endif 
}

uint subgroupBallotFindMSB(uvec4 value)
{
#ifdef GL_NV_shader_thread_group 
    return findMSB(value.x);
#else 
    int firstLive = findMSB(value.y);
    return uint(firstLive!=-1 ? (firstLive+32):findMSB(value.x));
#endif 
}
```

The rest of can be implemented in terms of the above operations, with optimization for `GL_NV_shader_thread_group` to make the ops run on `.x` instead of the `.xy` part of the `value` so that the bitfield operations introduced in `ARB_gpu_shader5` don't need to run twice.
```glsl
        bool subgroupInverseBallot(uvec4 value);
        bool subgroupBallotBitExtract(uvec4 value, uint index);
        uint subgroupBallotBitCount(uvec4 value);
        uint subgroupBallotInclusiveBitCount(uvec4 value);
        uint subgroupBallotExclusiveBitCount(uvec4 value);
```

P.S. `GL_KHR_shader_subgroup_shuffle`, `GL_KHR_shader_subgroup_shuffle_relative`, `GL_KHR_shader_subgroup_clustered`, `GL_KHR_shader_subgroup_quad` can only be implemented as either `GL_NV_shader_thread_shuffle`+`GL_NV_shader_thread_group` or `GL_AMD_shader_ballot`.

**Comment by devshgraphicsprogramming** [comment]
@HansKristian-Work I'm considering providing an implementation myself or assigning someone from my company to this.

How would you like to see the implementation approach this?

Any pointers or documentation on how the GLSL backend with no vulkan semantics should approach something like this?

My main questions are:
- how to emit the extensions so I can get the correct fallback `enable` / `require` chain
- obviously I cannot declare any `const` variable with a `gl_` prefix because that's not legal GLSL and driver won't compile such a shader... so I should emit some sort of a constant, what shall it be named?
- the functions, am I allowed to use the names from the original spec such as `subgroupInverseBallot` ? Should I prepare some sort of a constant header and inject it into the emitted final GLSL?

**Comment by devshgraphicsprogramming** [comment]
Naturally I understand that we'll have to implement #1351 as well since any `GL_KHR_shader_subgroup_*` extension implicitly enables `GL_KHR_shader_subgroup_basic`

Have you got any tests in your CI for `GL_KHR_shader_subgroup` containing shaders?

**Comment by HansKristian-Work** [comment]
For complex extension ladders, you can check for the KHR extension by name, and check if !vulkan_semantics, then emit a fallback chain. There are similar ladders for 8/16-bit arithmetic.

If you emit a constant, you can call it SPIRV_Cross_gl_something, and change the name where builtin name is queried depending on vulkan_semantic. You can emit these constants in emit_resources(). You should be able to detect if the capability is enabled and only emit builtin constants based on that.

To emit workaround functions for things like subgroupInverseBallot you can use the original name if it does not cause issues.

For test, see shaders-no-opt/comp/subgroups.nocompat.invalid.vk.comp. You can remove the nocompat to make it try to target desktop GLSL as well.

**Comment by devshgraphicsprogramming** [comment]
@HansKristian-Work would this PR be something that shows how to add a complex extension support when downcompiling SPIR-V to GLSL with vendor extensions
https://github.com/KhronosGroup/SPIRV-Cross/pull/338
?

**Comment by HansKristian-Work** [comment]
Not really, this is probably where you'll need to add those ladders. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L686
