### ISSUE TITLE
GLSL: generate "hand-unrolled" loops for OpLoopMerges with "Unroll"

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/SPIRV-Cross#1358]
Context: at least on some mobile platforms hand-unrolling GLSL loops still appears to make a difference. 

In HLSL, the `[unroll]` directive causes the compiler DirectXShaderCompiler to emit loops with `OpLoopMerge`s tagged with `Unroll`. However, SPIRV-Cross (or at least the GLSL backend) appears to ignore the loop control part of the instruction, and produces GLSL that has a normal-looking loop.

It would be nice if there was an option to emit code equivalent to what a hand-unrolled loop would look like in this cases.

**Comment by HansKristian-Work** [comment]
No. This kind of transform belongs in spirv-opt, where it already exists. It has no place in SPIRV-Cross.
