### ISSUE TITLE
MSL: bool array in struct is translated to packed_uint array which is not a valid type.

### ISSUE THREAD

**Issue by kakashidinho** [KhronosGroup/SPIRV-Cross#1359]
Hi,
I tried to translate this GLSL:
```
#version 450 core
struct Struct
{
    bool flags[1];
};

layout(set=0, binding=0, std140) uniform defaultUniformsVS
{
    Struct flags;
    vec2 uquad[4];
    mat4 umatrix;
};

layout (location = 0) in vec4 a_position;

void main()
{
    gl_Position = umatrix * vec4(uquad[gl_VertexIndex], a_position.z, a_position.w);
    if (flags.flags[0])
        gl_Position.z = 0.0;
}
```

And got this MSL:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Struct
{
    packed_uint flags[1];
};

struct defaultUniformsVS
{
    Struct flags;
    float4 uquad[4];
    float4x4 umatrix;
};

struct main0_out
{
    float4 gl_Position [[position]];
};

struct main0_in
{
    float4 a_position [[attribute(0)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant defaultUniformsVS& _25 [[buffer(0)]], uint gl_VertexIndex [[vertex_id]])
{
    main0_out out = {};
    out.gl_Position = _25.umatrix * float4(_25.uquad[int(gl_VertexIndex)].x, _25.uquad[int(gl_VertexIndex)].y, in.a_position.z, in.a_position.w);
    if (uint(_25.flags.flags[0]) != 0u)
    {
        out.gl_Position.z = 0.0;
    }
    return out;
}
```

`bool` was translated to `packed_uint`. I don't think `packed_uint` is a valid type accepted by Metal compiler:
```
error: unknown type name 'packed_uint'
```
Only `packed_uint`2/3/4 are valid.

**Comment by kakashidinho** [comment]
Correct me if I’m wrong. But why an array with one element is relaxed now? It seems the relaxation doesn’t honor the std140 layout rule that array must be multiple of vec4 in size anymore.
Now uint [1] array will just be sizeof(uint) for example.

**Comment by kakashidinho** [comment]
I didn’t follow the dx layout not compatible with std140 topic. But if the code cannot handle these cases programmatically then maybe an explicit option could be helpful?

**Comment by HansKristian-Work** [comment]
MSL does not have any concept of std140 layout, it is packed similar to std430 always (with the difference that sizeof(float3) == 16). Emitting smaller sizes in MSL is generally always fine since we can pad out the difference. The other way however, won't work.

Is the current codegen wrong?

**Comment by HansKristian-Work** [comment]
DX layout allows for the last element of an array to be smaller than the array stride, which complicates things.

**Comment by kakashidinho** [comment]
Yes, you are right. My mistake, I just saw that the array is not multiple of vec4 anymore (previously bool[] would be translated to uint4[]) and thought it could mess up the next member's alignment. However, the next member in the example "float4" already has a correct alignment.
Thanks,
