### ISSUE TITLE
Provide `SPIRV_Cross_BaseInstance` from `gl_BaseInstance` if `GL_ARB_shader_draw_parameters` is available

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/SPIRV-Cross#1367]
I'd see the fix looking something like this

Extension "header"
```glsl
#extension GL_ARB_shader_draw_parameters : enable
```

Where you define `SPIRV_Cross_BaseInstance`
```glsl
#ifdef GL_ARB_shader_draw_parameters
#define SPIRV_Cross_BaseInstance gl_BaseInstance
#else 
uniform uint SPIRV_Cross_BaseInstance;
#endif 
```

A nearly identical "fix" is possible for `gl_BaseVertex`/`gl_VertexIndex`

**Comment by HansKristian-Work** [comment]
This seems pretty easy, I can look into this. gl_VertexIndex should match gl_VertexID semantics 1:1 though.
