### ISSUE TITLE
Add "deprecated" macro to allow Compiler methods to be marked as deprecated

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#137]
Currently, SPIRV-Cross code does not support declaring Compiler (and subclasses) methods to be deprecated. As the SPRIV-Cross code base matures, this will become necessary.

A general, cross-platform depreciation macro would be useful to allow this to be supported.

To clarify...I am referring to marking methods within the SPRIV-Cross code base itself as deprecated. I am not referring to marking functions within generated shader code as deprecated.

**Comment by HansKristian-ARM** [comment]
Fixed in https://github.com/KhronosGroup/SPIRV-Cross/pull/138
