### ISSUE TITLE
Wrong size of buffer-reference element returned from Reflection-API?

### ISSUE THREAD

**Issue by fynv** [KhronosGroup/SPIRV-Cross#1374]
I'm trying to inspect the following compute shader using the Reflection-API
```cpp
#version 460\n
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_buffer_reference2 : enable
layout(buffer_reference, std430, buffer_reference_align = 4) buffer IntBuf
{
	int v;
};
layout(std140, binding = 0) uniform Params
{
	float x;
	IntBuf y;
};
void main()
{
}
```
```cpp
spirv_cross::Compiler comp(std::move(spv));
ShaderResources res = comp.get_shader_resources();
auto ub = res.uniform_buffers[0];
auto type = comp.get_type(ub.base_type_id);
size_t size = comp.get_declared_struct_size(type);
printf("struct_size: %d\n", size);
unsigned num_members = type.member_types.size();
printf("num_members: %d\n", num_members);
size_t member_size = comp.get_declared_struct_member_size(type, 0);
printf("size of float: %d\n", member_size);
member_size = comp.get_declared_struct_member_size(type, 1);
printf("size of pointer: %d\n", member_size);
auto member_type = comp.get_type(type.member_types[1]);
member_size = comp.get_declared_struct_size(member_type);
printf("size of pointer: %d\n", member_size);
```
output:
struct_size: 12
num_members: 2
size of float: 4
size of pointer: 4
size of pointer: 4

If I change "int v;" to "int64_t v;", the output becomes:
struct_size: 16
num_members: 2
size of float: 4
size of pointer: 8
size of pointer: 8

I'm a little bit confused here. Is the size of a buffer reference related to its element type?

**Comment by fynv** [comment]
To make it clear, I'm expecting to always get "8" for a buffer reference, because at host-side, it is corresponding to a VkDeviceAddress value.

**Comment by HansKristian-Work** [comment]
Yes, it's a bug here where physical pointers would be reflected to have the size of its element.

**Comment by fynv** [comment]
Thanks! Actually, I found that reflections of "offset" and "stride" information are more useful for me than "size". Luckily, these have been working correctly for me so far. Anyway, nice to see you are fixing it!
