### ISSUE TITLE
GLSL: Is there a way to avoid duplicate uniform block instance name in GLSL Compiler?

### ISSUE THREAD

**Issue by koseonjae** [KhronosGroup/SPIRV-Cross#1382]
I write vertex and fragment shader as below.

# vertex
```
layout( location = 0 ) in vec3 aPosition;

layout( set = 0, binding = 0 ) uniform UniformVariables
{
    mat4 LocalToWorld;
    mat4 WorldToView;
    mat4 ViewToClip;
};

void main()
{
	mat4 MVP = ViewToClip * WorldToView * LocalToWorld;
	gl_Position = MVP * vec4( aPosition, 1.0 );
}

```

# fragment
```
precision mediump float;

layout( set = 0, binding = 1 ) uniform ColorProperties
{
    vec3 uColor;
};

layout( location = 0 ) out vec4 FragColor0;

void main()
{
	FragColor0 = vec4( uColor, 1.0 );
}
```

## and converted glsl shader code is here !!!

# vertex
```
#version 100

struct UniformVariables
{
    mat4 LocalToWorld;
    mat4 WorldToView;
    mat4 ViewToClip;
};

uniform UniformVariables _13;

attribute vec3 aPosition;

void main()
{
    mat4 MVP = (_13.ViewToClip * _13.WorldToView) * _13.LocalToWorld;
    gl_Position = MVP * vec4(aPosition, 1.0);
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}
```

# fragment
```
#version 100
precision mediump float;
precision highp int;

struct ColorProperties
{
    vec3 uColor;
};

uniform ColorProperties _13;

void main()
{
    gl_FragData[0] = vec4(_13.uColor, 1.0);
}
```

# question

the problem is that generated uniform block name is same as `_13`

so it causes problem on glLinkProgram

***L0001 The fragment structure variable _13 does not match the vertex variable _13.
The table members count does not match.***

I can avoid it with uniform block instance name like

```
layout(...) uniform UniformVariables
{
...
} UniformVariable;
```

```
layout(...) uniform ColorProperties
{
...
} ColorProperty;
```

but.. Is there any other solution without using set_name (https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L154)?
I tried glsl compiler options but cannot fix it.

Or.. Could this be a spirv-cross bug?

thanks!

**Comment by HansKristian-Work** [comment]
This is not a bug since SPIRV-Cross cannot know your intended naming scheme. You will need to either name the instances in the shader itself, or use the reflection API to assign names to the instance variables to make sure they match or don't match.
