### ISSUE TITLE
SPIRV_CROSS_DEPRECATED warning spam

### ISSUE THREAD

**Issue by bkaradzic** [KhronosGroup/SPIRV-Cross#1399]
Different compilers (and their versions) behave differently about deprecated. Clang doesn't like `SPIRV_CROSS_DEPRECATED` on `typedef`-s. MSVC complains that deprecated struct is used as argument of deprecated function. This causes deprecated warning spam even in projects that don't use deprecated code at all.

Would it be possible to move all deprecated code into separate `#ifdef` block, and disable it by default? Allow users who rely on deprecated code to enable it if needed?

**Comment by HansKristian-Work** [comment]
It's a bit of a mess that all the compilers behave so differently w.r.t. deprecation. I just removed the API in question that uses deprecated instead in the PR.
