### ISSUE TITLE
OpSwitch generated by spirv-opt

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/SPIRV-Cross#1406]
spirv-opt may generate OpSwitch during function inlining (KhronosGroup/SPIRV-Tools/issues/3244).
For example:

original shader
```
#version 450

layout(set = 0, binding = 0) uniform UBO
{
	int i;
};

vec4 test_func(bool compile_time_val, bool dynamic_val)
{
	if (compile_time_val || dynamic_val)
	{
		return vec4(0.0);
	}
	return vec4(1.0);
}

void main()
{
	gl_Position = test_func(false, i > 0);
}
```
after spirv-opt -O and spirv-cross --es --version 100
```
#version 100

struct UBO
{
    int i;
};

uniform UBO _38;

void main()
{
    vec4 _68;
    switch (0)
    {
        default:
        {
            if (false || (_38.i > 0))
            {
                _68 = vec4(0.0);
                break;
            }
            _68 = vec4(1.0);
            break;
        }
    }
    gl_Position = _68;
}

```
This code can't be compiled since "switch" is not supported by glsl es 100. Is there any way around this?

**Comment by HansKristian-Work** [comment]
Please try latest master, these switch blocks are converted to a `do/while(false)` block instead, since this pattern is buggy on FXC as well.

**Comment by konstantinegorov** [comment]
It may not work on some implementations of opengl es 2.0 since support for while, do-while is not mandated. Only simple form of for-loop is guaranteed to be supported.

**Comment by HansKristian-Work** [comment]
Does `break;` even work on such severely restricted implementations?

**Comment by konstantinegorov** [comment]
From the glsl es 100 spec:

> In general, control flow is limited to forward branching and to loops where the maximum number of
> iterations can easily be determined at compile time.
> Forward branching is allowed, both for constant and non-constant conditions. Therefore **if-then**, **if-thenelse**, **break** and **continue** statements are permitted.
