### ISSUE TITLE
Cross-compiling GLSL to HLSL produces invalid HLSL with overlapping register/spaces

### ISSUE THREAD

**Issue by cranflavin** [KhronosGroup/SPIRV-Cross#1407]
I am cross-compiling from GLSL to HLSL via SPIRV and ending up with HLSL that doesn't compile.  I believe the interesting bits of the GLSL shader are here:
```glsl
layout(set = 2, binding = 4) uniform texture2D light_textures[MAX_LIGHT_TEXTURES];
layout(set = 2, binding = 5) uniform texture2D shadow_textures[MAX_LIGHT_TEXTURES];
```
Produces this output in HLSL:
```hlsl
Texture2D<float4> light_textures[16] : register(t4, space2);
Texture2D<float4> shadow_textures[16] : register(t5, space2);
```
When you compile the HLSL, you end up with this error:

>error X4610: SRV binding ranges overlap for range T[5:20]

Manually changing the t5 above to t20 prevents the slots from overlapping and seems to solve the issue, since light_textures is an array of 16 float4.  Curious if I'm missing some configuration that would do this for me, or if this is a bug.

**Comment by cdavis5e** [comment]
By default, SPIRV-Cross just passes the binding information through. If you want the generated HLSL to have different bindings, you can pass some `HLSLResourceBinding` structures to the compiler. If you're using the command line, unfortunately there is no way to specify these yet.

**Comment by cranflavin** [comment]
It sounds like what I'd need to do is reflect over the SPIRV and build a custom resource mapping before compiling to HLSL?  I'm definitely new to this space.  Naively, I'd think it would be valuable to have an option to produce valid HLSL at the cost of changing the bindings automatically.  Then the HLSL could be compiled and reflected as DXBC to produce the root signatures for a DX12 implementation without the intermediate SPIRV reflection.

If it's a goal of the SPRIV -> HLSL compilation to produce valid HLSL that will compile via FXC, it does seem like that process should fail instead of just passing through the bindings.  Of course, my assumption here is that the HLSL is in fact invalid, when it may just be invalid for FXC.  Maybe there are other targets that don't mind the overlapping registers?

**Comment by HansKristian-Work** [comment]
Either you need to remap bindings yourself to make it work, or you can use the auto binding API where register information is not emitted at all, and you would rely on reflection on the HLSL. See: https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.hpp#L185

SPIRV-Cross does not have a binding validator currently, generally it is somewhat redundant to do the exact same validation that FXC would do, just in the next step in the toolchain.
