### ISSUE TITLE
A feature for flattening inside interface blocks

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/SPIRV-Cross#1408]
Is it possible to introduce a feature for flattening all members that are of a structure type inside interface blocks. It will simplify a lot name mangling (unification) task in glsl where linking by name. Name mangling is necessary if the debug info was stripped and if you want the linker not to rely on names.
Below the example of flattening:
```
struct ExampleInnerStruct
{
	vec4 a;
};

struct ExampleStruct
{
	vec4 a;
	ExampleInnerStruct b;
};

layout(location = 0) in InputBlock
{
	ExampleStruct a;
	vec4 b;
};

layout(binding = 0) uniform UniformBlock
{
	TestStruct a;
	vec4 b;
	vec4 c;
};
```
transform to:
```
layout(location = 0) in InputBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
};

layout(binding = 0) uniform UniformBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
	vec4 c;
};
```

**Comment by HansKristian-Work** [comment]
Is it strictly necessary to flatten the members here? Wouldn't it be enough to just ensure the names match up?

**Comment by konstantinegorov** [comment]
I forgot to remove layout(location, binding) from the desired result after copy-paste.
The desired result:
```
in InputBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
};

uniform UniformBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
	vec4 c;
};
```
The fact is that structure name must also match across shaders for successfull linking.
With flattening, I don't need to worry about structure names.

**Comment by konstantinegorov** [comment]
> Is it strictly necessary to flatten the members here? Wouldn't it be enough to just ensure the names match up?

It's not necessary. For successful linking, it is enough that the names, types, decorations of the members match up. But if the member has a structure type, the structure name must also match. (I'm not sure that it's required for I/O blocks, but I came across this when declaring uniform blocks). With flattening, I don't need to worry about structure names.

> Also, I'm quite confused, since you're emitting code here with explicit location and binding. Names inside the GLSL should be irrelevant in this case.

I forgot to remove layout(location, binding) from the desired result after C&P.
The desired result:
```
in InputBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
};

uniform UniformBlock
{
	vec4 a_a;
	vec4 a_b_a;
	vec4 b;
	vec4 c;
};
```

**Comment by HansKristian-Work** [comment]
I'd rather not support flattening. It is very painful and requires a lot of special casing to support that, so I'd rather go with exhausive renaming. You should be able to use the reflection API to rename everything related here, including struct names and member names.

**Comment by konstantinegorov** [comment]
I just don't know on the base of what should I generate the structure name? I can generate name based on hash of members. But in this case structures with same definition will have the same names.

How to generate structure name without knowledge about other shader stages?

**Comment by HansKristian-Work** [comment]
Hm ye, if there are duplicate struct definitions with same types this could get unwieldy. I'll need to experiment a bit.

**Comment by HansKristian-Work** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/pull/1417 implements multi-level struct flattening for I/O blocks at least ...

**Comment by konstantinegorov** [comment]
It's good. What about uniform/storage blocks?

**Comment by HansKristian-Work** [comment]
I don't think these are feasible. A problem with this kind of flattening is that it breaks arrays of structs. If we flatten arrays of structs, we make it impossible to index the structs, which is not an acceptable restriction.

**Comment by konstantinegorov** [comment]
maybe it's possible to forbid structures with equivalent definitions?
For example:
input:
```
struct FirstStrut
{
	float a;
	float b;
};

struct SecondStruct
{
	float c;
	float d;
};

uniform UBO
{
	FirstStruct s1;
	SecondStruct s2;
};
```
output:
```
struct Struct_Float_Float
{
	float Member1;
	float Member2;
};

uniform UBO
{
	Struct_Float_Float s1;
	Struct_Float_Float s2;
};

```

**Comment by HansKristian-Work** [comment]
There is some logic in place to deal with this already, might be possible to expand the struct aliasing code, but it's rather messy.

**Comment by HansKristian-Work** [comment]
The PR in flight makes it so that structs with the same name is only emitted once, so linking by name without flattening in UBOs should work fine.

**Comment by konstantinegorov** [comment]
It does not work for me. What am I doing wrong?

input: **test.vert:**
```
#version 450

struct Struct1
{
	vec4 a;
	vec4 b;
};

struct Struct2
{
	vec4 a;
	vec4 b;
};

layout(binding = 0) uniform MyUBO1
{
	Struct1 s1;
} ubo1;

layout(binding = 1) uniform MyUBO2
{
	Struct2 s2;
	Struct1 s1;
} ubo2;

void main()
{
	gl_Position = ubo1.s1.a + ubo2.s1.b + ubo2.s2.a * ubo2.s2.b;
}
```
output: **test.vert.es_3_0:**
```
#version 300 es

struct Struct1
{
    vec4 a;
    vec4 b;
};

struct Struct2
{
    vec4 a;
    vec4 b;
};

layout(std140) uniform MyUBO1
{
    Struct1 s1;
} ubo1;

layout(std140) uniform MyUBO2
{
    Struct2 s2;
    Struct1 s1;
} ubo2;

void main()
{
    gl_Position = (ubo1.s1.a + ubo2.s1.b) + (ubo2.s2.a * ubo2.s2.b);
}

```

```
glslangValidator.exe -V -o test.vert.spv test.vert
spirv-cross test.vert.spv --es --version 300 --output test.vert.es_3_0
```

**Comment by HansKristian-Work** [comment]
You need to use the API to force the naming scheme yourself. When struct names match up, SPIRV-Cross will consider that they might be type aliases.
