### ISSUE TITLE
isfinite() not supported

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#141]
Hi,

I've got a shader which uses the isfinite() function from hlsl. This translates correctly to SPIR-V (or at least I think it does since it uses IsFinite in the SPIRV) but if I try to output glsl from it all it says is "// unimplemented op 158" and leaves my shader in an unusable state (it doesn't compile, not even incorrectly). Sample code:

```
float4 main ( float input ) 
{ 
    if(isfinite(input))
	{
		return float4(1, 0, 0, 0);
	}
	else
	{
		return float4(0, 0, 0, 0);
	}
}
```

**Comment by HansKristian-ARM** [comment]
SPIR-V has OpIsFinite, which is Kernel only according to SPIR-V specification.
SPIRV-Cross only supports the Shader model. Maybe you could use `!isinf() && !isnan()` instead?

**Comment by redorav** [comment]
Ah, I see. I can probably get away with using what you suggest, but it'd still be nice to have it translate properly. I'm guessing this is one for glslang as well?

**Comment by HansKristian-ARM** [comment]
Should be fixed in glslang, fixing it in SPIRV-Cross would be a kludgy workaround, but not hard if necessary.

**Comment by HansKristian-ARM** [comment]
While thinking about how the workaround would look like, I found an actual bug in SPIRV-Cross, so hey :p

**Comment by HansKristian-ARM** [comment]
Closing issue in wait for glslang.

**Comment by redorav** [comment]
I'm glad it was of help at least :)
