### ISSUE TITLE
DX9 compilation of DX9 features

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Cross#1414]
I want to ask about a possible inconsistency.  I'm told from a side discussion that:

https://github.com/KhronosGroup/SPIRV-Cross/blob/master/test_shaders.py#L375

(`subprocess.check_call([paths.glslang, '--amb', '--target-env', 'vulkan1.1', '-V', '-o', spirv_path, shader])`)

Is being used to compile a derivative HLSL from shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag, which looks like DX9 usage of `sampler2D`, but glslang fails because it needs the command-line option ` --hlsl-dx9-compatible` to compile DX9 correctly.

Can we know the intent of this path?  Is it trying to test DX9 HLSL shaders?  Or, should this HLSL work as a DX10 shader?

Thanks.

**Comment by HansKristian-Work** [comment]
That's somewhat curious, it has never tripped any errors when running test suite.

**Comment by dj2** [comment]
When I run the test suite built in Debug, it triggers an error message from GLSLang and the suite continues. If you build GLSLang in Debug mode the test suite aborts instead.

**Comment by dj2** [comment]
(Note, I'm attempting to role GLSLang to the latest rev, so it may need an updated GLSLang hash, haven't tried debug with old glslang to see what happens)

**Comment by HansKristian-Work** [comment]
Surprised check_call in Python doesn't catch that, any exit() code not 0 should trip the script. Perhaps it's merely logged in glslang and not a true error? The intention is definitely to use DX9 semantics for sm30 shaders at least.

**Comment by dj2** [comment]
Running:  `PATH=./external/glslang-build/output/bin:./external/spirv-tools-build/output/bin:.:$PATH ./test_shaders.py shaders-hlsl --hlsl --spirv-cross  ./spirv-cross`

ends with: 

```
Testing HLSL shader: shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag
shaders-hlsl/frag/legacy-tex-modifiers.sm30.frag
/var/folders/z8/flp9w9wx0vx01vh_m_gwgn900048mf/T/tmpsr20x4rolegacy-tex-modifiers.sm30.frag
Assertion failed: (node->getOp()), function visitAggregate, file /Users/dsinclair/Development/spirv-cross/external/glslang/SPIRV/GlslangToSpv.cpp, line 2398.
Error: Command '['glslangValidator', '--amb', '-e', 'main', '-D', '--target-env', 'vulkan1.1', '-V', '/var/folders/z8/flp9w9wx0vx01vh_m_gwgn900048mf/T/tmpsr20x4rolegacy-tex-modifiers.sm30.frag']' died with <Signals.SIGABRT: 6>.
~/Development/spirv-cross [roll-deps-29]$ echo $?
1
```

**Comment by dj2** [comment]
By your comment, does that mean that you need to add the `--hlsl-dx9-compatible` flag when passing the HLSL back to GLSLang?

**Comment by HansKristian-Work** [comment]
Ok, when I build glslang in debug mode, I do indeed trip the assertion. In release build, an error is reported for me, but it does not return 1. I'll just fix the test script ...

**Comment by HansKristian-Work** [comment]
Fixed on master.
