### ISSUE TITLE
GLSL: Opt-in to flatten I/O blocks

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/SPIRV-Cross#1427]
I think it's better to always (or by flag in options) flatten I/O blocks if they are not directly supported by specified glsl version than to rely on the GL_EXT_shader_io_blocks extension. Currently I/O blocks may not be supported on es 310 (if extension is not presented), but are supported on older versions through flattening. It's a bit strange.

**Comment by HansKristian-Work** [comment]
Would it be good enough to add a flag where I/O blocks (and structs) are always flattened similar to legacy GLSL?

**Comment by konstantinegorov** [comment]
Yes, it would be enough.
