### ISSUE TITLE
OpExtension doesn't get handled by Compiler::parse(const Instruction &instruction)

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/SPIRV-Cross#143]
The offending shader (below) compiles just fine with shaderc into a SPIRV binary, but the binary doesn't get picked up properly by SPIRV-Cross because a case for the `OpExtension` op seems to be lacking. Throwing the error "Currently no block to insert opcode".

```
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_AMD_gcn_shader : enable

void main() 
{
	uint64_t v = timeAMD();
}
```

**Comment by HansKristian-ARM** [comment]
Currently no SPIR-V extensions other than the standard GLSL external ops are supported, and I suppose that's tripping up the parser.

Is the intention here to do reflection on the SPIR-V, or decompile back to GLSL? For the first, it should be easy to ignore unsupported extensions during parse, but for compilation to GLSL, any vendor-extension must be supported explicitly.

**Comment by Jasper-Bekkers** [comment]
For my current use case it's reflection only, so having a way to tell it to skip unknown ops Should Be Fine™

**Comment by HansKristian-ARM** [comment]
Fix in flight here, parser didn't handle OpExtension: https://github.com/KhronosGroup/SPIRV-Cross/pull/144

**Comment by HansKristian-ARM** [comment]
Merged.
