### ISSUE TITLE
exception with message "cannot be expressed with either HLSL packing layout or packoffset."

### ISSUE THREAD

**Issue by stephenc87** [KhronosGroup/SPIRV-Cross#1437]
Getting unexpected results
I use glsllangvalidator to produce the spv with this code

`					#version 420
					
					layout(binding=6,std140) uniform PGlobals {
						vec4 unused_0_0[2];
						vec4 _LightColor0;
						vec4 unused_0_2;
						mat4x4 unity_WorldToLight;
						float _NormalStrength;
						vec2 _Speed_Main;
						float _Tile1;
						vec2 _Speed_Main2;
						float _DetailNormalStrength;
						vec2 _SpeedDetail;
						float _Tile2;
						vec2 _SpeedDetail2;
						float _FoamNormalStrength;
						float _FoamExponent;
						float _FoamBlendContrast;
						vec4 _WaterDeep;
						vec4 _Color0;
						vec3 _FresnelBiasScalePower;
						vec4 _WaterShallow;
						vec4 _DepthAlphaWaveRemapXMinOldYMaxOldZMinNewWMaxNew;
						vec4 _FoamColor;
						float _FoamWidth;
						float _FoamPower;
						float _Metallic;
						float _Smoothness;
						float _FoamSmoothness;
						float _Float0;
						float _Opacity;
						float _EdgeAlphaWidth;
						float _EdgeAlphaBreakup;
						float _EdgeAlphaPower;
						vec4 unused_0_31;
					};
					layout(binding=7,std140) uniform UnityPerCamera {
						vec4 _Time;
						vec4 unused_1_1[7];
					};
					layout(binding=8,std140) uniform UnityLighting {
						vec4 _WorldSpaceLightPos0;
						vec4 unused_2_1[45];
						vec4 unity_OcclusionMaskSelector;
						vec4 unused_2_3;
					};
					layout(binding=4,std140) uniform UnityStereoGlobals {
						vec4 unused_3_0[64];
						vec3 unity_StereoWorldSpaceCameraPos[2];
						vec4 unused_3_2[3];
					};
					layout(binding=5,std140) uniform UnityStereoEyeIndex {
						int unity_StereoEyeIndex;
					};
					layout(binding=9,std140) uniform UnityProbeVolume {
						vec4 unity_ProbeVolumeParams;
						mat4x4 unity_ProbeVolumeWorldToObject;
						vec3 unity_ProbeVolumeSizeInv;
						vec3 unity_ProbeVolumeMin;
					};
					layout(binding=25) uniform  sampler2D _Texture0;
					layout(binding=23) uniform  sampler2D _LightTexture0;
					layout(binding=24) uniform  sampler2D _LightTextureB0;
					layout(binding=28) uniform  sampler3D unity_ProbeVolumeSH;
					layout (location = 2) in  vec2 vs_TEXCOORD0;
					layout (location = 4) in  vec3 vs_TEXCOORD1;
					layout (location = 5) in  vec3 vs_TEXCOORD2;
					layout (location = 6) in  vec3 vs_TEXCOORD3;
					layout (location = 7) in  vec3 vs_TEXCOORD4;
					layout (location = 8) in  vec4 vs_COLOR0;
					layout(location = 0) out vec4 SV_Target0;
					vec3 u_xlat0;
					vec3 u_xlat1;
					vec3 u_xlat2;
					vec4 u_xlat3;
					vec4 u_xlat4;
					vec4 u_xlat5;
					vec4 u_xlat6;
					vec4 u_xlat10_6;
					vec4 u_xlat7;
					vec4 u_xlat10_7;
					vec3 u_xlat8;
					float u_xlat9;
					float u_xlat10;
					vec3 u_xlat11;
					vec3 u_xlat13;
					float u_xlat16;
					vec2 u_xlat19;
					float u_xlat24;
					bool u_xlatb24;
					float u_xlat25;
					int u_xlati25;
					bool u_xlatb25;
					float u_xlat26;
					bool u_xlatb26;
					float u_xlat27;
					float u_xlat28;
					float u_xlat29;
					void main()
					{
					    u_xlat0.xyz = (-vs_TEXCOORD4.xyz) + _WorldSpaceLightPos0.xyz;
					    u_xlat24 = dot(u_xlat0.xyz, u_xlat0.xyz);
					    u_xlat24 = inversesqrt(u_xlat24);
					    u_xlat1.xyz = vec3(u_xlat24) * u_xlat0.xyz;
					    u_xlati25 = unity_StereoEyeIndex;
					    u_xlat2.xyz = (-vs_TEXCOORD4.xyz) + unity_StereoWorldSpaceCameraPos[u_xlati25].xyz;
					    u_xlat25 = dot(u_xlat2.xyz, u_xlat2.xyz);
					    u_xlat25 = inversesqrt(u_xlat25);
					    u_xlat2.xyz = vec3(u_xlat25) * u_xlat2.xyz;
					    u_xlat3.xy = vs_TEXCOORD0.xy * vec2(vec2(_Tile1, _Tile1));
					    u_xlat3.xy = u_xlat3.xy * vec2(1.10000002, 1.10000002);
					    u_xlat19.xy = _Time.yy * vec2(_Speed_Main.x, _Speed_Main.y) + u_xlat3.xy;
					    u_xlat3.xy = _Time.yy * _Speed_Main2.xy + u_xlat3.xy;
					    u_xlat4 = texture(_Texture0, u_xlat19.xy);
					    u_xlat4.x = u_xlat4.w * u_xlat4.x;
					    u_xlat19.xy = u_xlat4.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
					    u_xlat4.xy = u_xlat19.xy * vec2(_NormalStrength);
					    u_xlat25 = dot(u_xlat4.xy, u_xlat4.xy);
					    u_xlat25 = min(u_xlat25, 1.0);
					    u_xlat25 = (-u_xlat25) + 1.0;
					    u_xlat25 = sqrt(u_xlat25);
					    u_xlat4 = texture(_Texture0, u_xlat3.xy);
					    u_xlat4.x = u_xlat4.w * u_xlat4.x;
					    u_xlat3.xy = u_xlat4.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
					    u_xlat3.xy = u_xlat3.xy * vec2(_NormalStrength);
					    u_xlat26 = dot(u_xlat3.xy, u_xlat3.xy);
					    u_xlat26 = min(u_xlat26, 1.0);
					    u_xlat26 = (-u_xlat26) + 1.0;
					    u_xlat26 = sqrt(u_xlat26);
					    u_xlat3.xy = u_xlat19.xy * vec2(_NormalStrength) + u_xlat3.xy;
					    u_xlat3.z = u_xlat25 * u_xlat26;
					    u_xlat25 = dot(u_xlat3.xyz, u_xlat3.xyz);
					    u_xlat25 = inversesqrt(u_xlat25);
					    u_xlat26 = u_xlat25 * u_xlat3.z;
					    u_xlat19.xy = vs_TEXCOORD0.xy * vec2(vec2(_Tile2, _Tile2));
					    u_xlat4.xy = _Time.yy * _SpeedDetail.xy + u_xlat19.xy;
					    u_xlat19.xy = _Time.yy * _SpeedDetail2.xy + u_xlat19.xy;
					    u_xlat4 = texture(_Texture0, u_xlat4.xy);
					    u_xlat4.x = u_xlat4.w * u_xlat4.x;
					    u_xlat4.xy = u_xlat4.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
					    u_xlat4.xy = u_xlat4.xy * vec2(vec2(_DetailNormalStrength, _DetailNormalStrength));
					    u_xlat28 = dot(u_xlat4.xy, u_xlat4.xy);
					    u_xlat28 = min(u_xlat28, 1.0);
					    u_xlat28 = (-u_xlat28) + 1.0;
					    u_xlat4.z = sqrt(u_xlat28);
					    u_xlat5 = texture(_Texture0, u_xlat19.xy);
					    u_xlat5.x = u_xlat5.w * u_xlat5.x;
					    u_xlat19.xy = u_xlat5.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
					    u_xlat5.xy = u_xlat19.xy * vec2(vec2(_DetailNormalStrength, _DetailNormalStrength));
					    u_xlat19.x = dot(u_xlat5.xy, u_xlat5.xy);
					    u_xlat19.x = min(u_xlat19.x, 1.0);
					    u_xlat19.x = (-u_xlat19.x) + 1.0;
					    u_xlat5.z = sqrt(u_xlat19.x);
					    u_xlat4.xyz = u_xlat4.xyz + u_xlat5.xyz;
					    u_xlat5.xy = u_xlat3.xy * vec2(u_xlat25) + u_xlat4.xy;
					    u_xlat5.z = u_xlat26 * u_xlat4.z;
					    u_xlat26 = dot(u_xlat5.xyz, u_xlat5.xyz);
					    u_xlat26 = inversesqrt(u_xlat26);
					    u_xlat11.xyz = vec3(u_xlat26) * u_xlat5.xyz;
					    u_xlat4.xy = u_xlat11.xy * vec2(vec2(_FoamNormalStrength, _FoamNormalStrength));
					    u_xlat28 = vs_COLOR0.x;
					    u_xlat28 = clamp(u_xlat28, 0.0, 1.0);
					    u_xlat29 = max(u_xlat11.y, 0.5);
					    u_xlat29 = min(u_xlat29, 1.0);
					    u_xlat29 = log2(u_xlat29);
					    u_xlat29 = u_xlat29 * _FoamExponent;
					    u_xlat29 = exp2(u_xlat29);
					    u_xlat29 = u_xlat28 * u_xlat29;
					    u_xlat29 = log2(u_xlat29);
					    u_xlat29 = u_xlat29 * _FoamBlendContrast;
					    u_xlat29 = exp2(u_xlat29);
					    u_xlat29 = min(u_xlat29, 1.0);
					    u_xlat4.z = 1.0;
					    u_xlat4.xyz = (-u_xlat5.xyz) * vec3(u_xlat26) + u_xlat4.xyz;
					    u_xlat4.xyz = vec3(u_xlat29) * u_xlat4.xyz + u_xlat11.xyz;
					    u_xlat6.x = vs_TEXCOORD1.z;
					    u_xlat6.y = vs_TEXCOORD2.z;
					    u_xlat6.z = vs_TEXCOORD3.z;
					    u_xlat19.x = dot(u_xlat6.xyz, u_xlat6.xyz);
					    u_xlat19.x = inversesqrt(u_xlat19.x);
					    u_xlat6.xyz = u_xlat19.xxx * u_xlat6.xyz;
					    u_xlat19.x = dot(u_xlat6.xyz, u_xlat2.xyz);
					    u_xlat19.x = (-u_xlat19.x) + 1.0;
					    u_xlat19.x = log2(u_xlat19.x);
					    u_xlat19.x = u_xlat19.x * _FresnelBiasScalePower.z;
					    u_xlat19.x = exp2(u_xlat19.x);
					    u_xlat19.x = _FresnelBiasScalePower.y * u_xlat19.x + _FresnelBiasScalePower.x;
					    u_xlat27 = u_xlat19.x * u_xlat19.x;
					    u_xlat19.x = u_xlat27 * u_xlat19.x;
					    u_xlat19.x = clamp(u_xlat19.x, 0.0, 1.0);
					    u_xlat19.x = (-u_xlat19.x) + 1.0;
					    u_xlat6.xyz = (-_WaterDeep.xyz) + _Color0.xyz;
					    u_xlat6.xyz = u_xlat19.xxx * u_xlat6.xyz + _WaterDeep.xyz;
					    u_xlat25 = u_xlat3.x * u_xlat25 + (-_DepthAlphaWaveRemapXMinOldYMaxOldZMinNewWMaxNew.x);
					    u_xlat3.xz = (-_DepthAlphaWaveRemapXMinOldYMaxOldZMinNewWMaxNew.zx) + _DepthAlphaWaveRemapXMinOldYMaxOldZMinNewWMaxNew.wy;
					    u_xlat25 = u_xlat25 * u_xlat3.x;
					    u_xlat25 = u_xlat25 / u_xlat3.z;
					    u_xlat25 = u_xlat25 + _DepthAlphaWaveRemapXMinOldYMaxOldZMinNewWMaxNew.z;
					    u_xlat25 = u_xlat28 * u_xlat25;
					    u_xlat25 = clamp(u_xlat25, 0.0, 1.0);
					    u_xlat3.xzw = (-u_xlat6.xyz) + _WaterShallow.xyz;
					    u_xlat3.xzw = vec3(u_xlat25) * u_xlat3.xzw + u_xlat6.xyz;
					    u_xlat28 = log2(u_xlat28);
					    u_xlat5.x = u_xlat28 * _FoamWidth;
					    u_xlat5.x = exp2(u_xlat5.x);
					    u_xlat26 = u_xlat5.y * u_xlat26 + u_xlat5.x;
					    u_xlat26 = clamp(u_xlat26, 0.0, 1.0);
					    u_xlat26 = log2(u_xlat26);
					    u_xlat26 = u_xlat26 * _FoamPower;
					    u_xlat26 = exp2(u_xlat26);
					    u_xlat26 = min(u_xlat26, 1.0);
					    u_xlat5.xyz = (-u_xlat3.xzw) + _FoamColor.xyz;
					    u_xlat3.xzw = vec3(u_xlat26) * u_xlat5.xyz + u_xlat3.xzw;
					    u_xlat5.x = (-_Smoothness) + _FoamSmoothness;
					    u_xlat5.x = u_xlat29 * u_xlat5.x + _Smoothness;
					    u_xlat28 = u_xlat28 * _EdgeAlphaWidth;
					    u_xlat28 = exp2(u_xlat28);
					    u_xlat13.x = min(u_xlat28, 1.0);
					    u_xlat11.x = u_xlat11.x * u_xlat13.x;
					    u_xlat13.x = (-u_xlat28) + _EdgeAlphaBreakup;
					    u_xlat11.x = u_xlat11.x * u_xlat13.x + u_xlat28;
					    u_xlat11.x = clamp(u_xlat11.x, 0.0, 1.0);
					    u_xlat11.x = log2(u_xlat11.x);
					    u_xlat11.x = u_xlat11.x * _EdgeAlphaPower;
					    u_xlat11.x = exp2(u_xlat11.x);
					    u_xlat11.x = min(u_xlat11.x, 1.0);
					    u_xlat25 = (-u_xlat25) + _Float0;
					    u_xlat25 = u_xlat25 + 1.0;
					    u_xlat25 = u_xlat25 * _Opacity + u_xlat26;
					    SV_Target0.w = (-u_xlat11.x) + u_xlat25;
					    SV_Target0.w = clamp(SV_Target0.w, 0.0, 1.0);
					    u_xlat6 = vs_TEXCOORD4.yyyy * unity_WorldToLight[1];
					    u_xlat6 = unity_WorldToLight[0] * vs_TEXCOORD4.xxxx + u_xlat6;
					    u_xlat6 = unity_WorldToLight[2] * vs_TEXCOORD4.zzzz + u_xlat6;
					    u_xlat6 = u_xlat6 + unity_WorldToLight[3];
					    u_xlatb25 = unity_ProbeVolumeParams.x==1.0;
					    if(u_xlatb25){
					        u_xlatb25 = unity_ProbeVolumeParams.y==1.0;
					        u_xlat13.xyz = vs_TEXCOORD4.yyy * unity_ProbeVolumeWorldToObject[1].xyz;
					        u_xlat13.xyz = unity_ProbeVolumeWorldToObject[0].xyz * vs_TEXCOORD4.xxx + u_xlat13.xyz;
					        u_xlat13.xyz = unity_ProbeVolumeWorldToObject[2].xyz * vs_TEXCOORD4.zzz + u_xlat13.xyz;
					        u_xlat13.xyz = u_xlat13.xyz + unity_ProbeVolumeWorldToObject[3].xyz;
					        u_xlat13.xyz = (bool(u_xlatb25)) ? u_xlat13.xyz : vs_TEXCOORD4.xyz;
					        u_xlat13.xyz = u_xlat13.xyz + (-unity_ProbeVolumeMin.xyz);
					        u_xlat7.yzw = u_xlat13.xyz * unity_ProbeVolumeSizeInv.xyz;
					        u_xlat25 = u_xlat7.y * 0.25 + 0.75;
					        u_xlat26 = unity_ProbeVolumeParams.z * 0.5 + 0.75;
					        u_xlat7.x = max(u_xlat25, u_xlat26);
					        u_xlat7 = texture(unity_ProbeVolumeSH, u_xlat7.xzw);
					    } else {
					        u_xlat7.x = float(1.0);
					        u_xlat7.y = float(1.0);
					        u_xlat7.z = float(1.0);
					        u_xlat7.w = float(1.0);
					    //ENDIF
					    }
					    u_xlat25 = dot(u_xlat7, unity_OcclusionMaskSelector);
					    u_xlat25 = clamp(u_xlat25, 0.0, 1.0);
					    u_xlatb26 = 0.0<u_xlat6.z;
					    u_xlat26 = u_xlatb26 ? 1.0 : float(0.0);
					    u_xlat13.xy = u_xlat6.xy / u_xlat6.ww;
					    u_xlat13.xy = u_xlat13.xy + vec2(0.5, 0.5);
					    u_xlat10_7 = texture(_LightTexture0, u_xlat13.xy);
					    u_xlat26 = u_xlat26 * u_xlat10_7.w;
					    u_xlat11.x = dot(u_xlat6.xyz, u_xlat6.xyz);
					    u_xlat10_6 = texture(_LightTextureB0, u_xlat11.xx);
					    u_xlat26 = u_xlat26 * u_xlat10_6.x;
					    u_xlat25 = u_xlat25 * u_xlat26;
					    u_xlat6.x = dot(vs_TEXCOORD1.xyz, u_xlat4.xyz);
					    u_xlat6.y = dot(vs_TEXCOORD2.xyz, u_xlat4.xyz);
					    u_xlat6.z = dot(vs_TEXCOORD3.xyz, u_xlat4.xyz);
					    u_xlat26 = dot(u_xlat6.xyz, u_xlat6.xyz);
					    u_xlat26 = inversesqrt(u_xlat26);
					    u_xlat4.xyz = vec3(u_xlat26) * u_xlat6.xyz;
					    u_xlat13.xyz = vec3(u_xlat25) * _LightColor0.xyz;
					    u_xlat6.xyz = u_xlat3.xzw + vec3(-0.220916301, -0.220916301, -0.220916301);
					    u_xlat6.xyz = vec3(vec3(_Metallic, _Metallic, _Metallic)) * u_xlat6.xyz + vec3(0.220916301, 0.220916301, 0.220916301);
					    u_xlat25 = (-_Metallic) * 0.779083729 + 0.779083729;
					    u_xlat3.xyz = vec3(u_xlat25) * u_xlat3.xzw;
					    u_xlat25 = (-u_xlat5.x) + 1.0;
					    u_xlat0.xyz = u_xlat0.xyz * vec3(u_xlat24) + u_xlat2.xyz;
					    u_xlat24 = dot(u_xlat0.xyz, u_xlat0.xyz);
					    u_xlat24 = max(u_xlat24, 0.00100000005);
					    u_xlat24 = inversesqrt(u_xlat24);
					    u_xlat0.xyz = vec3(u_xlat24) * u_xlat0.xyz;
					    u_xlat24 = dot(u_xlat4.xyz, u_xlat2.xyz);
					    u_xlat2.x = dot(u_xlat4.xyz, u_xlat1.xyz);
					    u_xlat2.x = clamp(u_xlat2.x, 0.0, 1.0);
					    u_xlat10 = dot(u_xlat4.xyz, u_xlat0.xyz);
					    u_xlat10 = clamp(u_xlat10, 0.0, 1.0);
					    u_xlat0.x = dot(u_xlat1.xyz, u_xlat0.xyz);
					    u_xlat0.x = clamp(u_xlat0.x, 0.0, 1.0);
					    u_xlat8.x = u_xlat0.x * u_xlat0.x;
					    u_xlat8.x = dot(u_xlat8.xx, vec2(u_xlat25));
					    u_xlat8.x = u_xlat8.x + -0.5;
					    u_xlat16 = (-u_xlat2.x) + 1.0;
					    u_xlat1.x = u_xlat16 * u_xlat16;
					    u_xlat1.x = u_xlat1.x * u_xlat1.x;
					    u_xlat16 = u_xlat16 * u_xlat1.x;
					    u_xlat16 = u_xlat8.x * u_xlat16 + 1.0;
					    u_xlat1.x = -abs(u_xlat24) + 1.0;
					    u_xlat9 = u_xlat1.x * u_xlat1.x;
					    u_xlat9 = u_xlat9 * u_xlat9;
					    u_xlat1.x = u_xlat1.x * u_xlat9;
					    u_xlat8.x = u_xlat8.x * u_xlat1.x + 1.0;
					    u_xlat8.x = u_xlat8.x * u_xlat16;
					    u_xlat16 = u_xlat25 * u_xlat25;
					    u_xlat16 = max(u_xlat16, 0.00200000009);
					    u_xlat1.x = (-u_xlat16) + 1.0;
					    u_xlat9 = abs(u_xlat24) * u_xlat1.x + u_xlat16;
					    u_xlat1.x = u_xlat2.x * u_xlat1.x + u_xlat16;
					    u_xlat24 = abs(u_xlat24) * u_xlat1.x;
					    u_xlat24 = u_xlat2.x * u_xlat9 + u_xlat24;
					    u_xlat24 = u_xlat24 + 9.99999975e-06;
					    u_xlat24 = 0.5 / u_xlat24;
					    u_xlat16 = u_xlat16 * u_xlat16;
					    u_xlat1.x = u_xlat10 * u_xlat16 + (-u_xlat10);
					    u_xlat1.x = u_xlat1.x * u_xlat10 + 1.0;
					    u_xlat16 = u_xlat16 * 0.318309873;
					    u_xlat1.x = u_xlat1.x * u_xlat1.x + 1.00000001e-07;
					    u_xlat16 = u_xlat16 / u_xlat1.x;
					    u_xlat16 = u_xlat16 * u_xlat24;
					    u_xlat16 = u_xlat16 * 3.14159274;
					    u_xlat16 = max(u_xlat16, 9.99999975e-05);
					    u_xlat8.y = sqrt(u_xlat16);
					    u_xlat8.xy = u_xlat2.xx * u_xlat8.xy;
					    u_xlat24 = dot(u_xlat6.xyz, u_xlat6.xyz);
					    u_xlatb24 = u_xlat24!=0.0;
					    u_xlat24 = u_xlatb24 ? 1.0 : float(0.0);
					    u_xlat16 = u_xlat24 * u_xlat8.y;
					    u_xlat1.xyz = u_xlat8.xxx * u_xlat13.xyz;
					    u_xlat8.xyz = u_xlat13.xyz * vec3(u_xlat16);
					    u_xlat0.x = (-u_xlat0.x) + 1.0;
					    u_xlat25 = u_xlat0.x * u_xlat0.x;
					    u_xlat25 = u_xlat25 * u_xlat25;
					    u_xlat0.x = u_xlat0.x * u_xlat25;
					    u_xlat2.xyz = (-u_xlat6.xyz) + vec3(1.0, 1.0, 1.0);
					    u_xlat2.xyz = u_xlat2.xyz * u_xlat0.xxx + u_xlat6.xyz;
					    u_xlat0.xyz = u_xlat8.xyz * u_xlat2.xyz;
					    SV_Target0.xyz = u_xlat3.xyz * u_xlat1.xyz + u_xlat0.xyz;
					    return;
					}`
and attempting to create an hlsl file with spriv-tools creates this message
`SPIRV-Cross threw an exception: cbuffer ID 86 (name: PGlobals), member index 9 (name: _SpeedDetail) cannot be expressed with either HLSL packing layout or packoffset.`
this is the commandline that I have used
`glslangValidator SPOT.UNITY_SINGLE_PASS_STEREO.vert  -V &&  /opt/spirv-cross/bin/spirv-cross vert.spv --hlsl --output SPOT.UNITY_SINGLE_PASS_STEREO.vert.hlsl`

It would appear to me that things are fine with the declaration but it is producing an error, changing `vec2 _SpeedDetail;` to `vec3 _SpeedDetail;` offers a bandaid for the problem

Not sure if I am doing something wrong or if this is a bug, I am just playing around with a few shaders and noticed this

**Comment by HansKristian-Work** [comment]
Very strange that this doesn't work.
