### ISSUE TITLE
MSL: Why do names starting with '_' followed by a digit e.g. "_1PixelColor" get changed to _m<num>?

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1440]
Hi,
Do you reserve names starting with '_' followed by a digit for something? from what I've seen these names are valid MSL, this is kind of a hidden gotcha, spent today debugging why our UI is misbehaving, only to find out that calling:
`spvc_compiler_get_member_name(spvCompiler, bufferResource.base_type_id, j);` on a variable named  `_1PixelClipInvView`returns an empty string. It seems that the names are changed to "_m" followed by their index int the UBO, so it looks intentional, however haven't found this documented anywhere.
The reflection result seems off to me, but I might not know the full context.
(Edit: accidentally submitted the issue a bit early so adding a repro on shader playground http://shader-playground.timjones.io/9734fd726901260175252c5c3a9bc812, can spend some time on a better reproduction shader if necessary)

**Comment by cdavis5e** [comment]
Normally when that happens, it's because the SPIR-V doesn't have an `OpName` or `OpMemberName` for the object in question, but in your example, I see that the generated SPIR-V indeed has those. I wonder why SPIRV-Cross stripped them away...

**Comment by cdavis5e** [comment]
Also, the version of SPIRV-Cross on Shader Playground is really old. Does this still happen with current SPIRV-Cross?

**Comment by HansKristian-Work** [comment]
`_$digit` is indeed reserved by the implementation, and such names will be ignored. As they are used to translate IDs which do not have a name, and need to be reserved. Members are `_m$digit`. It might be possible to be a little smarter to not block names like these since they won't conflict, but this is a rather special case ...

**Comment by HansKristian-Work** [comment]
I'm on holiday now FWIW, so PR-ing it would be a faster way to get this fixed.

**Comment by HansKristian-Work** [comment]
These names might be culled away already in parsing stage, which is not strictly necessary, albeit convenient. If you only need to know the name before compilation for reflection, it should be possible to defer the name pruning after parsing, but before compilation.

**Comment by Dredhog** [comment]
Ok, thanks for the details!
>Does this still happen with current SPIRV-Cross?

The commit I'm using is quite recent (24 days old) so most likely

>I'm on holiday now FWIW, so PR-ing it would be a faster way to get this fixed.

That's fine, we can wait for now :), this bug is not too time critical as we haven't yet shipped the code which uses SPIRV-Cross. In the meantime we can work around the issue at the source level since we only use these names in a few places, hopefully there aren't other reserved patterns...
