### ISSUE TITLE
SPIR-V with multiple decorations for same BuiltIn creates invalid MSL code

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/SPIRV-Cross#1442]
In the attached english readable spv you can see that both 'gl_InstanceID' and 'gl_InstanceIndex' are both assigned as names for 'BuiltIn InstanceIndex'.

[test.english.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5038926/test.english.txt)

This seems legal and works fine on Windows. In the MoltenVKShaderConverter however it ends up creating a duplicate declaration in the MSL shader:

`vertex main0_out main0(uint gl_InstanceIndex [[instance_id]], uint gl_InstanceIndex [[instance_id]])`

Which fails on shader compile.

Attached is the binary .spv file:

[test.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5038928/test.spv.txt)

This could also be fixed at the source that generated the troublesome SPIR-V, but since it's legal SPIR-V it would seem better if it was fixed at this stage. Thoughts?

**Comment by HansKristian-Work** [comment]
Unsure if this is actually allowed or not, need to wait for clarification. Needless to say, this is highly discouraged.

**Comment by HansKristian-Work** [comment]
From what I can tell it's not really supposed to be allowed, but it's not clear in spec. I'll treat this as WONTFIX until spec states I have to support this.

**Comment by mbechard** [comment]
Got it, thanks for confirming
