### ISSUE TITLE
Convert gl array of int[] to MSL int4[] 

### ISSUE THREAD

**Issue by tlond** [KhronosGroup/SPIRV-Cross#1447]
On current master branch 3347b1076dc98fa9f146ce57038ccbbc893c37b1
Have a simple gl shader 

#version 310 es

layout(std140) uniform UBO
{
    uniform mat4 uMVP;
    int uTypes[3];
};

layout(location = 0) in vec4 aVertex;

void main()
{
	if(uTypes[0] == 1)
	{
    	gl_Position = uMVP * aVertex;
	}
	else if(uTypes[1] == 1)
	{
		gl_Position = aVertex;
	}
	else
	{
		gl_Position = aVertex + vec4(1);
	}

}

run ./test_shaders.py shaders_test --msl --opt --spirv-cross ./spirv-cross

generate next metal shader 
======================
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct UBO
{
    float4x4 uMVP;
    int4 uTypes[3];
};

struct main0_out
{
    float4 gl_Position [[position]];
};

struct main0_in
{
    float4 aVertex [[attribute(0)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant UBO& _15 [[buffer(0)]])
{
    main0_out out = {};
    if (_15.uTypes[0].x == 1)
    {
        out.gl_Position = _15.uMVP * in.aVertex;
    }
    else
    {
        if (_15.uTypes[1].x == 1)
        {
            out.gl_Position = in.aVertex;
        }
        else
        {
            out.gl_Position = in.aVertex + float4(1.0);
        }
    }
    return out;
}

======================

Wonder why   int uTypes[3]; convert into array of four component vector  int4 uTypes[3];

**Comment by cdavis5e** [comment]
Because that uniform block has `std140` layout, where all scalars and vectors have 16-byte alignment. This ensures that the array elements are all aligned correctly.

If you use `std430` or `scalar` layout, there should be no expansion to `int4`.

**Comment by tlond** [comment]
Thanks for clarification
