### ISSUE TITLE
Textures in vertex shaders in WebGL

### ISSUE THREAD

**Issue by RobDangerous** [KhronosGroup/SPIRV-Cross#146]
Kind of a silly situation here as far as I can tell:
According to https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpImageSampleImplicitLod imlicit lods are disallowed in vertex shaders and glslang acts accordingly. On the other hand https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/ is only defined for fragment shaders and browsers seem to act accordingly (see Kode/Kha#418 - could reproduce using Chrome 57 in Windows) while supporting regular texture2D calls just fine in vertex shaders.
So I guess we should change texture2DLodEXT back to texture2D when we are in legacy es and lod is 0 (glslang sets lod to 0 when it's not explicitly defined). Changes get a bit messy so wanted to discuss it first...

**Comment by HansKristian-ARM** [comment]
Well, that's an odd ball.

The logic doesn't have to be so bad. You could check if you're emitting texture2DLodEXT and the stage is vertex, you could then check if the explicit LOD is a SPIRConstant with scalar value 0.0, if so, replace with texture2D.

**Comment by RobDangerous** [comment]
Will do a PR using that exact strategy (started with that, have to change the interface a bit to pass the lod around...).

**Comment by rdb** [comment]
The suggested fix is not right.  In fact, GLSL and ESSL have provided texture2DLod for vertex shaders from the beginning.  This is why the referenced extensions are only defined for fragment shaders—they are simply extending the functionality that was already available for vertex shaders to the fragment shader.

I have filed #1528 to address this.
