### ISSUE TITLE
[GLSL] Exception inside get_active_buffer_ranges on compute shader

### ISSUE THREAD

**Issue by hemicuda1984** [KhronosGroup/SPIRV-Cross#1462]
"Bad cast" exception is thrown inside get_active_buffer_ranges function for the following shader:
https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/glsl/computecullandlod/cull.comp
https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/glsl/computecullandlod/cull.comp.spv

The ID of the buffer provided as argument to get_active_buffer_ranges is 0x54.
resource.id = 0x54
resource.type_id = 0x53
resource.base_type_id = 0x52
resource,name = "UBOOut"

**Comment by HansKristian-Work** [comment]
This fails because it tries to look at the array size of an expression which is a spec constant operation. SPIRV-Cross currently has no evaluator of specialization constant expressions, so this fails.
