### ISSUE TITLE
MSL: Uniform binding location bug with GLSL->SPIRV->MSL

### ISSUE THREAD

**Issue by artyomd** [KhronosGroup/SPIRV-Cross#1464]
I am not sure if this is a bug or there is a flag to change the behavior. I didn't find any relevant flag for this case. Anyway here is the issue. I have the following glsl:
``` glsl
#version 450
#pragma shader_stage(fragment)
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0)out vec4 color;
layout(location = 0)in vec2 v_texCoords;
layout(binding = 1)uniform sampler2D utexture;

void main(){
    color = texture(utexture, v_texCoords);
}
```
I want to create an msl 2.1 shader from this. With the following steps:
``` sh
glslc shader.glsl -o shader.spv
spirv-cross --msl --msl-version 20100 --msl-ios shader.spv --output shader.metal
```
Here is the result
``` metal
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 color [[color(0)]];
};

struct main0_in
{
    float2 v_texCoords [[user(locn0)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> utexture [[texture(0)]], sampler utextureSmplr [[sampler(0)]])
{
    main0_out out = {};
    out.color = utexture.sample(utextureSmplr, in.v_texCoords);
    return out;
}
```
**I was expecting that utexture and utextureSmplr will be bound to index 1, not 0.** 
Here is my environment:
os: macos 10.15.6
vulkan sdk: 1.2.148.1
spirv-cross: Git commit: 0376576d Timestamp: 2020-08-11T13:43:51
glslc -v output:
shaderc v2020.2 v2020.2
spirv-tools v2020.4 v2020.4
glslang 8.13.3743-193-g3ee5f2f1

I am pretty sure that this behavior is causing spirv-cross, not the glslc because when I generate glsl 450 from the same spir-v the sampler2d is being bound to index 1.

**Comment by cdavis5e** [comment]
By default, SPIRV-Cross assigns binding numbers itself for MSL, instead of using the binding numbers from the SPIR-V. This is because buffers, textures, and samplers all have different binding spaces in Metal. If you want to use the binding numbers from the SPIR-V, you can use the `--msl-decoration-binding` option.

**Comment by artyomd** [comment]
thanks, @cdavis5e, received the desired output 🙌 thanks
