### ISSUE TITLE
Incorrect MSL generation : switch statement with return

### ISSUE THREAD

**Issue by jbright282** [KhronosGroup/SPIRV-Cross#1465]
Hello - I believe I've found  incorrect code generation for a switch statement with early returns. 

The pixel shader has a switch statement with 4 cases - each of them performs a return.  Otherwise default will break, and it will return a constant.

In the generated MSL, for each case it calculates the result, plus sets a bool = true for hitting a case - default does not.
It then falls out of the switch, but instead of picking result/default based on that bool, it always returns the default value.

I've attached files for source hlsl, disassembled SPIRV, and generated MSL. 
[textureIndex.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/5237406/textureIndex.zip)

**Comment by HansKristian-Work** [comment]
Super weird, but somehow there's a branch that's dropped, which is supposed to happen before it breaks out of the dummy do/while loop ...

**Comment by HansKristian-Work** [comment]
Nice find, very subtle bug indeed. PR in flight.

**Comment by jbright282** [comment]
Fix validated.  Thank you!
