### ISSUE TITLE
No flip_vert_y option for GLSL tessellation shaders

### ISSUE THREAD

**Issue by jhanssen** [KhronosGroup/SPIRV-Cross#1469]
I'm noticing there's a `vertex.flip_vert_y` option but no such option is available for tessellation control and evaluation shaders even though they have a `gl_Position` output. Is there a particular reason for this?

**Comment by HansKristian-Work** [comment]
Pretty sure the option works in tessellation and geometry shaders though. There should be no need for a separate option.

**Comment by jhanssen** [comment]
I might be missing something but looking at `spirv_glsl.cpp`, the code that inserts the flip statement is guarded by a `if (execution.model == ExecutionModelVertex) { .... }` block. I'm not compiling my tessellation shaders with that model. Also, the option name is `vertex.flip_vert_y` which implies that it operates on vertex shaders?

**Comment by HansKristian-Work** [comment]
Right, if it only checks for Vertex, that's not intentional. Should allow Tess/Geom as well.
