### ISSUE TITLE
Double underscore in parameter names

### ISSUE THREAD

**Issue by cpt-max** [KhronosGroup/SPIRV-Cross#1473]
Double underscores in parameter names get replaced with single underscores. This didn't happen before. The change was introduced somewhere between https://github.com/KhronosGroup/SPIRV-Cross/commit/eb0f0323d3b8b364e51071c0beafcc3d4a18c410 and https://github.com/KhronosGroup/SPIRV-Cross/commit/8891bd35120ca91c252a66ccfdc3f9a9d03c70cd. I can pinpoint the exact commit if needed.  
Is this intentional? I'm compiling SPIRV to GLSL.

**Comment by HansKristian-Work** [comment]
Double underscores are illegal in GLSL, so this is expected, and SPIRV-Cross must clean up such identifiers. There was a refactoring commit recently which would have fixed this.

**Comment by cpt-max** [comment]
Thanks for the clarification.
