### ISSUE TITLE
MSL：open argument buffer option , do not support  set buffer index offset

### ISSUE THREAD

**Issue by kingzjw** [KhronosGroup/SPIRV-Cross#1500]
we use argument buffer as vs or ps param input , is  the [[buffer]]  support has a index offset to start from , example ,use id between 16-31

**Comment by cdavis5e** [comment]
Yes, you should be able to remap argument buffers' binding indices. You can set up an `MSLResourceBinding` using the descriptor set number corresponding to the argument buffer as the `desc_set`, and the special constant `kArgumentBufferBinding` as the `binding`, and the Metal binding number you want as the `msl_buffer`.

**Comment by kingzjw** [comment]
Wonderful! thanks!
