### ISSUE TITLE
SPIRV-Cross generates duplicated code

### ISSUE THREAD

**Issue by caosdoar** [KhronosGroup/SPIRV-Cross#1511]
Hello,

I found a problem with SPIRV-Cross generating a block of code twice. A statement that was placed after a condition is written inside both the "if" and "else" blocks on the output. 

I am using CLSPV to generate SPIRV code from an OpenCL shader, so I am using OpenCL code as reference of the "input" to explain the problem. I am generating Metal shaders from the SPIRV file. The OpenCL shader for a repro-case, the SPIRV binary and dissassembly generated by CLSPV and the Metal file generated by SPIRV-Cross are here:

[spirv-cross-bug-duplication.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/5450912/spirv-cross-bug-duplication.zip)

The original code is a simple parallel reduction program to find the minimum value of a list:

```OpenCL
#define THREADS 256
#define THREADS_HALF (THREADS/2)

__kernel void main_kernel(__global float* data, __global float* output, int count)
{ 
	__local float list[THREADS];

	const int point1Index = get_global_id(1);
	const int index = get_local_id(0);

	list[index] = data[index];
	
	for (int halfSize = THREADS_HALF; halfSize > 0; halfSize >>= 1) 
	{
		if (index < halfSize)
		{
			const float value1 = list[index];
			const float value2 = list[index + halfSize];
			if (value2 < value1) list[index] = value2;
		}
		barrier(CLK_LOCAL_MEM_FENCE);
	}

	if (!index)
	{
		output[point1Index] = list[0];
	}
}
```

And this is (some parts omitted) of the Metal code generated by SPIRV-Cross:

```Metal
kernel void main_kernel(device _3& _23 [[buffer(0)]], device _3& _24 [[buffer(1)]], constant _7& _25 [[buffer(2)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup float _15[256];
    uint3 _22 = gl_WorkGroupSize;
    _15[gl_LocalInvocationID.x] = _23._m0[gl_LocalInvocationID.x];
    uint _47 = 128u;
    for (;;)
    {
        if (int(gl_LocalInvocationID.x) < int(_47))
        {
            uint _54 = _47 + gl_LocalInvocationID.x;
            if (_15[_54] < _15[gl_LocalInvocationID.x])
            {
                _15[gl_LocalInvocationID.x] = _15[_54];
            }
            threadgroup_barrier(mem_flags::mem_threadgroup); // Problem here
            uint _67 = _47 >> 1u;
            if (_67 == 0u)
            {
                break;
            }
            else
            {
                _47 = _67;
                continue;
            }
        }
        else
        {
            threadgroup_barrier(mem_flags::mem_threadgroup); // And also here
            uint _67 = _47 >> 1u;
            if (_67 == 0u)
            {
                break;
            }
            else
            {
                _47 = _67;
                continue;
            }
        }
    }
    if (gl_LocalInvocationID.x == 0u)
    {
        _24._m0[gl_GlobalInvocationID.y] = _15[0u];
    }
}
```

The memory barrier is outputted twice, as it is other code related to the for loop. This seems to crash the Metal driver when reaching the different memory barriers.

The SPIRV generated by CLSPV seems reasonable to me, and there is no duplicated operation there. I tried to debug SPIRV-Cross but I cannot point where the problem/solution is.

**Comment by HansKristian-Work** [comment]
I think this is a CLSPV bug if anything. There is no merge happening to the continue block, so I don't think you can assume that thread execution has converged. With this diff to the asm, codegen seems fine:

```
--- /tmp/orig.asm	2020-10-28 11:10:49.455557688 +0100
+++ /tmp/test.asm	2020-10-28 11:12:44.342851235 +0100
@@ -79,6 +79,9 @@
          %47 = OpPhi %uint %uint_128 %29 %67 %64
          %49 = OpSLessThan %bool %39 %47
                OpLoopMerge %70 %64 None
+			   OpBranch %tmp_header
+	   %tmp_header = OpLabel
+	           OpSelectionMerge %64 None
                OpBranchConditional %49 %52 %64
          %52 = OpLabel
          %53 = OpLoad %float %44
```

```
kernel void main_kernel(device _5& _9 [[buffer(0)]], device _5& _10 [[buffer(1)]], constant _7& _38 [[buffer(2)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup float _36[256];
    uint3 _37 = gl_WorkGroupSize;
    _36[gl_LocalInvocationID.x] = _9._m0[gl_LocalInvocationID.x];
    uint _50 = 128u;
    bool _53;
    for (;;)
    {
        _53 = int(gl_LocalInvocationID.x) < int(_50);
        if (_53)
        {
            uint _58 = _50 + gl_LocalInvocationID.x;
            if (_36[_58] < _36[gl_LocalInvocationID.x])
            {
                _36[gl_LocalInvocationID.x] = _36[_58];
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        uint _51 = _50 >> 1u;
        if (_51 == 0u)
        {
            break;
        }
        else
        {
            _50 = _51;
            continue;
        }
    }
    if (gl_LocalInvocationID.x == 0u)
    {
        _10._m0[gl_GlobalInvocationID.y] = _36[0u];
    }
}
```

**Comment by caosdoar** [comment]
Thank you Hans, I will investigate the problem on the CLSPV side.

**Comment by alan-baker** [comment]
@HansKristian-Work your diff is not valid SPIR-V. The selection cannot have a merge that is the same block as the continue target because the selection must be nested completely within the loop construct (which does not include the continue target).

**Comment by caosdoar** [comment]
Hey @alan-baker thank you for chipping in. I was about to open an issue on the clspv project, and I just saw you are a major contributor there.

It tried to figure out a little more of how clspv is generating that code. The SPIR-V generated without optimizations (-O=0) is translated to Metal correctly by SPIRV-Cross, and it has an OpSelectionMerge for that condition, but the SPIRV code is quite different anyway.

Do you reckon it is a problem on the clspv side?

**Comment by alan-baker** [comment]
LLVM ends up sinking the barrier into the loop's continue target from the selection. I know why it does this, but I agree it can be problematic. There is nothing in SPIR-V that prevents invocations from reconverging at the barrier, but also nothing currently that guarantees it will happen. The source code is unambiguous though. Unfortunately, there isn't a lot I can do about the LLVM side of things at the moment beyond not running most optimizations.

**Comment by caosdoar** [comment]
Alan, thank you very much for your insight.

Knowing that avoids me a lot of work trying to figure out what was going on.

In case anyone finds himself on the same situation: I just moved the barrier before the "if". That way I avoid the duplication of the barrier and runs just fine.

Thank you both.

**Comment by alan-baker** [comment]
I'm going to open this on clspv to track the issue.

**Comment by HansKristian-Work** [comment]
> @HansKristian-Work your diff is not valid SPIR-V. The selection cannot have a merge that is the same block as the continue target because the selection must be nested completely within the loop construct (which does not include the continue target).

Indeed, I noticed that I was getting validation errors and couldn't see right away why that was the case, the diff was mostly to demonstrate the problem.

**Comment by HansKristian-Work** [comment]
Marking this as not-a-bug on SPIRV-Cross' side.
