### ISSUE TITLE
MSL: globals dependencies are not propagated for subgroup operations

### ISSUE THREAD

**Issue by js6i** [KhronosGroup/SPIRV-Cross#1513]
Recently I started noticing shader compilation failures with errors like these:
```                                                                
program_source:302:57: error: use of undeclared identifier 'gl_SubgroupSize'
            uint _791 = spvSubgroupBallotBitCount(_790, gl_SubgroupSize);
                                                        ^                              
program_source:303:66: error: use of undeclared identifier 'gl_SubgroupInvocationID'
            uint _792 = spvSubgroupBallotExclusiveBitCount(_790, gl_SubgroupInvocationID);
```
The call site function does not receive these as parameters.

Looks like the issue is that `CompilerMSL::extract_global_variables_from_function` does not pick up dependencies introduced by these operations. Adding `OpGroup*` cases to it fixes the issue, but is it the right approach? It seems pretty error-prone. On the other hand triggering recompilation when they are emitted (if it would work, I'm not sure) sounds wasteful.

**Comment by HansKristian-Work** [comment]
Specific analysis to detect cases like this is unfortunately necessary, might just be a missed case.

**Comment by js6i** [comment]
I pushed a tentative fix to my fork.
