### ISSUE TITLE
SPIRV-Cross duplicates the continue construct, even when it has a barrier

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Cross#1515]
This is prompted by the investigation into #1511 

SPIRV-Cross will duplicate the continue construct.  But this can be invalid if the continue construct has a barrier in it.

Here's an example compute shader in GLSL.  The third clause of the for loop has a function call out to `helper`, which then has a barrier in it. (It's silly, but it's a reduced case for illustration).

```
#version 450

layout(set=0, binding=0) buffer ABuf { uint a; } A;

shared uint sa;

uint helper(uint x) {
   uint result = 99 + x;
   if (sa < 1000) {
    result = 999;
    sa = 1000;
   }
   barrier();
   return result;
}

void main() {
  uint i;
  sa = 0;
  for (i = 1 ; i < sa; i += helper(i)) {
    if ((i&1) == 1) {
      sa += 1;
      continue;
    }
    sa += 2;
  }
  A.a = sa;
}
```

When you compile this shader with Glslang, then inline the helper function, then you get this SPIR-V.  This particular example was generated with 'glslc -O' which is like gv -V, followed by spirv-opt -O (which inlines and does load/store and other scalar optimizations).

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %4 "main"
               OpExecutionMode %4 LocalSize 1 1 1
               OpMemberDecorate %_struct_56 0 Offset 0
               OpDecorate %_struct_56 BufferBlock
               OpDecorate %58 DescriptorSet 0
               OpDecorate %58 Binding 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
    %uint_99 = OpConstant %uint 99
%_ptr_Workgroup_uint = OpTypePointer Workgroup %uint
         %17 = OpVariable %_ptr_Workgroup_uint Workgroup
  %uint_1000 = OpConstant %uint 1000
       %bool = OpTypeBool
   %uint_999 = OpConstant %uint 999
     %uint_2 = OpConstant %uint 2
   %uint_264 = OpConstant %uint 264
     %uint_0 = OpConstant %uint 0
     %uint_1 = OpConstant %uint 1
 %_struct_56 = OpTypeStruct %uint
%_ptr_Uniform__struct_56 = OpTypePointer Uniform %_struct_56
         %58 = OpVariable %_ptr_Uniform__struct_56 Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_uint = OpTypePointer Uniform %uint
          %4 = OpFunction %void None %3
          %5 = OpLabel
               OpStore %17 %uint_0
               OpBranch %33
         %33 = OpLabel
         %74 = OpPhi %uint %uint_1 %5 %55 %72
         %39 = OpLoad %uint %17
         %40 = OpULessThan %bool %74 %39
               OpLoopMerge %35 %36 None
               OpBranchConditional %40 %34 %35
         %34 = OpLabel
         %42 = OpBitwiseAnd %uint %74 %uint_1
         %43 = OpIEqual %bool %42 %uint_1
               OpSelectionMerge %45 None
               OpBranchConditional %43 %44 %45
         %44 = OpLabel
         %46 = OpLoad %uint %17
         %47 = OpIAdd %uint %46 %uint_1
               OpStore %17 %47
               OpBranch %36
         %45 = OpLabel
         %49 = OpLoad %uint %17
         %50 = OpIAdd %uint %49 %uint_2
               OpStore %17 %50
               OpBranch %36
         %36 = OpLabel
         %68 = OpIAdd %uint %uint_99 %74
         %69 = OpLoad %uint %17
         %70 = OpULessThan %bool %69 %uint_1000
               OpSelectionMerge %72 None
               OpBranchConditional %70 %71 %72
         %71 = OpLabel
               OpStore %17 %uint_1000
               OpBranch %72
         %72 = OpLabel
         %80 = OpSelect %uint %70 %uint_999 %68
               OpControlBarrier %uint_2 %uint_2 %uint_264           ;; only one barrier call.
         %55 = OpIAdd %uint %74 %80
               OpBranch %33
         %35 = OpLabel
         %61 = OpLoad %uint %17
         %63 = OpAccessChain %_ptr_Uniform_uint %58 %int_0
               OpStore %63 %61
               OpReturn
               OpFunctionEnd
```

This is the output from `spirv-cross -V --es`
```
#version 450 es
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer _56_58
{
    uint _m0;
} _58;

shared uint _17;

void main()
{
    _17 = 0u;
    uint _68;
    bool _70;
    uint _74 = 1u;
    for (;;)
    {
        if (_74 < _17)
        {
            if ((_74 & 1u) == 1u)
            {
                _17++;
                _68 = 99u + _74;
                uint _69 = _17;
                _70 = _69 < 1000u;
                if (_70)
                {
                    _17 = 1000u;
                }
                barrier();
                uint _55 = _74 + (_70 ? 999u : _68);
                _74 = _55;
                continue;
            }
            _17 += 2u;
            _68 = 99u + _74;
            uint _69 = _17;
            _70 = _69 < 1000u;
            if (_70)
            {
                _17 = 1000u;
            }
            barrier();
            uint _55 = _74 + (_70 ? 999u : _68);
            _74 = _55;
            continue;
        }
        else
        {
            break;
        }
    }
    _58._m0 = _17;
}
```
This has duplicated the continue construct, including the call to the barrier. 

A valid way to translate this is to:
- generate the continue construct only once, at the top of the loop, but guarded by a 'not-first-iteration' flag.  This allows the control flow graph in the continue construct to be quite complex.
- the challenge is that sometimes an SSA value generated in the first part of the loop iteration might be used in the continue construct.  To handle this, you have to hoist the value up, perhaps outside the loop, either as a variable or via an OpPhi.

This is how Tint translates it to MSL (I faked the barrier because Tint doesn't currently support barrier.):
```
#include <metal_stdlib>

struct S {
  uint field0;
};

kernel void main_tint_0(device S& x_57 [[buffer(0)]]) {
  uint x_73_phi = 0u;
  x_17 = 0u;
  x_73_phi = 1u;
  {
    bool tint_msl_is_first_1 = true;
    uint x_54;
    const uint x_73;
    const uint x_37;
    const uint x_48;
    for(;;) {
      if (!tint_msl_is_first_1) {
        const uint x_67 = (99u + x_73);
        const uint x_68 = x_17;
        const bool x_69 = (x_68 < 1000u);
        if (x_69) {
          x_17 = 1000u;
        }
        ///// barrier goes here, if Tint supported it already.
        x_54 = (x_73 +         select(999u, x_67, x_69));
        x_73_phi = x_54;
      }
      tint_msl_is_first_1 = false;

      x_54 = 0u;
      x_73 = x_73_phi;
      x_37 = x_17;
      if ((x_73 < x_37)) {
      } else {
        break;
      }
      if (((x_73 & 1u) == 1u)) {
        const uint x_44 = x_17;
        x_17 = (x_44 + 1u);
        continue;
      }
      x_48 = x_17;
      x_17 = (x_48 + 2u);
    }
  }
  const uint x_60 = x_17;
  x_57.field0 = x_60;
  return;
}

```

**Comment by HansKristian-Work** [comment]
I believe this SPIR-V is still wrong. There is no merge when entering continue, so the implementation is free to assume that execution has not been merged. Also, moving the continue to the top is not a valid solution since we cannot store OpAccessChain to a temporary. The workaround that would work for that case would be to wrap the entire loop body in a do {} while(0) construct and then emit continue block once perhaps ...

**Comment by HansKristian-Work** [comment]
There is no OpSelectionMerge to %36 here. I see no spec wording that this means execution has become dynamically uniform again. The wording is for merge targets, but continue is not a merge target I think.

**Comment by HansKristian-Work** [comment]
> If control flow is uniform upon entry into a structured loop or selection, and all invocations leave that loop or selection via the header block’s declared **merge block**, then control flow reconverges to be uniform at that **merge block**.

**Comment by dneto0** [comment]
> I believe this SPIR-V is still wrong. There is no merge when entering continue, so the implementation is free to assume that execution has not been merged, and thus executing a barrier will be undefined unless all threads entered continue the same way.

In this code example, all choices are uniform: all the invocations in the workgroup take the same branches and compute the same values. So execution is uniform.  So I think the barrier is valid to use where it is.
(Yes, all the invocations race on updating the 'sa' variable and the output result to the storage buffer. But I didn't want to make this any more complicated.)

**Comment by dneto0** [comment]
> Also, moving the continue to the top is not a valid solution since we cannot store OpAccessChain to a temporary.

You mean in the general case, since the only access chain in the example is in the last block in the function.  Yes, you can't store a pointer or put it through a Phi.  In that case you would have to sink the phi into the continue target, but hoist its indices.  If there are chained access chains, then you have to hoist them all, until you get to a variable declaration or to a root point that is early enough to dominate the hoisted continue target.

**Comment by HansKristian-Work** [comment]
I don't see the problem if the control flow is uniform. All code paths will hit the same barrier if control flow is uniform.

**Comment by HansKristian-Work** [comment]
>  In that case you would have to sink the phi into the continue target, but hoist its indices. If there are chained access chains, then you have to hoist them all, until you get to a variable declaration or to a root point that is early enough to dominate the hoisted continue target.

The complexity to implement that would be mind-boggling and I'd rather not go there.

**Comment by dneto0** [comment]
> The workaround that would work for that case would be to wrap the entire loop body in a do {} while(0) construct, translate continue to a break and then emit continue block once perhaps

We have to do something like that in spirv-opt's merge-return pass.  It ends up chaining the state of "I've broken out".

You'd have to track if the a 'break' in the new code was really an original 'continue' or actually  a 'break' in the original.

**Comment by dneto0** [comment]
> I don't see the problem if the control flow is uniform. All code paths will hit the same barrier if control flow is uniform.

Ha. Well that might wrap it up nicely.  :-)   I'll have to think if my example was too simple.

**Comment by HansKristian-Work** [comment]
Yes, SPIRV-Cross needs to do this for switch blocks, since you can break out of a loop while inside a switch block in SPIR-V.

**Comment by HansKristian-Work** [comment]
This interacts with subgroup operations as well FWIW (which invocations are active in a continue construct coming from divergent control flow?), so adding a workaround to force convergence might very well be a bug.

**Comment by dneto0** [comment]
Yeah, if barrier is resolved in that tidy way, then I agree subgroup operations are the next thing to consider.  I haven't thought through the subgroup operation case.

The rules are less well specified with respect to what lanes are guaranteed to be active. So it's debatable one way or another whether some transformations are really wrong at all.

I don't have urgency for this issue, and like you say it's not a functionality bug for barriers at least.

**Comment by HansKristian-Work** [comment]
Either way, this needs to be clarified in the SPIR-V spec somehow I think, otherwise I will assume my interpretation is correct.

**Comment by HansKristian-Work** [comment]
Actually, if a workaround wraps the body in `do { } while(0)` then you can just continue out of that construct, no need for break shenanigans, and then emit the continue block, so a workaround won't be all that horrible, but ... ye ...
