### ISSUE TITLE
Double generation of SPIRV_Cross_workaround_load_row_major

### ISSUE THREAD

**Issue by Calestian** [KhronosGroup/SPIRV-Cross#1539]
When using spirv_cross to compile spv binary back into glsl source, it emits the function SPIRV_Cross_workaround_load_row_major if needed.
If I use spirv_cross twice(once for reflection and once for decompilation since AMD does not support spirv in OpenGL), that function gets emitted twice.
This results in a linkage error.

**Comment by HansKristian-Work** [comment]
Are you calling ::compile() multiple times on the same object? That is not supported FWIW.

**Comment by Calestian** [comment]
I'm calling compile, then using glslang with the source code provided to
generate spv. On opengl platforms I need to call a second compile on
spirvcross to get back to the source code.

**Comment by HansKristian-Work** [comment]
> I'm calling compile, then using glslang with the source code provided to generate spv

That's ... a curious use case, care to elaborate why? Ok, but I think I know why it goes wrong, since the code doesn't handle SPIRV_Cross reserved identifiers like you'd expect. Need to deal with those better ...

**Comment by Calestian** [comment]
I compile my shaders offline and I only keep binaries on the drive. So when
I'm ready to create an opengl shader I only have spirv. AMD doesn't support
spirv with opengl so I need to go back to glsl source. SpirvCross is the
only alternative I have since my original shaders are in glsl. It works
fine without issues, aside from that function
