### ISSUE TITLE
MSL codegen missing [[flat]] attribute on vertex shader

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Cross#1542]
I think the confusing Metal Shading Language (MSL) docs on this were implemented into spriv-cross.  These indicate that interpolation modifiers need to be on the "fragment input".  But the fragment input exists as the output from the vertex shader as well.  We only see an interpolation modifier output to the fragment shader.  The vertex and fragment compile independently, but then don't link.

The vertex shader and fragment shader that each define "flat in" on a variable in GLSL style.  But on the output side, we only see MSL [[flat]] in the fragment shader.  The render pipeline then can't link the vertex and fragment shader together, due to the interpolator mismatch.  Has anyone else encountered this?

vs
flat out highp vec4 v_floatFoo;  <- this is missing from output of vs
flat out highp ivec4 v_intFoo;  <- this [[flat]] is stripped, and docs state all ivec are flat interpolation

fs
flat in highp vec4 v_floatFoo;  <- this is present
flat in highp ivec4 v_intFoo;  <- also stripped due to ivec

**Comment by cdavis5e** [comment]
Works for me. I've run almost the entire Vulkan CTS against MoltenVK with this in place, with Metal's validation layers up, and I have seen no problems related to this whatsoever. Can you show me the error you are seeing?

**Comment by cdavis5e** [comment]
Also, I've run `vkd3d`'s gears demo, which I know for sure uses `flat`, and I have also seen no problems.

**Comment by alecazam** [comment]
Thanks for the info.  So  did you write source shaders in GLSL or HLSL?  Also did you gen Metal or Vulkan shaders for MoltenVK?  We haven't seen issues in Vulkan gen on Android, so this may be specific to MSL gen.  MoltenVK is likely converting your Vulkan shaders just fine. The error was on another devs machine, so

**Comment by cdavis5e** [comment]
> So did you write source shaders in GLSL or HLSL?

Both. The Vulkan CTS has its shaders in Vulkan GLSL, which it compiles at runtime to SPIR-V; while `vkd3d` (an implementation of Direct3D 12 on top of Vulkan) used HLSL, which was precompiled down to DXBC TPF, which is converted on the fly to SPIR-V.

> Also did you gen Metal or Vulkan shaders for MoltenVK?

Both passed SPIR-V to MoltenVK, which itself uses SPIRV-Cross to generate MSL.

**Comment by alecazam** [comment]
The failure case was on Xcode 11.3.1 not able to link the render pipeline.  That is only from 1/2020.  So the assumption was that flat mismatch in vs and ps was the culprit, since there was a mismatch on that element in the link.  We may just have to update that Xcode and see if that helps.

**Comment by alecazam** [comment]
I'm going to close this one for now.  We had one dev with that same 11.3.1 that had the generated shaders link (with flat only in the fragment shader), and another that didn't.  So I'm going to chalk it up to stale caches in Xcode or on device for now.  Still seems odd though, since Apple forums and samples had flat in the vertex shader, and our GLSL does too.

**Comment by alecazam** [comment]
We might be seeing a mismatch on iOS9.  I know this iOS is pretty old, but it may prefer a match of flat on the vs and ps attribute to link, and newer iOS builds can handle "flat" on the vs or fs side or both.

**Comment by fgungor** [comment]
Hi, I've run into a similar issue where SPIRV-Cross only adds [[flat]] in PS and not in the matching VS when transpiling from HLSL to MSL even though I add nointerpolation to all relevant places in both vertex and fragment shaders. I bumped into this while using shadercross with SDL3, not sure if it's relevant.
