### ISSUE TITLE
invalid MSL code generation when tessellation control output variable has initializer

### ISSUE THREAD

**Issue by comex** [KhronosGroup/SPIRV-Cross#1554]
In the following SPIR-V program, a tessellation control shader has one non-patch output array, `out_attr0`, which is initialized to a constant composite value.  (I'm not sure whether it should be legal to initialize an output array like this, but it passes `spirv-val` and is based on something Yuzu produced.)

After running it through `spirv-as` followed by `spirv-cross --msl --msl-version 20300`, the generated MSL is invalid.  It first declares the output as a pointer to a struct:
```cpp
struct main0_out
{
    uint out_attr0;
};
[..]
    device main0_out* gl_out = &spvOut[gl_PrimitiveID * 3];
```
but then attempts to initialize the data like this:
```cpp
constant spvUnsafeArray<uint, 3> _8 = spvUnsafeArray<uint, 3>({ 0u, 0u, 0u });
[..]
    out.out_attr0 = _8;
```

This is invalid because (a) it mentions `out` instead of `gl_out`, and (b) it tries to initialize with an array of `uint` even though the output data is declared as an array of `struct main0_out`, with the `uint` as a field of the struct.

I guess it should probably do something like `gl_out[gl_InvocationID] = _8[gl_InvocationID]`...

Full SPIR-V:
```
               OpCapability Shader
               OpCapability Tessellation
               OpMemoryModel Logical GLSL450
               OpEntryPoint TessellationControl %1 "main" %out_attr0
               OpExecutionMode %1 OutputVertices 3
               OpName %out_attr0 "out_attr0"
       %void = OpTypeVoid
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
     %uint_3 = OpConstant %uint 3
%_arr_uint_uint_3 = OpTypeArray %uint %uint_3
          %8 = OpConstantComposite %_arr_uint_uint_3 %uint_0 %uint_0 %uint_0
%_ptr_Output__arr_uint_uint_3 = OpTypePointer Output %_arr_uint_uint_3
  %out_attr0 = OpVariable %_ptr_Output__arr_uint_uint_3 Output %8
         %10 = OpTypeFunction %void
          %1 = OpFunction %void None %10
         %11 = OpLabel
               OpReturn
               OpFunctionEnd
```

Generated MSL:
```cpp
// omitted boilerplate at top

constant spvUnsafeArray<uint, 3> _8 = spvUnsafeArray<uint, 3>({ 0u, 0u, 0u });

struct main0_out
{
    uint out_attr0;
};

kernel void main0(uint gl_InvocationID [[thread_index_in_threadgroup]], uint gl_PrimitiveID [[threadgroup_position_in_grid]], device main0_out* spvOut [[buffer(28)]], constant uint* spvIndirectParams [[buffer(29)]], device MTLQuadTessellationFactorsHalf* spvTessLevel [[buffer(26)]])
{
    device main0_out* gl_out = &spvOut[gl_PrimitiveID * 3];
    out.out_attr0 = _8;
}
```

**Comment by HansKristian-Work** [comment]
Initializing an output variable like that is technically supported by SPIR-V, but no high-level languages support it directly, which causes some jank. There is some fixup code at the start of main() to make it work in the "normal" cases, but I wouldn't be surprised if it breaks for the weird output that tessellation emits.

As a workaround for now, I recommend not using the feature.
