### ISSUE TITLE
Distinguishing between texture and array of textures (for bindless)

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#1556]
I'm having a bit of trouble distinguishing in the reflection information between a normal texture declared as Texture2D myTex and the bindless equivalent Texture2D myArrayOfTex[42], I've been poring through get_type to see if it was any different to a normal texture but I can't really find what I need. Have you got any pointers? Thanks!

**Comment by HansKristian-Work** [comment]
You can look at `resource.type_id`. It holds the full array information.

**Comment by redorav** [comment]
Ah, I can see that there's an array member of SPIRVType called array that is a SmallVector that contains the size of the array as its first member (says there that it can be an array of arrays)

When I declare it as an unbound array, the size becomes 4. Is that correct?

**Comment by HansKristian-Work** [comment]
Doesn't seem like there's more to do in this issue, so closing.

**Comment by redorav** [comment]
Agh I apologize for not replying, but you were most helpful :) Thanks again
