### ISSUE TITLE
Generated GLSL uses pointers even though GLSL has no pointers

### ISSUE THREAD

**Issue by Boscop** [KhronosGroup/SPIRV-Cross#1559]
I'm compiling a Rust shader to SPIR-V using [`SpirvBuilder`](https://embarkstudios.github.io/rust-gpu/api/spirv_builder/struct.SpirvBuilder.html) and then compiling the SPIR-V to GLSL using [SPIRV-Cross](https://github.com/grovesNL/spirv_cross).
When the Rust code contains code like `*[&c.x, &c.y, &c.z][x]`, the resulting GLSL has this code:
```glsl
_892[0u] = &_891.x;
_892[1u] = &_891.y;
_892[2u] = &_891.z;
```
which doesn't compile.

My workaround was to change the Rust code to `[c.x, c.y, c.z][x]`, but SPIRV-Cross should either transform the pointers to code that works or it should reject the input code with an error.

**Comment by HansKristian-Work** [comment]
SPIRV-Cross does not support SPV_KHR_variable_pointers in GLSL or HLSL. You're likely making use of pointer features where you are not supposed to.

**Comment by Boscop** [comment]
@HansKristian-Work I mean, SPIR-Cross should then fail with a compilation error if the input code uses pointers.
So that such errors can be caught as early in the pipeline as possible.
