### ISSUE TITLE
Resulting MSL Code from SPIR-V Code Does Not Compile

### ISSUE THREAD

**Issue by jakejaylee123** [KhronosGroup/SPIRV-Cross#1561]
Hello!

Hopefully I will be able to explain this well; I am new to shader languages and what-not. Please do let me know if more information is needed.

I have a SPIR-V file ([shader_data_2.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/5649839/shader_data_2.spv.zip)) that I converted to Metal using the following command:
```
spirv-cross --msl shader_data_2.spv
```
This is the resulting file: [shader_data_2.metal.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/5649854/shader_data_2.metal.zip)

Then I tried to compile the resulting Metal file  above with the following command:
```
xcrun -sdk macosx metal -c shader_data_2.metal -o shader_data_2.air
```
The compilation failed with quite a few errors ([compiler_errors.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5649862/compiler_errors.txt)). Based on the SPIR-V and Metal files, any ideas what the problem could be? I ask because it may be possible that this is because of a bug in SPIRV-Cross. Something tells me it has to do with the numerous **bool**'s declared in the main function of the Metal file (perhaps they should be of a different type?). All of the above operations were performed on a 16" MacBook Pro running macOS Big Sur.

Thanks in advanced for any assistance!

**Comment by cdavis5e** [comment]
This module doesn't even validate:
```shell
$ spirv-val shader_data_2.spv
error: line 752: OpStore Pointer <id> '59[%gpr_0]'s type does not match Object <id> '146[%146]'s type.
  OpStore %gpr_0 %146
```
`%146` is of type `%float`. Where did you get this SPIR-V from?

In general, you shouldn't expect invalid SPIR-V to do anything. Anything up to and including the appearance of nasal demons is possible.

**Comment by jakejaylee123** [comment]
Oh, that makes sense! Garbage SPIR-V in, garbage MSL out I suppose. The SPIR-V validator looks handy, will definitely use that from now on. Thanks @cdavis5e!
