### ISSUE TITLE
error: 'to_string' is not a member of 'std'

### ISSUE THREAD

**Issue by lance-loong** [KhronosGroup/SPIRV-Cross#1562]
### question:

I use NDK compile for my android project.But there was a mistake.“error: 'to_string' is not a member of 'std'”.this error is Repaired in glslang.

### environment:

NDK r16b gcc 4.9.0 gunstl

### Solution:

in glslang have code:

```
#if defined(__ANDROID__) || (defined(_MSC_VER) && _MSC_VER < 1700)
#include <sstream>
namespace std {
template<typename T>
std::string to_string(const T& val) {
  std::ostringstream os;
  os << val;
  return os.str();
}
}
#endif
```

**Comment by HansKristian-Work** [comment]
gnustl is ancient and has been deprecated for ages. Use libc++ STL.

**Comment by lance-loong** [comment]
OK,thank you.
