### ISSUE TITLE
OpIgnoreIntersectionKHR is not supported

### ISSUE THREAD

**Issue by GritWorldNV** [KhronosGroup/SPIRV-Cross#1569]
Hi,

The value of OpIgnoreIntersectionKHR changed from 5335 to 4448 (https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing.asciidoc) and SPIRV-Cross didn't reflect this change.
It's currently crashing when such an opcode is present.

Best regards,
Pascal

**Comment by HansKristian-Work** [comment]
SPIRV-Cross hasn't been updated to support KHR ray-tracing. It's on my TODO to eventually replace NV with KHR and then finally support RT for HLSL as well.

**Comment by TheMostDiligent** [comment]
We are hitting the same issue
