### ISSUE TITLE
Get boolean type back when parsing glsl bool

### ISSUE THREAD

**Issue by eugchriss** [KhronosGroup/SPIRV-Cross#1579]
Since booleans uniforms are implicitly converted to uint, is there a way to get the original bool type? I mean from a spirv_cross user point of view, how can I know if the resource's type is uint because it is actually a uint in the shader or because it's a converted bool?

**Comment by HansKristian-Work** [comment]
You cannot, because bool is not a physical type. There isn't anything SPIRV-Cross can do here since the SPIR-V is uint always.
