### ISSUE TITLE
MSL: Mismatching vertex shader out.

### ISSUE THREAD

**Issue by VZout** [KhronosGroup/SPIRV-Cross#1592]
Thanks for fixing the other issues I opened! I'm now running into another problem however.
Compiling a pipeline gives me the following error: `mismatching vertex shader output type or not written by vertex shader`.
However as far as I can tell the vertex out is written and match.

generated metal vertex out:
```metal
struct fullscreen_triangle_out
{
    float3 out_uv [[user(locn0)]];
    float4 gl_Position [[position]];
    uint gl_Layer [[render_target_array_index]];
};
```
generated metal fragment in:
```metal
struct spectate_main_fs_in
{
    float3 uv [[user(locn0)]];
};
```

Using a float4 works but float3 or 3 floats don't. 
I don't think this is a SPRIV-Cross issue. But I think you might have a clue of what's going on here. Is there a requirement I am missing or is this possibly a issue with MoltenVK / Drivers? I've attached both complete shaders to this issue.

Feel free to close if you think this is to off-topic.

[metal_shaders.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/5808774/metal_shaders.zip)

**Comment by HansKristian-Work** [comment]
This doesn't make any sense. The types are literally matching here. Only quirk I can see is that gl_Layer is not written, but just initialized to 0, but I claim this output is not a bug unless proven otherwise. Please reopen if there is a good reason this is a SPIRV-Cross bug.
