### ISSUE TITLE
Distinguishing a RW buffer from a RO buffer in hlsl

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#1605]
I compile a shader that uses both a RW buffer and a RO (read-only) buffer. In the reflection information I was hoping to get a simple way to distinguish between the UAV and SRV versions of these using DecorationNonWritable. However this decoration doesn't convey that information as far as I can tell and I'm struggling to find other mechanism to query this. What am I missing?

**Comment by HansKristian-Work** [comment]
DecorationNonWritable is the only way to detect SRV vs UAV raw buffers since they both map to SSBOs in Vulkan. For typed buffers, you have storage_image vs sampled_image (typed buffers are image types in Vulkan).

**Comment by redorav** [comment]
My code at the moment looks like this:

```cpp
for (const spirv_cross::Resource& r : resources.storage_buffers)
{
    uint32_t isReadOnly = reflection.get_decoration(r.id, spv::DecorationNonWritable);
```

But no matter what resource comes through, the decoration is always 0

**Comment by HansKristian-Work** [comment]
Do you have the SPIR-V? It might be a case where the struct block members all have NonWritable.

**Comment by redorav** [comment]
Here's the spir-v file. It might look a little weird (there's only resources, no usage) because I'm trying to use this for metadata only.

[buffers.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5882039/buffers.txt)

**Comment by HansKristian-Work** [comment]
Ok, the way to get this information is:

https://github.com/KhronosGroup/SPIRV-Cross/blob/master/main.cpp#L323

The NonWritable decorations only live in the members here, so we need the special "get_buffer_block_flags" which looks at both the variable and the member decorations to deduce the correct decoration.

**Comment by HansKristian-Work** [comment]
--dump-resources gives:
```
ssbos
=============

 ID 024 : ExampleStructuredBufferFloat (Set : 0) (Binding : 0) readonly (BlockSize : 0 bytes) (Unsized array stride: 16 bytes)
 ID 028 : ExampleAppendBufferFloat (Set : 0) (Binding : 0) (BlockSize : 0 bytes) (Unsized array stride: 16 bytes)
 ID 076 : ExampleStructuredBuffer (Set : 0) (Binding : 0) readonly (BlockSize : 0 bytes) (Unsized array stride: 8 bytes)
 ID 080 : ExampleRWStructuredBuffer (Set : 0) (Binding : 0) (BlockSize : 0 bytes) (Unsized array stride: 8 bytes)
 ID 081 : ExampleAppendBuffer (Set : 0) (Binding : 0) (BlockSize : 0 bytes) (Unsized array stride: 8 bytes)
 ID 082 : ExampleConsumeBuffer (Set : 0) (Binding : 0) (BlockSize : 0 bytes) (Unsized array stride: 8 bytes)
 ID 092 : ExampleByteBuffer (Set : 0) (Binding : 0) readonly (BlockSize : 0 bytes) (Unsized array stride: 4 bytes)
 ID 096 : ExampleRWByteBuffer (Set : 0) (Binding : 0) (BlockSize : 0 bytes) (Unsized array stride: 4 bytes)
=============
```

**Comment by HansKristian-Work** [comment]
Closing as I don't think there is more to do here.

**Comment by redorav** [comment]
I'm sorry for not replying earlier, I thought when you said 

> we need the special get_buffer_block_flags

you meant that it needed implementing! But I can see what you mean now, thanks for looking into it and your help.
