### ISSUE TITLE
Builtin position is not handled correctly with shaders generated by DXVK

### ISSUE THREAD

**Issue by K0bin** [KhronosGroup/SPIRV-Cross#1609]
When compiling shaders generated by DXVK, it seems like SPIR-V does not handle Builtin Position correctly.

It can be reproduced with the simple D3D11-triangle test shader found here:
https://github.com/doitsujin/dxvk/blob/master/tests/d3d11/test_d3d11_triangle.cpp#L28
I dumped the SPIR-V of that and it passes SPIRV-val;
[VS_d5e45125669b644f0270190e8c241decb99c760d.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5925719/VS_d5e45125669b644f0270190e8c241decb99c760d.spv.txt) (had to change the file extension because GitHub doesn't like uploading .spv files)

All of the backends I tested had that issue in one way or another.

Metal: 
```
struct main0_out
{
    float4 o0 [[user(locn0)]];
    float4 o1 [[user(locn1)]];
};
```

HLSL:
```
struct SPIRV_Cross_Output
{
    float4 o0 : TEXCOORD0;
    float2 o1 : TEXCOORD1;
};
```

GLSL just never assigns gl_Position.

Here's (what I assume are) the relevant SPIRV bits:
```
OpEntryPoint Vertex %main "main" %vs_vertex_out %v0 %o0 %o1 %vs_vertex_index %vs_base_vertex %vs_instance_index %vs_base_instance
[...]
OpName %s_per_vertex "s_per_vertex"
OpMemberName %s_per_vertex 0 "position"
[...]
OpMemberDecorate %s_per_vertex 0 BuiltIn Position
OpDecorate %s_per_vertex Block
[...]
%s_per_vertex = OpTypeStruct %v4float
%_ptr_Output_s_per_vertex = OpTypePointer Output %s_per_vertex
[...]
%vs_vertex_out = OpVariable %_ptr_Output_s_per_vertex Output
```

**Comment by HansKristian-Work** [comment]
Are you sure about this? The test seems to be part of a tessellation pipeline, so it makes sense for vertex shader to not write Position builtin at all.

**Comment by HansKristian-Work** [comment]
HLSL does not throw error if you don't return SV_Position from vertex shader.
MSL potentially has this problem only for vertex shaders which are not part of transform feedback or tessellation and position is not used.
