### ISSUE TITLE
MSL : atomic aliases

### ISSUE THREAD

**Issue by jbright282** [KhronosGroup/SPIRV-Cross#1613]
With the workaround for providing atomic access to textures - e.g.

struct spvDescriptorSetBuffer0
{
    texture3d<int> g_myTexture [[id(0)]];
    device atomic_uint* g_myTexture_atomic [[id(1)]];
};

is there any way/reflection info to determine these assignments post compile? I could not find any --- currently doing it all via text regex.

**Comment by HansKristian-Work** [comment]
You should be able to use `CompilerMSL::get_automatic_msl_resource_binding_secondary()` after compiling to MSL.

**Comment by HansKristian-Work** [comment]
Tested it to make sure, and it works. Added a comment about this in latest master.
