### ISSUE TITLE
 'attribute' index '0' is used more than once

### ISSUE THREAD

**Issue by nedres** [KhronosGroup/SPIRV-Cross#1618]
I'm seeing the error ` 'attribute' index '0' is used more than once` translating hlsl->spirv->msl.

Sample hlsl:
[A.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5984524/A.hlsl.txt)

dxc produces this spirv code:
[A.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5984526/A.spv.txt)

spirv-cross produces this msl:
[A.metal.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5984529/A.metal.txt)

**Comment by cdavis5e** [comment]
That SPIR-V assigns the same location to two different variables. Also, why is DXC putting the `TESS_FACTOR` input in the `Output` storage class? In domain (tessellation evaluation) shaders, the tessellation factors (levels) are inputs. This seems like a bug in DXC.

**Comment by nedres** [comment]
Thanks for looking at this. I should have included more information.

The full error message:
```
error: 'attribute' index '0' is used more than once
    float4 in_var_DOMAIN_B [[attribute(0)]];
                             ^
note: prior use here
    float4 gl_TessLevel [[attribute(0)]];
           ^
1 error generated.
```

The commmand line:
`spirv-cross.exe A.spv --output A.metal --msl --msl-ios --msl-version 20300 --msl-texture-buffer-native`


Stepping through, I see `get_ordered_member_location()` return `0` for gl_TessLevel based on index, as no location was explicitly set.

glTessLevel is in struct `ds_main_patchIn`, and I wondered if the index was reset to zero without checking if that location was already used in `ds_main_in`.


As far as the TESS_FACTOR as output instead of input, that is a good question, I need to look into that.

**Comment by cdavis5e** [comment]
OK, you were right, I was wrong. I've figured out why `TESS_FACTOR` is in the `Output` class--because it *is* an output. It is distinct from the `TessLevel` input which is the problem. So this is a bug in SPIRV-Cross after all, not in DXC. Sorry about that.

**Comment by HansKristian-Work** [comment]
Right, it seems like automatic attribute assignment for builtins doesn't take user attributes into account and they end up overlapping.
