### ISSUE TITLE
metal errors with `edgeTessellationFactor` and `insideTessellationFactor`

### ISSUE THREAD

**Issue by nedres** [KhronosGroup/SPIRV-Cross#1619]
I'm seeing spirv-cross produce this metal code:
```
spvTessLevel[gl_PrimitiveID].edgeTessellationFactor = _36;
spvTessLevel[gl_PrimitiveID].insideTessellationFactor = _35;
```

This causes metal compiler errors:
```
error: array type 'half device[4]' is not assignable
        spvTessLevel[gl_PrimitiveID].edgeTessellationFactor = _36;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
error: array type 'half device[2]' is not assignable
        spvTessLevel[gl_PrimitiveID].insideTessellationFactor = _35;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

Changing to this code fixes it:
```
spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[0] = _36[0];
spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[1] = _36[1];
spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[2] = _36[2];
spvTessLevel[gl_PrimitiveID].edgeTessellationFactor[3] = _36[3];
spvTessLevel[gl_PrimitiveID].insideTessellationFactor[0] = _35[0];
spvTessLevel[gl_PrimitiveID].insideTessellationFactor[1] = _35[1];
```

I can supply a repro if that's helpful.

**Comment by HansKristian-Work** [comment]
I need a repro SPIR-V.

**Comment by nedres** [comment]
Sample hlsl:
[B.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5990387/B.hlsl.txt)

`dxc.exe -spirv -Zpc -fvk-use-dx-layout -fvk-use-dx-position-w -T hs_6_0 -E hs_main B.hlsl > B.spv.txt`
produces this spirv:
[B.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5990394/B.spv.txt)

`spirv-cross.exe  B.spv --output B.metal --msl --msl-ios --msl-version 20300 --msl-texture-buffer-native`
produces this msl:
[B.metal.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/5990396/B.metal.txt)


I notice `edgeTessellationFactor` and `insideTessellationFactor` are msl symbols:
https://developer.apple.com/documentation/metal/mtlquadtessellationfactorshalf/1639974-edgetessellationfactor
https://developer.apple.com/documentation/metal/mtltriangletessellationfactorshalf/1639953-insidetessellationfactor

Was wondering if it was a simple matter of writing out the assignments.
