### ISSUE TITLE
[MSL] C pointer type syntax is not (trivially) concatenable, like SPIRV-Cross assumes.

### ISSUE THREAD

**Issue by eddyb** [KhronosGroup/SPIRV-Cross#1628]
There are a bunch of places in `spirv_msl.cpp` in which types/declarations are built up by concatenation:
<details>
<summary>(click to expand a **non-exhaustive** series of examples - there's more I've skipped)</summary>

https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L6111
https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L6139
https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L10986
https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L10986
https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L11207-L11208
https://github.com/KhronosGroup/SPIRV-Cross/blob/621884d70917038caf7509f7b1b3c143807ff43f/spirv_msl.cpp#L12552
</details>

These all assume that you can substitute `T` in `some_addrspace T*` (or `some_addrspace T global;`) with any type and have the result mean "a pointer/global in `some_addrspace` pointing to `T`", but that only works in limited circumstances.

One of the simpler examples from what we've seen is (easiest way to get these is `OpUndef`s, FWIW) this type:
```
thread thread float2**
```

If C type syntax allowed for parenthesis, it'd be easy to see how we got there (and avoid the problem in the first place):
```
thread (thread float2*)*
```

But because the pointer syntax steals all of the relevant qualifiers before the `*`, what happens is:
* the first `*` takes *both* `thread`s
* the second `*` ends up with none

The simplest solution (for this example) is to *never* try and add anything *to the left* of a type, but instead *only add to the right* - that is, `T some_addrspace*` (or `T some_addrspace global;`), e.g.:
```
float2 thread* thread*
```

The order is irrelevant (as long as you don't move anything before/after an `*`) so this means the same as if you tried to go for preserving `thread float2*` in the "simple" case, but is easier to do than trying to account for everything that could be found in the nested type you're adding to.

It also has the nice property of making `some_addrspace*` look like a special form of `*`, but that's subjective.

<hr/>

We've also seen `constant texture2d<float>` show up as a type, how does that work? If the address space does indeed apply to `texture2d<...>` successfully, it probably has to be kept *before* `texture2d<...>`?

**Comment by eddyb** [comment]
The other option, of course, is to rely solely on `template<...> using` aliases to create all structural types.

**Comment by eddyb** [comment]
Quick example, that shows both pointer type syntax and declaration syntax failures:
(you may also note that `%uPPF` is unused - that's a separate issue of unreachable `OpUndef`s being emitted)
```llvm
OpCapability Shader
OpCapability VulkanMemoryModel
OpMemoryModel Logical Vulkan

; == Entry-points ==
OpEntryPoint Vertex %fn_vert "vert"

; == Types ==
%F = OpTypeFloat 32
%PF = OpTypePointer Private %F
%PPF = OpTypePointer Private %PF

%V = OpTypeVoid
%Fn0V = OpTypeFunction %V

; == Constants ==
%uPPF = OpUndef %PPF

; == Functions ==
%fn_vert = OpFunction %V None %Fn0V
  %fn_vert_bb0 = OpLabel
    OpReturn
OpFunctionEnd
```
```c++
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

constant thread thread float** _7 = {};

vertex void vert()
{
}
```

With my suggestion, the invalid line could be generated as this instead:
```c++
float thread* thread* constant _7 = {};
```

**Comment by HansKristian-Work** [comment]
The storage class pointer stuff is a hot mess, and I wouldn't be surprised if it's broken for nested pointer types.

**Comment by eddyb** [comment]
> The storage class pointer stuff is a hot mess, and I wouldn't be surprised if it's broken for nested pointer types.

it doesn't look *too* bad to fix, the hard thing would be generating *nice-looking* code. Correct code should be easy with my trick.
