### ISSUE TITLE
[Discussion] HLSL vertex shader input semantics from attribute names

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#163]
@RobDangerous suggested I open an issue for this to have a small discussion what a good solution would be :)

Currently the HLSL backend assigns TEXCOORDn semantics to vertex shader input attributes (https://github.com/KhronosGroup/SPIRV-Cross/blob/3804292c43c4a6ea0d90acd067ccf626e0853646/spirv_hlsl.cpp#L320), regardless of the vertex attribute's name.

When creating a D3D11 input layout, only the semantic can be used, not the vertex attribute name (https://msdn.microsoft.com/en-us/library/windows/desktop/ff476180(v=vs.85).aspx), and core-D3D11 doesn't have the necessary reflection API get the original name of the vertex attribute (this only exists with D3DReflect, which is part of the d3dcompiler_xx.dll.

My suggestion is to copy the vertex attribute name into the semantic (only for the vertex shader input attributes, not the varyings between vertex shader and pixel shader, those should keep the TEXCOORDn semantics), so that this name information isn't lost from the original GLSL source code, and allows D3D11 code to create an input layout with the semantic names without a separate reflection step. This new behaviour could be behind a flag/option.

I used this solution in my previous python-based shader code generator, and it worked well (or at least I'm not aware of any disadvantages compared to the current solution).

For instance a simple GLSL v100 shader like this:
```glsl
attribute vec4 position;
attribute vec4 color0;
varying vec4 color;
void main() 
{
   gl_Position = position;
   color = color0;
}
```
Could look like this in HLSL (this is copy-pasted from my old code-generator, spirv-cross looks quite a bit different):

```hlsl
void main(
  in vec4 position : position,
  in vec4 color0 : color0,
  out vec4 color : color,
  out vec4 _oPosition : SV_Position) 
{
  _oPosition = position;
  color = color0;
}
```

Another possible solution I was pondering was to generate a reflection-info file (maybe JSON) along with the generated source code, which could contain all the necessary binding information for the shader (uniform blocks, and their members with name and type, shader input and outputs etc...), this would also solve the problem in a more comprehensive way, but would be a lot more work.

So... any suggestions? :) I'm currently working on converting my own cross-platform-engine's shader code generator over to glslangValidator + spirv-cross (here: https://github.com/floooh/oryol, the work is happening in the spirv-tooling branch), and I'm happy to provide pull requests and test cases.

Cheers!

**Comment by HansKristian-ARM** [comment]
Hm, the intention here is that the semantic name matches the location decoration used by the shader. For example:

```
layout(location = 3) in vec3 AttrNameWeDontCareAbout;
```
This is translated to `TEXCOORD3` (maybe ATTR#n makes more sense?) when emitting HLSL. The intention is that you link the attribute name to DecorationLocation which you can query from the reflection API and use that when setting up your input layouts. You can also modify the location used by the shader before compiling to HLSL, so I think this should be flexible enough. In SPIR-V, the explicit decorations in layout() are significant, not the names of the variables.

Is there a need to emit custom named semantics? I can see the problem if the D3D implementation must use pre-baked semantic names (like POSITION, NORMAL) and so on.

I don't see a significant problem in having an option to emit the variable names as semantic, but it cannot be the default behavior (stripped SPIR-V files for example), but I'd only add it if there is a real need for it.

**Comment by floooh** [comment]
Ok, the intended behaviour should work for me if I move away from the standalone executable and use it as a link library, because then I can extract the required reflection info right from spirv-cross.

I think I need to take this step anyway if I want to get away from my own pre-parsing of the initial shader source. I currently have preprocessor-like tags to define uniform buffers and entry-function in/out params, which I'm currently using to build my own "poor-man's reflection info" before I'm handing the raw shader source over to glsangValidator and spirv-cross.

I'll try that out, thanks for the reply :)

**Comment by HansKristian-ARM** [comment]
I assume this is resolved now, so closing.
