### ISSUE TITLE
Functions like image_format_to_components() are useful outside of hlsl

### ISSUE THREAD

**Issue by wrosecrans** [KhronosGroup/SPIRV-Cross#1637]
There are some functions in spirv_hlsl.cpp that probably make sense as public API's and aren't specific to hlsl like image_format_to_components() : https://github.com/KhronosGroup/SPIRV-Cross/blob/fb1f295aaf4044b6ada277ff82cce502d5962213/spirv_hlsl.cpp#L69

It takes an ImageFormat enum from spirv.hpp, and returns that for example ImageFormatRg32f has two channels and ImageFormatRgba8Snorm has four, which is true regardless of what language you are dealing with.  Likewise, image_format_to_normalized_state() 

Since these functions seem to be private to the hlsl generator, is there a supported way to get details of image formats expected by a shader parsed from SPIR-V?  If not, would it make sense to migrate some of these functions for getting the specifics of an ImageFormat into a different header so they are available for wider consumption?  I only found them in the hlsl header by searching the code for any reference to ImageFormat.  The "Reflection-API-user-guide" wiki page is a little vague on how exactly you are supposed to be doing this.

**Comment by HansKristian-Work** [comment]
This is a very random function to expose. I'm not sure if it makes sense to expose various random helper functions which are completely independent of any SPIR-V.

**Comment by wrosecrans** [comment]
Fair enough.  There may be some more obvious ways to do what I want that I just haven't noticed.

But within the SPIR-V shader, if it takes an image as input, it needs to be in the right format.  Aside from the ImageFormat enum, how is an application developer expected to validate that an image is in the right format for a shader, and has the right number of components, etc?

**Comment by HansKristian-Work** [comment]
That's the task of validation layers and friends, not SPIRV-Cross.
