### ISSUE TITLE
C: Missing active builtins query API

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1649]
The C API is lacking access to `Compiler::has_active_builtin` and `Compiler::update_active_builtins`.

I could make a PR but am unable to push a branch to this repo. Do I necessarily have to fork the repo to make a PR?

If you prefer, you can `git apply add_c_api.diff.txt` youself.
[add_c_api.diff.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/6310780/add_c_api.diff.txt)

**Comment by HansKristian-Work** [comment]
You're supposed to fork, submit a PR and then sign the Khronos CLA.
