### ISSUE TITLE
SPIRV-Cross can't resolve some std430/scalar layouts

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/SPIRV-Cross#1656]
Take this shader for example:

https://github.com/Plagman/gamescope/blob/9a9953192e2479a7185187208cfa2eb7da02461b/src/composite.comp

It has:
```glsl
layout(std430, binding = 1)
uniform layers_t {
    vec2 u_scale[MaxLayers];
    vec2 u_offset[MaxLayers];
    float u_opacity[MaxLayers];
};
```

Compiling this shader with glslang and attempting to translate it back results in:
`SPIRV-Cross threw an exception: Buffer block cannot be expressed as any of std430, std140, scalar, even with enhanced layouts. You can try flattening this block to support a more flexible layout`

**Comment by HansKristian-Work** [comment]
Needs --vulkan-semantics since this is using GL_EXT_scalar_block_layout.
