### ISSUE TITLE
MSL: Reading tessellation factors in quad patch domain shader generates invalid MSL

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1658]
Hi, I noticed that reading `SV_TessFactor` or `SV_InsideTessFactor` from the domain shader patch input results in invalid MSL.

Here's the source HLSL:
```
struct ControlPoint {
    float4 customValue : CUSTOM_VALUE;
};

struct PatchData {
    float edge [4] : SV_TessFactor;
    float inside[2] : SV_InsideTessFactor;
};

[domain("quad")]
ControlPoint Domain (PatchData patchData, const OutputPatch<ControlPoint,4> vi, float2 uv : SV_DomainLocation)
{
    ControlPoint o;
    o.customValue = float4(patchData.edge[0] + patchData.inside[0],
                           patchData.edge[1] + patchData.inside[1],
                           patchData.edge[2],
                           patchData.edge[3]);
    return o;
}
```
DXC generates the following SPIR-V (downloaded from [shader playground](http://shader-playground.timjones.io/fb6e7856a1fbc71a18d124132b11dd30)):
[quad_tess_factor_read.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/6359726/quad_tess_factor_read.spv.txt)

With `./spirv-cross --msl --msl-multi-patch-workgroup quad_tess_factor_read.spv.txt` SPIRV-Cross generates this MSL:

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Domain_out
{
    float4 out_var_CUSTOM_VALUE [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct Domain_patchIn
{
    float4 gl_TessLevelOuter [[attribute(0)]];
    float2 gl_TessLevelInner [[attribute(1)]];
};

[[ patch(quad, 0) ]] vertex Domain_out Domain(Domain_patchIn patchIn [[stage_in]])
{
    Domain_out out = {};
    out.out_var_CUSTOM_VALUE = float4(patchIn.gl_TessLevelOuter.x[0] + patchIn.gl_TessLevelInner.x[0], patchIn.gl_TessLevelOuter.x[1] + patchIn.gl_TessLevelInner.x[1], patchIn.gl_TessLevelOuter.x[2], patchIn.gl_TessLevelOuter.x[3]);
    return out;
}
```

The `patchIn.gl_TessLevelOuter.x[3]` and similar array style reads are invalid MSL as `patchIn.gl_TessLevelOuter.x` is a float. The output for triangle patch domain is correct though

**Comment by HansKristian-Work** [comment]
Ok, the weird part here is at TessLevels array is loaded as an array, and then it's composite extracted from. Normal access chains and loads work fine.

**Comment by HansKristian-Work** [comment]
Should be fixed in PR.

**Comment by Dredhog** [comment]
Tried it, seems fixed indeed!
