### ISSUE TITLE
SPIRV OpGroupNonUniformShuffle to HLSL WaveReadLaneAt

### ISSUE THREAD

**Issue by xhcao** [KhronosGroup/SPIRV-Cross#1659]
My GLSL shader uses `T subgroupShuffle(T value, uint index)`, the `index` parameter value is specified dynamically, and this shader will be compiled to SPIRV by glslang, then the SPIRV will be translated into HLSL by SPIRV-CROSS on windows. 
The compiling error happens in https://github.com/KhronosGroup/SPIRV-Cross/blob/bbcef69a455fbf3e0deddf4e2eca47e57bf296e3/spirv_hlsl.cpp#L4615, throws "Cannot trivially implement Shuffle in HLSL" message.
My question is why spirv-cross cannot translate SPIRV OpGroupNonUniformShuffle to HLSL WaveReadLaneAt function, https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/wavereadlaneat, HLSL had removed uniform lane index requirement for Wave in https://github.com/MicrosoftDocs/win32/commit/803a98ea702c4fcf8ba2b80e5ab1bca54ebfa05a. Are there other reasons?

**Comment by HansKristian-Work** [comment]
Now that the HLSL spec changed, sure, we can implement this.
