### ISSUE TITLE
❓ Spirv cross - offset generation push constants

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/SPIRV-Cross#1664]
Greetings,

I have a api user question, but I don't know if this is the right method to submit it. If no, please excuse me and close this.

I compile a GLSL shader to spirv using spirv-cross. After that, I use the latter to extract the decoration etc. from it, including the offsets of the push_constants from the vertex and fragment shader. I do not manually set offsets in the shader via layout qualifier.

Now, when I read back the push_constants offsets from the resources it seems to me that the offsets start at 0 for each of the vertex and fragment stages. However, that means the push_constant definitions from vertex and fragment will overlap  which causes problems since all push_constants share the same space, right?

Is there any way to have spirv_cross rewire the offsets so there are no more overlaps?

Regards.

**Comment by HansKristian-Work** [comment]
Please post example SPIR-V files.

**Comment by Desperado17** [comment]
SPIR-V or the GLSL files?

**Comment by HansKristian-Work** [comment]
Both can't hurt.

**Comment by Desperado17** [comment]
I have to wait until tomorrow until I'm back at the office. Can you tell me what is the regular behaviour for the push_constant offsets generated by the GLSL compiler if the GLSL file doesn't specify them? Should they be distinct between stages?

**Comment by HansKristian-Work** [comment]
You normally would need to specify offsets manually with `layout(offset = 64) float C;`.

**Comment by Desperado17** [comment]
So there is no functionality in spirv_cross that would help me synchronize vertex and fragment offsets? Or even reset them via the api afterwards?

**Comment by HansKristian-Work** [comment]
You can override offsets with set_member_decoration on the push constant block, but that's about it.

**Comment by Desperado17** [comment]
What if I declare the same push_constant block in both vertex and fragment stage with the combined set of variables, then update them with one vkCmdPushConstants call?

I tried that but I get a UNASSIGNED-CoreValidation-Shader-PushConstantOutOfRange validation error because the glsl compiler seems to omit the variables for the stage where they are not used.

**Comment by HansKristian-Work** [comment]
Closing this as I don't think there is a SPIRV-Cross issue here.
