### ISSUE TITLE
OpenGL Error when linking GLSL shaders due to variables naming

### ISSUE THREAD

**Issue by Loki7979** [KhronosGroup/SPIRV-Cross#168]
Hi,

I am developing a Multiplatform and multi graphics API C++ 3d engine and I am writing all shaders in HLSL (my preferred language).
When executing the 3d engine on Windows platform and OpenGL 4.2, HLSL shaders are translated to GLSL (HLSL -> SPIRV binary -> GLSL) and OpenGL links the shaders successfully.
But when I perform the same operation on Mac OS (Sierra) machine, Mac OS OpenGL implementation throws the following error when linking:

27/4/2017 10:25:5.0 ERROR : Error linking shader :
WARNING: Output of vertex shader '_entryPointOutput' not read by fragment shader
ERROR: Input of fragment shader '_input' not written by vertex shader

The error is generated by the following glsl code lines:
Vertex Shader:
layout(location = 0) out VertexOut_1 _entryPointOutput;
Fragment Shader:
layout(location = 0) in VertexOut_1 _input;

It seems that Mac OS OpenGL implementation requires outputs from Vertex shader and inputs from Fragment shader that share the same location to have the same name.

Of course, I could replace the name manually but this doesn't seem the proper way to solve it.
Any suggestions?

Thank you very much! Keep the good work!

Regards 

Agustí

**Comment by HansKristian-ARM** [comment]
Which GLSL version are you using as the target? Are the types VertexOut_1 declared exactly the same?

This shader should work fine (location is used instead of name to match), but it could be a bug in the OSX implementation. This kind of case (HLSL -> GLSL) is covered in the README. It is intended that you can fiddle with the variable name to make things match. This is needed for legacy GLSL where there is no layout() to use. This also goes for the struct name (which does need to match).

**Comment by Loki7979** [comment]
Thanks for the quick response,

I am using OpenGL 4.1 as target on OS X platform and yes, the types on the VertexOut_1 struct are the same in both shaders. Here you can see the shader code generated by SPIRV-Cross:

GLSL
-----
VERTEX SHADER
-----------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct VertexIn
{
    vec3 position;
    vec3 normal;
    vec3 tangent;
    vec2 uv1;
};

struct VertexOut
{
    vec4 pos;
    vec3 normalWorld;
    vec3 posWorld;
    vec2 tex;
    vec3 tangentWorld;
};

struct VertexOut_1
{
    vec3 normalWorld;
    vec3 posWorld;
    vec2 tex;
    vec3 tangentWorld;
};

layout(std140) uniform _shared_camera
{
    mat4 V;
    mat4 invV;
    mat4 P;
    mat4 invP;
} __shared_camera;

layout(std140) uniform model
{
    mat4 M;
    mat4 invM;
} _model;

layout(location = 0) in vec3 position;
layout(location = 1) in vec3 normal;
layout(location = 2) in vec3 tangent;
layout(location = 3) in vec2 uv1;
layout(location = 0) out VertexOut_1 _entryPointOutput;

VertexOut _vs_main(VertexIn _input)
{
    VertexOut _output;
    _output.pos = __shared_camera.P * (__shared_camera.V * (_model.M * vec4(_input.position, 1.0)));
    _output.posWorld = (_model.M * vec4(_input.position, 1.0)).xyz;
    _output.normalWorld = normalize((_model.M * vec4(_input.normal, 0.0)).xyz);
    _output.tangentWorld = normalize((_model.M * vec4(_input.tangent, 0.0)).xyz);
    _output.tex = vec2(_input.uv1.x, 1.0 - _input.uv1.y);
    return _output;
}

void main()
{
    VertexIn _input;
    _input.position = position;
    _input.normal = normal;
    _input.tangent = tangent;
    _input.uv1 = uv1;
    VertexIn param = _input;
    VertexOut flattenTemp = _vs_main(param);
    gl_Position = flattenTemp.pos;
    _entryPointOutput.normalWorld = flattenTemp.normalWorld;
    _entryPointOutput.posWorld = flattenTemp.posWorld;
    _entryPointOutput.tex = flattenTemp.tex;
    _entryPointOutput.tangentWorld = flattenTemp.tangentWorld;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}


FRAGMENT SHADER
---------------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct VertexOut
{
    vec4 pos;
    vec3 normalWorld;
    vec3 posWorld;
    vec2 tex;
    vec3 tangentWorld;
};

struct VertexOut_1
{
    vec3 normalWorld;
    vec3 posWorld;
    vec2 tex;
    vec3 tangentWorld;
};

layout(std140) uniform _shared_lighting
{
    mat4 lightView;
    mat4 lightProj;
    mat4 lightWorldToTex;
    vec4 ambientLightColor;
    vec4 lightColor;
} __shared_lighting;

uniform sampler2D diffuseTex;
uniform sampler2D specularTex;
uniform sampler2D bumpTex;

layout(location = 0) in VertexOut_1 _input;
layout(location = 0) out vec4 _entryPointOutput;

vec3 GetBumpMappedSurfaceNormal(vec3 surfaceNormal, inout vec3 surfaceTangent, inout vec3 bumpMapNormal)
{
    surfaceTangent = normalize(surfaceTangent - (surfaceNormal * dot(surfaceTangent, surfaceNormal)));
    vec3 biTangent = cross(surfaceTangent, surfaceNormal);
    bumpMapNormal = (bumpMapNormal * 2.0) - vec3(1.0);
    mat3 TBN = mat3(vec3(surfaceTangent), vec3(biTangent), vec3(surfaceNormal));
    return bumpMapNormal * TBN;
}

vec3 GetDiffuseReflection(vec3 lightColor, vec3 diffuseColor, vec3 surfaceNormal, vec3 lightDir)
{
    return (lightColor * diffuseColor) * clamp(dot(surfaceNormal, lightDir), 0.0, 1.0);
}

vec3 GetSpecularReflection(vec3 lightColor, vec3 diffuseColor, vec3 surfaceNormal, vec3 lightDirection, vec3 viewDirection, float specularIntensity, float shininess)
{
    return ((diffuseColor * specularIntensity) * pow(clamp(dot(reflect(-lightDirection, surfaceNormal), viewDirection), 0.0, 1.0), 1.0 + shininess)) * lightColor;
}

vec4 _ps_main(VertexOut _input_1)
{
    vec4 diffuseColor = texture(diffuseTex, _input_1.tex);
    vec4 specularColor = texture(specularTex, _input_1.tex);
    vec4 bumpedNormal = texture(bumpTex, _input_1.tex);
    vec3 ldir = vec3(__shared_lighting.lightView[0].z, __shared_lighting.lightView[1].z, __shared_lighting.lightView[2].z);
    vec3 param = _input_1.normalWorld;
    vec3 param_1 = _input_1.tangentWorld;
    vec3 param_2 = bumpedNormal.xyz;
    vec3 _175 = GetBumpMappedSurfaceNormal(param, param_1, param_2);
    vec3 surfaceNormal = _175;
    vec3 param_3 = __shared_lighting.lightColor.xyz;
    vec3 param_4 = diffuseColor.xyz;
    vec3 param_5 = surfaceNormal;
    vec3 param_6 = -ldir;
    vec3 diffuseReflection = GetDiffuseReflection(param_3, param_4, param_5, param_6);
    vec3 viewDir = vec3(__shared_camera.V[0].z, __shared_camera.V[1].z, __shared_camera.V[2].z);
    vec3 param_7 = __shared_lighting.lightColor.xyz;
    vec3 param_8 = diffuseColor.xyz;
    vec3 param_9 = surfaceNormal;
    vec3 param_10 = -ldir;
    vec3 param_11 = viewDir;
    float param_12 = specularColor.x;
    float param_13 = 25.0;
    vec3 specularReflection = GetSpecularReflection(param_7, param_8, param_9, param_10, param_11, param_12, param_13);
    vec4 finalColor = vec4((diffuseReflection + specularReflection) + (diffuseColor.xyz * __shared_lighting.ambientLightColor.xyz), diffuseColor.w);
    return finalColor;
}

void main()
{
    VertexOut _input_1;
    _input_1.pos = gl_FragCoord;
    _input_1.normalWorld = _input.normalWorld;
    _input_1.posWorld = _input.posWorld;
    _input_1.tex = _input.tex;
    _input_1.tangentWorld = _input.tangentWorld;
    VertexOut param = _input_1;
    _entryPointOutput = _ps_main(param);
}

--------------------

I have read the readme.txt but it refers to struct naming but not to struct INSTANCE naming declaration.
So, do you think the solution should be to rename the the struct instances manually? When I do it manually the shader linking works.

Thank you very much.

Agustí

**Comment by Loki7979** [comment]
Well, it seems that this problem is caused by OSX OpenGL implementation bug :
http://stackoverflow.com/questions/24267069/opengl-mac-osx-vertex-shader-not-linking-to-fragment-shader
So, the solution is to rename the variables manually.

Agustí

**Comment by Loki7979** [comment]
Sorry for disturbing you again,

I have found a different case where this bug is not so easy to solve (just renaming the struct instances). It occurs when the struct VertexOut_1 only has one attribute. See the GLSL code generated by SPIRV-Cross below (specially to code lines marked in bold):

GLSL
-----
VERTEX SHADER
------------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct VertexOut
{
    vec4 pos;
    vec2 tex;
};

**struct VertexOut_1
{
    vec2 tex;
};**

layout(std140) uniform _shared_renderSettings
{
    uint invertVCoord;
} __shared_renderSettings;


**layout(location = 0) out VertexOut_1 _entryPointOutput;**

VertexOut _vs_main(uint id)
{
    VertexOut _output;
    _output.tex = vec2(mod(float(id), 2.0), float(1u - (id / 2u)));
    _output.pos = vec4(-1.0 + (2.0 * _output.tex.x), 1.0 - (2.0 * (1.0 - _output.tex.y)), 0.0, 1.0);
    if (__shared_renderSettings.invertVCoord == 1u)
    {
        _output.tex.y = 1.0 - _output.tex.y;
    }
    return _output;
}

void main()
{
    uint id = gl_VertexID;
    uint param = id;
    VertexOut flattenTemp = _vs_main(param);
    gl_Position = flattenTemp.pos;
    _entryPointOutput.tex = flattenTemp.tex;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}

FRAGMENT SHADER
-----------------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

layout(std140) uniform shaderCB
{
    uint blurSamples;
    float blurSize;
    float softBlurFactor;
    float sigma;
    vec2 blurDirection;
} _shaderCB;

uniform sampler2D diffuseTex;
uniform sampler2D blurMaskTex;

**layout(location = 0) in vec2 tex;**
layout(location = 0) out vec4 _entryPointOutput;

vec4 _ps_main(vec4 pos, vec2 tex_1)
{
    vec4 diffuseColor = texture(diffuseTex, tex_1);
    bool _40 = _shaderCB.softBlurFactor >= 1.0;
    bool _49;
    if (!_40)
    {
        _49 = _shaderCB.blurSize == 0.0;
    }
    else
    {
        _49 = _40;
    }
    if (_49)
    {
        return diffuseColor;
    }
    float maskValue = 1.0 - texture(blurMaskTex, tex_1).x;
    float fixedBlurSize = _shaderCB.blurSize * maskValue;
    vec3 incrementalGaussian;
    incrementalGaussian.x = 1.0 / (2.5066282749176025390625 * _shaderCB.sigma);
    incrementalGaussian.y = exp(-0.5 / (_shaderCB.sigma * _shaderCB.sigma));
    incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;
    vec4 avgValue = vec4(0.0);
    float coefficientSum = 0.0;
    uint numBlurPixelsPerSide = 0u;
    if (mod(float(_shaderCB.blurSamples), 2.0) != 0.0)
    {
        avgValue += (diffuseColor * incrementalGaussian.x);
        coefficientSum += incrementalGaussian.x;
        numBlurPixelsPerSide = (_shaderCB.blurSamples - 1u) / 2u;
    }
    else
    {
        numBlurPixelsPerSide = _shaderCB.blurSamples / 2u;
    }
    vec2 _135 = incrementalGaussian.xy * incrementalGaussian.yz;
    incrementalGaussian = vec3(_135.x, _135.y, incrementalGaussian.z);
    vec2 deltaOffset = _shaderCB.blurDirection * (fixedBlurSize / float(_shaderCB.blurSamples));
    for (uint i = 1u; i <= numBlurPixelsPerSide; i++)
    {
        avgValue += (texture(diffuseTex, tex_1 - (deltaOffset * float(i))) * incrementalGaussian.x);
        avgValue += (texture(diffuseTex, tex_1 + (deltaOffset * float(i))) * incrementalGaussian.x);
        coefficientSum += (2.0 * incrementalGaussian.x);
        vec2 _197 = incrementalGaussian.xy * incrementalGaussian.yz;
        incrementalGaussian = vec3(_197.x, _197.y, incrementalGaussian.z);
    }
    return mix(avgValue / vec4(coefficientSum), diffuseColor, vec4(_shaderCB.softBlurFactor));
}

void main()
{
    vec4 pos = gl_FragCoord;
    vec2 tex_1 = tex;
    vec4 param = pos;
    vec2 param_1 = tex_1;
    _entryPointOutput = _ps_main(param, param_1);
}

------------------------------------------------------------

As you can see, this time, the struct VertexOut_1 is not declared on the fragment shader and the input variable of the fragment shader is vec2 type (single member of struct VertexOut_1 on the vertex shader).
So, in this case, the following changes have to be performed to the shader code to avoid linking errors. (All changes are marked in bold): 

VERTEX SHADER
------------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct VertexOut
{
    vec4 pos;
    vec2 tex;
};

struct VertexOut_1
{
    vec2 tex;
};

layout(std140) uniform _shared_renderSettings
{
    uint invertVCoord;
} __shared_renderSettings;


layout(location = 0) out VertexOut_1 **_vertexOut1**;

VertexOut _vs_main(uint id)
{
    VertexOut _output;
    _output.tex = vec2(mod(float(id), 2.0), float(1u - (id / 2u)));
    _output.pos = vec4(-1.0 + (2.0 * _output.tex.x), 1.0 - (2.0 * (1.0 - _output.tex.y)), 0.0, 1.0);
    if (__shared_renderSettings.invertVCoord == 1u)
    {
        _output.tex.y = 1.0 - _output.tex.y;
    }
    return _output;
}

void main()
{
    uint id = gl_VertexID;
    uint param = id;
    VertexOut flattenTemp = _vs_main(param);
    gl_Position = flattenTemp.pos;
    _entryPointOutput.tex = flattenTemp.tex;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}

FRAGMENT SHADER
-----------------------
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

layout(std140) uniform shaderCB
{
    uint blurSamples;
    float blurSize;
    float softBlurFactor;
    float sigma;
    vec2 blurDirection;
} _shaderCB;

**struct VertexOut_1
{
    vec2 tex;
};**

uniform sampler2D diffuseTex;
uniform sampler2D blurMaskTex;

layout(location = 0) in **VertexOut_1 _vertexOut1**;
layout(location = 0) out vec4 _entryPointOutput;

vec4 _ps_main(vec4 pos, vec2 tex_1)
{
    vec4 diffuseColor = texture(diffuseTex, tex_1);
    bool _40 = _shaderCB.softBlurFactor >= 1.0;
    bool _49;
    if (!_40)
    {
        _49 = _shaderCB.blurSize == 0.0;
    }
    else
    {
        _49 = _40;
    }
    if (_49)
    {
        return diffuseColor;
    }
    float maskValue = 1.0 - texture(blurMaskTex, tex_1).x;
    float fixedBlurSize = _shaderCB.blurSize * maskValue;
    vec3 incrementalGaussian;
    incrementalGaussian.x = 1.0 / (2.5066282749176025390625 * _shaderCB.sigma);
    incrementalGaussian.y = exp(-0.5 / (_shaderCB.sigma * _shaderCB.sigma));
    incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;
    vec4 avgValue = vec4(0.0);
    float coefficientSum = 0.0;
    uint numBlurPixelsPerSide = 0u;
    if (mod(float(_shaderCB.blurSamples), 2.0) != 0.0)
    {
        avgValue += (diffuseColor * incrementalGaussian.x);
        coefficientSum += incrementalGaussian.x;
        numBlurPixelsPerSide = (_shaderCB.blurSamples - 1u) / 2u;
    }
    else
    {
        numBlurPixelsPerSide = _shaderCB.blurSamples / 2u;
    }
    vec2 _135 = incrementalGaussian.xy * incrementalGaussian.yz;
    incrementalGaussian = vec3(_135.x, _135.y, incrementalGaussian.z);
    vec2 deltaOffset = _shaderCB.blurDirection * (fixedBlurSize / float(_shaderCB.blurSamples));
    for (uint i = 1u; i <= numBlurPixelsPerSide; i++)
    {
        avgValue += (texture(diffuseTex, tex_1 - (deltaOffset * float(i))) * incrementalGaussian.x);
        avgValue += (texture(diffuseTex, tex_1 + (deltaOffset * float(i))) * incrementalGaussian.x);
        coefficientSum += (2.0 * incrementalGaussian.x);
        vec2 _197 = incrementalGaussian.xy * incrementalGaussian.yz;
        incrementalGaussian = vec3(_197.x, _197.y, incrementalGaussian.z);
    }
    return mix(avgValue / vec4(coefficientSum), diffuseColor, vec4(_shaderCB.softBlurFactor));
}

void main()
{
    vec4 pos = gl_FragCoord;
    vec2 tex_1 = **_vertexOut1.tex**;
    vec4 param = pos;
    vec2 param_1 = tex_1;
    _entryPointOutput = _ps_main(param, param_1);
}

---------------------------------------------------------------
As you can see, now is more complicated to solve, as VertexOut_1 struct declaration has to be inserted manually on fragment shader code. I fear that this type of issue could happen in other shader stages.
I am wondering if SPIRV-Cross could help handling this bug automatically as it seems that Apple will never fix it.

Thank you veru much!

Agustí

**Comment by ratchetfreak** [comment]
FYI you can surround the code with 3 backticks to format it as code. It preserves indentation so it's easier to follow.

**Comment by Loki7979** [comment]
Thanks for pointing this out, first time I post an issue in GitHub, sorry for the noobish mistake ;-)
I can post the code again with the correct format if you prefer. Anyway, only few lines of code need to be read as the error is generated on the vertex output and fragment input variables, but I understand is much more readable with the correct format.

Agustí

**Comment by ratchetfreak** [comment]
You can also edit your comment with the little pencil. It's preferable to do that than to repeat yourself

**Comment by Loki7979** [comment]
Thanks for the tutorial! Now the code has the proper format! Now I really feel I am part of the GitHub community! :-) 

I hope the issue will become more understandable now!

Agustí
Agustí

**Comment by HansKristian-ARM** [comment]
SPIRV-Cross cannot automatically fix issues like this. It does not know about the entire pipeline.
As for the mismatch between output struct in vertex and plain vec2 input in fragment, that sounds like a problem with the HLSL, that cannot work.

What are the original HLSL shaders here?

**Comment by Loki7979** [comment]
Here you can see the original code:

HLSL
------
VERTEX SHADER
------------------
```

cbuffer _shared_renderSettings
{
	uint invertVCoord;
};
																						
struct VertexOut																			
{																							
	float4 pos : SV_POSITION;																
	float2 tex : TEXCOORD0;																	
};																							
																							
VertexOut vs_main(uint id : SV_VertexID)													
{																							
	VertexOut output;																		
																							
	//we build a fullscreen quad using id input value (id has to be equal to [0,3])			
		output.tex = float2(fmod(id, 2), 1 - (id / 2));										
		output.pos = float4((-1 + 2 * output.tex.x), (1 - 2 * (1 - output.tex.y)), 0, 1);	
	if(invertVCoord == 1)																	
		output.tex.y = 1 - output.tex.y;													
	return output;																			
}
```

FRAGMENT SHADER
-----------------------

```
SamplerState linearSampler;
SamplerState pointSampler;

Texture2D diffuseTex;
Texture2D blurMaskTex;

cbuffer shaderCB
{
	uint blurSamples;
	float blurSize;
	float softBlurFactor;
	float sigma; 
	float2 blurDirection; 
};

static const float pi = 3.14159265;
float4 ps_main(float4 pos : SV_POSITION, float2 tex : TEXCOORD0) : SV_TARGET0
{
	float4 diffuseColor = diffuseTex.Sample(linearSampler, tex);
	if (softBlurFactor >= 1.0 || blurSize == 0.0)
		return diffuseColor;
	float maskValue = 1 - blurMaskTex.Sample(pointSampler, tex).r;
	float fixedBlurSize = blurSize * maskValue;
	
	// Incremental Gaussian Coefficent Calculation (See GPU Gems 3 pp. 877 - 889)
	float3 incrementalGaussian;
	incrementalGaussian.x = 1.0 / (sqrt(2.0 * pi) * sigma);
	incrementalGaussian.y = exp(-0.5 / (sigma * sigma));
	incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;
	float4 avgValue = float4(0.0, 0.0, 0.0, 0.0);
	float coefficientSum = 0.0;
	uint numBlurPixelsPerSide = 0;
	if (fmod(blurSamples, 2) != 0)
	{
		// Take the central sample first...
		avgValue += diffuseColor * incrementalGaussian.x;
		coefficientSum += incrementalGaussian.x;
		numBlurPixelsPerSide = (blurSamples - 1) / 2;
	}
	else
		numBlurPixelsPerSide = (blurSamples) / 2;
	incrementalGaussian.xy *= incrementalGaussian.yz;
	float2 deltaOffset = (fixedBlurSize / blurSamples) * blurDirection;
	// Go through the remaining samples
	for (uint i = 1; i <= numBlurPixelsPerSide; ++i) 
	{
		avgValue += diffuseTex.Sample(linearSampler, tex - i * deltaOffset) * incrementalGaussian.x;
		avgValue += diffuseTex.Sample(linearSampler, tex + i * deltaOffset) * incrementalGaussian.x;
		coefficientSum += 2.0 * incrementalGaussian.x;
		incrementalGaussian.xy *= incrementalGaussian.yz;
	}
	
	return lerp(avgValue / coefficientSum, diffuseColor, softBlurFactor);
}
```

It doesn't seem to be anything wrong with the code. As I told you in previous messages, when I translate the shaders to GLSL on windows platform, OpenGL shader linking works ok.
Does SPIRV-Cross add the code lines corresponding to VertexOut_1 struct declaration on the vertex shader?

```
struct VertexOut_1
{
    vec2 tex;
};
```
If so, perhaps the solution should be to avoid the struct declaration on the vertex shader when it has only one attribute, and to write the vertex output declaration like this :

`layout(location = 0) out vec2 tex;`

```

**Comment by HansKristian-ARM** [comment]
Yes, the problem is that the vertex shader returns a struct, while the fragment shader takes just a pure semantic variable. I'm not sure how HLSL semantics are supposed to work, but glslang does not generate compatible code here.

At any rate, SPIRV-Cross cannot safely "rewrite" stuff like this. This is most likely a glslang issue which needs to be sorted out.

**Comment by HansKristian-ARM** [comment]
glslang issue: https://github.com/KhronosGroup/glslang/issues/871

**Comment by Loki7979** [comment]
Well, I am not sure if it's a glslang issue because, on Windows platform, OpenGL is able to link the shaders correctly.

Unfortunatelly, OS X OpenGL implementation doesn't follow the same logic and is not able to relate the vertex shader output struct and the fragment shader input variables specified directly as parameters on the fragment shader method.

Finally, I solved the issue by rewriting the HLSL shader, so the inputs on the fragment shader are declared as struct instead of as parameters. This way, the shaders are linked correctly on Windows and MacOS.

Here you can see the fixed code:

FRAGMENT SHADER
---------------------
HLSL
-----
```
SamplerState linearSampler;
SamplerState pointSampler;

Texture2D diffuseTex;
Texture2D blurMaskTex;

cbuffer materialCB
{
	uint blurSamples;
	float blurSize;
	float softBlurFactor;
	float sigma; 
	float2 blurDirection; 
};

struct VertexOut
{
	float4 pos : SV_POSITION;
	float2 tex : TEXCOORD0;
};

static const float pi = 3.14159265;

float4 ps_main(VertexOut input) : SV_TARGET0
{
	float4 diffuseColor = diffuseTex.Sample(linearSampler, input.tex);

	if (softBlurFactor >= 1.0 || blurSize == 0.0)
		return diffuseColor;

	float maskValue = 1 - blurMaskTex.Sample(pointSampler, input.tex).r;

	float fixedBlurSize = blurSize * maskValue;
	
	// Incremental Gaussian Coefficent Calculation (See GPU Gems 3 pp. 877 - 889)
	float3 incrementalGaussian;
	incrementalGaussian.x = 1.0 / (sqrt(2.0 * pi) * sigma);
	incrementalGaussian.y = exp(-0.5 / (sigma * sigma));
	incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;

	float4 avgValue = float4(0.0, 0.0, 0.0, 0.0);
	float coefficientSum = 0.0;
	uint numBlurPixelsPerSide = 0;

	if (fmod(blurSamples, 2) != 0)
	{
		// Take the central sample first...
		avgValue += diffuseColor * incrementalGaussian.x;
		coefficientSum += incrementalGaussian.x;
		numBlurPixelsPerSide = (blurSamples - 1) / 2;
	}
	else
		numBlurPixelsPerSide = (blurSamples) / 2;

	incrementalGaussian.xy *= incrementalGaussian.yz;

	float2 deltaOffset = (fixedBlurSize / blurSamples) * blurDirection;

	// Go through the remaining vertical samples
	for (uint i = 1; i <= numBlurPixelsPerSide; ++i) 
	{
		avgValue += diffuseTex.Sample(linearSampler, input.tex - i * deltaOffset) * incrementalGaussian.x;
		avgValue += diffuseTex.Sample(linearSampler, input.tex + i * deltaOffset) * incrementalGaussian.x;

		coefficientSum += 2.0 * incrementalGaussian.x;
		incrementalGaussian.xy *= incrementalGaussian.yz;
	}
	
	return lerp(avgValue / coefficientSum, diffuseColor, softBlurFactor);
}
```
GLSL (Translated by SPIRV-Cross)
-----
```
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct VertexOut
{
    vec4 pos;
    vec2 tex;
};

struct VertexOut_1
{
    vec2 tex;
};

layout(std140) uniform materialCB
{
    uint blurSamples;
    float blurSize;
    float softBlurFactor;
    float sigma;
    vec2 blurDirection;
} _materialCB;

uniform sampler2D diffuseTex;
uniform sampler2D blurMaskTex;

layout(location = 0) in VertexOut_1 _vertexOut1;
layout(location = 0) out vec4 _entryPointOutput;

vec4 _ps_main(VertexOut _vertexOut1_1)
{
    vec4 diffuseColor = texture(diffuseTex, _vertexOut1_1.tex);
    bool _43 = _materialCB.softBlurFactor >= 1.0;
    bool _51;
    if (!_43)
    {
        _51 = _materialCB.blurSize == 0.0;
    }
    else
    {
        _51 = _43;
    }
    if (_51)
    {
        return diffuseColor;
    }
    float maskValue = 1.0 - texture(blurMaskTex, _vertexOut1_1.tex).x;
    float fixedBlurSize = _materialCB.blurSize * maskValue;
    vec3 incrementalGaussian;
    incrementalGaussian.x = 1.0 / (2.5066282749176025390625 * _materialCB.sigma);
    incrementalGaussian.y = exp(-0.5 / (_materialCB.sigma * _materialCB.sigma));
    incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;
    vec4 avgValue = vec4(0.0);
    float coefficientSum = 0.0;
    uint numBlurPixelsPerSide = 0u;
    if (mod(float(_materialCB.blurSamples), 2.0) != 0.0)
    {
        avgValue += (diffuseColor * incrementalGaussian.x);
        coefficientSum += incrementalGaussian.x;
        numBlurPixelsPerSide = (_materialCB.blurSamples - 1u) / 2u;
    }
    else
    {
        numBlurPixelsPerSide = _materialCB.blurSamples / 2u;
    }
    vec2 _138 = incrementalGaussian.xy * incrementalGaussian.yz;
    incrementalGaussian = vec3(_138.x, _138.y, incrementalGaussian.z);
    vec2 deltaOffset = _materialCB.blurDirection * (fixedBlurSize / float(_materialCB.blurSamples));
    for (uint i = 1u; i <= numBlurPixelsPerSide; i++)
    {
        avgValue += (texture(diffuseTex, _vertexOut1_1.tex - (deltaOffset * float(i))) * incrementalGaussian.x);
        avgValue += (texture(diffuseTex, _vertexOut1_1.tex + (deltaOffset * float(i))) * incrementalGaussian.x);
        coefficientSum += (2.0 * incrementalGaussian.x);
        vec2 _202 = incrementalGaussian.xy * incrementalGaussian.yz;
        incrementalGaussian = vec3(_202.x, _202.y, incrementalGaussian.z);
    }
    return mix(avgValue / vec4(coefficientSum), diffuseColor, vec4(_materialCB.softBlurFactor));
}

void main()
{
    VertexOut _vertexOut1_1;
    _vertexOut1_1.pos = gl_FragCoord;
    _vertexOut1_1.tex = _vertexOut1.tex;
    VertexOut param = _vertexOut1_1;
    _entryPointOutput = _ps_main(param);
}
```
 
So, the only modification to perform on the SPIRV-Cross generated code is to rename the vertex shader outputs and fragment shader so they share the same name.

I believe we can close the issue as I already have found a solution

Thanks for the help

Agustí
