### ISSUE TITLE
CLI MSL BaseInstance support

### ISSUE THREAD

**Issue by glangis-ubi** [KhronosGroup/SPIRV-Cross#1682]
Hello.

Using the CLI, SPIRV-Cross will throw this exception:

`SPIRV-Cross threw an exception: BaseInstance requires Metal 1.1 and Mac or Apple A9+ hardware.`

However, these are the options I'm using: **--msl --msl-ios --msl-version 20100 --msl-texture-buffer-native --msl-argument-buffers --entry main**

After messing a bit with the code, it seems base instance support is not something I can turn on for the CLI, but does function (at least for the small shaders I'm using). Adding it as a command line argument seems pretty straightforward, but I wanted to make sure I'm not missing something.

**Comment by HansKristian-Work** [comment]
Just enabled the option in CLI unconditionally on master.
