### ISSUE TITLE
GLSL: Flat branches for OpSelectionMerge with 'Flatten'

### ISSUE THREAD

**Issue by sindney** [KhronosGroup/SPIRV-Cross#1684]
Hi, i'm compiling HLSL to SPIR-V (using DirectXShaderCompiler) to GLES (using SPIRV-Cross):

```bash
# HLSL to SPIR-V binary
.\dxc.exe -E main -T ps_6_0 -spirv -Od -Fo .\if2.bin .\if2.hlsl
# SPIR-V binary to es glsl
.\spirv-cross.exe --es .\if2.bin
```

I'm using HLSL's attribute feature to trying to flat some if branches.

```hlsl
[flatten] if(x) {
  x = sqrt(x);
}
```

The test shader looks like this:

```hlsl
float main(float2 a : A, int b : B) : SV_Target {
  [flatten]
  if (b == 1)
    return a.x;
  return a.y;
}
```

Result glsl no matter [flatten] is configured or not:

```
#version 450 es
precision mediump float;
precision highp int;

layout(location = 0) in highp vec2 in_var_A;
layout(location = 1) flat in int in_var_B;
layout(location = 0) out highp float out_var_SV_Target;

highp float src_main(highp vec2 a, int b) {
    if (b == 1) {
        return a.x;
    }
    return a.y;
}

void main() {
    highp vec2 param_var_a = in_var_A;
    int param_var_b = in_var_B;
    out_var_SV_Target = src_main(param_var_a, param_var_b);
}
```

I diffed SPIR-V output by comment out [flatten] attribute:

```diff
@@ -60,7 +60,7 @@
    %bb_entry = OpLabel
          %28 = OpLoad %int %b
          %30 = OpIEqual %bool %28 %int_1
-               OpSelectionMerge %if_merge Flatten
+               OpSelectionMerge %if_merge None
                OpBranchConditional %30 %if_true %if_merge
     %if_true = OpLabel
          %34 = OpAccessChain %_ptr_Function_float %a %int_0
```

Seems SPIR-V to GLSL didn't flatten the specified if branch, am i missing something? 
--no-es, --msl returns roughly the same result. It only works when targeting HLSL:

```hlsl
// ...
struct SPIRV_Cross_Output {
    float4 out_var_SV_Target : COLOR0;
};

float src_main(float2 a, int b)
{
    [flatten]
    if (b == 1) {
        return a.x;
    }
    return a.y;
}
// ...
```

Is this a unsupported feature when compiling to non-HLSL target?

I figured loop unrolling is handled by spirv-opt. But i didn't find related options for [branch attrubute](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-if) [Flatten]

**Comment by HansKristian-Work** [comment]
Adding support for control flow hints in GLSL using GL_EXT_control_flow_hints. MSL does not support this. Rewriting any code to enforce this is not the job of SPIRV-Cross, that is spirv-opt territory.

**Comment by sindney** [comment]
Understood, thanks.
