### ISSUE TITLE
Getting the HLSL Semantic Name using the Reflection API

### ISSUE THREAD

**Issue by FahimFuad** [KhronosGroup/SPIRV-Cross#1687]
Hello! Is there is any way by which I can get the semantic name that I used in my HLS shader? That is, I have a shader like
```hlsl
struct vsOut
{
    float4 v_Position  : SV_POSITION;
    float3 v_Normal    : M_NORMAL;
    //....
};

vsOut main(vsIn input)
{
    //....
}
```
Is there is any way by which I can get the name `M_NORMAL` from the spirv of this vertex shader by using the SPIRV Cross Reflection API? Thanks in advance 🙂

**Comment by cdavis5e** [comment]
Try looking for an `HlslSemantic` decoration.

**Comment by HansKristian-Work** [comment]
Yes, HlslSemantic is the way to go here. Compiler::get_decoration_string can deal with this.
