### ISSUE TITLE
Bug: Problems handling conditional expressions 

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/SPIRV-Cross#1694]
The following Vulkan GLSL
```glsl
		bool fail = true;
		vec3 acc = fail ? vec3(1.f,0.f,0.f):vec3(0.f,1.f,0.f);
```
gets transpiled to the following OpenGL GLSL
```glsl
        bool fail = true;
        vec3 acc = vec3(fail);
```
which is obviously wrong.

**Comment by HansKristian-Work** [comment]
Reproduced. I think this is related to SPIR-V 1.4 which relaxed OpSelect to support scalar selector even with composite input.
