### ISSUE TITLE
Flatten matrix vertex input for GLSL

### ISSUE THREAD

**Issue by cpt-max** [KhronosGroup/SPIRV-Cross#1695]
There is an option to [flatten matrices into multiple vectors for HLSL](https://github.com/KhronosGroup/SPIRV-Cross/pull/1523/commits/b3344174f7474c97ed473893d072317d06f156db)
Any chance to get the same for GLSL?

**Comment by HansKristian-Work** [comment]
Why is this needed? GLSL supports this, and I don't want to add complicated flatten/unflatten hacks for this.

**Comment by cpt-max** [comment]
The framework I'm using (MonoGame) uses vectors to represent vertex shader inputs, also for matrices. 
For each vector it finds the corresponding shader input using glGetAttribLocation. If you have a matrix in the vertex shader, rather than separate vectors, this will currently fail.

If the shader compiler could turn matrices into vectors, it would have solved this problem, but I'm sure there's other solutions as well.

**Comment by cpt-max** [comment]
Thanks, I solved it like you suggested.
