### ISSUE TITLE
[Question] HLSL and RowMajor/ColumnMajor matrices

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#170]
When adding spirv-cross support to my engine I noticed that I need to pass a transposed model-view-projection matrix to the vertex shader in D3D11, which is different to GL and Metal. I realize that GL and D3D traditionally had different row/column order convention, however I'm using GLM on the CPU side, so matrices passed to shaders are always GL style, regardless of the rendering backend.

What's the recommended way to resolve this? Should I pass transposed matrices when running in D3D11? Or should I manually add or change the ColMajor/RowMajor decorations?

Or is this a missing feature or option in the HLSL backend? for instance, searching for DecorationRowMajor and DecorationColMajor yields hits in the GLSL and MSL backends, but not in the HLSL backends (paging @RobDangerous)

Thanks :)

**Comment by HansKristian-ARM** [comment]
I don't think the HLSL backend considers RowMajor vs ColumnMajor atm. GLSL will emit column major by default, but HLSL is row-major default iirc. Ideally, we'd only have to tack on column-major in the HLSL.

**Comment by RobDangerous** [comment]
Have to have a closer look. Will call you back...

**Comment by floooh** [comment]
HLSL also has row_major / column_major type modifiers (https://msdn.microsoft.com/en-us/library/windows/desktop/bb509706(v=vs.85).aspx), but I'm not sure if the 'wrong one' leads to additional code when loading the ub matrix data into registers.

**Comment by floooh** [comment]
I played around a bit with this in my fork, here's what I came up with:

First in my own command line tool around SPIRV-Cross, I'm enforcing the matrix order of all matrices in uniform buffers, this is basically defines what matrix convention the engine is passing to shaders:

```cpp
void fix_ub_matrix_force_colmajor(Compiler* compiler) {
    // go though all uniform block matrixes and decorate them with
    // column-major, this is needed in the HLSL backend to fix the
    // multiplication order
    ShaderResources res = compiler->get_shader_resources();
    for (const Resource& ub_res : res.uniform_buffers) {
        const SPIRType& ub_type = compiler->get_type(ub_res.base_type_id);
        for (int m_index = 0; m_index < int(ub_type.member_types.size()); m_index++) {
            const SPIRType& m_type = compiler->get_type(ub_type.member_types[m_index]);
            if ((m_type.basetype == SPIRType::Float) && (m_type.vecsize > 1) && (m_type.columns > 1)) {
                compiler->set_member_decoration(ub_res.base_type_id, m_index, DecorationColMajor);
            }
        }
    }
}
```
This function is also useful for testing, I can flip the decoration to RowMajor, in the engine pass all matrices transposed, and the result should look right again across all rendering backends and shader languages.

In the SPIRV-Cross HLSL backend I had to do 2 changes, first I had to set the backend flag ```native_row_major_flag``` to false, otherwise the need_transpose in the multiply ops wouldn't be set, since on higher-version GLSL backends which have this set to true, a ```layout(row_major)``` would be emitted, instead of reversing the multiplication order (I wonder if this layout(row_major) generates non-optimal loading-code though?).

Then I replaced the handling of OpMatrixTimesVector and OpVectorTimesMatrix with essentially the same code from GLSL.

Both changes are in this commit: https://github.com/floooh/SPIRV-Cross/commit/94dd78b7b683e2e774545015324b602212b2206f

This will now emit mul() function calls with the same order as in GLSL for ColMajor matrices, and reverse the order if the matrices are decorated with RowMajor.

I just not sure about the Matrix*Matrix operation, the HLSL backend also generally reverses the multiplication order compared to the GLSL backend:

HLSL: https://github.com/KhronosGroup/SPIRV-Cross/blob/012cb25b7dd4e9f0ba4bff4a7d6af95f3fc98b66/spirv_hlsl.cpp#L1583

GLSL: https://github.com/KhronosGroup/SPIRV-Cross/blob/543e380d90ebc03d88f69897445e22ed99de768b/spirv_glsl.cpp#L4733

Is this correct? I don't have any matrix*matrix shader code lying around to test unfortunately :)

**Comment by HansKristian-ARM** [comment]
hm ... I suspect this difference is due to the HLSL backend always assuming ColMajor (and HLSL thinks it's row major), which means everything becomes transposed (reverse multiply order to implicitly transpose). Tacking on proper layouts for the matrix order should fix this.

**Comment by alek314** [comment]
I think a global options would suffice. At least in our engine, we stick with only one matrix layout. IMHO,  mixing different matrix layout in one project would make the code hard to maintain.

**Comment by HansKristian-ARM** [comment]
I have made a new issue which will need to sort out the ColumnMajor/RowMajor confusion properly. See #290.

**Comment by HansKristian-ARM** [comment]
@floooh this might be of interest: https://github.com/KhronosGroup/SPIRV-Cross/pull/304

**Comment by floooh** [comment]
Thanks! keeping an eye on it :)
