### ISSUE TITLE
push_constant struct not decompiled correctly

### ISSUE THREAD

**Issue by 16uhrpasing** [KhronosGroup/SPIRV-Cross#1704]
Hi All,

I'm using the latest commit 1ae2b58 of SPIRV-Cross, as well as the VulkanSDK 1.2.176.1

If my shader contains the following snippet:

`layout(push_constant) uniform PushConstants {
    mat4 projection;
    mat4 modelview;
} pc;`

and I compile it via the glslangValidator to the .spv format and decompile it again, it results in:
`struct PushConstants
{
    mat4 projection;
    mat4 modelview;
};

uniform PushConstants pc;
`

Which is not the correct decompilation, since non-opaque uniforms outside a block are not allowed when using GLSL for Vulkan. The decompiled code cannot be compiled again.

**Comment by HansKristian-Work** [comment]
By default, spirv-cross targets GL semantics, which does not support push_constants, and the closest analog is plain uniforms. Try `--vulkan-semantics` or its alias `-V` and it will compile back again to push constants.
