### ISSUE TITLE
[msl] bit casting

### ISSUE THREAD

**Issue by rextimmy** [KhronosGroup/SPIRV-Cross#171]
The glsl bit casting functions like floatBitsToInt (and others like intBitsToFloat) are not getting translated with msl and therefore survive the the round trip. I believe the msl equivalent is as_type<type-id>()

**Comment by billhollings** [comment]
I'm starting to look into this now.

@rextimmy Can you provide a SMALL sample GLSL file that we can add as an MSL test case for this please?

**Comment by rextimmy** [comment]
@billhollings  Yeah no worries
[bitcasting.frag.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/980547/bitcasting.frag.txt)

**Comment by billhollings** [comment]
Fixed in PR #186.
