### ISSUE TITLE
How to Relection Hlsl semantic name

### ISSUE THREAD

**Issue by LuciferSweety** [KhronosGroup/SPIRV-Cross#1713]
I'm trying using directxshadercompiler generate spirv code. and use Compiler::get_decoration_string return empty string.
original  hlsl shader code:
![image](https://user-images.githubusercontent.com/18320190/126443550-c1db904f-7e30-4ae6-b32d-84ce4e9c71d0.png)
output hlsl shader code:
![image](https://user-images.githubusercontent.com/18320190/126443727-a401c3d9-1099-4509-8edb-7c5c25192632.png)
This's a Default Semantic Name(TEXCOORD+N).

**Comment by HansKristian-Work** [comment]
You can try using get_decoration_string() with DecorationHlslSemanticGOOGLE which DXC should emit.

**Comment by LuciferSweety** [comment]
Yes. I had Used it yet, bug decoration's flags haven't flag DecorationHlslSemanticGOOGLE.
I guess that maybe missing some configurable options for DirectXShaderCompiler.
![image](https://user-images.githubusercontent.com/18320190/126639572-6487a83f-94dc-4f55-9db2-a82ee22fcbbc.png)
Thanks.

**Comment by LuciferSweety** [comment]
It's missing command line "-fspv-reflect".
Thank you all the same.
