### ISSUE TITLE
Help build this project.

### ISSUE THREAD

**Issue by DatTaiwanGuy** [KhronosGroup/SPIRV-Cross#1714]
Hi,

i'm struggling on how to build this project that i downloaded from your repository, is there any way you can show me step by step on how to build this thing with either CMake or Visual Studio, cause i'm stuck on what to do with this downloaded project....

**Comment by HansKristian-Work** [comment]
It builds like any CMake project:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
```
That would work on Visual Studio and GCC/Clang.
