### ISSUE TITLE
About plus operation for mat4.

### ISSUE THREAD

**Issue by ockeymm** [KhronosGroup/SPIRV-Cross#1717]
Hello SPIR：
       I use spir-v convert shader from vulkan compatible (version 440) to  GLSL 150. I found that, the "+" operation between two mat4 be converted to vec4 "+" operation.(eg: **mat4 testMatC = testMatA + testMatB** => **mat4 testMatC = mat4(testMatA[0] + testMatB[0], testMatA[1] + testMatB[1], testMatA[2] + testMatB[2], testMatA[3] + testMatB[3]);**) 
      Why do this convert？
[SrcShader.txt](https://github.com/KhronosGroup/SPIR-Registry/files/6915180/SrcShader.txt)
[GLSL150.txt](https://github.com/KhronosGroup/SPIR-Registry/files/6915181/GLSL150.txt)

**Comment by HansKristian-Work** [comment]
Because there is no OpMatrixFAdd in SPIR-V and GLSL compiler needs to unroll this.

**Comment by ockeymm** [comment]
> Because there is no OpMatrixFAdd in SPIR-V and GLSL compiler needs to unroll this.

Thank you!
