### ISSUE TITLE
Bindings don't get picked up properly

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/SPIRV-Cross#1718]
This is a shader I'm trying to round-trip through DXC & spirv-cross as an experiment (ultimately DXC will be replaced by rust-gpu instead).

```hlsl
struct RenderResourceHandle {
    uint handle;

    uint readIndex() { return this.handle & ((1 << 23) - 1); }
    bool isValid() { return this.handle != ~0; }

    uint writeIndex() {
        uint uav_idx = this.handle + 1;
        return uav_idx & ((1 << 23) - 1);
    }
};

struct BindingsOffset {
    RenderResourceHandle bindingsOffset;
    uint userData0;
    uint userData1;
    uint userData2;
};

ConstantBuffer<BindingsOffset> g_bindingsOffset : register(b0, space10);
ByteAddressBuffer g_byteAddressBuffer[] : register(t0, space3);
RWByteAddressBuffer g_rwByteAddressBuffer[] : register(u0, space4);

#define byteBuffer(handle)                                                     \
    g_byteAddressBuffer[NonUniformResourceIndex(handle.readIndex())]
#define rwByteBuffer(handle) g_rwByteAddressBuffer[handle.writeIndex()]

struct Bindings {
    RenderResourceHandle input;
    RenderResourceHandle output;
};

[numthreads(64, 1, 1)]
void main(int threadId: SV_DispatchThreadID)
{
    Bindings bnd = byteBuffer(g_bindingsOffset.bindingsOffset).Load<Bindings>(0);

    rwByteBuffer(bnd.output).Store(threadId, byteBuffer(bnd.input).Load(threadId));
}
```

Invoked with:
```cmd
dxc -Tcs_6_5 -spirv test.hlsl -spirv > test.spirv
```

I'd assemble the `test.spirv` as usual with `spirv-as test.spirv`

Which leads to the `out.spv` file (attached) - I feed that into spirv-cross like so:

[out.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/6950745/out.zip)

```cmd
spirv-cross --dump-resources --hlsl --shader-model 65 out.spv
```

Which leads to the following hlsl output:

```hlsl
struct RenderResourceHandle
{
    uint handle;
};

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint _11 = g_bindingsOffset.bindingsOffset.handle & 8388607u;
    uint _45 = uint(int3(gl_GlobalInvocationID).x) >> 2u;
    uint _16 = g_byteAddressBuffer[NonUniformResourceIndex(_11)].Load<uint>(0) & 8388607u;
    g_rwByteAddressBuffer[(g_byteAddressBuffer[NonUniformResourceIndex(_11)].Load<uint>(4) + 1u) & 8388607u].Store<uint>(_45 * 4 + 0, g_byteAddressBuffer[NonUniformResourceIndex(_16)].Load<uint>(_45 * 4 + 0));
}

[numthreads(64, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
```

This fails to compile because all of the bindings are missing.

**Comment by Jasper-Bekkers** [comment]
I've also noticed that the spirv-cross I have installed on my system (621884d7) will output the bindings with `--dump-bindings`, but the latest one from bab4e591 (lastest master branch) that I built just now doesn't display them anymore.

**Comment by HansKristian-Work** [comment]
Sorry for late reply, was on holiday.

**Comment by HansKristian-Work** [comment]
The SPIR-V is invalid. In SPIR-V 1.4 and later, global active variables (not just stage IO) must be part of the OpEntryPoint list, otherwise, they are filtered out.

**Comment by Jasper-Bekkers** [comment]
@HansKristian-Work I'm not entirely sure what the problem is with the SPIR-V binary? It's not a 1.4 binary (DXC doesn't generate SPIRV 1.4 iirc)? Does spirv-cross only support the latest SPIR-V version?

**Comment by HansKristian-Work** [comment]
> @HansKristian-Work I'm not entirely sure what the problem is with the SPIR-V binary? It's not a 1.4 binary (DXC doesn't generate SPIRV 1.4 iirc)? Does spirv-cross only support the latest SPIR-V version?

The SPIR-V you linked is 1.5:

```
; SPIR-V
; Version: 1.5
; Generator: Khronos SPIR-V Tools Assembler; 0
; Bound: 48
; Schema: 0
               OpCapability Shader
               OpCapability RuntimeDescriptorArray
               OpCapability ShaderNonUniform
               OpExtension "SPV_EXT_descriptor_indexing"
               OpMemoryModel Logical GLSL450
```

SPIRV-Cross supports all SPIR-V versions, but the semantics in SPIR-V 1.4 and up changed.

**Comment by HansKristian-Work** [comment]
I guess the problem is that spirv-as targets 1.5 by default, unless overridden with --target-env.
