### ISSUE TITLE
[HLSL] ternary operator generates invalid mix() function call

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#172]
The following line of code:

```vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);```

Generates the following function call in HLSL (sm5):

```float2 i1 = mix(float2(0.0f, 1.0f), float2(1.0f, 0.0f), bool2(_85, _85));```

Which the hlsl compiler complains about with: error X3004: undeclared identifier 'mix', when compiled with:

```
>C:\Program Files (x86)\Windows Kits\10\bin\x86\fxc.exe /T ps_5_0 /Fh shaders_offscreenFS.hlsl.h /Vn offscreenFS_fs_hlsl5 /Gec /O3 shaders_offscreenFS.hlsl
```
Turning the ternary operator into a simple if() makes it work.

Attached is a ZIP with the input GLSL file, the SPIRV-file, and the generated code for various GLSL versions, the faulty HLSL version, and Metal (the code for GLSL and Metal looks different).

[shaders_offscreenFS.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/974061/shaders_offscreenFS.zip)

**Comment by HansKristian-ARM** [comment]
This looks like the GLSL path for boolean mix with OpSelect. HLSL path should use the "simpler" paths here for OpSelect.

**Comment by HansKristian-ARM** [comment]
Fixed on master.

**Comment by floooh** [comment]
working great, thanks!
