### ISSUE TITLE
[HLSL] mod() function only implemented for float type

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#173]
Probably a known issue or temporary placeholder: currently the HLSL backend only implements the mod() function for the float datatype, this leads to fxc warnings and incorrect code when called with vector types (warning X3206: 'mod': implicit truncation of vector type).

See here: https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.cpp#L751

**Comment by HansKristian-ARM** [comment]
Hm, can't mod() be replaced with fmod() here? Is there some sneaky incompatibility between the two?
Ping @RobDangerous.

**Comment by floooh** [comment]
Yes, unfortunately HLSL's fmod() is different from GLSL's mod() if one of the args is negative. In my old generator I solved this with a macro ```#define mod(x,y) (x-y*floor(x/y))```, since it was a macro it worked automatically for all types.

**Comment by HansKristian-ARM** [comment]
Welp, that's annoying. Guess we'll have to stamp out all the variants. Wonder how glslang HLSL implements fmod() in that case.

**Comment by RobDangerous** [comment]
Will get to the stamping then (after more texturing stuff and having a really close look at the matrix situation).
