### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/SPIRV-Cross#1730]
Versions of MoltenVK >= 1.1.2 can't be built with latest spirv-cross release, since they depend on some "random" commit after latest tag.
It's quite hard to create proper packages for package managers.

**Comment by billhollings** [comment]
> they depend on some "random" commit after latest tag

Can you expand on what you mean by this? What is "they"? And what do you mean by "random"?

You can change the commit version of SPIRV-Cross that MoltenVK builds with via one of the following two techniques:

- Update the contents of the MoltenVK `ExternalRevisions/SPIRV-Cross_repo_revision` file to the SPIRV-Cross commit you wish to use, and rerun the `./fetchDependencies --all` MoltenVK script.

or

- Clone the SPIRV-Cross repo somewhere, checkout the commit or tag you want to use, and run MoltenVK's `fetchDependencies` script as follows:

    `./fetchDependencies --all --spirv-cross-root path-to-SPIRV-Cross-repo`

You can substitute specific platforms in place of `--all` to speed up the build. For more on that, see the documentation in the MoltenVK `README.md` file, or in the `fetchDependencies` script file.

**Comment by SpaceIm** [comment]
I mean that MoltenVK doesn't depend on spirv-cross official releases, but specific commits without tags. MoltenVK 1.1.2 and later can't be built with the latest official release of spirv-cross, I've already tried.
It's tedious for package managers, because they are supposed to package only stable releases. They can't package every single commit.

**Comment by billhollings** [comment]
>If there is an issue that it would be helpful to specifically tag SPIRV-Cross commits that get set in `ExternalRevisions/SPIRV-Cross_repo_revision` in MoltenVK, that might be something that we can coordinate. For example...something like a `MoltenVK-v.v.v` tag within SPIRV-Cross when we do a MoltenVK release, which, in turn, is tied to a Vulkan SDK release.

I've created a [SPIRV-Cross tag](https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/MoltenVK-1.1.5) for the version of SPIRV-Cross used in the [Molten-1.1.5 release](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.5).
