### ISSUE TITLE
[HLSL] what to do about gl_PointSize in HLSL

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#174]
Apologies for ticket spam, I think this is the last remaining issue for my engine's core samples :)

Currently, using gl_PointSize throws an "Unsupported builtin in HLSL" error (https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.cpp#L274), which is sort of understandable since D3D11 doesn't have point sprite support.

I wonder though if it isn't better to generate a dummy output variable instead (that's what I did in my old shader code generator) and convert the hard error into a soft warning? That way the code would compile even though the point-size output would be ignored in D3D11.

**Comment by HansKristian-ARM** [comment]
It sounds more reliable to not use gl_PointSize in the shader at all in that case? This should turn into a point of size 1 in GLSL which I assume is what HLSL supports?

The easy workaround is to not emit a semantic for PointSize, certainly, but I prefer something more explicit than warnings which can easily be ignored, and someone might want a more stricter operation.

A compromise might be to add a "compat" option for PointSize where this semantic is simply ignored.

**Comment by floooh** [comment]
Ideally I'd like to be able to use point-size for the generated GLSL and Metal sources, so that I can use the point-sprite feature there even if the feature isn't supported on D3D11 (it would render as 1-pixel-sized points there).

An option in the HLSL generator would be nice. A vertex shader which has a gl_PointSize output could simply have a gl_PointSize output in HLSL without any semantic (so the shader would compile, but it would be a 'throw-away' output (this is btw what the Metal source generator currently does, see #169, even though Metal supports a point_size semantic).

**Comment by HansKristian-ARM** [comment]
Ok, I think I can add an option for a "compat" mode, where you opt into ignoring PointSize in HLSL.

**Comment by HansKristian-ARM** [comment]
Fixed on master.

**Comment by floooh** [comment]
...and this is also working great. Thanks!
