### ISSUE TITLE
Handling resources that are defined in both vertex and fragment shader

### ISSUE THREAD

**Issue by Desperado17** [KhronosGroup/SPIRV-Cross#1740]
Greetings,

can someone tell me how I can handle an UBO / interface block that is defined in both vertex and fragment shader? Currently I have a separate compiler object for both, is there a unified list somewhere where I can retrieve these resources or do I have to do this manually, as in "get all the bindings, then manually check for duplicates between vertex and fragment shader".

?

**Comment by HansKristian-Work** [comment]
Reflect separately and merge the duplicates, yes.
