### ISSUE TITLE
Column major matrix layout support in HLSL

### ISSUE THREAD

**Issue by antaalt** [KhronosGroup/SPIRV-Cross#1742]
I wanted to use SPIRV-Cross to convert GLSL to HLSL for a custom engine im working on. For ease of development, I decided to use a single matrix layout (column major for both API (OpenGL & D3D11)), but it seems SPIRV-Cross automatically convert GLSL column major layout to row major layout for HLSL because of convention. There should be a way to pass a setting or anything to SPIRV-Cross API to make it write colum major matrix in HLSL. This would also mean to not flip the matrix operands order and maybe some other parameters.

**Comment by HansKristian-Work** [comment]
This is a misconception. SPIRV-Cross is forced to flip the row/column major and flip all multiplication orders because HLSL addressing is row-major and not column major, so if you see row-major in the shader, it's actually column-major.

**Comment by antaalt** [comment]
Yes but the layout of the matrix still need to be transposed on CPU side. And as HLSL is agnostic, it should be possible to pass it column major matrix without having to transpose every matrix before sending them to the shader (when using column major library such as glm), but this require to keep the same multiplication order as in GLSL.

**Comment by HansKristian-Work** [comment]
It doesn't need to be transposed on CPU side, that's the point.

**Comment by antaalt** [comment]
Oh I see, I got it to work, sorry for the trouble !
