### ISSUE TITLE
Access to spvc_set data in C API requires C++

### ISSUE THREAD

**Issue by Illithidek** [KhronosGroup/SPIRV-Cross#1750]
So the problem is fundamental.
In C API header(`spirv_cross_c.h`) there are functions which returns `spvc_set` defined in a way:
```
struct spvc_set_s;
typedef const struct spvc_set_s *spvc_set;
```
In the implementation this structure(`spirv_cross_c.cpp`) uses` std::unordered_set` which is C++ feature. 

```
struct spvc_set_s : ScratchMemoryAllocation
 {
       std::unordered_set<VariableID> set;
 };
```
Yet there are functions in C header like a `spvc_compiler_get_active_interface_variables` that returns by pointer `spvc_set`.
And now after getting active interface variables, I would like to get access to that set.
But since it's std::unordered_map I can't get access to it in C.
Is it some misconception in C API design or am I wrong about something?

**Comment by HansKristian-Work** [comment]
The set is not intended to be inspected directly. It is only used for get_active_interface_variables -> set_enabled_interface_variables, and the set is used as an intermediate handle.

**Comment by Illithidek** [comment]
Thanks for answer. In that case just switching from C++ API is confusing.
I will try simply use other functions as you say.
