### ISSUE TITLE
MSL: Error trying to cast spvUnsafeArray<float, 3> to float[3] array

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#1763]
SPIR-V conversion to MSL fails compilation in an attempt to cast `spvUnsafeArray<float, 3>` to `float[3]` array:

These CTS test fail as a result:
```
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_vert
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_tessc
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_tesse
dEQP-VK.spirv_assembly.instruction.graphics.decoration_group.same_decoration_group_on_multiple_types_frag
```
SPIR-V file: 
[bad_cast_from_spvUnsafeArray.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/7305033/bad_cast_from_spvUnsafeArray.spv.zip)

**Comment by cfnptr** [comment]
Decompiled `bad_cast_from_spvUnsafeArray.spv.zip` MSL shader:

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct _14
{
    float _m0[3];
};

struct _15
{
    float _m0[3];
};

constant spvUnsafeArray<float, 3> _93 = spvUnsafeArray<float, 3>({ 1.0, 2.0, 1.0 });
constant spvUnsafeArray<float, 3> _94 = spvUnsafeArray<float, 3>({ -1.0, -2.0, -1.0 });

struct main0_out
{
    float4 m_4 [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float4 m_3 [[attribute(0)]];
    float4 m_5 [[attribute(1)]];
};

static inline __attribute__((always_inline))
float4 _102(float4 _107)
{
    float4 _109 = _107;
    _14 _110 = _14{ spvUnsafeArray<float, 3>({ 1.0, 2.0, 1.0 }) };
    _15 _111 = _15{ spvUnsafeArray<float, 3>({ -1.0, -2.0, -1.0 }) };
    _109.y = (_110._m0[2] + _111._m0[2]) + _109.y;
    return _109;
}

vertex main0_out main0(main0_in in [[stage_in]])
{
    main0_out out = {};
    out.gl_Position = in.m_3;
    out.m_4 = _102(in.m_5);
    return out;
}
```

We can initialise structures this way:

```
_14 _110 = _14{ spvUnsafeArray<float, 3>({ 1.0, 2.0, 1.0 })[0], spvUnsafeArray<float, 3>({ 1.0, 2.0, 1.0 })[1], spvUnsafeArray<float, 3>({ 1.0, 2.0, 1.0 })[2] };
```

Hacky but I think should be not hard to implement, and this way shader compiles.

**Comment by etra0** [comment]
imho it would be more idiomatic to check if the struct has only one member and if it's an array, in cases where that's true declare a constructor from `spvUnsafeArray<T, N>`. Creating an assigning loop should be possible because we know N at compile time.

@HansKristian-Work thoughts?

**Comment by billhollings** [comment]
>declare a constructor from `spvUnsafeArray<T, N>`

Intersting idea.

Do we do this anywhere else already for MSL structs? As far as I know, we treat them all as PODS.

**Comment by etra0** [comment]
correct me if I'm wrong, but in C/C++ you can initiate structs as 'array' using array-initialization only if it's written directly, not through variables, and when you have different types you don't have an implicit copy constructor.
i.e.
```c++
// direct array initialization, which is valid
spvUnsafeArray<float, 3> a {1., 2., 3.};

// this is valid because of an implicit copy constructor
spvUnsafeArray<float, 3> b { a };


// this is invalid because we don't have a constructor that accepts array
spvUnsafeArray<float, 3> b { a.elements };

// spvUnsafeArray is built no problems but we have no constructor
// for _14 that accepts spvUnsafeArray
_14 _110 = _14 { spvUnsafeArray {1., 2., 3. } };
```

maybe relevant: https://en.cppreference.com/w/cpp/language/initialization

**Comment by etra0** [comment]
Hmm, upon further investigation, the structs are emitted as plain `float`s because of this condition:
https://github.com/KhronosGroup/SPIRV-Cross/blob/53d94a982e1d654515b44db5391de37f85489204/spirv_msl.cpp#L10619-L10620

In the attached .spv it does the following:
```spvasm
               (...)
               OpDecorate %10 Offset 0
          %9 = OpDecorationGroup
         %10 = OpDecorationGroup
               OpDecorate %11 RelaxedPrecision
               OpDecorate %12 RelaxedPrecision
               OpDecorate %12 Flat
               OpDecorate %12 Restrict
         %13 = OpDecorationGroup
         %11 = OpDecorationGroup
         %12 = OpDecorationGroup
               OpGroupMemberDecorate %10 %_struct_14 0 %_struct_15 0
              (...)
```
Which from my understanding sets the decoration `Offset` to the first members of the structs `_14` and `_15`.
From what I can read from the SPIR-V spec, adding the `Offset 0` decoration to a struct with only one member is redundant? so it could be ignored in this *specific* case, but the type conversion would *still* be an issue I'm unsure how to handle.

In my inexperience I can think of two solutions, one is to write a constructor that takes `spvUnsafeArray` to those structs, or relay in list-initialization for constants, i.e. hacking something around here

https://github.com/KhronosGroup/SPIRV-Cross/blob/53d94a982e1d654515b44db5391de37f85489204/spirv_glsl.cpp#L5002-L5007

where removing the type to glsl constructor kinda works.

Any tips or guidance is really appreciated :-)
