### ISSUE TITLE
MSL & GLSL: Clamp vector element access to vector size

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#1784]
SPIR-V conversion to MSL fails Metal compilation when shader accesses vector element outside vector size.

The following SPIR-V code accesses a vector element outside the size of the vector:
```
      OpName %9 "v"
 %6 = OpTypeFloat 32
 %7 = OpTypeVector %6 3
 %8 = OpTypePointer Function %7
 %9 = OpVariable %8 Function
%10 = OpTypeInt 32 1
%26 = OpConstant %10 3
...
%48 = OpAccessChain %47 %9 %26
      OpStore %48 %46
```

The resulting MSL code is:
```
v.w = _43._GLF_uniform_float_values[0];
```

which is attempting to set the a vector value at index `3` (`.w`), even the vector only has 3 components (`float3`).

This is similar to #1778, but generalized to treat swizzle access outside size of vector as undefined behavior. Clamp swizzle to allow compilation, but invoke undefined behavior at runtime.

One possible solution is to pass the vector size to `CompilerGLSL::index_to_swizzle()` and clamp the returned value to the vector size (which would also fix what #1778 fixed. However, this wouldn't handle indexed element access using a constant value (`v[3]`). So perhaps an alternative that would solve both would be to clamp the size of any constant access to a vector component to the vector size, before using either `[n]` or `index_to_swizzle()`.

These CTS test fail as a result:
```
dEQP-VK.graphicsfuzz.cov-vector-illegal-index-never-executed
```

SPIR-V files:
[out-of-vector-bounds.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/7392841/out-of-vector-bounds.spv.zip)

**Comment by etra0** [comment]
The CTS was a bit more complex than just checking the out of bound access so here's a minimal repro: [out-of-bounds.spv.gz](https://github.com/KhronosGroup/SPIRV-Cross/files/7513816/out-of-bounds.spv.gz)

**Comment by HansKristian-Work** [comment]
This can probably be closed now?

**Comment by etra0** [comment]
I can confirm master pass the CTS test in MoltenVK.
