### ISSUE TITLE
Unsized array reflection

### ISSUE THREAD

**Issue by Lumengine** [KhronosGroup/SPIRV-Cross#1788]
Hi,

I just want to know if you support unsized array of resources. If I have something like
` layout(set = 1, binding = 0) uniform sampler2D Textures[];
`
can I know that the resource is unsized ? If yes, what should I use ?

Thanks !

**Comment by HansKristian-Work** [comment]
Assuming issue is resolved.

**Comment by Lumengine** [comment]
Oh yes sorry, I forgot to resolve the issue and it worked fine ! Thx :)
