### ISSUE TITLE
[GLSL v100 + WebGL] accessing uniform arrays in vertex shader fails

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#180]
I've hit an interesting problem with WebGL when accessing uniform arrays in the vertex shader. 

I'm actually not sure whether the problem is in the WebGL implementations of browsers, since I think the WebGL spec is clear, accessing arrays in vertex shaders should *not* require "constant-index-expessions" (see Appendix 5: https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf).

Here's the problem, first an example which works (this is how I used to do it in my old shader-code-generator):

```glsl
// a vec4 array as 'direct' uniform
uniform vec4 color_table[32];
// the vertex shader
void main() {
...
    // access the array with a computed index
    int color_index = int(mod(facedata.z, 32.0));
    vec4 color = color_table[color_index];
...
}
```
This compiles fine in WebGL. However SPIRV-Cross creates a struct from uniform blocks:

```glsl
struct vsParams {
    vec4 color_table[32];
};
uniform vsParams _44;

void main() {
...
    int color_index = int(mod(facedata.z, 32.0));
    vec4 color = _44.color_table[color_index];
...
}
```
In WebGL, this produces an error ```Index expression must be constant```.

Is it possible to add an option to the GLSL generator to not wrap uniform blocks into structs, but instead "unpack" their members into unique uniforms? If it isn't too complicated I can try to implement this and provide a pull request (I guess support for WebGL isn't very high on the list for anybody else)?

Even though this might be a problem in WebGL implementations I'd rather have a workaround in the shader code generation instead of waiting for browsers to be fixed, especially since this isn't a problem anymore in WebGL2 :)

**Comment by HansKristian-ARM** [comment]
Yes, there is support for this. Have a look at flatten_buffer_block (--flatten-ubo in CLI).
Any UBO or push constant block can be flattened to an array of vec4 values.

**Comment by floooh** [comment]
Ah, now I get it :) I tried this out earlier but since this flattening destroys all type information (eg. matrices etc) I didn't consider it further. But together with the reflection information I'm writing out this should give me enough data for arranging the uniform data the right way on the CPU side (in fact it's even much better then before since I only need a single glUniform4fv() call to update all uniforms even on WebGL/GLES2).

Thanks!
