### ISSUE TITLE
GLSL < 420 not really supported?

### ISSUE THREAD

**Issue by slembcke** [KhronosGroup/SPIRV-Cross#181]
Was looking into using glslang + spirv-cross to cross compile various shader languages. My main GL target is 330, but spirv-cross doesn't really seem to support it. For example, my output ends up being:

```
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
```

It seems to only do this so that it can use layout(location = ...) on the shader output. While I'm sure the SPIRV contains such layout qualifiers, they aren't really needed. It does a perfectly good job of naming the outputs like I expect, and I have no problem binding the outputs in the C code.

Seems like these are the lines responsible, but I don't quite get how.
https://github.com/KhronosGroup/SPIRV-Cross/blob/95d4cbcd8c41fe5accf82c451395cc6283e1188e/spirv_glsl.cpp#L480

**Comment by HansKristian-ARM** [comment]
All GLSL variants are supported, but there might be some fixup-code needed to make shaders compatible for older targets.

You can use Compiler::unset_decoration() to remove any layout(location = ...) statements from the code when it is compiled to GLSL, so it can be compatible with 330 and older.

The reason for the 420pack is to be able to support layout(binding) on UBOs on older targets mostly without too much fuss, and 420pack is a widely supported extension. Is there a problem with this extension being conditionally enabled like this?

**Comment by slembcke** [comment]
I guess I haven't actually tried loading one of the shaders, but since they don't validate with glslangValidator, I was assuming they won't. It's not really conditionally enabling the extension if the shader won't compile without it no?

As for widely supported, feel free to sigh profusely, but OS X doesn't support it. :-\ Neither does my really low end Linux netbook (HD 5xx or somesuch?), though supporting that hardware is more of a novelty.

I'm already highly considering a Metal backend for the renderer since it would probably take less lines of C code to support than the sum of my shader code. Looks like Bill H is working on Metal SL output. :D I'm also looking into XShaderCompiler which looks similarly promising.

All of these shader cross-compilation tools look amazing lately. Thanks to all involved!

**Comment by HansKristian-ARM** [comment]
Could you paste the shader which is not validating with 330?

**Comment by floooh** [comment]
FYI, I'm using "#version 330" for my input shaders to glsangValidator, but they're admittedly not very complex :)

**Comment by slembcke** [comment]
Ok, sorry to leave this hanging for a while. My day job is a console game project in some mild crunch. Not a lot of free time to play with fun tools. :-\

Anyway, it looks like the problem is specifically that I'm cross compiling from HLSL, which means I need to turn on "vulkan semantics". Seems the only thing it does to my shaders is to add those layout decorations which aren't 330 compatible. Is there any way to disable the decorations on the command line, or do I need to do it by embedding the library?

So specifically, I've been using templated GLSL code to add features like includes and whatnot (actually more or less like @floooh does in Oryol). My thought was to see if shader cross compiling tools were mature enough yet to just write them in a language that has such features (HLSL) instead of trying to invent a better GLSL.

**Comment by HansKristian-ARM** [comment]
There is no way to drop the layouts from the command line, no. You will need to use the API for that currently.

**Comment by slembcke** [comment]
Ok. Thanks. I'll give embedding the library a go.
