### ISSUE TITLE
Why "Identifiers beginning with underscores or identifiers which contain double underscores" are reserved by spirv-cross

### ISSUE THREAD

**Issue by MioMioReimu** [KhronosGroup/SPIRV-Cross#1814]
We have some auto generated HLSL shader, it has some "albedo__0" texture name. after coversion, it will be "albedo_0".

can we remove this rule in my private branch?

see
```
// spirv_cross.hpp
// Overrides the identifier OpName of an ID.
// Identifiers beginning with underscores or identifiers which contain double underscores
// are reserved by the implementation.
void set_name(uint32_t id, const std::string &name);
```

```
// spirv_cross_parsed_ir.cpp
void ParsedIR::sanitize_underscores(std::string &str)
```

**Comment by HansKristian-Work** [comment]
What do you mean "can we remove this rule"? Double underscores are reserved and fail compilation in many cases. If they don't on your target compiler, by all means, but it won't be upstream.

**Comment by MioMioReimu** [comment]
thanks. 
I found some desc in glsl spec 3.6 pp23.
> In addition, all identifiers containing two consecutive underscores ( __ ) are reserved for use by underlying software layers. Defining such a name in a shader does not itself result in an error, but may result in unintended behaviors that stem from having multiple definitions of the same name.
