### ISSUE TITLE
[Metal] size of vec3 in uniform blocks is 12, should be 16?

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#182]
[edit: added link to MSL spec]

I have rewritten my reflection information to use the member offsets reported by the ```type_struct_member_offset()``` method, to generate C structs from this information for the CPU side.

This seems to work well for GLSL, but I stumbled over a case in Metal which gives me trouble:

If a float follows a vec3, it looks like the float is directly appended to the vec3 (after 12 bytes), instead of adding 4 bytes padding, for instance:

```
// GLSL:
uniform fsParams {
    vec2 shadowMapSize;
    vec3 lightDir;
    vec3 eyePos;
    float specIntensity;
};

// reported offsets:
// shadorMapSize: 0
// lightDir: 16
// eyePos: 32
// specIntensity: 44 (should be 32+16 = 48?)

// generated C struct:
struct fsParams {
    glm::vec2 shadowMapSize;
    uint8_t _pad_8[8];
    glm::vec3 lightDir;
    uint8_t _pad_28[4];
    glm::vec3 eyePos;
    float specIntensity;
};
```
With this C struct, Metal does indeed not pickup the specIntensity.

The Metal shading language spec says that both alignment and size are 16 bytes for a vec3 (see "2.8 Alignment of Types"): https://developer.apple.com/metal/metal-shading-language-specification.pdf

Is this a bug or am I missing something? :)

PS: I also tried to be clever and flatten all the uniform buffers to vec4 arrays (like I'm doing now in GLSL, which is working great btw), but this generates invalid Metal code (the feature is probably not supported for the Metal backend).

Halp.

**Comment by HansKristian-ARM** [comment]
MSL should emit the packed_vec3 type here for vec3 + float case. Paging @billhollings.

**Comment by HansKristian-ARM** [comment]
Well, MSL does emit
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct UBO
{
    float2 a;
    float3 light_dir;
    packed_float3 eye_pos;
    float spec;
};

struct main0_out
{
    float FragColor [[color(0)]];
};

fragment main0_out main0(constant UBO& _13 [[buffer(0)]])
{
    main0_out out = {};
    out.FragColor = _13.spec;
    return out;
}
```
So it looks correct to me. Are you sure glm::vec3 is the right size?

**Comment by floooh** [comment]
Hmm, that packed_float3 is not there in my case:

```
struct fsParams
{
    float2 shadowMapSize;
    float3 lightDir;
    float3 eyePos;
    float specIntensity;
};
```
...for the following GLSL uniform block:
```
uniform fsParams {
    vec2 shadowMapSize;
    vec3 lightDir;
    vec3 eyePos;
    float specIntensity;
};
```
buuuuut... I'm seeing there's a pad_and_pack_uniform_structs option which is set to false as default... I'll see what happens when I'm setting this to true...

**Comment by HansKristian-ARM** [comment]
Ah, I see ... It's true by default in the CLI, but not in the API, that should be fixed.

**Comment by floooh** [comment]
Ok that works :) I wonder if the option makes sense though... since if it is not set, the type_struct_member_offset() method returns bogus information...

**Comment by HansKristian-ARM** [comment]
Agreed, default behavior should be correctness, but I'm not sure where we would want the packing to be different from the SPIR-V ...
@billhollings, is there a need for supporting non-packed/padded structs?

**Comment by billhollings** [comment]
I've removed the pad_and_pack_uniform_structs option. Non-stage structs are always packed now.

Oops...since PR #186 is still pending...my push for this got automatically added to it...instead of being added as a separate PR.
