### ISSUE TITLE
HLSL: packoffset is produced for SM3.0 but fxc does not honor it

### ISSUE THREAD

**Issue by skhrshin** [KhronosGroup/SPIRV-Cross#1827]
Hi, I'm still developing Direct3D 9 application in order to make my program run on old PCs. I'm trying to port my shader written for Vulkan to SM3.0, and facing a problem where constants are not packed as the code produced by spirv-cross is saying like `packoffset(c0.z)`. This is because fxc ignores `packoffset` if the shader profile is SM3.0, so it's not a bug. But I think it would be nicer if spirv-cross had an option to combine multiple constants into one and make the constant layout identical to as if `packoffset` is applied. Here's example:

The source code

```hlsl
struct MyShaderParams {
    float2 alpha;
    float beta;
};
[[vk::push_constant]]
MyShaderParams params;
float4 main() : SV_Position {
    return float4(params.alpha, params.beta, 1.0);
}
```

passing to dxc and spirv-cross, we get

```hlsl
cbuffer type_PushConstant_MyShaderParams
{
    float2 params_alpha : packoffset(c0);
    float params_beta : packoffset(c0.z);
};

uniform float4 gl_HalfPixel;

static float4 gl_Position;
struct SPIRV_Cross_Output
{
    float4 gl_Position : POSITION;
};

void vert_main()
{
    gl_Position = float4(params_alpha, params_beta, 1.0f);
    gl_Position.x = gl_Position.x - gl_HalfPixel.x * gl_Position.w;
    gl_Position.y = gl_Position.y + gl_HalfPixel.y * gl_Position.w;
}

SPIRV_Cross_Output main()
{
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    return stage_output;
}
```
It says `float params_beta : packoffset(c0.z);` but fxc ignores `packoffset`, so it's assigned to c1 actually.

In my idea, `params_alpha` and `params_beta` will be combined into one member variable. The output will be like below:

```hlsl
cbuffer type_PushConstant_MyShaderParams
{
    float3 params_alpha_and_params_beta;
};

uniform float4 gl_HalfPixel;

static float4 gl_Position;
struct SPIRV_Cross_Output
{
    float4 gl_Position : POSITION;
};

void vert_main()
{
    gl_Position = float4(params_alpha_and_params_beta.xy, params_alpha_and_params_beta.z, 1.0f);
    gl_Position.x = gl_Position.x - gl_HalfPixel.x * gl_Position.w;
    gl_Position.y = gl_Position.y + gl_HalfPixel.y * gl_Position.w;
}

SPIRV_Cross_Output main()
{
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    return stage_output;
}
```

Is there anyone else interested in?

**Comment by HansKristian-Work** [comment]
What? Sigh ... You'd be better off trying to use the "flattened UBO" system for this purpose. Then everything is lowered to float4[].

**Comment by skhrshin** [comment]
Thank you for replying. I didn't know --flatten-ubo option. So I tried it, and thought "Yes, this is what I want for HLSL!".
```
#version 450

uniform vec4 type_PushConstant_MyShaderParams[1];
void main()
{
    gl_Position = vec4(type_PushConstant_MyShaderParams[0].xy, type_PushConstant_MyShaderParams[0].z, 1.0);
}
```

Then I tried to convert the generated GLSL code to SPIR-V again so that I could get the desired SM3.0 HLSL code finally, but this scheme didn't work because glslangValidator rejected the generated GLSL code with saying:
```
ERROR: tmp/test.vert.glsl:3: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan
```

**Comment by HansKristian-Work** [comment]
No, you'd need the HLSL backend to support --flatten-ubo as well. That is currently not supported, but it should be theoretically possible.

**Comment by skhrshin** [comment]
I tried adding the following code at the beginning of `CompilerHLSL::emit_push_constant_block`:
```
	if (flattened_buffer_blocks.count(var.self))
	{
		emit_buffer_block_flattened(var);
	}
````

and this looked working as expected to me. But I'm not sure if it's much enough to do. If it was OK, I would correct the help message (to note that --flatten-ubo is no longer only for GLSL) and create a PR. Is there anything wrong?

**Comment by skhrshin** [comment]
Oops, `else` was also added before the next if statement.

**Comment by skhrshin** [comment]
I'm facing a problem where assignment to structure like
```
        light.Position = _21_lights[i].Position;
        light.Radius = _21_lights[i].Radius;
        light.Color = _21_lights[i].Color;
```
turns into an invalid constructor-like syntax by appending `--flatten-ubo` option.
```
        Light _52 = Light(UBO[i * 2 + 4].xyz, UBO[i * 2 + 4].w, UBO[i * 2 + 5]);
        light.Position = _52.Position;
        light.Radius = _52.Radius;
        light.Color = _52.Color;
```
This is reproducible with the test shader at shaders/flatten/copy.flatten.vert.

I would appreciate if some hints were given.

**Comment by skhrshin** [comment]
I found that `CompilerHLSL::access_chain` falled back to `CompilerGLSL::access_chain` and `CompilerGLSL::access_chain` called `CompilerGLSL::flattened_access_chain` and then that function generated the code which is invalid as HLSL. Maybe `CompilerHLSL::access_chain` must handle this case.
