### ISSUE TITLE
[Question] Removing declaration of uniform buffers

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#183]
I'm compiling some shaders that end up having too many constant buffers declared. This isn't an issue on PC as the hardware seems to strip them out, but is an issue on the Mac, where glGetActiveUniformBlock reports buffers as being used when in reality they're just declared.

With SPIRV-Cross, I can know which of these constant buffers are used via get_shader_resources(get_active_interface_variables()), but I can't seem to find a way to remove the declaration of the unused constant buffers entirely from the resulting glsl. I was kind of hoping plugging in the current SPIRV-opt into the SPIR-V would help the Mac, but it doesn't work. Any suggestions? Is there any part of the SPIRVCross API I can use to do this?

EDIT: I'm already using set_enabled_interface_variables(get_active_interface_variables())

**Comment by HansKristian-ARM** [comment]
Hm. This works fine for me in the CLI. Test:
```
#version 450

layout(std140) uniform UBO
{
	vec4 a;
};

layout(std140) uniform UBO2
{
	vec4 b;
};

layout(location = 0) out vec4 FragColor;

void main()
{
	FragColor = a;
}
```

With --remove-unused-variables (which uses set_enabled_interface_variables) I get:
```
#version 450

layout(std140) uniform UBO
{
    vec4 a;
} _12;

layout(location = 0) out vec4 FragColor;

void main()
{
    FragColor = _12.a;
}
```

without I get:
```
#version 450

layout(std140) uniform UBO
{
    vec4 a;
} _12;

layout(std140) uniform UBO2
{
    vec4 b;
} _20;

layout(location = 0) out vec4 FragColor;

void main()
{
    FragColor = _12.a;
}
```

**Comment by redorav** [comment]
Sorry, my bad... I was looking at the SPIR-V instead of the glsl and pulling my hair out. It's down to the lack of a proper SPIR-V optimizer then I guess (the fact that these groups appear). I'll close the question, sorry for wasting your time :)
