### ISSUE TITLE
2D arrays in SPIR-V get translated as 2D arrays in glsl

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#184]
Hi,

I have an hlsl shader that uses 2D arrays. It translates correctly into SPIR-V (using the 2D array) but the resulting glsl uses a 2D array as well which is not allowed in the language if my understanding is correct.

The Cg compiler we used to use would flatten the array so there's really no runtime cost to it. How hard/easy would it be to fix this?

**Comment by HansKristian-ARM** [comment]
By 2D array, I assume you mean sampler2DArray? This is supported in GLSL just fine, but maybe not in ESSL 1.0, but there should be an extension for that.

**Comment by redorav** [comment]
Sorry if I wasn't clear, I mean actual 2D arrays like say

```
float values[4][4];
// Do something with values by accessing as values[i][j]
```

**Comment by HansKristian-ARM** [comment]
Oh, so you mean arrays of arrays? And Cg would flatten that into a single array dimension?

**Comment by redorav** [comment]
That's right yes

**Comment by HansKristian-ARM** [comment]
Before considering implementing array flattening I would need to know:
- Are you targeting GLSL 4.3 already.
- If not, would enabling the arrays_of_arrays extension be enough to support it.

**Comment by redorav** [comment]
We use OpenGL as a target for the Mac while we don't have a Metal implementation, which will remain so for the foreseeable two or three years as Apple slowly phases out GL on the Macs. The issue is that Macs don't implement OpenGL higher than 4.1 and don't implement this extension either. https://developer.apple.com/opengl/capabilities/ It also doesn't seem like Apple is going to do anything about it in the future either.

**Comment by HansKristian-ARM** [comment]
Ok, seems reasonable then. It will get funky if arrays are just flattened behind the scenes depending on the version, so I assume you will need to explicitly call "flatten_multidimensional_array" or something like that in the API once it gets there.

**Comment by redorav** [comment]
Maybe it could automatically detect if not version 4.3 and you've not required the arrays_of_arrays extension, then flatten? I'd also be fine with it being more explicit but it isn't immediately obvious otherwise that it can produce incorrect shaders if those two conditions aren't present (maybe there are other conditions, I wasn't aware that modern GL allowed arrays of arrays).

**Comment by HansKristian-ARM** [comment]
That kind of behavior would only make sense if the user knows the differences between 4.2 and 4.3, which is a very subtle (unlike say, legacy vs. modern GLSL, that one is very well known). Flattening the array changes the interface of the shader quite a lot, and I would prefer that is opt-in.

Similar rationale for flattening UBOs and combining image and samplers. The modification to the shader is too big to do silently.

**Comment by redorav** [comment]
I understand your point, though I could argue whether producing shaders that won't compile is the right alternative. Maybe if SPIRVCross has a warning mechanism it can inform the user of his options? In any case, I'm fine with the proposed solution.

**Comment by HansKristian-ARM** [comment]
Emitting a shader < 430 with the extension is still "valid" shader code, it might just not be supported by a driver. This kind of feature can be considered a compatibility workaround if anything.

**Comment by redorav** [comment]
Sorry I hit the wrong button, I'm fine with it then. Thanks for the support :)

**Comment by HansKristian-ARM** [comment]
PR here: https://github.com/KhronosGroup/SPIRV-Cross/pull/189
Please test it and see if it solves your issues.

**Comment by HansKristian-ARM** [comment]
@redorav, any feedback? If not, I will merge as is.

**Comment by HansKristian-ARM** [comment]
Merged. Feel free to reopen if there are issues or missing functionality.
