### ISSUE TITLE
How to get gles's plain uniforms offset?

### ISSUE THREAD

**Issue by LuciferSweety** [KhronosGroup/SPIRV-Cross#1841]
Hi, I want to get plain uniform offset or uniform buffer size in gles3. 
on "options.emit_uniform_buffer_as_plain_uniforms".
But CompilerReflection emit the uniform buffer like UBO.
eg : float[2]  
The size is 32 in the UBO;
The size is 8 in the plain uniform; 
How to emit it?  Thanks.
![1974a163b791cedf5ea97ba3c652528759004593](https://user-images.githubusercontent.com/18320190/148688820-31f29786-2c72-41dc-9e41-980f2dfc2e46.png)
![f81ca0c008a5974681b40f1a96bc8da118c59e97](https://user-images.githubusercontent.com/18320190/148688822-8d8c7819-7fea-4389-941b-9883e62aa373.png)

**Comment by HansKristian-Work** [comment]
With plain uniforms, the size of a uniform object is purely logical, so not sure if we can meaningfully return anything here.
