### ISSUE TITLE
MSL : Incorrect code generation - struct assignment

### ISSUE THREAD

**Issue by jbright282** [KhronosGroup/SPIRV-Cross#1844]
[spvc-bug.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/7867180/spvc-bug.zip)

Hi - have reduced case down to a small shader.

When DXC compiles spirv with -O0,  spirv-cross generates valid MSL.
When compiles -O3, spriv-cross generates invalid MSL.

src.hlsl : shader
compile.bat : cmdline used.

spirv_good.out -> msl_good.txt : no DXC optimization.
spirv_bad.out -> msl_bad.txt : DXC -O3

Thx!

**Comment by HansKristian-Work** [comment]
The spvUnsafeArray is going to haunt me until end of time ... ._.
