### ISSUE TITLE
Compute workgroup size from c wrapper api?

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/SPIRV-Cross#1853]
Is it possible to retrieve compute shader entry point workgroup size using the c wrapper api?

**Comment by HansKristian-Work** [comment]
`spvc_compiler_get_execution_mode_argument_by_index(compiler, SpvExecutionModeWorkgroupSize, 0/1/2);` is probably what you want.

**Comment by Onhi** [comment]
Thank you!
