### ISSUE TITLE
MSL - exceeding compilation loops

### ISSUE THREAD

**Issue by jbright282** [KhronosGroup/SPIRV-Cross#1854]
Hi -- updating spirv-cross from 2021-10-14 (e4243b8) to head, and now have some shaders (msl) failing at:

```
	if (iteration_count >= 3 && !is_force_recompile_forward_progress)
		SPIRV_CROSS_THROW("Over 3 compilation loops detected and no forward progress was made. Must be a bug!");
```
Picking an arbitrary higher value (20) succeeds.
Would there be any appetite to change this limit to a compile define? I would like to avoid a divergence.

I will investigate the shaders further -- the are quite large and may not be possible to reduce to a simple test case.

**Comment by HansKristian-Work** [comment]
Large test cases are fine. It is probably a case where more forward progress cases need to be marked. Odd that they used to work though.
