### ISSUE TITLE
GLSL: Anonymous structs in uniform blocks have unstable name assignments and cause stage linkage errors

### ISSUE THREAD

**Issue by Dredhog** [KhronosGroup/SPIRV-Cross#1889]
We've hit an issue where generated vertex/fragment shaders fail to link on certain drivers when UBOs have anonymous structs in them as SPIRV-Cross can generate different anon. type names depending on the order/presence of other UBOs in a stage.

Here's an example HLSL shader that will cause the names to change depending which UBOs are used from the entry point:
```
cbuffer MyCBufferA {
    struct
    {
        float myFloatA;
    } structInstanceA;
}

cbuffer MyCBufferB {
    struct
    {
        float myFloatB;
    } structInstanceB[10];
}

struct {
    float memberA;
} myGlobalA;

struct {
    float memberB;
} myGlobalB;

float4 PSMain() : SV_TARGET
{
    float result = 0;
    //result += structInstanceA.myFloatA;    //Uncomment to see generated names for anonymous struct types change
    result += structInstanceB[3].myFloatB;
    result += myGlobalA.memberA;

	return result;
}
```
SPIRV-Cross generates the following essl (see [shader playground](https://shader-playground.timjones.io/20fed1fc9c60c19835d108a142c62317)):

```
#version 300 es
precision mediump float;
precision highp int;

struct _4
{
    highp float myFloatB;
};

struct _7
{
    highp float memberA;
};

struct _8
{
    highp float memberB;
};

layout(std140) uniform type_MyCBufferB
{
    _4 structInstanceB[10];
} MyCBufferB;

layout(std140) uniform type_Globals
{
    _7 myGlobalA;
    _8 myGlobalB;
} _Globals;

layout(location = 0) out highp vec4 out_var_SV_TARGET;

void main()
{
    out_var_SV_TARGET = vec4(MyCBufferB.structInstanceB[3].myFloatB + _Globals.myGlobalA.memberA);
}
```

after uncommenting the marked line in the source HLSL, the SPIRV-Cross codegene will change to the following (see [shader playground](https://shader-playground.timjones.io/7b2f9f195ed61e7d74921cbb9fb7b2a1)):

```
#version 300 es
precision mediump float;
precision highp int;

struct _4
{
    highp float myFloatA;
};

struct _7
{
    highp float myFloatB;
};

struct _10
{
    highp float memberA;
};

struct _11
{
    highp float memberB;
};

layout(std140) uniform type_MyCBufferA
{
    _4 structInstanceA;
} MyCBufferA;

layout(std140) uniform type_MyCBufferB
{
    _7 structInstanceB[10];
} MyCBufferB;

layout(std140) uniform type_Globals
{
    _10 myGlobalA;
    _11 myGlobalB;
} _Globals;

layout(location = 0) out highp vec4 out_var_SV_TARGET;

void main()
{
    out_var_SV_TARGET = vec4((MyCBufferA.structInstanceA.myFloatA + MyCBufferB.structInstanceB[3].myFloatB) + _Globals.myGlobalA.memberA);
}
```

Heres the corresponding SPIR-V:
[spirv_1.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/8223359/spirv_1.txt)
[spirv_2.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/8223353/spirv_2.txt)

It seems that it should be possible to generate stable and unique names for anonymous structs with a pattern like `<ubo_name> + "_anon" + <anon decl num. in the UBO>`  or  `<ubo_member_name> + "_type"`

I'm not sure about all cases but at least for SPIR-V generated from a high level language like `HLSL` I can't think of any cases where a specific anonymous struct could be used in more than one UBO (as it can only be defined in one place), which hopefully sufficiently constrains the problem to be solvable.

**Comment by HansKristian-Work** [comment]
Right, we don't do heroics at the moment to give these struct proper names. We **do** try just that for blocks however, but I didn't think about anonymous sub-structs. I guess we can try to deduce struct type names from members. Shouldn't be too hard, I can look into it.

**Comment by Dredhog** [comment]
Wow, that was fast, thank you! 👍
