### ISSUE TITLE
Segmentation fault when initializing CompilerGLSL object.

### ISSUE THREAD

**Issue by Makogan** [KhronosGroup/SPIRV-Cross#1891]
I am trying to parse some spirv code generated from glsl and it crashes on construction. I am sure the spirv array is correct because I am creating vulkan shader modules using shaderc that compile and run fine.

 This is the smallest program I could make that reproduces the error:
 
 ```

    Compiler compiler;
    CompileOptions options;
    shaderc::SpvCompilationResult compilation_result = compiler.CompileGlslToSpv(
        shader_source, shaderc_shader_kind::shaderc_glsl_vertex_shader, shader_path.c_str(), options);

    std::vector<uint32_t> spirv_shader;
    spirv_shader.assign(compilation_result.cbegin(), compilation_result.cend());

    std::vector<uint32_t> source_copy = spirv_shader;
    spirv_cross::CompilerGLSL glsl(source_copy);
 ```

where `shader_source` is the std string containing the glsl string of the shader. 

 With input:
 ```
 #version 450

layout(location = 0) in vec2 inPosition;
layout(location = 1) in vec3 inColor;

layout(location = 0) out vec3 fragColor;

layout(binding = 0) uniform MatUBO
{
    mat2 transform;
};


void main() {
    gl_Position = vec4(inPosition, 0.5, 1.0);
    fragColor = inColor;
}
```
 
 OS Ubuntu 21.10, compiler clang. The error is a segmentation fault thrown at line: `spirv_common.hpp:86`

**Comment by HansKristian-Work** [comment]
Do you have the actual SPIR-V that fails? Does it reproduce in CLI? My guess is a botched build.

**Comment by Makogan** [comment]
Well the actual SPIRV that fails is the one generated by shaderc. The same glsl file compiled on disk with glslc and then analyzed with spirv-cross doesn't crash (just tested). However, the uint32_t array genrrated by shaderc is consumed by the vulkan API just fine and a triangle is rendered, no validaiton layers are triggered and renderdoc shows things are normal.

i.e. the problem seems to be that whatever binary data shaderc produces, spirv-cross doesn;t like.

**Comment by HansKristian-Work** [comment]
Is there a mismatch in compilers here or something? There is no reason why it should happen to fail parsing something this trivial, and if it's not something that can reproduce in CLI, I doubt it's actually a SPIRV-Cross bug.

Do you have a backtrace with debug symbols?

**Comment by Makogan** [comment]
To try to test that hypothesis I tried simplifying the code further, now I am doing this:

static std::vector<uint32_t> readFile(const std::string& filename)
{
    std::ifstream file(filename, std::ios::ate | std::ios::binary);

    if (!file.is_open()) {
        throw std::runtime_error("failed to open file!");
    }
    size_t fileSize = (size_t) file.tellg();
    std::vector<uint32_t> buffer(fileSize / sizeof(uint32_t));
    file.seekg(0);
    file.read((char*)buffer.data(), fileSize);
    file.close();

    return buffer;
}
/* */
    std::vector<uint32_t> source_copy = readFile("/home/makogan/neverengine_personal/Source/Examples/vert.spv");
    spirv_cross::CompilerGLSL glsl(source_copy);
```

Where `vert.spv` was generated from the prior shader using glslc. The segmentation fault occurs on the same line inside spirv_cross.

**Comment by Makogan** [comment]
[shader.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/8228359/shader.zip)

This contians both the glsl source and the generated spirv binary.

**Comment by Makogan** [comment]
This is the smallest full program I managed to make that reproduces the error on my computer:

```
// tmp.cpp

#include <vector>
#include <cstdint>
#include <iostream>
#include <fstream>

#include "spirv_glsl.hpp"

static std::vector<uint32_t> readFile(const std::string& filename)
{
    std::ifstream file(filename, std::ios::ate | std::ios::binary);

    if (!file.is_open()) {
        throw std::runtime_error("failed to open file!");
    }
    size_t fileSize = (size_t) file.tellg();
    std::vector<uint32_t> buffer(fileSize / sizeof(uint32_t));
    file.seekg(0);
    file.read((char*)buffer.data(), fileSize);
    file.close();

    return buffer;
}

int main()
{
    std::vector<uint32_t> source_copy = readFile("/home/makogan/neverengine_personal/Source/Examples/vert.spv");
    spirv_cross::CompilerGLSL glsl(source_copy);
}
```

Same data s priorly sent.

These are the compilation commands generated by meson:

```
[1/2] clang++ -Itmp.p -I. -I.. -I/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/include -I/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/include/spirv_cross -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++20 -O0 -g -DVULKAN_HPP_NO_EXCEPTIONS -DVULKAN_HPP_TYPESAFE_CONVERSION -D_USE_MATH_DEFINES -DTRACY_ENABLE -ftime-trace -DSPIRV_CROSS_NAMESPACE_OVERRIDE=spirv_cross -MD -MQ tmp.p/tmp.cpp.o -MF tmp.p/tmp.cpp.o.d -o tmp.p/tmp.cpp.o -c ../tmp.cpp
[2/2] clang++  -o tmp tmp.p/tmp.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group -lubsan /home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib/libspirv-cross-glsl.a -lm /usr/bin/../lib/gcc/x86_64-linux-gnu/11/libstdc++.so -Wl,-rpath,/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib /home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib/libspirv-cross-core.a -Wl,--end-group -Wl,-rpath,/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib
```

**Comment by HansKristian-Work** [comment]
Works fine here still. Built with clang++. You're likely building SPIRV-Cross with mismatched compiler options which breaks ABI or something.

**Comment by Makogan** [comment]
I am very confused. I tried simplifying the build process even further, I am compiling in one step by passing all parameters manually, like this:

`clang++ ../tmp.cpp -I/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/include/spirv_cross -Wl,--start-group /home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib/libspirv-cross-glsl.a -Wl,-rpath,/home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib /home/makogan/.conan/data/spirv-cross/cci.20211113/_/_/package/030e582b36d202f731215ad1c699b10f3cd6f67f/lib/libspirv-cross-core.a -Wl,--end-group`

Note that that has only the strict minimum number of parameters needed to compile, the source file, and the paths to my local installation of spirv-cross (which was isntalled through the conan package manager).

I tried 2 different versions installed with conan, they both segfault.

The error does not occure with gcc, i.e. changing clang++ with g++ results in a well behaved program. Maybe it's a bug with the conan package, I will go bug them.

**Comment by Makogan** [comment]
I downloaded this repo's source code, compiled it on my machine using the default cmake configuration, I am linking directly against it:

```
clang++ ../tmp.cpp -I ../SPIRV-Cross/ -Wl,--start-group ../SPIRV-Cross/build/libspirv-cross-glsl.a -Wl,-rpath, ../SPIRV-Cross/build/ ../SPIRV-Cross/build/libspirv-cross-core.a -Wl,--end-group
```

Same code, same input, I still get a segmentation fault :C

Are you on the same ubuntu version as me? are we using the same clang version? I don't think the problem is on my end unless there is something broken with my hardware. I don;t think I can simplify the example further.

**Comment by Makogan** [comment]
Using gdb to step through, the error occurs at this line:

```
0x0000000000483ca3 in spirv_cross::Bitset::set (this=0x60, bit=11) at /home/makogan/neverengine_personal/Source/SPIRV-Cross/spirv_common.hpp:86
86                              lower |= 1ull << bit;
(gdb) p lower
Cannot access memory at address 0x60
```

My suspicion is that this is UB due to the use of references, e.g. `auto &dec`

Each time the `[]` operator is used there is a posibility that the unordeed map meta reallocates memory, invalidating a reference. I would like to suggest appending const in front of every unmutable variable,a nd replacing `[]` with `at()` or `insert()`. I am mildly confident that either a compilation error or an exception would be thrown, revealing the problem.

**Comment by HansKristian-Work** [comment]
unordered_map and friends in C++ do not invalidate iterators or references on inserts, so I don't see how that can be it.

**Comment by Makogan** [comment]
All evidence I have on my end strongly points towards spirv_cross invalidating its memory through a reallocation.

**Comment by Makogan** [comment]
I think I caught it. According to gdb the resize method for the custom vector class does not actually resize:

```
(gdb) l
452     ID& to_id(const TypeID id) { return *new ID(id); }
453     void ParsedIR::set_member_decoration(TypeID id, uint32_t index, Decoration decoration, uint32_t argument)
454     {
455             const size_t mem_size = meta[id].members.size();
456             meta[id].members.resize(max(mem_size, size_t(index) + 1));
457             auto &dec = meta[id].members[index];
458             dec.decoration_flags.set(decoration);
459
460             switch (decoration)
461             {
(gdb) p meta[to_id(id)].members.size()
$5 = 0
```

**Comment by Makogan** [comment]
I will not, this bug is not consistent. On my machine there have been a couple of times that I have compiled and ran and it seems to be mysteriously gone, but it comes back again. 

Since it is likely a form of UB, it is possible on your end you have not been able to reproduce merely because the internal machine state is different and so the UB makes it seem like the library works fine.

**Comment by HansKristian-Work** [comment]
Ok, iterators do actually get invalidated, but not reference and pointers to the data:

> References and pointers to either key or data stored in the container are only invalidated by erasing that element, even when the corresponding iterator is invalidated.

I don't see how this code can cause invalidation. The reference is used after the resize, and a vector resize definitely invalidates things.

**Comment by Makogan** [comment]
This specific snippet is not what left the program in a brittle state, it's where things are going awry. The auto& pattern combined with the [] operator is potentially creating a ddanling reference somewhere, is my hypothesis

i.e. I am not saying this specific snippet is where the UB is spawned, I am trying to narrow it down.

**Comment by HansKristian-Work** [comment]
> on an Ubuntu system on your end

I'm on Arch. Tried with gcc 11.2 and clang 13.0.1 and ubsan does not complain in either scenario. Neither does valgrind.

**Comment by Makogan** [comment]
Hmm I am using clang 11, let me try to update

**Comment by HansKristian-Work** [comment]
```
455             const size_t mem_size = meta[id].members.size();
456             meta[id].members.resize(max(mem_size, size_t(index) + 1));
457             auto &dec = meta[id].members[index];
458             dec.decoration_flags.set(decoration);
```
Are you on master? const size_t mem_size does not exist in my checkout.

**Comment by Makogan** [comment]
Oh my bad, I modified the code in my attempts to figure out what is wrong, that snippet I copied is a mod on my end (this error happens with the pristine library, this was just a small debug tweak).

On the pristine library it still happens on that region.

**Comment by Makogan** [comment]
For what is worth, I have narrow down the problem to the `void Parser::parse()` function. Something in there before the calls to 

```
	for (auto &i : instructions)
		parse(i);
```

Is responsible.

**Comment by HansKristian-Work** [comment]
FWIW, the ParsedIR::set_member_decoration code was pretty goofy on a second look, so made https://github.com/KhronosGroup/SPIRV-Cross/pull/1892. Shouldn't fix anything, just heads up.

**Comment by Makogan** [comment]
I give up, there's too much stuff going on on the parse function and I cannot make a mental model of what;s going on. If it cannot be reproduced on your end then there no hope of fixing this, it will just be easier to make my own parser at this rate.

**Comment by HansKristian-Work** [comment]
My only idea is that the build environment you're using (it doesn't seem like you're using the CMake build at all?) causes subtle ABI issues. Maybe there's a mismatch in compiler version, compiler flags, libc++ ABI versions, etc. Might be worthwhile trying the C API instead which firewalls such issues. Either way, without concrete proof I doubt there is an actual UB bug here. Annoying situation, but not sure what I can even do here.

**Comment by Makogan** [comment]
For the MVE there is no build environment, i am compiling by hand using clang. I mentioned it in a prior post.

I used CMake to setup spirv-cross, compiled it
then compiled the MVE like this:

`clang++ ../tmp.cpp -I ../SPIRV-Cross/ -Wl,--start-group ../SPIRV-Cross/build/libspirv-cross-glsl.a -Wl,-rpath, ../SPIRV-Cross/build/ ../SPIRV-Cross/build/libspirv-cross-core.a -Wl,--end-group`

I mentioned it [here](https://github.com/KhronosGroup/SPIRV-Cross/issues/1891#issuecomment-1065531955).

I tried to make the compilaiton command as simple as possible to prevent ABI issues but maybe I am still doing something wrong?

**Comment by Makogan** [comment]
Hmmm I just tested it on a different machine with the exact same OS and version of clang. It works on that machine. So this might be an issue on my end after all.

**Comment by Makogan** [comment]
Found it!!!!

I hav eno idea how or why this is the problem but, when spirv cross is compiled with gcc 10 all of the above happens, when it is compiled with gcc 11, it does not.

So for this to be reproduced you needed to be on linux, compile spirv-cross with gcc 10, and then compile the consumer code with clang 11.

I have no idea if this is a bug with spirv_cross, clang, or gcc, but jesus that was too specific.
