### ISSUE TITLE
MSL: RayQuery WorldRayDirection and WorldRayOrigin() are incorrectly translated

### ISSUE THREAD

**Issue by awefers** [KhronosGroup/SPIRV-Cross#1900]
`WorldRayDirection()` is translated to `get_world_space_ray_origin()` and `WorldRayOrigin()` to `get_world_space_ray_direction()`. The fix is simple:

https://github.com/KhronosGroup/SPIRV-Cross/blob/44691aa9754d9db9f8c0828e5ca6d2909c671200/spirv_msl.cpp#L8535

Should be:
```
MSL_RAY_QUERY_GET_OP(WorldRayOrigin, world_space_ray_origin);
```
And line 8536 should be:
```
MSL_RAY_QUERY_GET_OP(WorldRayDirection, world_space_ray_direction);
```

**Comment by HansKristian-Work** [comment]
Nice find. Guess it was missed during review. :\

**Comment by awefers** [comment]
Thank you!
