### ISSUE TITLE
SPIR-V to MSL: attempt to assign array element to the array itself (out.gl_ClipDistance)

### ISSUE THREAD

**Issue by nastys** [KhronosGroup/SPIRV-Cross#1919]
Attempting to compile [this SPIR-V shader](https://github.com/KhronosGroup/SPIRV-Cross/files/8523117/test.spv.zip) to MSL fails with:
```
Generated MSL failed a validation compilation: (Error code 3):
program_source:443:25: error: array type 'float [1]' is not assignable
    out.gl_ClipDistance = out.gl_ClipDistance[0];
    ~~~~~~~~~~~~~~~~~~~ ^
```
since commit 3d4daab29dd07d531cb309a6db85e87bdc4db220.
Previous commit 44c3333a1c315ead00c24f7aef5fa8a7ccf49299 works.
This affects MoltenVK as well as MoltenVKShaderConverter (which is what I'm using to convert the shader).

**Comment by billhollings** [comment]
Fixed in PR #1927.
