### ISSUE TITLE
Transpile of GLSL to HLSL isn't correct logic on gl_FragCoord.w

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Cross#1921]
This isn't the correct conversion for code that was using gl_fragCoord in GLSL, then converting to SPIR-V, then transpiling to HLSL.  This threw off all our depth calculations.

We had code in our shaders doing.  gl_FragCoord = (xyz, 1/w)
float linearDepth = 1.0 / gl_FragCoord.w;

Since this uses SV_POSITION, that means we have gl_FragCoord = (xyz, w)
float linearDepth = gl_FragCoord.w;   // our workaround for now

Spriv-Cross needs a compile setting to invert w to match the original GLSL logic.

https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.cpp
```
	case BuiltInFragCoord:
			type = "float4";
			semantic = legacy ? "VPOS" : "SV_Position";
			break;
```

**Comment by alecazam** [comment]
This doesn't have to be the default, but something were we say the original SPIRV was generated from GLSL sources and needs inverted gl_FragCoord.w

**Comment by HansKristian-Work** [comment]
SPIRV-Cross already does this.

```
#version 450
layout(location = 0) out vec4 FragColor;
void main()
{
	FragColor = gl_FragCoord;
}
```
emits
```
static float4 gl_FragCoord;
static float4 FragColor;

struct SPIRV_Cross_Input
{
    float4 gl_FragCoord : SV_Position;
};

struct SPIRV_Cross_Output
{
    float4 FragColor : SV_Target0;
};

void frag_main()
{
    FragColor = gl_FragCoord;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    gl_FragCoord = stage_input.gl_FragCoord;
    gl_FragCoord.w = 1.0 / gl_FragCoord.w;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.FragColor = FragColor;
    return stage_output;
}
```

**Comment by alecazam** [comment]
Hmm, we're not seeing this, but I'll delve more.  Note that we use glslc to convert GLSL -> SPIRV, then we use spirv-cross to go from SPIRV -> HLSL.  Is there an indicator in that SPIRV that the original source came from GLSL/gl_FragCoord.w?

**Comment by HansKristian-Work** [comment]
No, but these are the proper semantics of FragCoord in SPIR-V. FragCoord.w is always 1.0 / w. A HLSL compiler targeting SPIR-V will also emit 1.0 / w since it has to emulate HLSL semantics on top of SPIR-V.

**Comment by alecazam** [comment]
This is definitely not working from SPIRV generated by glslc processing GLSL.  This is then run through spirv-opt and SM 5.0.   Then feeding that to spriv-cross doesn't add the 1.0/w correction.  I do see that addition of 1/w in a version of spirv-cross that I pulled from github.   Next I'll run the same command line if I can get that built.

Note that MSL's position is already (xyz,1/w), so that's probably why we've never seen this in our Metal or Vulkan code.  It's just the HLSL gen out of spriv-cross that doesn't have any 1/w correction.

**Comment by alecazam** [comment]
Yes, the newer spirv-cross has the 1.0/w in it, so it was just that our spriv-cross is way too old from 2020.
