### ISSUE TITLE
sorting inputs/outputs/ubos by binding instead of name

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Cross#1923]
We're trying to update to the latest spriv-cross, since our last one was from 2020.   But our reflection pass is failing.  It seems that the uniforms are listed in order by offset, but the inputs/outputs/ubos are sorted by name.   I think in the past, our code received these sorted by binding.   Is there an option to re-enable this behavior?  These randomized bindings are inconsistent with the offset ordering.

**Comment by alecazam** [comment]
I think what's actually happening is unused inputs to the fragment shader are getting removed, and then our own reflection code thinks there's a mismatch between vertex and fragment shader.

**Comment by HansKristian-Work** [comment]
I would need concrete SPIR-V examples to look at this.

**Comment by alecazam** [comment]
This is the simplest case.  I don't see a_worldPos in the spirv output from glslc/spirv-opt, unless I declare it.  So this may all be happening upstream.

```
// vs
#version 450

in vec4 a_position;
out vec3 a_worldPos;

void main()
{
   gl_position = a_position;
   a_worldPos = a_position.xyz;
}

// fs
#version 450

in vec3 a_worldPos;
layout (location = 0) out vec4 o_fragColor0;

void main()
{
    a_worldPos; // fixes issue
    // with this commented out, the input is stripped, and vs outputs/fs inputs now have a gap
    //o_fragColor0 = a_position;
    o_fragColor0 = float4(0.0);
}

```

**Comment by HansKristian-Work** [comment]
SPIRV-opt will remove unused variables like this, so you'll have to skip that optimization I think. SPIRV-Cross does not eliminate inputs unless asked so.

**Comment by alecazam** [comment]
The problem is that I think glslc is doing this, and there's no option there to prevent it.   For spriv-opt, we set --preserve-bindings, but the values are stripped.

**Comment by HansKristian-Work** [comment]
It sounds like this should be reported to shaderc / spirv-tools instead, is there a SPIRV-Cross bug here?

**Comment by alecazam** [comment]
I'll file it with glslc.  I tried to fixup cases where unsed vertex or fragment inputs were stripped, but on some platforms the data isn't getting down to the vs, or passed between the vs/fs correctly anymore.
