### ISSUE TITLE
undeclared identifier

### ISSUE THREAD

**Issue by vili-1** [KhronosGroup/SPIRV-Cross#1925]
`spirv-cross` generates incorrect MSL program which the Metal compiler is rejecting. The error below is self-described. Attached the original SPIR-V and the corresponding metal.

```
error: use of undeclared identifier '_62'
    _32._m0[_62] = 8u;
```
[Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/8567042/Archive.zip)

**Comment by HansKristian-Work** [comment]
The MSL output looks bizarre here, I'll have a look ...
