### ISSUE TITLE
GLSL -> HLSL switch statement no breaks generated

### ISSUE THREAD

**Issue by iwubcode** [KhronosGroup/SPIRV-Cross#1943]
I'm not an expert in graphics programming but am trying to convert an existing project to use SPIRV-Cross.  One of the issues I am running into is the following error from the HLSL compiler:

`error X3533: non-empty case statements must have break or return`

I believe this is an issue with either SPIRV-Cross or the code we use to generate the spriv glslang.

The generated HLSL code unsurprisingly looks like this:

```
case 0u:
{
    if (comp0 && comp1)
    {
        break;
    }
    else
    {
        discard;
    }
}
case 1u:
{
...
}
```

However, here is the GLSL:

```
#define discard_fragment discard
...
case 0u:
{
  if (comp0 && comp1) break; else discard_fragment;
}
break;
case 1u:
{
  ...
}
```

I believe this is the relevant SPIRV disassembly:

```
                                Switch 1,686 1,691 
                                       case 0: 1,687
                                       case 1: 1,688
                                       case 2: 1,689
                                       case 3: 1,690
           1,687:                 Label
                                  Line 1 662 0
           1,692:    58(bool)     Load 1,651(comp0)
           1,693:    58(bool)     Load 1,666(comp1)
           1,694:    58(bool)     LogicalAnd 1,692 1,693
                                  SelectionMerge 1,696 None
                                  BranchConditional 1,694 1,695 1,698
           1,695:                   Label
                                    Branch 1,691
           1,698:                   Label
                                    Kill
           1,696:                 Label
                                  Unreachable
```

I was assuming this was a Spirv-cross issue but it may also be an issue with glslang that we use to generate the spirv.

Please let me know if any other details are needed!

EDIT:  forgot to mention, this was tested with the last known tag (since the releases were really old), [sdk-1.3.211.0](https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/sdk-1.3.211.0)

**Comment by HansKristian-Work** [comment]
This is pretty subtle. discard is not a terminating instruction in HLSL, but it is in SPIR-V. SPIR-V also allows fallthrough. We'll have to detect this case and inject dummy breaks to make this work.
