### ISSUE TITLE
MSL: Support SPV_KHR_fragment_shader_barycentric

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/SPIRV-Cross#1949]
The `VK_KHR_fragment_shader_barycentric` extension was released today with 1.3.215 and as Metal has supported barycentric coordinates in fragment shaders for nearly two years now (since iOS 14) and the extension purely adds support for the SPIR-V extension, one would mostly only need SPIRV-Cross to support emitting proper MSL shaders. A simple fragment might look like this:

```metal
fragment float4 simple_frag(VertexOut vertex,
                            float2 barycentric [[barycentric_coord]]) {

}
```

Related to #1010 and the KHR extension seems to be nearly identical to what NVIDIA released back then, so I guess this should not be too hard. I think even myself could add the support pretty quickly :)

**Comment by billhollings** [comment]
Can you clarify what functionality you are requesting that is not already provided by the NV version of this already implemented in SPIRV-Cross?

For instance, in comparing your MSL above to [this](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/reference/shaders-msl/frag/barycentric-nv-nopersp.msl22.frag) SPIRV-Cross reference shader.

**Comment by spnda** [comment]
The functionality is completely identical. The issue is that SPIRV-Cross probably doesn't recognise the new version of the extension when parsing the SPIR-V. Perhaps it's simply just adding detection for `SPV_KHR_fragment_shader_barycentric`, as all other enum values should be identical.

**Comment by HansKristian-Work** [comment]
KHR barys already work fine as-is. Well, PerVertexKHR does not exist in MSL at all it seems, but the Bary builtins work as-is. All the enums for NV and KHR alias so there is no work needed here.
