### ISSUE TITLE
HLSL source to GLSL Vertex/Fragment interface linking error on MacOSX

### ISSUE THREAD

**Issue by Jasonchan35** [KhronosGroup/SPIRV-Cross#196]
I found the solution in Readme.md  ("Vertex/Fragment interface linking")
but I have no idea where and how to add those line in the code
```
// Something like this for both vertex outputs and fragment inputs.
compiler.set_name(varying_resource.base_type_id, "VertexFragmentLinkage");
```
I have no idea the value of varying_resource.base_type_id

so I did my dirty fix by remapping any VS output / FS input at location=0, 
and any better suggestion for the fix ?

by the way, if this can be handled by default would be very nice, or any knowing concern to not doing this ?

here is my dirty fix:
```
void CompilerGLSL::remap_varying() {
	//MacOSX require vs_output -> ps_input variable using the same variable name

	auto model = get_execution_model();
	uint32_t i = 0;
	for (auto& m : meta) {
		auto& dec = m.decoration;
		if (dec.decoration_flags & (1ull << DecorationLocation) && dec.location == 0) {
			auto& v = get<SPIRVariable>(i);
			auto& t = get<SPIRType>(v.basetype);

			switch (model) {
				case ExecutionModelVertex: {
					if (t.storage == StorageClassOutput) {
						set_name(i, "VertexFragmentLinkage");
					}
				}break;
				case ExecutionModelFragment: {
					if (t.storage == StorageClassInput) {
						set_name(i, "VertexFragmentLinkage");
					}
				}break;
			}
		}
		i++;
	}
}
```

**Comment by HansKristian-ARM** [comment]
Could you paste the .spv for vertex and fragment so I could get the full context?

The main idea here is that glslang emits HLSL in a particular way, and you will need to make sure that the name of the struct which is passed between stages is the same type.

The reason for not doing this by default is because it depends on factors which spirv-cross cannot know of in isolation. It only sees one shader at a time, not a group of shaders which are linked together.

**Comment by HansKristian-ARM** [comment]
Normally what you would want is something like:
```
auto resources = compiler.get_shader_resources();
// For fragment shaders
for (auto &v : resources.stage_inputs)
    if (compiler.get_decoration(v.id, spv::DecorationLocation) == 0)
        compiler.set_name(v.base_type_id, "VertexFragmentLinkage");
// For vertex shaders
for (auto &v : resources.stage_output)
    if (compiler.get_decoration(v.id, spv::DecorationLocation) == 0)
        compiler.set_name(v.base_type_id, "VertexFragmentLinkage");
```

**Comment by Jasonchan35** [comment]
Thanks,
If this cannot be done by default, then is it possible to add command line argument to control it ?
for example:
```
spirv-cross.exe  vs.spv  --remap-output-layout-variable 0 "VertexFragmentLinkage" --output my.glsl_vert
spirv-cross.exe  ps.spv  --remap-input-layout-variable 0 "VertexFragmentLinkage" --output my.glsl_frag
```
Which would be nice to avoid code modification and compile own version for this use case.

And I can do the change and sending pull request if you think it's a good feature to have for everyone

Here is my HLSL source and output SPV, GLSL files
[HLSL_to_GLSL.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1069031/HLSL_to_GLSL.zip)

**Comment by HansKristian-ARM** [comment]
I see, there is something similar atm with --remap, but that is designed to remap to builtin variables. If you can add a feature --rename-interface-variable "src-name" "dst-name" or something like that I can merge that. Seems like a useful feature.

**Comment by Jasonchan35** [comment]
Yup, I tried remap, but it didn't fit what I need.

I can add the feature. But I prefer to use input/output location instead of "src-name", because the "src-name" maybe different between HLSL files, but the location seems always '0' if struct type is used for input/output interface variables, which is what people do in HLSL with struct member "Semantic"

Then it become:
--rename-interface-variable <in/out> <location> "dst-name"

And I can use the same suffix rule in Makefile
