### ISSUE TITLE
'default' statement not in switch statement

### ISSUE THREAD

**Issue by vili-1** [KhronosGroup/SPIRV-Cross#1969]
spirv-cross generates incorrect MSL program; the Metal compiler rejects it. There are three different errors in this example all related to switch/case/default - see below. Attached the original SPIR-V and the corresponding metal.

```
$ xcrun -sdk macosx metal --analyze /Users/vklim/Downloads/switch_error.metal
/Users/vklim/Downloads/switch_error.metal:54:9: error: 'default' statement not in switch statement
        default:
        ^
/Users/vklim/Downloads/switch_error.metal:67:9: error: 'default' statement not in switch statement
        default:
        ^
/Users/vklim/Downloads/switch_error.metal:252:41: error: multiple default labels in one switch
                                        default:
                                        ^
/Users/vklim/Downloads/switch_error.metal:144:17: note: previous case defined here
                default:
                ^
/Users/vklim/Downloads/switch_error.metal:470:41: error: multiple default labels in one switch
                                        default:
                                        ^
/Users/vklim/Downloads/switch_error.metal:362:17: note: previous case defined here
                default:
                ^
4 errors generated.
```
[Archive.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/9023742/Archive.zip)

**Comment by HansKristian-Work** [comment]
Is this fuzzed code? This is the root cause I think:

```
               OpSelectionMerge %158 None
               OpSwitch %155 %158
```
deeply cursed ...

**Comment by afd** [comment]
Yes, it is a kind of fuzzing, but a bit different from GraphicsFuzz or spirv-fuzz. We have designed a formal model of SPIR-V control flow and are using it to generate interesting control flow graphs. We then have a way of turning those into runnable test cases, which involves choosing a random path through the CFG, inserting instrumentation to force that path to be followed, and then checking (via an SSBO) that the required path is indeed followed.
