### ISSUE TITLE
Undeclared identifier when generating HLSL

### ISSUE THREAD

**Issue by Jack-Clark** [KhronosGroup/SPIRV-Cross#1972]
For the SPIR-V example contained in [this archive](https://github.com/KhronosGroup/SPIRV-Cross/files/9048485/undeclared-identifier.tar.gz), spirv-cross seems to be generating incorrect HLSL code. When using DXC to compile the HLSL produced by spirv-cross I get the following error:
```
error: use of undeclared identifier '_189'
            uint _191 = _189;
```

There are two fragments in the HLSL code that look like this:
```
for (;;)
{
    _21.Store(_186 * 4 + 0, 23u);
    uint _189 = _186 + 1u;
    break;
}
uint _199;
uint _200;
uint _216;
uint _217;
uint _224;
uint _225;
uint _191 = _189;
```
I'm not too familiar with HLSL, but I'm guessing that it has scoping rules similar to C? If so, then this fragment would be invalid, because `_189` is declared inside the loop, but then is referred to outside the loop (and is not defined in any outer scope).

I've reproduced this on main (commit id: d8d051381f65b9606fb8016c79b7c3bab872eec3). This error was found by a fuzzer, and it seems to be necessary to have OpPhi commands in the SPIR-V in order to trigger this.

**Comment by HansKristian-Work** [comment]
Extreme edge case where the Phi is detected as a loop variable in addition to a Phi input being a part of a block-like loop construct, so the write to _191 is not resolved inside the loop, but it gets deferred through static assignment instead. We'll have to detect this case.
