### ISSUE TITLE
Segfault when creating a pipeline with an empty shader module

### ISSUE THREAD

**Issue by danielkeller** [KhronosGroup/SPIRV-Cross#1980]
If I create a compute pipeline from MoltenVK using the spirv `0x07230203, 0x00010000, 0, 0, 0, 0x0003000e, 0, 1` which is

```
; Magic:     0x07230203 (SPIR-V)
; Version:   0x00010000 (Version: 1.0.0)
; Generator: 0x00000000
; Bound:     0
; Schema:    0
               OpMemoryModel Logical GLSL450
```

I get a segfault from spirv_cross, inside

```
MVK_spirv_cross::CompilerMSL::is_msl_resource_binding_used
mvk::SPIRVToMSLConverter::convert
```

**Comment by HansKristian-Work** [comment]
You're passing in an invalid SPIR-V module here, so passing it to MoltenVK is undefined behavior to begin with.

```
error: line 1: Operand 2 of MemoryModel requires one of these capabilities: Shader 
  OpMemoryModel Logical GLSL450
```

When trying to decompile the shader SPIRV-Cross throws: `There is no entry point in the SPIR-V module.` I don't believe this is a SPIRV-Cross bug, so closing.
