### ISSUE TITLE
Unknown identifier 'binding' in layout error

### ISSUE THREAD

**Issue by ellipticaldoor** [KhronosGroup/SPIRV-Cross#1981]
I'm trying to transform an spv shader made with 440 glsl to an 330 glsl shader file, but when I try to load the result I get the error:

```
Unable to compile fragment shader
ERROR: 0:6: Unknown identifier 'binding' in layout
ERROR: 0:12: Use of undeclared identifier 'texture_1'
```

The platfom I'm using is macos.

This is the original shader code:
```glsl
#version 450 core

layout(location = 0) out vec4 color;

layout(binding = 1) uniform sampler2D texture_1;

void main() {
    color = texelFetch(texture_1, ivec2(gl_FragCoord.xy), 0);
}
```

This is the command used to generate the spirv file
```shell
./glslc ./canvas.frag -o ./canvas.frag.spv
```

This is the command used to convert the spirv file to glsl 330
```shell
./spirv-cross --version 330 --no-es ./canvas.frag.spv --output canvas.330.frag
```
And this is the output
```glsl
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

layout(binding = 1) uniform sampler2D texture_1;

layout(location = 0) out vec4 color;

void main()
{
    color = texelFetch(texture_1, ivec2(gl_FragCoord.xy), 0);
}
```
I think in glsl 330 you are not supposed to use binding with uniform samplers, maybe the issue is that GL_ARB_shading_language_420pack is not properly supported in mac?

I attached the spv with a .txt extension because github will not let me to upload it.
[canvas.frag.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/9125733/canvas.frag.spv.txt)

**Comment by HansKristian-Work** [comment]
> GL_ARB_shading_language_420pack is not properly supported in mac?

That might be the case, but I'm not sure what to do in that case. You'd have to just unset all binding decorations using the reflection API instead probably.

**Comment by uraniumanchor** [comment]
I think `--no-420pack-extension` is what you want if you're using the CLI. I ran into a similar problem on OSX, and when using the library to do the cross compilation I had to set `enable_420pack_extension` to false in the options struct before making the call, or I'd run into the same problem.

**Comment by ellipticaldoor** [comment]
thank you! @uraniumanchor that worked for me
