### ISSUE TITLE
In HLSL output, allow setting a custom "register" for resources

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/SPIRV-Cross#199]
In NXT we are using spirv-hlsl for our D3D12 backend and successfully got a HelloTriangle working with VS inputs. We are now looking at adding support for uniform buffers and need to control which register a ```cbuffer``` is assigned to so that we can make it match the register number in our root signature. Is it possible to provide an API to set the register numbers? The same thing would be necessary for texture, samplers, UAVs, and friends.

For reference here's our SPIR-V GLSL:
```
layout(set = 0, binding = 0) uniform myBlock {
    int a;
    float b;
} myUbo;
```

What spriv-hlsl produces:
```
struct _myBlock
{
   int a;
   float b;
};

cbuffer myBlock
{
   _myBlock myUbo;
};
```

What we need (with N being customizable):
```
struct _myBlock
{
   int a;
   float b;
};

cbuffer myBlock : register(cN)
{
   _myBlock myUbo;
};
```

**Comment by Kangz** [comment]
Also CC @austinEng

**Comment by HansKristian-ARM** [comment]
Currently, DecorationBinding is not honored in the HLSL backend when emitting uniforms. This should be fairly trivial to add. Ping @RobDangerous

**Comment by HansKristian-ARM** [comment]
I'll probably have a stab at this tomorrow, seems simple enough.

**Comment by Kangz** [comment]
Thanks for the quick answer! Using DecorationBinding for that sounds good, we'll modify it before invoking compile().

**Comment by HansKristian-ARM** [comment]
Merged on master. https://github.com/KhronosGroup/SPIRV-Cross/pull/202

**Comment by Kangz** [comment]
#202 LGTM and would work for us, thanks!
