### ISSUE TITLE
Is the **target_sources** accumulated for shared libraries??

### ISSUE THREAD

**Issue by jiapei-nexera** [KhronosGroup/SPIRV-Cross#1991]
From [CMakeLists.txt](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/CMakeLists.txt#L37),
`option(SPIRV_CROSS_SHARED "Build the C API as a single shared library." ON)` seems to tell, if I wanna build a **SHARED** library, it will combine everything into a **single** library???

However, for instance, **line 355~358** of [CMakeLists.txt](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/CMakeLists.txt#L355-L358),

```C++
if (SPIRV_CROSS_ENABLE_GLSL)
		target_sources(spirv-cross-c-shared PRIVATE ${spirv-cross-glsl-sources})
		target_compile_definitions(spirv-cross-c-shared PRIVATE SPIRV_CROSS_C_API_GLSL=1)
	endif()
```

is the **target_sources** accumulated?

I tested and it seems for **SHARED** libraries, if we build a section, say: **SPIRV_CROSS_ENABLE_GLSL**, then, I cannot build another section **SPIRV_CROSS_ENABLE_MSL** at the same time, which is **NOT** as convenient as static  ?????

Am I right??

Cheers

**Comment by HansKristian-Work** [comment]
target_sources in CMake is accumulative, yes. Not sure exactly what the question is. You can build everything (GLSL/MSL/HLSL/etc) into the shared library.

**Comment by HansKristian-Work** [comment]
Doesn't seem like there are further actions, so closing.
