### ISSUE TITLE
Bindless/unbounded array reflection not always accurate

### ISSUE THREAD

**Issue by LiamTyler** [KhronosGroup/SPIRV-Cross#2006]
Hello,

Say I have a bindless array like so: `layout( set = 0, binding = 0 ) uniform sampler2D textures[];`

I noticed that when a shader does not actually index into this array with at least one non-uniform index, spirv-cross reflection will report a non-zero size for the array. Specifically, the size will be the highest static index + 1. Is this intentional? Dumb example repro:

```
#version 450
#extension GL_EXT_nonuniform_qualifier : enable

layout( location = 0 ) out vec4 FragColor;
layout( location = 0 ) in vec4 vColor;
layout( set = 1, binding = 0 ) uniform sampler2D textures[];

void main()
{
    FragColor = texture( textures[0], vec2( 0, 0 ) ).rgba;
}
```

The reflection will report a size of 1. If you change the final line to be `texture( textures[5], vec2( 0, 0 ) )` it will report a size of 6. If you change it to be `texture( textures[int( vColor.x )], vec2( 0, 0 ) )` it will report a size of 0 (which is what I expected for all of them, given how it was declared). I am doing the reflection by getting the SPIRType for that resource, and checking type.array (just like how it's done here: https://github.com/Themaister/Granite/blob/master/vulkan/shader.cpp#L338)

I noticed this as I was commenting out large swathes of shader code to debug some things, and noticed that the reflection suddenly considered the resource as non-bindless, with a size of 1. I was only accessing the first slot like this `textures[0]` because it contained a known debug texture. Things exploded since I was using the reflection to help build the descriptor set layout for the bindless textures, and then I was binding textures to it on the CPU side still expecting an unbounded array, but now that it was array of size 1, it was invalid to bind those textures.

Wondering if this is intentional, and if so, if there is any way around it?

**Comment by HansKristian-Work** [comment]
For unaccessed arrays, glslang emits the array size as 1, so there's nothing we can do. This inherits legacy GLSL behavior where unsized resource arrays are supported if they are only accessed with constant indices and the size is inferred from that.

**Comment by LiamTyler** [comment]
> This inherits legacy GLSL behavior where unsized resource arrays are supported if they are only accessed with constant indices and the size is inferred from that.

Well that's unfortunate haha. Thanks for the info though!
