### ISSUE TITLE
[MSL] some Zink generated SPIR-V shaders fail with "SPIRV-Cross threw an exception: Found a buffer packing case which we cannot represent in MSL."

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#2008]
Hi,

don't know if this is fixable or not but running some code through Zink and captured resulting SPIR-V files through ZINK_DEBUG=spirv..
I include three shaders altough all fail equally with SPIRV-Cross, they are different.. they fail with:
"SPIRV-Cross threw an exception: Found a buffer packing case which we cannot represent in MSL."
I compile using SPIRV-Cross from Vulkan SDK 1.3.224 so few days old, using:
"spirv-cross out.spv --metal --msl-version 20200 >a.metal"

one variant of compiled shader uses NV_shader_atomic_int64 which currently not officially Zink supported but some patches were provided to support it..

also note the Zink generated SPIR-V currently fails validation with spirv-val but hope is not the reason of SPIRV-Cross failing..

included shaders:
*dump06.spv (uses atomic min on uint64 buffer but current Zink patches don't insert Option atomic int64 capability):
```
spirv-val dump06.spv
error: line 2182: AtomicUMin: 64-bit atomics require the Int64Atomics capability
  %2024 = OpAtomicUMin %ulong %2023 %uint_1 %uint_0 %2003
```
*dump06no.spv (doesn't use atomic uint64 instruction emulates with read+min+store uint64 buffer and renders with Zink correctly)
*dump06cap.spv (more hacking to forcelly Zink to insert option)
these two fail similarly with:
```
spirv-val dump06cap.spv
error: line 55: Structure id 10 decorated as Block for variable in StorageBuffer storage class must follow standard storage buffer layout rules: member 1 at offset 0 overlaps previous member ending at offset 255
  %struct_ssbos = OpTypeStruct %_arr_ulong_uint_32 %_runtimearr_ulong

spirv-val dump06no.spv
error: line 54: Structure id 10 decorated as Block for variable in StorageBuffer storage class must follow standard storage buffer layout rules: member 1 at offset 0 overlaps previous member ending at offset 255
  %struct_ssbos = OpTypeStruct %_arr_ulong_uint_32 %_runtimearr_ulong

```
Attached 3 SPIR-V files:
[metalbugs.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/9429521/metalbugs.zip)
 
once if fixed this, will try with Metal Developer Tools to see if they compile correctly..
really expecting the atomic int64 versions (dump06.spv,dump06cap.spv) will not compile due to SPIRV-Cross generating atomic_fetch_min_explicit() insted of only required atomic_min_explicit() in this shaders (they don't need a return value of atomic min with old value on buffer)..

see https://github.com/KhronosGroup/MoltenVK/issues/1692 for more related info..
but let me open another related issue with more detailed info on that topic..

thanks..

**Comment by HansKristian-Work** [comment]
spirv-val fails even with --scalar-block-layout here, so I would expect that to explode.

```
spirv-val /tmp/dump06no.spv --scalar-block-layout
error: line 54: Structure id 10 decorated as Block for variable in StorageBuffer storage class must follow scalar storage buffer layout rules: member 1 at offset 0 overlaps previous member ending at offset 255
  %struct_ssbos = OpTypeStruct %_arr_ulong_uint_32 %_runtimearr_ulong
```

```
spirv-val /tmp/dump06no.spv --scalar-block-layout
error: line 54: Structure id 10 decorated as Block for variable in StorageBuffer storage class must follow scalar storage buffer layout rules: member 1 at offset 0 overlaps previous member ending at offset 255
  %struct_ssbos = OpTypeStruct %_arr_ulong_uint_32 %_runtimearr_ulong
```
