### ISSUE TITLE
GLSL: support for loop unrolling?

### ISSUE THREAD

**Issue by everywill** [KhronosGroup/SPIRV-Cross#2013]
I encounter a shader related problem in safari browser(webgl via metal). The shader computing the lighting with a large for-loop block makes the gpu abnormally high. When unrolling the loop(by hand), everything looks good. Is there a option can make spirv-cross to unrolling the loop?

**Comment by HansKristian-Work** [comment]
No. This is the domain of spirv-opt. It has loop-unrolling passes.
