### ISSUE TITLE
Is there any plan to support translating SPIRV to WGSL

### ISSUE THREAD

**Issue by jianliang79** [KhronosGroup/SPIRV-Cross#2030]
WebGPU will be officially supported in chrome 109 according to this link:
    https://chromestatus.com/feature/6213121689518080
    WGSL will be the shader language used by WebGPU (SPIRV support seems to be dropped by WebGPU), Is there any plan to support translating SPIRV to WGSL with SPIRV-Cross project?

**Comment by HansKristian-Work** [comment]
No. WebGPU provides their own tooling for this.
