### ISSUE TITLE
Need a way to remap attribute names to HLSL semantics

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Cross#2037]
There are some shipping shader compilers that seem to strip all attributes silently above TEXCOORD9 and then our shaders break.   But spriv-cross, just keeps incrementing TEXCOORD by default.

The current command line arguments aren't sufficient where you specify a location and semantic.  We don't track location.   We need to remap by name instead.  We don't track locations, only that we have a_position, a_normal, a_tangent.  Something akin to the following change.

```
std::string CompilerHLSL::to_semantic(uint32_t location, ExecutionModel em, StorageClass sc)
{
	if (em == ExecutionModelVertex && sc == StorageClassInput)
	{
		// We have a vertex attribute - we should look at remapping it if the user provided
		// vertex attribute hints.
		for (auto &attribute : remap_vertex_attributes)
			if (attribute.location == location)
				return attribute.semantic;

                  // Note: name would need to passed in as well
                  for (auto &attribute : remap_vertex_attributes_names)
			if (attribute.name == name)
				return attribute.semantic;
	}

	// Not a vertex attribute, or no remap_vertex_attributes entry.
	return join("TEXCOORD", location);
}

```

**Comment by HansKristian-Work** [comment]
OK, so the gist here is that you want a way to emit user defined names for vertex inputs rather than plain locations?
