### ISSUE TITLE
MSL: restrict keyword is not working

### ISSUE THREAD

**Issue by KhoraLee** [KhronosGroup/SPIRV-Cross#2038]
I run `MoltenVKShaderConverter` to convert spv to msl. Msl output was valid but if restrict keyword exist it fails to run since metal 2.3.

Metal 2.2
```
% xcrun metal -x metal -std=macos-metal2.2 -Werror -Wno-unused-variable test.metal
```

Metal2.3 ~ 3.0
```
% xcrun metal -x metal -std=macos-metal2.3 -Werror -Wno-unused-variable test.metal
test.metal:98:70: error: expected ')'
  ...main_fs_out main_fs(const device fragmentDataType& restrict fragmentDat...
                                                                 ^
test.metal:98:29: note: to match this '('
fragment main_fs_out main_fs(const device fragmentDataType& restrict fr...
                            ^
test.metal:111:21: error: use of undeclared identifier 'fragmentData'
        sa[i + 0] = fragmentData.buffer14[i];
                    ^
2 errors generated.```

**Comment by cdavis5e** [comment]
It looks like they changed it so that `restrict` is no longer a keyword. I wonder why they did that...

Anyway, this issue was known to me because several Vulkan CTS tests fail because of it.

`__restrict` still works for now. I wonder how long it'll be before that remove that too.

**Comment by HansKristian-Work** [comment]
If __restrict works on older MSL versions, we can just move to that. `restrict` does not exist in ISO C++ yet iirc, but it does in C.
