### ISSUE TITLE
[HLSL] cbuffers using a struct to access members

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/SPIRV-Cross#204]
Hi. When converting a cbuffer from SPV to HLSL, SPIRV-Cross generates an additional struct:

`struct _PerDraw
{
    float4x4 MatrixTransform;
};

cbuffer PerDraw
{
    _PerDraw PerDraw_var;
};`

Is there the possibility not to have this struct, but have all cbuffer members inserted into the cbuffer instead?

**Comment by HansKristian-ARM** [comment]
We have tried this, but it is not possible to avoid it, sadly.

**Comment by Joojooo** [comment]
Thanks for your reply.
In our case it's not only for cosmetics: our app fails to retrieve / link cbuffer members when replacing our HLSL-base shaders by SPIRV (and converting back SPV to HLSL with SPIRV-Cross), due to this intermediary struct. No worry we can investigate how to update our app to consider this. I was just checking what why the reason behing it.
I also implemented (hacked) a quick work-around in SPIRV-Cross in order to remove the struct, but it will indeed not work in all cases.
Perhaps in the future it could be beneficial to add the struct only for the cbuffer that requires it (if possible)?

**Comment by HansKristian-ARM** [comment]
If a cbuffer does not have an instance name set, it might be possible to avoid the struct, but there are other problems associated with that, like namespace collisions, and special casing more stuff to handle this case. It's not impossible, but I would like to avoid such workarounds if possible.

**Comment by HansKristian-ARM** [comment]
I will close this as there is no obvious clean solution to this problem. Please reopen if you are blocked on this and really need a workaround.
