### ISSUE TITLE
Incorrect pointer handling in shader from Zink

### ISSUE THREAD

**Issue by stefand** [KhronosGroup/SPIRV-Cross#2040]
I am trying to run wglgears with Zink built for Windows inside Wine on MacOS. Wine plus Zink's Win32 support take care of the Window system integration, MoltenVK translates this to metal. With the attached SPIR-V shader I get the following error from MSL:

`program_source:43:884: error: member reference type 'const constant struct_uniform_0_32 *' is a pointer; did you mean to use '->'?`

Copypasting the failing line won't help much because it is a 800 character monster, so I'll try cut it down:

```
struct struct_uniform_0_32
{
    uint _m0[44];
};

...

vertex main0_out main0(main0_in in [[stage_in]], constant struct_uniform_0_32* uniform_0_32_0 [[buffer(1)]])
{
    constant struct_uniform_0_32* uniform_0_32[] =
    {
        uniform_0_32_0,
    };

```

Later this  array of pointers is accessed as

`uniform_0_32[0u]._m0[28u]`

To my eyes it looks indeed as if this should be "uniform_0_32[0u]->_m0[28u]" instead.

I tried to read the SPIRV disassembly itself. I think it is correct, and on Linux the khronos validation layer does not find anything objectionable. Afaics one example of the relevant SPIRV lines are the OpAccessChain operations at "%34 = OpAccessChain %33 %25 %31" and following. spirv-val complains about struct alignment but nothing else:

```
spirv-val dump00.spv 
error: line 46: Structure id 22 decorated as Block for variable in Uniform storage class must follow standard uniform buffer layout rules: member 0 contains an array with stride 4 not satisfying alignment to 16
  %struct_uniform_0_32 = OpTypeStruct %_arr_uint_uint_44
```

But to be honest, this is the first time I am trying to understand a SPIR-V shader and it isn't exactly an accessible language.
[zink.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/9828158/zink.zip)

I'll keep investigating this issue myself, but maybe someone with more experience with the spirv-cross code can find a solution faster than I do.

**Comment by stefand** [comment]
Afaics the bug is most likely in CompilerMSL::to_member_reference.

Indexing into the array of pointers is SPIRExpression, not a SPIRVariable, so the declared_as_pointer detection does not work. I tried to hack it up by checking the type when the function is faced with an Expression. Weirdly type.pointer is not set. I did hack it up  for my test program with the attached hack though. The generated shader then compiles with an offline compiler.

[hack.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/9840945/hack.txt)

Putting the modifications back into MoltenVK successfully runs wglgears:

<img width="966" alt="Bildschirmfoto 2022-10-21 um 19 45 38" src="https://user-images.githubusercontent.com/521262/197248200-d2567827-9d94-433a-b120-418ee4df2f83.png">

This non-benchmark runs at a whopping 110-120 fps with vsync off, vs ~3000 with Apple's own GL to Metal wrapper. So a lot of work needs to be done...

(I hope the attached files work, I accidentally uploaded them in a different browser tab that had pull request 1563 open)

**Comment by HansKristian-Work** [comment]
I'll look into it tomorrow.

**Comment by HansKristian-Work** [comment]
The bug manifests with partial access chains. Here's a smaller reproducer:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 25
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %FragColor
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 450
               OpName %main "main"
               OpName %FragColor "FragColor"
               OpName %UBOs "UBOs"
               OpMemberName %UBOs 0 "v"
               OpName %ubos "ubos"
               OpDecorate %FragColor Location 0
               OpMemberDecorate %UBOs 0 Offset 0
               OpDecorate %UBOs Block
               OpDecorate %ubos DescriptorSet 0
               OpDecorate %ubos Binding 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
  %FragColor = OpVariable %_ptr_Output_v4float Output
       %UBOs = OpTypeStruct %v4float
       %uint = OpTypeInt 32 0
     %uint_2 = OpConstant %uint 2
%_arr_UBOs_uint_2 = OpTypeArray %UBOs %uint_2
%_ptr_Uniform__arr_UBOs_uint_2 = OpTypePointer Uniform %_arr_UBOs_uint_2
%_ptr_Uniform_UBOs = OpTypePointer Uniform %UBOs
       %ubos = OpVariable %_ptr_Uniform__arr_UBOs_uint_2 Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_v4float = OpTypePointer Uniform %v4float
      %int_1 = OpConstant %int 1
       %main = OpFunction %void None %3
          %5 = OpLabel
         %ptr0_partial = OpAccessChain %_ptr_Uniform_UBOs %ubos %int_0
		 %ptr0 = OpAccessChain %_ptr_Uniform_v4float %ptr0_partial %int_0
         %ptr1_partial = OpAccessChain %_ptr_Uniform_UBOs %ubos %int_1
		 %ptr1 = OpAccessChain %_ptr_Uniform_v4float %ptr1_partial %int_0
         %20 = OpLoad %v4float %ptr0
         %23 = OpLoad %v4float %ptr1
         %24 = OpFAdd %v4float %20 %23
               OpStore %FragColor %24
               OpReturn
               OpFunctionEnd
```

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct UBOs
{
    float4 v;
};

struct spvDescriptorSetBuffer0
{
    constant UBOs* ubos [[id(0)]][2];
};

struct main0_out
{
    float4 FragColor [[color(0)]];
};

fragment main0_out main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    main0_out out = {};
    out.FragColor = spvDescriptorSet0.ubos[0].v + spvDescriptorSet0.ubos[1].v;
    return out;
}
```

**Comment by stefand** [comment]
The fix works for me with wglgears, thanks!
