### ISSUE TITLE
sampler buffer is put into resources.sampled_images

### ISSUE THREAD

**Issue by zhangming-cloud** [KhronosGroup/SPIRV-Cross#2041]
![image](https://user-images.githubusercontent.com/62131507/197710377-012bef66-e7bf-44c5-8e52-05fcd47410cc.png)
sampler buffer is put into resources.sampled_images
![8693555491_71798292001_IMG_20221025_153351_ B@9263dbb](https://user-images.githubusercontent.com/62131507/197711778-cc48f294-4e1a-4a5c-a64e-005b59e55db5.jpg)
![8693555491_71798230870_IMG_20221025_153400_ B@1c14d23](https://user-images.githubusercontent.com/62131507/197711822-d544c1a8-497b-42a2-982c-bb221621611d.jpg)
![image](https://user-images.githubusercontent.com/62131507/197711916-96ecc98b-63cb-4fde-9546-8f03be96082a.png)

**Comment by zhangming-cloud** [comment]
![image](https://user-images.githubusercontent.com/62131507/197722892-312e1640-3c4b-45c1-874b-229929dca332.png)

**Comment by HansKristian-Work** [comment]
This is expected. sampledBuffer is a deprecated construct that is combined with sampler. A samplerBuffer is technically an image, it just has a buffer dimension. To get separate_image here, you need `textureBuffer`.

**Comment by zhangming-cloud** [comment]
thanks
