### ISSUE TITLE
Numerous test shaders failing with most recent glslang

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#205]
I just updated to the most recent `glslang`, `SPIRV-Tools`, and `SPIRV-Cross`.

This has caused a number of test shaders to start breaking...mostly around the handling of resource locations. Some GLSL shaders result in DIFF's with the reference shaders...and some GLSL shaders refuse to compile to SPIR-V.

**Comment by HansKristian-ARM** [comment]
I'll have a look as soon as I can.

**Comment by HansKristian-ARM** [comment]
@billhollings I had to make some changes to MSL, so please review: https://github.com/KhronosGroup/SPIRV-Cross/pull/206

**Comment by billhollings** [comment]
@HansKristian-ARM 

I've reviewed now. Looks good.
