### ISSUE TITLE
Fix `shaderFragmentDepth32FloatMultisample` failures in the Vulkan CTS

### ISSUE THREAD

**Issue by cdavis5e** [KhronosGroup/SPIRV-Cross#2054]
This is in support of a Khronos contract to reduce CTS failures in MoltenVK, leading up to certification as a Vulkan Portability implementation.

These failures are caused by a bug in Metal, but not one the name of the Vulkan Portability feature implies. It's actually caused by some Metal devices--notably, Apple Silicon GPUs, and possibly others--continuing to allow writes to storage resources, even if the fragment were discarded. Luckily, we can work around this, and the workaround isn't even that intrusive. A boolean flag will be added, which is set when the fragment is discarded, and checked when a resource is written to.

I have filed feedback FB11736212 to cajole Apple into fixing this on their end. In anticipation of this, the workaround is controlled by an option.

Fixes at least three CTS tests, under `dEQP-VK.glsl.builtin_var.fragdepth.*`, and possibly others.

**Comment by HansKristian-Work** [comment]
Was this meant to be a PR, or just the issue explaining the upcoming PR?

**Comment by cdavis5e** [comment]
This is the issue explaining the upcoming PR.
