### ISSUE TITLE
Reflection gives incorrect size of std140 uniform buffer

### ISSUE THREAD

**Issue by wolfpld** [KhronosGroup/SPIRV-Cross#2057]
Hi,
I believe the uniform buffer size returned by spirv-cross reflection facilities is not conformant to the std140 specification.

The following test code will print uniform buffer sizes in a shader:

```c++
#include <stdio.h>
#include "SPIRV-Cross/spirv_glsl.hpp"

int main()
{
    FILE* f = fopen( "shader.spv", "rb" );
    fseek( f, 0, SEEK_END );
    const auto fsz = ftell( f );
    fseek( f, 0, SEEK_SET );
    auto buf = new char[fsz];
    fread( buf, 1, fsz, f );
    fclose( f );

    spirv_cross::CompilerGLSL compiler( (uint32_t*)buf, fsz/4 );
    auto res = compiler.get_shader_resources();
    for( auto& ub : res.uniform_buffers )
    {
        const auto size = compiler.get_declared_struct_size( compiler.get_type( ub.base_type_id ) );
        printf( "Size: %zu\n", size );
    }
}
```

Let's now declare a simple vertex shader:

```glsl
#version 450

layout(std140, binding = 0) uniform TEST
{
    float val;
};

void main() {}
```

Executing the code will print the following result:

```
[14:09 wolf@mimir:~/test]% clang++ test.cpp SPIRV-Cross/build/libspirv-cross-*
[14:09 wolf@mimir:~/test]% ./a.out
Size: 4
```

OpenGL 4.6 Core [specification](https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf) section 7.6.2.2 gives the following rule to obey:

> 9. If the member is a structure, the base alignment of the structure is *N*, where *N* is the largest base alignment value of any of its members, and rounded up to the base alignment of a `vec4`. (...)

This alone is not actionable, as there are no structures in the uniform block declared in the shader above. However, careful reading of the specification reveals another requirement:

> The members of a top-level uniform block are laid out in buffer storage by treating the uniform block as a structure with a base offset of zero.

So, the whole uniform block is actually a structure and it must conform to the rule 9 quoted above. Hence, the uniform block size should be 16 ("rounded up to the base alignment of a `vec4`").

This is perhaps spelled out in a less obfuscated way in the original specification of the [ARB_uniform_buffer_object](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_uniform_buffer_object.txt) extension:

>  For uniform blocks laid out according to these rules, the minimum buffer object size returned by the UNIFORM_BLOCK_DATA_SIZE query is derived by taking the offset of the last basic machine unit consumed by the last uniform of the uniform block (including any end-of-array or end-of-structure padding), adding one, and rounding up to the next multiple of the base alignment required for a vec4.

If you would perform such a query on the uniform block specified in the shader above, you would get the value 16. This is quite important, if you consider section 7.6.3 of the OpenGL specification, which states:

> When executing shaders that access uniform blocks, the binding point corresponding to each active uniform block must be populated with a buffer object with a size no smaller than the minimum required size of the uniform block (the value of `UNIFORM_BLOCK_DATA_SIZE`). (...) If any active uniform block is not backed by a sufficiently large buffer object, the results of shader execution may be undefined or modified, as described in section 6.4.

If an application uses spirv-cross reflection functionality to determine its uniform buffer size requirements, it may in effect be relying on undefined behavior. While most graphics drivers don't care about this, some WebGL implementations actually do, in which case the result of rendering is a black screen.

**Comment by wolfpld** [comment]
According to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/623, this requirement is not present in Vulkan specification.

**Comment by HansKristian-Work** [comment]
> So, the whole uniform block is actually a structure and it must conform to the rule 9 quoted above. Hence, the uniform block size should be 16 ("rounded up to the base alignment of a vec4").

I don't think so. The SPIR-V itself has no knowledge of the packing standard being used. Rounding up the size of the UBO itself is left to alignment requirements of the UBO. In Vulkan, if the implementation has a minUniformBufferOffsetAlignment of 16, this enforces the size alignment, so this UBO would have to be bound with range of 16.

It is ambiguous in the SPIR-V if the layout is std140 or std430 or scalar, so returning 16 would be a bug if the intention was std430. SPIRV-Cross will emit packing standard based on a pattern match. For UBOs, std140 is emitted if it ends up conforming to the SPIR-V decorations, if that cannot work, it will try std430, if that doesn't work, scalar, etc.

> If an application uses spirv-cross reflection functionality to determine its uniform buffer size requirements, it may in effect be relying on undefined behavior.

The application can just round up the size to conform to host API requirements. This is a GL requirement, not a Vulkan one.

**Comment by wolfpld** [comment]
> It is ambiguous in the SPIR-V if the layout is std140 or std430 or scalar, so returning 16 would be a bug if the intention was std430. SPIRV-Cross will emit packing standard based on a pattern match. For UBOs, std140 is emitted if it ends up conforming to the SPIR-V decorations, if that cannot work, it will try std430, if that doesn't work, scalar, etc.

So basically, the `std140` layout declaration from shader is not present in the bytecode?

**Comment by HansKristian-Work** [comment]
> So basically, the `std140` layout declaration from shader is not present in the bytecode?

Correct, the SPIR-V does not know or care about those. Layout requirements is a GLSL construct in GL, and in Vulkan, there are just rules specifying how Offset, ArrayStride and MatrixStride can be declared.

**Comment by wolfpld** [comment]
Ok, thanks, that's a bit disappointing, but things are what they are.
