### ISSUE TITLE
[GLSL] HLSL Texture2D in compute shader uses texelFetch instead of imageLoad

### ISSUE THREAD

**Issue by vkaytsanov** [KhronosGroup/SPIRV-Cross#2059]
The following HLSL code, compiled by using the C++ API:
```HLSL
StructuredBuffer<float> InputFilterMatrix : register (t0);
Texture2D InputImage : register(t1);
RWTexture2D<float4> TextureOut : register(u0);

[numthreads(16, 16, 1)]
void CSMain(uint2 dt : SV_DispatchThreadID)
{
    uint matrixRows = 3;
    float width = 1024;
    float height = 1024;

    uint2 filterStart = uint2(dt - matrixRows / 2);
    uint2 samplingPoint = uint2(fmod(filterStart, float2(width, height)));
    float4 color = InputImage.Load(uint3(samplingPoint, 0));

    TextureOut[dt] = color;
}

```
which gets compiled to GLSL, with option `vulkan_semantics` and not running `build_dummy_sampler_for_combined_images`:
```GLSL
#version 460
#extension GL_EXT_samplerless_texture_functions : require
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 1) uniform texture2D InputImage;
layout(set = 0, binding = 0, rgba32f) uniform image2D TextureOut;

void main()
{
    vec2 _30 = vec2(gl_GlobalInvocationID.xy - uvec2(1u));
    ivec3 _36 = ivec3(uvec3(uvec2(_30 - vec2(1024.0) * trunc(_30 / vec2(1024.0))), 0u));
    imageStore(TextureOut, ivec2(gl_GlobalInvocationID.xy), texelFetch(InputImage, _36.xy, _36.z));
}
```

My questions:
1. Can the compiled `HLSL code` with only `Texture2D` be translated to `readonly image2D`, which uses `imageLoad` if there is no `SamplerState` declared, even if `build_dummy_sampler_for_combined_images` is called. Its weird on the other GPU APIs to bind only a single texture, but on OpenGL to be required to bind and a sampler.
2. If no, is this a bug or needs to be implemented? If the latter, is this commit the best way to follow-up for a solution on my side - https://github.com/KhronosGroup/SPIRV-Cross/pull/1308 ?
3. Can the extension requirement be removed?

Desired output:
```GLSL
#version 460

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform readonly image2D u_InputImage;
layout(rgba8, binding = 1) uniform writeonly image2D u_OutputImage;

layout(std430, binding = 0) restrict readonly buffer u_InputMatrix
{
	float inputMatrix[];
};

void main()
{
	int matrixRows = 3;
	int width = 1024;
        int height = 1024;
	ivec2 pixelPosition = ivec2(gl_GlobalInvocationID.xy);
	
	ivec2 filterStart = (pixelPosition - matrixRows / 2);

        ivec2 samplingPoint = ivec2(mod(filterStart + ivec2(filterX, filterY), ivec2(width, height)));
	vec4 color = imageLoad(u_InputImage, samplingPoint);

	imageStore(u_OutputImage, pixelPosition, color);
}

```

**Comment by HansKristian-Work** [comment]
Texture2D is an SRV, meaning it is a sampled image, not a storage image. texelFetch is therefore correct.

> Can the extension requirement be removed?

Why? This extension is only used in Vulkan GLSL.

When targeting normal GLSL the output becomes:

```
#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rgba32f) uniform writeonly image2D TextureOut;

// From the automatic combining stuff. To fixup bindings and names, see the reflection API.
uniform sampler2D SPIRV_Cross_CombinedInputImageSPIRV_Cross_DummySampler;

void main()
{
    vec2 _30 = vec2(gl_GlobalInvocationID.xy - uvec2(1u));
    ivec3 _36 = ivec3(uvec3(uvec2(_30 - vec2(1024.0) * trunc(_30 / vec2(1024.0))), 0u));
    imageStore(TextureOut, ivec2(gl_GlobalInvocationID.xy), texelFetch(SPIRV_Cross_CombinedInputImageSPIRV_Cross_DummySampler, _36.xy, _36.z));
}
```

The sampler-less texture is automatically combined with a dummy sampler to make it work.

> Its weird on the other GPU APIs to bind only a single texture, but on OpenGL to be required to bind and a sampler.

That's just OpenGL being weird. IIRC, you're not required to bind samplers explicitly, a texture has its own internal one.

> readonly image2D, which uses imageLoad if there is no SamplerState declared

This breaks on many GPUs. Images require explicit format to work with read, but texelFetch does not require that. This is not feasible.

**Comment by vkaytsanov** [comment]
Thank you very much for the clarifications and for the new knowledge. Didn't know textures in OpenGL have internal sampler
