### ISSUE TITLE
HLSL's SampleCmpLevelZero is not translated correctly to GLSL when using a SamplerComparisonState and a Texture2DArray

### ISSUE THREAD

**Issue by Loki7979** [KhronosGroup/SPIRV-Cross#207]
Hi,

In my HLSL fragment shader, I am sampling a Texture2DArray using SamplerCmpLevelZero in order to perform a 2x2 hardware shadow PCF filtering :

```
SamplerComparisonState shadowSamplerPCF;
Texture2DArray _shared_shadowMap;

float comparisonResult = _shared_shadowMap.SampleCmpLevelZero(shadowSamplerPCF, float3(texCoords, cascadeIndex), fragDepth);	
```

Spirv-Cross translates these code lines to GLSL this way :

```
uniform sampler2DArrayShadow _shared_shadowMap;

vec4 _587 = vec4(vec3(texCoords, float(cascadeIndex)), fragDepth);
float comparisonResult = textureLod(_shared_shadowMap, vec4(_587.xyz, _587.w), 0.0);
```
            
But when compiling the 	GLSL shader (windows platform) the following error is shown :

error C1115: unable to find compatible overloaded function "textureLod(sampler2DArrayShadow, vec4, float)"

If you take a look at the OpenGL reference ( https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureLod.xhtml ) textureLod doesn't accept sampler2DArrayShadow as parameter.

Please, could you help me with this? I really need to use SamplerCmpLevelZero in my HLSL shader

Thank you very much

**Comment by HansKristian-ARM** [comment]
Ah, yes. The elusive textureLod with sampler array shadow, let me guess cascaded shadow mapping? :p
I think I'll have to translate this to textureGrad with static gradient == 0.0 as a special case, as I've seen glitches on desktop with plain texture() when array slice diverges ...

I'll implement it as soon as I can.

**Comment by Loki7979** [comment]
You're right, I am using cascaded shadow maps on the shader :-)

I am glad that you seem to know which would be the correct translation in this case. If you need to see more shader code just let me know.

Please keep me informed about the progress fixing this issue.

Thanks for the support! :-)

**Comment by HansKristian-ARM** [comment]
I've run into the problem before in my own projects, will probably have a fix tomorrow.

**Comment by Loki7979** [comment]
that's really fast support service! :-)

Thank you very much!

**Comment by HansKristian-ARM** [comment]
Merged on master.

**Comment by Loki7979** [comment]
Fantastic. Now the glsl shader is compiled correctly :-)

I still have to test cascaded shadow maps when running the app using OpenGL. I will tell you later if works ok

Thanks for the help :-)

**Comment by Loki7979** [comment]
Works as expected. Good work!

Thanks again
