### ISSUE TITLE
[MSL] Generated shader can include MSL keywords, which results in Metal compiler error

### ISSUE THREAD

**Issue by Devaniti** [KhronosGroup/SPIRV-Cross#2073]
Assume you have such shader (HLSL, later compiled to SPIR-V with DXC and finally cross-compiled to MSL)

```
[numthreads(1,1,1)]
void CS_Sample(int3 DTid : SV_DispatchThreadID)
{
    uint3 thread = DTid;
    ...
}
```

SPIRV-Cross succeds to output MSL for that shader, but it is not valid MSL
Here's how Metal compiler fails to compile that:
```
file.metal:4:18: error: expected unqualified-id
    uint3 thread = uint3(DTid);
```
This is due to fact that `thread` is keyword in MSL (but not in original HLSL shader)

SPIRV-Cross needs to patch names that collide with keywords such as `thread` so resulting shader is correct, or error out during SPIR-V processing and not produce invalid MSL

**Comment by HansKristian-Work** [comment]
Can you reproduce this on master? Because this shader:

```
#version 450

layout(set = 0, binding = 0) buffer BUF
{
	vec4 thread_foo;
};

void main()
{
	vec4 thread = thread_foo;
	thread += 1.0;
}
```

converts to

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct BUF
{
    float4 thread_foo;
};

kernel void main0(device BUF& _12 [[buffer(0)]])
{
    float4 thread0 = _12.thread_foo;
    thread0 += float4(1.0);
}
```

**Comment by Devaniti** [comment]
Can confirm that on latest master this issue no longer happens.
Thanks!
