### ISSUE TITLE
spirv_msl makes unnecessary type conversion between half and full precision type. (ex. half3(float3(half3(a))) + b )

### ISSUE THREAD

**Issue by SungJJinKang** [KhronosGroup/SPIRV-Cross#2082]
spirv_msl makes unnecessary type conversion between half and full precision type. like half3(float3(half3(a))) + b.

I attached some example..

`
float4 _339 = float4(half4(float4(half4(spvFAdd(half3(float3(half3(MobileBasePass.MobileBasePass_Fog_ExponentialFogColorParameter.xyz))) * (half(1.0) - _329), select(_315, half3(half(0.0)), bool3(_326))), _329))));
...
half3 _183 = half3(float3(0.0));
...
half _329 = _326 ? half(1.0) : half(fast::max(fast::clamp(exp2(-spvFMul(_280, _249)), 0.0, 1.0), float(half(MobileBasePass.MobileBasePass_Fog_ExponentialFogColorParameter.w))));
`

In our case, this caused precision problem.
![face_material](https://user-images.githubusercontent.com/33873804/211764492-f6201960-2683-4a81-a5cd-0f887f13304e.png)
You can see that the result of operation is different with the one that unnecessary type conversion is removed.

[MobileBasePassVertexShader.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/10390498/MobileBasePassVertexShader.txt)
This shader file is compiled by unreal engine 5.0. ue5 converts hlsl shader code to metal shader code using dxc and spirv-cross ( hlsl -> spirv(by dxc) -> msl(by spirv-cross) ).

**Comment by SungJJinKang** [comment]
I'm sorry for that. I attached it.
[Metal.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/10397633/Metal.txt)
[HLSL.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/10397634/HLSL.txt)
[SPIRV.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/10397636/SPIRV.txt)

**Comment by HansKristian-Work** [comment]
The attached SPIR-V only seems to contain Vertex stage, but the screenshot points to Fragment code.

**Comment by SungJJinKang** [comment]
@HansKristian-Work 

Oh. I'm sorry for that. But you can see the same problem from attached Metal.txt file.

At line 267 : half _329 = _326 ? half(1.0) : half(fast::max(fast::clamp(exp2(-spvFMul(_280, _249)), 0.0, 1.0), **float(half(MobileBasePass.MobileBasePass_Fog_ExponentialFogColorParameter.w))**));

At line 317 : out.out_var_COLOR0 = **half4(float4(half4(in.in_var_ATTRIBUTE3)))**;

**Comment by SungJJinKang** [comment]
You gave me a hit. As i see the spirv with spirv visualizer, it looks spirv code has unnecessary type conversion codes. Thanks.

**Comment by SungJJinKang** [comment]
I'm sorry for bothering. hlsl code already has unnecessary type conversion
