### ISSUE TITLE
[GLSL] Incorrect mul-assign generated for Fma in version 310 es 

### ISSUE THREAD

**Issue by Frizi** [KhronosGroup/SPIRV-Cross#2129]
I have an input spir-v with following disassembly:
```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %a
               OpSource ESSL 310
               OpName %main "main"
               OpName %a "a"
               OpDecorate %a Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
%_ptr_Output_float = OpTypePointer Output %float
          %a = OpVariable %_ptr_Output_float Output
    %float_5 = OpConstant %float 5
    %float_2 = OpConstant %float 2
    %float_1 = OpConstant %float 1
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpStore %a %float_5
         %10 = OpLoad %float %a
         %14 = OpExtInst %float %1 Fma %10 %float_2 %float_1
               OpStore %a %14
               OpReturn
               OpFunctionEnd
```

Spirv-cross is generating following glsl from it:

```glsl
#version 310 es

layout(location = 0) out float a;

void main()
{
    a = 5.0;
    a *= 2.0 + 1.0;
}
```

The generated mul-assign expression is incorrect, as it doesn't preserve the semantics of `Fma` instruction. The addition should happen after multiplication, but in generated code that order is reversed. I would expect output like this:
```glsl
    a = a * 2.0 + 1.0;
```

This is generated incorrectly only if `Fma` result is subsequently loaded into the source of its first operand, like in the provided spirv.
```
         %10 = OpLoad %float %a
         %14 = OpExtInst %float %1 Fma %10 %float_2 %float_1
               OpStore %a %14
```

My shader pipeline feeds source glsl shaders through chain of glslc -> spirv-opt -> spirv-cross. This spir-v file has been generated from minimal source vertex shader like this:
```glsl
#version 310 es
layout(location=0) out float a;
void main () {
    a = 5.0;
    a = a * 2.0 + 1.0;
}
```

**Comment by HansKristian-Work** [comment]
Funny bug ._. Pretty sure it's the a = a * 2.0 part that thinks it can optimize to *= but it needs to consider that the expression must be enclosed.

**Comment by HansKristian-Work** [comment]
Ye, I'll look into it today. It's a pretty serious bug.

**Comment by wdanilo** [comment]
@HansKristian-Work thank you so much for fixing it so fast. We are really thankful for your help!
