### ISSUE TITLE
opengl es cross compil problem

### ISSUE THREAD

**Issue by laurentcau** [KhronosGroup/SPIRV-Cross#2136]
Hi,

I'm trying to cross compil my glsl 300 shader to glsl 300 **es** version because of the different behavior on the input parameters.
(glsl 300 es doesn't ignore unused input parameters.)
I have a problem with one of my uniform definition that is not converted in the same way in vertex and fragment shaders.

- Common source shader:

```
struct SMaterialUniforms1 { 
	int materialType; 
	float LuminousFactor; 
};

uniform AnimationFxUniforms_Bloc1 {
SMaterialUniforms1 g_material1;
};
```
- Vertex Shader result:
```
struct SMaterialUniforms1 { 
	int materialType; 
	float LuminousFactor; 
};

layout(std140) uniform AnimationFxUniforms_Bloc1
{
    SMaterialUniforms1 g_material1;
} _326;
 ```
 - Fragment Shader result:
 ```
 struct SMaterialUniforms1
{
    int materialType;
	highp float LuminousFactor;
}

struct SMaterialUniforms1_1
{
    int materialType;
	highp float LuminousFactor;
}

layout(std140) uniform AnimationFxUniforms_Bloc1
{
    SMaterialUniforms1_1 g_material1;
} _1779;
 ```
As you can see struct SMaterialUniforms1 is duplicated in fragment shader and shader fail to load at runtime with error:
Structure names of uniform block 'AnimationFxUniforms_Bloc1' member 'AnimationFxUniforms_Bloc1.g_material1' differ between VERTEX and FRAGMENT shaders.

Is there any fix or workaround for this issue ?
Thanks

**Comment by HansKristian-Work** [comment]
Do you have a concrete vertex SPIR-V and fragment SPIR-V to test with?

**Comment by laurentcau** [comment]
Sorry my example was not correct and I identified what was wrong.
The issue is with bool type inside the structure.
bool type are not 'real' type for uniforms, they are treated as uint.
So the struct is duplicated with bool on one side and uint on the other side.
I don't know if the problem comes from glslangValidator or spirv-cross.
I fixed the issue by explicitly using uint for my bool values.
The downside is that I have to cast each of them explicitly since opengl es doesn't allow to test with uint:
```
struct SMaterialUniforms1 { 
	int materialType; 
	uint myBool; 
};
if (bool(myBool)) ....
```
vs
```
struct SMaterialUniforms1 { 
	int materialType; 
	bool myBool; 
};
if (myBool) ....
```

**Comment by HansKristian-Work** [comment]
You can use `int` instead to make it more compatible.

**Comment by laurentcau** [comment]
glslangValidator generates error: "boolean expression expected"

**Comment by HansKristian-Work** [comment]
You have to use `intValue != 0` when using ints.

**Comment by HansKristian-Work** [comment]
Doesn't seem like there is anything actionable here. Closing.
