### ISSUE TITLE
[MSL] How to record image binding changes from GLSL->SPIRV-MSL

### ISSUE THREAD

**Issue by pengfei666** [KhronosGroup/SPIRV-Cross#2140]
HI, I have below glsl code
```
layout (binding = 0, rgba8) uniform writeonly image2D u_texture_out;

layout(binding = 0) uniform sampler2D u_tex_sampler_0;
layout(binding = 1) uniform sampler2D u_tex_sampler_1;
```

the generated MSL code is:
```
texture2d<float> u_tex_sampler_1 [[texture(0)]], 
texture2d<float> u_tex_sampler_2 [[texture(1)]], 
texture2d<float, access::write> u_texture_out [[texture(2)]], 
sampler u_tex_sampler_1Smplr [[sampler(0)]], 
sampler u_tex_sampler_2Smplr [[sampler(1)]], 
```

Note: the binding number of `u_texture_out` changes from 0 to 2.

I want to know where I can get these changes when I am using CLI tool?  I need to record these changes to know binding 0 is mapped to 2 when I set a texture to `u_texture_out`? 

Thanks.

**Comment by HansKristian-Work** [comment]
I think you want

```
	// This must only be called after a successful call to CompilerMSL::compile().
	// For a variable resource ID obtained through reflection API, report the automatically assigned resource index.
	// If the descriptor set was part of an argument buffer, report the [[id(N)]],
	// or [[buffer/texture/sampler]] binding for other resources.
	// If the resource was a combined image sampler, report the image binding here,
	// use the _secondary version of this call to query the sampler half of the resource.
	// If no binding exists, uint32_t(-1) is returned.
	uint32_t get_automatic_msl_resource_binding(uint32_t id) const;
```
The ID should be the resource.id from reflection.

**Comment by HansKristian-Work** [comment]
Not really. My suggestion is making your own simple toolchain using the API to emit the information you need. Every user of the CLI will have slightly different need, and I cannot cater to all such use cases at the same time. You could take the CLI as-is and remove all the stuff you don't need and emit whatever reflection information your engine in particular needs.

Binding models are very complicated and completely different in each engine, so I'd suggest going that route.
