### ISSUE TITLE
Metal output does not compile in sample using PhysicalStorageBuffer pointers

### ISSUE THREAD

**Issue by Hugobros3** [KhronosGroup/SPIRV-Cross#2145]
MoltenVK fails to run the [aobench](https://github.com/Hugobros3/shady/tree/master/samples/aobench) sample from shady. I tracked down the issue and was able to minimize the source code down to this:
```
; SPIR-V
; Version: 1.5
; Generator: Khronos; 35
; Bound: 5550
; Schema: 0
               OpCapability Int8
               OpCapability Int64
               OpCapability Int64
               OpCapability Shader
               OpCapability PhysicalStorageBufferAddresses
               OpExtension "SPV_KHR_physical_storage_buffer"
               OpMemoryModel PhysicalStorageBuffer64 Simple
               OpEntryPoint GLCompute %main "main" %globals
               OpExecutionMode %main LocalSize 16 16 1

               OpDecorate %ptr_uchar ArrayStride 8
               OpDecorate %ptr_uint ArrayStride 8
               OpDecorate %ptr_array_t ArrayStride 8
               OpDecorate %array_t ArrayStride 1
               OpDecorate %struct_t Block
               OpMemberDecorate %struct_t 0 Offset 0
               OpMemberDecorate %struct_t 1 Offset 8
               OpDecorate %ptr_struct ArrayStride 32
               OpDecorate %globals DescriptorSet 0
               OpDecorate %globals Binding 0

       %void = OpTypeVoid
      %uchar = OpTypeInt 8 0
       %uint = OpTypeInt 32 0
      %ulong = OpTypeInt 64 0
       %bool = OpTypeBool

   %ulong_12 = OpConstant %ulong 12
     %uint_0 = OpConstant %uint 0
     %uint_1 = OpConstant %uint 1
     %uint_2 = OpConstant %uint 2
   %uchar_69 = OpConstant %uchar 69
   %ulong_16 = OpConstant %ulong 16

   %ptr_uint = OpTypePointer PhysicalStorageBuffer %uint
  %ptr_uchar = OpTypePointer PhysicalStorageBuffer %uchar

    %array_t = OpTypeArray %uchar %ulong_12
%ptr_array_t = OpTypePointer PhysicalStorageBuffer %array_t

   %struct_t = OpTypeStruct %ptr_uchar %ptr_array_t
 %ptr_struct = OpTypePointer StorageBuffer %struct_t

    %void_fn = OpTypeFunction %void
      %foo_t = OpTypeFunction %ptr_uint

%ptr_uchararr_sb = OpTypePointer StorageBuffer %ptr_array_t

    %globals = OpVariable %ptr_struct StorageBuffer

        %foo = OpFunction %ptr_uint None %foo_t
  %foo_entry = OpLabel
       %lea2 = OpAccessChain %ptr_uchararr_sb %globals %uint_1
    %loaded2 = OpLoad %ptr_array_t %lea2
       %cast = OpConvertPtrToU %ulong %loaded2
   %adjusted = OpIAdd %ulong %cast %ulong_16
      %cast2 = OpConvertUToPtr %ptr_uint %adjusted
               OpStore %cast2 %uint_1 Aligned 4 ; eliminating this store generates different code and the problem disappears
               OpReturnValue %cast2
               OpFunctionEnd

       %main = OpFunction %void None %void_fn
 %main_entry = OpLabel
    %nothing = OpFunctionCall %ptr_uint %foo
               OpReturn
               OpFunctionEnd
```

This fails to compile like so:
```
out.metal:165:39: error: member reference type 'device spvUnsafeArray<uchar, 12> *' (aka 'device spvUnsafeArray<unsigned char, 12> *') is a pointer; did you mean to use
      '->'?
    spvArrayCopyFromDeviceToStack1(_26.elements, _2._m1);
                                   ~~~^
                                      ->
out.metal:165:5: error: no matching function for call to 'spvArrayCopyFromDeviceToStack1'
    spvArrayCopyFromDeviceToStack1(_26.elements, _2._m1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
out.metal:138:13: note: candidate template ignored: could not match 'const device T [A]' against 'device uchar *device' (aka 'device unsigned char *device')
inline void spvArrayCopyFromDeviceToStack1(thread T (&dst)[A], device const T (&src)[A])
            ^
```

I've had a look in SPIRV-Cross source and I found that the `SPIRType` seems a bit suspect: The way I understand it, there is no way to disambiguate between a pointer to an array, and an array of pointers, which might be related.

**Comment by HansKristian-Work** [comment]
> The way I understand it, there is no way to disambiguate between a pointer to an array, and an array of pointers, which might be related.

Yes, at the time SPIRType was made there was no BDA, so this confusion is there and it's a bit hard to untangle that now without a rewrite.

There is a way to disambiguate though, it requires looking at the parent type. E.g. if parent type's pointer depth changes, then type is a pointer.

**Comment by HansKristian-Work** [comment]
What's likely going wrong is that it think storing a pointer-to-array is actually storing an array, so it ends up hitting the array copy wrapper stuff.

**Comment by HansKristian-Work** [comment]
```
               OpDecorate %ptr_uchar ArrayStride 8
               OpDecorate %ptr_uint ArrayStride 8
               OpDecorate %ptr_array_t ArrayStride 8
```
These array strides are confusing me. What are they trying to accomplish in this shader?

**Comment by Hugobros3** [comment]
It's a workaround, it appears spirv-cross was incorrectly using ArrayStride to lay out the structs, or at least was erroring out while saying it attempted to do so. See https://github.com/KhronosGroup/SPIRV-Cross/issues/2146

**Comment by Hugobros3** [comment]
> There is a way to disambiguate though, it requires looking at the parent type. E.g. if parent type's pointer depth changes, then type is a pointer.

Sure but that's incredibly error-prone. From my own experience writing compilers, I'm a bit confused as to why SPIRType was written that way, instead of just matching spirv-s grammar 1:1. I might be interested in contributing to a rewrite effort, since this issue (and related) is blocking me from supporting Apple devices properly.

**Comment by HansKristian-Work** [comment]
The fix is probably not that hard.

**Comment by HansKristian-Work** [comment]
GLSL output now looks like:

```
#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_8bit_storage : require
#if defined(GL_ARB_gpu_shader_int64)
#extension GL_ARB_gpu_shader_int64 : require
#else
#error No extension available for 64-bit integers.
#endif
#extension GL_EXT_buffer_reference : require
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(buffer_reference) buffer uint8_tPointer
{
    uint8_t value;
};

layout(buffer_reference, buffer_reference_align = 4) buffer uintPointer
{
    uint value;
};

layout(buffer_reference, buffer_reference_align = 1) buffer uint8_t12_Pointer
{
    uint8_t value[12];
};

layout(set = 0, binding = 0, std430) buffer _7_2
{
    uint8_tPointer _m0;
    uint8_t12_Pointer _m1;
} _2;

uintPointer _23()
{
    uint8_t12_Pointer _26 = _2._m1;
    uintPointer _29 = uintPointer(uint64_t(_26) + 16ul);
    _29.value = 1u;
    return _29;
}

void main()
{
    uintPointer _31 = _23();
}
```

MSL looks like:

```
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct _7
{
    device uchar* _m0;
    device uchar* _m1;
};

static inline __attribute__((always_inline))
device uint* _23(device _7& _2)
{
    device spvUnsafeArray<uchar, 12>* _26 = _2._m1;
    device uint* _29 = reinterpret_cast<device uint*>(reinterpret_cast<ulong>(_26) + 16ul);
    *_29 = 1u;
    return _29;
}

kernel void main0(device _7& _2 [[buffer(0)]])
{
    device uint* _31 = _23(_2);
}
```

_m1 one seems to be missing the pointer to array thing. Probably related to the spvUnsafeArray<T> mess ...

**Comment by HansKristian-Work** [comment]
The PR should fix this shader. Hopefully that resolves the issue for now.

**Comment by Hugobros3** [comment]
Thanks. My prior comment about this being error-prone does not concern the fix in this particular case, but rather it will ultimately be simpler to have the representation of types structurally match SPIRV's, and then backend code can just exhaustively match that representation. Here's an [example](https://github.com/Hugobros3/shady/blob/master/src/shady/emit/c/emit_c_signatures.c#L97).

I understand it's probably a tall order to refactor spirv-cross to adopt a similar type representation, but I think it's worth it for the long-term maintainability. I'd be glad to contribute to such an effort.

As for whether this problem is fixed, it indeed does fix the reproduction, but my overall shader still failed to compile when I gave it a try on Wednesday. I see there's been another addition, I'll get back to this with a more concrete answer, and if appropriate, another reproduction.

**Comment by HansKristian-Work** [comment]
> I understand it's probably a tall order to refactor spirv-cross to adopt a similar type representation

The SPIRType is exposed in the API, so changing everything would be problematic. However, it's possible to work towards a refactor where all internal usage of SPIRType::pointer, SPIRType::pointer_depth and SPIRType::array is removed, and force them to go through helper functions. That might be viable.

It's also potentially possible to add a field to SPIRType which opcode it was created from (OpTypePointer vs OpTypeArray etc). However, SPIRType is sometimes synthesized inline (which is where aggregated SPIRType happened to help a lot actually despite being awkward), so ensuring all that works is non-trivial, but definitely possible.

I'm still interested in seeing concrete cases where things break though.
