### ISSUE TITLE
Incorrect handling of ArrayStride on pointers

### ISSUE THREAD

**Issue by Hugobros3** [KhronosGroup/SPIRV-Cross#2146]
Related to https://github.com/KhronosGroup/SPIRV-Cross/issues/2145:

That example has all the pointer types with array stride of 8. I had to do this to get that far, but this is incorrect according to the SPIR-V specification:

> If an array-element pointer is derived from an array (e.g., using OpAccessChain), and the resulting element-pointer type is decorated with ArrayStride, its Array Stride must match the Array Stride of the array’s type. If the array’s type is not decorated with ArrayStride, the derived array-element pointer also must not be decorated with ArrayStride.

If I do this "correctly" (1), using the stride of the pointee I emit the following (see linked issue for the rest of the sample):

```
OpDecorate %ptr_uchar ArrayStride 1
OpDecorate %ptr_uint ArrayStride 8
OpDecorate %ptr_array_t ArrayStride 12
```

I get this error:

> SPIRV-Cross threw an exception: Found a buffer packing case which we cannot represent in MSL.

Exploring this through my debugger, it seems that SPIRV-Cross is again confused about what is is emitting and thinks it's emitting an array, when it's really emitting a pointer to an array.

If I don't decorate any pointer types with `ArrayStride` (which the spec allows, see below), I get this different error: 

> SPIRV-Cross threw an exception: Struct member does not have ArrayStride set

---

(1): That's still not correct, technically! The spec says the following about `ArrayStride`:

> Apply to an array type to specify the stride, in bytes, of the array’s elements. Can also apply to a pointer type to an array element. Array Stride is an unsigned 32-bit integer specifying the stride of the array that the element resides in. Must not be applied to any other type.

The first two pointer types hence, should not be annotated at all! This was done to get spirv-cross further along and I encountered the other problems after that.

**Comment by HansKristian-Work** [comment]
This should be fixed on main.

**Comment by HansKristian-Work** [comment]
I think this is fixed. Please open another issue if there are more bugs.
