### ISSUE TITLE
GLSL backend: Allow only certain extensions

### ISSUE THREAD

**Issue by tklajnscek** [KhronosGroup/SPIRV-Cross#2149]
We're targeting WebGL 2.0 (and even 1.0 _sad face_) and we often get GLSL shaders that successfully compile only to turn out they used some extensions that's not available under WebGL or not available on key devices we're targeting.

It would be nice if we could specify which extensions we allow instead of the GLSL compiler automatically using any extensions it knows about. I would like the compilation to fail with some descriptive error (or at least something along the lines of `Shader would require extension EXT_BLABLA, but it's not available.`)

Alternatively, we can expose the list of actually used extensions (in the C API as well) and we can check it against our whitelist after compilation succeeds.

Currently, I resorted to parsing the output for `#extension BLA : require` but it feels like there's a better way.

I volunteer to add this, but wanted to start a discussion about any preferences on what has the best shot at getting upstreamed...

**Comment by HansKristian-Work** [comment]
An API could be added where we would return all enabled extensions which are enabled without an ifdef check. Then you could do whatever you'd need with that information. Would that be enough?

**Comment by tklajnscek** [comment]
Yeah, that would work great and should be a very minor change.

**Comment by HansKristian-Work** [comment]
Merged.
