### ISSUE TITLE
Parse SPIR-V -> Modify -> Write SPIR-V?

### ISSUE THREAD

**Issue by unvestigate** [KhronosGroup/SPIRV-Cross#2150]
Hi,

Is it possible to load a shader module in SPIR-V format, set/unset some decorations and then write the result back out to a file, in SPIR-V format? It looks like I should be able to just create a Parser and feed it the data, then call set_member_decoration() etc. on the ParsedIR, but I am unsure if it is possible to go the other way, ie. back to SPIR-V using the library.

Thanks!

**Comment by HansKristian-Work** [comment]
No, this is not supported. There is limited support for querying byte offsets of those decoration, so it's possible to patch it by hand. SPIR-V -> SPIR-V transformations is the domain of SPIRV-Tools.

**Comment by unvestigate** [comment]
Okay, thanks.
