### ISSUE TITLE
Support constant buffer register names for HLSL Shader Model 5.1

### ISSUE THREAD

**Issue by austinEng** [KhronosGroup/SPIRV-Cross#216]
According to https://msdn.microsoft.com/en-us/library/windows/desktop/dn899207(v=vs.85).aspx, constant buffer views (CBV), must use the logical register space "b" whereas in previous versions it could be "c" or "b"

**Comment by HansKristian-ARM** [comment]
So the implementation would look something like

if (SM < 5.1) use cbuffer; else ConstantBuffer; ?

**Comment by austinEng** [comment]
Yes, but I think there would also need to be a change here https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.cpp#L1589

Shader model 5.1 now uses b0, b1, b2, b3... instead of c0, c1, c2 ,c3...

**Comment by HansKristian-ARM** [comment]
Alright, seems simple enough.

**Comment by HansKristian-ARM** [comment]
Implemented here: https://github.com/KhronosGroup/SPIRV-Cross/pull/218
Does this work for you?

**Comment by austinEng** [comment]
The constant buffers do work, thank you. But I apologize I should have been more clear. I believe push constants have also changed in 5.1 to be b0, b1, b2, b3... instead of c0, c1, c2 ,c3...

**Comment by HansKristian-ARM** [comment]
Fixed the push constant buffers, thanks. Merged.
