### ISSUE TITLE
add rust support

### ISSUE THREAD

**Issue by xcloudplatform** [KhronosGroup/SPIRV-Cross#2164]

**Comment by grovesNL** [comment]
There are Rust bindings in the crate [spirv_cross](https://github.com/grovesNL/spirv_cross) and an alternative pure Rust shader translator in the crate [naga](https://github.com/gfx-rs/naga)

**Comment by xcloudplatform** [comment]
would it be beneficial to provide NLP LLM API to the spirv_cross/naga via
HTTP interface?
