### ISSUE TITLE
LINK problem

### ISSUE THREAD

**Issue by Kir1n** [KhronosGroup/SPIRV-Cross#2173]
I am using cmake to build my project, vcpkg to install spirv-cross, I can include the head file in my code, but when I build it, it says:

...
(the errors are like that)
E:\0Study\cyrenderer\out\build\x64-debug\cyrenderer\1main.cpp.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl spirv_cross::CompilerGLSL::cast_to_builtin_store(unsigned int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,struct 
...
 fatal error LNK1120: 54 unresolved externals

I am new in using Cmake, this is  some relative settings:

```
find_package(spirv_cross_core  REQUIRED)
find_package(spirv_cross_util  REQUIRED)
target_link_libraries(${TARGET_NAME} PRIVATE spirv-cross-core)
target_link_libraries(${TARGET_NAME} PRIVATE spirv-cross-util)
```

I can see the code in LINK Pass 1: command, I can find spirv-cross-cored.lib, spirv-cross-utild.lib in it. I am totally don't know what to do next, And I have been taken so much time on it. QAQ

**Comment by cdavis5e** [comment]
You also need to link to `spirv-cross-glsl`. Depending on what you're doing, you may need some of the other compiler backends as well.

**Comment by Kir1n** [comment]
thank you so much, It works now :)
