### ISSUE TITLE
GL_EXT_shader_explicit_arithmetic_types produces "???" in HLSL output

### ISSUE THREAD

**Issue by Ravbug** [KhronosGroup/SPIRV-Cross#2181]
My GLSL shader contains the following:
```glsl
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(location = 3) in uint8_t inCastsShadows;    

void main(){
     if (bool(inCastsShaodws)){
          // ...
     }
} 
```
This shader compiles successfully to SPIR-V with glslang. However, when this SPIR-V is passed to SPIRV-Cross in HLSL output mode, it produces "???" everywhere the uint8_t is used
```hlsl
static ??? inCastsShadows;
```
which causes DXC to error.

**Comment by cdavis5e** [comment]
Did you enable shader model 6 output?

**Comment by Ravbug** [comment]
I am setting `options.shader_model` to `64`.
```cpp
spirv_cross::CompilerHLSL hlsl(bin);
	
spirv_cross::CompilerHLSL::Options options;
options.shader_model = opt.version;  // 64
options.point_size_compat = true;
hlsl.set_hlsl_options(options);

return hlsl.compile();
```

**Comment by HansKristian-Work** [comment]
HLSL does not support 8-bit arithmetic, so this isn't unexpected. Does 16-bit work?

**Comment by HansKristian-Work** [comment]
> layout(location = 3) in uint8_t inCastsShadows;    

This isn't even supported in Vulkan. There is 16-bit inputOutputStorage feature, but nothing for 8-bit.

**Comment by Ravbug** [comment]
I was able to resolve the issue on my end with a 32 bit int. I'll take a look at 16 bit, thanks
