### ISSUE TITLE
HLSL's SampleCmpLevelZero not translated correctly to GLSL when using TextureCube

### ISSUE THREAD

**Issue by Loki7979** [KhronosGroup/SPIRV-Cross#219]
Hi,

Some days ago I posted a similar issue because hlsl's SampleCmpLevelZero was not translated correctly to glsl when using Texture2DArray : https://github.com/KhronosGroup/SPIRV-Cross/issues/207

Well, the same issue happens when using hlsl's TextureCube:

HLSL code:

```
TextureCube pointLightShadowMap;
SamplerComparisonState shadowSamplerPCF;

float comparisonResult = pointLightShadowMap.SampleCmpLevelZero(shadowSamplerPCF, lightDir, fragDepth);
```

translated GLSL code:

```
uniform samplerCubeShadow pointLightShadowMap;

vec4 _799 = vec4(lightDir, fragDepth);
float comparisonResult = textureLod(pointLightShadowMap, vec4(_799.xyz, _799.w), 0.0);
```

the glsl shader fails when compiling because textureLod doesn't accept samplerCubeShadow as parameter.

Please, could you perform the same fix in this specific case?

Thank you very much

**Comment by HansKristian-ARM** [comment]
Will do, but might take a while due to holidays.

**Comment by Loki7979** [comment]
No problem, I can wait. ;-)

Thanks for responding and have a nice holidays!

**Comment by HansKristian-ARM** [comment]
Implemented on master.

**Comment by Loki7979** [comment]
Thanks Mr! Works like a charm! :-)
