### ISSUE TITLE
MSL: Unsized texture argument buffer causes syntax error

### ISSUE THREAD

**Issue by inanevin** [KhronosGroup/SPIRV-Cross#2194]
I have just been getting into Metal and testing some basic GLSL shaders to cross-compile to MSL and see how to structure my abstraction in Metal.

Using an unsized array in GLSL `uniform texture2D myTextures[];` will cause uncompilable code if argument buffers are  enabled. More details about the commit hash and spirv_cross settings below.

I see #2112  and other mentioned as related and there has been some improvements made after that issue, but it is unclear to me what is the current state of unsized images in MSL using SPIRV-Cross. If there is an unsupported case, I believe we should be asserting or notifying the users somehow.

Example GLSL:

```
// Omitting unnecessary parts, nonuniform extension etc.

layout (set = 0, binding = 0) uniform SingleUbo
{
    int a;
} singleUbo;
layout (set = 0, binding = 1) uniform sampler singleSampler;
layout (set = 0, binding = 2) uniform texture2D unboundedTexture[];

// in frag main
int index = singleUbo.a;
vec4 col1 = texture(sampler2D(unboundedTexture[index], singleSampler), uv);
```

Generated MSL:

```
// Omitting unnecessary stuff

// Here adds the wrappers correctly
template<typename T>
struct spvDescriptor
{
    T value;
};

template<typename T>
struct spvDescriptorArray
{
    spvDescriptorArray(const device spvDescriptor<T>* ptr) : ptr(ptr)
    {
    }
    const device T& operator [] (size_t i) const
    {
        return ptr[i].value;
    }
    const device spvDescriptor<T>* ptr;
};

// here creating the arg buffer
// not sure about spvDescriptor or spvDescriptorArray?
struct spvDescriptorSetBuffer0
{
    constant SingleUbo* singleUbo [[id(0)]];
    const device spvDescriptor<texture2d<float>>* unboundedTexture [[id(1)]];
    sampler singleSampler [[id(2)]];
};

// In frag main, calling .sample will throw
int index = (*spvDescriptorSet0.singleUbo).a;
float4 col1 = spvDescriptorSet0.unboundedTexture[index].sample(spvDescriptorSet0.singleSampler, in.uv);
```

Notice the usage of **spvDescriptorSet0.unboundedTexture[index].sample**, which will raise:

```
Shader compile error! program_source:53:61: error: no member named 'sample' in 'spvDescriptor<metal::texture2d<float, metal::access::sample, void> >'
float4 col1 = spvDescriptorSet0.unboundedTexture[index].sample(spvDescriptorSet0.singleSampler, in.uv);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

Repo: 54997fb4bc3adeb47b9b9f7bb67f1c25eaca2204 (master)
Compile settings:

```
spirv_cross::CompilerMSL::Options options;
options.set_msl_version(3);
options.argument_buffers_tier = spirv_cross::CompilerMSL::Options::ArgumentBuffersTier::Tier2;
options.force_active_argument_buffer_resources = true;
options.argument_buffers = true;
options.enable_decoration_binding = true;
```

From my understanding, in MSL we could have unsized buffers (ubo/ssbo) by using the pointer syntax, as its what SPIRV-Cross is doing atm. For textures and samplers, afaik we could achieve similar by wrapping them with helper structs? At least for samplers, it wraps them around with **spvDescriptorArray**, but for textures it uses spvDescriptor, which is another question mark for me.

I could always post-process the generated MSL and fix, however would love to see if there is something I am missing and get more information about this, cheers!

**Comment by inanhh** [comment]
I see #2112 and other mentioned as related and there has been some improvements made after that issue, but it is unclear to me what is the current state of unsized images in MSL using SPIRV-Cross. If there is an unsupported case, I believe we should be asserting or notifying the users somehow.

**Comment by Try** [comment]
Hi, @inanevin !

Runtime arrays are implemented over Metal3-style argument buffers; and descriptor sets are also implemented over argument buffers.
However combination of those two is not supported currently. One of options here is to set `options.argument_buffers = false;`

**Comment by inanevin** [comment]
Thanks for the information! Yes currently I am using Metal 1.0 style bindings without argument buffers to also enable runtime arrays, was just second-guessing myself when Spirv-cross compiled the shader without any errors. Closing the issue, thanks for the verification!
