### ISSUE TITLE
Vulkan OpImageRead with (Dim = SubpassData) and Coordinate

### ISSUE THREAD

**Issue by liuzhengwei127** [KhronosGroup/SPIRV-Cross#2195]
In Vulkan documentation, I found this.
![Pasted image 20230829144433](https://github.com/KhronosGroup/SPIRV-Cross/assets/38502813/ebaff9cd-8dd6-4af4-a0ce-1a284d5fc901)
Let's assume that we are trying to use Vulkan Subpasses to prevent data flushing back into main memory from on-chip memory(TBDR architecture in mobile) when we use GBuffer to do Deferred Rendering(two pass: GBuffer pass, Lighting pass).
Does that mean we can access Gbuffer textures with other pixel coordinates?(typically we can just fetch exactly the same position pixel value.)
If so, can other mobile API(metal/openGLES) do anything same?

**Comment by cdavis5e** [comment]
In the actual Vulkan standard [it says this][1]:
> The (u,v) coordinates used for a `SubpassData` **must** be the <id> of a constant vector (0,0), or if a layer coordinate is used, **must** be a vector that was formed with constant 0 for the u and v components

So no. And no, you can't do this with Metal framebuffer fetch or OpenGL ES framebuffer fetch, either.

[1]: https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap51.html#VUID-StandaloneSpirv-SubpassData-04660
