### ISSUE TITLE
Direct SPIRV-Cross build crashes (invalid data in builtin_outputs)

### ISSUE THREAD

**Issue by MarcelPiNacy** [KhronosGroup/SPIRV-Cross#2219]
A manually built SPIRV-Cross library seems to miss initialization of the builtin_outputs variable.
Some info:
 - Compiler: clang-cl 18
 - System: Windows 10
 - Link type: Static from manual build, exceptions and RTTI disabled.

![image](https://github.com/KhronosGroup/SPIRV-Cross/assets/25649656/af996a70-6b1b-4963-b1bc-0098ee429ac8)

This later results in crashes due to the invalid data in builtin_outputs.

**Comment by MarcelPiNacy** [comment]
Nevermind, it seems switching to the library provided by the SDK fixes this.

**Comment by edvn0** [comment]
what do you mean? I'm just now having this issue
