### ISSUE TITLE
[MSL] Incorrect conversion of pointers to arrays.

### ISSUE THREAD

**Issue by VitaliiGitHub** [KhronosGroup/SPIRV-Cross#2221]
Hello, I try to convert OpenCL code to Metal and found out with problem where Metal code not valid after clspv + spirv-cross.
If converting a pointer to a one-dimensional array to a pointer of another type, then in the output code it turns into a two-dimensional array (1D -> 2D, 2D -> 3D, 3D -> 4D).

Example here:
[https://www.dropbox.com/scl/fi/fa8vw5c9f9sx60atl8wrt/cl_to_metal.png?rlkey=q38ntj4a0ss4ra8dm8caw9bwx&dl=0](url)

Code:

```
__local uint block0[256];
__local uint block1[256];
....
*(__local uint*)(block0 + shift) = value;
*(__local uchar*)(block1 + shift) = value;
```
===> 
```
threadgroup uint block0[256];
threadgroup uchar block1[1024];
....
block0[x] = y;
block1[x][y] = z;
```

**Comment by cdavis5e** [comment]
Do you have the SPIR-V that `clspv` produced?

**Comment by VitaliiGitHub** [comment]
You can download files here: [https://www.dropbox.com/scl/fi/w4oeej4y1c8gbni2tlrf9/cl_to_metal.zip?rlkey=ds2h96gror4ud22t5oj1g0f3c&dl=0](url) (uploaded original OpenCL code and SPIRV file)

**Comment by VitaliiGitHub** [comment]
> The link appears to be dead.

Please copy the link manually, automatic opening does not work.

**Comment by HansKristian-Work** [comment]
The SPIR-V is hitting this case basically:

From PtrAccessChain:
```
Note: If Base is typed to be a pointer to an array and the desired operation is to select an element of that array, [OpAccessChain](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpAccessChain) should be directly used, as its first Index selects the array element.
```

**Comment by VitaliiGitHub** [comment]
Super, I already did "git pull", rebuilt "spirv-cross" and after got a valid Metal code. Thanks!
