### ISSUE TITLE
get_entry_point get wrong output_primitives

### ISSUE THREAD

**Issue by BodinoMing** [KhronosGroup/SPIRV-Cross#2225]
i use 
```
spirv_cross::Compiler comp(spiirv);
auto entrypoints = comp.get_entry_point("main", spv::ExecutionModelGeometry);
```
No matter what the ouput of gs is (points, triangle_strip, line_strip), the output_primitives is zero
![image](https://github.com/KhronosGroup/SPIRV-Cross/assets/62131507/5d16323b-3c33-439d-95bc-813786559abf)
![image](https://github.com/KhronosGroup/SPIRV-Cross/assets/62131507/07070cfd-d270-4729-be46-f584a28c144a)

**Comment by HansKristian-Work** [comment]
output_primitives is in relation to number of primitives (from e.g. Mesh shader). Do you need to be able to reflect the primitive type?

**Comment by cdavis5e** [comment]
Yeah, that's a *geometry* shader you're reflecting. Geometry shaders don't declare the number of *primitives* they output; only the number of *vertices* they output. You should be able to derive the number of primitives from this and the output primitive type. The primitive type is available as an execution mode decoration.

(And I believe I was the one who told you to use that member in the first place. I apologize for misleading you.)

**Comment by BodinoMing** [comment]
Ok, I get it. Really thank you for your answers @ cdavis5e @ HansKristian-Work
