### ISSUE TITLE
[MSL] half4x4 codegen for constant buffers is broken

### ISSUE THREAD

**Issue by forbiddencactus** [KhronosGroup/SPIRV-Cross#2226]
Using SPIR-V generated by DXC with the following HLSL code leads to an exception being thrown when that SPIR-V is then used to attempt to generate MSL:
`cbuffer Constants : register(b0)
{
 half4x4 variable;
}`

> SPIRV_CROSS_THROW("Cannot represent vectors with more than 4 elements in MSL.");

**Comment by HansKristian-Work** [comment]
This is pretty awkward yes ... Needs a special case workaround I think.

**Comment by forbiddencactus** [comment]
Is there a a way the MSL emitter can just emit the half4x4 in the MSL uniform structure while ignoring the MatrixStride decoration emitted by DXC? I can just get my C++ code to align the cbuffer the way MSL needs it when running on Apple platforms.

**Comment by HansKristian-Work** [comment]
DXC should be able to emit cbuffer without legacy layout, that's the better way to avoid this problem.
