### ISSUE TITLE
[MSL] Conflict with Function Named Divide

### ISSUE THREAD

**Issue by cwfitzgerald** [KhronosGroup/SPIRV-Cross#2228]
I'm quite a few steps removed from spirv-cross here is all the information I have easily available, if you need more, ask and I can dig it up.

When running on MoltenVK with a shader that contains a function called `divide` with arguments `vec3 divide(vec3, vec3)` it runs into the following MSL compilation error.

```msl
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:516:42: error: call to 'divide' is ambiguous
            linearBlended = srgbToLinear(divide(srgbBase, srgbOver));
                                         ^~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.26/include/metal/metal_math:5099:19: note: candidate function
METAL_FUNC float3 divide(float3 x, float3 y)
                  ^
program_source:277:8: note: candidate function
float3 divide(float3 base, float3 over)
       ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
```

I tried running with `MVK_CONFIG_DEBUG=1` but I'm not getting additional messages with shader contents, maybe something is up with my logging configuration.

**Comment by cdavis5e** [comment]
It looks like your shader is defining a function that also happens to be defined by Metal. SPIRV-Cross has [code to remap conflicting identifiers][1], but it looks like we're not handling that one.

[1]: https://github.com/KhronosGroup/SPIRV-Cross/blob/42aac916ab5db0cbaf55c2d41f4d063f4ce3955a/spirv_msl.cpp#L14456
