### ISSUE TITLE
Why do push constants get their name differently from other blocks?

### ISSUE THREAD

**Issue by friesofdoom** [KhronosGroup/SPIRV-Cross#2231]
Push constants use get_name(var.self) which is inconsistent with other buffer blocks. Why does it not use get_remapped_declared_block_name(var.self, ssbo_instance_name) to be consistent? 

Thanks
Luke

**Comment by HansKristian-Work** [comment]
This is because how GL drivers interact with the uniform. When you query the uniform from API you query based on instance name, e.g.

```
layout(push_constant) uniform PushConstants
{
    float a, b;
} push;
````

becomes
```
uniform PushConstants push;
```

and API-side you do `glGetUniformLocation("push.a");`.
With UBOs you use the block name, so that was the logical thing to return.
