### ISSUE TITLE
[MSL] Invalid MSL generated when copying from groupshared array to local

### ISSUE THREAD

**Issue by jmccarthy634** [KhronosGroup/SPIRV-Cross#2239]
Hello, in our source HLSL we have a groupshared array of structs, each containing an array of float3 declared like this:
```
struct Data
{
    float3 sourceData[16];
};

groupshared Data g_data[64];
```
Then we attempt to copy from that array back into a local like this:
```
 getIndex(g_data[threadId.x].sourceData);
 ...
 uint getIndex(const float3 data[16])
{
	uint indices = 0;
	for (int i=0; i<16; ++i)
	{
		float3 color = data[i];
		uint index = uint(saturate(dot(color, float3(-1.f, -1.f, -1.f))));
		indices |= index;
	}

	return indices;
}
```
After feeding that into DXC and then the resulting spir-v into spirv-cross we get errors like this in the generated MSL:
```
error: no matching function for call to 'spvArrayCopyFromThreadGroupToStack1'
        spvArrayCopyFromThreadGroupToStack1(_133.elements, g_ColorData[_141].sourceColor);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:91:13: note: candidate template ignored: could not match 'const threadgroup T [A]' against 'threadgroup spvUnsafeArray<float3, 16>'
inline void spvArrayCopyFromThreadGroupToStack1(thread T (&dst)[A], threadgroup const T (&src)[A])
```
I've attached a cut down version of our HLSL that reproduces the issue, as well as the spir-v and disassembly from DXC and finally the MSL generated by spirv-cross:
[groupshared.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/13552105/groupshared.zip)

**Comment by HansKristian-Work** [comment]
Yet another case where the context sensitive nature of spvUnsafeArray is impossible to maintain ... :(
