### ISSUE TITLE
Double negation translated incorrectly

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#225]
This shader is translated incorrectly:

```
#version 450 core

layout(location = 0) in vec4 input1;
layout(location = 0) out vec4 outColor;

void main() {
    outColor = vec4(input1.x, -(-input1.y), input1.z, -(-input1.w));
}
```

to this:

```
    outColor = vec4(input1.x, --input1.y, input1.z, --input1.w);
```

The double negation in the original is due to preprocessor trickery.

**Comment by HansKristian-ARM** [comment]
Ah, probably some missed case with parenthesis removal optimization. Should be easy to fix.

**Comment by turol** [comment]
Yes, I tracked it down to [CompilerGLSL::enclose_expression](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L1812) which should check if `expr` begins with minus. I hacked around it locally but didn't make a PR because I'd have to write tests and everything. Also should probably check if the other backends are affected.

**Comment by HansKristian-ARM** [comment]
Fixed on master.
