### ISSUE TITLE
spriv-cross needs to support --version CLI argument

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/SPIRV-Cross#2262]
All the other spirv tools support this except spirv-cross.  I found out the spriv-tools build of spriv-cross is from like 2021.  So I'd like to dump all the versions of all the spriv tools for safe guarding against stale builds.

**Comment by HansKristian-Work** [comment]
This is already supported through the `--revision` CLI argument. `--version` is used to signal the GLSL versions.
