### ISSUE TITLE
Metal computer shader from SPIRV generated by new clspv tool..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#227]
@billhollings 
are you aware of https://github.com/google/clspv effort I say that because now seem very easy to translate OpenCL kernels to Spir-V Vulkan compute shaders (before that OpenCL kernels translated to SPIR-V via Khronos tool but where only usable from OpenCL SPIR-V capable implelentations only no Vulkan graphic drivers)..
I say that because MoltenVk will support compute shaders soon.. 
so would be interesting to know if MoltenVk & Metal API can support compute shaders generated by this tool.. the SPIRV code generated by that tool can use new SPV extensions like:
*SPV_KHR_variable_pointers
which seems the most important..
and also:
*SPV_KHR_16bit_storage & shaderInt16
*For image access:
shaderStorageImageReadWithoutFormat
shaderStorageImageWriteWithoutFormat

I don't know if MoltenVK supports currently or can support (i.e. Metal supports it) features like:
SPV_KHR_16bit_storage & shaderInt16
shaderStorageImageReadWithoutFormat
shaderStorageImageWriteWithoutFormat

and more afraid I'm of SPV_KHR_variable_pointers which Metal might not be ready for it..

For example with this tool I get for a simple kernel like:

```
void kernel __attribute__((reqd_work_group_size(1, 1, 1))) foo(sampler_t s, read_only image2d_t i, float2 c, global float4* a)
{
  *a = read_imagef(i, s, c);
}


```
SPIRV output like:

```
; SPIR-V
; Version: 1.0
; Generator: Codeplay; 0
; Bound: 34        
; Schema: 0
	OpCapability Shader
	OpCapability StorageImageReadWithoutFormat
	OpCapability VariablePointers
	OpExtension "SPV_KHR_variable_pointers"
	OpMemoryModel Logical GLSL450
	OpEntryPoint GLCompute %25 "foo"
	OpExecutionMode %25 LocalSize 1 1 1
	OpSource OpenCL_C 120
	OpMemberDecorate %7 0 Offset 0
	OpDecorate %7 BufferBlock
	OpDecorate %12 ArrayStride 16
	OpMemberDecorate %13 0 Offset 0
	OpDecorate %13 BufferBlock
	OpDecorate %21 DescriptorSet 0
	OpDecorate %21 Binding 0
	OpDecorate %22 DescriptorSet 0
	OpDecorate %22 Binding 1
	OpDecorate %22 NonWritable
	OpDecorate %23 DescriptorSet 0
	OpDecorate %23 Binding 2
	OpDecorate %24 DescriptorSet 0
	OpDecorate %24 Binding 3
%1 = 	OpTypeFloat 32
%2 = 	OpTypeSampler
%3 = 	OpTypePointer UniformConstant %2
%4 = 	OpTypeImage %1 2D 0 0 0 1 Unknown
%5 = 	OpTypePointer UniformConstant %4
%6 = 	OpTypeVector %1 2
%7 = 	OpTypeStruct %6
%8 = 	OpTypePointer StorageBuffer %7
%9 = 	OpTypePointer StorageBuffer %6
%10 = 	OpTypeVector %1 4
%11 = 	OpTypePointer StorageBuffer %10
%12 = 	OpTypeRuntimeArray %10
%13 = 	OpTypeStruct %12
%14 = 	OpTypePointer StorageBuffer %13
%15 = 	OpTypeInt 32 0
%16 = 	OpTypeVoid
%17 = 	OpTypeFunction %16
%18 = 	OpTypeSampledImage %4
%19 = 	OpConstant %1 0
%20 = 	OpConstant %15 0
%21 = 	OpVariable %3 UniformConstant
%22 = 	OpVariable %5 UniformConstant
%23 = 	OpVariable %8 StorageBuffer
%24 = 	OpVariable %14 StorageBuffer
%25 = 	OpFunction %16 None %17
%26 = 	OpLabel
%27 = 	OpLoad %2 %21
%28 = 	OpLoad %4 %22
%29 = 	OpAccessChain %9 %23 %20
%30 = 	OpLoad %6 %29
%31 = 	OpAccessChain %11 %24 %20 %20
%32 = 	OpSampledImage %18 %28 %27
%33 = 	OpImageSampleExplicitLod %10 %32 %30 Lod %19
	OpStore %31 %33
	OpReturn
	OpFunctionEnd


```

**Comment by HansKristian-ARM** [comment]
SPV_KHR_variable_pointers is not something we currently support. I'm not sure it can be translated into GLSL, maybe Metal, but it doesn't sound trivial to add.

**Comment by billhollings** [comment]
@oscarbg 

Thanks for the input.

Pointers and 16-bit `int` and `float` in/out variables should be acceptable in Metal.

As @HansKristian-ARM points out...building support into SPIRV-Cross might take some effort.

...Bill

**Comment by lygstate** [comment]
This is an very interesting topic and useful. And what's the hard part to support that?

**Comment by HansKristian-Work** [comment]
Indeed.
