### ISSUE TITLE
Inconsistent Block/Variable names

### ISSUE THREAD

**Issue by Calestian** [KhronosGroup/SPIRV-Cross#2277]
My workflow for shader compilation goes as follows.
-HLSL goes through DXC to generate Spirv.
-Resulting Spirv goes through spirv-cross, where I set decorations for bindings/sets.
-Resulting glsl string from spirv-cross goes to glslang for the final Spirv.

During the spirv-cross compilation phase, the resulting block names (and variable names for those blocks) are not always consistent and it messes with my reflections.

Eg.
```
StructuredBuffer<FPrimitiveMeshlet> PrimitiveMeshletBuffer;
StructuredBuffer<half3> PrimitivePositionBuffer;
StructuredBuffer<half3> PrimitiveNormalBuffer;
StructuredBuffer<half2> PrimitiveUVChannelBuffer;
StructuredBuffer<float4> PrimitiveVertexColorBuffer;
StructuredBuffer<uint>  PrimitiveVertexLookupTable;
ByteAddressBuffer PrimitiveIndicesBuffer;
StructuredBuffer<FPrimitiveLODData> PrimitiveLODDataBuffer;
```
The above gets compiled into this.
```
layout(set = 1, binding = 2, std430) readonly buffer type_StructuredBuffer_FPrimitiveMeshlet
{
    FPrimitiveMeshlet _m0[];
} PrimitiveMeshletBuffer;

layout(set = 1, binding = 3, std430) readonly buffer type_StructuredBuffer_v3half
{
    f16vec3 _m0[];
} PrimitivePositionBuffer;

layout(set = 1, binding = 4, std430) readonly buffer PrimitiveNormalBuffer
{
    f16vec3 _m0[];
} PrimitiveNormalBuffer_1;

layout(set = 1, binding = 5, std430) readonly buffer type_StructuredBuffer_v2half
{
    f16vec2 _m0[];
} PrimitiveUVChannelBuffer;

layout(set = 1, binding = 6, std430) readonly buffer type_StructuredBuffer_v4float
{
    vec4 _m0[];
} PrimitiveVertexColorBuffer;

layout(set = 1, binding = 7, std430) readonly buffer type_StructuredBuffer_uint
{
    uint _m0[];
} PrimitiveVertexLookupTable;

layout(set = 1, binding = 8, std430) readonly buffer type_ByteAddressBuffer
{
    uint _m0[];
} PrimitiveIndicesBuffer;
```

In most cases it's fine that the block name is not preserved, as it's passed to the variable name and I can do reflections using that, however in some cases that doesn't happen either (as is shown in the PrimitiveNormalBuffer example).

**Comment by HansKristian-Work** [comment]
My hunch here is that 

```
StructuredBuffer<half3> PrimitivePositionBuffer;
StructuredBuffer<half3> PrimitiveNormalBuffer;
```
map to the same OpType in DXC output. That makes it difficult to emit consistent names in spirv-cross.
When emitting PrimitiveNormalBuffer, spirv-cross cannot use the type name again as block name since there is a conflict, so it will promote the variable's name to block name instead as a workaround.

Maybe you can try clearing out block type names before compiling? That way, there should be a consistent promotion pattern to block name at least ...

**Comment by Calestian** [comment]
Good hunch!

Worked exactly as you described, thanks!
