### ISSUE TITLE
Incorrect texelFetch emitted for sampler2DMS

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#23]
I compiled this shader with glslang:
`#version 420
 uniform sampler2DMS colorBuffer;
 layout(location = 0) out vec4 outColor;
 void main(void)
 {
    outColor = texelFetch(colorBuffer, ivec2(gl_FragCoord.xy), 0);
 }
`

This compiles successfully but when compiled back to GLSL with SPIRV-cross it produces this:
`outColor = texelFetch(colorBuffer, ivec2(gl_FragCoord.xy));`

which will fail with "'texelFetch' : no matching overloaded function found".

**Comment by HansKristian-ARM** [comment]
Fixed on master.

**Comment by turol** [comment]
It works now, thanks.
