### ISSUE TITLE
MSL: Invalid code generated with matrix temporary

### ISSUE THREAD

**Issue by jmccarthy634** [KhronosGroup/SPIRV-Cross#2302]
Hello, have a somewhat annoying to reproduce issue with float4x4 or float4x3 temporaries, it seems that sometimes the MSL generated from source HLSL that looks like this:
```
StructuredBuffer<float4x4> InXforms : register(t0);
...
float4x4 tmWorld = InXforms[viewData.gModelIndex];
```

Will end up generating MSL like this:
```
const device auto& InXforms = (const device type_StructuredBuffer_mat4v4float&)(*spvDescriptorSet0.viewData);
```

Which in turn gives errors like this:
```
Metal Error: program_source:46:35: error: C-style cast from 'const constant type_viewData' to 'const device type_StructuredBuffer_mat4v4float &' is not allowed
    const device auto& InXforms = (const device type_StructuredBuffer_mat4v4float&)(*spvDescriptorSet0.viewData);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I've managed to create a simple repro of one we saw generated by a compute kernel for a vertex shader with the `vertex_for_tessellation` option enabled, but we've also seen this affect regular compute shaders as well. I've attached said repro with the source HLSL, SPIR-V and disassembly from DXC and the final output MSL from spirv-cross.

[broken_mat4.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/14752757/broken_mat4.zip)

**Comment by HansKristian-Work** [comment]
This is because you're aliasing a UBO and SSBO over the same binding and using both. This is not valid SPIR-V.

**Comment by jmccarthy634** [comment]
Hi, it occurs to me that the SPIR-V is taken from DXC but _before_ a step in which we modify the arguments to increment all buffer bindings by 1, to avoid this overlap - I will endeavor to provide the actual SPIR-V that we feed into SPIRV-Cross with all post-compile modifications, so that this issue can be reopened.
