### ISSUE TITLE
Shader specialization constant support

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/SPIRV-Cross#232]
It's seems that specialization support is not completed yet.
i run a test with the following line in the vulkan glsl ( taken from sascha's vulkan bloom sample):
  layout (constant_id = 0) const int blurdirection = 0;

the glsl es back end would generate:
  if((0 == 1)){ ... }

the hlsl backend would generate:
  if (blurdirection == 1){..}  but, blurdirection is not declare as a uniform

**Comment by HansKristian-ARM** [comment]
Does this only happen in HLSL? It should work in GLSL at least. The specialization constant should become a constant literal. (You can modify the spec constant before decompile to GLSL).

**Comment by HansKristian-ARM** [comment]
Indeed, constants are not being declared in HLSL. Will fix.
