### ISSUE TITLE
Struct inside another struct has same name as variable

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#233]
Hi,

I have this simple code that produces invalid glsl. The issue comes from using the CreateStripDebugInfoPass which renames structs to numbered builtin names such as _1. it normally happens when one of a very large struct's member is another struct. It's a bit of an issue right now as I really want to get the optimization pass working to reduce our huge glsl size. The input hlsl is:

```
struct A
{
	float a;
};

struct E
{	
	float a, b, c, d, e, f, g, h, i, j, k, l;
	A s;
};

float4 fragmentProgram() : SV_Target0
{	
	E e;
	return float4(e.a,e.b,e.c,e.d);
}
```
```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 35

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "fragmentProgram" 33
                              ExecutionMode 4 OriginLowerLeft
                              Decorate 33 Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypeFunction 7(fvec4)
              11:             TypeStruct 6(float)
              12:             TypeStruct 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 6(float) 11(struct)
              13:             TypePointer Function 12(struct)
              15:             TypeInt 32 1
              16:     15(int) Constant 0
              17:             TypePointer Function 6(float)
              20:     15(int) Constant 1
              23:     15(int) Constant 2
              26:     15(int) Constant 3
              32:             TypePointer Output 7(fvec4)
              33:     32(ptr) Variable Output
               4:           2 Function None 3
               5:             Label
              34:    7(fvec4) FunctionCall 9
                              Store 33 34
                              Return
                              FunctionEnd
               9:    7(fvec4) Function None 8
              10:             Label
              14:     13(ptr) Variable Function
              18:     17(ptr) AccessChain 14 16
              19:    6(float) Load 18
              21:     17(ptr) AccessChain 14 20
              22:    6(float) Load 21
              24:     17(ptr) AccessChain 14 23
              25:    6(float) Load 24
              27:     17(ptr) AccessChain 14 26
              28:    6(float) Load 27
              29:    7(fvec4) CompositeConstruct 19 22 25 28
                              ReturnValue 29
                              FunctionEnd

```

The resulting SPIR-V has no issue because the built-in variables don't have a name yet. I suspect it's SPIRVCross that assigns them, without taking into account that types might be named so.

The resulting glsl for the stucts becomes the following, which is wrong because both a struct and a variable name are _11.

```
struct _11
{
    float _0;
};

struct _12
{
    float _0;
    float _1;
    float _2;
    float _3;
    float _4;
    float _5;
    float _6;
    float _7;
    float _8;
    float _9;
    float _10;
    float _11;
    _11 _12;
};
```

**Comment by HansKristian-ARM** [comment]
Ah, nice find. Should be a trivial fix if we name the member variables _m_## or something like that instead of using the same numbering scheme as types.

**Comment by redorav** [comment]
One quick thing I'd like to point out: what I like about only having an underscore is that they can bring down the glsl filesize. I'm  struggling to get the Mac compiler to be performant and I'm finding that every byte counts. Could we just do mXX to those variables or will it conflict with something else?

**Comment by HansKristian-ARM** [comment]
mXX would not work because they easily conflict with user defined names. I've reserved the leading underscore for spirv-cross generated names to avoid these kinds of conflicts. Double underscores are also disallowed in GLSL.

**Comment by HansKristian-ARM** [comment]
you have a spir-v binary/asm version of that shader so I can add it to regression suite?

**Comment by redorav** [comment]
I can generate it quickly for you now. Unfortunately for me, it makes sense that mXX names collide with user names, I was only thinking of the case where SPIRVCross automatically assigns names. I'll send it to you via email.

**Comment by HansKristian-ARM** [comment]
I can compact it to "_m", just one byte, there are other ways we can shave bytes if this actually matters. (Stripping spaces, etc)

**Comment by HansKristian-ARM** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/pull/234 here's a PR which should fix the issue. I'll add a regression test for it when I get it.

**Comment by redorav** [comment]
Yeah I already do space/newline stripping and other tricks as a post pass. It's actually very useful that SPIRVCross glsl is so well formatted as it can be parsed with little effort. It's a bit unfortunate to have to do it at the glsl level but the Mac compiler is very finicky about some things and the SPIRVTools optimizer isn't as mature as I would like at the moment so we do code elimination by removing if(false), if(true), if(1 == 0) type of replacement. "_m" should be fine here, can't complain really, it's still very compact.
