### ISSUE TITLE
Slang produces spv that works on win/linux but not with MoltenVk

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/SPIRV-Cross#2336]
Using Slang v2024.1.18 and MoltenVk from SDK 1.3.283.0

Output is:
<img width="912" alt="335888549-fb5e548c-9e41-41fb-be50-5c0df315d81c" src="https://github.com/KhronosGroup/SPIRV-Cross/assets/15105596/13251379-7a18-435e-a968-385e25dc64b9">

But should be:
![Screenshot 2024-06-02 200220](https://github.com/KhronosGroup/SPIRV-Cross/assets/15105596/09db9c0e-bc97-419b-8da5-0a0a7427a9fe)

Use the code here to reproduce.
https://github.com/fknfilewalker/vulkan-triangle-modern/tree/sdl

My guess is that the pointer arithmetic does not work correctly. So the shift here `vertices[vid]` is just 1 float.
```csharp
[[vk::push_constant]] float3* vertices;

[shader("vertex")]
float4 vertexMain(uint vid : SV_VertexID) : SV_Position
{
    return float4(vertices[vid], 1.0);
}
```

**Comment by HansKristian-Work** [comment]
Can you upload the SPIR-V? I'm not going to figure out how to build and run a random project just to fish out a SPIR-V. Most likely this is caused by float3 being stride 16 in Metal and we have to figure out a way to deal with OpPtrAccessChain with arbitrary ArrayStride.

**Comment by fknfilewalker** [comment]
The spirv in here https://github.com/fknfilewalker/vulkan-triangle-modern/blob/sdl/src/shaders.h

Is this fine or do you need it in a different form?

**Comment by HansKristian-Work** [comment]
If it's not too much to ask, either a SPIR-V asm file or raw SPIR-V is fine.

**Comment by fknfilewalker** [comment]
could only share them here in a zip (includes asm as well as spa)
[spv.zip](https://github.com/user-attachments/files/15552208/spv.zip)

**Comment by HansKristian-Work** [comment]
Thanks. That works.

```
OpDecorate %_ptr_PhysicalStorageBuffer_v3float ArrayStride 12
```
is the culprit. If you want to workaround this in the interim, try using float4 for now.
