### ISSUE TITLE
Feature request: Support for SM 6.8 SV_StartVertexLocation/SV_StartInstanceLocation in HLSL output

### ISSUE THREAD

**Issue by Ravbug** [KhronosGroup/SPIRV-Cross#2348]
In Shader Model 6.8, two new system values were added to HLSL to provide the functionality of `gl_BaseVertex` and `gl_BaseInstance`. 

More information can be found here: https://microsoft.github.io/hlsl-specs/proposals/0015-extended-command-info.html

This means the cbuffer SPIRV-Cross currently generates to emulate the GLSL variables would no longer be necessary if targeting SM 6.8:
```hlsl
cbuffer SPIRV_Cross_VertexInfo    // can eliminate this
{
    int SPIRV_Cross_BaseVertex;
    int SPIRV_Cross_BaseInstance;
};
```
changing to this:
```hlsl
struct SPIRV_Cross_Input
{
    // ...
    uint SPIRV_Cross_BaseInstance: SV_StartInstanceLocation;
};

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
   gl_BaseInstanceARB = stage_input.SPIRV_Cross_BaseInstance;
    // ...
}

```

**Comment by HansKristian-Work** [comment]
This should be easy to support. I'll get to it in a while, but would be faster to PR it.
