### ISSUE TITLE
Enable github discussions feature?

### ISSUE THREAD

**Issue by Try** [KhronosGroup/SPIRV-Cross#2359]
GitHub discussions allow for users of this particular repository to raise how-to kind of questions and share finding with each other in similar to forum manner. Would be nice to have them in this project.
This will help to segregate question (at this point labeled as `question`) from bug reports and real issues.

Documentation: https://docs.github.com/en/discussions

**Comment by HansKristian-Work** [comment]
@outofcontrol I assume this is something you have control over? I'm okay adding discussions tab, but I don't have perms to add them myself.

**Comment by HansKristian-Work** [comment]
Should be done now.
