### ISSUE TITLE
Input variable base_type doesn't get renamed properly

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#236]
Here's another problematic shader. I'm calling

```
glslCompiler.set_name(resources.stage_inputs[0].base_type_id, "InputStruct");
```

on this SPIRV, because the InputStruct has been renamed by the debug stripping pass and Mac GL needs it be the same to be able to link shaders. I call it on stage_inputs[0] because it only ever has one input, which is a struct shared by vertex and pixel shader. For some reason glslCompiler.compile() doesn't replace the base_type. I don't know what's going on but it works on most shaders, it's just a few that don't work. A minimal example works correctly, so I need to send you the spv as it's input to glsl compiler by email. Unless I'm using the API wrong and there's some expectation on my side that doesn't necessarily need to be met.

**Comment by HansKristian-ARM** [comment]
Fixed in https://github.com/KhronosGroup/SPIRV-Cross/pull/237. Please check if it fixed your issues.

**Comment by redorav** [comment]
Cool waiting for this to merge. Will let you know as soon as you have it.

**Comment by redorav** [comment]
Ok I copy pasted the diff into latest code and I confirm it works. Thanks for all your support (I'm removing a big chunk of hack I had to work around it which makes me happy)
