### ISSUE TITLE
Undefined behaviour glsl code generated

### ISSUE THREAD

**Issue by mihaly-sisak** [KhronosGroup/SPIRV-Cross#2378]
I have 2 variables generated (`bool _78998; uint _79108;`) that are global, read only and are not initialized. The spir-v file passes the validator without errors.
I invoke SPIRV-Cross with `spirv-cross --version 430 --no-es --output glsl.glsl spv.spv`.
I attached the input file and the file I get as output.
[glsl_bugreport.zip](https://github.com/user-attachments/files/16936081/glsl_bugreport.zip)

**Comment by HansKristian-Work** [comment]
This is the code pattern for OpUndef, so that is expected. Are the SSA variables here not supposed to be Undef?

**Comment by mihaly-sisak** [comment]
Thank you for the feedback, you are correct, it is actually OpUndef, my bad.
