### ISSUE TITLE
Support emitting SPIRV?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [KhronosGroup/SPIRV-Cross#2387]
Based on what I can gather SPIRV-Cross does not support emitting back out SPIRV from the reflection done on it.
This would be a nice to have in engines which end up wanting to programmatically modify input SPIRV before consumption, by eg. reassigning descriptor sets and layouts.

I've started work on a PR for such a backend, but would this be desirable?

**Comment by HansKristian-Work** [comment]
No, simple patching can be done through the reflection API to query byte offsets for decorations. There's little to no point in adding a SPIR-V emitter to SPIRV-Cross, and I don't want to maintain it.

**Comment by LunaTheFoxgirl** [comment]
Okay, good to know, I'll keep these changes in a fork, then.
