### ISSUE TITLE
Incorrect GLSL generated from spirv-remap -minimized shader

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#24]
This shader:
```
#version 420
uniform sampler2D tex1;
out vec4 t;
void main() {
    float f = texture(tex1, vec2(0.0f)).x;
    t = vec4(f * f);
}
```
works OK when GLSL is created directly from glslang-outputted spv file but breaks after spirv-remap has been run. Produced output looks like this:
```
    vec4 _17 = texture(tex1, vec2(0.0));
    float f = .x;
    t = vec4((_17f * _17f));
```

The SPIR-V code itself seems ok, the relevant part before remap:
```
         %21 = OpCompositeExtract %6 %18 0
               OpStore %8 %21
         %24 = OpLoad %6 %8
         %25 = OpLoad %6 %8
         %26 = OpFMul %6 %24 %25
```

and after:
```
         %20 = OpCompositeExtract %6 %17 0
         %23 = OpFMul %6 %20 %20
```

Looks like something is wrong in the handling of OpCompositeExtract when it's not followed by OpStore. Or is this a bug in the remapper?

**Comment by HansKristian-ARM** [comment]
The output looks very strange, yes. I'll take a look.

**Comment by HansKristian-ARM** [comment]
Thanks for the finding. Should be fixed on master now with a regression test.

**Comment by turol** [comment]
Thanks for fixing it.
