### ISSUE TITLE
SPIRVCross seems to create invalid code after inlining multipe returns due to Undef tokens

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#242]
I want to bring to your attention this bug. https://github.com/KhronosGroup/SPIRV-Tools/issues/736

Essentially, I've been inlining code that has multiple return values, which after translation to glsl becomes invalid. I thought it was a SPIRVTools bug (since activating the inliner caused it) but it seems to be a SPIRVCross bug according to the devs after inspecting the code I provided them.

Do you think you could take a quick look at it and see what you can make out of it?

**Comment by HansKristian-ARM** [comment]
Huh ... Well, I'll take a look tomorrow.

**Comment by HansKristian-ARM** [comment]
Fixed the Undef issue. This found another issue with the CFG analysis which I've also fixed now.

**Comment by redorav** [comment]
Awesome! Thanks very much :)
