### ISSUE TITLE
MSL: divergence in different code stages when relying on DecorationInvariant

### ISSUE THREAD

**Issue by mabaro** [KhronosGroup/SPIRV-Cross#2420]
The current implementation relies on adding the dependency chain of the **invariant** variable (i.e, position) to the **forced_temporary** group. This already splits a lot of operations reducing the chances of divergencies, but it's not enough for complex setups.
In our use case, the **spirv-opt** output has divergencies on different stages, splitting one particular operation on one stage (i.e.,  __961 - (_958 * dot(_961, _958))__) into temporaries, while keeping it inlined on the other stage.
When passing the produced spirv through **spirv-cross** the **invariant** decoration current behaviour keeps the divergences generating glitches.
The only solution I came up to have some sort of working code is:
- propagate decorationInvariant through the dependency chain
- use decorationInvariant in the same sense as decorationNoContraction in emit_binary_op/emit_binary_op_func (i.e., the latter is used by spirv_msl when outputting spvXXX functions)

This is for sure not a complete solution, and I don't know if that approach could even be considered adequated for merging at certain point, or for further investigation.

I'd appreciate any hints/opinions.
Cheers.

**Comment by mabaro** [comment]
related post -> https://github.com/KhronosGroup/SPIRV-Cross/pull/1022

**Comment by mabaro** [comment]
This pull request contains the changes that fix the mentioned divergence problem by having all operations involved being forced into temporaries, assuming the Metal compiler will do a proper job optimizing.

https://github.com/KhronosGroup/SPIRV-Cross/pull/2424

**Comment by HansKristian-Work** [comment]
Ok, I think I grok the problem now.

If a dependent variable was marked forced temporary in one translation unit, but not the other, the tracking of the dependency chain breaks. I think I see a better solution though. I'll try that.
