### ISSUE TITLE
MSL compute shader support?

### ISSUE THREAD

**Issue by yvt** [KhronosGroup/SPIRV-Cross#248]
I'm wondering about the status of the compute shader support of the MSL backend...

When I checked for the last time, the following items were not working:

- `Workgroup` storage class
    ```glsl
    shared uint kernel_values[64];
    ```
- `OpControlBarrier` and `OpMemoryBarrier`

    ```glsl
    // wait for all inputs to be ready...
    groupMemoryBarrier();
    barrier();
    ```

Is there any plan to support them? Or is anyone currently working on them?

------

Because they were crucial components to make compute shaders unique from other shaders, I managed to implement them in [my fork](https://github.com/yvt/SPIRV-Cross/blob/5670f1a132336da0ad56af5a6b6ed2a704984eb7/spirv_msl.cpp) to use in an experimental project that I am working on. This currently has the following restrictions:

- Shared variables cannot have a matrix type. Matrix types in Metal cannot be default-constructed in the `threadgroup` memory space. 
- `OpMemoryBarrier` has no MSL counterpart. Memory barriers only can be inserted as a part of a control barrier. 

    To make matters worse, `barrier()` in GLSL ES does not imply a memory barrier and users have to use the following common idiom:
    ```glsl
    groupMemoryBarrier();
    barrier();
    ```
    This code is translated by `glslang` into two separate instructions; `OpMemoryBarrier` that only inserts a workgroup memory barrier which does not have a MSL counterpart, and `OpControlBarrier` that only inserts a control barrier. As a result, the direct MSL translation of this code would look like this:
    ```msl
    // (OpMemoryBarrier is ignored because there's no MSL counterpart)
    threadgroup_barrier(mem_flags::mem_none);
    ```
    This is unacceptable, so as a work-around I decided to automatically include `Workgroup` in `OpControlBarrier`'s memory semantics. Therefore, the above code will be translated to
    ```msl
    // memory barrier is not supported in MSL
    threadgroup_barrier(mem_flags::mem_threadgroup);
    ```

Even with these restrictions, I think this adds a kind of real support for compute shader. With it, I successfully transpiled and got a simple convolution kernel working.  Let me know if you want me to send a pull request. (I will need to update `reference/shaders-msl` before doing that)

**Comment by billhollings** [comment]
I will be able to look at computer shader support in a couple of weeks.

**Comment by billhollings** [comment]
Development of this is now underway. I should be able to release functional code by next week.

**Comment by HansKristian-ARM** [comment]
Can this be closed now?
