### ISSUE TITLE
Error due to out parameter instead of inout

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/SPIRV-Cross#250]
Hi,
I have some HLSL shaders converted to SPIRV, then converted back to HLSL thanks to SPIRV-Cross.
In some cases, those later HLSL shaders will fail to compile, because SPIRV-Cross changed an "inout" parameter to an "out" (compared to the former HLSL shader)

For example with this basic HLSL shader, Compute function takes an inout parameter, if this inout is replaced by an out attribute, HLSL compilation will fail and say: **output parameter 'output' not completely initialized**

struct VS_INPUT
{
    float4 Pos : POSITION;
    float4 Color : COLOR;
};
struct PS_INPUT
{
    float4 Pos : SV_POSITION;
    float4 Color : COLOR;
};

void Compute(**inout** PS_INPUT output)
{
    output.Color = float4(1, 0, 0, 1);
}

PS_INPUT main( VS_INPUT input )
{
    PS_INPUT output = (PS_INPUT)0;
    output.Pos = input.Pos;
    output.Color = input.Color;
    Compute(output);
    return output;
}

**Comment by HansKristian-ARM** [comment]
Hm ... I suspect this has something to do with the analysis of in/inout/out. We might need to add extra checks to deal with partial writes to a parameter. If an out variable is only partially written to we need inout. :(

**Comment by Joojooo** [comment]
Thanks for your quick answer and the support. Yes this fix about partial writes would be great  :)
