### ISSUE TITLE
Question about unimplemented image type

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/SPIRV-Cross#253]
Hi and thank you for your work and support on SPIRV-Cross

I'm just wondering if you please have any information as to when this feature will be supported ?

string CompilerHLSL::image_type_hlsl_modern(const SPIRType &type)
{
  ...
  case **DimRect**:
    SPIRV_CROSS_THROW("Rectangle texture support is not yet implemented for HLSL"); // TODO
  case **DimBuffer**:
    // Buffer/RWBuffer.
    SPIRV_CROSS_THROW("Buffer/RWBuffer support is not yet implemented for HLSL"); // TODO

**Comment by HansKristian-ARM** [comment]
No immediate plan, but if you have some test shaders you need to work it would get some priority.

**Comment by Joojooo** [comment]
This is the test shader I'm using:

______________________________________________
Texture3D<uint2> LightClusters;
Buffer<uint> LightIndices;
Buffer<float4> PointLights;
	
void PSMain()
{
	int realLightIndex = LightIndices.Load(0);
	float4 pointLight1 = PointLights.Load(realLightIndex * 2);
	uint2 lightData = LightClusters.Load(int4(0, 1, 2, 3));
}
______________________________________________

I can convert it to SPIRV using glslang
But when I convert it back from SPRIV to HLSL using SPIRV-Cross, it will throw this exception:
SPIRV_CROSS_THROW("Buffer/RWBuffer support is not yet implemented for HLSL"); // TODO

I'm using hlsl shader model 40 (--shader-model 40)
If the shader model is below 40, it will throw this exception instead:
SPIRV_CROSS_THROW("Separate image and samplers not supported in legacy HLSL.");

**Comment by Joojooo** [comment]
Awesome, thank you !
