### ISSUE TITLE
GLSL code uses uninitialized variables

### ISSUE THREAD

**Issue by dsrbecky** [KhronosGroup/SPIRV-Cross#258]
If the original code looks something like this:
out vec4 TEXCOORD0;
void main() {
    TEXCOORD0.xy = ...;
    TEXCOORD0.zw = ...;
}

glslang will translate the first line to something like
              29:   10(fvec4) Load 23(TEXCOORD0)
              30:   10(fvec4) VectorShuffle 29 ... 4 5 2 3
                                      Store 23(TEXCOORD0) 30

which SPIRV-Cross will translate to:
    TEXCOORD0 = vec4(..., ..., TEXCOORD0.z, TEXCOORD0.w);

That is technically correct, but some of the drivers that I have encountered start warning that TEXCOORD0 is read uninitialized, which is true...

I am wondering if there is a way to produce clean output.... thoughts?

I suppose "working as intended" is also reasonable resolution.

**Comment by HansKristian-ARM** [comment]
The SPIR-V code generated by glslang for these partial writes is it reads the whole vector, combines that with the data you're writing, and swizzles them (picks 4 components out of 8), writing back some of the original values in the process. I don't think there is a reasonable way to avoid this without a lot of hackery.

**Comment by dsrbecky** [comment]
Yeap, I have realized it is non-trivial / hacky as well.

I can somewhat excuse glslang, as without masked write, this seems like reasonable way to do it in SPIRV.

How would you feel about pattern-matching?  I think any multi-component assignment will pretty much always result in this "Load, VectorShuffle, Store" pattern.

**Comment by HansKristian-ARM** [comment]
You *could* hijack OpStore and so some checks there, this is currently done for "a = a + x -> a += x", but this is vitally important for ESSL 1.0 loop updates, or they refuse to compile. That kind of check is trivial to implement as well.

I would consider it if I see a PR, but I don't think I will spend time on it as this is quite cosmetic.

It should be possible to create a module for simple "string based optimizations" which OpStore can call into.

**Comment by dsrbecky** [comment]
Fair enough, I currently do not have much spare time, but will see if can make a PR at some point in the future.  Any quick hints?

**Comment by HansKristian-ARM** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L4605
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L4479 should be good starting points.
