### ISSUE TITLE
Adds unused sampler uniforms when there are functions with sampler parameters

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#26]
This shader:
```
#version 330

uniform sampler2D s1;
uniform sampler2D s2;

in vec2 texcoord;
in float selector;

layout (location = 0) out vec4 o;

vec4 helper(sampler2D helpsampler, vec2 c) {
    return texture(helpsampler, c);
}

void main(void) {
    if (selector < 0.0) {
        o = helper(s1, texcoord);
    } else {
        o = helper(s2, texcoord);
    }
}
```
turns into this after glslang + spirv-cross:
```
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

uniform sampler2D helpsampler;
uniform sampler2D s1;
uniform sampler2D s2;

in float selector;
layout(location = 0) out vec4 o;
in vec2 texcoord;

vec4 helper(sampler2D helpsampler_1, vec2 c)
{
    return texture(helpsampler_1, c);
}

void main()
{
    vec2 param;
    vec2 param_1;
    if ((selector < 0.0))
    {
        param = texcoord;
        o = helper(s1, param);
    }
    else
    {
        param_1 = texcoord;
        o = helper(s2, param_1);
    }
}
```
There's a completely unused "helpsampler" uniform and the old "helpsampler" function parameter has been renamed to "helpsampler_1". With a sufficiently complex shader and enough samplers this can make a shader go over implementation-defined limit on number of samplers. This new uniform is also reported in shader resources which confused the hell out of my shader introspection code.

**Comment by HansKristian-ARM** [comment]
I cannot reproduce this in my copy of glslang.
{code}
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

uniform sampler2D s1;
uniform sampler2D s2;

in float selector;
layout(location = 0) out vec4 o;
in vec2 texcoord;

vec4 helper(sampler2D helpsampler, vec2 c)
{
    return texture(helpsampler, c);
}

void main()
{
    vec2 param;
    vec2 param_1;
    if ((selector < 0.0))
    {
        param = texcoord;
        o = helper(s1, param);
    }
    else
    {
        param_1 = texcoord;
        o = helper(s2, param_1);
    }
}
{code}

Which glslang commit are you on?

**Comment by turol** [comment]
I upgraded my glslang to latest and it still happens for me.

**Comment by turol** [comment]
The previous version of glslang I was using was ac666e7368 from June 14.

**Comment by HansKristian-ARM** [comment]
Ok, bug was due to glslang now passing samplers as StorageClassUniform. Pushed fix to master.

**Comment by turol** [comment]
Fixed, thanks.
