### ISSUE TITLE
Legacy GL or GLES 2.0/3.0 attributes

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#263]
Vulkan support location index for stage attribute binding, this is not supported under legacy opengl or GLES backends, usually its used the "v" prefix for passing attributes between vertex and fragment shader, how to handle this scenario using SPIRV-Cross? Or it is handled?

Sorry if dump question or if already answered, I tried to dig README.md but not found something related.
Thanks

**Comment by HansKristian-ARM** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/README.md#linking-by-name-for-targets-which-do-not-support-explicit-locations-legacy-glslessl should answer your question.

**Comment by HansKristian-ARM** [comment]
No reply, so I assume it answered the question, closing.
