### ISSUE TITLE
Invalid shader after unrolling input / output variables

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/SPIRV-Cross#264]
I noticed an issue when SPIRV-Cross unrolls input / output blocks

My sample HLSL shader is:
____________________________________________________________________________________
struct VS_Input
{
    float3x3 VS_IN_tangentToWorld : SEMANTIC01;
};

struct VS_Output
{
    float3x3 VS_OUT_tangentToWorld : SEMANTIC02;
};

VS_Output main(VS_Input input)
{
    VS_Output stage_output;
    stage_output.VS_OUT_tangentToWorld = input.VS_IN_tangentToWorld;
    return stage_output;
}
____________________________________________________________________________________

I convert it to SPV using glslang (vertex stage), convert it back using SPIRV-Cross, and get this HLSL output:

____________________________________________________________________________________
struct VS_Input
{
    float3x3 VS_IN_tangentToWorld;
};

struct VS_Output
{
    float3x3 VS_OUT_tangentToWorld;
};

uniform float4 gl_HalfPixel;

static float3x3 VS_IN_tangentToWorld;
static float3x3 VS_OUT_tangentToWorld;

struct SPIRV_Cross_Input
{
    float3 VS_IN_tangentToWorld_0 : TEXCOORD0;
    float3 VS_IN_tangentToWorld_1 : TEXCOORD1;
    float3 VS_IN_tangentToWorld_2 : TEXCOORD2;
};

struct SPIRV_Cross_Output
{
    float3 VS_OUT_tangentToWorld_0 : TEXCOORD0;
    float3 VS_OUT_tangentToWorld_1 : TEXCOORD1;
    float3 VS_OUT_tangentToWorld_2 : TEXCOORD2;
};

VS_Output _main(VS_Input input)
{
    VS_Output stage_output;
    stage_output.VS_OUT_tangentToWorld = input.VS_IN_tangentToWorld;
    return stage_output;
}

void vert_main()
{
    VS_Input input;
    input.VS_IN_tangentToWorld = VS_IN_tangentToWorld;
    VS_Input param = input;
    VS_OUT_tangentToWorld = _main(param).VS_OUT_tangentToWorld;
    gl_Position.x = gl_Position.x - gl_HalfPixel.x * gl_Position.w;
    gl_Position.y = gl_Position.y + gl_HalfPixel.y * gl_Position.w;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    VS_IN_tangentToWorld[0] = stage_input.VS_IN_tangentToWorld_0;
    VS_IN_tangentToWorld[1] = stage_input.VS_IN_tangentToWorld_1;
    VS_IN_tangentToWorld[2] = stage_input.VS_IN_tangentToWorld_2;
    vert_main();
    SPIRV_Cross_Output stage_output;
    **stage_output.VS_OUT_tangentToWorld** = VS_OUT_tangentToWorld;
    return stage_output;
}
____________________________________________________________________________________

The problem is that **"stage_output.VS_OUT_tangentToWorld"** variable does not exist, since it has been unrolled into 3 different variable in "SPIRV_Cross_Output" struct.

**Comment by HansKristian-ARM** [comment]
Right ... There is some unrolling code for matrices (is that even needed?), it's probably not implemented for stores.

**Comment by HansKristian-ARM** [comment]
@RobDangerous , you know what the reason was for unrolling matrices like this? Is it needed?

**Comment by RobDangerous** [comment]
Because I apparently didn't know that matrices can be in/outputs in HLSL. Maybe only in D3D11 though, will take a look.

**Comment by HansKristian-ARM** [comment]
@RobDangerous Any progress on this? If not, I can look at it.

**Comment by RobDangerous** [comment]
No progress yet, sorry.
