### ISSUE TITLE
`coherent` attribute missing from SSBO

### ISSUE THREAD

**Issue by paniq** [KhronosGroup/SPIRV-Cross#265]
after compiling this GLSL snippet to SPIR-V and back using SPIRV-Cross, the `coherent` attribute is missing:
```
#version 450

layout(binding = 0) coherent readonly buffer InVals
{
    int x;
    int y;
} invals;
layout(binding = 1) coherent writeonly buffer OutVals
{
    int x;
    int y;
} outvals;

void main() {
    outvals.x = invals.x;
    outvals.y = invals.y;
}
```
In fact it appears I can't seem to get the `coherent` attribute to show up with my own code generator either.

**Comment by HansKristian-ARM** [comment]
Merged on master.
