### ISSUE TITLE
command line app does not output error messages

### ISSUE THREAD

**Issue by l0calh05t** [KhronosGroup/SPIRV-Cross#275]
The command line app should either catch the exceptions thrown and print the message and/or if exceptions-to-assert is active the print should always happen. As is, the application fails silently, leaving the user clueless as to what went wrong.

**Comment by HansKristian-ARM** [comment]
I suppose this is most relevant on Windows? On Linux the default exception handler does this, but I agree that's not very clean. I'll make sure it's logged properly on Windows CLI as well.

**Comment by l0calh05t** [comment]
Yes, this is on windows. The default Windows handler does nothing but return a non-zero error code.
