### ISSUE TITLE
layout specifiers on uniforms are not stripped correctly

### ISSUE THREAD

**Issue by l0calh05t** [KhronosGroup/SPIRV-Cross#276]
I have compiled a 450 shader with a uniform with specified location to spirv, and am cross compiling to desktop GLSL. The location specifier is not stripped, and

```
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
```

is added to the Shader for version < 420. There should either be an option to strip these specifiers, or they should even be stripped by default as is done for GLSL-ES.

**Comment by HansKristian-ARM** [comment]
So if I understand it correctly, you have

```
#version 450
layout(binding = 1) uniform MyUBO
{
};
```

and you want to generate

```
#version something-less-than-420
uniform MyUBO
{
};
```
?

**Comment by l0calh05t** [comment]
Actually, I miswrote and meant predefined texture binding and not location, so `layout(binding = 0) uniform sampler2D foo;` is turned into `uniform highp sampler2D foo;` for glsl-es, but into
```
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

layout(binding = 0) uniform sampler2D foo;
```
for glsl.

However, a similar issue does occur with what you mentioned:
```
layout(location = 0) uniform UBO
{
	float foo;
};
```
is turned into
```
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

layout(location = 0, std140) uniform UBO
{
    float foo;
} _49;
```

**Comment by HansKristian-ARM** [comment]
Ok, so instead of trying to make use of 420pack extension, you would like an option to strip all explicit bindings and not try to use the extension?

**Comment by l0calh05t** [comment]
yes, pretty much.

**Comment by HansKristian-ARM** [comment]
Fair enough, I can see that being useful on OSX.
