### ISSUE TITLE
HLSL support

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#28]
Not an issue, are there any plans to support HLSL conversion?

Thanks

**Comment by HansKristian-ARM** [comment]
Someone is currently working on it, but I don't know any timeframe.

**Comment by amerkoleci** [comment]
Are there any links?
Recently I ended up on [https://github.com/KTXSoftware/krafix](url)

**Comment by billhollings** [comment]
Yes...Robert, the developer of [Krafix](https://github.com/KTXSoftware/krafix), is the one that is producing the HLSL implementation for SPIRV-Cross. You can contact him directly through the Krafix GitHub to find out more.

**Comment by RobDangerous** [comment]
Ah. Yes, I'm doing that. Wanted to get to it earlier but I'm on it now.

**Comment by RobDangerous** [comment]
In case somebody wants to watch the progress: https://github.com/KTXSoftware/SPIRV-Cross/tree/hlsl

**Comment by Joojooo** [comment]
Hi, can I please ask what's the status of this HLSL support for SPIRV-cross? the hlsl branch din't get updated since last August, so just like to know if it's already usable or still a work progress.

**Comment by RobDangerous** [comment]
It's in active use and there's more HLSL work on our master branch. Think it's about time, I'll try to get the pull request going next week.

**Comment by Joojooo** [comment]
This is a great news, thanks for the update

**Comment by HansKristian-ARM** [comment]
First iteration of the backend is now merged.
