### ISSUE TITLE
A variable is modified but not used

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#281]
[spirv_cross.cpp line 2632](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.cpp#L2632) variable `length` is decremented but the new value is not used by this function. Is this left over from something or was `length` supposed to be passed by reference?

**Comment by HansKristian-ARM** [comment]
This seems like dead code which might have been made obsolete after some refactoring. Both args pointer increment and length decrement are not used there from what I can tell.
