### ISSUE TITLE
can not convert textureSize to HLSL

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/SPIRV-Cross#283]
layout (binding = 1) uniform sampler samLinear;
layout (binding = 2) uniform texture2D texGlow;
layout (location = 0) out vec4 outFragColor;
void main()
{
    vec2 texSize = textureSize(sampler2D(texGlow, samLinear), 0);
    outFragColor = vec4(0.0, 0.0, 0.0, 1.0);
}

this fragment shader world trigger assertion "Combined image samplers have no default expression representaion"

**Comment by HansKristian-ARM** [comment]
Indeed, this is not implemented currently.
https://msdn.microsoft.com/en-us/library/windows/desktop/bb509693(v=vs.85).aspx will need to be used.

**Comment by HansKristian-ARM** [comment]
Started on this. Found some other bugs related to texture queries in GLSL as well.
