### ISSUE TITLE
Splitting `parse` from compiler

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/SPIRV-Cross#287]
Have there been any discussions about splitting `parse` from the compiler class? The idea would be that you can parse some SPIR-V input and compile to HLSL and MSL at the same time without re-parsing. As well, some parsed information (like parsed extension names) could be used to determine whether to apply certain transformations or options.

I expect there are probably ways I can hack around it to get this kind of behavior, but I was wondering if there is any interest to incorporate this into the API directly. Alternatively there could be a way to instantiate the parts of the base compiler that does the parsing, and later "upgrade" it (through composition, copying properties, etc.) into multiple instances of any derived classes.

**Comment by HansKristian-ARM** [comment]
There has not been any discussions about this, no.

What do you want to accomplish here? The "obvious" method right now is to parse the same SPIR-V twice, which is a small inefficiency (I think, but I might be wrong).

Something like a copy constructor which copies over the parsed data from a base class`CompilerGLSL::CompilerGLSL(const Compiler &)` seems doable, but I need to understand the benefits before looking into this, as there are probably better solutions.

**Comment by grovesNL** [comment]
Thanks for the quick response!

The use case is roughly as I described. The user provides some SPIR-V modules, parses each module, does some work based on the result of parsing (i.e. extension names), then (potentially much later) generates HLSL and MSL for each of the parsed modules. So the parsing work upfront is very generic; the user doesn't "specialize" to create HLSL/MSL compilers until potentially much later than the parse step.

As you said, in the case where I create HLSL/MSL/GLSL for a list of SPIR-V modules, I could parse each of the modules three times. Although the efficiency of re-parsing depends on the parser complexity, which is why it would be preferable to share the parsed module directly. Ideally the API would allow me to create an instance of a parser, set the parser options, and parse all modules with this parser. Later I could create a single compiler instance for each of HLSL/MSL/GLSL, set the compiler options, and compile each of the parsed modules.

Although I don't want to introduce maintenance cost to this repository to support a copy constructor or similar. I can work around it by re-parsing for now. That's why I was wondering if there is general interest in having a more explicit API for module parsing anyway. For example, it's not obvious to me whether some options relate to parsing or compilation without checking whether it's used during `parse`.

**Comment by HansKristian-ARM** [comment]
If you only want to parse things like decorations, extensions and generic SPIR-V stuff, you could just use spirv_cross::Compiler and use the reflection API. Using the base class is designed for those kinds of use cases where you don't want to emit code.

Parsing SPIR-V is very straight forward and cheap (op, length, data) chunks, I doubt the cost of doing this is significant, so I suspect the API will have to go much deeper than this to make a difference.

You could copy over the parsed SPIR-V instructions, or go a bit further and import decorations and strings. Even further, you can modify decorations on the base class, then import that into all compiler classes for which you want to emit code (HLSL, GLSL, MSL) ...

I'll mark this ticket as question, if there is a broader desire for this, we can consider how to expose it.

**Comment by grovesNL** [comment]
> Even further, you can modify decorations on the base class, then import that into all compiler classes for which you want to emit code

Yes, exactly! 😄 This is the kind of transformation I'd like to be able to share rather than set up independently per compiler.

I agree with your point about the reflection API in general. I suppose I prefer to keep the parser more general, like `SpirvParser`, rather than tie it to any particular compiler. But if I can copy that Compiler into the specialized compilers then the approaches are functionally equivalent.

For some additional context if you're wondering, the reason I'm asking about this is because I'm creating a [simple Rust wrapper](https://github.com/grovesNL/spirv_cross/blob/master/examples/src/hlsl/main.rs), and I'd like to split the parser/reflection into i.e. `SpirvParser` which is separate from the code emitting parts i.e. `HlslCompiler`, `GlslCompiler` `MslCompiler`.

**Comment by HansKristian-ARM** [comment]
It is possible to build just reflection standalone. The current CMake build for example has the core as a separate library you can link to. GLSL/HLSL/MSL are all separate libraries which depend on the core library.

**Comment by grovesNL** [comment]
To clarify, I meant separating the parser and compilers into separate objects rather than separate binaries. But that is useful to know.

**Comment by HansKristian-ARM** [comment]
This issue will be solved in #712, so closing this.
