### ISSUE TITLE
[Question] How to get the array size of a decoration?

### ISSUE THREAD

**Issue by Mercesa** [KhronosGroup/SPIRV-Cross#291]
Hello,

 I have a shader which contains this:
`layout(set = 2, binding = 0) uniform texture2D realTexture[24];`

I want to know how many textures are in this array but I am quite clueless on how to query this. This is essential if I want to generate descriptor layouts for Vulkan automatically.

**Comment by HansKristian-ARM** [comment]
When you get the resource, try this, should do what you want:
```
const SPIRType &type = compiler.get_type(resource.type_id);
if (type.array.empty()) // No array.
{
}
else
{
    unsigned array_size = type.array[0]; // Should be 24.
}

**Comment by Mercesa** [comment]
`for (auto& e : resources.separate_images)
	{
		const spirv_cross::SPIRType& type = compiler.get_type(e.base_type_id);

		if (type.array.empty())
		{
			std::cout << "no array" << std::endl;
		}
		else
		{
			unsigned array_size = type.array[0];
			std::cout << array_size << std::endl;
		}
}`

Constantly will end up in "no array", which seems a bit weird. I have recompiled my shaders several times, changed them a bit. Will look at the assembly now to see if it maybe optimizes something away but I doubt that.

**Comment by HansKristian-ARM** [comment]
Yes, don't use `base_type_id`, but `type_id` here. I am aware this distinction is rather weird, but SPIR-V builds up the type system hierarchically. This should be explained in the headers. `base_type_id` refers to the image type itself, while `type_id` refers to the completed, composited type, which is here the array.

**Comment by Mercesa** [comment]
Ah I see, thanks a lot. I overlooked the comments in the headers. Works now 👍
