### ISSUE TITLE
Invalid GLSL generated from HLSL SPIRV

### ISSUE THREAD

**Issue by Izman** [KhronosGroup/SPIRV-Cross#296]
Compiling HLSL into SPIRV using glslang and converting it GLSL using SPIRV-Cross seems to generate invalid GLSL when mapping vertex shader outputs to fragment shader inputs.

I've attached the shader and its spirv. The following commands were used to generate it:

`glslangValidator -D --amb --aml -S vert -Os -e VS -V100 shader.hlsl`
`glslangValidator -D --amb --aml -S frag -Os -e PS -V100 shader.hlsl`
`spirv-cross --es --version 100 vert.spv > vertex.glsl`
`spirv-cross --es --version 100 frag.spv > fragment.glsl`

The main issue is that the vertex shader's varying `_entryPointOutput_texcoord` doesn't match the fragment shader's varying `input_texcoord`. 

[shader.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1360431/shader.zip)

**Comment by HansKristian-ARM** [comment]
I will have a look.

**Comment by HansKristian-ARM** [comment]
Ok, so for the naming issue, this is a well known problem. You will need to rename interface variables to make sure they match. SPIR-V does not care about names:
https://github.com/KhronosGroup/SPIRV-Cross#vertexfragment-interface-linking

The fragment shader output you posted does not match what I get, so you might want to update SPIRV-Cross.

Here's the output I get:
```
./spirv-cross /tmp/vert.spv --rename-interface-variable out 0 TEXCOORD0 --version 100 --es
#version 100

struct VertexIn
{
    vec4 position;
    vec2 texcoord;
};

struct VertexOut
{
    vec4 position;
    vec2 texcoord;
};

struct _Global
{
    mat4 MVP;
};

uniform _Global _23;

attribute vec4 input_position;
attribute vec2 input_texcoord;
varying vec2 TEXCOORD0;

void main()
{
    gl_Position = input_position * _23.MVP;
    TEXCOORD0 = input_texcoord;
}
```
```
./spirv-cross /tmp/frag.spv --rename-interface-variable in 0 TEXCOORD0 --version 100 --es
#version 100
precision mediump float;
precision highp int;

struct VertexOut
{
    highp vec4 position;
    highp vec2 texcoord;
};

varying highp vec2 TEXCOORD0;

VertexOut _65;

void main()
{
    VertexOut _58 = _65;
    _58.position = gl_FragCoord;
    VertexOut _60 = _58;
    _60.texcoord = TEXCOORD0;
    gl_FragData[0] = vec4(_60.texcoord.x, _60.texcoord.y, 0.0, 1.0);
}
```
For the case when you have input/output structs (i.e. you have more than one varying), I have a PR in flight which should make --rename-interface-variables more useable. https://github.com/KhronosGroup/SPIRV-Cross/pull/297

**Comment by Izman** [comment]
Yeah it looks like my spirv-cross was a bit out of date. Didn't see the `--rename-interface-variable` argument.

It sounds like a convenient feature to have a command line argument that does this all for you -- like will rename all the locations to the name from the vertex shader or __locationN.

Nevertheless, this issue looks to be fixed.
