### ISSUE TITLE
Overriding parse() behaviour?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#301]
@HansKristian-ARM 

I've run into an issue where it seems the cleanest fix is to override behaviour while `parse()` is running...but, since `parse()` is called directly from the `Compiler` constructor, there is no opportunity to override any behaviour.

Specifically...MSL does not allow a specialized constant to be used as an array length. Therefore, if a constant is used as an array length, I want to turn off the `SPIRConstant::specialization` flag for that constant in `CompilerMSL`.

From what I can see...the easiest place to do this is in the `parse()` function when `OpTypeArray` is processed:

		<...>
		auto *c = maybe_get<SPIRConstant>(ops[2]);
		mark_as_array_length(c);
		bool literal = c && !c->specialization;

		arraybase.array_size_literal.push_back(literal);
		arraybase.array.push_back(literal ? c->scalar() : ops[2]);
		arraybase.parent_type = ops[1];

where the `mark_as_array_length ()` function would do nothing in `Compiler`...but in `CompilerMSL`, it would turn off the `SPIRConstant::specialization` flag. The rest of the existing code above would then automatically use the literal value of the constant as the array length...and so would all other uses of the constant for deriving array indexes, etc.

But alas...the overridden `mark_as_array_length ()` function is not called because `parse()` is running in the superclass constructor. Similarly...I can't set an option flag value (eg. `backend.allow_array_length_specialization`) anywhere in a subclass that would affect behaviour within the `OpTypeArray` section of the `parse()` function itself within that subclass.

Does it make sense to move the calling of `parse()` into the `compile()` function instead of the constructor, in order to allow overridden behaviour during parsing?

Otherwise...I'm going to have to write an ugly and costly function to hunt down all the constants and figure out which ones are used by arrays...and then turn off the `specialization` flag accordingly...AND convert the array length values to literals after all.

**Comment by grovesNL** [comment]
This is related to #287 as well. I was thinking it might be useful to move the other way and split parse out of the compiler class entirely, which could simplify the class hierarchy issues mentioned.

**Comment by HansKristian-ARM** [comment]
Right, the compiler constructor will be run so that virtual functions cannot work. As mentioned in #287 making the parsing dependent on backend is a bit problematic because this will break any hope of reusing compiler output.

Fixing the virtual stuff is pretty easy if we just defer the parsing to the subclass constructor, but I would like to keep the parsing verifyably backend neutral if possible.

Would it be possible to add an unordered_set in Compiler which marks which spec constants are used as array sizes, and CompilerMSL can trivially fix this up in its constructor or compile()?

Also, you cannot really turn array sizes into literals in parse(). Spec constants mean that you will have to resolve array sizes to literals in compile-time in MSL does not support this. Of course, at that time you can emit pure constants since you should have all spec constant information.

**Comment by billhollings** [comment]
@HansKristian-ARM 

I understand your interest in keeping `parse()` backend-neutral...and that makes sense until we find a compelling reason not to.

I thought about creating an unordered-set to keep track of constants that are used as array lengths, but I thought a more integrated (and easier to understand) mechanism might be to add a `is_used_as_array_length` flag to `SPIRConstant` which can be set during `parse() OpTypeArray`...and then, in a  `CompilerMSL compile()` pre-processing stage, used to turn specialization off on any `SPIRConstant` instance for which that is set.

I think I'll make running this a `CompilerMSL` API context switch too...so that this mechanism can be turned on or off at runtime. Specialized array-lengths is the kind of thing that Apple might introduce at some point (I'll file a request), and so might become unnecessary for some future platform or OS versions.

**Comment by HansKristian-ARM** [comment]
Adding a field which explains its usage to SPIRConstant also works, I'm fine with that.

**Comment by HansKristian-ARM** [comment]
Stale issue, closing.
