### ISSUE TITLE
Support for packoffset in the HLSL backend

### ISSUE THREAD

**Issue by rossy** [KhronosGroup/SPIRV-Cross#302]
Shader Model 4.0 seems to support explicit offsets in constant buffers with the [packoffset][1] keyword. It would be great if SPIRV-Cross could use this to replicate the UBO layout from the input SPIR-V. That way, code that uses the shader could use the same buffer layout for GLSL and HLSL targets.

One issue is that I think this will require removing the intermediate struct that SPIRV-Cross emits for UBOs, since packoffset only works on direct members of the cbuffer definition.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd607358.aspx

**Comment by HansKristian-ARM** [comment]
This won't really work when the UBO itself has structs inside it. The only way I think to support arbitrary offsets is to do something ala GLES and use flattened buffers, but there any more important issues to look at in HLSL atm I think.

**Comment by rossy** [comment]
Ah yeah, I didn't think of the struct case. I wonder if it would be easier to make the cbuffer contain a raw float4[] array and to address it manually. I noticed that SSBOs already kind of work like this with RWByteAddressBuffer::Load(), but it guess it also goes against SPIRV-Cross' stated goal of generating code that looks like it was written by a human (though it would be fine for our use-case.)

Something that would also work for us (but not really solve this bug) would be to add padding members to the HLSL structs so their layout matches std140.

**Comment by HansKristian-ARM** [comment]
SSBOs are a lost cause indeed, it is just not possible to implement it like GLSL and SPIR-V does it in a sensible way. HLSL's StructuredBuffer is only designed for one unsized array, but GLSL can mix and match a bit.

The "looking pretty" part is not a goal which should overrule everything else, sometimes compromises must be made.

**Comment by HansKristian-ARM** [comment]
It would help if you had some example code where lack of packoffset is a problem.

**Comment by rossy** [comment]
No problem. In our program we pack D3D11 constant buffers and GL/Vulkan UBOs with the same code. This code has already been taught to handle some of the differences between std140 and HLSL's default cbuffer layout, but we recently found an issue where it was incorrectly using std140 alignment for a vector in a cbuffer. (See mpv-player/mpv#4957. We will probably fix this issue, but it would be great if SPIRV-Cross could prevent these layout differences.)

The problem UBO layout:
```glsl
layout(std140, binding=0) uniform UBO
{
	layout(offset=0) float fcoord;
	layout(offset=16) vec3 src_luma;
	layout(offset=32) vec3 dst_luma;
	layout(offset=48) mat3 cms_matrix;
	layout(offset=96) vec2 texture_size0;
	layout(offset=112) mat2 texture_rot0;
	layout(offset=136) vec2 texture_off0;
	layout(offset=144) vec2 pixel_size0;
	layout(offset=152) vec2 texture_size1;
	layout(offset=160) mat2 texture_rot1;
	layout(offset=184) vec2 texture_off1;
	layout(offset=192) vec2 pixel_size1;
	layout(offset=200) vec2 texture_size2;
	layout(offset=208) mat2 texture_rot2;
	layout(offset=232) vec2 texture_off2;
	layout(offset=240) vec2 pixel_size2;
	layout(offset=248) vec2 texture_size3;
	layout(offset=256) mat2 texture_rot3;
	layout(offset=280) vec2 texture_off3;
	layout(offset=288) vec2 pixel_size3;
};
```

Compiles to this HLSL:
```hlsl
struct __22
{
	float _m0;
	float3 _m1;
	float3 _m2;
	float3x3 _m3;
	float2 _m4;
	float2x2 _m5;
	float2 _m6;
	float2 _m7;
	float2 _m8;
	float2x2 _m9;
	float2 _m10;
	float2 _m11;
	float2 _m12;
	float2x2 _m13;
	float2 _m14;
	float2 _m15;
	float2 _m16;
	float2x2 _m17;
	float2 _m18;
	float2 _m19;
};
```

In particular, our current issue is how HLSL packs a ``float`` followed by a ``vec3``.

In std140, vec3 has the same alignment as vec4, so it would be packed like this:
```
c0:  float   padding  padding  padding
c1:  vec3.x  vec3.y   vec3.z   padding
```

But HLSL cbuffer packing is more complicated. It uses tight packing for all scalars and vectors, except it doesn't allow a vector to straddle a constant boundary (float[4]). So HLSL would pack it like this:
```
c0:  float  vec3.x  vec3.y  vec3.z
```

It would be different if the float was followed by a ``vec4``, since in that case, it would straddle a float[4] boundary. So, for a ``float`` followed by a ``vec4``, both HLSL and std140 pack it loosely like this:
```
c0:  float   padding  padding  padding
c1:  vec3.x  vec3.y   vec3.z   vec4.w
```

We have also had a similar issue with a mat2 followed by a vec2, since HLSL will try to pack the vec2 into the padding after the last element of the mat2, but std140 will push it to a new constant. We have fixed this issue in our cbuffer packing code though.

I think in all cases, HLSL packing is tighter than std140 packing, so maybe this could just be solved by adding padding members to structs?

**Comment by HansKristian-ARM** [comment]
Ok, thanks for that explanation, I'll play around with fxc and see how feasible it is to just pad struct declarations, but short term fix is to avoid code which is known to behave differently on HLSL and GLSL.

**Comment by rossy** [comment]
Thanks for looking into this. As a video player, we only use a small subset of GLSL, so using SPIRV-Cross to cross-compile shaders on the fly has been working well for us so far. I will probably fix this issue on our side by changing our UBO packing code, but it would be great to have a long-term fix in SPIRV-Cross itself.

**Comment by HansKristian-ARM** [comment]
Didn't know that mpv is adding Vulkan support, very cool, I'll do what I can.

**Comment by rossy** [comment]
Thanks for the fix.
