### ISSUE TITLE
Fragment outputs incorrectly given a layout location in some versions of GLSL

### ISSUE THREAD

**Issue by akb825** [KhronosGroup/SPIRV-Cross#308]
After applying the fix provided in #306, I discovered that a similar issue exists for fragment outputs. I double checked the  [GLSL 150 standard](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.50.pdf) and it looks like the location layout parameter isn't allowed in any situation.

**Comment by akb825** [comment]
Similarly, GLSL ES 3.0 will generate locations for vertex output/fragment inputs (i.e. variables linked between the two), which is unsupported until GLSL ES 3.1.

**Comment by HansKristian-ARM** [comment]
Right. For ESSL, this check should already be in place for version < 310.

**Comment by akb825** [comment]
> For ESSL, this check should already be in place for version < 310.

I'm wondering if this is because I put my outputs in a struct.

    struct VertexOut
    {
        vec2 texCoord;
    };
    out VertexOut vertexOut;

gives:

    layout(location = 0) out vec2 VertexOut_texCoord;

**Comment by HansKristian-ARM** [comment]
Ah, right, that's for block outputs ... Need to apply the same check there I guess.

**Comment by HansKristian-ARM** [comment]
Block outputs should be fixed in latest PR.

**Comment by akb825** [comment]
Awesome, thanks for resolving these so quickly!
