### ISSUE TITLE
Short Question

### ISSUE THREAD

**Issue by twanks123** [KhronosGroup/SPIRV-Cross#31]
Hello just a short question,
is it possible to get the member-name of a struct? Say i have this

```
layout (set = 6, binding = 1) uniform Material_D
{
	vec4 color;
	float specularIntensity;
	float specularPower;
	float uvScale;
} material;
```
with
`        const spirv_cross::SPIRType& type   = comp.get_type(resource.type_id);`
i can get the member types, but i didnt find anything about the member names.
Is this possible?
Thanks in Advance 
P.S. For the future, where can i ask such questions?

EDIT:
My intention is to get the offset and size of a member through a name e.g. getOffset("specularPower") --> return a struct with { 20, 4 }

**Comment by HansKristian-ARM** [comment]
Hi, you can use comp.get_member_name(resource.base_type_id, index) to get names. You can use comp.get_member_decoration(resource.base_type_id, index, spv::DecorationOffset).

However, there is a special function to deal with UBO/push constant parsing like this:
comp.get_active_buffer_ranges(res.id), which returns this information for the members which are statically accessed in the shader.

**Comment by twanks123** [comment]
Thanks it works!
P.S. i was irritated by all the possible 'ids'. I used         
`const std::string& memberName = comp.get_member_name(resource.id, 0);`
instead of
`        const std::string& memberName = comp.get_member_name(resource.base_type_id, 0);`
which gave me always an empty string.
Thanks!
