### ISSUE TITLE
Uniforms in GLSL ES can't be linked together

### ISSUE THREAD

**Issue by akb825** [KhronosGroup/SPIRV-Cross#310]
When compiling for GLSL ES, the uniforms are declared differently between vertex and fragment shaders so they can't be linked together. (at least with the Intel driver)

For example:

    layout(push_constant) uniform Uniforms
    {
        mat4 modelViewProjection;
    } uniforms;

will be output as this in the vertex shader:

    struct Uniforms
    {
        mat4 modelViewProjection;
    }
    uniform Uniforms uniforms;

but like this in the fragment shader:

    struct Uniforms
    {
        highp mat4 modelViewProjection;
    }
    uniform Uniforms uniforms;

I tried adding a header line of `precision highp float;`, but this isn't sufficient. I also tried explicitly decorating the uniform with highp (before passing through glslang), but that didn't have any effect, at least on the Intel driver.

The error I'm getting is: `error: uniform 'uniforms' declared as type 'Uniforms' and type 'Uniforms'`. (i.e. it sees the structs as different types, even though they have the same name and the same members)

**Comment by HansKristian-ARM** [comment]
Sounds like a driver bug ... You can try --flatten-ubo perhaps to flatten buffer blocks like these to plain uniform arrays?

**Comment by akb825** [comment]
I tried flattening the buffer and the driver is able to link the shader. I can't readily test on other devices right now (I was just using my laptop to make sure I can run OpenGL ES at all), so I can't say if this affects more than just Intel. I'm curious, though: is there a reason why the precision is specified for fragment shaders but not vertex shaders?

**Comment by HansKristian-ARM** [comment]
Default precision for vertex is highp, while default precision for fragment is mediump (and all highp declarations are explicit). This can be modified in the spirv-cross API if that helps.

**Comment by HansKristian-ARM** [comment]
Closing, as it doesn't seem like a SPIRV-Cross bug, feel free to reopen if this is shown to be wrong codegen.

**Comment by akb825** [comment]
> Default precision for vertex is highp, while default precision for fragment is mediump (and all highp declarations are explicit). This can be modified in the spirv-cross API if that helps.

Thank you, setting the default precision to high worked around the problem.
