### ISSUE TITLE
Naming conflict in spirv_common.hpp

### ISSUE THREAD

**Issue by SinnersSumit** [KhronosGroup/SPIRV-Cross#313]
While using swig to create a C# wrapper for spirv cross, I ran into a problem at line 294 of spirv_common.hpp. The issue being, that the struct `SPIRType` contains a enum value named Image, and a nested type also named Image.

```
struct SPIRType : IVariant		// Line 246 of spirv_common.hpp
{
	enum
	{
		type = TypeType
	};

	enum BaseType
	{
		Unknown,
		Void,
		// ...
		Image,			// SPIRType::Image refers to this value
		SampledImage,
		Sampler
	};

	// Scalar/vector/matrix support.
	BaseType basetype = Unknown;
	
	// ...
	
	struct Image			// As such, this type is inaccessible
	{				// I recommend this type be renamed
		// ...
	} image;
};
```

Now I appreciate that for general use this works, however it horribly messes up the parsing of the header. My kludge was to simply rename the struct, then use a rename directive in swig to pretty things up.

I would suggest that the struct `Image` be renamed to something along the lines of `ImageTag`, or what ever the project's naming convention dictates appropriate. This shouldn't break any existing code because as far as I know there is currently no way to access the struct type.

**Comment by SinnersSumit** [comment]
I'm submitting this as an issue as I am completely new to git, otherwise I would just make the necessary changes myself.

**Comment by HansKristian-ARM** [comment]
Should be fine to rename that struct type if it creates friction for API wrappers.
