### ISSUE TITLE
Adding arbitrary metadata to SPIR-V

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#328]
I made a [demo](https://github.com/turol/smaaDemo) which uses SPIRV-Cross. I'm compiling shaders from source during runtime and then caching the SPIR-V because this is a relatively slow operation. Currently the cache invalidation only checks the main source file timestamp but not the included header file timestamps. This leads to trouble when the header files change. To check the header timestamps I'd need to store information about included headers and I'd like to keep it in the SPIR-V file as some kind of comment metadata.

Would it be possible to add something to SPIRV-Cross for this use case? Something like

```
void set_metadata(const std::string &key, const std::string &value)
const std::string &get_metadata(const std::string &key)
```

**Comment by HansKristian-ARM** [comment]
You can use add_header_line, and append whatever you want. You can probably put pragmas or comments here as you wish.

**Comment by turol** [comment]
That's not what I want, I want metadata which goes in the SPIR-V file, not the generated GLSL.

**Comment by HansKristian-ARM** [comment]
Gotcha, SPIRV-Cross does not emit or modify SPIR-V, so not sure this is the place to do it. There is no obvious generic "metadata" format defined for SPIR-V, so your best bet is probably to store this information as side-band information.

**Comment by turol** [comment]
Looks like side-band is my only option. Thanks anyway.
