### ISSUE TITLE
Ability to set entry-point name for spirv-glsl

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/SPIRV-Cross#34]
At least in Vulkan, the entry-point of the shader isn't a constant (main) but is given at shader compilation. Considering the use-case of having an abstraction layer over OpenGL and Vulkan that takes SPIRV for shaders, it seems very useful for spirv-glsl to be able to define at compilation time which function should be output as "main". Better, to save parse-time on the OpenGL driver-side, it would be good if only the main function's dependencies were output in the GLSL.

**Comment by HansKristian-ARM** [comment]
Indeed. This has been on the back burner for a while, but it shouldn't be too hard to implement. SPIRV-Cross already just emits the functions it needs statically from main(), so we probably just need a reflection interface for swapping out the entrypoints and handling the in/out variables per entry point appropriately.

**Comment by HansKristian-ARM** [comment]
Implemented in this PR:
https://github.com/KhronosGroup/SPIRV-Cross/pull/35

Is this kind of interface what you had in mind?

**Comment by Kangz** [comment]
Yep that would work perfectly, thank you!

**Comment by HansKristian-ARM** [comment]
Merged.
