### ISSUE TITLE
HLSL: unhandled storage image format "unknown"

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/SPIRV-Cross#342]
Hi,

the to HLSL translator throws an exception if it encounters a storage image with unknown target format.

**Comment by HansKristian-ARM** [comment]
Hm ... I'm unsure how this would be implemented in a sensible way as the format seems to have to be defined in RWBuffer<T> in most cases. Would float4/int4/uint4 fallback work?

**Comment by TiemoJung** [comment]
In our case its mostly float4, i also take a look at our compiler pipeline to emit the proper format info, if possible.
