### ISSUE TITLE
Question about structured buffers

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#345]
I'm having an issue with reflection information in glsl. A constant buffer declaration of the following format

```
struct MyStruct
{
    float a;
};

cbuffer g_MyStruct_CB
{
    MyStruct g_MyStruct;
};
```

gets translated to 

```
layout(std140) uniform g_MyStruct_CB
{
    LargeScaleAOParams g_MyStruct;
} _709;
```

However, a declaration for structured buffers like the following

```
StructuredBuffer<MyStruct> g_RO_MyStruct;
```

gets translated into

```
layout(std430) buffer _18_20
{
    MyStruct _data[];
} g_RO_MyStruct;
```

where I would expect

```
layout(std430) buffer g_RO_MyStruct
{
    MyStructuredBuffer _data[];
} _18_20;
```

I find this to be a little bit inconsistent and it's throwing off the reflection queries we do later (as we get back _18_20 instead of the name of the structured buffer). Is this intended or an overlook?

**Comment by HansKristian-ARM** [comment]
Hi, yes. Block reflection information is known to be a bit annoying atm. In HLSL, the "block" type is basically nothing, it's the "variable" name which is most relevant. However, in GLSL, the "block" name is the significant name, like
```
uniform BlockName { ... } internal_useless_name;
```
In HLSL, it seems to be
```
uniform UselessName { } NameOfCbuffer
```
The workaround is using `compiler.get_name(res.id)`.

**Comment by HansKristian-ARM** [comment]
Similar issue is: https://github.com/KhronosGroup/SPIRV-Cross/issues/195

**Comment by redorav** [comment]
Am I correct in thinking I can work around it by setting the block name to the useless name and viceversa through the reflection API? Ideally, we'd have this swapped by default if just for consistency.

**Comment by HansKristian-ARM** [comment]
yup, that works too. You can override the name of the block by setting compiler.set_name(res.base_type_id, "blockName")

**Comment by redorav** [comment]
It's a bit of a hassle though ^^ because it seems to validate the names so as not to repeat them? Anyway, it's possible so I'll work around it like this for now.

**Comment by HansKristian-ARM** [comment]
Yup ... There's no obvious solution here because doing this stuff automatically could be just as confusing. It might be best to add a utility function which would fix up block names automatically, but it'd have to be an explicit step.

**Comment by redorav** [comment]
I think this is a bug though. Why is doing it automatically as confusing? Reflection APIs that parse glsl surely treat the internal name (the instance name) and the real name (the name after the keyword uniform or buffer) in the same way?

**Comment by HansKristian-ARM** [comment]
Hm ... So, to make sure I understand the problem fully:

- When declaring a StructuredBuffer in HLSL, a buffer block is emitted such that:
The block type has no name (some internally generated type).
The instance name is whatever the name of the StructuredBuffer is.

- When reflecting for the block name, you get some weird, useless name back, because SPIRV-Cross is returning the block name, rather than the instance name.

- When compiling to GLSL, the block name is not set, so SPIRV-Cross will invent some magic name for it, but the instance name "makes sense".

The solution you want is:
- When reflecting for the block name, you'll want the instance name if it exists and block name does not exist.
- When compiling to GLSL, if block name doesn't exist, use the same fallback as for reflection.

**Comment by redorav** [comment]
Well, to be fair SPIRVCross seems to return the useful name when I query it (so res.name or calling compiler.get_name(res.id) actually returns the useful name), the issue is that for one platform we use glsl as input to another compiler, and that compiler's reflection expects the useful name to be consistent with the constant buffer naming convention.

I can't seem to get the internal name though, no matter what I try.

compiler.get_name(id) returns the useful name, 
compiler.get_name(type_id) returns empty, and 
compiler.get_name(base_type_id) returns the useful name too. (?)

**Comment by HansKristian-ARM** [comment]
So:
- compiler.get_name(id) returns the instance name (name of the block variable itself basically)
- compiler.get_name(type_id) is generally meaningless. It is the pointer to the block, or an array of the block type. You generally just use this to figure out if you have a descriptor array.
- compiler.get_name(base_type_id) returns the name of the block itself.

What do you mean by "internal name" here?

**Comment by redorav** [comment]
Sorry, I called internal name the useless name.

**Comment by HansKristian-ARM** [comment]
Oh ... I see what's going on ... HLSL now actually emits the name for both block and variable, but GLSL backend is probably tripping up the names because block and instance name alias and it cannot emit both ... This is clearly a bug, yes.

**Comment by redorav** [comment]
If by BlockName you mean

```
layout(std430) buffer BlockName
{
    StructName _data[];
} InstanceName;
```

then I think I'd be good with it. In my case I care about the name I've given to the block, not so much to the instance of it.

**Comment by HansKristian-ARM** [comment]
Ok, I'll make sure that BlockName always take precedence (and InstanceName will be a fallback), rather than other way around.

**Comment by HansKristian-ARM** [comment]
@redorav I have devised a solution which should solve your problems: https://github.com/KhronosGroup/SPIRV-Cross/pull/355. get_remapped_declared_block_name should be a bullet-proof way to figure out what the block was declared as in the shader.

**Comment by redorav** [comment]
That's great thanks! I'll try it out this week hopefully
