### ISSUE TITLE
Issue with structured buffer access

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#352]
I have an issue with a simple glsl shader sourced from hlsl.

```hlsl
RWTexture2D<float4> myTex;

struct CSInput
{
	uint3 groupId		: SV_GroupID;
	uint3 groupThreadId	: SV_GroupThreadID;
	uint3 dispatchThreadId	: SV_DispatchThreadID;
	uint groupIndex		: SV_GroupIndex;
};

[numthreads(8, 8, 1)]
void main(CSInput input)
{
    myTex[input.dispatchThreadId.xy] = float4(1, 1, 1, 1);
}
```

This gets translated into

```glsl
#version 430
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

struct _8
{
    uvec3 _m0;
    uvec3 _m1;
    uvec3 _m2;
    uint _m3;
};

struct _54
{
    vec4 _m0;
};

layout(rgba32f) uniform writeonly image2D myTex;

void main()
{
    imageStore(myTex, gl_GlobalInvocationID.xy, vec4(1.0));
}
```

However this doesn't work because there are no imageStore functions that take uvec, but instead they take ivecs exclusively (see https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/imageStore.xhtml). gl_GlobalInvocationID is defined as a uvec3 (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_GlobalInvocationID.xhtml), which becomes a problem. I'm a little bit confused as to why imageStore would have this limitation, and it seems like compilers can be more or less lenient with regards to this, but in essence, passing in a uint2 should work and I'm finding some compilers/toolchains assert on this. I'm having to cast everything to ints to appease it which is a bit annoying.

**Comment by HansKristian-ARM** [comment]
Yup, this class of problem is well known (GLSL has strict signedness, but SPIR-V doesn't), and there is scaffolding in SPIRV-Cross to resolve this class of issues, but I haven't plugged all the leaks yet :P

**Comment by redorav** [comment]
That's awesome, thanks :)
