### ISSUE TITLE
Question: Modify SPIRV decorations directly

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#362]
I have a small question. Is there a way for SPIRV-Cross to modify decorations in a SPIRV module that can later be saved again as SPIRV?

My use case is the optimizer's debug pass, which removes names from the module, I'd like to modify the names while still in SPIRV land, save it out, then pass it to a different stage that consumes it instead of renaming them on the destination language.

I've looked through the API but I can only find ways to compile to a different high level language.

**Comment by HansKristian-ARM** [comment]
Yes, there is, see: https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L386

**Comment by redorav** [comment]
Right, I suppose it can't be done then. I really like SPIRV-Cross's reflection API as it's really simple, it's just a bit of a shame I need to grab the reflection information before the optimization pass, optimize, then restore at a later stage when I'm translating to GLSL. Makes translating to say MSL need the same process, and also wouldn't allow me to load the SPIRV directly if we were to move to pure Vulkan.

Do you know if SPIRV-Tools allows this renaming?

**Comment by HansKristian-ARM** [comment]
Giving semantic meaning to names in SPIR-V is a bit shaky (OpName is purely a debugging thing), it's just annoying that it has semantic meaning in higher-level languages. I'm not sure if SPIRV-Tools can do this as-is with a convenient interface, maybe https://github.com/danginsburg/spirv-utils can.

Would it be possible to remove the name-stripping pass from the optimizer?

**Comment by redorav** [comment]
Well, the pass is called StripDebugInfoPass, so it removes more than just names. Further, I want it to remove all names except for the resource variables, essentially the inputs and outputs of the shader. Maybe I can create a bug for the SPIRVTools team see what they say about it.

**Comment by amerkoleci** [comment]
The ability to modify the SPIRV is something I would use it also, I would like to invert the gl_position y before sending SPIRV bytecode to vulkan, any thought on how to handle that scenario?

**Comment by HansKristian-ARM** [comment]
spirv-utils can flip Y, but a better approach is to use negative viewport height.
Modifying SPIR-V code is outside the scope of SPIRV-Cross, I'd suggest looking at other projects like SPIRV-Tools and spirv-utils which should be better candidates here.
