### ISSUE TITLE
is that possible convert SPV_KHR_variable_pointers to earlier version of spirv

### ISSUE THREAD

**Issue by lygstate** [KhronosGroup/SPIRV-Cross#366]
for some shading Language such as clspv , it's generated code may need SPV_KHR_variable_pointers, but for earlier version of vulkan, it's wouldn't support for SPV_KHR_variable_pointers， so is that possible to convert from spirv with SPV_KHR_variable_pointers to spirv without SPV_KHR_variable_pointers？

**Comment by HansKristian-ARM** [comment]
If by this you mean modifying SPIR-V to be compatible, I don't think so:
- Rewriting SPIR-V is outside the scope of SPIRV-Cross.
- variable_pointers is necessary to support actual pointers, i.e. a pointer can have a non-static address. This is not supported in most high level shading languages. There is no easy substitute.

**Comment by lygstate** [comment]
@HansKristian-ARM For example, I want to use clspv to creating a CNN implementation, and I need that would be possible running in Mobile devices, then SPV_KHR_variable_pointers would be needed:(, cause SPV_KHR_variable_pointers is a must be feature in clspv

**Comment by lygstate** [comment]
@HansKristian-ARM According to https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_variable_pointers.html, SPV_KHR_variable_pointers  is already a part of SPIR-V standard. So if my .spv binary code conatins extension SPV_KHR_variable_pointers, would it be possible convert to GLSL or Mental?

**Comment by HansKristian-ARM** [comment]
If the .spv contains SPV_KHR_variable_pointers, and makes use of the features in the extension, GLSL output will not work. If the extension is enabled, but does *not* make active use of the features, it should work.

Metal is in the same situation as GLSL for the time being.

**Comment by HansKristian-ARM** [comment]
I think this question is answered, closing.
