### ISSUE TITLE
Resource arrays

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#367]
Array of resources/descriptors are not translated correctly, at least for HLSL (haven't tested other backends so far).

GLSL example:
```
layout(set = 1, binding = 1) uniform texture2D u_Textures[3];
layout(set = 1, binding = 2) uniform sampler u_Samplers[3];
```
HLSL output (ignoring the `space` values):
```
Texture2D<float4> u_Textures : register(t1, space3);
SamplerState u_Samplers : register(s2, space4);
```
Expected output:
```
Texture2D<float4> u_Textures[3] : register(t1, space3);
SamplerState u_Samplers[3] : register(s2, space4);
```

**Comment by amerkoleci** [comment]
Still not sure why you get space3 and space4 when set is 1

**Comment by msiglreith** [comment]
@amerkoleci As mentioned, please ignore those values 😄 
We manually patch the space values to fit a specific root signature layout.

**Comment by HansKristian-ARM** [comment]
Will fix when I'm back from holidays.
