### ISSUE TITLE
GLSL gl_ViewportIndex undefined

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#368]
Hi,

I am trying to compile a geometry shader which sets a [gl_ViewportIndex](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_ViewportIndex.xhtml ) built-in, however in the output it turns into `gl_BuiltIn_10`.

```glsl
#version 450
#extension GL_NV_geometry_shader_passthrough : require
layout(triangles) in;
layout(passthrough) in gl_PerVertex { vec4 gl_Position; } gl_in[];

void main() {
	gl_ViewportIndex = 1;
}
```

```glsl
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
layout(triangles) in;
layout(max_vertices = 196611) out;

void main()
{
    gl_BuiltIn_10 = 1;
}
```

Am I missing something? Is `gl_ViewportIndex` not yet handled in SPIRV-Cross? I am trying to speed up the voxelization process by using passthrough-only geometry shader.

Using SPIRV-Cross through [krafix](https://github.com/Kode/krafix) & [glslang](https://github.com/KhronosGroup/glslang).

Thanks for help!

**Comment by HansKristian-ARM** [comment]
Will fix when I'm back from holidays.

**Comment by HansKristian-ARM** [comment]
Well, so there are two issues here, one being ViewportIndex and supporting a vendor specific extension, GL_NV_geometry_shader_passthrough, can this be split into two issues?

**Comment by luboslenco** [comment]
I see. Created the other issue at https://github.com/KhronosGroup/SPIRV-Cross/issues/379, edited the original post.
