### ISSUE TITLE
How to get array size of an array of sampled images

### ISSUE THREAD

**Issue by twanks123** [KhronosGroup/SPIRV-Cross#37]
Hello in my Shader-Code i have this:
`layout (set = 1, binding = 4) uniform sampler2D ShadowMap_S[16];`

I want to get the array-size from this (in this case: 16). I thought the "vecsize" from the type is it, but its always 1.

![vecsize](https://cloud.githubusercontent.com/assets/12892928/17622256/6bdb3fd8-6099-11e6-9164-bdc628f8f4b7.png)

BTW: What is "resources.storage_images"? My first thought was this are the arrays, but thats obviously not true.

**Comment by HansKristian-ARM** [comment]
You can use the type_id, which is the final type used in the variable (and not base_type_id, which is typically used for reflecting decorations on structs, etc). main.cpp has an example of how it parses array types.

https://github.com/KhronosGroup/SPIRV-Cross/blob/master/main.cpp#L202

storage images is used for image load/store, like uniform image2D foo.

**Comment by twanks123** [comment]
It doesnt work.
This is my ShaderCode for the sampler:
```
#define MAX_NUM_SHADOW_MAPS 12
layout (set = 1, binding = 4) uniform sampler2D ShadowMap_S[MAX_NUM_SHADOW_MAPS];
```
Array-size is always 1.

**Comment by HansKristian-ARM** [comment]
Are you sure you're checking type.array[0]? type.array.size() would be 1, because there is one array declaration. foo[10][20] would have type.array.size() == 2, type.array = { 20, 10 }.

**Comment by twanks123** [comment]
Oh yes, that works.. Thanks!!
