### ISSUE TITLE
Question: Constant buffers used in more than one shader stage

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#370]
Up until recently, we had a system where constant buffers were only used in one stage per shader. This has changed to allow for greater sharing, however I've come up with a problem. This problem is loosely related to https://github.com/KhronosGroup/SPIRV-Cross/issues/362. 

Typically we declare a constant buffer like this in hlsl:

```glsl
struct MyStruct
{
    float a;
}

cbuffer MyStructCB
{
    MyStruct g_MyStruct;
}

// Shader code accesses like g_MyStruct.a
```

This works fine after cross-compiling through glslang + SPIRVOpt + SPIRVCross. However, if I enable the StripDebugInfoPass in SPIRV-opt, the struct belonging to the constant buffer no longer has the same name in both stages (even though their contents, layout, etc are identical) and the glsl linker complains that two constant buffers with the same name (g_MyStruct_CB) don't use the same struct.

Here the constant buffers have the same name in both vertex and pixel shaders because I manually rename them via the SPIRV-Cross reflection (the names are lost after the StripDebugInfoPass). Is there a way to rename the structs as well as the constant buffers?

I feel like we do a lot of work by name but reading through the github comments and suggestions it seems like everyone just loses the names. Am I missing something fundamental in wanting metadata inside the shader for the interface variables?

**Comment by HansKristian-ARM** [comment]
Will look at it when I'm back from holidays.

**Comment by redorav** [comment]
Enjoy and Merry Christmas :)

**Comment by HansKristian-ARM** [comment]
So, the fundamental issue is that modern GLSL and SPIR-V are not languages where the names need to carry semantic value. Everything should be done using layout(location, binding, set) etc. These decorations are robust and carry through mangling, stripping, etc ...

Unfortunately, with legacy GLSL (and to some degree HLSL) we're still stuck with legacy link-by-name mechanics, and there is no ideal way to deal with it once names have been removed from the module. The best, and only way I can think of is to rename everything yourself according to some standard scheme to make sure that the names match.

It is possible to change the name of inner structs by looking at the struct type for a block, pick out member_types, get its SPIRType struct, and calling set_name() on SPIRType::self, but yes, this gets kinda tedious.

One possibility of solving this is to have some feature in SPIRV-Cross where it will go over all types and set up names automatically for you (mangled names) based on types and layout/binding/set, which would guarantee that if those decorations match across modules, they will end up with compatible names for legacy.

It gets more annoying if you need a very specific name (like, your engine expects names and not bindings numbers), no automatic magic will help in that case ...

The cleanest short-term solution I think is to avoiding stripping all semantic-bearing names in SPIR-V, but that solution falls outside SPIRV-Cross.

**Comment by HansKristian-ARM** [comment]
Closing as there hasn't been any activity in a long time.
