### ISSUE TITLE
Select/Deselect reference shaders based on platform/version being tested

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#372]
For MSL, I've encountered a couple of use cases where being able to select and deselect reference shaders based on characteristics of the build...such as a platform type (iOS vs macOS)...or even a shader language version (MSL 2.0 vs 1.2).

Essentially...some MSL functions and parameters are not available in all MSL versions and on all platforms. Apple distinguishes between iOS and macOS...and MSL versions.

Another example is the use of SPIR-V optimizations (`--opt`). Optimizations of certain complex shaders sometimes create SPIR-V that is not straightforward to convert to MSL. Since we have no control over changes to SPIR-V optimizations...it would be useful to be able to selectively deselect those shaders from the optimization run.

What are our options for an approach here? Could we start to differentiate shader directories and selectively run them for platforms, versions, and optimizations from `test_shaders.sh`? Or could we think in terms of selecting shaders based on characteristics (eg- maybe a platform & version shader naming convention)?

**Comment by billhollings** [comment]
PR #373 partially addresses this.

The MSL shaders that cannot be optimized have been moved to the new `shaders-msl-no-opts` folder.

MSL shaders in the `shaders-msl` are run both with and without optimizations. MSL shaders in the `shaders-msl-no-opts` folder are only run WITHOUT SPIR-V optimizations.

`CompilerMSL` now supports a platform (iOS or macOS) indicator to selectively output MSL according to platform requirements. This is in addition to the existing MSL version indication.

The ability to select this via the `spirv-cross` command line has NOT been implemented. Nor have any separate tests and reference shaders been developed for each separate platform...pending further discussion.

**Comment by HansKristian-ARM** [comment]
So, the original implementation also had certain shaders which refused to work properly with optimizations (glslang issues for the most part), for that case I tacked on .noopt. to the file name, but in hindsight with test_shaders.sh/update_test_shaders.sh now, it probably makes more sense to move those shaders to special folders as well. I don't mind that approach.

For dealing with OSX vs iOS specific shaders, I think it makes sense to use file names. I assume it will only be a handful shaders which should be tested specifically for iOS vs. OSX. Another route is to run iOS and OSX testing for all the MSL shaders, and opt out as necessary, either is fine with me.

**Comment by HansKristian-Work** [comment]
FWIW, I think this is resolved long ago.
