### ISSUE TITLE
GL_NV_geometry_shader_passthrough extension support

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#379]
```glsl
#version 450
#extension GL_NV_geometry_shader_passthrough : require
layout(triangles) in;
layout(passthrough) in gl_PerVertex { vec4 gl_Position; } gl_in[];

void main() {
}
```

[GL_NV_geometry_shader_passthrough](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_geometry_shader_passthrough.txt) extension and the `passthrough` qualifier get omitted in the resulting shader. I am trying to speed up the voxelization process by using passthrough-only geometry shader.

**Comment by devshgraphicsprogramming** [comment]
I second this.

**Comment by HansKristian-Work** [comment]
Alright, there isn't much else taking higher priority, so I'll consider this one. Don't think I'll get around to it before January though.

**Comment by HansKristian-Work** [comment]
Well, it only took two years, but hey, PR is up :tada:

**Comment by luboslenco** [comment]
Thanks!
