### ISSUE TITLE
Bad return value when debug info stripped

### ISSUE THREAD

**Issue by akb825** [KhronosGroup/SPIRV-Cross#38]
When generating GLSL on SPIR-V that had debug info stripped, 0 is returned in place of an empty string, causing an exception to be thrown when compiled as debug. Attached is the fix.

[fix.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/416393/fix.txt)

**Comment by HansKristian-ARM** [comment]
Ouch, that's bad. Thanks for the find. Pushed fix.
