### ISSUE TITLE
Invalid MSL generated for an optimized SPIRV shader

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#384]
Several of our more complex shaders convert to invalid MSL that can't be consumed by the MSL frontend. The shaders go through HLSL->glslang compilation step w/optimization; the output SPIRV is valid or at least the validator doesn't complain about it :)

The specific error is that the identifier is declared in one `do {} while (false)` block, and is used in another `do {} while (false)` block where it's not declared so it can't be found. This might be a recent regression - I haven't seen this before and we did test the optimized SPIRV output for the offending shader at one point, IIRC.

Offending MSL fragment; note that `_1124` is declared in one `do` block and used in another one.

```
    do
    {
        bool _1124 = 0.0 == 0.0;
        if (_1124)
        {
            _1132 = DiffuseMapTexture.sample(DiffuseMapSampler, _1024);
            _1517 = _1132;
            break;
        }
        else
        {
            float _1135 = 1.0 / (1.0 - 0.0);
            _1156 = mix(DiffuseMapTexture.sample(DiffuseMapSampler, (_1024 * 0.25)), DiffuseMapTexture.sample(DiffuseMapSampler, _1024), float4(clamp((clamp(1.0 - (_1396.View_Depth.w * 0.0033333334140479564666748046875), 0.0, 1.0) * _1135) - (0.0 * _1135), 0.0, 1.0)));
            _1517 = _1156;
            break;
        }
        _1517 = _1157;
        break;
    } while (false);
    float4 _1523;
    do
    {
        if (_1124)
        {
            _1178 = NormalMapTexture.sample(NormalMapSampler, _1024);
            _1523 = _1178;
            break;
        }
        else
        {
            float _1181 = 1.0 / (1.0 - 0.0);
            _1202 = mix(NormalMapTexture.sample(NormalMapSampler, (_1024 * 0.25)), NormalMapTexture.sample(NormalMapSampler, _1024), float4(clamp((_990 * _1181) - (0.0 * _1181), 0.0, 1.0)));
            _1523 = _1202;
            break;
        }
        _1523 = _1203;
        break;
    } while (false);
```

Also attaching complete SPIRV input and MSL output.

[shaders.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1612406/shaders.zip)

**Comment by zeux** [comment]
(note that the SPIRV in question can and should be optimized further; I filed https://github.com/KhronosGroup/SPIRV-Tools/issues/1182 for that, but assuming the SPIRV is valid SPIRV-Cross should still generate valid MSL)

**Comment by HansKristian-ARM** [comment]
Seen and fixed similar issues many times now, wonder what it is this time ... :)

**Comment by billhollings** [comment]
@HansKristian-ARM 

Are you able to look at this? It doesn't seem specific to MSL...and you certainly have more knowledge of the branching logic that I do!  `;^)`

Coincidentally...I have just encountered a similar failure in an unrelated, but similarly optimized, shader...

    do
    {
        float3 _10009 = normalize(in.m_3428);
        break;
    } while (false);
    float4 _23391 = _5152.sample(_3080, _10009);

...and fixing this should fix that too.

**Comment by HansKristian-ARM** [comment]
Yup, this is spirv_cross.cpp territory where it analyses the CFG and figures out dominating blocks for variables, thought I had plugged all the fixes, but guess not. spirv-opt finds new ways to break it once in a while. :p

**Comment by HansKristian-ARM** [comment]
Oh ... damn it, seems like we need full CFG analysis for temporary variables now as well :| Classic dominator-is-hiding-inside-a-fake-loop scenario, but for temporaries this time. I'll need to think about this.
