### ISSUE TITLE
void CompilerGLSL::emit_block_chain(SPIRBlock &block) will assert on Unreachable block

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#391]
Basically the switch statement doesn't handle the Unreachable block terminator. I'm not sure whether unreachable shouldn't even get here or is handled before, or should be gracefully handled here. Unreachable seems to be a noop according to the Terminator enum. 

I can try and cook a simple shader if it helps, although it's becoming quite time consuming to narrow down some of these.

UPDATE: I hacked in a dummy case label for my example and it seems to work (I was going by the intuition that a noop doesn't emit any code). Is it as simple as that?

**Comment by HansKristian-ARM** [comment]
Hm ... seems to be an oversight, should be trivial to add. Don't think I need a repro to test this.
