### ISSUE TITLE
Array out of bounds compile error

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#397]
This one might be simpler to fix. I have this shader that after translation reports an "array out of bounds". This is because the loop variable strips the "_" when accessing an array, and therefore a variable named _645 gets turned into 645, which is much bigger than the array.

[ArrayOutOfBounds_SPV.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1631849/ArrayOutOfBounds_SPV.TXT)

This is what it looks like:

```glsl
for (int _645 = 0; _645 < 1; _645++)
{
    vec3 _738 = _128.g_IrradLightsPS[645].params1.xyz - (_20.g_IrradianceVolumePopulatePS.irradVolumeMtx * ((vec4(fract(_676), fract(_670), floor(_676) / _20.g_IrradianceVolumePopulatePS.textureDimensions.z, 1.0) * 2.0) - vec4(1.0))).xyz;
```

I think this was introduced after I enabled the cfg_analysis option, as it wasn't happening before.

**Comment by HansKristian-ARM** [comment]
I think the SPIR-V is bogus:
```
        %848 = OpLoad %126 %128
        %837 = OpCompositeExtract %6 %848 0 645 2 3
        %839 = OpCompositeExtract %7 %848 0 645 1
        %841 = OpCompositeExtract %6 %848 0 645 0 3
        %843 = OpCompositeExtract %6 %848 0 645 1 3
        %845 = OpCompositeExtract %7 %848 0 645 0
        %847 = OpCompositeExtract %7 %848 0 645 2
```
OpCompositeExtract has literals here and using 645 makes no sense. I believe spirv-opt is trying to use the variable 645 to index into the uniform array, but it cannot index dynamically, it even loads the entire UBO to a temporary first :|

**Comment by redorav** [comment]
I see, I did update spirv-tools when trying to repro the other bug, I'll rewind to what I was using before and test. Might be the optimization going wrong.

**Comment by redorav** [comment]
Quick question while I do that, is this https://github.com/KhronosGroup/SPIRV-Cross/pull/399/commits/150b18733ffa08eea65734bd1bc2381b22bbd6c5 related to the bug?

**Comment by HansKristian-ARM** [comment]
No, separate issue (but this issue reminded me of it).

**Comment by redorav** [comment]
Ok, I can confirm that reverting to commit 

5eafc00 commit eb0c73dad6102fc0d4f03c62fe910348bae43a11 @alan-baker alan-baker committed 5 days ago

makes the problem go away. I'll make a bug for them and reference this.
