### ISSUE TITLE
Output interface block causes a crash when converting to metal

### ISSUE THREAD

**Issue by akb825** [KhronosGroup/SPIRV-Cross#40]
If you have the following GLSL code compiled to SPIR-V:

    uniform Transform
    {
        mat4 transform;
    } block;
    
    in vec3 position;
    in vec4 color;
    
    out VertexOut
    {
        vec4 color;
    } outputs;
    
    void main()
    {
        gl_Position = block.transform*vec4(position, 1.0);
        outputs.color = color;
    }

cross-compiling to metal will throw an exception in the function Compiler::get_member_decoration() because the meta members element is empty.

**Comment by akb825** [comment]
I should also mention that debug symbols were stripped from the SPIR-V. When debug symbols are left intact, it works fine.

**Comment by HansKristian-ARM** [comment]
Pushed a fix. Which commands are you using to strip debug symbols? Sounds like we should have a test run which strips out debug information from all shaders.

**Comment by akb825** [comment]
It appears to execute correctly now, though I should note I haven't tried executing any of the shader code. (I've been trying to get my shader compilation pipeline set up with as many targets as I can, even though I won't be using some of these targets for a while)

I am using the SPIR-V remapper provided by glslang to strip the debug symbols. However, when looking closer at some of the output, it looks like it also strips the names of the uniforms, which makes its utility rather limited.

**Comment by HansKristian-ARM** [comment]
I made a general ticket about testing debug-stripped binaries here: https://github.com/KhronosGroup/SPIRV-Cross/issues/43, so I'll close this ticket now.
