### ISSUE TITLE
More undefined variables

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#400]
I have cfg_analysis now on, but still getting undefined variable issues on a different shader. There are a few variables wrapped in a for(;;) that are being accessed at the very end.

The SPV in question is this.

[UndefinedVariables_SPV.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1635194/UndefinedVariables_SPV.TXT)

**Comment by redorav** [comment]
Never mind, I didn't have the latest SPIRV-Cross

**Comment by redorav** [comment]
Sorry again, it does still fail with latest SPIRV-Cross...

**Comment by HansKristian-ARM** [comment]
Okay, problem is understood.

**Comment by redorav** [comment]
Cool I'll test this soon

**Comment by redorav** [comment]
@HansKristian-ARM Just wondering what's up with Mac builds? They seem to be taking forever to compile.

**Comment by HansKristian-ARM** [comment]
Yes, it's annoying me as well ... Travis have reported that there is an issue with OSX atm, so I assume it's that.

**Comment by redorav** [comment]
I did a quick test and it looks like it's fixed. I'll let you know next week once I've done testing on a bigger set of shaders. I do have other bugs though...
