### ISSUE TITLE
GLSL setting float/int precision

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#401]
This seems like a basic thing but I am unable to figure it out. Writing `highp vec3 v = a - b;` compiles fine, however `highp` gets thrown away in the resulting shader. This is causing trouble on gles where it defaults to `mediump`. I need to manually specify `highp` for some values, is there a way to do so?

Using SPIRV-Cross through [krafix](https://github.com/Kode/krafix) & [glslang](https://github.com/KhronosGroup/glslang).

**Comment by HansKristian-ARM** [comment]
Generally if RelaxedPrecision is not present, highp will be emitted. Should work just fine, but I'll probably need some repros.

**Comment by HansKristian-ARM** [comment]
For example:
```
#version 450
layout(location = 0) in vec2 foo;
layout(location = 0) out float FooOut;

void main()
{
	float result = foo.x + foo.y;
	FooOut = result;
}
```
through SPIR-V and `spirv-cross test.spv --version 100 --es`:
```
#version 100
precision mediump float;
precision highp int;

varying highp vec2 foo;

void main()
{
    highp float result = foo.x + foo.y;
    gl_FragData[0] = result;
}
```

**Comment by luboslenco** [comment]
Argh, running the latest `glslang` and `spirv-cross` in `krafix` fixes the issue and it now works like in your example above.

I tried going the other way, manually specifying `mediump`:
```glsl
#version 450
in vec3 test;
out vec4 FragColor;
void main() {
	mediump vec3 v = test * vec3(0.5);
	FragColor = vec4(v.xyz, 1.0);
}
```

Results in `mediump` being discarded:

```glsl
#version 100
precision mediump float;
precision highp int;

varying highp vec3 test;

void main()
{
    highp vec3 v = test * vec3(0.5);
    gl_FragData[0] = vec4(v, 1.0);
}
```

We are not running through spirv-opt. I have also attached intermediate spirv. Perhaps the RelaxedPrecision is not there even though `mediump` was set?

[shader.frag.spirv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1652264/shader.frag.spirv.zip)

**Comment by HansKristian-ARM** [comment]
There is no RelaxedPrecision in that SPIR-V. I suspect you are compiling with GL semantics. mediump/highp does not mean anything in GLSL 4.5, and is probably just ignored. Tried using Vulkan GLSL? That should work.

**Comment by luboslenco** [comment]
Aha, that's likely it then! Thanks for the help, moving the issue to krafix to check on the Vulkan GLSL: https://github.com/Kode/krafix/issues/51.
