### ISSUE TITLE
Implicit cast and too little data in type constructor

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#403]
I have a shader that after optimization ("-O") does a somewhat weird thing, which incidentally also shows compilation errors.

[FRAGMENTPROGRAM_OPTIMIZED_SPV.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1647045/FRAGMENTPROGRAM_OPTIMIZED_SPV.TXT)

The resulting glsl shows the following at line 352:

```glsl
float _6568 = _6561 + ((SurfaceDesc(_3817, _2706.g_CameraPS.fs_invViewMtx * _3817, _3790, _2706.g_CameraPS.fs_viewportScaleBias.xy + (_9900 * _2706.g_CameraPS.fs_viewportScaleBias.zw), _3390, _4972, _3825, _5134 * _4972, _3829, mat3(vec3(_2706.g_CameraPS.fs_invViewMtx[0].x, _2706.g_CameraPS.fs_invViewMtx[0].y, _2706.g_CameraPS.fs_invViewMtx[0].z), vec3(_2706.g_CameraPS.fs_invViewMtx[1].x, _2706.g_CameraPS.fs_invViewMtx[1].y, _2706.g_CameraPS.fs_invViewMtx[1].z), vec3(_2706.g_CameraPS.fs_invViewMtx[2].x, _2706.g_CameraPS.fs_invViewMtx[2].y, _2706.g_CameraPS.fs_invViewMtx[2].z)) * _3829, _3833, _4979, _5161, _5134 * _3869, _3359 != 0.0, _2706.g_CameraPS.fs_invViewMtx, 2, _3404, _5066, _2513.g_MaterialPS.fs_specular_specular.xyz.zx, 1.0, true, vec4(0.800000011920928955078125, 0.5, 0.75, 1.0), vec4(-0.300000011920928955078125, 1.0, 0.0, 0.0), _2513.g_MaterialPS.fs_refraction_kIndex.x * 1.0, _2513.g_MaterialPS.fs_refraction_kIndex.z, _3409, 1.0 * _4189, _3848, false, 0.0, _3869, length(_3862), _5058, _5062, _5087, _5081, _5076, _5070).pixelNormal_viewspace.z > 0.0) ? 0.2509804069995880126953125 : 0.0);
```

All that long line is meant to do really is 
```glsl
pixelNormal_viewspace.z > 0.0) ? 0.2509804069995880126953125 : 0.0
```

and it constructs the entire struct just to read that one value. This would probably be ok-ish if it weren't causing compile errors. I get the following implicit casts:

1) vec2 to float
2) bool to float
3) vec4 to bool
4) float to vec4
5) float to vec3
6) float to bool

The last error however is more revealing:

"too little data in type constructor"

Is it possible that one of the parameters has been missed when constructing the struct and the implicit casts are just a consequence of this?

**Comment by HansKristian-ARM** [comment]
Will have a look first thing monday.

**Comment by HansKristian-ARM** [comment]
Fairly trivial bug after all. The merging that happens to swizzles in vectors (like, vec4(foo.x, foo.y, foo.z, 1.0) becomes vec4(foo.xyz, 1.0), was also applied falsely to struct construction.

**Comment by redorav** [comment]
> The merging that happens to swizzles in vectors (like, vec4(foo.x, foo.y, foo.z, 1.0) becomes vec4(foo.xyz, 1.0), was also applied falsely to struct construction.

That's awesome, I'll check it out soon. Hopefully there aren't many more. Getting everything working together is proving challenging but I think it's getting there. Thanks for your support.

> The weird case where a whole struct is created only to only pick out a single element afterwards is indeed what the SPIR-V is doing

Interesting to know, probably not a big deal, maybe one for the spirv-tools team.

**Comment by HansKristian-ARM** [comment]
I'm appreciating the tireless reporting of bugs, you're hopefully the first of many to make this trip. :)
