### ISSUE TITLE
[HLSL] problem with struct initialization

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/SPIRV-Cross#405]
Hi, after having updated SPIRV-Cross with the latest version, my generated HLSL outputs has been changed from this syntax:

```
struct aStruct
{
    float f;
    int i;
};

aStruct aFunction()
{
    aStruct res = { 0.0, 0 };
    return res;
}

```
To this one:
```
struct aStruct
{
    float f;
    int i;
};

aStruct aFunction()
{
    aStruct res = aStruct{ 0.0, 0 };
    return res;
}
```

Problem is that the HLSL compiler now returns an error with the new syntax:
error X3000: syntax error: unexpected token '{'

**Comment by HansKristian-ARM** [comment]
Ah right, this is a recent change indeed. Trivial to fix :)

**Comment by HansKristian-ARM** [comment]
Fix is in flight.

**Comment by Joojooo** [comment]
Awesome, thank you for the quick fix
