### ISSUE TITLE
Recent changes have introduced OpPhi initialization issue

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#407]
Recent changes (within the most recent 18 commits) have introduced an issue with OpPhi handling in certain circumstances.

           %7404 = OpPhi %13 %15154 %22801 %11264 %9010

causes the following MSL to be omitted:

            float _7404 = _0;

which of course fails compilation because of the `_0`.

This did not happen before.

The SPIR-V that causes this is: 
[OpPhiBug.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1657112/OpPhiBug.spv.zip)

The full log of the conversion is: 
[OpPhiBugLog.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1657108/OpPhiBugLog.txt)

**Comment by HansKristian-ARM** [comment]
I see. It falsely deduces that 7404 is a loop variable, and tries to initialize the static expression (which is ID 0). Working on a fix.
