### ISSUE TITLE
Declaring a constant buffer struct with the name of the constant buffer instead of the struct

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#409]
I have this SPIR-V

[DEFERREDLIGHTPS_OPTIMIZED.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1661206/DEFERREDLIGHTPS_OPTIMIZED.TXT)

that ends up producing code like the following:

```glsl
void main()
{
    float _4855;
    vec4 _4849;
    float _1956;
    vec3 _2333;
    vec3 _2374;
    float _2468;
    vec3 _3297;
    vec3 _3296;
    g_Light_CB _4842;
    vec3 _2504;
    float _2518;
    vec4 _4851;
```

Notice how variable _4842 is being declared as g_Light_CB instead of just Light.

**Comment by HansKristian-ARM** [comment]
Think I accidentally fixed it just now :D
Unrelated regression.

**Comment by HansKristian-ARM** [comment]
Will ping the ticket.

**Comment by HansKristian-ARM** [comment]
That PR fixes the two shaders you posted.

**Comment by redorav** [comment]
I'll check it out tomorrow, it's late now. Thanks!
