### ISSUE TITLE
Still getting undeclared variable issues

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#410]
For an example of this, see

[DEFERREDRENDERSSRPS_OPTIMIZED.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1661243/DEFERREDRENDERSSRPS_OPTIMIZED.TXT)

Variable _3209 is being used without being declared

**Comment by HansKristian-ARM** [comment]
And this too seems to have been accidentally fixed.
