### ISSUE TITLE
Missing parenthesis compile error

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#412]
I've been putting SPIRV-Cross through quite a big bunch of shaders, so far it seems to work well until it meets this one shader:

[FRAGMENTPROGRAM_OPTIMIZED.TXT](https://github.com/KhronosGroup/SPIRV-Cross/files/1665042/FRAGMENTPROGRAM_OPTIMIZED.TXT)

This produces the following line:

```glsl
 _8767 = ((vec3 _8754) * _5276.x) + vec3(_5276.y);
```

it's somehow trying to declare and use _8754 at the same time.

**Comment by HansKristian-ARM** [comment]
This shader does not pass spirv-val:
```
error: 459: The following forward referenced IDs have not been defined:
4689
```

**Comment by HansKristian-ARM** [comment]
This is associated with the phi node in question (8754), so don't think this is a bug.

**Comment by redorav** [comment]
Hmm, maybe I'll need to integrate spirv-val at some point to be able to distinguish between spirv-tools and spirv-cross bugs. Thanks for the quick reply, I'll take a further look then.
