### ISSUE TITLE
Broken multi-dimensional shared arrays on Metal

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/SPIRV-Cross#414]
Consider SPIRV generated from this GLSL piece ([full source](https://github.com/msiglreith/gfx_ocean/blob/ffc93f7ad0d8b7b60e54ab99f962f40e672d3c8f/shader/fft_col.comp#L23)):
```glsl
shared vec2 shared_row[2][512];
```
Generated metal code for it has the dimensionality erased:
```cpp
void butterfly(thread const uint& block_size, thread const uint& src, thread const uint& dst, thread uint3& gl_GlobalInvocationID, threadgroup float2* shared_row)
```
Thus, access to `shared_row` is broken: `shared_row[dst][dest]` indexes inside `float2`, producing the relevant MSL compile errors:
> assigning to `float` from incompatible type `float2`

cc @msiglreith @billhollings

**Comment by HansKristian-ARM** [comment]
I pushed a PR #416 which should fix it (passes test), but not sure if it's the appropriate way to do it. To support arrays-of-arrays it's probably best to have reference to array-of-array rather than go through pointers.
