### ISSUE TITLE
textureSize fails with create sampled images

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#418]
```glsl
#version 450

layout(set = 0, binding = 1) uniform texture2D u_Texture;
layout(set = 0, binding = 2) uniform sampler u_Sampler;

void main() {
    ivec2 dim = textureSize(sampler2D(u_Texture, u_Sampler), 0);
}
```

Converting the shader into spv and calling `spirv-cross --hlsl 60 frag.spv` fails with `SPIRV-Cross threw an exception: Combined image samplers have no default expression representation.`.

The following shader translates correctly:
```glsl
#version 450

uniform sampler2D texture;

void main() {
    ivec2 dim = textureSize(texture, 0);
}
```

We also received reports for other image instructions failing with the same error: https://github.com/gfx-rs/gfx/issues/1784

**Comment by HansKristian-ARM** [comment]
You need `--shader-model 60` there I think.

**Comment by msiglreith** [comment]
Sry, typo. I actually ran it with the shader model flag
```
spirv-cross --hlsl --shader-model 60 frag.spv
SPIRV-Cross threw an exception: Combined image samplers have no default expression representation.
```

**Comment by HansKristian-ARM** [comment]
Ah, right. Should be a trivial fix.
