### ISSUE TITLE
Invalid glsl generated from hlsl Texture2D Load()

### ISSUE THREAD

**Issue by mikeh001** [KhronosGroup/SPIRV-Cross#424]
With the following test HLSL code does a texture load without a sampler and I don't think it's possible to generate valid GLSL from the resulting SPIR-V. But spirv-cross doesn't fail - it just produces invalid GLSL. I don't think spirv-cross can generate the correct GLSL without being given a bound sampler but it would be better if it issued an error instead of generating invalid code.
```
// begin test.hlsl:
Texture2D g_xTexture : register(t0);

float4 main( float4 xIn : SV_Position ) : SV_Target
{
	int3 xUVMip = int3(xIn.x * 1280.f, xIn.y * 720.f, 0);
	float4 xOutput = g_xTexture.Load( xUVMip );

	return xOutput;
}
// end test.hlsl
```

// convert hlsl to spir-v
glslangvalidator -D -V -S frag -e main test.hlsl -o test.spv
// convert spir-v to glsl
spirv-cross test.spv --output test.glsl
// validate and convert to spv
glslangvalidator -V -S frag test.glsl
// ERROR: test.glsl:7: 'g_xTexture' : undeclared identifier

// convert spir-v to glsl with vulkan semantics
spirv-cross test.spv --vulkan-semantics --output test.vulkansemantics.glsl
// validate and convert to spv
glslangvalidator -V -S frag test.vulkansemantics.glsl
// ERROR: test.vulkansemantics.glsl:9: 'texelFetch' : no matching overloaded function found

**Comment by HansKristian-ARM** [comment]
Right ... This is a GLSL limitation which needs to be fixed in Vulkan GLSL. SPIRV-Cross should throw an error here instead.

**Comment by mikeh001** [comment]
Would you consider an enhancement where you can specify a binding for a point sampler which can be assumed to exist, and is used to generate a sampler2d? e.g. adding a command line argument of "--texel-fetch-sampler-binding=1,1" would result in adding this to the GLSL
`layout(set = 1, binding = 1) uniform sampler g_xSPIRVCROSS_Sampler;`
and instead of outputting
`texelFetch(g_xTexture, ivec3(int(gl_FragCoord.x * 1280.0), int(gl_FragCoord.y * 720.0), 0).xy, 0);`
it outputs
`texelFetch(sampler2D(g_xTexture, g_xSPIRVCROSS_Sampler), ivec3(int(gl_FragCoord.x * 1280.0), int(gl_FragCoord.y * 720.0), 0).xy, 0);`

**Comment by HansKristian-ARM** [comment]
It could be possible to add some kind of API where you do that (have SPIRV-Cross hallucinate a new sampler for this purpose), but it wouldn't help regular desktop GLSL which only supports combined image samplers. Sounds really painful either way.

**Comment by HansKristian-ARM** [comment]
I think I know how I will implement this now, but need to do this after the dust has settled on some more critical bugs.
