### ISSUE TITLE
gl_NumWorkGroups in HLSL

### ISSUE THREAD

**Issue by rossy** [KhronosGroup/SPIRV-Cross#429]
I'm trying to compile a shader that uses gl_NumWorkGroups, but it seems like HLSL doesn't have an equivalent semantic. Would there be another way to support this builtin? Since gl_NumWorkGroups should be known when the compute shader is dispatched, the calling program could probably store the value in a cbuffer and the shader could read it out, though that would require the calling program and the shader to agree on the format and binding location of the cbuffer.

Would this be feasible to implement in SPIRV-Cross?

**Comment by HansKristian-ARM** [comment]
yup, will need to emit some kind of special cbuffer. Shouldn't be too hard.
