### ISSUE TITLE
Subpasses in MSL and HLSL

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/SPIRV-Cross#435]
Sorry for all the issues 😅 Given the following GLSL:

```glsl
#version 450 core
#extension GL_ARB_separate_shader_objects : enable

layout(input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput test;
layout(location = 0) out vec4 out_color;

void main() {
    out_color = subpassLoad(test);
}
```

`../glslang-build/standalone/glslangvalidator test.frag -V; and ../spirv-cross/spirv-cross frag.spv --msl` creates the following MSL (silently fails with `unknown_texture_type`):

```metal
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 out_color [[color(0)]];
};

fragment main0_out main0(unknown_texture_type<float> test [[texture(0)]])
{
    main0_out out = {};
    out.out_color = test.read(int2(0));
    return out;
}
```

`--hlsl` with a high enough shader model will throw an exception.

I realize this is  because `DimSubpassData` is not handled at the moment for [MSL](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.cpp#L3128) and [HLSL](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_hlsl.cpp#L262). I was wondering whether implementing this in MSL should be as straightforward as the HLSL comment suggests, or if you have any thoughts about how it should be handled.

**Comment by HansKristian-ARM** [comment]
Neither are supported currently, but shouldn't be that hard to add.
