### ISSUE TITLE
"Cannot resolve expression type" while translating optimized SPIRV

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#437]
Translating the shader before running it through spirv-opt succeeds.
Translating the shader *after* running it through spirv-opt fails with:

> Cannot resolve expression type

The validator doesn't fail on the optimized shader but it might be an omission to the validator; I'm looking into what exactly happens here. Also, would it be possible to improve the exception text to note the instruction/id that is problematic?

[shader32.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1700346/shader32.zip)

**Comment by zeux** [comment]
Looks like it's this OpIAdd:

       %7127 = OpSelect %int %3220 %7058 %7058
       ...
       %3326 = OpIAdd %int %7127 %int_1

This seems valid to me, so I'm assuming it's a SPIRV-Cross bug. The type field of OpSelect result is 0 (TypeNone) for some reason...

**Comment by HansKristian-ARM** [comment]
Huh ... well, it seems like the block where 7127 is generated is never actually used. It might be dead code (and dead code cannot dominate live code), need to dig a bit deeper, but currently points to a bug in the SPIR-V.

**Comment by zeux** [comment]
Here's the CFG:

![shader32-afteropt](https://user-images.githubusercontent.com/1106629/36106255-abbab1fa-0fcb-11e8-8118-fc8b4f7bd819.png)

Unless I'm misreading the SPIRV, it looks like OpIAdd is generated in block 3251, and the OpSelect argument is generated in block 3221. Is the issue the continue from 3128 to 3251, which leaves 3221 unevaluated?

**Comment by zeux** [comment]
Ok - looking at this closer I'm pretty sure this is just a SPIRV-Cross bug. Block 3251 is the continue block, and the OpIAdd in question is incrementing the induction variable. For whatever reason the left hand of the increment is a dummy OpSelect computed in block 3221 - but this is all valid as far as I can see.

The issue occurs because SPIRV-Cross goes into this branch:

    // This is the older loop behavior in glslang which branches to loop body directly from the loop header.
    if (block_is_loop_candidate(block, SPIRBlock::MergeToSelectForLoop))

And emits continue block *before* the body; in this case, continue block requires 3221 to be emitted first. If I change the code to disable loop emission like this:

    if (block_is_loop_candidate(block, SPIRBlock::MergeToSelectForLoop) && 0)

Then SPIRV-Cross emits `for (;;)` loop instead without issues. I'm not sure what a general solution to this looks like though.

**Comment by HansKristian-ARM** [comment]
Normally, SPIRV-Cross should handle temporaries and variables being touched in the continue block. There is a "hoisting" pass. It might be as simple as something missing there ... I'll have a look.

**Comment by HansKristian-ARM** [comment]
Herp, derp. One-liner fix <_<
