### ISSUE TITLE
Inactive variables

### ISSUE THREAD

**Issue by hiddenbitious** [KhronosGroup/SPIRV-Cross#44]
I'm generating spir-v using glslang. Although shader reflection from glslang correctly reports only active variables (varying inputs/outputs, ubos etc), they appear in the generated spir-v. 

SPIR-Cross lists these variables when doing print_resources(). Is there a way to prevent inactive variables from being listed in shader resources?

**Comment by HansKristian-ARM** [comment]
I have been thinking of adding an option to detect all inactive global variables (based on static function call graph from selected entry point) and be able to remove them from all consideration.

It is possible to do this manually using the call graph traversal interface (I think it's marked private though), but that's a bit heavy handed. I can look at adding a more dedicated interface for this.

**Comment by hiddenbitious** [comment]
If it's a big fuss maybe it would me better if these variables weren't in the spir-v in the first place. Looks more like the compiler's job to discard inactive variables

**Comment by HansKristian-ARM** [comment]
Ye, the compiler would ideally do this, but with multiple entry points it gets more annoying since some variables can be used in one entry point and not the other, so the compiler cannot solve the entire problem alone.

**Comment by hiddenbitious** [comment]
> It is possible to do this manually using the call graph traversal interface (I think it's marked private though)

You mean traverse_all_reachable_opcodes() or parse()?

**Comment by HansKristian-ARM** [comment]
traverse_all_reachable_opcodes.

**Comment by hiddenbitious** [comment]
I'm thinking of doing a workaround tailored for my needs, by trying to add reference counters that parse() will increase accordingly. Do you believe it will work?

**Comment by HansKristian-ARM** [comment]
I've implemented a more proper method of doing this, will make a PR soon.

**Comment by hiddenbitious** [comment]
Ah many many thanks :+1:

**Comment by HansKristian-ARM** [comment]
Try this PR: https://github.com/KhronosGroup/SPIRV-Cross/pull/45
Example is provided.
