### ISSUE TITLE
HLSL: ClipDistance builtin not supported

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#445]
Vertex shader:
```
#version 450

out gl_PerVertex
{
    vec4 gl_Position;
    float gl_ClipDistance[];
};

void main()
{
    gl_Position = vec4(0.0);
    gl_ClipDistance[0] = 0.0;
}
```
`spirv-cross.exe clip_distance.spv --hlsl` will emit
`SPIRV-Cross threw an exception: Unsupported builtin in HLSL: 3`

**Comment by HansKristian-ARM** [comment]
Does HLSL even have ClipDistance? This might be a similar situation to gl_PointSize which isn't supported either.

**Comment by msiglreith** [comment]
`SV_ClipDistance` should provide the same semantic (https://anteru.net/blog/2016/mapping-between-hlsl-and-glsl/index.html)

**Comment by msiglreith** [comment]
Awesome! Works in my testcase 👍
