### ISSUE TITLE
MSL does not honour different alignment packing in shader struct-packing.comp. How to handle?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#447]
For MSL...`struct-packing.comp` converts and compiles...however...it does not support the fact that the `Content` struct has two completely different packing alignment requirements when it appears in two different parent structs...one of which is defined with `std140` packing and the other is defined with `std430`.

The `type_alias` feature of `Compiler` aliases one to the other...and only one `Content` structure is output.

If this MSL was used in a real-world application...it would presumably fail on the alignments of one or the other buffers.

Since MSL is based on C++, I expect it would actually need two completely separate struct definitions for the `Content` struct...and it's not at all clear how MSL conversion should handle this.

One option might be to output two different `Content` base structs...with different names...and different alignment specifications (either padding or `alignas` specifiers.

But on first blush...that sounds pretty complex and intrusive.

I'm throwing this out here with the idea to generate some discussion.

Is this a contrived situation? Should we be trying to deal with this...or can we insist on consistent packing across all buffers that use the same base structures?

If not...what approaches can we consider to make this happen?

**Comment by HansKristian-ARM** [comment]
This should work now with type_alias overhaul. Multiple struct types will be generated.
