### ISSUE TITLE
Correct Spir-V not correctly translating to GLES due to extension

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#46]
Hi,

I'm currently trying to get desktop glsl to gles but I've come across a problem. In desktop glsl, you can sample a texture by creating texture2d and sampler objects in the shader. This is the behavior I'm getting after translating both valid glsl and the experimental hlsl support in glslang. They both produce correct Spir-V as far as I can tell.

However, if I use SPIRV-Cross to try and translate that Spir-V into glsl-es, it asserts saying that the GL_ARB_shader_image_load_store is required.

How is this normally handled? If the Spir-V is valid, should it not compile to everything, perhaps falling back to normal texture sampling and issuing a warning?

**Comment by HansKristian-ARM** [comment]
This sounds like you're trying to use separate sampler/images. This is a Vulkan GLSL feature, not desktop GLSL. It is not really possible to translate this directly to regular GLSL as GLSL does not support this feature.

However, GL_ARB_shader_image_load_store is probably reported wrongly, it is probably triggering on texture2D, although it should only trigger on image2D. What it should do is report use of separate sampler/images.

A fallback for separate image/sampler sounds reasonable, but not sure how to best handle it.

**Comment by redorav** [comment]
Huh, what's the difference between Vulkan GLSL and Desktop GLSL? I thought the language itself was the same.

If I use a 
```
sampler2D s;
vec4 c = texture(s);
```

 in glsl, translate to spir-v and then back to glsl-es, it correctly gets translated to

```
sampler2D s;
vec4 c = texture2D(s);
```

I'm guessing this is what the fallback should be for opengl-es.

When you say GL_ARB_shader_image_load_store is unrelated, what do you mean?

**Comment by ratchetfreak** [comment]
@redorav https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt

**Comment by HansKristian-ARM** [comment]
Ok, I might be misunderstanding. @redorav, can you paste the shader you can trying to use?

**Comment by redorav** [comment]
This is roughly the same glsl the hlsl -> spir-v -> glsl process gets me after conversion. It complains if I try to do hlsl -> spir-v -> gles 100 which is why I started investigating, assembled this glsl shader, put it through glsl -> spir-v -> gles 100 and it still goes wrong. I hope it's a bit clearer now.

```
#version 140

precision highp float;

struct MyConstantBuffer
{
	vec4 tintColor;
	vec4 uvCoords1;
	vec4 uvCoords2;
};

uniform texture2D g_myTexture2D;
uniform sampler g_myTexture2DSampler;

out vec4 _entryPointOutput;
MyConstantBuffer g_MyConstantBuffer;

void main()
{
	vec4 color2D = texture(sampler2D(g_myTexture2D, g_myTexture2DSampler), g_MyConstantBuffer.uvCoords1.xy);
	_entryPointOutput = color2D;
}
```

**Comment by HansKristian-ARM** [comment]
Ok, so it seems like HLSL makes use of separate sampler images. It is not currently possible to convert this to desktop GLSL or ESSL (only Vulkan GLSL).

I'll look into fixing the error message, and try to find a way to do separate sampler/images in regular GLSL.

A simple implementation can enforce that a texture can only be used with one of the samplers at a time, so that texture2D can be promoted to sampler2D instead.

**Comment by redorav** [comment]
For my use case in HLSL, in general, we associate a single sampler state with a texture, and although that need not be the case,  it would definitely help if the system could detect it and like you say, promote to a sampler2D.

A more general option would be to create individual sampler2D objects for every sampler/image combination if the GLSL/ESSL spec just doesn't support them.

**Comment by HansKristian-ARM** [comment]
I'll get to this as soon as I have time.

**Comment by HansKristian-ARM** [comment]
Reflection support for separate sampler/textures is added and fixed the issue with texture2D being treated as image load store in ESSL.

Next up is a complete implementation where all statically used texture/sampler combinations (even through function calls) will be supported.

**Comment by HansKristian-ARM** [comment]
Implemented combined image sampler support here:
https://github.com/KhronosGroup/SPIRV-Cross/pull/48

Except for arrays of textures and arrays of samplers, it should fully support the feature.
