### ISSUE TITLE
special float constants produce invalid GLSL

### ISSUE THREAD

**Issue by paniq** [KhronosGroup/SPIRV-Cross#461]
If a floating point constant is nan, the generated code is invalid. Here's some example output:
```
float _392(vec2 _391)
{
    return _398(_391 * vec2(-nan.0));
}
```

**Comment by HansKristian-ARM** [comment]
+Inf/-Inf/NaN would need "special" constants, there is no way to express these natively in GLSL.

**Comment by paniq** [comment]
i only service modern targets so a partial solution based on uintBitsToFloat() would be fine for me
