### ISSUE TITLE
HLSL: Point coords with compat mode

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#462]
There currently is a compatibility mode for points or rather pointsizes (ignoring them). Unfortunately, even with the compat mode the point coordinates builtin isn't supported and will throw an exception. Could this be handled somehow?

**Comment by HansKristian-ARM** [comment]
I don't know what the appropriate solution is here considering SV_PointCoord does not exist (and neither does SV_PointSize).

If you are faking point sprites with quads we'll need to plumb through a custom semantic (which will be really painful if we want point sprites to work transparently on DX), or I could just say that gl_PointCoord is constant (0.5, 0.5). Technically, this isn't correct, but it's probably the only realistic workaround. PointCoord is kind of meaningless without point sprites.

**Comment by msiglreith** [comment]
Yes, setting gl_PointCoord to (0.5, 0.5) seems to be way to go for now imo.

Emulating point sprites via quads would be a goal in the future (really low priority for me), but I guessed this could be also solved in an independent transformation pass before feeding the SPIR-V shader code into SPIRV-Cross, not sure what the best direction would be here.

**Comment by HansKristian-ARM** [comment]
Yes, that kind of transform could be done outside SPIRV-Cross if need be ... Or application could just write portable point sprites. :) I'll implement vec2(0.5) hack for now.
