### ISSUE TITLE
HLSL: Implicit derivatives in non-uniform control flow

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#463]
GLSL and SPIR-V define implicit derivatives as undefined in the specification in contrast to HLSL which seems to like these cases (e.g Sample in non-uniform control flow) and try to unroll the loop.
Would there be a way to workaround this, considering the derivatives are undefined? For example, detecting requirement for implicit derivatives and set hardcoded ones like emitting `SampleLod(0)` instead of `Sample`?

**Comment by HansKristian-ARM** [comment]
Uh ... How would HLSL give you sensible (i.e. non-undefined) derivatives in non-uniform control flow?
I'm not sure I see the issue here, SPIR-V requires that control flow is uniform on implicit LOD, so compiling to HLSL or any other target should just ... work? HLSL -> SPIR-V sounds like the problem case here if HLSL is more lax than SPIR-V, but that's not SPIRV-Cross' issue.

**Comment by msiglreith** [comment]
Hm, the offending shader is here: https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/parallax/parallax.frag#L73-L80
Compiling from spv -> HLSL gives me shader errrors due to HLSL trying to unroll the loop but fails after 1024 unrolls

**Comment by HansKristian-ARM** [comment]
Wait, so, HLSL has to assume the worst, and even try to unroll "correct" code even with dynamic loop counter? ... Wow :(

SampleLod(0) is just plain incorrect, so that's not a solution.

**Comment by msiglreith** [comment]
right.. I just saw that `Code motion` section which prohibits implicit derivatives in non-uniform control flow (TIL). Couldn't find a corresponding restriction in the GLSL specification so far beside being undefined, but need to look again.

**Comment by HansKristian-ARM** [comment]
There is definitely such a restriction in GLSL as well.

**Comment by msiglreith** [comment]
Reconfirmed that the generated spv code is illegal https://github.com/KhronosGroup/SPIRV-Headers/issues/58#issuecomment-371019137
The corresponding code sections have been changed https://github.com/SaschaWillems/Vulkan/issues/425
Closing this, thanks!
