### ISSUE TITLE
Ambiguous entry point names in `get_entry_point`

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/SPIRV-Cross#476]
From the SPIR-V specification:

> Name is a name string for the entry point. A module cannot have two OpEntryPoint instructions with the same Execution Model and the same Name string.

In `get_entry_point` we don't specify which execution model to search. So if there is an `OpEntryPoint` with a duplicate name, we may return the incorrect entry point.

For example, when we use `get_cleansed_entry_point_name` we only pass a string for the name. But if the SPIR-V contains two entry points with the same name but different execution models (i.e. both named `main` for vertex and fragment), we have no way to distinguish between which `main` is the entry point we're searching for. I also expect this probably breaks `rename_entry_point` and some other methods.

I'll try to create a sample shader later.

**Comment by HansKristian-ARM** [comment]
Ok, probably just have to add an optional execution model argument to those functions to disambiguate.
