### ISSUE TITLE
MSL: The fragment function output structure may not include a matrix or array.

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#478]
This shader can't be converted to MSL:

```
#version 450

layout(location = 0)
out vec4 frag_RastData[1];

void main()
{
	frag_RastData[0] = vec4(0.0);
}
```

With the following error:

> SPIRV-Cross threw an exception: The fragment function output structure may not include a matrix or array.

There are potentially two issues here:

- arrays with size 1 should be supported
- arrays with size N should be supported (for MRT output)

**Comment by HansKristian-ARM** [comment]
Is this an MSL restriction? I.e. must the fragment outputs be unrolled in the shader?

**Comment by zeux** [comment]
From MSL spec:

![image](https://user-images.githubusercontent.com/1106629/37216728-62d81e1a-2370-11e8-9906-897c27aa4288.png)

So yeah I believe arrays should be unrolled with the appropriate attributes (like color(0), color(1), color(2) for 3 color outputs)
