### ISSUE TITLE
Support true half precision (16 bit floats) for HLSL and GLSL backends..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#484]
Hi,
I'm testing half output support ("true 16 bit float output") on all backends from a SPIR-V using halfs, I mean it has things like:

>     OpCapability Float16
>     OpExtension "SPV_AMD_gpu_shader_half_float"
>     %half = OpTypeFloat 16
>     %v2half = OpTypeVector %half 2

this SPIR-V file in fact is generated from either:
1) from GLSL using glslangValidator and shaders with:

>  #extension GL_AMD_gpu_shader_half_float: enable
> and using f16vec2 

(**see #define vec2 f16vec2** in attached shaders file at the end)

glslangValidator  --target-env vulkan1.0 -e main -S  comp -DWIDTH=1920 -DHEIGHT=1080 -DWORKGROUP_SIZE=32 shaderfp16.comp -o shaderfp16.comp.spv

2) from HLSL using min16float and DirectXShaderCompiler (originally had minor issues which had since then been fixed (https://github.com/Microsoft/DirectXShaderCompiler/issues/1095)):
as currently glslangValidator doesn't have support for mapping min16float to SPIR-V "OpTypeFloat 16" yet.. (see https://github.com/KhronosGroup/glslang/issues/1271)

dxc.exe -E CSMandelJulia_scalarFloat test.hlsl -enable-16bit-types -T cs_6_2 -spirv -O0 -Vd

(see DXC  requires -enable-16bit-types argument to map to "OpTypeFloat 16" if not is mapped as float) 
either way,from GLSL or HLSL code using halfs, I'm able to obtain 16bit float SPIR-V code:

>     OpCapability Float16
>     OpExtension "SPV_AMD_gpu_shader_half_float"
>     %half = OpTypeFloat 16

evaluating backends:
1)MSL output is supported, nice!

> spirv-cross.exe shaderfp16.comp.spv --msl
we get output like:

 ```
half2 uv = half2(half(x), half(y));
    float n = 0.0;
    half2 c = half2(6.5690069410618774650762595405465e-41, 0.0) + (half2(float2(uv) - float2(0.5)) * half2(2.3202699972290321060355114440114e-41));
    half2 z = half2(0.0);
    for (int i = 0; i < 128; i++)
    {
        z = half2((z.x * z.x) - (z.y * z.y), half((2.0 * float(z.x)) * float(z.y))) + c;
```

2)HLSL output: things are not as wished :
 ```
  float2 uv = float2(float(x), float(y));
    float n = 0.0f;
    float2 c = float2(6.5690069410618774650762595405465e-41f, 0.0f) + (float2(float2(uv) - 0.5f.xx) * 2.3202699972290321060355114440114e-41f.xx);
    float2 z = 0.0f.xx;
    for (int i = 0; i < 128; i++)
    {
        z = float2((z.x * z.x) - (z.y * z.y), float((2.0f * float(z.x)) * float(z.y))) + c;
```
which seems to map as float.. as HLSL supports min16float which I checked and seems to provide speedups using halfs vs floats for this Mandelbrot shader on supported HW (at least on Intel HD 530 they provide >50% speedup using HLSL min16float code vs original HLSL using float)..
I checked and seems to be no command line argument to pass to specify we want true halfs in HLSL (something like -hlsl-min16prec-enable would be nice)..
so just filling a request here to support that use case..

finally for GLSL output we obtain the same mapping to float..
as clearly this SPIR-V was originated from a GLSL having 
#extension GL_AMD_gpu_shader_half_float: enable
and using f16vec2 
we would like to have a mapping to true 16 bit floats even if default is mapping to float for compatibilty reasons..
understandable as right now desktop GLSL 16bit floats seem to require using #extension GL_AMD_gpu_shader_half_float: enable and only work on AMD GPUs could be an argument like (-glsl-enable-amd-16bit-floats)
Updating soon with attached shaders and motivation soon..
EDIT:
For motivation/use case of HLSL output see https://github.com/msiglreith/rostkatze
it's a Vulkan on D3D12 wrapper working fairly well.. I'm playing with adding VK_AMD_gpu_shader_half_float support to this wrapper.. as it uses SPIR-V Cross to output HLSL from SPIR-V so I would SPIR-V cross supporting translation of SPIR-V using SPV_AMD_gpu_shader_half_float+"OpTypeFloat 16" variables to HLSL+min16float variables..
This is useful for example right now for Intel HD GPUs on Windows which his Vulkan driver doesn't expose 16 bit float computations but his D3D12 driver exposes min16float..

Note this petition can evolve in future to similarly request mapping of "OpTypeInt 16" to HLSL min16int..

For GLSL output right now no urgent use case but seems useful anyway to be able to restore GLSL output similar to the GLSL that originated the SPIR-V..

See files:
see reproglsl.txt and reprohlsl.txt to see the sequence of commands used to generate all files included..
mainly we have output.{glsl,msl,hlsl} generated by SPIRV-Cross 3 differents backends..
in each case:
*feeding SPIR-V (shaderfp16.comp.spv) from GLSL shader(shaderfp16.comp)
*feeding SPIR-V (test.spv) from HLSL(test.hlsl)
[**reprofp16spirvcross.zip**](https://github.com/KhronosGroup/SPIRV-Cross/files/1784261/reprofp16spirvcross.zip)

thanks..

**Comment by HansKristian-ARM** [comment]
So you're saying there are two ways to use fp16 in HLSL? half and min16float, which one to use? How does this interact with buffer objects? Afaik, there is no 16-bit store/load instructions to UAV.

For GLSL the only option right now seems to be AMD's extension.

I'm a bit confused what this ticket is about when wave/lane ops are dragged into this.

**Comment by oscarbg** [comment]
Ok sorry for confusion..
forget about "half", what **I'm asking is for support for min16float in HLSL output** of "OpType Float 16" variables on SPIR-V shaders.. 
I'm mainly **interested on 16bit float computation** support as Mandelbrot sample shows.. as said if mapped to min16float then this shaders are supported by SM5.x hardware on D3D11 API which expose min16float optional capability.. AFAIK if SPIR-V not uses SPV_KHR_16bit_storage then the support expecpted is for only 16bit float variables and arithmetic ops on SPIR-V so no problem when translating to HLSL.. no worries about lack of support of  input/output to UAV/Buffers/Tesxtures..
also if mapping to min16float AFAIK even when hardware doesn't support 16bit floats then min16float gets mapped magically to float as said no worries not having load/store instruction to UAVs for ex..
NOTE: half should be supported on HLSL on SM6.x shaders compiled via new open source  but as said min16float is more flexible in that HLSL output is feedable to D3DCompiler in addition to new DXCompiler part of DirectXShaderCompiler.. 
as I'm interested only on 16 bit computation so no issues with 16 bit load/store limitations..
of course if SPIR-V uses SPV_16bit_storage with input output to buffers/textures etc.. HLSL backend should say that is not supported on HLSL currently..

For GLSL yes right now is AMD ext. only.. but thought having support in glslangValidator to compile shaders using this ext. to SPIR-V code using SPV_AMD_gpu_shader_half_float makes sense to have to reverse operation i.e. namely going from this SPIR-V code generated by glslangValidator to a similar GLSL shader mapping the SPV_AMD_gpu_shader_half_float to GL_AMD_gpu_shader_half_float.. 
**after all the SPIR-V file we are getting as input uses SPV_AMD_gpu_shader_half_float** so 
mapping to a GLSL using GL_AMD_gpu_shader_half_float doesn't seem a loss of compatibilty in fact maintains the same compatiblity..
two things to say:
1)In fact I think, with  current mapping to float, user should be notified a change in precision is being done from original SPIR-V file for compat. reasons..
2)user should have the possibilty of maintaining precision of SPIR-V in GLSL output (obviously for performance reasons).. could be a flag like --glsl-amd-16bit-float or somethinkg like this..

regarding wave ops it was to say that in discussion with rostkatze author and asking for things for improvement it was said both 16 bit floats and wave ops required SPIRV-Cross support which is currently missing..

as said now I updated repro with {GL,HLSL} shaders,SPIR-V generated files (DXC+glslangValidator) and output of three backends so you can see my experiments and current limitations: 
[reprofp16spirvcross.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1784411/reprofp16spirvcross.zip)
In fact as said earlier I'm surprised by results namely that Metal output support halfs and not in DirectX even min16float being supported by all hardware (as said maps to float when no native 16 float ops on GPU by virtue of no I/O support only ops on 16 bit ops)..

**Comment by HansKristian-ARM** [comment]
So, I've mostly implemented FP16 now on GLSL using GL_AMD_gpu_shader_half_float and works, even in buffer types, but HLSL is just being weird as usual.

min16float is effectively mediump, and that's what glslang generates. half is just 32-bit floats in glslang.

FXC similarly generates 32-bit FP from "half", and tags expressions with min16f when using min16float. Do any DX drivers even care about min16float? Should we just go for half?

**Comment by oscarbg** [comment]
nice news on GLSL!
please forgive my ignorance but really don't get the difficulties on HLSL support.. couldn't you adapt similar to your GLSL patches,and add to  spirv_hlsl.cpp below:

> case SPIRType::Float:
> return "float";
> 
also:
> case SPIRType::Half:
> 			return "min16float";
> 

As I said FXC is old compiler and maps half to float, I believe using DXC -profile_6_x -spirv -enable-16bit-types should map it to native float16..
that's why I think we should map to min16float..
Yes drivers care about min16float in fact I have running program sample here:
[mandelmin16float.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1785790/mandelmin16float.zip)
I checked on desktop GPUs where is I care the most and on Intel HD 530 which have fp16 2x float perfomance this mandelbrot min16float demo runs more than 50% faster than float version and also shows computations are being done in float16 precision as zooming in (left mouse button) sees issues very fast vs float precision..
regarding the attached file in float folder you have normal program with hlsl shader using fp32 computations..
in min16float folder you have same program but I modified hlsl shader to use min16float computations..
(the shader to see is CSMandelJulia_scalarFloat) also don't care about what precision is shown in menu bar it's just a lame repro case I just sent to one AMD engineer because I see graphical issues on AMD RX Vega which also exposes optional min16float as supported (i.e. it will not be mapped to normal float by the driver as said previously)..
Nvidia cards can't say I have Maxwell and only fast FP16 cards are very expensive like Titan V..

**Comment by HansKristian-ARM** [comment]
Ok, if min16float is being honored by drivers, it should be a good enough solution.

**Comment by oscarbg** [comment]
Ok nice..
final post for today.. drained all my energy :-)
can I ask you to have a look, now that seems I convinced you of IMHO the right approach to support,
of similar support in SPIRV-Cross for min16int and min16uint HLSL output of SPIR-V shaders using int16..
I mean without opening a separate issue..
here we have more luck as int16 is official optional capabilty in Vulkan/SPIR-V that doesn't require additional extensions so has cross vendor support as long as vendor advertises int16 support on his Vulkan driver and similar to min16float for HLSL..
Interestingly I checked recent ARM Mali Vulkan drivers and it support shaderInt16:
https://vulkan.gpuinfo.org/displayreport.php?id=2292#features
In fact I convinced also a AMD engineer (@amdrexu) to open issue for glslangValidator HLSL frontend support it also:
https://github.com/KhronosGroup/glslang/issues/1271
(HLSL: Map min16float/min16int/min16uint to float16_t/int16_t/uint16_t )

with that we close the loop of 16 bit integer/FP types support as HLSL input/output in glslangValidator/SPIRV-Cross!

Hint: I will also ask about int64 HLSL input/output support on glslang/SPIRV-Cross (that requires I believe SM>=6.1 so DXC (FXC no))..
but that requires a little exploration from me..

thanks for your support!

**Comment by HansKristian-ARM** [comment]
I've made a separate ticket for 16-bit integers, this ticket will be closed when FP16 has been merged.

**Comment by oscarbg** [comment]
Hi @HansKristian-ARM,
finally compiled SPIRV-Cross from master today and seems some bugs exist:
using for example test.spv file from mandelmin16float.zip I attached previously which is in hlslfloat16 folder and running on GLSL and HLSL I get similar errors:
spirv-cross.exe test.spv >output.glsl
`SPIRV-Cross threw an exception: Unrecognized type in type_to_packed_base_size.`

spirv-cross.exe test.spv --hlsl --shader-model 50 >output.hlsl
`SPIRV-Cross threw an exception: Unrecognized type in type_to_packed_base_size.`

**Comment by HansKristian-ARM** [comment]
You cannot place bools in buffers in SPIR-V, so this is invalid SPIR-V in any case. There was no checking before, so it just assumed 4 bytes.

**Comment by oscarbg** [comment]
Seems the bug is in directxshadercompiler spir-v output.. will report it.. thanks..
