### ISSUE TITLE
CompilerMSL::Options shadows CompilerGLSL::Options

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#489]
This makes setting options complicated; some options in CompilerGLSL are still valid for MSL, for example vertex.fixup_clipspace - to set them, you need to do this:

    compiler.CompilerGLSL::set_options(options);

Which seems unnecessarily awkward.

**Comment by HansKristian-ARM** [comment]
I'll probably deprecate the current interface with set_common_options and set_hlsl/msl_options. The overload issue here is rather awkward.
