### ISSUE TITLE
How can i get uniform buffer members?

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#49]
I'm accessing the shader_resources uniform_buffers members, how can I get members of given uniform buffer? How about type, size etc?

Thanks

**Comment by HansKristian-ARM** [comment]
Hi, you can use
```
const SPIRType &type = compiler.get_type(resource.base_type_id);
```
to get the underlying UBO type. For names,
```
compiler.get_member_name(resource.base_type, member_index);
```

**Comment by grovesNL** [comment]
@HansKristian-ARM How do we know how many members exist (i.e. if we wanted to iterate over all members)? I don't see `members.size()` exposed anywhere, but I'm not sure if this is intentional or if there is another way.

**Comment by HansKristian-ARM** [comment]
member_types.size() should do it.
