### ISSUE TITLE
Support 16-bit integer types.

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Cross#491]

**Comment by oscarbg** [comment]
Hi,
thanks for opening issue..
as glslangValidator added HLSL min16int support recently:
https://github.com/KhronosGroup/glslang/commit/cb61eec948b80a5e3f4e305513a3656374ef3191
I wanted to compare to DXC and seems right now has some issues:
see bottom of:
https://github.com/KhronosGroup/glslang/issues/1271

anyway DXC works currently and replacing some min16float to min16int in the mandlebrot shader I shared on the HLSL min16float support issue I generated some SPIR-V using int16.. of course would not produce correct rendering as should play a little to make "good fixed point" usage..
I use:
dxc.exe -E CSMandelJulia_scalarFloat testint16.hlsl -enable-16bit-types -T cs_6_2 -spirv -O0 -Vd >testint16.txt
spirv-as testint16.txt -o testint16.spv
spirv-val testint16.spv
spirv-dis testint16.spv >testint16.spv.txt


so I attach test files for future reference:
DOWNLOAD->[testint16.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1800568/testint16.zip)
thanks..

**Comment by oscarbg** [comment]
Hi,
just pointing out doing a quick hack in spirv_hlsl.cpp:
in CompilerHLSL::type_to_glsl I modifify to (similar to msl backend):

> 	case SPIRType::Int:
> 			return (type.width == 16 ? "min16int" : "int");

and I was able for my mandelbrot sample to obtain the HLSL using min16int and from quick comparison 
 to original HLSL min16int version seems OK..
of course l should also patch accordingly the vector case and matrix case..
and assuming this is done is something remaining to add, i.e. can get unexpected consequencies/bad translation by using this simple patch for ex. with type conversions assignement with diferent types from/to short/int16?
thanks..

**Comment by oscarbg** [comment]
Ok, will live with my patch in the meanwhile..

**Comment by HansKristian-ARM** [comment]
Implemented in https://github.com/KhronosGroup/SPIRV-Cross/pull/738
