### ISSUE TITLE
Complex loop fallback (when enabled) turns a loop into an infinite loop

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#493]
The attached shader is converted without issues to MSL by SPIRV-Cross by default.

However, changing `block_is_loop_candidate` to always return false (to trigger complex loop emission) converts this shader to a shader with an infinite loop. This shader has three nested loops, and complex loop continues in one of them in the branch that should break instead.

This happens because in CompilerGLSL::branch, one of the blocks returns true for both `is_continue` and `is_break`; `is_continue` is checked first...

[shader-opt.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1790469/shader-opt.spv.zip)

**Comment by HansKristian-ARM** [comment]
So this shader uncovered another bug.
Turns out select merging and loop merging directly into a continue block was not working right.
