### ISSUE TITLE
Bad GLSL code generated from optimized SPIR-V

### ISSUE THREAD

**Issue by turol** [KhronosGroup/SPIRV-Cross#494]
SPIRV-Cross generates GLSL code with different behavior from two shaders which should be functionally equivalent. The only difference between these shaders is that the bad version has been run through the optimizer. When testing with Vulkan where SPIRV-cross is not used the shaders behave identically. Currently using revision c9516fa91709b68ac20fa614625e85e0ced3f23f but I don't see major changes to GLSL in master.

[Good shader](https://gist.github.com/turol/5527f957a0c602c14a7f864ce061f442)
[Bad shader](https://gist.github.com/turol/054fdfdd966a03ba09163eda1f2ba586)

I originally thought this was a SPIRV-Tools optimizer bug https://github.com/KhronosGroup/SPIRV-Tools/issues/1388

**Comment by turol** [comment]
Running standalone spirv-cross on the shaders doesn't produce exactly the right GLSL since the code changes the resource bindings by removing the set indices before converting to GLSL. However there should be no functional changes.

The actual shaders as seen by apitrace:

[Good GLSL shader](https://gist.github.com/turol/d5a9896ab9f887eb3cefd6251bec0386)
[Bad GLSL shader](https://gist.github.com/turol/341070b7197c2e92fb7c5bcdcf8cc593)

**Comment by HansKristian-ARM** [comment]
Ok, scanning through the shader, the structure seems to be the same ...
But one interesting point is that fma() and textureLod seem to be reordered.

It seems like there is a dependency problem when loading from a phi node and writing to it.
The order of how phi nodes are written out actually becomes relevant now, which is not good ...

**Comment by HansKristian-ARM** [comment]
This should be fixed now, but it's hard to verify it 100%. Please reopen if it still doesn't work.

**Comment by turol** [comment]
Testing now.

**Comment by turol** [comment]
Looks like that did it. Thanks!
