### ISSUE TITLE
Support HLSL output of new Vulkan 1.1 Subgroup/Wave Ops..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#499]
Hi,
just compiled glslangValidator from master that has added support for SM6.0 wave ops in HLSL input  mode..
DXC has a pull request with wave ops support also (https://github.com/Microsoft/DirectXShaderCompiler/pull/1118) 
but I'm hitting some issues currently.. please see bottom of:
(https://github.com/Microsoft/DirectXShaderCompiler/issues/645)

so compiled wave.hlsl to SPIR-V of this sample:

https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12SM6WaveIntrinsics

using:
glslangValidator -D -H -e PSMain -S frag wave.hlsl --target-env vulkan1.1

(as soon as DXC is fixed should be also capable with:
dxc   /E"PSMain"  /Tps_6_0  wave.hlsl  -spirv)

As said previously motivation is adding support for that to (https://github.com/msiglreith/rostkatze)
which depends on SPIRV-Cross HLSL output for it's features that can support..

I'm attaching SPIR-V output and disasm and source file:
**DOWNLOAD**->[test.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1800547/test.zip)

this test uses most of new SM6.0 wave ops if not all and resulting spir-v file uses:
```
; SPIR-V
; Version: 1.3
               OpCapability GroupNonUniform
               OpCapability GroupNonUniformArithmetic
               OpCapability GroupNonUniformBallot
               OpCapability GroupNonUniformQuad

```

Note I'm not asking about GLSL output altough glslangValidator also has added support for generating new SPIR-V 1.1 subgroup ops from GLSL code via new GLSL extenisons for Vulkan output:

> GL_KHR_shader_subgroup_arithmetic
> GL_KHR_shader_subgroup_ballot
> GL_KHR_shader_subgroup_basic
> GL_KHR_shader_subgroup_clustered
> GL_KHR_shader_subgroup_vote
> GL_KHR_shader_subgroup_quad
> GL_KHR_shader_subgroup_shuffle
> GL_KHR_shader_subgroup_shuffle_relative

and includes extensive new tests (`glslang/Test/spv.subgroup*`)
exercicing all this new exts. so would be nice if eventually also SPIRV-Cross is able to generate back these kind of GLSL files from SPIR-V files.. closing the loop basically..

Note glslangValidator HLSL wave tests are in Test folder:
```
hlsl.wavebroadcast.comp
hlsl.waveprefix.comp
hlsl.wavequad.comp
hlsl.wavequery.comp
hlsl.wavequery.frag
hlsl.wavereduction.comp
hlsl.wavevote.comp
```
thanks..

**Comment by dneto0** [comment]
Sorry, what is the issue with SPIRV-Tools?  I believe it already supports everything as of 00fa39318 which was pushed to master the same day as the SPIR-V 1.3 spec release.

**Comment by dneto0** [comment]
Never mind.  I'm looking at the wrong repository.  :-)

**Comment by oscarbg** [comment]
@HansKristian-ARM as always thanks for nice work!
you will hate me for all requests I do but let's do it anyway:
Seems Metal (2.0) has some subgroup ops supported (called SIMD-group ops or quad-group ops (when SIMD=4), different support depending on IOS or Macos..
Of course would be very useful for start implementing Vulkan 1.1 subgroups on MoltenVK..
Crrently seem only supported on fragment and compute stages..
may I open a separate issue for request of subgroup support on Metal output?

For example
section 5.13 of spec( https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf)
mentions for macos (and only supported on fragment and compute stages)
 simd_shuffle(T data, ushort simd_lane_id) 
 simd_broadcast(T data, ushort broadcast_lane_id) 
 simd_shuffle_up(T data, ushort delta) 
 simd_shuffle_down(T data, ushort delta) 
IOS supports same variations but on quads..
thanks..

**Comment by HansKristian-ARM** [comment]
Well, you can open a new issue, but not going to work on that any time soon.
