### ISSUE TITLE
With --vulkan option, test script checks both OpenGL and Vulkan paths

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Cross#5]
Its help string says it will test Vulkan *instead of* OpenGL semantics.

I suspect the better fix is to update the help string.

**Comment by dneto0** [comment]
Hm.  If we just update the help string, then we would still be checking OpenGL semantics on Vulkan sample shaders from shaders-vulkan. That might not be appropriate.
So I'm not sure what to suggest.

**Comment by HansKristian-ARM** [comment]
A better approach might be to use file extensions to denote shaders which are Vulkan GLSL and regular GLSL. There is no real reason why there should be a need to add --vulkan.

**Comment by HansKristian-ARM** [comment]
Cleaned up most of this in: https://github.com/KhronosGroup/SPIRV-Cross/pull/7. Does that work as expected for you?
