### ISSUE TITLE
Missing support for OpTypeBool in structs

### ISSUE THREAD

**Issue by amddb** [KhronosGroup/SPIRV-Cross#504]
SPIRV-Cross throws an exception when run on SPIRV that defines OpTypeBool as member of a struct.
In that case the SPIR-V was compiled from HLSL with DXC.
Compiling with glslangValidator does not throw, as the `bool` struct member is treated as `int`.

Compare _dxc-spirv-cross-issue.hlsl.spv-txt_ (line 43) and _glslang-spirv-cross-issue.hlsl.spv-txt_ (line 53).

[Repro files](https://github.com/KhronosGroup/SPIRV-Cross/files/1803748/missing-bool-support.zip)

**Comment by HansKristian-ARM** [comment]
the DXC generated code is illegal SPIR-V.

```
OpTypeBool: Declare the Boolean type. Values of this type can only be either true or false. There is *no physical size or bit pattern* defined for these values.
```

**Comment by amddb** [comment]
Ah yeah you a right. I'll raise that with DXC. That'll teach me to read the spec first.
