### ISSUE TITLE
[MSL] Sampling a 1D texture in compute shader results in an invalid code

### ISSUE THREAD

**Issue by yvt** [KhronosGroup/SPIRV-Cross#506]
The current version of SPIRV-Cross emits an invalid Metal code for 1D texture read inside a compute shader like the following:

```glsl
#version 450

layout(binding = 2) uniform sampler1D uSampler1D;

layout(std430, binding = 1) writeonly buffer SSBO2 { vec4 out_data[]; };

void main() {
    out_data[0] = texture(uSampler1D, 0.0);
}
```

The above code is converted to `ImageSampleExplicitLod` by glslang, and then to a call to `texture1d<float>::sample(sampler, float, lod_options)` method by SPIRV-Cross. However, since Metal (at least on macOS) does not support mipmapping on 1D textures, the `sample` function actually does not have an overload accepting `lod_options`, hence the compilation error.

The transpiled MSL and the compilation output are available [here](https://gist.github.com/yvt/e0a1f52faf08749246654806cf80ef72).

**Comment by HansKristian-ARM** [comment]
I'll have a look after GDC.
