### ISSUE TITLE
SPIRV_Cross_BaseInstance issue

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#511]
I have a shader that uses hlsl instancing. As far as I understand it, instancing in hlsl provides an instance id on the shader side and a StartInstance on the API side. Apparently Vulkan also supports this in that it has InstanceIndex which combines both factors, but glsl for OpenGL/GLES doesn't and so SPIRV-Cross emulates it using SPIRV_Cross_BaseInstance which the renderer has to populate through the normal uniform uploading mechanisms.

Now, my issue is that I have a platform that doesn't support simple uniforms in glsl other than textures and images and expects everything else to be put in a uniform block instead. I've worked around it by replacing

```cpp
if (meta[var.self].decoration.builtin_type == BuiltInInstanceIndex && !options.vulkan_semantics)
{
	statement("uniform int SPIRV_Cross_BaseInstance;");
	emitted = true;
}
```

with

```cpp
if (meta[var.self].decoration.builtin_type == BuiltInInstanceIndex && !options.vulkan_semantics)
{
	statement("layout(std140) uniform g_SPIRV_Cross_BaseInstance { int BaseInstance; } SPIRV_Cross_BaseInstance;");
	emitted = true;
}
```

and the corresponding code that reads it later.

Obviously GLES2 doesn't support uniform blocks, so is there a chance we could have a behavior where certain profiles of GLSL put it in a regular uniform and the rest uses a uniform block?

**Comment by HansKristian-ARM** [comment]
In which case is this actually needed? Regular GLSL always support plain uniforms.

**Comment by HansKristian-ARM** [comment]
From offline discussion I haven't heard back if this is actually required after all, so I'll close until I hear otherwise.
