### ISSUE TITLE
Empty structs don't compile in glsl

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#512]
As near as I can tell, OpTypeStruct is allowed to have zero members. Glsl does not allow empty structs though so the attached code will fail to compile when translated.

I can easily work around this by adding a dummy member to empty structs so this isn't a big issue.
[EmptyStructError.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1843059/EmptyStructError.txt)

**Comment by HansKristian-ARM** [comment]
Empty structs are kinda painful to deal with in various cases. I'll have a look and see if this particular case can be worked around.
