### ISSUE TITLE
vertexFunction must not be nil

### ISSUE THREAD

**Issue by hodasemi** [KhronosGroup/SPIRV-Cross#513]
Hi,

I have a running vulkan program, which works fine on Linux and Windows. I'm currently trying to get it running on MacOS. 

I got my shaders precompiled in binary SPIR-V format. When I hand over a VkShaderModule with this SPIR-V to vkCreateGraphicsPipelines I get following error:

`[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module compilation failed (code 3):

Compilation failed:

program_source:9:21: error: 'attribute' attribute cannot be applied to types
    float4 vertex [[attribute(0)]];
                    ^
program_source:9:5: warning: declaration does not declare anything
    float4 vertex [[attribute(0)]];
    ^~~~~~
program_source:22:26: error: expected unqualified-id
    out.gl_Position = in.vertex;
                         ^

-[MTLRenderPipelineDescriptorInternal validateWithDevice😏:2149: failed assertion 'vertexFunction must not be nil.'
Abort trap: 6`

Since this doesnt work, I converted the SPIR-V shaders to metal shaders. It doesnt matter if I convert the GLSL shader directly to metal shader or if I use my SPIR-V shaders, the result is the same. Here I get the following error:

`[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module does not contain an entry point named ''.
[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module does not contain an entry point named ''.
-[MTLRenderPipelineDescriptorInternal validateWithDevice😏:2149: failed assertion 'vertexFunction must not be nil.'
Abort trap: 6`

These errors are present with the current version MoltenVK.

It is an absolutely basic pass through shader.

`#version 450

layout (location = 0) in vec4 pos;
layout (location = 1) in vec2 uvs;

layout (location = 0) out vec2 uv;

void main() 
{
    uv = uvs;
    gl_Position = pos;
}`

**Comment by HansKristian-ARM** [comment]
Not sure, seems to work fine here:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_in
{
    float2 uvs [[attribute(1)]];
    float4 pos [[attribute(0)]];
};

struct main0_out
{
    float2 uv [[user(locn0)]];
    float4 gl_Position [[position]];
};

vertex main0_out main0(main0_in in [[stage_in]])
{
    main0_out out = {};
    out.uv = in.uvs;
    out.gl_Position = in.pos;
    return out;
}
```
There were some recent changes to how entry points were handled in SPIRV-Cross (old entry point is deprecated). Based on the error with "does not contain an entry point named ''", I wonder what MoltenVK is doing here.

**Comment by hodasemi** [comment]
Yea, I get the exact metal shader when using their converter tool. 
I opened an issue first on their repository, they told me to also open one around here.

**Comment by billhollings** [comment]
This can be closed. See [MoltenVK issue](https://github.com/KhronosGroup/MoltenVK/issues/112) for resolution explanation.

I'll add a separate issue on SPIRV-Cross to add additional MSL-specific keyword screening.
