### ISSUE TITLE
Should throw if compiling uniform blocks to GLSL <= 1.30

### ISSUE THREAD

**Issue by rtbo** [KhronosGroup/SPIRV-Cross#515]
Following code can get out without any error being thrown and will eventually produce a shader compile error.
```glsl
#version 130
layout(std140) uniform Matrices
{
    mat4 mvpMat;
    mat4 normalMat;
} ubo;
...
```
Uniform blocks were introduced with GLSL 1.40.

**Comment by HansKristian-ARM** [comment]
Currently, I think UBOs should become uniform structs in legacy targets, but GL 3.0 (GLSL 1.30) is probably an edge case here, it's not a legacy target, except it doesn't have UBOs.
