### ISSUE TITLE
Color index location lost during conversion

### ISSUE THREAD

**Issue by VinDuv** [KhronosGroup/SPIRV-Cross#516]
(I originally reported this issue as part of https://github.com/KhronosGroup/MoltenVK/issues/113)
The Dolphin emulator generates Vulkan fragment shaders with a layout attribute containing both a location and an index. Here’s a reduced test case:
```
#version 450 core
layout(location = 0, index = 0) out vec4 ocol0;
layout(location = 0, index = 1) out vec4 ocol1;
void main() {
	ocol0 = vec4(0.0, 0.0, 0.0, 0.0);
	ocol1 = vec4(0.0, 0.0, 0.0, 0.0);
}
```
When compiled with MoltenVKShaderConverter, the resulting SPIR-V has both attributes:
```
               OpName %9 "ocol0"
               OpName %12 "ocol1"
               OpDecorate %9 Index 0
               OpDecorate %9 Location 0
               OpDecorate %12 Index 1
               OpDecorate %12 Location 0
```
When compiled to MSL, however, the location is lost, giving this erroneous code:
```
struct main0_out
{
    float4 ocol0 [[color(0)]];
    float4 ocol1 [[color(0)]];
};
[…]
```
The index part of the attribute is also missing in the “Estimated original GLSL” output from MoltenVK.

Apparently the location/index attribute is related to [dual-source blending](https://www.khronos.org/opengl/wiki/Blending#Dual_Source_Blending) (thanks @HansKristian-ARM for mentioning it in my original bug report!) and the expected notation in Metal is (according to [Apple docs](https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/WhatsNewiniOS10tvOS10andOSX1012/WhatsNewiniOS10tvOS10andOSX1012.html#//apple_ref/doc/uid/TP40014221-CH14-DontLinkElementID_81)):
```
    float4 ocol0 [[color(0), index(0)]];
    float4 ocol1 [[color(0), index(1)]];
```

**Comment by HansKristian-ARM** [comment]
Dual-source blending is currently not supported, but should be trivial to add.
