### ISSUE TITLE
Additional MSL keyword screening

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#517]
MSL-specifid keywords like `vertex`, `fragment`, `kernel`, etc...need to be added to the list of illegal words for MSL.  

While we are at it...`CompilerMSL` and `CompilerGLSL` have slightly different approaches to renaming. Perhaps we can look to consolidate. I prefer name for functions to not simply have a  `_` prepended.

Edit: See [this MoltenVK issue](https://github.com/KhronosGroup/MoltenVK/issues/112) for example of this issue.

**Comment by HansKristian-ARM** [comment]
What is the rationale for not prepending with `_`?
