### ISSUE TITLE
Question about half / mediump

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/SPIRV-Cross#527]
Hi! I'm trying to write shader targeting both iOS and android. For best performance, one should use half/mediump most of the time.
When I use HLSL front end and HALF, metal shader use HALF, but glsl shader use an AMD half extension which is not supported on target machine ( I use ANGLE for testing).
When I use GLSL front end and mediump, glsl shader use medium, but metal use float.
Is there any way to have metal shader use half, and glsl use mediump at the same time?
Thank you.

**Comment by HansKristian-ARM** [comment]
I think an explicit conversion pass before ::compile() might be considered as a compat option for FP16.

- Validate that no FP16 values are used as part of any buffer types.
- Replace all FP16 types with float.
- All OpVariables with FP16 get RelaxedPrecision decoration.
- All operations with FP16 result get RelaxedPrecision decoration.

However, this is borderline SPIRV-Tools territory imo.

**Comment by alek314** [comment]
I would be nice if spirv cross add min16float support for HLSL as well.

**Comment by HansKristian-ARM** [comment]
It does already. If you use FP16 types, HLSL will emit min16float.

**Comment by HansKristian-ARM** [comment]
Don't think this will go anywhere, the ideal solution will be SPIRV-Tools.
