### ISSUE TITLE
Using depth texture for Metal

### ISSUE THREAD

**Issue by cyh36** [KhronosGroup/SPIRV-Cross#529]
Given the SPIRV generated from the following shader:
```
layout (binding = 0) uniform texture2D uDepth; 
layout (binding = 1) uniform samplerShadow uSampler;

float Samp(vec2 uv)
{
    return texture(sampler2DShadow(uDepth, uSampler), vec3(uv, 0.001));
}
```
The Metal version would automatically supplement the function arguments, like:
```
float Samp(thread const float2& uv, thread texture2d<float> uDepth_, thread sampler uSampler_)
{
    return uDepth_.sample_compare(uSampler_, uv, 0.001);
}
```
Obviously the texture “uDepth” get a wrong type "texture2d<float>". If I define the function arguments explicitly like "float Samp(texture2D t, samplerShadow s, vec2 uv)", than the metal shader converted will be correct.

The second problem is, the iOS Metal requires that the sampler in sample_compare is a compile-time constant, so the metal shader above wouldn't be compiled successfully on iOS. It seems that the MSL Compiler should add a "constexpr sampler" declaration before sample_compare method invoking automatically for iOS?

Thanks.

**Comment by HansKristian-ARM** [comment]
Something is probably missing in the tracking of how images are used.

Having to use compile-time constant samplers for depth seems kinda silly, does Metal seriously require this? That means changing a sampler will force a full recompile of shaders, and forget about arrays of samplers ...

**Comment by cyh36** [comment]
I've compiled my shader on ipad mini2 (iOS 10.3.2), the console output "Error Domain=AGXMetalA8 Code=1 sampler argument for sample_compare must be known at compile time".

**Comment by HansKristian-ARM** [comment]
Using depth2d seems to have fixed the issue, no constexpr samplers are needed.
