### ISSUE TITLE
iOS metal seems to require compile-time constant sampler for sample_compare

### ISSUE THREAD

**Issue by cyh36** [KhronosGroup/SPIRV-Cross#533]
Hi, I've raised an issue #529 several days ago. You said "no constexpr samplers are needed" because you tested on OSX, it seems that only iOS metal requires this. I upgraded my iOS system and Xcode to the latest version, but the issue still remains. Is there any way to deal with this problem? Otherwise, maybe I have to use sample instead of sample_compare on iOS.

**Comment by HansKristian-ARM** [comment]
If iOS truly requires this, MoltenVK would need to add emulation support here because SPIRV-Cross would need another interface which lets you set constant sampler state ahead of time. I don't think there is much I can do right now. Please file a bug on MoltenVK if you're using that.

**Comment by alek314** [comment]
Can you add a new interface while remain backward compatibility? We can not do PCF shadow mapping without this feature in our in house engine, which has nothing to do with MoltenVK.
Thank you.

**Comment by HansKristian-ARM** [comment]
If you're using the API only, I could add something like:
```
void CompilerMSL::remap_constexpr_sampler(unsigned id, const MSLConstexprSamplerData &)
```
However, I don't know how this works in MSL, so please paste some example shaders how you'd like the resulting MSL code to look.

**Comment by cyh36** [comment]
The sampler remapped could be declared at the beginning of the entry point function, and passed to those functions that use this sampler. Just like:
```
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_in
{
    float3 vUV [[user(locn0)]];
};

struct main0_out
{
    float FragColor [[color(0)]];
};

float Samp(thread const float3& uv, thread depth2d<float> uTex, thread sampler uSamp)
{
    return uTex.sample_compare(uSamp, uv.xy, uv.z);
}

fragment main0_out main0(main0_in in [[stage_in]], depth2d<float> uTex [[texture(0)]], depth2d<float> uTex2 [[texture(1)]], sampler uSamp [[sampler(0)]], sampler uSamp2 [[sampler(1)]])
{
    constexpr sampler uSamp_(address::clamp_to_edge, mip_filter::none, min_filter::linear, mag_filter::linear, compare_func::less);
    constexpr sampler uSamp2_(address::clamp_to_edge, mip_filter::none, min_filter::nearest, mag_filter::nearest, compare_func::less_equal);

    main0_out out = {};
    out.FragColor = uTex.sample_compare(uSamp_, in.vUV.xy, in.vUV.z);
    out.FragColor += Samp(in.vUV, uTex2, uSamp2_);
    return out;
}
```

**Comment by HansKristian-ARM** [comment]
Ok, that seems reasonable enough.

**Comment by HansKristian-ARM** [comment]
Got something WIP that should solve your problem. Please check it out and give feedback if this fixes your issue.

**Comment by alek314** [comment]
We will test it ASAP

**Comment by cyh36** [comment]
This seems to resolve the issue we had. Thanks very much! @HansKristian-ARM
