### ISSUE TITLE
Mapping types for older GLSL versions

### ISSUE THREAD

**Issue by hbirchtree** [KhronosGroup/SPIRV-Cross#535]
I noticed that on old GLSL versions (eg. version 1.00), spirv_glsl still outputs types such as `uint` and `double`, which do not exist in that particular version.
There is no graceful way of keeping their precision and etc., but it is possible to substitute them for `int` and `float` respectively for the purpose of creating valid GLSL.

I know this might not be part of the scope for SPIRV-Cross, but I've been considering making a patch for this.

**Comment by HansKristian-ARM** [comment]
Renaming uint to int is not valid. There are several operations where the signedness matters.
double currently uses fp64 extension. Renaming that to float is sketchy. Using FP64 in shaders typically means the application has very specific precision requirements, and it would break buffer packing, bit-casting operations, etc, etc ...

For legacy targets, the current policy is that if you cannot express it sensibly, we don't try to emit "wrong" code. Essentially, to target legacy targets, you must be willing to compromise on the feature-set you're using.

I think the best thing to do here is to check if uint is used in legacy targets and throw error on that.
