### ISSUE TITLE
SPIRV-Cross threw an exception: Attempting to use arrays or structs of separate images. This is not possible to statically remap to plain GLSL.

### ISSUE THREAD

**Issue by fredrikzetterman** [KhronosGroup/SPIRV-Cross#542]
We've recently updated from Vulkan LunarG SDK 1.0.65 to 1.1.73, and this error popped up.

Currently we only use SPIRV-Cross to do shader reflection, by running 'spirv-cross --vulkan-semantics --dump-resources <our_shader.spv>' and grabbing and parsing stdout. From stdout we grab buffer names, set index, binding index, array count (if present) etc. Pretty simple stuff

Everything runs fine with the .exe provided in 1.0.65. The .exe provided in 1.1.73 gives us the following error however: "SPIRV-Cross threw an exception: Attempting to use arrays or structs of separate images. This is not possible to statically remap to plain GLSL."

We believe the offending code is the following (simplified a bit, so please excuse any errors):
```
layout(set = 0,binding = 22) uniform texture2DArray textures[64];
layout(set = 0,binding = 23) uniform sampler linear_sampler;
layout(set = 0,binding = 24) uniform sampler linear_clamp_sampler;

vec4
sample_texture_array( const in vec2 uv, int bucket, int index, sampler s ) {
  return texture( sampler2DArray( textures[bucket], s ), vec3( uv, index ) );
}

... used like this ...
vec4 color = sample_texture_array( uv, 3, 15, linear_sampler );
```
As can be seen, we compile GLSL to SPIRV and that code compiles and works just fine.

Is it possible to get this working again? I've read the comment where this appears in the source code, about N*M permutations, and it seems like to indicate that this won't be fixed? Is there a flag we can use in the exe to get it to work? Or are we misusing spirv-cross for reflection when we should be using something else? Or should we build our own SPIRV parser? Looking for a way forward here :) Thanks for any input and for the good work on SPIRV-Cross so far anyways :)

**Comment by HansKristian-ARM** [comment]
Indeed, remapping combined image samplers from arrays of images and samplers is a really painful endeavour. However, if you only care about Vulkan GLSL here, you can easily use --vulkan-semantics to get around this.

However, there are two cases I think can be worked around:
- Array of images, scalar sampler.
- Array of samplers, scalar images.
The latter seems extremely unlikely, but with "bindless-like" workflows, I can see the first one pop up. It might be possible to add support for this case.

**Comment by fredrikzetterman** [comment]
> This should not happen.

Famous programmer words of wisdom 😁 

I will look into the C++ API then, to see if I can get it working.

As a feature request though, I'd wish for a standardized reflection output from SPIRV-Cross. For us, it's much more desirable to run the CLI tool (which is delivered with the LunarG SDK) than to download source code, especially since source code for SPIRV-Cross is not supplied in the Windows version of the LunarG SDK.

Working against the CLI, we don't have to care about new code, new compile settings/error fixes/source files for compilers, internal API changes etc etc, so it really is my preferred way to do the reflection. Converting the output from 
```
ubos
=============
<buffer goes here>
```

to something like (maybe JSON?)
```
{
  "ubos" : {
     "buffer goes here" : {
     }
}
```
would be super-handy for a lot of people, I think.

Please consider it 😄

**Comment by HansKristian-ARM** [comment]
I'm not very comfortable with the idea that the CLI output is becoming an API, that means I can never change the layout of the ad-hoc output without risking applications breaking ...
You don't need the entire repo to just use reflection. Just include the files you need.

> we don't have to care about new code
That's not a problem if you bundle the necessary files or submodule a particular commit.

> internal API changes
CLI output can also change, which is probably worse, because you'll have to debug why the text-parsing code started failing.

I really don't want to add another "uber format" for reflections which needs to be maintained and set in stone. Applications typically have very specific information they need, so they need a filtering pass anyways to reflect only the relevant information, and at that point you might as well just use the API.

**Comment by HansKristian-ARM** [comment]
That's not to say I'm not open to the idea of a JSON-ish reflection format that can be parsed outside C++, but I think someone else would need to champion this if it is indeed useful for many people.
