### ISSUE TITLE
Uber-reflection format

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Cross#544]
#542 expressed a desire for uber-reflection formats, e.g., output a JSON file with all relevant reflection data in it.

Please ping this thread if this is important to you.

Help wanted is tagged here, because someone should PR this functionality if they want it. A separate class derived from Compiler would work well here. `::compile()` could return a full document.

**Comment by fredrikzetterman** [comment]
I want it, of course :)

I've taken the liberty to promote it on reddit as well, to see if someone wants to champion this (my time is limited, otherwise I'd love to help out)

**Comment by volcanoauthors** [comment]
I wrote a shader reflection implementation that uses the SPIRV-Cross library to write out a C (with C++) header for each .spv file input. I call it "copy_header".

Feel free to take inspiration from it: https://github.com/ndsol/volcano/tree/master/src/tools

**Comment by prideout** [comment]
See also:

https://github.com/chaoticbob/SPIRV-Reflect

**Comment by jherico** [comment]
I'm interested in this as well, although I'm interested in the output being a C/C++ header declaring the structs and enums required for the header interface.  However, if JSON output would also be sufficient if there was enough information enced in JSON for me to produce the C++ header with a simple parser on my own.

**Comment by jherico** [comment]
I'm going to work on tackling this in my fork.  I'm likely going to rely on https://github.com/nlohmann/json for formatting JSON output.  There's no existing pattern for inclusion of external libraries.  I could include it as a submodule, or just add the json.hpp header to 3rdparty folder.  Any suggestions?

**Comment by HansKristian-ARM** [comment]
Hm, that is a good question. I'm not sure if there is some convention within Khronos for hosting 3rdparty code, but it's MIT so I doubt that'd be an issue ...

I'd normally lean towards submodule, but since it's a single-header library, it might be more friendly to just add it directly into the repo.

**Comment by jherico** [comment]
My initial plan is to make reflection emission based on a command line option in the style `--reflect [format]` where format would default to `json`, and then potentially support alternative formats like `xml` and `c++`, but only after I've nailed down the JSON reflection.  I'm currently examining the code triggered by `--dump-resources` as a starting point for what I need to iterate over to produce my output.     I had earlier started work on a derived compiler that would output a C++ header with enums and structs,  but I think building a hierarchical structure like JSON first and then transforming that to other formats is likely going to be easier.

**Comment by HansKristian-ARM** [comment]
Another consideration is the compiler support.

I support MSVC 2013 and above and GCC 4.8/4.9+ and Clang. Those compilers need to be supported at least by json.hpp for it to be useable.

**Comment by jherico** [comment]
looks like the JSON [compiler support](https://github.com/nlohmann/json#supported-compilers) is _just_ above what you listed (VC 2015 and GCC 4.9 are the lower limits).  I'll look into switching to using the existing glsl buffering logic.

**Comment by jherico** [comment]
Here's what I have so far...  
Given [this fragment shader](https://gist.github.com/jherico/a4868b0992fff4c7732b119badbb08ce) input, I output [this JSON](https://gist.github.com/jherico/53a4c5bc0b9478efb16d5ffda95c023e).  

I'm primarily targeting this for my organization's internal use, so my minimum viable feature set is probably going to be a subset of what the public at large would like.  @HansKristian-ARM what do you think would be a reasonable minimum feature set to release as an experimental model upon which people can then build more?

**Comment by HansKristian-ARM** [comment]
Hi. So the way types are structured here makes sense, looks like a good start.

I am missing decorations though, i.e. offset, row/col-major matrices, etc. This is required for UBOs/push_constant/SSBOs.

**Comment by jherico** [comment]
I've updated the reflection generator to include the mentioned points based on the layout qualifier generation code for type members and resources.  I've also updated the test_shaders.py script to add reflection testing and run it in `update` mode to populate the current JSON output for everything in `reference/shaders`.  You can browse the results and compare to the corresponding shaders [here](https://github.com/jherico/SPIRV-Cross/tree/reflection/reference/shaders)

**Comment by HansKristian-ARM** [comment]
This is now merged. Many thanks to @jherico.

**Comment by tgjones** [comment]
This looks really cool.

And if anyone wants to play with it, I've just added it to Shader Playground. Try it here (you'll have to switch to the "Reflection" output manually, that's not currently saved as part of the URL):

http://shader-playground.timjones.io/ed0fe4e938e5fb4b114337ed2ce55dc9

<img width="934" alt="reflection" src="https://user-images.githubusercontent.com/102049/42103106-a8910cfe-7bfa-11e8-95a4-52b074831d4f.PNG">
