### ISSUE TITLE
Using the result of OpSampledImage in multiple expressions can result in invalid code gen

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#545]
In the attached file I merge an image and sampler into a sampled image and use that result id (14) to sample out a value and store it. If I use that same id (14) to do another sample then the translated code generates a new sampler on the stack. If instead I make another sampledimage from the same inputs to make a new temporary id this problem goes away.

[SamplersTestBed.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1951912/SamplersTestBed.txt)

I'll be honest and admit that I find the standard a bit lacking in rules regarding images/samplers so I could be doing something wrong that I don't realize.

**Comment by HansKristian-ARM** [comment]
Right, I suppose this is part of the "tracking" that SPIRV-Cross does to detect multiple expressions. I suspect combined image samplers don't tick the "don't track usage" bit.

**Comment by jodavis42** [comment]
Related to this I ran into another issue with samplers but I'm not sure if it's a SPRIV-Cross issue or SPIRV itself. Should it be valid in SPIRV to take the result of OpSampledImage and store it into a variable to re-load later? I got similar local opaque type issues when I tried this.

I filed an issue on the tools here https://github.com/KhronosGroup/SPIRV-Tools/issues/1528 since I'm not sure what's a better place to do this.

**Comment by jodavis42** [comment]
Here's an example of what I mean:
[SamplersTestBed.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1952193/SamplersTestBed.txt)

The only difference between this and the previous example is that I store the result after OpSampledImage and then I Load before each call to OpImageSampleImplicitLod

**Comment by jodavis42** [comment]
Nevermind. According to the Tools team it is illegal to store a sampled image and the validator will be adding a check for this.
https://github.com/KhronosGroup/SPIRV-Tools/issues/1528

**Comment by HansKristian-ARM** [comment]
It is illegal to store OpSampledImage, yes (or any other opaque objects). Similar with passing it as a function parameter.
