### ISSUE TITLE
More examples of exotic/unique/in-depth reflection use-cases

### ISSUE THREAD

**Issue by fuchstraumer** [KhronosGroup/SPIRV-Cross#551]
There is currently a relatively serious lack of examples demonstrating how to use the various reflection facilities in this library: most of what is known and used is cobbled together from a wide array of sources, from the minimal example code one can find, to articles on graphics techniques, to various snippets from [reddit posts](https://www.reddit.com/r/vulkan/comments/8dkkub/spirvcross_how_can_i_get_ubo_structure_member/) or even issues here. 

- For example, how would one use the reflection API to differentiate between something that becomes (in Vulkan) a `VK_DESCRIPTOR_TYPE_DYNAMIC_UNIFORM_BUFFER` vs the un-dynamic version? 

- How does one retrieve specialization constants? this was an issue I personally was only able to figure out by diving deep into the API and following functions and type definitions around

I wish I personally had more potential questions or examples of topics that should be covered, but maybe other users can contribute as well? I may also be able to help write some example code - I would have done so already, if I wasn't so absorbed/lost-in a project using this repository ;)

**Comment by HansKristian-ARM** [comment]
I'll document some more next week.

**Comment by fuchstraumer** [comment]
Interesting. That's good to know though, and makes sense!

**Comment by HansKristian-ARM** [comment]
Spent a good while writing up a wiki page on this ... Hopefully this should cover the relevant reflection API use:

https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide

**Comment by HansKristian-ARM** [comment]
Cool. I'll close this then, if you run into darker corners, I can add that.
