### ISSUE TITLE
Split OpAccessChain incorrectly declares built-in variables in Geometry shader stages

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#566]
As near as I understand, if I have a geometry input roughly declared as:
gl_In[3].

Then to write the access to gl_Position I could write it one of two ways:
Either all in one access chain:
%glPosition = OpAccessChain %gl_in %vec4Type %0 %0
or as two subsequent access chains
%temp = OpAccessChain %gl_In %gl_In_Type %0
%glPosition = OpAccessChain %temp %vec4Type %0
(excuse my made up result types)

If I do the latter then the resultant translation doesn't realize this is an array output and prints
var = gl_Position
instead of
var = gl_In[0].gl_Position.

Attached is a sample where I split the access chain into two ops
[GeometryTestSmall.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1980755/GeometryTestSmall.txt)

**Comment by HansKristian-ARM** [comment]
*Cries in painful workarounds*

**Comment by HansKristian-ARM** [comment]
Yup, split access chains are a bit annoying, and test coverage isn't that great currently.
