### ISSUE TITLE
Internal Compiler Error - VS 2013

### ISSUE THREAD

**Issue by twanks123** [KhronosGroup/SPIRV-Cross#57]
Hello guys, i tried to compile my rendering engine (developed on vs 2015) to compile it on vs 2013.
I have got always the C1001 Error: Internal Compiler Error in file "spirv_common.hpp".
```
struct SPIREntryPoint
{
	SPIREntryPoint(uint32_t self_, spv::ExecutionModel execution_model, std::string entry_name)
	    : self(self_)
	    , name(std::move(entry_name))
	    , model(execution_model)
	{
	}
	SPIREntryPoint() = default;

	uint32_t self = 0;
	std::string name;
	std::vector<uint32_t> interface_variables;

	uint64_t flags = 0;
	struct
	{
		uint32_t x = 0, y = 0, z = 0;
	} workgroup_size;
	uint32_t invocations = 0;
	uint32_t output_vertices = 0;
	spv::ExecutionModel model = {};
};
```
I could manage to fix it by removing the empty-bracket initilization from the
`spv::ExecutionModel model = {};`

I just wanna know why this is working then. (and i dont want to do this every time i update spirv-cross in my engine)

Thanks in Advance :)

**Comment by HansKristian-ARM** [comment]
Smells like compiler bug to me, but it's redundant. Pushed a fix.

**Comment by twanks123** [comment]
Thanks :)
