### ISSUE TITLE
Question: What optimizer should be use with SPIRV-Cross

### ISSUE THREAD

**Issue by alek314** [KhronosGroup/SPIRV-Cross#579]
Should I turn on spirv-opt before spirv-cross or should I use things like [https://github.com/aras-p/glsl-optimizer](url) on the code generated by spriv-cross? Thank you

**Comment by HansKristian-ARM** [comment]
Not sure. I don't think spirv-opt is going to make GLSL output faster. Don't know glsl-optimizer enough to comment on that.

**Comment by alek314** [comment]
Is the purpose of spirv-opt  to make spv faster, so that Vulkan can be faster?  If I am to target Vulkan and GLES at the same time, what would be the optimal pipeline configuration?

**Comment by HansKristian-ARM** [comment]
spirv-opt primarily makes things smaller I think (and legalizes various cases w.r.t HLSL). I haven't seen a case where spirv-opt can find performance optimizations which a backend driver compiler cannot yet, but I haven't looked into this all that much.

**Comment by alek314** [comment]
I think this question should be asked on the ARM graphics forum instead. I will close this issue. Thank you.
