### ISSUE TITLE
Wrong layout for tessellation evaluation shader

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#58]
The header of my tessellation evaluation shader looks like this:
```glsl
#version 450
layout(triangles, equal_spacing, ccw) in;
```

However, in the output the 'triangles' is omitted from layout line.
```glsl
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif
#extension GL_ARB_tessellation_shader : require
layout(ccw, equal_spacing) in;
```

This throws error at runtime:
```
GLSL linker error: ERROR: Tessellation evaluation shader must specify triangles, quads or isolines.
```

After editing the output and explicitly specifying 'triangles', everything appears to work perfectly.
```glsl
layout(triangles, ccw, equal_spacing) in;
```

Any idea on the possible cause? Or is this implementation specific and 'triangles' should be taken as default?

I am using SPIRV-Cross through [krafix](https://github.com/KTXSoftware/krafix), macos 10.11.6, Intel Iris GPU.

**Comment by HansKristian-ARM** [comment]
For some reason, triangle mode was just missing. Fixed, and added regression tests.
