### ISSUE TITLE
Generated GLSL samplers lose their binding points

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/SPIRV-Cross#584]
You can repro this with [reference/shaders-hlsl/frag/basic.frag](https://github.com/KhronosGroup/SPIRV-Cross/blob/f929c36/reference/shaders-hlsl/frag/basic.frag) shader:

```hlsl
Texture2D<float4> uTex : register(t0);
SamplerState _uTex_sampler : register(s0);

static float4 FragColor;
static float4 vColor;
static float2 vTex;

struct SPIRV_Cross_Input
{
    float4 vColor : TEXCOORD0;
    float2 vTex : TEXCOORD1;
};

struct SPIRV_Cross_Output
{
    float4 FragColor : SV_Target0;
};

void frag_main()
{
    FragColor = vColor * uTex.Sample(_uTex_sampler, vTex);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    vColor = stage_input.vColor;
    vTex = stage_input.vTex;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.FragColor = FragColor;
    return stage_output;
}
```

Compile command (`glslc` from ndk r17, latest `spirv-cross`):

```bash
./glslc -x hlsl -fshader-stage=frag basic.frag -o /tmp/a.spv && ./spirv-cross /tmp/a.spv
```

You get this output:

```glsl
#version 450

struct SPIRV_Cross_Input
{
    vec4 vColor;
    vec2 vTex;
};

struct SPIRV_Cross_Output
{
    vec4 FragColor;
};

uniform sampler2D SPIRV_Cross_CombineduTex_uTex_sampler;

layout(location = 0) in vec4 stage_input_vColor;
layout(location = 1) in vec2 stage_input_vTex;
layout(location = 0) out vec4 _entryPointOutput_FragColor;
vec4 FragColor;
vec4 vColor;
vec2 vTex;

void main()
{
    vColor = stage_input_vColor;
    vTex = stage_input_vTex;
    FragColor = vColor * texture(SPIRV_Cross_CombineduTex_uTex_sampler, vTex);
    _entryPointOutput_FragColor = FragColor;
}

```

Notice

```glsl
uniform sampler2D SPIRV_Cross_CombineduTex_uTex_sampler;
```

loosed its binding point, resulting in incorrect binding point assumptions by a graphics driver. In this case it may be correct since `SamplerState _uTex_sampler : register(s0);` starts from register 0, for any other register this will result in incorrect sampler picking.

x86_64 Linux binaries used for this repro, just in case:
[glslc.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/2031668/glslc.zip)
[spirv-cross.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/2031669/spirv-cross.zip)

**Comment by procedural** [comment]
How that line should look for correct behaviour:

```
layout(binding = 0) uniform sampler2DArray SPIRV_Cross_Combinedt_colors_color;
```

**Comment by procedural** [comment]
Maybe have an option to map them directly? Because for my shaders if I map sampler at register s2, I use it only for texture at register t2...

**Comment by procedural** [comment]
Without this mapping, some of my shaders mention only some sampler registers like s2 and s3 for example, and in OpenGL I bind samplers at binding points 2 and 3 respectively, but currently without GLSL sampler binding points the driver interprets them as if they are bound to s0 and s1 given no explicit binding points was provided.

**Comment by procedural** [comment]
Manually setting samplers to correct binding points helps, I just can't see why spirv-cross loses `register(s0)`, `register(s1)`, `register(s2)` information I provide in shaders so it could use them to generate direct `layout(binding = 0)`, `layout(binding = 1)`, `layout(binding = 2)` GLSL variants?

**Comment by procedural** [comment]
> That assumes you want a 1:1 mapping, but not everyone would want that (it's not always that easy).

Can we have an option for that? Or, where should I look in spirv-cross source code to at least make the change my shaders need for my local version?

**Comment by procedural** [comment]
By the way, I should clarify that I don't set texture's implicit samplers, I always create and set separate sampler objects: https://www.khronos.org/opengl/wiki/Sampler_Object

**Comment by procedural** [comment]
> When a sampler object is bound to a texture image unit, the internal sampling parameters for a texture bound to the same image unit are all ignored. Instead, the sampling parameters are taken from this sampler object.

I'm definitely not the only one who does this if even the official documentation specifically mentions it...

**Comment by HansKristian-ARM** [comment]
So, from an API point of view, what you need to do for this kind of mapping is:
```
compiler->build_combined_image_samplers();
const vector<CombinedImageSampler> &samplers = compiler->get_combined_image_samplers();
for (auto &s : samplers)
{
    uint32_t binding = compiler->get_decoration(compiler->image_id, spv::DecorationBinding); // or sampler_id.
    compiler->set_decoration(compiler->combined_id, spv::DecorationBinding, binding);
}
compiler->compile(); // Get GLSL.
```

**Comment by procedural** [comment]
> If you think this is good enough for this use case, I will consider adding it as a CLI option.
If I'm not asking too much, could you please add it to CLI as an option and paste source difference patches here so I could apply them and test on my end? I don't use API and dunno how...

**Comment by HansKristian-ARM** [comment]
If I make a pull request with this feature, would you be able to pull that and see if it fixes the issue?

**Comment by procedural** [comment]
Sure!

**Comment by HansKristian-ARM** [comment]
Try this: https://github.com/KhronosGroup/SPIRV-Cross/pull/586
Add --combined-samplers-inherit-bindings to the command line.
