### ISSUE TITLE
shaders/tesc/basic.tesc fails

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Cross#6]
Generated GLSL in /tmp/tmpt1cmqw_0basic.tesc does not match reference /blah/SPIRV-Cross/shaders/tesc/basic.tesc!
```
$ diff /tmp/*tesc ../shaders/tesc/basic.tesc
3d2
< layout(vertices = 1) out;
5c4,6
< out patch vec3 vFoo;
---
> patch out vec3 vFoo;
> 
> layout(vertices = 1) out;
9,14c10,15
<     gl_TessLevelInner[0] = 8.8999996185302734375;
<     gl_TessLevelInner[1] = 6.900000095367431640625;
<     gl_TessLevelOuter[0] = 8.8999996185302734375;
<     gl_TessLevelOuter[1] = 6.900000095367431640625;
<     gl_TessLevelOuter[2] = 3.900000095367431640625;
<     gl_TessLevelOuter[3] = 4.900000095367431640625;
---
>     gl_TessLevelInner[0] = 8.9;
>     gl_TessLevelInner[1] = 6.9;
>     gl_TessLevelOuter[0] = 8.9;
>     gl_TessLevelOuter[1] = 6.9;
>     gl_TessLevelOuter[2] = 3.9;
>     gl_TessLevelOuter[3] = 4.9;
17d17
< 
```

There are three problems: 
* ordering of the "out patch" vs. "patch out"
* location of the layout directive
* floating point numbers that can't be represented exactly. For these I recommend using a fractional portion like .875 instead of .9

**Comment by HansKristian-ARM** [comment]
Is that log from test_shaders.py? If test_shaders.py tests against original shaders that's a bug, but it doesn't do that for me.

The output there does match with the reference files under reference/, it should not try to test against the original shader.

 * out patch vs patch out. glslangValidator validates this. Is this not allowed according to spec?
 * Layout directive should not matter if it comes before or after out patch.
 * I agree on ugly FP numbers in general. Should clean that up in tests to avoid ugly output like this.

**Comment by HansKristian-ARM** [comment]
This issue should be resolved with https://github.com/KhronosGroup/SPIRV-Cross/pull/7.

**Comment by dneto0** [comment]
Works for me now.  It's a nice cleanup. Thanks.
