### ISSUE TITLE
[MSL] Option to generate real constants for SPIR-V specialization constants

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/SPIRV-Cross#601]
This is another request for a feature that would make SPIRV-Cross more friendly to my particular use case. It may not fit in with the overall vision for the project, but I figured a discussion of it couldn't hurt.

SPIR-V specialization constants are currently translated over to Metal Function Constants, which are a relatively similar concept. However, they don't have default values, and you need to provide the full set of substitutions when you actually create an `MTLFunction` at runtime.

It might be useful for the MSL compiler to have an option to simply "materialize" the specialization constants into real const variables with the specified default values defined by the compiler. This would allow you to directly use the code in an MTLFunction, which in some ways is closer happens when you compile to HLSL/GLSL and substitute in the constants at compile-time.

**Comment by HansKristian-ARM** [comment]
I believe there is an optimization pass in SPIRV-Tools already which can lower specialization constants into real constants, maybe check if that exists?

Modifying spec constants into real constants is a fairly trivial operation at any rate.

**Comment by HansKristian-ARM** [comment]
Ok, it seems like this can be trivially solved on the app side, so closing this.
