### ISSUE TITLE
Discuss approach to supporting in/out matrices in MSL

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#602]
@HansKristian-ARM, et al...

The GLSL `in` and `out` variable declarations get translated to vertex output structure and fragment `stage_in` structure elements.

In GLSL it is posible to define a matrix as an `in` or `out` variable.

However...In MSL, matrices (and scalar & vector arrays) cannot be passed as between vertex and fragment shaders in the vertex shader output struct and the fragment `stage_in` struct.

One way around this might be to convert the matrices back and forth to 4 (or less depending on matrix size) vectors, each with its own element in the `in/out` struct.

Assuming this makes sense...I'd like to discuss how best to do this.

My thoughts so far revolve around having `CompilerMSL` special-case matrices in the `OpLoad` and `OpStore` operations to inject code that will convert back and forth to vectors appropriately when it knows it is dealing with a matrix that is part of `StorageClassInput` or `StorageClassOutput` struct.

I'm throwing this issue out here for discussion...because I'm not sure this will cover all use-cases...and I'm not sure that there are not better approaches that could be explored.

For example...could the existing flattening functions within `CompilerGLSL` be of any help here? I am not familiar with their use.

Or would it be better to inject the appropriate conversion code into the SPIR-V itself...maybe by `glslang`?

Thoughts?

Thanks.

**Comment by HansKristian-ARM** [comment]
For considering just input/output, I think we can go with a lowering scheme. E.g. the internal variable is a matrix, but at the end of a vertex shader, or start of a fragment shader, we can copy over the matrix.

I did this recently with MSL MRT for example, where if you have an array of render targets, I had to flatten that separately. Internally, I have an actual array, but and the end of main(), the array elements are written out to the MSL render targets.

The problem with flattening a matrix is that you can dynamically index into one, so we need at least to express it as an array-of-vectors if we are going to directly flatten things.

**Comment by billhollings** [comment]
@HansKristian-ARM  I've started to explore this. Let me know if you are too.

**Comment by HansKristian-ARM** [comment]
No, I haven't looked into this yet, go ahead.

**Comment by billhollings** [comment]
This enhancement was added in PR #607.
