### ISSUE TITLE
Accurate retrieval of access modifiers for uniforms?

### ISSUE THREAD

**Issue by fuchstraumer** [KhronosGroup/SPIRV-Cross#606]
I'm currently having a wicked difficult time figuring out how to accurately extract access modifiers (i.e, `writeonly`, `readonly`, `restrict`, etc) from SPIR-V I'm doing reflection on. Being able to assess if a resource is `writeonly` or `readonly` would be extremely valuable, and I'm guessing it must be information we can access somehow- I just am confused on how it's done?

I'm going to use some examples to quickly show my particular problem. Lets start with the resources as they head into glslang:
```glsl
// Resource block: Lights
layout (set = 1, binding = 0, rgba8) readonly restrict uniform imageBuffer lightColors;
layout (set = 1, binding = 1, rgba32f) restrict uniform imageBuffer positionRanges;
// End resource block

// Resource block: ClusteredForward
layout (set = 2, binding = 0, r32ui) restrict uniform uimageBuffer lightCountTotal;
layout (set = 2, binding = 1, r32ui) restrict uniform uimageBuffer lightBounds;
layout (set = 2, binding = 2, r8ui) restrict uniform uimageBuffer Flags;
layout (set = 2, binding = 3, r32ui) restrict uniform uimageBuffer lightList;
layout (set = 2, binding = 4, r32ui) restrict uniform uimageBuffer lightCounts;
layout (set = 2, binding = 5, r32ui) restrict uniform uimageBuffer lightCountOffsets;
layout (set = 2, binding = 6, r32ui) restrict uniform uimageBuffer lightCountCompare;
// End resource block
```

If I check the generated SPIR-V, I can see that the `restrict` qualifier is preserved via a dedicated decoration:
```
OpDecorate %Flags DescriptorSet 2
OpDecorate %Flags Binding 2
OpDecorate %Flags Restrict
```

My confusion comes from checking the GLSL generated feeding spirv-cross the binary - here, qualifiers I didn't add are added:

```glsl
layout(set = 1, binding = 1, rgba32f) uniform restrict imageBuffer positionRanges;
layout(set = 2, binding = 1, r32ui) uniform restrict writeonly uimageBuffer lightBounds;
layout(set = 2, binding = 2, r8ui) uniform restrict readonly uimageBuffer Flags;
layout(set = 2, binding = 4, r32ui) uniform restrict uimageBuffer lightCounts;
```

I'm guessing SPIR-V doesn't really store the access qualifiers, or isn't entirely aware of them? Then the access qualifiers in the generated code are based on usage of SPIR-V variables. Is there any way to easily extract from spirv-cross that our "Flags" `uimageBuffer` resource is used as `readonly`, `lightBounds` is `writeonly`, etc, or is this not really easily accomplished?

Currently checking for `DecorationNonWritable` and `DecorationNonReadable` doesn't work, as texel buffers and storage images both always have both these flags set, it seems?

I've done my best to crawl deep through the code that generates these qualifiers, and I'm still lost so help would be really appreciated. Thanks!

**Comment by fuchstraumer** [comment]
_Aaaaaand_ closed my own issue by playing around with things a bunch more.

Making sure to call `compile()` seems to have done the trick. Still guessing that, effectively, SPIR-V doesn't really know about `readonly`/`writeonly` though? Whatever the case, it's really proving useful for rendergraph construction and dependency management stuff, and extracting it this way is fine I think.

**Comment by HansKristian-ARM** [comment]
What I suspect happens here is that SPIRV-Cross needs to deduce if a resource is read-only or write-only, even if the SPIR-V has declared nothing. This is to combat a restriction in ESSL 3.1, which in many cases can only support certain formats if it's writeonly/readonly, but not R/W.

When you call compile, it will internally modify readonly/writeonly flags based on usage, so this behavior is expected, albeit a bit awkward.
