### ISSUE TITLE
Option to remove SPIRV_Cross_BaseInstance

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#614]
I'm looking into switching to SPIRV-Cross for our GL/GLES shader toolchain; I currently can't disable SPIRV_Cross_BaseInstance output and emit GL-compatible shaders. We never use base instance != 0, and this adds redundant shader instructions. Would it be possible to only emit SPIRV_Cross_BaseInstance if the corresponding option is set?

**Comment by HansKristian-ARM** [comment]
Should be easy.

**Comment by zeux** [comment]
Thanks!
