### ISSUE TITLE
'flat' keyword omitted

### ISSUE THREAD

**Issue by luboslenco** [KhronosGroup/SPIRV-Cross#62]
When passing integer attributes from geometry shader into fragment shader, 'flat' keyword used to prevent interpolation is removed from the output. For integers, 'flat' seems to be mandatory and thus removing it will break the shader.

Source:
```glsl
// Geometry shader
out fData {
    flat int axis;
} frag;

// Fragment shader
in fData {
    flat int axis;
} frag;
```

Output:
```glsl
// Geometry shader
out fData {
    int axis;
} frag;

// Fragment shader
in fData {
   int axis;
}
```

Am I missing something? Is there a way to preserve 'flat'?

I am using SPIRV-Cross through [krafix](https://github.com/KTXSoftware/krafix), macos 10.11.6 / win 10, Intel Iris GPU.

**Comment by HansKristian-ARM** [comment]
Pretty sure this is an oversight when emitting blocks, those are handled differently than plain varyings, should be a trivial fix.

**Comment by HansKristian-ARM** [comment]
Fixed.

**Comment by luboslenco** [comment]
Crazy support going on here - thanks for building amazing tools.
