### ISSUE TITLE
Sample code in Struct member reflection in the wiki does not compile

### ISSUE THREAD

**Issue by YukinoHayakawa** [KhronosGroup/SPIRV-Cross#632]
[https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide#struct-member-reflection](url)

At the last line `comp.get_member_name(type, i)`, type is a SPIRType while the function requires a uint32_t.  It seems that I should use `type.self` instead?

**Comment by HansKristian-ARM** [comment]
Correct, thanks for finding the error. I've updated the page with `type.self`.
