### ISSUE TITLE
MSL: Lookup table codegen causes spilling on NVidia drivers

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#633]
This is sort of a cross-post of this https://github.com/KhronosGroup/glslang/issues/1430 - based on my renewed understanding of the SPIRV limitations it's starting to look like this problem can only be addressed on SPIRV-Cross side.

Given this shader:

```
float4 main(uint iid: SV_InstanceId): SV_Position
{
    static const float3 uvRoutingA[16] = { float3(0,0,1),  float3(1,0,0), float3(1,0,0), float3(0,0,1),  float3(1,0,0), float3(1,0,0),  float3(1,0,0),        float3(1,0,0),           float3(0,0,1),        float3(0,0,0), /* #10: */ float3(1,0,0), float3(0,1,0), float3(0,1,0), float3(1,0,0), float3(0,1,0),  float3(0,1,0) };

    return float4(uvRoutingA[iid], 1);
}
```

SPIRV-Cross MSL translation generates this code:

```
vertex main0_out main0(uint gl_InstanceIndex [[instance_id]])
{
    main0_out out = {};
    float3 _45[16] = {float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0)};
    out.gl_Position = float4(_45[gl_InstanceIndex], 1.0);
    return out;
}
```

We currently use https://github.com/zeux/hlslparser; it has support for lifting static const arrays out to global scope, producing this code:

```
const static constant constexpr float3 uvRoutingA[16] = { float3(0, 0, 1), float3(1, 0, 0), float3(1, 0, 0), float3(0, 0, 1), float3(1, 0, 0), float3(1, 0, 0), float3(1, 0, 0), float3(1, 0, 0), float3(0, 0, 1), float3(0, 0, 0), float3(1, 0, 0), float3(0, 1, 0), float3(0, 1, 0), float3(1, 0, 0), float3(0, 1, 0), float3(0, 1, 0) };
...
vertex main0_out main0(uint gl_InstanceIndex [[instance_id]])
{
    main0_out out = {};
    out.gl_Position = float4(uvRoutingA[gl_InstanceIndex], 1.0);
    return out;
}
```

In one of our production shaders, the construct seen above happens two times (with two separate tables); on NVidia drivers in latest OSX, the shader generated from SPIRV-Cross output is very inefficient - on a full frame where only some of the draw calls use that, the GPU time jumps from 10 ms (as compiled by hlslparser) to 26 ms (as compiled by glslang+spirv-cross). I suspect that the driver compiler is spilling the array to perform dynamic indexing which takes forever.

It seems like SPIRV-Cross needs to learn to lift the table literals to the global scope similarly to hlslparser, and index them directly *without* copying them to local variables with spvArrayCopy or whatnot.

**Comment by zeux** [comment]
Just to have a more precise example from our production shader, not the simplified version above, here's an excerpt from SPIRV-Cross generated MSL (that takes 26 ms) - there's only 2 arrays, but there's 2 lookups into each so they are replicated twice:

```
    float3 _575[16] = {float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0)};
    float2 _982 = _1008;
    _982.x = dot(_142.CB1[gl_InstanceIndex].uvScale.xyz, _575[_614]);
    float3 _576[16] = {float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.699999988079071044921875, 0.699999988079071044921875, 0.0), float3(0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, -1.0), float3(0.0, 0.0, 1.0)};
    float2 _984 = _982;
    _984.y = dot(_142.CB1[gl_InstanceIndex].uvScale.xyz, _576[_614]);
    float3 _577[16] = {float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(1.0, 0.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0)};
    float2 _986 = _1008;
    _986.x = dot(_142.CB1[gl_InstanceIndex].scale.xyz, _577[_614]);
    float3 _578[16] = {float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 1.0, 0.0), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.0, 0.699999988079071044921875, 0.699999988079071044921875), float3(0.699999988079071044921875, 0.699999988079071044921875, 0.0), float3(0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, 1.0), float3(1.0, 0.0, 0.0), float3(0.0, 0.0, 1.0), float3(0.0, 0.0, -1.0), float3(0.0, 0.0, 1.0)};
    float2 _988 = _986;
```

And here's the hlslparser:

```
        float2 selector;
        selector.x = dot(uvScale.xyz, uvRoutingA[normalId]);
        selector.y = dot(uvScale.xyz, uvRoutingB[normalId]);
        uv = ((uv * selector) + matUvOffs.xy);
        selector.x = dot(scale.xyz, uvRoutingA[normalId]);
        selector.y = dot(scale.xyz, uvRoutingB[normalId]);
        uvStuds = (uvStuds * selector);
```

**Comment by zeux** [comment]
Just to keep everything nicely linked, here’s a DXC bug: https://github.com/Microsoft/DirectXShaderCompiler/issues/1398. DXC generates and extra branch that hopefully can be removed as part of this issue; my overarching goal is to make sure static constexpr array can be emitted from SPIRV produced by both compilers.

I think I more or less understand how to hack up a solution for this assuming there’s easy access to domination info... I’ll try to take a look at this later this week, although implementation suggestions are certainly welcome.

**Comment by HansKristian-ARM** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.cpp#L3650 is the grand place where domination for all variables and temporaries live. I'm not sure this will be enough. It doesn't track all the info I think you'll need though.

**Comment by HansKristian-ARM** [comment]
I've started refactor some internals to make this analysis possible. This won't be easy though ...

**Comment by HansKristian-ARM** [comment]
Should "just werk" now when DXC fixes their static const init issue.
