### ISSUE TITLE
frame buffer fetch extension support

### ISSUE THREAD

**Issue by DsoTsin** [KhronosGroup/SPIRV-Cross#634]

**Comment by alek314** [comment]
I think it's about programmable blending (quote from Metal-Shading-Language-Specification):

The GLSL version is:
#extension GL_APPLE_shader_framebuffer_fetch : require
void main()
{
// RGB to grayscale
mediump float lum = dot(gl_LastFragData[0].rgb, vec3(0.30,0.59,0.11));
gl_FragColor = vec4(lum, lum, lum, 1.0);
} 

The Metal version equivalent is:
fragment half4
paint_grayscale(half4 dst_color [[color(0)]])
{
// RGB to grayscale
half lum = dot(dst_color.rgb, half3(0.30h, 0.59h, 0.11h));
return half4(lum, lum, lum, 1.0h);
}

**Comment by HansKristian-ARM** [comment]
Right, for this case, SPIRV-Cross can already implement it.
You'd do something like `set_remapped_variable_state` for some input or subpassInput variable. Rename it to gl_LastFragData with set_name, then add the extension using require_extension.

**Comment by DsoTsin** [comment]
Thanks for clarifying my confusion, it works.
