### ISSUE TITLE
No SPIR-V support for Mali G71 public drivers

### ISSUE THREAD

**Issue by huzz** [KhronosGroup/SPIRV-Cross#640]
HI, I am trying to cross compile tensorflow on aarch64 platform. My board is Hikey 960 having the Mali G71 GPU. I have installed the GPU drivers available publically on the ARM official website (https://developer.arm.com/products/software/mali-drivers/user-space). The documentation for the installation that i am following is :
https://developer.codeplay.com/computecppce/latest/tensorflow-arm-setup-guide 

It installed successfully but while running any model or benchmarks on tensorflow I get an error because the public drivers of Mali G71 do not have the Spir-v support.

is there any was I can compile this to enable Spir-v support to make tensorflow?

**Comment by HansKristian-ARM** [comment]
Huh? This issue has nothing to do with SPIRV-Cross. Closing.
