### ISSUE TITLE
buffer_is_packing_standard() initializer defaults conflict with windows headers.

### ISSUE THREAD

**Issue by johnhable** [KhronosGroup/SPIRV-Cross#641]
Hi,

In spirv_glsl.hpp, there is a compiler issue on Windows.
```
bool buffer_is_packing_standard(const SPIRType &type, BufferPackingStandard packing, uint32_t start_offset = 0,
	                                uint32_t end_offset = std::numeric_limits<uint32_t>::max());
```

Windows complains about the max(). Can we instead just hardcode the constant? Or we could make the default 0, and ignore end_offset in that case.

**Comment by HansKristian-ARM** [comment]
Use NOMINMAX? `~(0u)` is also fine if it's a problem.

**Comment by johnhable** [comment]
~(0u) is fine, although my vote would actually be zero, with an if inside (so it doesn't bounds check if it is 0). That way you are explicitly telling the api that you are not bounds checking, as opposed to just setting it to the highest value and hoping for the best. But it's not a big deal either way.

It's not a problem for me specifically, but in general I advocate removing dependencies like these unless there is a very compelling reason. Maybe someone out there uses a large codebase that relies on Windows.h min/max behavior for some reason? It's unlikely but there are some wacky codebases out there. Replacing with a constant is probably the easiest solution that is guaranteed to work for everybody.

**Comment by HansKristian-ARM** [comment]
Ok, removed any `<limits>` use from public headers, should be compatible with min/max macro pollution now.
