### ISSUE TITLE
Tagging a version

### ISSUE THREAD

**Issue by dholm** [KhronosGroup/SPIRV-Cross#642]
Would you mind tagging a version of SPIRV-Cross so that it can be packaged in Homebrew?

**Comment by HansKristian-ARM** [comment]
Would any commit do? I think the only logical thing to tag would be current master.

**Comment by dholm** [comment]
Yes, I guess so.

**Comment by HansKristian-ARM** [comment]
I've tagged current HEAD: https://github.com/KhronosGroup/SPIRV-Cross/tree/2018-08-07.
