### ISSUE TITLE
OpFunctionCall can emit bad MSL (address space mismatch)

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/SPIRV-Cross#643]
[This commit](https://github.com/prideout/SPIRV-Cross/commit/e2090e5f5199374c781583e62fadaf2194f779b5) adds a SPIR-V assembly test case that fails when compiling MSL with the following error message:

```
shaders-msl/asm/reference/frag/address-space.asm.frag:533:30: error: no matching function for call to 'computePreExposedIntensity'
    light.colorIntensity.w = computePreExposedIntensity(colorIntensity.w, frameUniforms.exposure);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
shaders-msl/asm/reference/frag/address-space.asm.frag:494:7: note: candidate function not viable: 2nd argument ('const constant float') is in address space 8388361, but parameter must be in address space 0
    float computePreExposedIntensity(thread const float& intensity, thread const float& exposure)
```

To repro, cherry-pick the aforementioned commit, or add [this asm file](https://github.com/KhronosGroup/SPIRV-Cross/files/2229849/address-space.asm.txt) to `shaders-msl/asm/frag` and do:

`./test_shaders.py shaders-msl/asm/frag --msl`

**Comment by HansKristian-ARM** [comment]
I'll have a look when I'm back from holiday, or @billhollings might be able to have a look at it earlier.

**Comment by prideout** [comment]
Thanks for the attention! In an effort to make this bug more palatable, I pared down the provoking SPIRV somewhat:

[address-space.asm.frag.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2233033/address-space.asm.frag.txt)

This also avoids an uninitialized warning in my earlier test case, which could distract from the actual issue.

**Comment by HansKristian-ARM** [comment]
Confirmed. The SPIR-V seems to take the arguments to that function by value, and not reference, yet MSL output uses const-reference, which is wrong.

**Comment by HansKristian-ARM** [comment]
Should be fixed now.
