### ISSUE TITLE
Glsl backend doesn't allow duplicate block names in different shader interfaces

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#645]
According to the glsl spec in section 4.3.9:

> A block name is allowed to have different definitions in different shader interfaces within the same shader, allowing, for example, an input block and output block to have the same name.

I'm running across this issue because I generate each shader stage in isolation of all others. In particular, this makes it difficult to know what to name an interface block if a geometry shader can show up in the middle. The easiest solution is to name all input/output interface blocks the same thing, but currently spirv-cross will determine that a name is a duplicate even though the shader interface is different. This seems to be around line 1589 of spirv_glsl.cpp.

**Comment by HansKristian-ARM** [comment]
I'll have a look when I'm back from holiday.

**Comment by jodavis42** [comment]
Enjoy your holiday! I can do a temp workaround so it's no rush.

**Comment by HansKristian-ARM** [comment]
So, it seems like even something crazy like this is legal in GLSL:
```
#version 450

layout(triangles) in;
layout(max_vertices = 4, triangle_strip) out;

layout(set = 0, binding = 0) uniform VertexInput
{
	vec4 a;
};

layout(set = 0, binding = 0) buffer VertexInput
{
	vec4 b;
};

layout(location = 0) in VertexInput
{
	vec4 vColor;
} vin[];

layout(location = 0) out VertexInput
{
	vec4 vColor;
};

void main()
{
	vec4 VertexInput = vec4(1.0);
	gl_Position = VertexInput + a + b;
	vColor = vin[0].vColor;
	EmitVertex();
}
```
It should be possible to UBO/SSBO/IN/OUT blocks their own namespace.
