### ISSUE TITLE
Optimized spirv can produce an invalid global sampler

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#647]
The attached file is an optimized spirv assembly file. When this is run through spirv-cross, it produces a global sampler that isn't decorated with uniform which causes a glsl compiler error. This seems to be get declared in CompilerGLSL::declare_undefined_values. I'm unsure exactly where the variable comes from as it's not a declared global, but I'd have to guess it's auto-generated from a OpSampledImage instruction.

[UnusedSampler.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2236678/UnusedSampler.txt)

**Comment by jodavis42** [comment]
So it looks like this was an issue on my end. I had accidentally declared samplers' pointer type with the function storage class instead of uniform constant which caused the optimizer to do some really odd stuff. For instance, it undefs the sampler type and then uses the result of the undef as an argument to OpSampledImage. When I fixed the storage type on my pointer then this issues seems to be gone.

I'll file a bug on the validator about this. Should I close this or are there other paths you might want to check related to this?

**Comment by HansKristian-ARM** [comment]
An undefined sampler makes no sense, especially if you say it's optimizer related, so I'll close this.
