### ISSUE TITLE
Reflection: storage buffer size is always 0

### ISSUE THREAD

**Issue by awefers** [KhronosGroup/SPIRV-Cross#649]
Hi,

I noticed that the size for storage buffers is always reported as 0. Here is an example, source:

	// test.frag.hlsl

	struct Data
	{
	    float4 m_color;
	};

	StructuredBuffer< Data > in_buffer : register( b0 );

	float4 main() : SV_TARGET0
	{
	    return in_buffer.Load( 0 ).m_color;
	}

Compiled via "glslangValidator -Os -V -e main -o test.frag.spv test.frag.hlsl". Outputs the following from "spirv-cross --dump-resources test.frag.spv":

	=============

	ssbos
	=============

	 ID 015 : in_buffer (Set : 0) (Binding : 0) readonly (BlockSize : 0 bytes)

Shouldn't this report a size of 16 bytes?

**Comment by HansKristian-ARM** [comment]
This is working as expected. A StructuredBuffer is an unsized array in SPIR-V, hence 0 bytes. If you need to find the size of the Data struct, you'll need to check the declared size of type.member_types[0].

**Comment by awefers** [comment]
Thanks, that works for me!
