### ISSUE TITLE
Writing readonly in variable in GLSL

### ISSUE THREAD

**Issue by baszalmstra** [KhronosGroup/SPIRV-Cross#65]
When converting an HLSL shader that does something like this:

```
PSInput Main(VSInput input)
{
  input.Position.y = 0;
  ...
}
```

it is converted to glsl that looks something like this:

```
layout(location = 0) in vec4 Position;
...

void main()
{
  Position.y = 0.0;
}
```

The driver does not accept this because `Position` is readonly. To fix this I can simply change the hlsl to introduce a temporary local variable which is used further in the function (`float3 tempPos = input.Position`). However, I think this should be done by the cross compiler or it should be an error caught by the cross compiler.

**Comment by HansKristian-ARM** [comment]
Do you have the full source of the HLSL shader? This sounds like a glslang bug to me.

**Comment by baszalmstra** [comment]
The example below modifies the `x` coordinate of the input. It generates invalid GLSL because it modifies the `in` variable `Position`.

HLSL:
```
cbuffer Camera 
{
    float4x4 ViewProjection;
};

struct InVsSprite
{
    float4 Position : POSITION;
    float4 Color : COLOR0;
    float2 TexCoord : TEXCOORD0;
};

struct InPsSprite
{
    float4 Position : SV_POSITION;
    float4 Color : TEXCOORD0;
    float2 TexCoord : TEXCOORD1;
};

InPsSprite Main(InVsSprite input)
{
    InPsSprite result;
    input.Position.x += 1.0f;
    result.Position = mul(float4(input.Position.xyz, 1), ViewProjection);
    result.Color = input.Color;
    result.TexCoord = input.TexCoord;
    return result;
}
```

The generated GLSL (for version 4.1)
```
#version 410
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct InPsSprite
{
    vec4 Position;
    vec4 Color;
    vec2 TexCoord;
};

layout(binding = 0, std140) uniform Camera
{
    layout(row_major) mat4 ViewProjection;
} _27;

layout(location = 0) in vec4 Position;
layout(location = 1) in vec4 Color;
layout(location = 2) in vec2 TexCoord;
layout(location = 0) out vec4 Color_1;
layout(location = 1) out vec2 TexCoord_1;

void main()
{
    Position.x = (Position.x + 1.0);
    InPsSprite result;
    result.Position = (_27.ViewProjection * vec4(Position.xyz, 1.0));
    result.Color = Color;
    result.TexCoord = TexCoord;
    gl_Position = result.Position;
    Color_1 = result.Color;
    TexCoord_1 = result.TexCoord;
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}
```

Note that the above HLSL works on Windows.

**Comment by HansKristian-ARM** [comment]
Hm, which glslang commit are you on and which command line arguments did you use?
I can't get valid SPIR-V for this HLSL file.
I'm on `e19e68d4313617b8f` and I get this validation error from spirv-val.

```
Function end cannot be called in blocks.
          %4 = OpFunction %2 None %3
          %5 = OpLabel
               OpFunctionEnd <-- This is wrong.

```

Similar error is found in spirv-cross and exception is thrown:
```
terminate called after throwing an instance of 'spirv_cross::CompilerError'
  what():  Cannot start a block before ending the current block.
zsh: abort (core dumped)  ./spirv-cross /tmp/test.spv
```

**Comment by baszalmstra** [comment]
Strange .. When I run this:
```
glslangValidator -D -V -e Main hlsl.vert -o hlsl.spv
spirv-cross --version 410 hlsl.spv
``` 

With the hlsl as above it outputs the glsl as above. 

glslang is at `e19e68d4313617b8fe8bb68578d2de51507e603f`
SPIRV-Cross is at `8199986c0e21af2c1a25d9e527bf51497ed43e7c`

spirv-val also reports no error with the generate hlsl.spv.

**Comment by HansKristian-ARM** [comment]
Oh, you're using -e ... Ye, now I see what you mean.
This is indeed a glslang bug, SPIR-V spec says.

```
StorageClass:
1 Input
Input from pipeline. Visible across all
functions in the current invocation. Variables
declared with this storage class are read-only,
and cannot have initializers.
```
and the SPIR-V contains
```
         %13 = OpTypePointer Input %6

         %14 = OpAccessChain %13 %9 %12
         %15 = OpLoad %6 %14
         %16 = OpFAdd %6 %15 %10
         %17 = OpAccessChain %13 %9 %12
               OpStore %17 %16

```

The InVsSprite here is mapped to Input, so it tries to store to it. Not even spirv-val catches this it seems. I'll file some bugs for those tools instead.

**Comment by baszalmstra** [comment]
Thanks, I'll track that. This can be closed then.
