### ISSUE TITLE
Is SPIRV-Cross supports converting Metal Shader to SPIRV?

### ISSUE THREAD

**Issue by Michael-Lfx** [KhronosGroup/SPIRV-Cross#650]
I have written some Metal Shader file and want to convert it to vulkan compatible SPIRV. I don't want to rewrite them to OpenGL Shader (from GLSL to SPIR is verified) by hand. Hence, **is SPIRV-Cross supports converting Metal Shader to SPIRV?**

**Comment by HansKristian-ARM** [comment]
No. There is no Metal -> SPIR-V compiler out there to my knowledge.

**Comment by godratio** [comment]
Is there one now?

**Comment by esummers** [comment]
> Is there one now?

I would love to see this, but I don't think it will happen unless Apple releases the Metal compiler as open source.

**Comment by harry75369** [comment]
Is there one now?
