### ISSUE TITLE
Issue SPIRV->GLSL

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#651]
I've recently updated our whole hlsl -> glsl pipeline and updated glslang, SPIRV-Tools and SPIRV-Cross. Everything is working fine except for one shader that ends up using undefined variables. The translated code has a line that looks like the following:

```glsl
bool _989;
float _1013;
while (_967 < 16)
{
```

but 967 was not defined above. There are two or three similar ones. I *think* the SPIRV looks ok so my first port of call is SPIRV-Cross, as we've had many similar-looking ones in the past.

[shader_optimized.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2257149/shader_optimized.spv.txt)

**Comment by HansKristian-ARM** [comment]
Ok, this seems to be some edge case with loop variable handling and while loops.

**Comment by redorav** [comment]
Awesome thanks :+1:
