### ISSUE TITLE
Incorrect UBO name when SPIRV is compiled with glslc

### ISSUE THREAD

**Issue by awefers** [KhronosGroup/SPIRV-Cross#653]
Hi,

I have been experimenting with generating SPIRV from HLSL via glslc instead of glslangValidator. I have come across an issue with incorrect reflection data, that seems to happen when multiple uniform blocks of the same size are present if optimization for size (-Os) is enabled with glslc.

Here is a vertex shader example:

	// test01.vert.hlsl

	struct Buffer0
	{
	    float4x4 m_viewProjection;
	};

	struct Buffer1
	{
	    float4x4 m_world;
	};

	ConstantBuffer< Buffer0 > in_buffer0;
	ConstantBuffer< Buffer1 > in_buffer1;

	float4 main( in float3 in_position : SV_POSITION ) : SV_POSITION
	{
	    const float4 position = in_buffer1.m_world * float4( in_position, 1.0f );

	    return in_buffer0.m_viewProjection * position;
	}

Compiled with:

	glslangValidator -Os -V450 -e main -o test01-glslangValidator.vert.spv test01.vert.hlsl

And:

	glslc -Os -c -g -fshader-stage=vertex -fentry-point=main -o test01-glslc.vert.spv test01.vert.hlsl

The output for test01-glslangValidator.vert.spv looks all good:

	spirv-cross --vulkan-semantics --dump-resources test01-glslangValidator.vert.spv

	Entry points:
	  main (vertex)

	=============

	inputs
	=============

	 ID 043 : in_position (Location : 0)
	=============

	ubos
	=============

	 ID 019 : in_buffer1 (Set : 0) (BlockSize : 64 bytes)
	 ID 034 : in_buffer0 (Set : 0) (BlockSize : 64 bytes)
	=============

	#version 450

	layout(set = 0, std140) uniform in_buffer1
	{
	    layout(row_major) mat4 m_world;
	} in_buffer1_1;

	layout(set = 0, std140) uniform in_buffer0
	{
	    layout(row_major) mat4 m_viewProjection;
	} in_buffer0_1;

	layout(location = 0) in vec3 in_position;

	void main()
	{
	    gl_Position = in_buffer0_1.m_viewProjection * (in_buffer1_1.m_world * vec4(in_position, 1.0));
	}

The output for test01-glslc.vert.spv reports an incorrect name for UBO with ID 034, it should be in_buffer0:

	 spirv-cross --vulkan-semantics --dump-resources test01-glslc.vert.spv

	Entry points:
	  main (vertex)

	=============

	inputs
	=============

	 ID 043 : in_position (Location : 0)
	=============

	ubos
	=============

	 ID 019 : in_buffer1 (Set : 0) (BlockSize : 64 bytes)
	 ID 034 : in_buffer1 (Set : 0) (BlockSize : 64 bytes)
	=============

	#version 450

	layout(set = 0, std140) uniform in_buffer1
	{
	    layout(row_major) mat4 m_world;
	} in_buffer1_1;

	layout(set = 0, std140) uniform in_buffer0
	{
	    layout(row_major) mat4 m_world;
	} in_buffer0_1;

	layout(location = 0) in vec3 in_position;

	void main()
	{
	    gl_Position = in_buffer0_1.m_world * (in_buffer1_1.m_world * vec4(in_position, 1.0));
	}

Obviously the optimization for size in glslc is causing some form of hazard. The buffer naming in the generated source output is correct, so the name is correctly mapped in the SPIRV itself and I suspect that this is an issue with the SPIRV-Cross reflection?

As as side note, you will notice an aggressive optimization for the names of member variables in in_buffer0, they are aliased to the variable names of members in in_buffer1 (which I am fine with).

**Comment by awefers** [comment]
Never mind, just noticed the section on your Wiki. Using

	m_pCompiler->get_name( resource.id );

instead of

	m_pCompiler->get_name( resource.base_type_id );

gives me the correct name in my code (it is a little confusing tho when using the spirv-cross output for debugging).

**Comment by HansKristian-ARM** [comment]
Yes, naming becomes rather confusing when spirv-opt starts trying to reuse block types. It seems like this has leaked to cbuffers as well now, and not just UAVs.

The default reflection interface returns the block type name, but those might end up becoming the same when spirv-opt wants to share block types between different buffers. GLSL output will usually figure out some name if there are conflicts. For your case with HLSL and ConstantBuffer<T>, it will make more sense to use resource.id's name instead of base_type_id indeed.

There is an interface to query the block name used in the actual source after compilation is complete: https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L493. However, that name might be something you don't expect, so it might not be relevant.

At any rate, this is a known issue, and no obvious fix, so I'll leave it at that.
