### ISSUE TITLE
Segfault when generating metal shader.

### ISSUE THREAD

**Issue by dati91** [KhronosGroup/SPIRV-Cross#658]
I got a segfault with [this](https://gist.github.com/dati91/947ff1e3cd72d5166ec8828bfff3bde0) shader.
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5b)
    frame #0: 0x00000001007d487d wrench`spirv_cross::CompilerMSL::maybe_emit_array_assignment(this=0x0000000105035a00, id_lhs=195, id_rhs=193) at spirv_msl.cpp:2115
   2112		auto *var = maybe_get<SPIRVariable>(id_lhs);
   2113
   2114		// Is this a remapped, static constant? Don't do anything.
-> 2115		if (var->remapped_variable && var->statically_assigned)
   2116			return true;
   2117
   2118		if (ids[id_rhs].get_type() == TypeConstant && var && var->deferred_declaration)
Target 0: (wrench) stopped.
```
This was working before. Something went wrong between [this](https://github.com/KhronosGroup/SPIRV-Cross/tree/314f39a7c4b67acddb13caaaf690a9be2169e77e) and [this](https://github.com/KhronosGroup/SPIRV-Cross/tree/cc7679ee4586a2e19cb6277fe40228b03d191760) revision.

**Comment by HansKristian-ARM** [comment]
Oh, seems like a simple oversight where var can be NULL.

**Comment by kvark** [comment]
one more coin towards that billion dollar mistake fund :)
