### ISSUE TITLE
MSL: Wrongly named point_size builtin

### ISSUE THREAD

**Issue by h3xl3r** [KhronosGroup/SPIRV-Cross#66]
When generating MSL shader source with "MSLConfiguration.is_rendering_points" set to true, there's a mismatch in naming for the [[point_size]] builtin between output block and assigment in vertex function:

``` c
struct mmain_out
{
    float3 v_bary [[user(locn0)]];
    float4 gl_PerVertex_gl_Position [[position]];
    float gl_PerVertex_gl_PointSize [[point_size]];
    float gl_PerVertex_gl_ClipDistance /* [[clip_distance]] built-in not yet supported under Metal. */;
};

vertex mmain_out mmain(mmain_in in [[stage_in]], constant PushConstants& vs_pcs [[buffer(16)]], uint gl_VertexIndex [[vertex_id]], uint gl_InstanceIndex [[instance_id]])
{
    mmain_out out = {};
    out.v_bary = in.a_bary;
    out.gl_PointSize = 2.0;
    out.gl_PerVertex_gl_Position = (vs_pcs.mvp * in.a_position);
    return out;
}
```

`float gl_PerVertex_gl_PointSize [[point_size]];`
vs
`out.gl_PointSize = 2.0;`

**Comment by HansKristian-ARM** [comment]
@billhollings Any idea here?

**Comment by billhollings** [comment]
I'll have a look.

@h3xl3r   Can you post a file containing the original SPIRV for testing please? Also...if you have the original source (I assume GLSL or HLSL) that the SPIRV was created from, that would help in understanding the intention.

Thanks...

...Bill

**Comment by h3xl3r** [comment]
Here's the files.

shader.glsl is the original GLSL source input to glslang, with options:
```
EShMessages options = EShMsgDefault;
options = (EShMessages)(options | EShMsgSpvRules);
options = (EShMessages)(options | EShMsgVulkanRules);
```

shader.spv is the SPIR-V output of glslang.

shader.msl is the output of spirv-cross, with (relevant) options:
```
spirv_cross::MSLConfiguration default_msl_cfg;
default_msl_cfg.vtx_attr_stage_in_binding = 0;
default_msl_cfg.flip_vert_y = false;
default_msl_cfg.flip_frag_y = false;
default_msl_cfg.is_rendering_points = true;
```

I checked, this regression was introduced in 0943d9f, before that generated MSL for point builtin is fine.

[shader.glsl.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/565477/shader.glsl.zip)
[shader.msl.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/565479/shader.msl.zip)
[shader.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/565478/shader.spv.zip)

**Comment by h3xl3r** [comment]
I have patched it in my local branch by replicating what is being done for the [[position]] builtin for MSL, but as I am not 100% clear on why this is being done, I would like to see if the author of the breaking changes can come up with a better fix first.

**Comment by billhollings** [comment]
[Pull request #67](https://github.com/KhronosGroup/SPIRV-Cross/pull/67) submitted to fix this issue.

Fix is to avoid qualifying in/out struct members that are built-ins, which have unique names. In/out struct members that are not built-ins will still be qualified to avoid name-conflicts during in/out struct flattening.

In that sense, this fix is opposite to local fix from h3xl3r. Treatment for gl_Position built-in now reverts to earlier behaviour.
