### ISSUE TITLE
Compile error using array of textures

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#662]
I have a simplified shader that illustrates a problem I'm having.

```hlsl
TextureCube t0; SamplerState s0;
TextureCube t1; SamplerState s1;

float4 fragmentProgram(float4 input : INPUT0) : SV_Target0
{
	float4 result = 0;

	TextureCube texCubeArray[2];
	texCubeArray[0] = t0;
	texCubeArray[1] = t1;

	[unroll]
	for (int i = 0; i < 2; ++i)
	{
		result += texCubeArray[i].Sample(s0, input.xyz);
	}

	return result;
}
```

If I compile this to SPIR-V and then into glsl, the result I get is the following:

```glsl
uniform samplerCube _105[2];

layout(location = 0) in vec4 _input;
layout(location = 0) out vec4 _69;

void main()
{
    _0[0] = t0;
    _0[1] = t1;
    vec4 _103;
    _103 = vec4(0.0);
    for (int _102 = 0; _102 < 2; )
    {
        _103 += texture(_105[_102], _input.xyz);
        _102++;
        continue;
    }
    _69 = _103;
}
```

For some reason it has created a _0 variable that it's trying to assign into, and also hasn't declared t0 or t1 anywhere and it's failing to compile. The glsl I'm showing comes from optimized SPIR-V, but unoptimized SPIR-V presents the same problem. Fxc is ok with this setup if indices are known at compile time.

[fragmentProgram_optimized.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2310564/fragmentProgram_optimized.spv.txt)

**Comment by HansKristian-ARM** [comment]
I'm pretty sure this is invalid SPIR-V, but I'll have a look tomorrow.

**Comment by HansKristian-ARM** [comment]
Ok, this is bogus SPIR-V, but the validation doesn't catch it.

The SPIR-V is trying to load the two textures, store them to a stack variable, then read from them. _0 is emitted because of an old, obsolete workaround for invalid SPIR-V.

This is not allowed in SPIR-V. The legalization pass in spirv-opt must unroll the array, and unroll the loop properly to make this work.

**Comment by redorav** [comment]
Understood, I'll send it over to glslang and continute the conversation there. Thanks for taking the time to look into it.
