### ISSUE TITLE
Generate Buffer access code for texel buffer views

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/SPIRV-Cross#664]
When the user has a texel buffer view, they typically want to access more elements than what Metal is limited for a texture dimension. We could generate MSL code that defines a buffer containing an array of texels of size 0, and then access this array dynamically instead of fetching texels from a texture.

**Comment by HansKristian-ARM** [comment]
MSL already emits 2D texture lookups to workaround this. Paging @billhollings.
Texel buffers need to perform automatic format conversion, so I don't see how you're going to fake that with a buffer.

**Comment by kvark** [comment]
Oh interesting. So just mapping a buffer to 2D texture is enough to support larger texel buffers. I guess we can close it then.

**Comment by billhollings** [comment]
Yup...this was implemented in PR #626.
