### ISSUE TITLE
Shared/threadgroup buffers break specialization constants in MSL

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/SPIRV-Cross#671]
Attempting to create a compute shader with a shared buffer generates incorrect MSL if the buffer is sized based on a specialization constant.

This GLSL

    #version 450

    layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;
    layout(constant_id = 1) const uint blockSize = 1;

    shared float bucket[blockSize];

    void main() {
        const uint tid = gl_LocalInvocationIndex;

        bucket[tid] = float(tid);

        memoryBarrierShared();
        barrier();
    }

generates this SPIR-V

               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %4 "main" %10
               OpExecutionMode %4 LocalSize 1 1 1
               OpSource GLSL 450
               OpName %4 "main"
               OpName %8 "tid"
               OpName %10 "gl_LocalInvocationIndex"
               OpName %13 "blockSize"
               OpName %16 "bucket"
               OpDecorate %10 BuiltIn LocalInvocationIndex
               OpDecorate %13 SpecId 1
               OpDecorate %25 SpecId 0
               OpDecorate %27 BuiltIn WorkgroupSize
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 0
          %7 = OpTypePointer Function %6
          %9 = OpTypePointer Input %6
         %10 = OpVariable %9 Input
         %12 = OpTypeFloat 32
         %13 = OpSpecConstant %6 1
         %14 = OpTypeArray %12 %13
         %15 = OpTypePointer Workgroup %14
         %16 = OpVariable %15 Workgroup
         %20 = OpTypePointer Workgroup %12
         %22 = OpConstant %6 1
         %23 = OpConstant %6 264
         %24 = OpConstant %6 2
         %25 = OpSpecConstant %6 1
         %26 = OpTypeVector %6 3
         %27 = OpSpecConstantComposite %26 %25 %22 %22
          %4 = OpFunction %2 None %3
          %5 = OpLabel
          %8 = OpVariable %7 Function
         %11 = OpLoad %6 %10
               OpStore %8 %11
         %17 = OpLoad %6 %8
         %18 = OpLoad %6 %8
         %19 = OpConvertUToF %12 %18
         %21 = OpAccessChain %20 %16 %17
               OpStore %21 %19
               OpMemoryBarrier %22 %23
               OpControlBarrier %24 %24 %23
               OpReturn
               OpFunctionEnd

which in turn generates incorrect MSL

    #include <metal_stdlib>
    #include <simd/simd.h>

    using namespace metal;

    constant uint _25_tmp [[function_constant(0)]];
    constant uint _25 = is_function_constant_defined(_25_tmp) ? _25_tmp : 1u;
    constant uint3 gl_WorkGroupSize = uint3(_25, 1u, 1u);

    kernel void main0(uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]])
    {
        threadgroup float bucket[1u];
        uint tid = gl_LocalInvocationIndex;
        bucket[tid] = float(tid);
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }

If instead I hardcode the buffer size

    #version 450

    layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;
    layout(constant_id = 1) const uint blockSize = 1;

    shared float bucket[256];

    void main() {
        const uint tid = gl_LocalInvocationIndex;

        bucket[tid] = float(tid);

        memoryBarrierShared();
        barrier();
    }

it generates this SPIR-V

               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %4 "main" %10
               OpExecutionMode %4 LocalSize 1 1 1
               OpSource GLSL 450
               OpName %4 "main"
               OpName %8 "tid"
               OpName %10 "gl_LocalInvocationIndex"
               OpName %16 "bucket"
               OpName %28 "blockSize"
               OpDecorate %10 BuiltIn LocalInvocationIndex
               OpDecorate %25 SpecId 0
               OpDecorate %27 BuiltIn WorkgroupSize
               OpDecorate %28 SpecId 1
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 0
          %7 = OpTypePointer Function %6
          %9 = OpTypePointer Input %6
         %10 = OpVariable %9 Input
         %12 = OpTypeFloat 32
         %13 = OpConstant %6 256
         %14 = OpTypeArray %12 %13
         %15 = OpTypePointer Workgroup %14
         %16 = OpVariable %15 Workgroup
         %20 = OpTypePointer Workgroup %12
         %22 = OpConstant %6 1
         %23 = OpConstant %6 264
         %24 = OpConstant %6 2
         %25 = OpSpecConstant %6 1
         %26 = OpTypeVector %6 3
         %27 = OpSpecConstantComposite %26 %25 %22 %22
         %28 = OpSpecConstant %6 1
          %4 = OpFunction %2 None %3
          %5 = OpLabel
          %8 = OpVariable %7 Function
         %11 = OpLoad %6 %10
               OpStore %8 %11
         %17 = OpLoad %6 %8
         %18 = OpLoad %6 %8
         %19 = OpConvertUToF %12 %18
         %21 = OpAccessChain %20 %16 %17
               OpStore %21 %19
               OpMemoryBarrier %22 %23
               OpControlBarrier %24 %24 %23
               OpReturn
               OpFunctionEnd

which generates the expected correct MSL

    #include <metal_stdlib>
    #include <simd/simd.h>

    using namespace metal;

    constant uint _25_tmp [[function_constant(0)]];
    constant uint _25 = is_function_constant_defined(_25_tmp) ? _25_tmp : 1u;
    constant uint blockSize_tmp [[function_constant(1)]];
    constant uint blockSize = is_function_constant_defined(blockSize_tmp) ? blockSize_tmp : 1u;
    constant uint3 gl_WorkGroupSize = uint3(_25, 1u, 1u);

    kernel void main0(uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]])
    {
        threadgroup float bucket[256];
        uint tid = gl_LocalInvocationIndex;
        bucket[tid] = float(tid);
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }

It seems the addition of a shared buffer that depends on the specialization constant causes it to be optimized out and use the default value.

For brevity, the pipeline is compiled with

    uint32_t lims[] = {256, 256};
    static const vk::SpecializationMapEntry mapEntries[] = {
        {0, 0*sizeof(uint32_t), sizeof(uint32_t)},
        {1, 1*sizeof(uint32_t), sizeof(uint32_t)}
    };
    const vk::SpecializationInfo specializationInfo(2, mapEntries, 2*sizeof(uint32_t), reinterpret_cast<void*>(lims));
    pipeline = device.createComputePipeline({}, {{}, {{}, vk::ShaderStageFlagBits::eCompute, shader, "main", &specializationInfo}, pipelineLayout});

**Comment by HansKristian-ARM** [comment]
Ping @billhollings. I think this is a restriction of MSL. IIRC, array sizes in MSL cannot depend on specialization constants (or function constants in MSL).

**Comment by mbarriault** [comment]
From what I can tell, Metal has threadgroup buffers similar to OpenCL (tagged with `[[threadgroup(*N*)]]` in arguments), their size specified by the [compute command encoder](https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/1443142-setthreadgroupmemorylength?language=objc). Considering this is already how the threads per threadgroup is translated, perhaps there is a way of carrying the shared buffer size information appropriately?

**Comment by mbarriault** [comment]
If I may ask, has anyone thought of this in the time since? From what I understand, tessellation support has to not dissimilar analysis of the SPIR-V.

**Comment by HansKristian-Work** [comment]
No, this issue went nowhere as far as I know. The solution is likely going to be having MoltenVK compiling variants based on spec constants as any solution would be incredibly high in complexity. Not sure how this compares to tessellation.

**Comment by mbarriault** [comment]
I'm trying to figure out whether I have the time to take a dive myself, but the idea I had in mind was due to the fact that the size has to be a constant integer expression. That tightly limits the possible instructions to compute its size, that could be parsed and stored with the vkShaderModule, and on pipeline creation evaluated based on the spec constant values and stored for later use in execution. The main hiccoughs will be in SPIRV-Cross detecting when a workgroup array depends on a spec constant, and ensuring all the potential operations are covered for the computation.

**Comment by HansKristian-Work** [comment]
There's a general problem with spec constant arrays which MSL doesn't support. I'm not sure if that general case is dealt with in MoltenVK atm.

We currently detect for cases where a spec constant is used as an array length, and that spec constant is forced to become a normal constant. The API user can override that constant, which would allow generating variants.

**Comment by mbarriault** [comment]
Is there any reason I'm missing why such a detected array can't be replaced with a `threadgroup` argument instead?

**Comment by HansKristian-Work** [comment]
For a threadgroup array to be replaced with a plain pointer expression in shader, this breaks array copy operations (or at least make them much harder to implement), and the calling code in MoltenVK needs to be able to compute the array size from OpSpecConstantOp, given spec constant inputs, something SPIRV-Cross currently does not support. I really don't want to go into that rabbit hole.

With constant replacement, the MSL compiler will make these constant computations instead.

**Comment by mbarriault** [comment]
"Support with caveats" is still a huge upgrade over "no support at all". I don't see how, for example, a reduction kernel could be done without it unless I hardcode your workgroup size to the lowest common denominator across the hardware I support.

**Comment by HansKristian-Work** [comment]
The workaround everyone has used since the beginning of time is shader variants for each workgroup size, before specialization constants were a thing. Is this is a CL kernel you're trying to port? I think CL had this feature of "unknown size of threadgroup block".

**Comment by devshgraphicsprogramming** [comment]
Slightly related.

Actually seems that SPIR-V Cross cannot produce valid GLSL when I use `local_size_x_id` (I can already handle spec constants properly, its only when `local_size_x_id` is used I have a problem).

This gets produced instead
```glsl
layout(local_size_x = , local_size_y = 1, local_size_z = 1) in;
```

**Comment by HansKristian-Work** [comment]
Works for me:
```
#version 450

#ifndef SPIRV_CROSS_CONSTANT_ID_0
#define SPIRV_CROSS_CONSTANT_ID_0 1u
#endif

layout(local_size_x = SPIRV_CROSS_CONSTANT_ID_0, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer SSBO
{
    vec4 v[];
} _11;

void main()
{
    _11.v[0] = _11.v[1];
}
```
and Vulkan GLSL output:
```
#version 450
layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;


layout(set = 0, binding = 0, std430) buffer SSBO
{
    vec4 v[];
} _11;

void main()
{
    _11.v[0] = _11.v[1];
}
```

Anyways, this particular issue is resolved as good as it can be solved, forgot to close it long ago.
