### ISSUE TITLE
MSL: `function_constant` not available in OS X 10.11

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/SPIRV-Cross#679]
The MSL compiler appears to emit [`function_constant` unconditionally for specialization constants](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.cpp#L1530), but this is only available in macOS 10.12+. Is there already a recommended approach for OS X 10.11, or should we try to replace these specialization constants outside of SPIRV-Cross?

cc https://github.com/gfx-rs/gfx/issues/2342#issuecomment-417068547

**Comment by HansKristian-ARM** [comment]
It should be fairly trivial to add an option to avoid emitting the function_constant declarations in the MSL backend, and just emit plain constants instead.

To make this work, you'll have to use the get_constant() API and poke in spec constants manually, then compile to MSL.

**Comment by grovesNL** [comment]
Sounds good to me. We should be able to tie it to the MSL version for SPIRV-Cross, because both a minimum MSL version and OS version (i.e. to use the `MTLFunctionConstantValues` API) are required.

The minimum MSL version appears to be 1.2 which I can see during shader compilation, at least on macOS (I can't check for iOS but I assume its the same):
> error: \'function_constant\' attribute requires Metal language standard macos-metal1.2 or higher

**Comment by billhollings** [comment]
A test for `msl_options.supports_msl_version(1, 2)` within SPIRV-Cross should suffice.

That aligns with both the macOS and iOS versions that support shader specialization (function constants).

**Comment by HansKristian-ARM** [comment]
Ok, I'll implement this tomorrow.
