### ISSUE TITLE
Exception thrown when parsing SPIR-V with mismatched entry point

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/SPIRV-Cross#68]
As reported in https://github.com/KhronosGroup/glslang/issues/588  (I first thought it was a glslang bug, and maybe it still is, but SPIRV-Cross shouldn't throw an exception).

The following HLSL:
```
float4 PixelShaderFunction(float4 input) : COLOR0   {
    return float4(0.0, 1.0, 0.0, 2.0);
}
```

Generates (through glslangValidator -V -D) the following SPIR-V:
```
                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main"
                              ExecutionMode 4 OriginUpperLeft
                              Name 4  "main"
                              Name 11  "PixelShaderFunction(vf4;"
                              Name 10  "input"
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
               9:             TypeFunction 7(fvec4) 8(ptr)
              13:    6(float) Constant 0
              14:    6(float) Constant 1065353216
              15:    6(float) Constant 1073741824
              16:    7(fvec4) ConstantComposite 13 14 13 15
         4(main):           2 Function None 3
               5:             Label
                              FunctionEnd
11(PixelShaderFunction(vf4;):    7(fvec4) Function None 9
       10(input):      8(ptr) FunctionParameter
              12:             Label
                              ReturnValue 16
                              FunctionEnd
```

Note that I specified "main" as the entry point while it was actually called "PixelShaderFunction", which causes the duplicate blocks. This crashes when fed into SPIRV-Cross, here:

    throw CompilerError("Cannot start a block before ending the current block.");

This seems unfortunate and a better error message would really be nice.

**Comment by HansKristian-ARM** [comment]
This is a glslang bug yes, because the main function is invalid, PixelShaderFunction isn't the entry point here. You cannot FunctionEnd while having an active block OpLabel.

This has come up before, so I've added a more descriptive exception now which should make it more clear what is going on:
```
  what():  Cannot end a function before ending the current block.
Likely cause: If this SPIR-V was created from glslang HLSL, make sure the entry point is valid.
```

**Comment by hrydgard** [comment]
That's great, thank you - should save the next person to encounter this a bit of time. I'll re-open the glslang issue instead.
