### ISSUE TITLE
Invalid struct size for dynamic object array

### ISSUE THREAD

**Issue by Nielsbishere** [KhronosGroup/SPIRV-Cross#683]
The following ssbo causes the type length of a dynamically sized array to be 0:
```glsl
struct PerObject {

	mat4 m;
	mat4 mvp;

	uint diffuse;
	uint specular;
	uint ambient;
	uint padding;

};

layout(std430, binding = 0) buffer Objects {

	PerObject arr[];
	
} obj;
```
PerObject, when queried returns a struct size of 0, while I would expect it to be 144 bytes. This makes querying the expected size for a dynamically sized array even harder. 
```cpp
u32 size = (u32)comp.get_declared_struct_member_size(type, i);

obj.length = size;
obj.arr = mem.array;
```
This results into my program to be invalid, because it depends on the size of the struct to find it.

**Comment by Nielsbishere** [comment]
I fixed it for my own implementation by calculating the struct size myself for when it's a dynamic array, but I think this should be done by SPIRV-Cross internally instead:
```cpp
u32 size = (u32)comp.get_declared_struct_member_size(type, i);

if (size == 0 && (flags & (u32)SBVarFlag::IS_DYNAMIC) != 0) {	//Go through each member and calculate size

	for (u32 j = 0; j < (u32)mem.member_types.size(); ++j) {

		const SPIRType &mmem = comp.get_type(mem.member_types[j]);

		u32 count = mmem.columns;

		for (u32 k : mmem.array)
			count *= k;

		if(mmem.basetype == SPIRType::Struct)
			size += count * (u32) comp.get_declared_struct_member_size(mem, j);
		else
			size += count * Graphics::getFormatSize(getFormat(mmem));

	}

}
```

**Comment by HansKristian-ARM** [comment]
This is working as intended. The SSBO itself has size 0, because it only consists of unsized arrays.
What you need to do is:
- Get memb_type = compiler.get_type(type.member_types[0]). This will give you an array of PerObject, which is 0 sized.
- Get memb_type.self, this will give you the type for PerObject itself. Then do get_declared_struct_size on that.

**Comment by HansKristian-ARM** [comment]
The .self member will point to the type itself, removing modifiers like pointer types, arrays, etc. It's more of an implementation detail, but I'll add a special helper function to work better with buffers which contain runtime length arrays.

**Comment by HansKristian-ARM** [comment]
I've added a new helper function which should help you.

**Comment by Nielsbishere** [comment]
Thanks
