### ISSUE TITLE
GLSL code generation throws exception in non-Vulkan semantics mode when sampling a texture (generated from HLSL)

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/SPIRV-Cross#69]
The to-GLSL compiler crashes when options.vulkan_semantics = false:

			throw CompilerError("Cannot find mapping for combined sampler, was build_combined_image_samplers() used "
			                    "before compile() was called?");

Works fine when options.vulkan_semantics = true, but obviously it'll then generate descriptor set annotations that won't work in regular GLSL.

Here's the original HLSL:

	struct VertexData {
		float4 color : COLOR0;
		float2 uv : TEXCOORD0;
	};

	SamplerState samp : register(s0);
	Texture2D<float4> tex : register(t0);

	float4 pshader(VertexData vin) : SV_Target {
		return tex.Sample(samp, vin.uv) * vin.color;
	}

Resulting in the following SPIR-V:

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "pshader" 9 22 26
                              ExecutionMode 4 OriginUpperLeft
                              Name 4  "pshader"
                              Name 9  "@entryPointOutput"
                              Name 12  "tex"
                              Name 16  "samp"
                              Name 22  "uv"
                              Name 26  "color"
                              Decorate 9(@entryPointOutput) Location 0
                              Decorate 12(tex) DescriptorSet 0
                              Decorate 12(tex) Binding 0
                              Decorate 16(samp) DescriptorSet 0
                              Decorate 16(samp) Binding 0
                              Decorate 22(uv) Location 1
                              Decorate 26(color) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
    9(@entryPointOutput):      8(ptr) Variable Output
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypePointer UniformConstant 10
         12(tex):     11(ptr) Variable UniformConstant
              14:             TypeSampler
              15:             TypePointer UniformConstant 14
        16(samp):     15(ptr) Variable UniformConstant
              18:             TypeSampledImage 10
              20:             TypeVector 6(float) 2
              21:             TypePointer Input 20(fvec2)
          22(uv):     21(ptr) Variable Input
              25:             TypePointer Input 7(fvec4)
       26(color):     25(ptr) Variable Input
      4(pshader):           2 Function None 3
               5:             Label
              13:          10 Load 12(tex)
              17:          14 Load 16(samp)
              19:          18 SampledImage 13 17
              23:   20(fvec2) Load 22(uv)
              24:    7(fvec4) ImageSampleImplicitLod 19 23
              27:    7(fvec4) Load 26(color)
              28:    7(fvec4) FMul 24 27
                              Store 9(@entryPointOutput) 28
                              Return
                              FunctionEnd

And the crash happened when trying to generate GLSL from this using spirv-cross (as a library), of course.

**Comment by hrydgard** [comment]
Please ignore, the obvious solution was to manually call build_combined_image_samplers() . 

From some code searching I got the impression that that would get automatically called when !vulkan_semantics, but that was in the main.cpp which I was not using.

**Comment by HansKristian-ARM** [comment]
Added a section to README about consuming SPIR-V from HLSL:
https://github.com/KhronosGroup/SPIRV-Cross/commit/f7ce25b6c269351a33e01d535170e6f573a96b4d

**Comment by hrydgard** [comment]
@HansKristian-ARM Thanks!

One note on the last paragraph - Vulkan supports both separated and combined images/samplers, and the latter actually has a slight performance advantage on some hardware, AMD for example recommends it. So in some situations it might make sense to use build_combined_image_samplers when emitting Vulkan GLSL as well.

Come to think of it, the option to combine image samplers really belongs in glslang rather than in spirv-cross, as if you were to use HLSL-generated SPIR-V directly in Vulkan but still want to combine images/samplers, there's no easy way to do that right now.

**Comment by HansKristian-ARM** [comment]
The problem of automatically building combined samplers is reflection and interface, if you have a sampler at binding N and image at binding M, which descriptor set/binding should glslang automatically translate that to, and how would you figure out that information?

I suppose it could be simplified if all combined image/samplers are unique and they use the same binding. Almost all HLSL shaders seem to do that anyways.

**Comment by hrydgard** [comment]
Yes, exactly. I'm not saying it should be fully automatic, but it could very well be an option in glslang to auto-merge them or merge according to some callback, so you can get whatever behaviour you desire.

**Comment by HansKristian-ARM** [comment]
If this can be considered an optimization for some GPUs, it might make more sense to have this as an optimization in spirv-tools.

**Comment by hrydgard** [comment]
Yeah, maybe so. I posted an issue for discussion in the glslang project: https://github.com/KhronosGroup/glslang/issues/591

Added your idea of putting it in spir-v tools as a suggestion.
