### ISSUE TITLE
MSL: HLSL CalculateLevelOfDetail does not translate properly

### ISSUE THREAD

**Issue by PixelZealot** [KhronosGroup/SPIRV-Cross#694]
**Versions:**
spirv-cross - top of tree
glslangValidator - Latest LunarG SDK

Given the code below in test.frag.hlsl:

```
layout(binding = 0) uniform sampler2D smp;
layout(binding = 1) uniform Texture2D<float4> tex;

float4 main( float2 uv : TEXCOORD0 ) : SV_Target
{
	float mip = tex.CalculateLevelOfDetail( smp, uv );
	return float4(mip.xxx, 1.0);
}
```
Compiled with:
```
glslangValidator -e main -V450 --target-env vulkan1.1 -o "test.spv" -Os test.frag.hlsl
```
Followed by: 
```
spirv-cross test.spv --msl
```
Results in:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 _entryPointOutput [[color(0)]];
};

struct main0_in
{
    float2 uv [[user(locn0)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex [[texture(1)]], sampler smp [[sampler(0)]])
{
    main0_out out = {};
    out._entryPointOutput = float4(textureQueryLod(tex, in.uv).xxx, 1.0);
    return out;
}
```
Where **textureQueryLod** is an invalid MSL instruction.

**Comment by HansKristian-ARM** [comment]
Definitely a bug, but I cannot see to find the MSL equivalent to this instruction. Do you know what the correct MSL would look like?

**Comment by HansKristian-ARM** [comment]
Ok, it seems like MSL does not support this directly.
Do you rely on this feature (which in case we need some ugly workaround), or would just making sure we error out on this SPIR-V opcode be enough?

**Comment by PixelZealot** [comment]
Error out would be fine.

- Piotr
