### ISSUE TITLE
MSL: Accessing shader input blocks uses the incorrect variable name

### ISSUE THREAD

**Issue by stenzek** [KhronosGroup/SPIRV-Cross#695]
Shaders which access the shader input blocks appear to use the name of the block's variable in the main function, instead of the name of the parameter which references the block. Tested on master @ c029b0a. See the GLSL below:

```
#version 450 core

layout(location = 0) out vec4 col;
layout(location = 0) in VertexData {
  vec4 foo;
};

vec4 bar() { return foo; }

void main() { col = bar(); }
```

Current output:

```
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 col [[color(0)]];
};

struct main0_in
{
    float4 VertexData_foo [[user(locn0)]];
};

float4 bar(thread VertexData& v_13)
{
    return in.VertexData_foo;
}

fragment main0_out main0(main0_in in [[stage_in]])
{
    main0_out out = {};
    out.col = bar(v_13);
    return out;
}
```

I'm assuming "in" in the bar function should be v_13.

**Comment by HansKristian-ARM** [comment]
Ok, the problem is dealing with passing down global-aliased and flattened types like I/O blocks and structs.
I think we'll need to refactor how this works, adding support for this directly will get very messy.

**Comment by billhollings** [comment]
Hmmm...this should be working already.

**Comment by HansKristian-ARM** [comment]
This kind of code should work now in MSL.

**Comment by stenzek** [comment]
Fantastic! Thank you. Can confirm the issue is fixed.
