### ISSUE TITLE
Python3 detection not working on Windows

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/SPIRV-Cross#70]
I get a "Could not find python3" warning when I run cmake for this project on Windows, despite having Python 3.5.2 installed. It seems to be looking for a python3.exe, and I don't see one in the installation directory (just python.exe).

It's not a fatal error, but is there any way to eliminate the spurious warning? Some way to disable testing before the Python3 check, perhaps?

**Comment by HansKristian-ARM** [comment]
Probably makes most sense to add a cmake option to disable/enable testing.

**Comment by cdwfs** [comment]
Should I put together a pull request, or would you like to handle it among yourselves? My cmake-fu is barely above white-belt, but it would be good practice :)

**Comment by HansKristian-ARM** [comment]
I'd prefer a PR. :)

**Comment by cdwfs** [comment]
This PR doesn't add an option to disable tests, but it should at least fix the existing Python test.
