### ISSUE TITLE
Control flow: switch-cases go to loop merge

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#702]
https://github.com/KhronosGroup/SPIRV-Headers/files/2179180/switchcase_goto_loop_merge.spv.txt

SPIRV-Cross does not translate it to GLSL correctly.
The trivial loops go out of loop at its end constantly. See comments at https://github.com/KhronosGroup/SPIRV-Headers/issues/75 .

**Comment by HansKristian-ARM** [comment]
Ouch, is this actually legal ...
