### ISSUE TITLE
Support new "raytracing shader types" in HLSL (DXR) and GLSL output backends from SPIR-V NV_raytracing shaders..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#707]
Hi,
now that NV ships VK_NV_raytracing and glslang already supports it.. (also yesterday DXR DXC bits have been open sourced) seems sensible to ask&track eventual support for translating DXR HLSL to GLSL with NV_raytracing extensions in any direction..

for GLSL: 
I'm basically asking for reverse operation of what new glslang NV_raytracing ext. support does..
see commit:
https://github.com/KhronosGroup/glslang/commit/b50c02ef53973e3e09565ed7066d2b39edc36b17

for HLSL:

translating SPIR-V VK_NV_raytracing code back to HLSL DXR..
reverse operation of what eventual DXC DXR -> VK_raytracing SPIR-V will do:
https://github.com/Microsoft/DirectXShaderCompiler/issues/1554

**Comment by oscarbg** [comment]
Seems Nvidia has added support for it already as playing with a VK RT sample on Nsight Graphics 2018.5 shows:
![screenshot_2018-10-09 twitter](https://user-images.githubusercontent.com/669305/46647567-f458f580-cb90-11e8-9d33-c6f453807ed9.jpg)
hope they share the changes eventually..

**Comment by s0501007** [comment]
Looks like still there is no proper support for raytracing shaders.
Trying to create cross compiler via "CreateCrossCompiler()" and get exception in 
`void Parser::parse(const Instruction &instruction)`
on line
`SPIRV_CROSS_THROW("Currently no block to insert opcode.");`
**op** value is **5341**.
The shader is simple ray generation shader.

**Comment by HansKristian-Work** [comment]
There is not, and vendor-specific extensions like these have the lowest priority for me.

**Comment by HansKristian-Work** [comment]
There is GLSL output support now. Closing this. A separate HLSL (DXR) issue should be created if desired.
