### ISSUE TITLE
Glsl backend doesn't support passing buffer blocks into functions

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#711]
Full disclaimer, I'm trying to do something that as near as I can tell is supported in spir-v but I know glsl doesn't support.

I'm toying around with passing ssbo data to a function in spir-v. In the attached file I tried two different methods of passing the data, one by passing the full struct and the other by passing the un-sized array. Both of these fail when being translated to glsl because as near as I know glsl doesn't have a mechanism to take care of this. In particular, I know glsl doesn't support passing unsized arrays into functions. Unfortunately, an ssbo doesn't have a known size at compile time which means there's no glsl mechanism to pass them into functions.

Is there any way to support this kind of behavior apart from writing a tool that finds all functions that take an ssbo and duplicates it for each global access of an ssbo used?

[Particle2.compute.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2420033/Particle2.compute.txt)

**Comment by HansKristian-ARM** [comment]
This cannot be supported in GLSL, no. I would need to error out on code like this. What you should do to make that work is run an inliner on it with spirv-opt. I cannot support this in SPIRV-Cross I think.

**Comment by jodavis42** [comment]
I see, I didn't think about running the optimizer to force inline everything. A quick test shows that working as I expect. Thanks for the quick reply!
