### ISSUE TITLE
Glsl backend doesn't handle certain builtin types being int vs. uint

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#716]
According to the Vulkan spec:

The  variable  decorated  with  GlobalInvocationId must  be  declared  as  a  three-component  vector of 32-bit integers.

Which implies to me the variable should be of type signed int not unsigned int. However making this an signed int and then copying generates invalid glsl code because of an implicit cast from uint3 to int3.

I'm unsure if this is incorrect in the Vulkan spec or what.

[Compute.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2425622/Compute.txt)

**Comment by HansKristian-ARM** [comment]
32-bit integer can mean either signed or unsigned.

**Comment by HansKristian-ARM** [comment]
The SPIR-V you posted works just fine.
```
void CopyInputs_Main(inout ParticleCompute self)
{
    self.GlobalInvocationId = ivec3(gl_GlobalInvocationID);
}
```
GlobalInvocationID is automatically bitcasted to its declared type int3. I don't see the bug.

**Comment by jodavis42** [comment]
Whoops, I made the mistake of not updating first to see if this had been fixed since I last pulled. Seems I was on a month or two old version. Works great now, thanks!
