### ISSUE TITLE
UBO names not preserved when compiling GLSL -> SPIR-V -> HLSL

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/SPIRV-Cross#728]
My shader pipeline is set up like this: I compile GLSL input to SPIR-V using `glslang`, then pass the SPIR-V to either a DX12 or Vulkan render backend (depending on platform). The DX12 backend uses `SPIRV-Cross` to transpile the SPIR-V to HLSL, then gives that to the DirectX shader compiler. I perform a good bit of reflection along the way to generate descriptor tables for DX12 and map from name of shader input to location of shader input, so that my materials can say "bind texture `NovaColorAtlas` to shader input `colortex`". Names of shader inputs are very important to me... and `SPIRV-Cross` is removing them.

Sample GLSL shader: https://pastebin.com/BSftA5K0
SPIR-V generated by `glslang`: https://pastebin.com/i4mbzbWu
HLSL generated by `SPIRV-Cross`: https://pastebin.com/u1ze9NEB

As you can see, the UBOs `per_model_uniforms` and `per_frame_uniforms` have their names preserved in the SPIR-V code, but anything at all related to names is missing from the HLSL code.

My code to compile from GLSL to SPIR-V is here: https://github.com/NovaMods/nova-renderer/blob/rewrite/native/src/loading/shaderpack/shaderpack_loading.cpp#L251
Code to compile SPIR-V to HLSL: https://github.com/NovaMods/nova-renderer/blob/rewrite/native/src/render_engine/dx12/dx12_render_engine.cpp#L782

What am I doing wrong? How can I ensure that I have UBO names available in the generated HLSL?

**Comment by HansKristian-ARM** [comment]
You're not doing anything wrong. The HLSL backend was picking the variable name instead of the block name. I made a PR to match the GLSL implementation which tries to use block name when possible, this should fix the issue for you. https://github.com/KhronosGroup/SPIRV-Cross/pull/729

**Comment by DethRaid** [comment]
Thanks for the PR! I hope for its quick acceptance

**Comment by DethRaid** [comment]
Finally got a chance to pull the latest SPIRV-Cross.. and it works perfectly! Thank you so much!
