### ISSUE TITLE
MSL backend not emitting vertex function with return value, causing link error in graphics pipeline creation

### ISSUE THREAD

**Issue by 741g** [KhronosGroup/SPIRV-Cross#735]
MoltenVK version: 1.0.24

Original GLSL:

    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    
    out gl_PerVertex {
        vec4 gl_Position;
    };
    
    layout (std140, binding = 0) uniform Transform {
        mat4 mvp;
    } transform;
    
    layout (location = 0) in vec2 pos;
    layout (location = 1) in vec2 color;
    
    layout (location = 0) out vec2 color_varying;
    
    void main() {
        gl_Position = transform.mvp * vec4(pos, 0.0, 1.0);
        color_varying = color;
    }
    
    // fragment shader
    
    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    
    layout (location = 0) in vec2 color_varying;
    layout (location = 0) out vec4 fragcolor;
    void main() {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }

SPIRV (using glslangValidator from macos vulkan sdk 1.1.82)

    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 39
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Vertex %4 "main" %13 %25 %36 %37
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %11 "gl_PerVertex"
                   OpMemberName %11 0 "gl_Position"
                   OpMemberName %11 1 "gl_PointSize"
                   OpMemberName %11 2 "gl_ClipDistance"
                   OpMemberName %11 3 "gl_CullDistance"
                   OpName %13 ""
                   OpName %17 "Transform"
                   OpMemberName %17 0 "mvp"
                   OpName %19 "transform"
                   OpName %25 "pos"
                   OpName %36 "color_varying"
                   OpName %37 "color"
                   OpMemberDecorate %11 0 BuiltIn Position
                   OpMemberDecorate %11 1 BuiltIn PointSize
                   OpMemberDecorate %11 2 BuiltIn ClipDistance
                   OpMemberDecorate %11 3 BuiltIn CullDistance
                   OpDecorate %11 Block
                   OpMemberDecorate %17 0 ColMajor
                   OpMemberDecorate %17 0 Offset 0
                   OpMemberDecorate %17 0 MatrixStride 16
                   OpDecorate %17 Block
                   OpDecorate %19 DescriptorSet 0
                   OpDecorate %19 Binding 0
                   OpDecorate %25 Location 0
                   OpDecorate %36 Location 0
                   OpDecorate %37 Location 1
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypeInt 32 0
              %9 = OpConstant %8 1
             %10 = OpTypeArray %6 %9
             %11 = OpTypeStruct %7 %6 %10 %10
             %12 = OpTypePointer Output %11
             %13 = OpVariable %12 Output
             %14 = OpTypeInt 32 1
             %15 = OpConstant %14 0
             %16 = OpTypeMatrix %7 4
             %17 = OpTypeStruct %16
             %18 = OpTypePointer Uniform %17
             %19 = OpVariable %18 Uniform
             %20 = OpTypePointer Uniform %16
             %23 = OpTypeVector %6 2
             %24 = OpTypePointer Input %23
             %25 = OpVariable %24 Input
             %27 = OpConstant %6 0
             %28 = OpConstant %6 1
             %33 = OpTypePointer Output %7
             %35 = OpTypePointer Output %23
             %36 = OpVariable %35 Output
             %37 = OpVariable %24 Input
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %21 = OpAccessChain %20 %19 %15
             %22 = OpLoad %16 %21
             %26 = OpLoad %23 %25
             %29 = OpCompositeExtract %6 %26 0
             %30 = OpCompositeExtract %6 %26 1
             %31 = OpCompositeConstruct %7 %29 %30 %27 %28
             %32 = OpMatrixTimesVector %7 %22 %31
             %34 = OpAccessChain %33 %13 %15
                   OpStore %34 %32
             %38 = OpLoad %23 %37
                   OpStore %36 %38
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct Transform
    {
        float4x4 mvp;
    };
    
    struct main0_out
    {
        float2 color_varying [[user(locn0)]];
        float4 gl_Position [[position]];
    };
    
    struct main0_in
    {
        float2 pos [[attribute(0)]];
        float2 color [[attribute(1)]];
    };
    
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    // is this supposed to be returning |out| here?/////////////////////////////////
    vertex void main0(main0_in in [[stage_in]], constant Transform& transform [[buffer(0)]])
    {
        main0_out out = {};
        out.gl_Position = transform.mvp * float4(in.pos, 0.0, 1.0);
        out.color_varying = in.color;
        out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(binding = 0, std140) uniform Transform
    {
        mat4 mvp;
    } transform;
    
    layout(location = 0) in vec2 pos;
    layout(location = 0) out vec2 color_varying;
    layout(location = 1) in vec2 color;
    
    void main()
    {
        gl_Position = transform.mvp * vec4(pos, 0.0, 1.0);
        color_varying = color;
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.180 ms, avg: 0.206 ms, min: 0.180 ms, max: 0.231 ms, count: 2
    [mvk-debug] Performance to retrieve shader library from the cache curr: 28.808 ms, avg: 28.808 ms, min: 28.808 ms, max: 28.808 ms, count: 1
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.005 ms, avg: 0.005 ms, min: 0.005 ms, max: 0.005 ms, count: 1
    [mvk-debug] Performance to convert SPIR-V to MSL source code curr: 0.877 ms, avg: 2.636 ms, min: 0.877 ms, max: 4.394 ms, count: 2
    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 24
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Fragment %4 "main" %9 %12
                   OpExecutionMode %4 OriginUpperLeft
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %9 "fragcolor"
                   OpName %12 "color_varying"
                   OpDecorate %9 Location 0
                   OpDecorate %12 Location 0
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypePointer Output %7
              %9 = OpVariable %8 Output
             %10 = OpTypeVector %6 2
             %11 = OpTypePointer Input %10
             %12 = OpVariable %11 Input
             %13 = OpTypeInt 32 0
             %14 = OpConstant %13 0
             %15 = OpTypePointer Input %6
             %18 = OpConstant %6 0.200000003
             %19 = OpConstant %13 1
             %22 = OpConstant %6 1
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %16 = OpAccessChain %15 %12 %14
             %17 = OpLoad %6 %16
             %20 = OpAccessChain %15 %12 %19
             %21 = OpLoad %6 %20
             %23 = OpCompositeConstruct %7 %17 %18 %21 %22
                   OpStore %9 %23
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct main0_out
    {
        float4 fragcolor [[color(0)]];
    };
    
    struct main0_in
    {
        float2 color_varying [[user(locn0)]];
    };
    
    fragment main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.fragcolor = float4(in.color_varying.x, 0.2, in.color_varying.y, 1.0);
        return out;
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(location = 0) out vec4 fragcolor;
    layout(location = 0) in vec2 color_varying;
    
    void main()
    {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.126 ms, avg: 0.179 ms, min: 0.126 ms, max: 0.231 ms, count: 3
    [mvk-debug] Performance to retrieve shader library from the cache curr: 22.515 ms, avg: 25.662 ms, min: 22.515 ms, max: 28.808 ms, count: 2
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.001 ms, avg: 0.003 ms, min: 0.001 ms, max: 0.005 ms, count: 2
    [***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (error code 1):
    Link failed: fragment input user(locn0) was not found in vertex shader outputs.

**Comment by 741g** [comment]
Found when using MoltenVK 1.0.24:

https://github.com/KhronosGroup/MoltenVK/issues/317

**Comment by HansKristian-ARM** [comment]
I cannot reproduce this, I get:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Transform
{
    float4x4 mvp;
};

struct main0_out
{
    float2 color_varying [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float2 pos [[attribute(0)]];
    float2 color [[attribute(1)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant Transform& transform [[buffer(0)]])
{
    main0_out out = {};
    out.gl_Position = transform.mvp * float4(in.pos, 0.0, 1.0);
    out.color_varying = in.color;
    return out; // Returns fine
}
```
Did you use rasterizerDiscard by any chance? @billhollings what are the conditions for disabling vertex main return?

**Comment by 741g** [comment]
That's right, I had rasterizerDiscard set to VK_TRUE at some point. Setting it to VK_FALSE seemed to have fixed the issue. Thanks!

Is this the expected correct behavior, then? If we have rasterizer discard enabled, shouldn't we still be able to use vertex shader outputs? Should it be a link error?

**Comment by KenThomases** [comment]
In Metal (don't know about Vulkan), when rasterizing is disabled the vertex shader can write to buffers or textures, but it can't return a value. The shader function's return type should be `void`.

**Comment by HansKristian-ARM** [comment]
It might be a case that you shouldn't include a fragment stage when you enable rasterizerDiscard? Maybe MoltenVK needs to remove that stage for you?

**Comment by billhollings** [comment]
Agreed that this is not a SPIRV-Cross issue.

As @KenThomases indicates, Metal requires that when rasterization is disabled, the vertex function must return `void`...hence the flag in `CompilerMSL` options in SPIRV-Cross. There is no mention in Metal docs about having to remove the fragment shader...but it may be necessary.

**Comment by alecazam** [comment]
This is a spirv-cross issue.   There is a problem that new spriv-cross always generates a gl_position (uninitialized) when we need a "vertex void" call for writing to SSBO.   The older version did the correct transpile to "vertex void".   Right now, we always get "vertex vsmain_out".     We have a VS with no FS, and set Metal's RasterizationEnabled to false.

This is the error returned by Metal.

Assert error: Renderer Crash, Failed to create render pipeline for shader VisibilityQuery: RasterizationEnabled is false but the vertex shader's return type is not void

I'd reported this here, but then found this thread.   Is there something we can set to get this behavior back like in the old spriv-cross.
https://github.com/KhronosGroup/SPIRV-Tools/issues/5525
