### ISSUE TITLE
[Android] Build error

### ISSUE THREAD

**Issue by Nielsbishere** [KhronosGroup/SPIRV-Cross#739]
When building using C++17 through Android arm64-v8a (clang; MinGW64), it generates the following build error:
```
D:\programming\repos\ocore\deps\SPIRV-Cross/spirv_common.hpp:240:14: error: no member named 'to_string' in namespace
      'std'
        return std::to_string(std::forward<T>(t));
```
This issue doesn't just occur in spirv_common, but other source files as well.

**Comment by HansKristian-ARM** [comment]
Make sure to use ANDROID_STL c++_static/shared. gnustl is broken, and doesn't support to_string.

**Comment by Nielsbishere** [comment]
Using"-DANDROID_STL=c++_shared" in my cmake android command fixed the compile errors. However, now it can't find std::vector's deconstructor; probably a linking error. Thank you anyways :+1:

**Comment by HansKristian-ARM** [comment]
I build SPIRV-Cross for Android regularly without issue, so probably an issue on your end, closing.
