### ISSUE TITLE
CompilerGLSL should flip texture coordinate Y

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#74]
Metal compiler has the flip_frag_y, probably should apply the same to GLSL one, otherwise vulkan shader translated to GLSL appears with UV flipped.

**Comment by HansKristian-ARM** [comment]
I am not the right one to answer for why Metal has the flip_frag_y flag, but flipping UV does not make sense for GL. The only difference between GL and Vulkan is the origin for the final backbuffer.

**Comment by amerkoleci** [comment]
The strange stuff is when I render in 3D space the texture UV's are flipped while orthographic sprite rendering works well without UV flipping.

**Comment by HansKristian-ARM** [comment]
Vulkan has different clip-space conventions than GL, which could be what you're seeing, but still, shaders are not the best place to apply any flipping, if any place, it should be gl_Position in vertex, not UVs.

**Comment by amerkoleci** [comment]
You mean -1..1 space for gl and 0..1 for Vulkan?

**Comment by HansKristian-ARM** [comment]
Y = -1 is logically top in Vulkan, and bottom for GL. However, this only matters when rendering to the swapchain, not anywhere else. The clip -> window transform is essentially the same in Vulkan and GL (sans the depth range, but that's not relevant here).

**Comment by amerkoleci** [comment]
Issue was from my side, I was flipping for some reasons the 3D cube UV's, closing now.
Thank you
