### ISSUE TITLE
Various widening arithmetic operations are not implemented

### ISSUE THREAD

**Issue by dignifiedquire** [KhronosGroup/SPIRV-Cross#740]
I have a small shader, which passes `spirv-val`, but fails to run through `spirv-cross` (on all backends).

```
> spirv-cross add.spv
SPIRV-Cross threw an exception: Cannot resolve expression type.
```
## Environment

- macOS 10.14
- spirv-cross compiled from `13633c05002168034e673bba769ffcdb779e19a8`
- spirv-tools compiled from `9e6f5134d1aa2ff2f09d1880c1e7a0324f0cec54`

[add.spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/2542285/add.spv.zip)

**Comment by HansKristian-ARM** [comment]
This is caused by IAddCarry. These opcodes are not implemented yet:
- IAddCarry
- ISubBorrow
- UMulExtended
- SMulExtended

Must have forgotten about them.

**Comment by dignifiedquire** [comment]
> How urgent is this? I'm on holiday next week.

Not super urgent. Knowing this is the issue already helps. (Also thank you for the super quick response)

**Comment by HansKristian-ARM** [comment]
Ok, I'll get to it the week after next one then, anyone else is free to make a PR meanwhile.

**Comment by DragonJoker** [comment]
How would it be best implemented, since in SPIR-V these operators return a struct ?
