### ISSUE TITLE
Support for SV_DepthGreaterEqual on the HLSL backend

### ISSUE THREAD

**Issue by siriux** [KhronosGroup/SPIRV-Cross#747]
The equivalent feature is already available on the GLSL backend ("depth_greater") and MSL backend ("depth(greater)") using the internal flag ExecutionModeDepthGreater, but it's not implemented for the HLSL backend.

Thanks

**Comment by HansKristian-ARM** [comment]
Should be trivial to add.

**Comment by HansKristian-ARM** [comment]
Turns out the GLSL implementation was broken :P there were no tests for this feature.
