### ISSUE TITLE
How to handle type_ prefix added by DXC when compiling HLSL

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Cross#753]
Hello! We are using SPIRV-Cross to get reflection information from SPIRV modules and automate shader resource binding. This works perfectly well for byte code produced by glslang. However for SPIRV modules generated by DXC, all constant buffer names reported in `spirv_cross::ShaderResources` have `type_` prefix (https://github.com/Microsoft/DirectXShaderCompiler/issues/1661). I am still not sure why Microsoft had to add this prefix and why glslang works fine without it, but can you suggest some generic way to handle both cases?

**Comment by HansKristian-ARM** [comment]
Could you paste a sample SPIR-V and what kind of output you would like from that module? If DXC emits both the block name (type) and instance name, you might be able to use `compiler.get_name(result.id)` to get the instance name.

**Comment by DiligentGraphics** [comment]
I am experimenting with the following shader:
```hlsl
cbuffer Constants
{
    float4x4 g_WorldViewProj;
};

struct PSInput 
{ 
    float4 Pos : SV_POSITION; 
    float4 Color : COLOR0; 
};

PSInput main(float3 pos : ATTRIB0, 
             float4 color : ATTRIB1) 
{
    PSInput ps; 
    ps.Pos = mul( float4(pos,1.0), g_WorldViewProj);
    ps.Color = color;
    return ps;
}
```

If I then use the following code to get uniform buffer name from the SPIRV. The result is that for glslang I get `"Constants"` as I would expect. However, for DXC I get `"type_Constant"`. `Compiler.get_name(resources.uniform_buffers[0].id);` returns empty string.
What I am trying to achieve is to have generic way to get `"Constants"` for both glslang and DXC.

```cpp
spirv_cross::Compiler Compiler(spirv_binary);
spirv_cross::ShaderResources resources = Compiler.get_shader_resources();
resources.uniform_buffers[0].name;// == "Constants" for glslang
                                  // == "type_Constant" for DXC
Compiler.get_name(resources.uniform_buffers[0].id); // empty
```

Please go to https://github.com/Microsoft/DirectXShaderCompiler/issues/1661 to see the byte codes generated by glslang and DXC/

**Comment by DiligentGraphics** [comment]
`compiler.get_name(result.id)` seems to be giving me what I was expecting, thanks! There is one thing I would still like to understand.

I am experimenting with HLSL shader that uses the following constant buffer:
```hlsl
cbuffer Constants
{
    float4x4 g_WorldViewProj;
};
```
Please go to https://github.com/Microsoft/DirectXShaderCompiler/issues/1661#issuecomment-435553916 to see the full shader code as well as SPIRV generated by glslang and DXC

When I get reflection information from SPIRV modules produced by glslang and DXC, I get the following:

|                                           | glslang        |   dxc        |
|------------------------------|--------------|------------ |
|result.name                           | "Constants" | "type_Constants"  |
|compiler.get_name(result.id) |  ""           |    "Constants"  |

So I use the following function to get the generic name:

```cpp
const std::string& GetUBName(spirv_cross::Compiler& Compiler, const spirv_cross::Resource& UB, const spirv_cross::ParsedIR::Source& IRSource)
{
    const auto& instance_name = Compiler.get_name(UB.id);
    return (IRSource.hlsl && !instance_name.empty()) ? instance_name : UB.name;
}
```

What I want to understand is why DXC produces opcodes for "Constants". Since glslang lives fine without it, this opcode seems to be redundant?

**Comment by HansKristian-ARM** [comment]
So the reason for the two different names here is instance name vs block name. GLslang appears to emit the names as if you did:

```
uniform Constants { // resource.name
    mat4 MVP;
}; // no instance name
```
in GLSL syntax, while DXC emits it like:

```
uniform type_Constants { // resource.name
    mat4 MVP;
} Constants; // get_name(resource.id)
```
in GLSL syntax.

I have no control over which naming convention DXC or glslang chooses to emit, so you will need some kind of heuristic here. I think the snippet you made is something you would have to do.

Reflection based on names can be a bit brittle because of issues like these. OpName is a debug instruction which doesn't have any real meaning to a driver, so you will have to rely on your toolchain emitting the information you need so you can reflect it later.

Not sure if this answers the question.

**Comment by DiligentGraphics** [comment]
@HansKristian-ARM This exactly answers my question, thanks!
