### ISSUE TITLE
Need to handle OpDecorationGroup, OpGroupDecorate and OpGroupMemberDecorate

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#758]
Here is an example from Vulkan CTS. Please help handle them, thanks!
[op_decoration_group.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2583196/op_decoration_group.spv.txt)

**Comment by HansKristian-ARM** [comment]
Right, this is known to be missing, just never got around to adding it.
