### ISSUE TITLE
Need to handle pointer of pointer

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#770]
Here is a shader from vulkan CTS variable pointer test group. Please have a look!
[pointer_of_pointer.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/2609925/pointer_of_pointer.zip)
[pointer_of_pointer.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2609975/pointer_of_pointer.spv.txt)

**Comment by lifpan** [comment]
[https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_variable_pointers.html](url)

**Comment by HansKristian-ARM** [comment]
I don't believe this is implementable. GLSL does not support pointers.

**Comment by lifpan** [comment]
Could we let it parse successfully for this case? It will throw an exception for pointer-to-pointer.
```
		if (ptrbase.pointer)
			SPIRV_CROSS_THROW("Cannot make pointer-to-pointer type.");
```

**Comment by HansKristian-ARM** [comment]
We could defer the failure to compilation, I agree. There is no reason why we can't do reflection at least.
Would that be enough?

**Comment by cdavis5e** [comment]
> I don't believe this is implementable. GLSL does not support pointers. AFAIK, KHR_variable_pointers is for CL-on-Vulkan workloads, and not shaders per se.

[Actually, it may well be possible.](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_buffer_load.txt)

> It might be implementable on Metal, but that's about it with the current state of shading languages.

I'm already working on this.

**Comment by lifpan** [comment]
> We could defer the failure to compilation, I agree. There is no reason why we can't do reflection at least.
Would that be enough to resolve this issue?
Yes for me.

**Comment by billhollings** [comment]
@cdavis5e 

> I'm already working on this.

What is it that you are working on in this area?

**Comment by cdavis5e** [comment]
Supporting this extension.

**Comment by HansKristian-ARM** [comment]
Ok, I will defer the failure of KHR_variable_pointers to compile time and close this once it hits master. I assume @cdavis5e will make a PR for Metal support later as it supports pointers.

**Comment by HansKristian-ARM** [comment]
Created #773 to track MSL.

**Comment by oscarbg** [comment]
@HansKristian-Work @cdavis5e @billhollings interested to hear thoughts on new VK_EXT_buffer_device_address ext. which seems to bring pointer support in shaders ( similar to shader buffer load NV GL ext.)  and possible MSL support in spirv-cross for exposing that ext. in MoltenVK.. as I recall reading that Metal kinda supports pointers in shading language..
Thanks in advance!
