### ISSUE TITLE
Remove redundant nested parenthesis eg:  if ((x == y))

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#78]
Metal presents a warning when redundant parens are encountered in some statements.

For example:

```
<program source>:97:16: warning: equality comparison with extraneous parentheses
    if ((_4463 == 0.0))
         ~~~~~~^~~~~~
<program source>:97:16: note: remove extraneous parentheses around the comparison to silence this warning
    if ((_4463 == 0.0))
        ~      ^     ~
```

It sounds like a fix should be fairly straightforward, and would be useful for all language versions...but I don't have a strong enough understanding of statement assembly to make a solid multi-language fix for this.

Can someone with better knowledge of statement assembly (maybe H-K) take a stab at this please?

Thanks...

...Bill

**Comment by HansKristian-ARM** [comment]
Instead of proactively adding parens around expressions, it might be cleaner to add them as needed, e.g. a binary op would add parens around its two child expressions. However, changing this needs a fair bit of testing, there are lots of cases where we need to remember to add parens. Seems worthwhile though, as we can remove most parentheses in generated output.

**Comment by zeux** [comment]
A simpler workaround would be to add this to all shaders:

    #pragma clang diagnostic ignored "-Wparentheses-equality"

**Comment by billhollings** [comment]
I've tested @zeux's suggestion...and it works. Thanks for the idea!

However...in general, I am not a fan of warning suppression, because it hides a deficiency in our conversion code, and it also hides when that deficiency has been fixed...and hence when the workaround should be removed.

I would prefer to leave the warnings visible until we fix them. If it appears that making a proper fix is too challenging or risky...and hence will never happen...I can install the workaround.

**Comment by HansKristian-ARM** [comment]
I'll give it a try.

**Comment by HansKristian-ARM** [comment]
Made a PR, seems reasonable, @billhollings please test it to see if your MSL tests work as expected as well:
https://github.com/KhronosGroup/SPIRV-Cross/pull/81

**Comment by billhollings** [comment]
@HansKristian-ARM 

Great!

I'm out of the office today...but should be able to give it a test in the next day or two.

Thanks!
