### ISSUE TITLE
Error with block namespace names conflicting with block names

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#780]
Here's the relevant spirv and resultant glsl files:
[SpirV.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2644763/SpirV.txt)
[Glsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2644764/Glsl.txt)

In the spirv there's two ssbos with the same buffer name. It looks like in spirv-cross this is handled around line 1560 when duplicate buffer names are found by using a fallback name based upon the variable's name. The problem is that if another variable already has this name it produces an error in glsl because I guess they're both in the global namespace.

**Comment by jodavis42** [comment]
I should add that my temp solution is to add:
`update_name_cache(resource_names, buffer_name);`
afterwards, but this doesn't seem like quite the right fix.

**Comment by HansKristian-Work** [comment]
Right, I found this passage in the GLSL 4.5 spec:

```
The block name (block-name) is used to match within shader interfaces: an output block of one pipeline
stage will be matched to an input block with the same name in the subsequent pipeline stage. For uniform
blocks, the application uses the block name to identify the block. Block names have no other use within a
shader beyond interface matching; it is a compile-time error to use a block name at global scope for
anything other than as a block name (e.g., use of a block name for a global variable name or function
name is currently reserved). It is a compile-time error to use the same block name for more than one
block declaration in the same shader interface (as defined above) within one shader, even if the block
contents are identical.
```
