### ISSUE TITLE
Large id bounds cause high memory usage and long initialization time

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/SPIRV-Cross#781]
In Compiler::parser() the value for the id bound is used to resize the ids and meta vectors. For low values of bound this is not problematic, but if the input file specifies a very high value this will cause a very large allocation. Additionally there is not guarantee that all of the data being allocated will ever be used, since this is just stating the largest id in use, not that the ids have been packed before hand.

The spec does call out keeping this bound as low as possible and packing ids is good practice, but there is no requirement that this occurs, so malformed/unoptimized inputs can cause issues. Potentially std::map is a more appropriate container for these values..

**Comment by billhollings** [comment]
Hmmm...presumably the reason the spec includes a `bound` in the preamble at all is so that the parser can preallocate collections accordingly.

I'm not sure an `std::(unordered)map` (I agree with preferring the `unordered` variant) would solve your concerns about unoptimized input. Are you referring to array slots that would contain empty content if not all ID's are used? In that case...an `std::(unordered)map` would also return empty content for any ID's not populated in the map.

I'm curious...what magnitude of memory overallocation are you encountering? How sparse is some of your ID content? And why is it coming in that way?

**Comment by dj2** [comment]
The issue we have is that we can't trust the input we've received, so our bound could be the maximum value, and only a handful of actual ids are in use. We have to assume that the input will be malicious and handle it accordingly.

Using a map means we only allocate for the id's which exist and not the theoretical maximum as specified by the bound in the preamble.

**Comment by dj2** [comment]
The values in the spec are the minimum limits. Implementations are allowed to support larger quantities.

**Comment by zoddicus** [comment]
Not being a security expert I cannot comment on if there is a data leaking attack, or other sophisticated attack, based around having a very large bound. But there is a simple denial of service if someone is feeding inputs, to the invoker of spiv-cross, with very large bounds. This is effectively what the fuzzer that found this is doing to itself. This is somewhat problematic, since the effort required on part of an attacker is not propotional to the effect on the use, since a trivial SPIR-V file with a very large id bound can cause the consumer to expend a large amount of memory and CPU on unused allocations.

Since we are moving from directly invoking spirv-cross to having spvc, which will invoke other validation/formatting passes before invoking spirv-cross, I have added an issue for adding compacting the ids to the passes it performs, see https://github.com/google/shaderc/issues/536. This should resolve the issue we are seeing here, since it will mean if spirv-cross is seeing a very large bound, those ids are actually referenced in the SPIR-V file, so need the allocation. Obviously an input could still have spurious/unused ids to bloat the bound, but other optimization passes should help in reducing those cases.

I agree that the minimizing the usage of iterating over the entire id space is still worthwhile, since it should help even in the common cases.

**Comment by HansKristian-Work** [comment]
Ok, We'll look into ID loop optimization as it's a general, good change.
Rewriting IDs in shaderc seems like a nicer approach than working around it in SPIRV-Cross. Thanks!
