### ISSUE TITLE
Support VK_KHR_shader_float16_int8 in Metal

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#783]
as Metal supports float16/half types..
@cdavis5e are you interested in possibly implementing support in MoltenVK also?

**Comment by cdavis5e** [comment]
Not to mention int8 types.

This extension must've been added in the latest version of Vulkan. I definitely remember seeing the `Int8` cap in the SPIR-V spec and wondering if I could do something about that. The `VK_AMD_gpu_shader_half_float` (this one's predecessor) extension was also on my list of things that could be implemented for Metal.

This doesn't seem particularly pressing, though, so it's probably going to have to wait until January when Hans-Kristian gets back.

**Comment by cdavis5e** [comment]
Actually... SPIRV-Cross already supports half-precision floating-point types. As far as you're concerned, nothing more needs to be done here.

I'm keeping the issue open for the purpose of adding support for int8 operations.

**Comment by HansKristian-Work** [comment]
Picking this up to add 8-bit arithmetic support for GLSL and MSL.
