### ISSUE TITLE
Need to handle FP rounding mode decoration

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#786]
OpDecorate %9 FPRoundingMode RTE

[rounding_mode_rte.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2670511/rounding_mode_rte.spv.txt)

**Comment by HansKristian-Work** [comment]
I'm unsure what the scope of this issue is. Do you need SPIRV-Cross to parse the decoration and set it accordingly so it can be reflected, or do you need codegen to respect that rounding?

The latter might not be possible as I cannot control rounding modes from GLSL.

**Comment by lifpan** [comment]
I just want SPIRV-Cross to parse the decoration and set it accordingly.
