### ISSUE TITLE
flatten_interface_block is too limited

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/SPIRV-Cross#79]
This library includes a function for flattening UBO for legacy GL targets (flatten_interface_block), but it only works if all members are of the same primitive type (so would work if all of them are float3 for example).

I'd like to change this - currently using SPIRV-Cross on our shader codebase isn't really practical for legacy GLES targets because of this (and even on GLES 3 there are bugs in some Adreno drivers that make using UBO problematic).

My understanding is that the biggest issue with this is that right now flattening can only rewrite the UBO declaration, which requires that SPIRV access chains are compatible between old and new layout. This may be solvable to an extent for simple cases, but ideally this would be generic.

I see two possible approaches for this:

1) Extend flatten_interface_block to be able to rewrite SPIRV access chains. I'm a bit wary of this approach but mostly because I don't have a good understanding of SPIRV yet and am not sure of what rewriting parts of SPIRV code involves.

2) Change flatten_interface_block to merely *mark* UB as "flattened", and extend GLSL generator to rewrite access chains. I did something along these lines once before, in an AST-to-GLSL translator:

https://github.com/zeux/hlslparser/commit/5a2106a754ac6b08fc4f017f26a3faea6b590a20#diff-8fa46791ec7a30a112f1575798cebc19R1311 (click "Load diff" to go to the important part)

The diff is a bit messy because I initially tried to generate a GLSL struct from a uniform buffer but it became apparent that supporting arrays is too inefficient with that approach even with glsl-optimizer running on the result - but it should give you the idea of what roughly I am aiming for. This approach results in generic UBO support that can respect whatever packing rules the UBO in question has, and is trivial to do immediate constant folding (https://github.com/zeux/hlslparser/commit/6b6b919ca3cf7eff9a602536bc6d8e3dfc2f00ba) on so that you can convert accesses like

    Lights[index].data.radius

to

    LightBuffer[5 * index + 4].w

for something like:

    struct Light {
        float4x4 transform;
        struct Data {
            float3 color;
            float radius;
        } data;
    };

Looking for some guidance & discussion on the above - does it seem like a worthwhile feature for SPIRV-Cross to adopt, what approach seems more promising, am I missing some complexities that this would involve due to the nature of SPIRV, etc.

**Comment by HansKristian-ARM** [comment]
Would it be better to change the UBO to a uniform struct instead? That's how SPIRV-Cross deals with push constant blocks atm, and it seems like a much better way to do it. flatten_interface_block is too limited in its current form, yes.

**Comment by billhollings** [comment]
`CompilerMSL::add_interface_struct()` attempts to do this for MSL, and that might make a reasonable starting reference point for this.

**Comment by zeux** [comment]
@HansKristian-ARM Uniform structs are unstable on some mobile drivers, sadly - some GLSL linkers don't work if you have the same struct in multiple shaders. Additionally, the problem with uniform structs for us is you can't set it in one glUniformfv call - it's not efficient.

**Comment by zeux** [comment]
@HansKristian-ARM float/int is not an issue in GLSL ES since int doesn't exist :) But yeah, that would still be a limitation.

**Comment by HansKristian-ARM** [comment]
Well, ints do exist in ESSL 1.0, just not guaranteed to actually be an int ...
```
#version 100
precision mediump float;
precision mediump int;

uniform int a;

void main()
{
	gl_FragColor = vec4(a);
}
```

Anyways, if uniform structs are not good enough and based on the current discussion, I'm thinking something like:

- If a UBO is compiled to legacy GLSL, by default, make it a uniform struct, this is the "correct" approach.
- As an optimization/workaround, flatten_interface_block will look at the struct type.
All basic types inside that struct including sub-structs must be the same, so mixing vec3, vec2, float, mat4 etc would be fine, mixing int, ivec2 etc would also be fine. If a mismatch is detected, exception is thrown. When declaring the struct, the UBO will be declared as a vec4 blob[ceil(blob_size / 16)].

On OpAccessChain, we add tracking of the base object + offset + dynamic offsets as well in the SPIRExpression. When trying to OpLoad from the access chain, we can see if the base object is a flattened struct, if so, use the offsets to generate array index + swizzle instead. Fortunately, we can make use of the fact that std140 UBOs have vec4 alignment for array access (we can throw exception is this doesn't hold).

**Comment by zeux** [comment]
@HansKristian-ARM Yup - this is basically what my plan is. And yeah, vec4 alignment for array access helps a lot for dynamic indexing. I'm not too familiar with SPIRV access chains yet, hoping that most of them end up at the primitive type - access chains that result in structs would have to be synthesized using struct/array constructors most likely.

I'm going to try and mock up something for this by changing CompilerGLSL::access_chain.

**Comment by zeux** [comment]
Added a WIP PR - this was surprisingly painless, I was worried that I'd have to analyze SPIRV deeper by coalescing access chains together to get longer ones, but at least for HLSL compiler the default access chains work really well as it is. My biggest source of confusion currently is the correct way to extract size information - I don't have a full understanding of why the type introspection is implemented the way it is (e.g. base Compiler has a method to get a struct member size, but not type size - CompilerMSL has one but I'm not clear on when there's a difference in semantics between querying size for a type vs for a struct member). Regardless, for now the PR is mostly to gather early feedback if any - I'm still working on this but wanted to share early progress.
