### ISSUE TITLE
[Metal] Vertex shader buffer bindings need to be incremented?

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/SPIRV-Cross#792]
In Metal, vertex buffers are passed to vertex functions via `[MTLRenderEncoder::setVertexBuffer](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515829-setvertexbuffer?language=objc)`. 

That same function is used to pass uniform data to a vertex function. Both the vertex buffers and uniform buffers are addressed using the same index. This creates the following problem. Consider the following input:

```
struct MeshVertIn
{
    float3 pos      : ATTRIB0;
    float3 norm     : ATTRIB1;
    float4 tangent  : ATTRIB2;
    float2 uv       : ATTRIB3;
    float2 uv2      : ATTRIB4;
};

struct MeshVertOut
{
    float4 pos : SV_POSITION;
    float2 uv;
    float2 uv2;
    half3 norm;
    half4 tang;
};

cbuffer Params : register( b0 )
{
    row_major float4x4 objViewProj;
    float meshScale;
};

MeshVertOut SimpleMesh_VS( in MeshVertIn v )
{
    MeshVertOut o;
    o.pos = float4( v.pos * meshScale, 1.0f ) * objViewProj;
    o.norm = half3( v.norm );  //* u.obj33;

    o.tang.xyz = half3( v.tangent.xyz );  //* uniforms.obj33;
    o.tang.w = 1.0f;

    o.uv = v.uv;  // * u.uvMod.xy + u.uvMod.zw;
    o.uv2 = v.uv2;

    return o;
}

half4 MeshNormals_PS( MeshVertOut v ) : SV_TARGET
{
    return half4( 0.5f + v.norm * 0.5f, 1.0f );
}

//T: MeshVisNormals vs:SimpleMesh_VS ps:MeshNormals_PS
```

Note how the cbuffer uses register `b0`.

This SPIR-V generated by this input produces the following Metal code:

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct MeshUniforms
{
    float4x4 objViewProj;
    float meshScale;
};

constant float4 _204 = {};

struct SimpleMesh_VS_out
{
    float2 _entryPointOutput_uv [[user(locn0)]];
    float2 _entryPointOutput_uv2 [[user(locn1)]];
    float3 _entryPointOutput_norm [[user(locn2)]];
    float4 _entryPointOutput_tang [[user(locn3)]];
    float4 gl_Position [[position]];
};

struct SimpleMesh_VS_in
{
    float3 v_pos [[attribute(0)]];
    float3 v_norm [[attribute(1)]];
    float4 v_tangent [[attribute(2)]];
    float2 v_uv [[attribute(3)]];
    float2 v_uv2 [[attribute(4)]];
};

vertex SimpleMesh_VS_out SimpleMesh_VS(SimpleMesh_VS_in in [[stage_in]], constant MeshUniforms& _27 [[buffer(0)]])
{
    SimpleMesh_VS_out out = {};
    float4 _203 = float4(in.v_tangent.xyz.x, in.v_tangent.xyz.y, in.v_tangent.xyz.z, _204.w);
    _203.w = 1.0;
    out.gl_Position = float4(in.v_pos * _27.meshScale, 1.0) * _27.objViewProj;
    out._entryPointOutput_uv = in.v_uv;
    out._entryPointOutput_uv2 = in.v_uv2;
    out._entryPointOutput_norm = in.v_norm;
    out._entryPointOutput_tang = _203;
    return out;
}
```

Note that the second parameter of the vertex function received a `[[buffer(0)]]` annotation, which introduces a conflict: the index `0` refers to the vertex buffer that the shader uses (either that, or I am misunderstanding how passing vertex buffers to vertex functions works on Metal).

The way I have addressed this problem on my side is to go through all uniform buffers used by the vertex stage and add 1 to their binding numbers if the vertex function consumes a vertex buffer. However, I feel like SPIRV-Cross should be able to just do it for me. I'm willing to work on a PR for this, however first I would like to understand if there is anything I'm missing here.

**Comment by KenThomases** [comment]
Buffer 0 is not *necessarily* the vertex buffer. When using `[[stage_in]]` and a struct with `[[attribute(n)]]` fields, the mapping from buffers to vertex data is governed by the vertex descriptor of the Metal pipeline. That's set using the `vertexDescriptor` field of the `MTLRenderPipelineDescriptor`. It can map from arbitrary buffers to the fields of that struct. So, the same shader code can be used with different buffer configurations and, likewise, a given buffer configuration can be used with different shaders and shader-language vertex data structures. One just has to make sure the field attributes track where you want the data to end up.

**Comment by nicebyte** [comment]
Thanks for the clarification, I completely forgot that Metal allows to assign bindings to vertex buffers via attribute descriptors. This makes things much easier; for example one could allocate vertex buffer bindings starting from 30, then 29, 28, etc., to avoid conflicting with "uniform buffer" bindings.

**Comment by nicebyte** [comment]
I've tried the above approach and it seems to work, so I'm closing the issue.

**Comment by minggo** [comment]
Why not set to buffer 0? Now i want to use the tool to translate to MSL in runtime, and i don't know what's suitable buffer index to set to vertex buffer.

**Comment by nicebyte** [comment]
i assume there's some abstraction layer between your code and the platform-specific graphics api, you can always do binding translation there (i.e. map "virtual" vertex buffer binding 0 to metal vertex buffer binding 30)

**Comment by minggo** [comment]
Yep, there is an abstraction layer. But how to know should bind to 30? May be 30 is used in MTL shader. My problem is how to bind to a safe index.

**Comment by luigifcruz** [comment]
@nicebyte Just for clarification, did you use the `VertexAttributeDescriptorArray_bufferIndex` starting from a value greater than one? Because this is what I'm doing and `newRenderPipelineState` is segfaulting for some reason. I'm wondering if this is a Metal bug or expected behavior.

**Comment by nicebyte** [comment]
You can see what i did in https://github.com/nicebyte/nicegraf/blob/master/source/ngf-mtl/impl.mm#L1403.
I set the bufferIndex of the vertex attribute descriptor to `MAX_BUFFER_BINDINDS - <whatever binding number is specified in the shader>`.  Yes, it will have values greater than 1.

**Comment by luigifcruz** [comment]
Thanks! I found out the root cause. I was indexing the layout wrong. I used the same index for the attribute and layout of the vertex descriptor. The correct way was to use the bufferIndex for the layout index.
![image](https://github.com/KhronosGroup/SPIRV-Cross/assets/6627901/e9549b2a-93e5-4007-be98-5358cb8e6971)
![image](https://github.com/KhronosGroup/SPIRV-Cross/assets/6627901/880e5fe5-71cc-4ed8-a990-8df4f2c043f8)
