### ISSUE TITLE
Phi operations that swap values

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Cross#793]
[op_phi_swap.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2711472/op_phi_swap.spv.txt)
[op_phi_swap.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/2711463/op_phi_swap.zip)

In this shader, %35 and %36 are swapped. The output GLSL shader doesn't handle it correctly. Need to use a temp here.

         %35 = OpPhi %float %31 %25 %36 %33
         %36 = OpPhi %float %32 %25 %35 %33

**Comment by lifpan** [comment]
%35 and %36 are chained by 2 Phi operations. I suggest that detect this case and add a copy operation at end of the loop header block:

         %35 = OpPhi %float %31 %25 %36 %33
         %36 = OpPhi %float %32 %25 %39 %33
	 %39 = OpCopyObject %float %35

**Comment by HansKristian-Work** [comment]
Nice find. This is a pretty tricky case.
