### ISSUE TITLE
Differences between in BuiltInVertexId/BuiltInVertexIndex on different targets

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/SPIRV-Cross#794]
Hi,

currently spir-v cross blindly translates BuiltInVertexId/BuiltInVertexIndex without adjusting for the behavior of their source language.
On HLSL/DX the vertex index does not include the base vertex value, on GLSL/OpenGL/Vulkan it does include the base vertex value (for MSL and Metal i don't know).
With that, it either needs to add or subtract base vertex value from the index (on HLSL there is no base index as far as i know)

**Comment by HansKristian-Work** [comment]
So, in GLSL this is sort of supported by emitting a `uniform int SPIRV_Cross_BaseInstance` to deal with different semantics for InstanceID and InstanceIndex. I think we will need to do basically the same thing with HLSL. However, HLSL is a bit more finicky about uniforms vs cbuffers, etc. Is it okay to just declare a similar uniform for HLSL as well?

**Comment by TiemoJung** [comment]
The problem with a user provided uniform is that it can not be used with indirect draw calls. For GLSL there is the draw parameters extension that provides a the vertex index offset value of that draw call, that can be used.

**Comment by HansKristian-Work** [comment]
Right, indirect does complicate it, but I don't know if there's a suitable way to deal with this if HLSL does not expose similar builtins. I merged something which sources offsets from a cbuffer, but it would be hard to make that work transparently with indirect.
