### ISSUE TITLE
[MSL] textureGrad -> sample_compare translation doesn't work on macOS

### ISSUE THREAD

**Issue by tgjones** [KhronosGroup/SPIRV-Cross#796]
[Shader Playground link](http://shader-playground.timjones.io/d4ebf0e290f6b7fa4b8e95cabddb27b4)

This GLSL:

``` glsl
float sample_depth_from_function(texture2DArray uT, samplerShadow uS)
{
    return textureGrad(
        sampler2DArrayShadow(uT, uS), 
        vec4(0.1, 0.2, 0, 0.5),
    	vec2(0, 0),
    	vec2(0, 0));
}
```

is currently converted (via glslang) to this MSL:

``` c
float sample_depth_from_function(thread const depth2d_array<float> uT, thread const sampler uS)
{
    return uT.sample_compare(uS, float4(0.1, 0.2, 0, 0.5).xy, uint(round(float4(0.1, 0.2, 0, 0.5).z)), float4(0.1, 0.2, 0, 0.5).w, gradient2d(float2(0.0), float2(0.0)));
}
```

This is correct for iOS. However, as noted in the [Metal Shading Language Specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf):

> On macOS, for sample_compare functions, level is the only supported lod_options value (bias and gradient* are not supported), and lod must be a zero constant.

On macOS, changing the above MSL to the following makes it compile:

``` c
float sample_depth_from_function(thread const depth2d_array<float> uT, thread const sampler uS)
{
    return uT.sample_compare(uS, float4(0.1, 0.2, 0, 0.5).xy, uint(round(float4(0.1, 0.2, 0, 0.5).z)), float4(0.1, 0.2, 0, 0.5).w, level(0));
}
```

I don't know if there is precedent for compiling MSL differently for iOS and macOS?

(Of course, all this would probably be unnecessary if GLSL had a `textureLod` overload that takes a `sampler2DArrayShadow`...)

*Edit*: I was rather laser-focused on my particular usage for cascaded shadow mapping. The above “fix” for macOS of course only works when the gradient parameters are 0.

**Comment by billhollings** [comment]
Sigh. Okay...looks like Apple introduced that restriction (at least documented it) in MSL 2.1.

Yes...SPRIV-Cross can emit different code for macOS and iOS...but in this case...do we want to? 

Do we want to simply output a `level(0)` on macOS and have it silently render somewhat different than is requested by the shader...or do we let the compile error happen...and force the app to provide different shader code for the platform?

Thoughts, everyone?

**Comment by tgjones** [comment]
It’s not quite the same thing, but a similar translation happens the other way, from SampleCmpLevelZero in HLSL to textureGrad in GLSL:

https://github.com/KhronosGroup/SPIRV-Cross/issues/207

**Comment by HansKristian-Work** [comment]
So, there is a similar case for GLSL already. In HLSL, you can SampleCmpLevelZero for the Cascaded case. Unfortunately, there is no textureLod() for sampler2DArrayShadow, so I go the other way, detect a constant 0 LOD and turn that into a constant 0 gradient. We can do the opposite case for MSL. If the gradient is not possible to prove to be constant 0, we can bail. I don't think we should special case just iOS here unless proven to be vitally important for some obscure use case.

I'll get to it.

**Comment by HansKristian-Work** [comment]
Was simple enough to just check for macOS vs iOS so implemented that as well. Should be a best-effort implementation for our purpose.
