### ISSUE TITLE
Bug with GLSL shader compilation using varying matrix

### ISSUE THREAD

**Issue by mlfarrell** [KhronosGroup/SPIRV-Cross#797]
This stems from original issue for MoltenVk (https://github.com/KhronosGroup/MoltenVK/issues/432) which I was asked to create here instead.

Using any GLSL shader that has shader stage (vertex) outputs and fragment stage inputs that are matrices fail to generate valid metal shader code.  

Per Vulkan spec, this needs to be supported

```
Compilation failed: 

program_source:62:8: error: vertex function has invalid return type 'main0_out'
vertex main0_out main0(main0_in in [[stage_in]], constant UniformBufferObject& _27 [[buffer(0)]])
       ^
program_source:48:5: note: field 'OutBlock_localSurface2World' of type 'float3x3' (aka 'matrix<float, 3, 3>') declared here
    float3x3 OutBlock_localSurface2World [[user(locn0)]];
    ^
.
```

The test shader that I use to generate the error is quite long and ugly, but here it is:
https://gist.github.com/mlfarrell/aed71113f8213831b65c9691104f9373

**Comment by HansKristian-Work** [comment]
Ok, I reproduced it. Seems to only happen for I/O blocks, and not plain varyings.

**Comment by mlfarrell** [comment]
confirmed working.  thanks so much!
