### ISSUE TITLE
Support for OpMemoryModel Physical32 and Physical64?

### ISSUE THREAD

**Issue by ashleyharris-maptek-com-au** [KhronosGroup/SPIRV-Cross#798]
Our companies shader compilation pipeline is currently C++ -> LLVM -> (Inhouse assembly format similar to DXIR / LLVM / SPIRV) -> (inhouse assembly manipulation functions, done just in time on target hardware) -> GLSL. As part of expanding our platform support to Vulkan / DirectX / Metal I've been looking at replacing the inhouse components of our software with SPIR-V and using SPIR-V Cross to do the export.

However, while SPIR-V seems to supports the physical memory model and all the stuff that comes with it: pointers, pointer casting, pointer arithmetic, etc. SPIR-V cross doesn't. It only supports the logical memory model currently.

This is unfortunate, as LLVM relies heavily on a physical memory model for it's optimisation passes, and casting between pointers to types is very common in optimised LLVM bitcode. Our company put a lot of work into getting general LLVM -> (inhouse SPIRV-ish) -> GLSL compiling for our shader library, and I'd like to keep this functionality while using SPIR-V cross. C++17 standard library features have spread fairly heavily across our shader code base and we'd like to keep them. (We just can't use dynamic function calling, exceptions, or dynamic_cast - but they're typically avoidable anyway).

I notice no-one else has raised this issue or anything like it before, so before I get too far into writing this capability I'd like to get feedback on whether this fits into the project scope? Whether such shaders are so rare in the wild that it's not worth adding support for them? Or whether this belongs in a standalone tool / library.

I've played away on my own fork and have gotten some **extremely** trivial cases working. Here is a very contrived example that now seems to work:

```
; SPIR-V
; Version: 1.3
; Generator: Khronos; 0
; Bound: 28
; Schema: 0
               OpCapability Shader
               OpCapability Addresses
               OpMemoryModel Physical32 GLSL450
               OpEntryPoint Fragment %main "main" %pFragColour
               OpExecutionMode %main OriginLowerLeft
              ... DebugNames ...
               OpDecorate %Tarr8Tf32 ArrayStride 4
               OpDecorate %pFragColour Location 0
      %Tvoid = OpTypeVoid
   %Tf_Tvoid = OpTypeFunction %Tvoid
       %Tf32 = OpTypeFloat 32
      %Ti32u = OpTypeInt 32 0
    %Ti32u_8 = OpConstant %Ti32u 8
  %Tarr8Tf32 = OpTypeArray %Tf32 %Ti32u_8
%TppTarr8Tf32 = OpTypePointer Function %Tarr8Tf32
    %TppTf32 = OpTypePointer Function %Tf32
    %Ti32u_0 = OpConstant %Ti32u 0
    %Ti32u_1 = OpConstant %Ti32u 1
    %Ti32u_2 = OpConstant %Ti32u 2
    %Ti32u_3 = OpConstant %Ti32u 3
     %Tf32_1 = OpConstant %Tf32 1
     %Tf32_0 = OpConstant %Tf32 0
      %Tvec4 = OpTypeVector %Tf32 4
   %TppTvec4 = OpTypePointer Function %Tvec4
   %TpoTvec4 = OpTypePointer Output %Tvec4
%pFragColour = OpVariable %TpoTvec4 Output
       %main = OpFunction %Tvoid None %Tf_Tvoid
      %Lmain = OpLabel
         %10 = OpVariable %TppTarr8Tf32 Function
         %12 = OpInBoundsAccessChain %TppTf32 %10 %Ti32u_0
         %14 = OpInBoundsAccessChain %TppTf32 %10 %Ti32u_1
         %16 = OpInBoundsAccessChain %TppTf32 %10 %Ti32u_2
         %18 = OpInBoundsAccessChain %TppTf32 %10 %Ti32u_3
               OpStore %12 %Tf32_0
               OpStore %14 %Tf32_1
               OpStore %16 %Tf32_1
               OpStore %18 %Tf32_1
         %24 = OpBitcast %TppTvec4 %10
         %25 = OpLoad %Tvec4 %24
               OpStore %pFragColour %25
               OpReturn
               OpFunctionEnd
```

This used to generate:
```
#version 450

layout(location = 0) out vec4 pFragColour;

void main()
{
    float _10[8];
    _10[0] = 0.0;
    _10[1] = 1.0;
    _10[2] = 2.0;
    _10[3] = 3.0;
    // unimplemented op
    pFragColour = _10; // Compile error
}
```

(Remember this is a trivial example - our production shaders have considerably more casts / memcopies / etc.)  So while this example could be fixed by "oh array to vector - just construct and use a group of trivial access chain", we will need more complex support. OpStore to a pointer that came from an OpPhi is a common pattern while compiling c++ code using std::array<T>::iterator to SPIR-V, and OpLoad on a pointer that was OpBitCast from an integer and itself OpLoad'd from memory is how std::vector<T>::front() is represented in SPIR-V. (There needs to be user-supplied-hints needed to deal with the no dynamic allocation / no OpVariable in a loop restriction - but that's solvable.)

I've written a first pass at a part of the memory analyser based on part of our old in-house code, which follows the access chain, pointer reinterpret_cast, stores, copies, and loads, and now gives the following compilable code:

```
#version 450

layout(location = 0) out vec4 pFragColour;

void main()
{
    vec4 _25 = vec4(0.0, 1.0, 1.0, 1.0);
    pFragColour = _25;
}
```

I have an extremely pre-alpha version work-in-progress going here: https://github.com/ashleyharris-maptek-com-au/SPIRV-Cross/tree/nonlogical_memory_support

**Comment by cdavis5e** [comment]
I don't think it's possible to support this fully in HLSL, or GLSL without the `GL_NV_shader_buffer_load` extension; and even with that extension, I don't think arbitrary pointers to the `Function` or `Private` spaces will work. But since Metal has real pointers, it should be possible to support this in MSL. After all, MSL is just freestanding C++14 with some restrictions and some extra features for interacting with the Metal runtime from the GPU. The `Physical32` model might pose a slight problem, though: `sizeof(void *)` is supposed to be 4 there, but in MSL it's always 8.

I have a change outstanding (#807) that's definitely related and might help with this. It adds support for the `SPV_KHR_variable_pointers` extension. It's still within the logical memory model, but it should hopefully help you with some of the bits around pointers in the physical models.

**Comment by HansKristian-Work** [comment]
Physical32/Physical64 sounds too extreme to me. As @cdavis5e says, SPV_KHR_variable_pointers is as far as Vulkan will go today, and even that is really pushing it. You can dynamically select between pointers with that at least, but this is only MSL.

But GLSL cannot support any of this either way. I assume you must have had some complicated passes to get from LLVM with all the bells and whistles down to a pure logical addressing model ala GLSL. You'll probably have to get there with SPIR-V as well to get anywhere on GLSL/HLSL.

**Comment by HansKristian-Work** [comment]
Closing this. I don't see SPIRV-Cross supporting physical addressing mode.
