### ISSUE TITLE
Question: Getting back SPIR-V code after changes to decorations

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/SPIRV-Cross#814]
I see that `spirv_cross::Compiler` has member functions allowing to modify and add/remove (among others) decorations (bindings, locations, etc.). However i can't see a way to get SPIR-V code back with applied modifications. Since there's a possibility to override things, I suppose there's also a way to apply the changes into actual code.
Is it possible?

I found [similar question](https://github.com/KhronosGroup/SPIRV-Cross/issues/362), however a link posted in the answer is probably outdated.

**Comment by HansKristian-Work** [comment]
For modifying existing decorations, there is an interface, see https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L482. It is just indirect however. SPIRV-Cross does not serialize SPIR-V back out again. I think you'll need SPIRV-Tools in this case.

**Comment by Crisspl** [comment]
Ok, thanks, just na offset might be sufficient. Is there a way to get offset to specialization constant Op? Or, if you're familiar with SPIRV-Tools, is there a way to do so?

**Comment by HansKristian-Work** [comment]
No way to get offset to spec constant op, but why do you need that? You can replace the value in the spec constant using less awkward means using either the Vulkan API when calling create pipeline, overriding the define emitted by SPIRV-Cross in older targets, or replace it for cross-compile with get_specialization_constant() in the API. I don't know SPIRV-Tools well enough to answer that.

I don't think there is more I can answer for now, so closing.

**Comment by Crisspl** [comment]
We want to simulate shader specialization under OpenGL (unifying our engine's API under VK and GL). We're supporting Vulkan GLSL and SPIR-V as shader source input. And the idea for simulating the specialization under GL was to modify SPIR-V making it GL-compatible, then down-compile to GLSL and feed into GL (possibly omit downcompiling step if SPIR-V extension for OpenGL is available). But I think I already found out how to do it with SPIRV-Cross (however didn't implement yet). But seems like I'll always have to down-compile to GLSL because modifications are going to be done on `ParsedIR`.

**Comment by raphael10241024** [comment]
Is that still available now ? I want to chang my spirv code binding .
