### ISSUE TITLE
Question: specialization constants behavior under GLSLCompiler

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/SPIRV-Cross#817]
I have another small question. What will happen if SPIR-V input contains specialization constants instructions (i.e. OpSpecConstant) and `GLSLCompiler` compiles it with `Options::vulkan_semantics` set to false? I guess it will produce regular GL GLSL syntax (without `layout(constant_id = ...)`) with the constant equal to spec constant's default value? I'm about desktop OpenGL GLSL, so `Options::es` is also set to false.

**Comment by HansKristian-Work** [comment]
GLSL will declare const variables instead, and you can override the specialization constants by either using defines (`#define SPIRV_CROSS_CONSTANT_ID_10 100`) later, or replace the constants in the API before calling `CompilerGLSL::compile()`.

**Comment by HansKristian-Work** [comment]
No further comments, so closing.
