### ISSUE TITLE
MSL: Need to pad out fragment outputs

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Cross#819]
Details: https://github.com/KhronosGroup/MoltenVK/issues/447

**Comment by grovesNL** [comment]
Maybe this could be an optional component count instead of defaulting to 4? Portability implementations should probably try to derive this as mentioned, but for other users of SPIRV-Cross these might just be mistakes (i.e. wrote `vec3` instead of `vec4` in the shader unintentionally)

**Comment by HansKristian-Work** [comment]
Yes, I'll make this optional.
