### ISSUE TITLE
MSL: Wrong packing when using nested structs

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Cross#838]
I found a weird edge case where the packing code messes up in MSL:

```
struct Foo { float a, b, c; };
struct Bar { vec3 d; float e; };
struct Buffer { Foo foo; Bar bar; };
```
The Bar struct ends up with packed_float3 and float, meaning the natural alignment of the Bar struct becomes 4 and not 16, so offset of bar.d is 12, not 16.

Codegen currently doesn't seem to take into account natural alignment of structs for some reason.

Another case is that MSL doesn't seem to take into account the minimum alignment of 16 bytes for structs in std140.

**Comment by cdavis5e** [comment]
Wait, why is it using `packed_float3` for `Bar::d`? Did `Bar::e` wind up at offset 12 within `Bar`?

**Comment by HansKristian-Work** [comment]
Yes, that's how std140, std430 and HLSL packing work. MSL is the "weird" one where sizeof(float3) == 16.
