### ISSUE TITLE
Universal reflection api

### ISSUE THREAD

**Issue by andrejnau** [KhronosGroup/SPIRV-Cross#839]
I look for universal reflection api, but found just separate solution SPIRV(SPIRV-Cross), DXBC(D3DReflect), DXIL(d3dcompiler_dxc_bridge::D3DReflect), OpenGL(Program Introspection).
Would it be a good idea to have such an api? Do you know existing solution? May be SPIRV-Cross right now support this?

Of couse I can translate my HLSL source to SPIRV and use SPIRV-Cross, but I don't like this solution.
I think it will be slower than a native reflection. I'm not sure that I can get all the information I need to generate resource binding for DirectX 11, DirectX 12, OpenGL. I'm not sure that Constant Buffer layout will be the same for DXBC, DXIL, SPIRV, SPIRV to GLSL created from one HLSL file. And etc.

What you do think about universal reflection api on base SPIRV-Cross? Is it possible? Is it has chance to merge with SPIRV-Cross if it ever will be done?

**Comment by HansKristian-Work** [comment]
SPIRV-Cross will only consider SPIR-V. If you want to consider more formats, a "meta project" sounds more appropriate. I will not merge support for reflection of any other formats.

**Comment by HansKristian-Work** [comment]
Closing and rejecting. Feature will not be integrated in SPIRV-Cross.
