### ISSUE TITLE
Shared base_type_id in RWByteAddressBuffer

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#854]
Hi, it's been a while since I last filed a bug report, we've been happy with the SPIRV pipeline so far which is good :)

I'm having an issue when compiling shaders (SPIR-V to GLSL) that have multiple storage buffers of the same type. I originally put a bug in for a related issue https://github.com/KhronosGroup/SPIRV-Cross/issues/345 Based on a comment of yours it seems like spirv-opt reuses base_type_id, meaning multiple buffers can actually end up with the same index. This is a problem when a shader uses more than one buffer of the same type, such as RWAddressByteBuffers. Based on previous conversations with you it seems like this is the mapping of the names in glsl:

```glsl
layout(std430) buffer BlockName (from get_name(base_type_id))
{
    uint _m0[];
} InstanceName (from get_name(id));
```

When compiling our pipeline renames the base_type_id name to the id name so that shader reflection works using the OpenGL API (and another pipeline we have for a different platform). The glsl is fed directly to the driver and reflection happens through the API, I can't call any SPIRVCross function.

A simple repro would be the following

```hlsl
RWByteAddressBuffer MyFirstBuffer;
RWByteAddressBuffer MySecondBuffer;
RWByteAddressBuffer MyThirdBuffer;

[numthreads(1, 1, 1)]
void main()
{
	uint4 a = MyFirstBuffer.Load4(0);
	uint4 b = MySecondBuffer.Load4(4);

	MyThirdBuffer.Store4(0, a + b);
}
```

The reason I need to rename them is because I've enabled the StripDebugInfoPass. I could disable it, but then the output of this is the following which is also incorrect:

```glsl
layout(std430) buffer MyFirstBuffer
{
    uint _data[];
} MyFirstBuffer_1;

layout(std430) buffer MySecondBuffer_1
{
    uint _data[];
} MySecondBuffer_1_1;

layout(std430) buffer MyThirdBuffer_1
{
    uint _data[];
} MyThirdBuffer_1_1;
```

If by default the translated glsl did something like the following it would be enough for my purposes.

```glsl
layout(std430) buffer MyFirstBuffer
{
    uint _data[];
} MyFirstBuffer_1;

layout(std430) buffer MySecondBuffer
{
    uint _data[];
} MySecondBuffer_1;

layout(std430) buffer MyThirdBuffer
{
    uint _data[];
} MyThirdBuffer_1;
```

**Comment by HansKristian-Work** [comment]
It already emit code like this on master:
```
#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer MyFirstBuffer
{
    uint _data[];
} MyFirstBuffer_1;

layout(binding = 0, std430) buffer MySecondBuffer
{
    uint _data[];
} MySecondBuffer_1;

layout(binding = 0, std430) buffer MyThirdBuffer
{
    uint _data[];
} MyThirdBuffer_1;

void _main()
{
    int byteAddrTemp = 0 >> 2;
    uvec4 a = uvec4(MyFirstBuffer_1._data[byteAddrTemp], MyFirstBuffer_1._data[byteAddrTemp + 1], MyFirstBuffer_1._data[byteAddrTemp + 2], MyFirstBuffer_1._data[byteAddrTemp + 3]);
    int byteAddrTemp_1 = 4 >> 2;
    uvec4 b = uvec4(MySecondBuffer_1._data[byteAddrTemp_1], MySecondBuffer_1._data[byteAddrTemp_1 + 1], MySecondBuffer_1._data[byteAddrTemp_1 + 2], MySecondBuffer_1._data[byteAddrTemp_1 + 3]);
    int byteAddrTemp_2 = 0 >> 2;
    MyThirdBuffer_1._data[byteAddrTemp_2] = (a + b).x;
    MyThirdBuffer_1._data[byteAddrTemp_2 + 1] = (a + b).y;
    MyThirdBuffer_1._data[byteAddrTemp_2 + 2] = (a + b).z;
    MyThirdBuffer_1._data[byteAddrTemp_2 + 3] = (a + b).w;
}

void main()
{
    _main();
}
```

I fixed something like this some time ago.

**Comment by HansKristian-Work** [comment]
Actually, nvm, I forgot to test with spirv-opt ...

**Comment by HansKristian-Work** [comment]
The problem is that we need forced recompile so the names have changed between two runs, and it throws the naming off guard.

**Comment by redorav** [comment]
Works great - thanks for the quick turnaround
