### ISSUE TITLE
Question: what actually is composite constant?

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/SPIRV-Cross#859]
If I understand correctly, if `SPIRConstant::subconstants.size() > 0` then it is composite constant and doesn't hold a value itself, just IDs of its subconstants. However SPIR-V specification defines Composite as "structure, array, matrix or vector" (section 2.2.2 Types). But SPIRConstant has also member `SPIRConstant::m` which seems like to be value of matrix types (also used for vector types and single simple types).

So that I don't understand. When I want to give a constant of matrix type (let's say GLSL's `mat4`) new value using SPIRV-Cross, should i write to `SPIRConstant::m` or get subconstants IDs from `SPIRConstant::subconstants` (which will be columns, i.e. constants of vector type)?

**Comment by HansKristian-Work** [comment]
The subconstants are for arrays and structs. For matrices, the SPIRConstant contains all information for a matrix type. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_common.hpp#L960

**Comment by Crisspl** [comment]
Ok, thanks for clarification. Another question: does vector of specialization constants returned by `Compiler::get_specialization_constants()` contain **all** spec constants including those being subconstants for array/struct constants?

**Comment by HansKristian-Work** [comment]
get_specialization_constants should only return the scalar specialization constants which can be overridden from the API. In Vulkan, these can only be pure scalar values.

**Comment by Crisspl** [comment]
>get_specialization_constants should only return the scalar specialization constants which can be overridden from the API.

Let me make sure: Vulkan allows only scalar types (uint, int, float...) to be spec constants? I couldn't find such information (restrictions on type of specialization constant) anywhere so it's extremely helpful now.

**Comment by HansKristian-Work** [comment]
Only scalar types can be used with DecorationSpecId (99.9% sure) in Vulkan, you can create composite spec constants or spec constant ops in the SPIR-V module, sure, but from Vulkan's POV, you can only interact with spec constants which have SpecId set, and that's what SPIRV-Cross checks for when returning it in get_specialization_constants.

**Comment by Crisspl** [comment]
Ok, this is very helpful. Thank you :)
