### ISSUE TITLE
Allow SPIRV to GLSL push_constant struct to have layout specifier

### ISSUE THREAD

**Issue by Thomspoon** [KhronosGroup/SPIRV-Cross#887]
Hello,

I'm working with the following shader:
```glsl
#version 450
layout (push_constant) uniform PushConsts {
    mat4 view_proj;
} push;

... other shader pieces
```
which is converted via spirv-cross to GLSL:
```glsl
#version 310
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct PushConsts
{
    mat4 view_proj;
};

uniform PushConsts push;

... other shader pieces
```

Would it be possible to output a specific layout location for push constants? That way we can associate uniforms with our pipeline layout the same way we do attributes?

**Comment by HansKristian-Work** [comment]
So, had a look, and this is already possible. You can set the DecorationLocation decoration on the push constant block's ID, and it will show up. However, it requires version 430 on desktop GL, don't think you can use version 310 for layout(location = N) on uniforms. (That version does not exist, btw!)

**Comment by Thomspoon** [comment]
Hello! Thanks for the response. 

For the version, I grabbed an example from [here](https://github.com/KhronosGroup/SPIRV-Cross#converting-a-spir-v-file-to-glsl-es), which used 310. Might've been a typo!

Are you talking about something like this?
```
#version 450
layout (location = 0, push_constant) uniform PushConsts {
    mat4 view_proj;
} push;
```
That produces an error in `glslangValidator` when converting from glsl to spirv format.

**Comment by HansKristian-Work** [comment]
No, I mean, in the SPIRV-Cross API, you can modify the ID's location, so that when you actually disassemble, you get `layout(location = 0) uniform PushConsts push;` in the output.

**Comment by Thomspoon** [comment]
Ah, thanks for that! I was able to implement that into my project.
