### ISSUE TITLE
Building on Android < 26 (nl_langinfo not available)

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/SPIRV-Cross#891]
[This commit](https://github.com/KhronosGroup/SPIRV-Cross/commit/8255dd3ed6e6a5853c56850e0a214715c6d2aefd) added a codepath that uses `nl_langinfo` on platforms outside Windows, including Android. It seems that this function is only available on Android versions >= 26, but I was previously able to target a much lower minimum version (16). I am not an expert in Android build environments, so it is entirely possible that I should have configured things to exclude that code path. If not, and you still want to support Android < 26, then I think some build-time checks might need to be added to work around this.

**Comment by mellinoe** [comment]
BTW, here's what I see in the langinfo header in my NDK:

```C
#if __ANDROID_API__ >= 26
char* nl_langinfo(nl_item __item) __INTRODUCED_IN(26);
char* nl_langinfo_l(nl_item __item, locale_t __l) __INTRODUCED_IN(26);
#endif /* __ANDROID_API__ >= 26 */
```

**Comment by HansKristian-Work** [comment]
Ok, that was not intended. I'll add a fallback.

**Comment by mellinoe** [comment]
Thanks for the quick fix. I can confirm that the issue is resolved, and I'm able to build for Android 16 again.
