### ISSUE TITLE
CompilerCPP does not generate valid c++ for array constant expressions

### ISSUE THREAD

**Issue by hiddenbitious** [KhronosGroup/SPIRV-Cross#9]
Invalid c++ is generated for shaders that use constant expressions to initialize arrays.
For example in shaders/frag/constant-array.frag the generated cpp is this: 
```
vec4 indexable[3] = vec4[](vec4(1.0f), vec4(2.0f), vec4(3.0f));
vec4 indexable_1[2][2] = vec4[][](vec4[](vec4(1.0f), vec4(2.0f)), vec4[](vec4(8.0f), vec4(10.0f)));
```
While this is valid glsl, it is not valid c++.
I fixed this by redefining 
`virtual std::string constant_expression(const SPIRConstant &c);`
in CompilerCPP like this:
```
string CompilerCPP::constant_expression(const SPIRConstant &c)
{
	if (!c.subconstants.empty())
	{
		// Handles Arrays and structures.
		string res = "{";
		for (auto &elem : c.subconstants)
		{
			res += constant_expression(get<SPIRConstant>(elem));
			if (&elem != &c.subconstants.back())
				res += ", ";
		}
		res += "}";
		return res;
	}
	else if (c.columns() == 1)
	{
		return constant_expression_vector(c, 0);
	}
	else
	{
		string res = "{";
		for (uint32_t col = 0; col < c.columns(); col++)
		{
			res += constant_expression_vector(c, col);
			if (col + 1 < c.columns())
				res += ", ";
		}
		res += "}";
		return res;
	}
}

```

**Comment by HansKristian-ARM** [comment]
You must be a mind reader, was just thinking about this :p 
This does get quite tricky in C++11 with compounds.

There are other problems like not being able to assign arrays when I think about it. We might need std::array.

**Comment by hiddenbitious** [comment]
To be honest I didn't looked into the problem very thoroughly, but come to the above solution just to fix the specific problem that appears with the shader I mentioned before. Can you describe other cases that will cause problems?

**Comment by HansKristian-ARM** [comment]
Hm. So the simple case is
```
int foo[] = { 1, 2, 3, 4 };
Struct foo = { 1, 2, 3, 4 };
```
That should work for both structs and arrays. As well as arrays of them. I'm less sure about cases where you pass constant structs and arrays as function parameters though. Glslang won't currently hit those cases since parameters are first stored to a local variable before being passed in, but that will probably change.

```
#version 310 es
precision mediump float;
layout(location = 0) out vec4 FragColor;

vec4 foo(vec4 a[2])
{
   return a[0] + a[1];
}

void main()
{
   FragColor = foo(vec4[](vec4(10.0), vec4(20.0)));
}
```
I'm not sure if we can properly express the compound here since the array turns into a pointer in C++.

**Comment by hiddenbitious** [comment]
#13
