### ISSUE TITLE
Crash in spirv_cross::Meta::~Meta() on iOS

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/SPIRV-Cross#902]
Hello!

I am seeing the following crash when releasing spirv-cross compiler:

```
#0	0x000000010445a308 in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, unsigned int> > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, unsigned int>, void*>*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1547
#1	0x000000010445a1bc in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, unsigned int> > >::~__hash_table() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1503
#2	0x000000010445a16c in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, unsigned int>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, unsigned int> > >::~__hash_table() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1495
#3	0x000000010445a138 in std::__1::unordered_map<unsigned int, unsigned int, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, unsigned int> > >::~unordered_map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1370
#4	0x0000000104459968 in std::__1::unordered_map<unsigned int, unsigned int, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, unsigned int> > >::~unordered_map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1370
#5	0x000000010445a900 in spirv_cross::Meta::~Meta() at /git/DiligentEngine/DiligentCore/External/SPIRV-Cross/spirv_common.hpp:1381
#6	0x000000010445a8c4 in spirv_cross::Meta::~Meta() at /git/DiligentEngine/DiligentCore/External/SPIRV-Cross/spirv_common.hpp:1381
#7	0x000000010445a890 in std::__1::pair<unsigned int const, spirv_cross::Meta>::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/utility:312
#8	0x000000010445a854 in std::__1::pair<unsigned int const, spirv_cross::Meta>::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/utility:312
#9	0x000000010445a7d8 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, void*> > >::__destroy<std::__1::pair<unsigned int const, spirv_cross::Meta> >(std::__1::integral_constant<bool, false>, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, void*> >&, std::__1::pair<unsigned int const, spirv_cross::Meta>*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1732
#10	0x000000010445a7d0 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, void*> > >::destroy<std::__1::pair<unsigned int const, spirv_cross::Meta> >(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, void*> >&, std::__1::pair<unsigned int const, spirv_cross::Meta>*) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1595
#11	0x000000010445a7c0 in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta> > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, void*>*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1564
#12	0x000000010445a614 in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta> > >::~__hash_table() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1503
#13	0x000000010445a5c4 in std::__1::__hash_table<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::__unordered_map_hasher<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::hash<unsigned int>, true>, std::__1::__unordered_map_equal<unsigned int, std::__1::__hash_value_type<unsigned int, spirv_cross::Meta>, std::__1::equal_to<unsigned int>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned int, spirv_cross::Meta> > >::~__hash_table() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1495
#14	0x000000010445a590 in std::__1::unordered_map<unsigned int, spirv_cross::Meta, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, spirv_cross::Meta> > >::~unordered_map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1370
#15	0x00000001044599d0 in std::__1::unordered_map<unsigned int, spirv_cross::Meta, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, spirv_cross::Meta> > >::~unordered_map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:1370
#16	0x00000001044598a8 in spirv_cross::ParsedIR::~ParsedIR() at /git/DiligentEngine/DiligentCore/External/SPIRV-Cross/spirv_cross_parsed_ir.hpp:33
#17	0x0000000104da9a70 in spirv_cross::Compiler::~Compiler() ()
#18	0x0000000104ddc920 in spirv_cross::Compiler::~Compiler() ()
```

There is nothing special about how compiler is used as well as about the byte code it parses:

```cpp
std::unique_ptr<spirv_cross::Parser> pParser(new spirv_cross::Parser(std::move(spirv_binary)));
pParser->parse();
auto ParsedIRSource = pParser->get_parsed_ir().source;
std::unique_ptr<spirv_cross::Compiler> pCompiler(new spirv_cross::Compiler(std::move(pParser->get_parsed_ir())));
```

This code works fine on Windows, Linux and Mac, but on iOS it crashes. If both parser and compiler are not destroyed, the app continues successfully and runs as expected.

**Comment by HansKristian-Work** [comment]
This is very strange. Code looks fine. Unfortunately, I don't have an iOS device readily available, so I cannot reproduce right now. I can only provide a list of things to try:

- Can you try running with sanitizers enabled and see if anything shows up?
- Try dropping the move constructors.

**Comment by DiligentGraphics** [comment]
Thanks for the suggestions, below are some answers:
* This code works fine everywhere but on iOS, and I don't think it is related to the byte code it processes.
* I actually tried dropping move ctors, but the result was the same.
* This is my first attempt to enable the engine on iOS, so I have nothing to compare with
* As I mentioned, the same code works fine on Windows, Linux, and Mac with the same clang version. As far as I understand, SPIRV-Cross does not abuse global states, so it would be really hard to corrupt something
* I haven't tried this code in isolation yet, will be my next step.

I am pretty sure there is something wrong with the toolchain / compiler, so I was hoping that you could have some experience with building/running for iOS.

**Comment by HansKristian-Work** [comment]
I have little/no experience with iOS I'm afraid. MoltenVK ships on iOS, and I haven't heard any issues from anyone about this before. If it's a general SPIRV-Cross issue with iOS, I assume we would have seen it by now. At least for something so trivial. The reason I'm asking about sanitizers is that it might be able to catch any iOS-specific issues.

**Comment by DiligentGraphics** [comment]
Yeah, OK. As I mentioned, if I let parser and compiler leak, everything else works fine and the scene is rendered correctly through MoltenVK. Will keep investigating.

**Comment by DiligentGraphics** [comment]
I will actually reopen the issue for some time, maybe someone finds something similar.

**Comment by billhollings** [comment]
I'm not sure if this will help...

MoltenVK uses the `CompilerMSL(std::vector<uint32_t>)` ctor...which creates and destroys Parser inline...and before `compile()` is called.

Could there be some conflict in the passing of `ParsedIR`between `Parser` and `Compiler`...and the order in which the various objects are destroyed?

BTW...in your snippet...how is the selection of the appropriate `Compiler` subclass (I assume `CompilerMSL`) performed?

**Comment by DiligentGraphics** [comment]
> MoltenVK uses the CompilerMSL(std::vector<uint32_t>) ctor...which creates and destroys Parser inline...and before compile() is called.

I used to use this too, but I need to query `ParsedIR::Sorce` first. This other constructor does the exact same thing anyway.

> BTW...in your snippet...how is the selection of the appropriate Compiler subclass (I assume CompilerMSL) performed?

I do not use any subclass and create the instance of `spirv_cross::Compiler` that is used to get shader reflection.

> Could there be some conflict in the passing of ParsedIRbetween Parser and Compiler...and the order in which the various objects are destroyed?

At this point I am almost 100% convinced there is something wrong with the build itself: if I call 

```cpp
pParser.release();
pCompiler.release();
```

to leak the parser and the compiler, the app still crashes. If I replace unique ptrs with raw pointers, the app runs fine. This makes no sense to me and I can't understand why it only manifests in one place. 
@billhollings you certainly have a lot experience with setting iOS build, maybe you can remember something  weird like that? 
The only reasonable idea that I have is that there is some heap corruption that manifests itself this way.

**Comment by DiligentGraphics** [comment]
@HansKristian-Work @billhollings could you please try to run the following code on iPhone arm64? No matter what I do it throws an exception and causes a crash. It works fine on Mac.

```cpp
std::vector<uint32_t> spirv = {119734787, 65536, 524295, 35, 0, 131089, 1, 393227, 1, 1280527431, 1685353262, 808793134, 0, 196622, 0, 1, 393231, 5, 4, 1852399981, 0, 11, 393232, 4, 17, 8, 8, 1, 196611, 1, 310, 262149, 4, 1852399981, 0, 327685, 9, 1651469383, 1850305633, 100, 524293, 11, 1197436007, 1633841004, 1986939244, 1952539503, 1231974249, 68, 262149, 16, 1299477839, 3174505, 262215, 11, 11, 28, 262215, 16, 34, 0, 262215, 16, 33, 0, 196679, 16, 25, 262215, 34, 11, 25, 131091, 2, 196641, 3, 2, 262165, 6, 32, 0, 262167, 7, 6, 3, 262176, 8, 7, 7, 262176, 10, 1, 7, 262203, 10, 11, 1, 196630, 13, 32, 589849, 14, 13, 1, 0, 1, 0, 2, 4, 262176, 15, 0, 14, 262203, 15, 16, 0, 262167, 18, 6, 2, 262165, 21, 32, 1, 262167, 22, 21, 2, 262187, 21, 24, 0, 262167, 25, 21, 3, 262167, 29, 13, 4, 262187, 13, 30, 0, 458796, 29, 31, 30, 30, 30, 30, 262187, 6, 32, 8, 262187, 6, 33, 1, 393260, 7, 34, 32, 32, 33, 327734, 2, 4, 0, 3, 131320, 5, 262203, 8, 9, 7, 262205, 7, 12, 11, 196670, 9, 12, 262205, 14, 17, 16, 262205, 7, 19, 9, 458831, 18, 20, 19, 19, 0, 1, 262268, 22, 23, 20, 327761, 21, 26, 23, 0, 327761, 21, 27, 23, 1, 393296, 25, 28, 26, 27, 24, 262243, 17, 28, 31, 65789, 65592};
spirv_cross::Parser Parser(std::move(spirv));
Parser.parse();
```

**Comment by HansKristian-Work** [comment]
Thanks for creating a reduced test case.

**Comment by HansKristian-Work** [comment]
Tried sanitizers on Linux and macOS, and Valgrind. Nothing :( Extremely puzzling. Maybe there's a libc++ mismatch or something?

**Comment by billhollings** [comment]
@DiligentGraphics 

I added your code above to `SPIRVConverterSPIRVToMSLConverter::convert()` function within MoltenVK. I did not use the results...I just wanted a place that linked SPIRV-Cross. and just pasted it in ahead of code that runs a normal shader conversion.

I ran it on iOS 12 on an iPad Pro 10.5" and an iPhone X and did not encounter any crashes. I tried running in Release mode, and stepping through the lines above in Debug mode.

What iOS version and device are you running?

**Comment by DiligentGraphics** [comment]
@billhollings Thanks for looking into that. It looks like @HansKristian-Work was right about libc++ mismatch: spirv-cross-core uses `c++11`, while some other projects use `gnu++11`. Now trying to understand where this came from.

**Comment by DiligentGraphics** [comment]
So there indeed was a mismatch between c++ std libraries, however this did not seem to be causing any problems. `spirv-cross-core` was using the same std library as the project it was used in. Anyway, making sure that all project use the same `-std=c++11` did not really help.
There is something completely odd going on with the build: while debugging, I can't step into spirv-cross, while all other third-party projects (glsang, for instance) work fine and can be stepped through. I made sure all binaries are up-to-date by running clean rebuild several times...
I almost ran out of ideas what that could be...

**Comment by DiligentGraphics** [comment]
I also tried to add spirv-cross source files directly to the project where it is used, and I still see the same crash and unable to step into spirv-cross. This looks like a complete nonsense now.

**Comment by DiligentGraphics** [comment]
I guess I may be finally getting close to what may be going on here: the linker uses spirv-cross from MoltenVK library. This would explain why I can't step into or have weird crashes in stl containers.

**Comment by HansKristian-Work** [comment]
Aha! That's a very likely cause. So, I can see two scenarios here:
- You're linking MoltenVK statically, which in turn would pull in SPIRV-Cross statically, along with your checkout of SPIRV-Cross. That's a red flag, and would explain the mismatch.
- You're linking directly to MoltenVK dynamically, and the library might be exporting SPIRV-Cross symbols for some reason, which can cause a conflict. If that's the case, MoltenVK will need to ensure that it's built with -fvisibility=hidden, at least for SPIRV-Cross.

I think we can bypass symbol conflicts if we can override the namespace used by SPIRV-Cross in build time.

**Comment by DiligentGraphics** [comment]
@HansKristian-Work
> You're linking MoltenVK statically

I was originally linking statically with MoltenVK and now have no more doubts that it is exactly the problem: I removed all spirv-cross source from the project, and it still links successfully and runs with the same error. TBH, I completely forgot that MoltenVK also uses spirv-cross and static linking may cause problems. What I don't understand though is why linker does not error out with duplicate symbol defintion. It does not even spit out a warning, but rather silently uses whatever definition it wants (BTW spirv-cross goes before MoltenVK in the library list so I don't know why it likes MoltenVK better).

> You're linking directly to MoltenVK dynamically

I tried linking dynamically, but was not able to get it running https://github.com/KhronosGroup/MoltenVK/issues/548

> Surprised this is only a problem on iOS though.

On other platforms the engine is linked with Vulkan loader, so there are no problems. Being said that, on MacOS it was originally linking with MoltenVK (dynamic) directly and it worked fine.

> I think we can bypass symbol conflicts if we can override the namespace used by SPIRV-Cross in build time.

I was thinking about that too, but did not want modify spirv-cross. Maybe this can be defined during CMake configuration stage?

**Comment by HansKristian-Work** [comment]
It sounds like the best option would be if MoltenVK enables a define which overrides the namespace to something MVK specific when building SPIRV-Cross dependency. That way we avoid this problem in the future. @billhollings what do you think? I can add a hook to override the spirv_cross namespace to something private to MVK to avoid these collisions.

**Comment by billhollings** [comment]
I'm not sure I understand the proposal.

Are you saying you would add a macro in SPIRV-Cross that would allow the `spirv_cross` namespace to be defined to something else during the build of the containing library (in this case MoltenVK)?

If so...that sounds fine. I'll modify MoltenVK accordingly once that's ready. Or if you're on a roll..and need to do so for testing anyway...feel free to do it and submit a MoltenVK PR.

**Comment by HansKristian-Work** [comment]
Right, I'm thinking something like:

```
#ifndef SPIRV_CROSS_NAMESPACE
#define SPIRV_CROSS_NAMESPACE spirv_cross
#endif
namespace SPIRV_CROSS_NAMESPACE
{
}
```
And then MoltenVK can override as necessary. I can submit a PR when I get it working. I'll do this tomorrow.

**Comment by DiligentGraphics** [comment]
@HansKristian-Work It would be great if there was CMake variable to define the namespace:

```cmake
if(SPIRV_CROSS_NAMESPACE)
	set(spirv-compiler-defines ${spirv-compiler-defines} "SPIRV_CROSS_NAMESPACE=${SPIRV_CROSS_NAMESPACE}")
endif()
```

**Comment by HansKristian-Work** [comment]
Yes, I'll also add a CMake option for it.

**Comment by DiligentGraphics** [comment]
@HansKristian-Work Thanks! That fixes the issue, and so does linking against dynamic MoltenVL library (that I made to work). Now everything works fine!
