### ISSUE TITLE
Weird uniform block size reported in reflection

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/SPIRV-Cross#911]
I have a uniform buffer block that looks lile this

{ mat4; mat4[128]; uint[16] }

This should come up to 8320 bytes total.
But the reflection api reports 8512 bytes, which is 192 bytes more which just seems off to me.
Even when aligning for 256 or 512 bytes, that still comes up to 8448 or 8704.

Am I just mistunderstanding something about the std140 layout?

**Comment by HansKristian-Work** [comment]
The reflection API is correct. In std140 layout, uint[16] has an array stride of 16 bytes, i.e. uvec4, which pads out the size. 64 + 64 * 128 + 16 * 16 = 8512.
