### ISSUE TITLE
Using "unsafe" functions floods VC compiler output with warnings

### ISSUE THREAD

**Issue by sergeyreznik** [KhronosGroup/SPIRV-Cross#92]
As you probably know, functions like `sprintf`, `strcat` which being used are considered "unsafe" in VC compiler. Better to use something more "safe" or wrap this functions into defines for VC.

**Comment by HansKristian-ARM** [comment]
In this case it's fine though. The buffer size statically cannot be overflowed and snprintf cannot be relied upon due to old msvcrt versions.

Is #pragma warning disables fine here? I'd rather avoid special paths with the "safe" versions for MSVC.

**Comment by sergeyreznik** [comment]
@HansKristian-ARM 
Yes, of course
Nobody will ever notice this, if console will not be flooded with warnings :)

**Comment by HansKristian-ARM** [comment]
Ok, the MSVC build already has the -D_CRT_blabla define, I guess the real problem is when using the source files externally, will just move stuff to the source files instead.

**Comment by HansKristian-ARM** [comment]
Fixed.
