### ISSUE TITLE
MSL: Cannot resolve expression type.

### ISSUE THREAD

**Issue by chadlayton** [KhronosGroup/SPIRV-Cross#941]
The following HLSL - when compiled to spirv with DXC and then run through spirv-cross to generate MSL - fails in OpLoad:

    static float offsets[] = 
    { 
        0, 
    }; 

    float4 ps_main() : SV_TARGET0
    { 
        float result = 1.0; 
    
        for (int i = 0 ; i < 1 ; i++) 
        { 
            float x = offsets[i];

            if (x < 1) 
            { 
                x *= 2; 
            }

            float y = (x == 0) ? offsets [ i ] : offsets [ 0 ] ; 
        
            result += x * y ; 
        } 

        return result; 
    }

**Comment by HansKristian-Work** [comment]
Bug is that a OpAccessChain is consumed in a continue block, but the declaration of the access chain is not declared until the loop body is emitted.
