### ISSUE TITLE
Recompile Error on complex GLSL shader: "Over 3 compilation loops detected. Must be a bug!"

### ISSUE THREAD

**Issue by fuchstraumer** [KhronosGroup/SPIRV-Cross#953]
Failure occurs at L453 of spirv_glsl.cpp, when calling `compile()` on SPIR-V passed to the GLSL compiler.

SPIR-V assembly that causes the failure can be found here: https://gist.github.com/fuchstraumer/7bd2a40a056c2eaa2ab889792e8fbabd

Issue is caused by using variables returned from atomic add, irrespective of the sign of the variables used. The partially recompiled source can be found here: https://gist.github.com/fuchstraumer/b47eababc5f925d4c3cf863c72f713d4

This could well be an issue in the logic of the shader, as it's shown weird non-deterministic behavior. RenderDoc captures of it will show different results for the point light grid and point light index counter results each time the event is re-run by RenderDoc - not sure what causes this, but it could also be unrelated to this particular issue.

**Comment by HansKristian-Work** [comment]
The cross-compiled SPIR-V compiles fine now. Non-deterministic behavior sounds like an unrelated shader bug if anything. Ordering of atomics isn't deterministic.

**Comment by fuchstraumer** [comment]
I figured - that was probably a case of me providing a bit too much detail. Regardless, thanks for the quick fix!
