### ISSUE TITLE
Question: evaluation of specialization constant expressions

### ISSUE THREAD

**Issue by PrimozLavric** [KhronosGroup/SPIRV-Cross#962]
Does SPIRV-Cross provide the functionality to evaluate expressions that consist of specialization constants and literals?

Example:
```
layout (constant_id = 0) const uint constA = 3;
layout (constant_id = 1) const uint constB = 5;

layout (set = 0, binding = 0) uniform sampler samplers[1 + constA];
layout (set = 1, binding = 0) uniform sampler someData[(constA + 5) * constB];
layout (location = 0) in vec3 inColors[1 + constB];
```
Here I would like to evaluate array sizes by either using default values or values specified by the user.

**Comment by HansKristian-Work** [comment]
There is currently no way to evaluate specialization constants.

**Comment by HansKristian-Work** [comment]
Doesn't seem like there is more to do in this question issue, so closing.

Adding full specialization constant evaluation is a non-trivial task, and I'll need a strong case to consider adding it. Feel free to open a new issue if there is such a case.
