### ISSUE TITLE
OpArrayLength unimplemented for MSL

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/SPIRV-Cross#965]
OpArrayLength is useful when doing compute shaders to avoid passing an extra uniform with the size of the data. It is implemented in the GLSL but not handled in HLSL (with `GetDimensions`) and MSL.

MSL is annoying because it doesn't have a concept of length of a buffer. An option would be to introduce and extra constant buffer argument that will contain the length of the storage buffers  so that the application can pass it. This would be needed for WebGPU to support OpArrayLength. WDYT?

**Comment by HansKristian-Work** [comment]
ArrayLength is tricky in both targets, but I guess we need to implement it somehow. MSL will need cooperation with the host.

**Comment by HansKristian-Work** [comment]
HLSL is done, MSL will have to wait a bit.

**Comment by Kangz** [comment]
Thanks, that'll definitely help. Like you said MSL support will need collaboration with application.

**Comment by Kangz** [comment]
Thanks, I'll take a look at using it in Dawn shortly!

**Comment by Kangz** [comment]
Finally got around to implementing this and it works great (Dawn CL is [here](https://dawn-review.googlesource.com/c/dawn/+/9386)). This is super important because it will allow doing a spirv transform "shader sandboxing" by clamping array accesses, in particular unsized array accesses.

Thanks again :)
