### ISSUE TITLE
vulkan/comp/buffer-reference.nocompat.vk.comp invalid: Drops restrict qualifier

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Cross#967]
The vulkan/comp/buffer-reference.nocompat.vk.comp test case doesn't compile in Glslang.
The call to overwrite_node drops the restrict qualifier.

It includes code like this:

```
layout(std430, set = 0, binding = 0) buffer LinkedList
{
        restrict Node head1;
        restrict Node head2;
};
...
        restrict Node n = gl_WorkGroupID.x < 4u ? head1 : head2;
...
        overwrite_node(n, head1);  // n may alias head1
```
and the definition of overwrite_node:
```
void overwrite_node(out Node dst, Node src)
{
        dst = src;
}
```

Glslang fails to compile, with errors:

ERROR: shaders/vulkan/comp/buffer-reference.nocompat.vk.comp:33: 'restrict' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: shaders/vulkan/comp/buffer-reference.nocompat.vk.comp:33: 'restrict' : argument cannot drop memory qualifier when passed to formal parameter

**Comment by HansKristian-Work** [comment]
I believe this is a glslang bug, but I'll workaround it locally: https://github.com/KhronosGroup/glslang/issues/1764
