### ISSUE TITLE
Using OpImageSampleProjDrefExplicitLod emits an exception with Lod != 0

### ISSUE THREAD

**Issue by Joshua-Ashton** [KhronosGroup/SPIRV-Cross#976]
When the op `OpImageSampleProjDrefExplicitLod` is used on a `sampler2DShadow`, this error is emitted:

> SPIRV-Cross threw an exception: textureLod on sampler2DArrayShadow is not constant 0.0. This cannot be expressed in GLSL.

However, despite the sampler type showing as incorrect in the error (I am using a `sampler2DShadow` and not a `sampler2DArrayShadow`), this works fine in GLSL so it can be expressed despite the error saying other wise.

It does not appear to be against the specification to do so either:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureLod.xhtml

Cheers and any help is appreciated 😄

**Comment by cdavis5e** [comment]
But `textureLod()` doesn't exist for `sampler2DArrayShadow` or `samplerCubeShadow`. The check [here](../blob/fce83b7e8b0f6599efd4481992b2eb30f69f21de/spirv_glsl.cpp#L4759) is supposed to catch those two cases, but it appears to be triggering incorrectly. What SPIR-V are you running this on?

**Comment by HansKristian-Work** [comment]
Pretty sure this is an oversight. I'll check it out, won't need a repro case.

**Comment by Joshua-Ashton** [comment]
My use case was my own d3d9 to vk layer d9vk with pretty much any game that uses depth compare (ie. A Hat in Time etc.) I'll try and fish out a broken shader tomorrow.

**Comment by HansKristian-Work** [comment]
Ping @Joshua-Ashton. Did you get a repro case?

**Comment by HansKristian-Work** [comment]
Closing as there's been no repro.
