### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#977]
Hi,

Would be possible to have artifacts from travis and appveyor build?
Would be usefull as I bridge C# SPIRV-Cross support and having the C (dll, so and dylib) would required less job for me to build.

Thanks

**Comment by HansKristian-Work** [comment]
Just Travis should be enough since it also builds for Windows. Do you have any pointers on how to enable this?

**Comment by amerkoleci** [comment]
https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by HansKristian-Work** [comment]
Ok, I'll try to get this working.

**Comment by HansKristian-Work** [comment]
Should be fixed now. See https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/2019-05-14 which was autogenerated from a tag.
