### ISSUE TITLE
spvc_resources_get_resource_list_for_type issue

### ISSUE THREAD

**Issue by amerkoleci** [KhronosGroup/SPIRV-Cross#981]
While bridging from C# I saw that resource_list is required and allocated from the method, its necessary to know the size first, so maybe making it options will be allowed to get first the size then allocate the struct and send it the method.

**Comment by amerkoleci** [comment]
Similar to vulkan API:

uint32_t extCount = 0;
			vkEnumerateDeviceExtensionProperties(physicalDevice, nullptr, &extCount, nullptr);
			if (extCount > 0)
			{
				std::vector<VkExtensionProperties> extensions(extCount);
				if (vkEnumerateDeviceExtensionProperties(physicalDevice, nullptr, &extCount, &extensions.front()) == VK_SUCCESS)
				{
					for (auto ext : extensions)
					{
						supportedExtensions.push_back(ext.extensionName);
					}
				}
			}

**Comment by HansKristian-Work** [comment]
Hi, the resource list is an opaque type, which is allocated internally and owned by the context. Any bridge API should not know anything about the size of that type.

**Comment by amerkoleci** [comment]
Basically the PInvoke fails because from C# it does not how much is big the array inside:

[DllImport("cspirv_cross", CallingConvention = CallingConvention.Cdecl)]
        public static extern Result spvc_resources_get_resource_list_for_type(
            spvc_resources resources,
            ResourceType resourceType,
            out ReflectedResource[] resource_list,
            out IntPtr resource_size);

And the ReflectedResource is declared as:
public struct ReflectedResource
    {
        public uint Id;
        public uint base_type_id;
        public uint type_id;
        public System.IntPtr name;
    }
What I need is to allocate the ReflectedResource with the size of elements and then send it as pointer on native side.

**Comment by HansKristian-Work** [comment]
Ok, but isn't this a fairly common problem with C? Is there no solution for this? I'd like to avoid adding lots of new APIs if possible.

**Comment by amerkoleci** [comment]
I see, you can just keep the same API and make resource_list  optional and assing only is send, so I can have two calls from C#, one to get size and one to get both size and pointer.

**Comment by HansKristian-Work** [comment]
If I make that change, how does the signature change in pinvoke?

**Comment by amerkoleci** [comment]
As bellow:

`
public ReflectedResource[] GetResources(ResourceType resourceType)
        {
            unsafe
            {
                // Get size first.
                var result = spvc_resources_get_resource_list_for_type(Handle, resourceType,
                    null,
                    out var resource_size);

                // Get resources.
                ReflectedResource[] resource_list = new ReflectedResource[resource_size.ToInt32()];
                result = spvc_resources_get_resource_list_for_type(Handle, resourceType,
                    (ReflectedResource*)Unsafe.AsPointer(ref resource_list[0]),
                    out resource_size);
                //return new[] { resource_list };
                return resource_list;
            }
        }
`

And PInvoke entry:

`
[DllImport("cspirv_cross", CallingConvention = CallingConvention.Cdecl)]
        public static extern Result spvc_resources_get_resource_list_for_type(
            spvc_resources resources,
            ResourceType resourceType,
            ReflectedResource* resource_list,
            out IntPtr resource_size);
`

**Comment by HansKristian-Work** [comment]
That doesn't seem right. The argument is a double-pointer.

**Comment by amerkoleci** [comment]
It works as C# sends it as pointer, if you take look at vkEnumeratePhysicalDevices here it works same:

**Comment by HansKristian-Work** [comment]
If it's possible to use pointers, isn't it okay to take a pointer, and then convert that to an array in C# land after you have pointer + size?

**Comment by amerkoleci** [comment]
Ok fixed, the pointer logic works, you can see the changes here:
https://github.com/amerkoleci/SharpSPIRVCross/commit/7cc64742b2fda1c4ebce028ee758d94008e5ec22

**Comment by HansKristian-Work** [comment]
Great! Closing.

**Comment by amerkoleci** [comment]
Just quick note, Entry point: spvc_type_get_vector_size is not present in artifacts downloaded.

Not sure it was added after the release.
