### ISSUE TITLE
MSL code generation problem: Undefined type

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/SPIRV-Cross#987]
Hello.

I'm having an issue where MSL code generated for a particular shader doesn't compile, because of what appears to be a definition order issue when it comes to nested structs: Parent struct has another struct as a member, and that other struct is defined /after/ the parent struct.

I've included the original GLSL source code (which gets passed through `glslang` to generate SPIR-V) and the resulting MSL code (after passing SPIR-V through `SPIR-V Cross`).

In the MSL shader note `SHVectorRGB_1` is defined after its first use in `SHCoeffsAndWeight_1`.

GLSL: https://pastebin.com/x7AtdCM6
MSL: https://pastebin.com/KjSNEzmL

If you feel this is something I can easily fix myself, feel free to point me in the direction of the file/class/method that might be relevant and I can take a crack at solving it.

Additional information
-----
SPIR-V Cross version: d11665424d515e224509bfe9cb4bd7a4e90a3158
glslang version: https://github.com/KhronosGroup/glslang/commit/2dd4ab3a4acba413ca6fe7585dab1c149d028000

Code I'm using to compile GLSL->SPIR-V
```
glslang::TShader* shader = bs_new<glslang::TShader>(glslType);
shader->setStrings(&sourceBytes, 1);
shader->setEntryPoint("main");

SPtr<GpuProgramBytecode> bytecode = bs_shared_ptr_new<GpuProgramBytecode>();
bytecode->compilerId = VULKAN_COMPILER_ID;
bytecode->compilerVersion = VULKAN_COMPILER_VERSION;

EShMessages messages = (EShMessages)((int)EShMsgSpvRules | (int)EShMsgVulkanRules);
if (!shader->parse(&resources, 450, false, messages))
{
	bytecode->messages = "Compile error: " + String(shader->getInfoLog());
	goto cleanup;
}

program->addShader(shader);

if (!program->link(messages))
{
	bytecode->messages = "Link error: " + String(program->getInfoLog());
	goto cleanup;
}

program->mapIO();
program->buildReflection();

// Compile to SPIR-V
GlslangToSpv(*program->getIntermediate(glslType), spirv, &logger);
```

And to compile SPIR-V to MSL:
```
spirv_cross::CompilerMSL compiler((UINT32*)spirv->instructions.data, spirv->instructions.size / sizeof(UINT32));
spirv_cross::CompilerMSL::Options mslOptions;
mslOptions.msl_version = spirv_cross::CompilerMSL::Options::make_msl_version(2, 1);
mslOptions.argument_buffers = true;
compiler.set_msl_options(mslOptions);

spirv_cross::CompilerGLSL::Options glslOptions;
glslOptions.separate_shader_objects = true;
glslOptions.vulkan_semantics = true;

compiler.set_common_options(glslOptions);
std::string source = compiler.compile();
```

**Comment by HansKristian-Work** [comment]
I'll try to have a look at this tomorrow.
