### ISSUE TITLE
MSL code generation problem: Duplicate binding locations

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/SPIRV-Cross#988]
Hello.

I'm having another issue regarding MSL code generation that is causing members of argument buffers to have duplicate ID's. In particular this seems to happen for combined texture/sampler bindings. When combined texture/sampler pair is split into separate texture & sampler objects in MSL, the texture appears to be given the original binding location, while the sampler gets assigned (original binding location + 1). The problem happens when (original binding location + 1) binding is already used by something else, as is in my case.

I've included the original GLSL source code (which gets passed through glslang to generate SPIR-V) and the resulting MSL code (after passing SPIR-V through SPIR-V Cross).

In the MSL shader note `spvDescriptorSetBuffer0` argument buffer in which both `gNormalTex` and `gAlbedoTexSmplr` have the same ID 23. The issue is visible on other members of the buffer as well.

GLSL: https://pastebin.com/ZhDd3SC3
MSL: https://pastebin.com/8p0xDaB5

I'm using the same compilation settings as described in my other issue #987.

Again, if you feel this is something I can easily fix myself, feel free to point me in the direction of the file/class/method that might be relevant and I can take a crack at solving it.

**Comment by HansKristian-Work** [comment]
Right. I think you need to use the resource binding API here, which is intended to map set/binding to ids/bindings for MSL. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L53

For example, to map a sampler2D you would need to set msl_texture to the `[[id()]]` you want for the image part, and msl_sampler for the sampler part. Generally, I'd like to avoid having SPIRV-Cross hallucinate bindings here, handling all possible conflicts, so I recommend applications make their own mapping scheme to handle the differences in binding models.

**Comment by BearishSun** [comment]
Alright, sounds good, thank you.
