### ISSUE TITLE
Suggestion: emit #line statements for SPIR-V OpLine opcode

### ISSUE THREAD

**Issue by floooh** [KhronosGroup/SPIRV-Cross#989]
It would be useful if there's an option to emit ```#line``` statements in the generated source code guided by the SPIR-V OpLine  opcode.

With this, a shader-cross-compiler tool can map errors and warnings from the Metal- and HLSL-compilers back to the original source file (at least roughly).

For example:

The Metal compiler might generate warnings like this on a piece of generated Metal source code, such "is used uninitialized" cases don't generate a warning on the original GLSL when compiled with glslang:

```bash
test.metal:34:13: warning: variable 'param' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
test.metal:74:23: note: uninitialized use occurs here
        float4 _593 = param;
```

Manually adding random ```#line``` statements like this:
```cpp
        float _636 = _656;
#line 12 "bla.glsl"
        float4 param;
#line 13 "bla.glsl"
        if (_656 < 0.100000001490116119384765625)
```
...changes the warning output to:

```cpp
bla.glsl:13:13: warning: variable 'param' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
```

It seems that one ```#line``` statement needs to be emitted for each generated source code line, without one, the compiler seems to increment the internal line counter for each parsed source code line, and a ```#line``` statement just resets this counter.

**Comment by oscarbg** [comment]
+1!
just DXC recently gained OpLine support in SPIR-V backend..

**Comment by KenThomases** [comment]
Personally, this seems to me like it would be confusing and misleading. Among other things, the column number in the warning output you provide would not correspond to anything in the original source. Perhaps it would be better to add comments to the generated MSL to indicate the original source file and line number. Leave the `#line` out, so the warnings indicate the relevant part of the MSL code, but when the developer looks there, they see where that comes from in the original.

**Comment by floooh** [comment]
@KenThomases comments wouldn't be very useful since they are for "human consumption", the #line statements are for tools and IDEs. And the feature would be disabled by default in SPIRV-Cross so that the generated source file is still "human readable", the #line statements would have to be enabled through the compiler options.

For example: I have a shader-cross-compiler which takes a GLSL file as input, converts this to SPIRV and (among others) Metal or HLSL source code, which is then compiled to Metal or D3D11 byte code through the Metal and D3D compilers.

The intermediate Metal or HLSL source code may might even only exist in memory, and never on disc.

Any warnings and errors in the last step would be mapped back to the original GLSL file and displayed in IDEs, or text editors which know how to parse GCC or MSVC error messages. For instance in Xcode it looks like this:

<img width="641" alt="sokol-shdc-errors" src="https://user-images.githubusercontent.com/1699414/58381033-25b7f180-7fb9-11e9-9618-a352903e8d20.png">

Currently this only works for errors and warnings generated by the intitial GLSL to SPIRV-step, not by errors generated by the Metal and D3D compilers (for those the line information is lost and I all errors are mapped to the first line of a file). For this last step to work I need the information how the line numbers in the generated HLSL / Metal source code roughly maps back to the original GLSL source.

...even when the line mapping isn't 100% correct it's still better than having to "map" the line number manually, and not having column information at all is okay too.

**Comment by HansKristian-Work** [comment]
The solution is to make this an option I guess, whether to ignore OpLine or not in conegen.

**Comment by HansKristian-Work** [comment]
PR in flight. I made it opt-in to emit OpLine statements.

**Comment by floooh** [comment]
Wow that was quick :) I'll give it a whirl ASAP!
