### ISSUE TITLE
coherent/volatile/restrict/readonly/writeonly is not supported in GLSL ES 3.0

### ISSUE THREAD

**Issue by zhaijialong** [KhronosGroup/SPIRV-Cross#993]
These qualifiers of SSBO is not supported in GLSL ES 3.0, they are reversed keywords in GLSL ES 3.0.

spirv_cross dosn't check it when target GLSL ES 3.0, which will result in a compilation error.

**Comment by HansKristian-Work** [comment]
Was closing this issue intentional?

**Comment by zhaijialong** [comment]
@HansKristian-Work Yes, I'm sorry for openning this issue. I didn't realized SSBO is not supported in gles 3.0 when I openned this issue.

**Comment by HansKristian-Work** [comment]
Yup, that's what I thought. No problem.
