### ISSUE TITLE
QUESTION: Merging UE4 SPIRV-Cross branch changes?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#997]
Hi,
seems UE4 codebase is starting to diverge from SPIRV-Cross having custom fixes..
don't know if they plan to upstream changes to main repo here or not.. maybe you are aware of their work..
Also don't know if makes total sense to merge all their changes from their branch as is but their work seems worth looking for..
For example (needs to subscribe as Github Epic Games member):
https://github.com/EpicGames/UnrealEngine/commit/51d4798277ef10bd22321dda53c9d5f3b302bef7
commit message (Workaround SPIRV losing an array indirection in Metal tessellation shaders - not the best solution but enough to keep things progressing)
makes some change to spirv_msl.cpp..
this improvement seems like a bug in current SPIRV-Cross, but really I don't know..
Just saying.. :-)

**Comment by HansKristian-Work** [comment]
I'm not aware of UE4 using SPIRV-Cross. If there are issues they need to be reported to upstream.

**Comment by RCalocaO** [comment]
Hi Oscar, we're doing some R&D work to use DXC+SPIRV-Cross as you found out :) the plan is to use the code from the main repo, but currently we have to do some workarounds to get UE4 happy; once we have a working system we'll send back our fixes/workarounds.

**Comment by HansKristian-Work** [comment]
@RCalocaO that's cool! I'll close this issue for now, and await specific issues/PRs.

**Comment by oscarbg** [comment]
@RCalocaO that's good news.. surely it will help SPIRV-Cross in some way.. thanks for info..
