### ISSUE TITLE
GLSL: NV_ray_tracing support seems forgot shaderRecordNV.

### ISSUE THREAD

**Issue by ygxie** [KhronosGroup/SPIRV-Cross#999]
Hi guys-
We already have GLSL_NV_ray_tracing support but it looks that we forgot shaderRecordNV. It turns out to be nothing but enums if I search "ShaderRecordBufferNV".

**Comment by HansKristian-Work** [comment]
Seems like callable shaders are not supported. Ping @pmoursnv.
